### ISSUE TITLE
CI/CD support

### ISSUE THREAD

**Issue by fox1t** [sinclairzx81/typebox#10]
Hi @sinclairzx81 we at [HospitalRun](https://github.com/HospitalRun/hospitalrun-frontend) decided to base our data and db validation structure upon this library.

Would you mind if we make a PR to typebox to add GitHub actions for building and testing it automatically?

In addition to that, if you like also other automation as Coveralls or auto publish on npm just ping us.

**Comment by sinclairzx81** [comment]
Hi, glad to hear TypeBox is getting put to good use :) Also, thanks for the offer !

I have configured TypeBox for Travis CI which automatically builds and tests on [commits](https://travis-ci.org/sinclairzx81/TypeBox), but could be interested in moving to GitHub Actions if its generally preferred these days. I haven't used GitHub Actions before, but bringing CI closer to the repository sounds like a good idea. Do you have any pre-configured repository i could take a look at?

As for auto npm publishing, I'm ok manually publishing for the time being. Perhaps when TypeBox gets to a 1.0.0 release I may look into it then.

Many Thanks
S

**Comment by fox1t** [comment]
Of course we have. We usually have configured an action on every PR and every merge to master. Additionally we have also configured auto release on some repos. 
This one is for PR https://github.com/HospitalRun/hospitalrun-frontend/actions/runs/53028945
This is the configuration that we use: https://github.com/HospitalRun/hospitalrun-frontend/tree/master/.github/workflows

As I said we can make a PR to this project to add support only for the run on PR (so you can be sure that new contributors doesn't break anything) and on push/merge on master, since it is important for releases.

**Comment by sinclairzx81** [comment]
Hi, that looks great. Would appreciate the PR ! I'll retire the Travis CI back end once you're able submit it through.

Many Thanks!
S

**Comment by sinclairzx81** [comment]
@fox1t @tehKapa Thank you very much !
