### ISSUE TITLE
Type.Nullable()

### ISSUE THREAD

**Issue by nezouse** [sinclairzx81/typebox#100]
Hi, i recently started using the lib and current way to make a field nullable is to write `Type.Union([type, Type.Null()])`
which both isn't very readable and also doesn't produce the best possible schema under the hood.

The result right now is `anyOf([{"type": "type"}, {"type": "null"}])` which isn't really working for example with fastify-swagger.
The proper result should be `{"type": "type", "nullable": "true}`.

Would it be a good idea to add `Type.Nullable()` method?

**Comment by sinclairzx81** [comment]
@nezouse Heya,

I've added a OpenAPI section to the readme that includes information on dealing with OpenAPI's `nullable` property which you can read about [here](https://github.com/sinclairzx81/typebox#openapi)

While TypeBox can be used to create OpenAPI schemas, there isn't 1-1 alignment between both schema representations, and it's not feasible to support both specifications simultaneously. Hopefully the information provided here demonstrates how users can achieve this alignment downstream. 

I do get a lot of enquiries about OpenAPI support, hopefully this clears things up
Cheers
S
