### ISSUE TITLE
HELP: Using a unsafe type to describe enum string for OpenApi

### ISSUE THREAD

**Issue by elvince** [sinclairzx81/typebox#1007]
Hi,

I already read the different topics on Type.Enum that is not compliant to OpenApi and that we should use unsafe method.

I end up with something like this but infers do not work as expected
```
export enum MyEnum{
  AAA= 'A',
  BBB = 'B',
}

const StringEnum = <T extends Record<string, string>>(item: T) => {
  if (IsUndefined(item)) throw new Error('Enum undefined or empty');
  const values1 = globalThis.Object.getOwnPropertyNames(item).map(
    (key) => item[key],
  ) as string[];
  const values2 = [...new Set(values1)];
  const items = values2.map((value) => value);
  return Type.Unsafe<T[string]>({ type: 'string', enum: items });
};

const a =  Type.Object({
 EnumValue: StringEnum(MyEnum),});

type final = Static<typeof a>;

```

On my final type,  EnumValue has a type of unknown.

Can someone help me with this?
I'm expecting to have EnumValue with type "MyEnum" in the final type.

thanks,

**Comment by sinclairzx81** [comment]
@elvince Hi,

You can try the following. [TypeScript Link Here](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjgGoEA2ArhgOI0FQAmOyAqgHYDOBAZhjgBfOPygQQcAOQABHsC4kqBYFAD0MdBgBGEAB7SAUEfXq4AWivWbtu-YeOnz0+fxRFAcwCiXGlIAKZFw4X38ASldLZxjYuPijfholYgguPBgPLh8-EAAeZDgMfRgMLhYeOAAlDBJoFjyeTK8cJqzPOAAfOFydDCgAPgGA4FKQAC4UcMnOXgEMAoBtAGsMVAh+FABdAcQjODg63ngAQSoqdy9KgF44AIA3ajoeSYC2ry6e-z6ocMWt8Jwa67R60DA8AB0GHu-VQDyeQmBcEoYMYzBYEIAkjxLtl4WDwpEDkcmnAzlQAHLffo3O6g56vd7ZT69fp-AFAkEIyHQ2H4uic5EItGsLE8KkgH78jCE-ZwYCbAIougijHY7gsDD8RQYFgjMaEuAwAAWEgA7j0MBbvFAJFAAtIwlJkprtVxdXBoEVwFppETDmlSfTwUC4J4qBAdNRkMbgJCAPI6ABWtRgEM8GBg8bNXAAChJMLBUBSCCBwfqMCBwhDtVRSvaAqtUICkXGSxTG2s4ARKu6Yb9qyACGAAp3m4LRpWVmsAXKSfAtJhQwE5QdybjPDxpTxAQB+RBG7STaRMzzSERwcarsnnCU-LfBndwfdIRcYY+sqDn0RXg4HJDCHK-pQJmNBQOkaCYBC3B8IIARIBCiFvjgZT+JMiyIRC7oWrgmbbuEWwiJEgFRPEZHkRRUQcHwGakRR9EMQ4RjFJAsBFLkcAALKoE6exricJyhtIJzSFgcoAEKSUJ4miUYJHzigoYoNoEKJimJAwPBcrBpMG5OgE3FOsRkRGG+im3PgRCkHkb4bCguxmIeS6FLcSA6VxPEcSRQA)

```typescript
import { Type, Static, ValueGuard, TUnsafe } from '@sinclair/typebox'

// ------------------------------------------------------------------
// StringEnum (TS Enum)
// ------------------------------------------------------------------
function StringEnum<T extends Record<string, string | number>>(item: T): TUnsafe<T[keyof T]> {
  const AllStrings = (values: (string | number)[]) => values.every(value => ValueGuard.IsString(value))
  const AllNumbers = (values: (string | number)[]) => values.every(value => ValueGuard.IsNumber(value))
  if (ValueGuard.IsUndefined(item)) throw new Error('Enum undefined or empty')
  const values = globalThis.Object.getOwnPropertyNames(item)
    .filter((key) => isNaN(key as never))
    .map((key) => item[key])
  const type = (
    AllStrings(values) ? { type: 'string' } :
    AllNumbers(values) ? { type: 'number' } :
    { }
  )
  return Type.Unsafe({ ...type, enum: [...new Set(values)] })
}

// ------------------------------------------------------------------
// Usage
// ------------------------------------------------------------------
export enum MyEnum {
  AAA = 'A',
  BBB = 'B',
}

const T =  Type.Object({
  value: StringEnum(MyEnum)
})

type T = Static<typeof T> // type T = { value: MyEnum }
```
I've updated the code to generate a `type` descriptor if all enum values are either strings or numbers, I've also fixed the value mapping logic for handling numeric enum values. The inferred type should be `MyEnum` as given by the `T[keyof T]`.

---

Will close up this issue for now, but if you have any questions, feel free to ping on this thread.
Cheers!
S
