### ISSUE TITLE
TS2589: Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by vsviridov** [sinclairzx81/typebox#101]
I have a schema with multiple nested partial objects, and at some point in time I start getting this error at compile time.

Looks like the recursive type is getting too complicated to process...

**Comment by sinclairzx81** [comment]
@vsviridov Yes, there are recursion limits in TypeScript, so TypeBox can't work around these constraints It should be difficult to produce a type that pushes these limits out however...

Are you able provide a repro of the type?

**Comment by sinclairzx81** [comment]
The following implements a deeply nested data structure using partial. You can test the below [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZJCOxbwAonAC8KYQDoA8iIBWGEjAAUSAgC4tmbQDkAriBEYopgJQ4R1tLcfPXDxwSHx1-Fzd3Cnd5RWU4ABENGww9Q2MzC1DbAAUCWGACLlMVTzhvFO08gqKSspDK6uJa0pxyGJkFJXgAYWTfVP0jE3M4K0b85uKEsoqBqsnC6frs1Kal0xm2jq74gCF+nSGM0fH59dqe2dWFmuKr4JuL+7L22O64AEFD22ORrImd1Me2ugKmwJWYI2IO2sne8RyPzWi1qnw6VAcnGIijgMAwylMYGs+CIpAAPEJMBAqHAcgA+KIIWRwFlwfj8OBgOAAWjgCigUAysnIQA)

```typescript
import { Type, Static } from '@sinclair/typebox'

const E = Type.Object({ a: Type.Number(), b: Type.Number(), c: Type.Number() })
const D = Type.Object({ a: Type.Partial(E), b: Type.Partial(E), c: Type.Partial(E), })
const C = Type.Object({ a: Type.Partial(D), b: Type.Partial(D), c: Type.Partial(D), })
const B = Type.Object({ a: Type.Partial(C), b: Type.Partial(C), c: Type.Partial(C), })
const A = Type.Object({ a: Type.Partial(B), b: Type.Partial(B), c: Type.Partial(B), })

const P = Type.Partial(A)
function test(p: Static<typeof P>) {
    // p - correct
}
```
However, you can break the above by referencing a object recursively, see [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZJCOxbwAonAC8KYQDoA8iIBWGEjAAUSAgC4tmbQDkAriBEYopgJQ4R1tLcfPXDxwSHx1-Fzd3Cnd5RWU4ABENGww9Q2MzC1DbAAUCWGACLlMVTzhvFO08gqKSspDK6uJagEEy8ij+fjgVbTIoDCpXDE4MFjgWuFMYAAtgcfm4IpYIOA4ANyLgABMl8cmZghZ2BngXEbhtwY4MXdQMGBiZBSV4AGFk31T9IxNzJeyqSahWKCTKFS+VXyzVB9UBUJqsJwHVirzgACFPjofhl-lZGtCQaY3uD4cDaiTgmTCRT2k8XvFJppITi-lkCYjTOjSRyYVy4byidzkU9UfEcljcjTim1ZFQHJxiIo4DAxmYwNZ8ERSAAeISYCBUOA5AB8UQQsjgVrgXTgYDgAFo1pxoAMTI6Us7lAR2M0lew1uMMOISGM2OsMFxUJcMBh7T7dpAWGwRFHnVQOMBVdpZOQgA). Note that the following isn't actually possible to as `A` hasn't been defined before passed to partial, however it will cause infinite recursion in the type system.
```typescript
import { Type, Static } from '@sinclair/typebox'

const E = Type.Object({ a: Type.Number(), b: Type.Number(), c: Type.Number() })
const D = Type.Object({ a: Type.Partial(E), b: Type.Partial(E), c: Type.Partial(A), }) // E.c references A (invalid as A hasn't been defined yet)
const C = Type.Object({ a: Type.Partial(D), b: Type.Partial(D), c: Type.Partial(D), })
const B = Type.Object({ a: Type.Partial(C), b: Type.Partial(C), c: Type.Partial(C), })
const A = Type.Object({ a: Type.Partial(B), b: Type.Partial(B), c: Type.Partial(B), })

const P = Type.Partial(A)
function test(p: Static<typeof P>) {
    // p - incorrect - Type instantiation is excessively deep and possibly infinite.
}
```
I would need to see a repro of the type to provide additional help here. As a general rule of thumb tho, recursion and TypeScript type inference is generally something to avoid if you can help it. TypeBox does however provide a `Type.Rec(...)` method [here](https://github.com/sinclairzx81/typebox#Recursive-Types) that will let you define a recursive type, however mileage will vary depending on your data structure. JSON Schema validators can be a bit hit or miss with respect to handling recursive types, There is an open issue about this on the AJV repository you can read about [here](https://github.com/ajv-validator/ajv/issues/1709). Also note, `Type.Rec(...)` is currently in an experimental state.

**Comment by NallT** [comment]
@vsviridov I had the same issue when I upgraded from 20.4 to 20.5. I downgraded to fix.

**Comment by vsviridov** [comment]
I need to scrub my use-case off the business-specific terminology and then I'll provide a repo...

**Comment by sinclairzx81** [comment]
@NallT Thanks for noting you had some issues on `20.5`. There were some updates to `Record<K, T>` from `20.4` to `20.5`, so would be keen to get a bit more insight into the error you observed. Just keep in mind that TypeBox does mandate on newer revisions of the compiler (currently `4.3.5` and above), and TypeBox is quite dependent on how the TypeScript compiler handles inference from version to version. If I recall, the updates to `Record<K, T>` were dependent on inference changes in TypeScript.

If you're able to produce a repro also, would be keen to take a look.

**Comment by sinclairzx81** [comment]
The following is a fairly extreme deeply nested data structure with partial and record. Inference seems to be ok on compiler version `4.4.2` and `4.3.5` running locally. Had some troubles getting inference working on the TypeScript Playground running [here](https://www.typescriptlang.org/play?ts=4.2.3#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZGcZFhwSEdi3gA1DCRjQ4AXhTCAdAHkRAKx0wAFAllwnccQC5jmEwDkAriBEYULYAlFiOzqjuaJ6+-oEhYTLOcABeUaaxAUHBsuQ5cjIKSvCq6vAASoYeGCblOtAAJrbRNZnxoXDautD5sqUacABaVS3mVjb2cATu5TgiMzgkMxS9Mv3wyACMAEwAHCOmFta6k9PVJgAKBLDABFy2g8ErfWoDW9sA7AeeRxNIZ6Mrjc7s0drsnnkXmUUDsAGzfGq-E7-dKeIHEEHvD4Q-LrGHbACsCLGxzsKPO6Nu93esJxULeOwALMSkWSpqiapTMTsCXS1q8NjsAMws8bI9kU64Y6lMvl497bUWk04cy5Sqmg7ZCuUC-GbJV-CWA9Xc7bbHXQ94ABgN4oBpi5Mu2mwtDM2AE5bWz7WiTU6ra7BZt9kZRqyVZLgTKPYGYZsvqHDmLvarHaDg7Gtpt4YmfsmI8ao+nsc9+ZbNpsibnEfnyYXpenaaX5RXmdWSYafZy-enec3dVmRe3w3WHT2s4zMxXFcPa0ax0XB1OK16CwuG1nzf3y5sbbPlaPfYuKy7twyrZ7953U+OKwGz4KrSHziP50eN7v3VOrQmX3Ou2qx5Pt+OZ-geb7dkBJaQmW55VmB16Rh+VpNjBLZWm2CF2jeQF9mhA67kOWEpkhGpbBh34zsRa7vmRhHfvqV7YaR3JWlu+Hllae7UYekHIaeHFvO6l48RBgHIfegkbO6z5hv+OEbsJmbur+cngQBabIDJymgWpiH1mRKnKfBenMQZmLuqhuIDu6mGmSR5nUu6eHWZa7pEfZNF8YZk4Pig7pUZ5vHiYZ2p+VpjGiRp44Bcp3FBWJmnugJrlvLsIkJdFi7upJqUbLsslJupClkelma7KpRX6eupXguFuy6VVZk1ZiFXlSZTUOS11INeVdmdV5IWtS59L5R5A3BZpuy+VJKC7IFE2JeOuxhbNyC7JFmUla17F5XN8WLVlG4bZmHwZYd209blo0oB8hV5sVLHUmdp2VQ91W0Zid2nY173NZ9z3QXtyAfB1f1dQDzQfFZN0g-14ODZpoOneNCOTeOHwzcDHwLWjS2Lh8q3Y5tF1PVDu2wx8B140dZEfClsOwudNOXVD12wRssL3TWj2Oc0TOZrCb08x93mYlzgu-SL-1i9SQuC2D0sQ7L-MwxzKCwvDSuI+OsIjeryCwqj2vo4umuC7jJv4xuRuCyTLNk4bFMG7C1NW7T4sMwbBLM+7rOG+z8oEtzHYy0N1I+5mBLC6Hyvh80wdR1Lsc64u0dR4rKemxuBJq0HWtZ9bZEEvrQfG4XHsR1jsMEpbFf+wSRM1-bfuO7XUdu-Xbde-KjK+13fPIASgcDoyIevpXzR95mjIxxP-tjzPyfz47s8z5nK+D4yeejwXm-dVPpej+X++Q8gjLVwbjJ16fKvn03V8twPB-n87ved7f8fnz3A5Cv3n+aUZCPS0Qpx7yUdn-TMQo57gMHqAqBy9YEv2gVAjeSCz5Ch3iAve6C75CiPiAk+uCv5CkvvKIUN9iGaSFA-chT8AHjgoVAj+VDGE-0tNsf+rDFxCmAW8PYq5s5kU4ZmT4gii6Yj2KIxBvMX6fFEWg2RZ9thYP4TgpRd9CSiKIRor+2wyEDjNOIyeyAtSiPodwjcZpREsN0ZpZ0U4uF2PHNsPhgowHOOPF+cK8ZjH+wzD4mRosv7xinIo4JmlsxTnURE28BCGQ6NiceAx5ZKGeI-LQgiFj0l0TfgRWxSSPzsKEn4x2u5yqlMHt4taMCcmtUFpUl+QMa6NLPqojYMSw6aXiRsRJXTxwpP4a0vBU5hl6MzAU-px5YwXGJJpAMshZBUB8JwYgag4AwAwBoWwYB3D4CIKQAAPEITAEAqBwAuAAPieA4JIzg8TiCqGAAAhCYAgrz3lvI+d8r5vzPn-J+QCv5gKQVfPCMkJwwKoVAphaC2F0K4XPPBRChFqL4XosRWipFdyIVwCxfijFBLEXIuSESslhKKXfJJc4clmLKW0upZC+llKADaVoAC6JhxDIrxKgJ5dKBW0oZTilFzLBViqxYyvFEqZXipBVKoVsrFXYtxUyuVyrlUKqVdquVWr1UYpZZsTlqAeW6hSPyjVOqiV6stfq3VIrSVWqdcSh1NLnW2oRTa913qVWqo9T64FXq7XApZdsTlKRchAA) however.

<details>
  <summary>Click to expand!</summary>

```typescript
import { Type, Static } from '@sinclair/typebox'

export const Vector = Type.Object({
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number()
})

export const R = Type.Record(Type.Number(), Vector)

const Z = Type.Object({ a: R, b: R, c: R })

const T128 = Type.Object({ a: Type.Partial(Z) })
const T127 = Type.Object({ a: Type.Partial(T128) })
const T126 = Type.Object({ a: Type.Partial(T127) })
const T125 = Type.Object({ a: Type.Partial(T126) })
const T124 = Type.Object({ a: Type.Partial(T125) })
const T123 = Type.Object({ a: Type.Partial(T124) })
const T122 = Type.Object({ a: Type.Partial(T123) })
const T121 = Type.Object({ a: Type.Partial(T122) })
const T120 = Type.Object({ a: Type.Partial(T121) })
const T119 = Type.Object({ a: Type.Partial(T120) })
const T118 = Type.Object({ a: Type.Partial(T119) })
const T117 = Type.Object({ a: Type.Partial(T118) })
const T116 = Type.Object({ a: Type.Partial(T117) })
const T115 = Type.Object({ a: Type.Partial(T116) })
const T114 = Type.Object({ a: Type.Partial(T115) })
const T113 = Type.Object({ a: Type.Partial(T114) })
const T112 = Type.Object({ a: Type.Partial(T113) })
const T111 = Type.Object({ a: Type.Partial(T112) })
const T110 = Type.Object({ a: Type.Partial(T111) })
const T109 = Type.Object({ a: Type.Partial(T110) })
const T108 = Type.Object({ a: Type.Partial(T109) })
const T107 = Type.Object({ a: Type.Partial(T108) })
const T106 = Type.Object({ a: Type.Partial(T107) })
const T105 = Type.Object({ a: Type.Partial(T106) })
const T104 = Type.Object({ a: Type.Partial(T105) })
const T103 = Type.Object({ a: Type.Partial(T104) })
const T102 = Type.Object({ a: Type.Partial(T103) })
const T101 = Type.Object({ a: Type.Partial(T102) })
const T100 = Type.Object({ a: Type.Partial(T101) })
const T99 = Type.Object({ a: Type.Partial(T100) })
const T98 = Type.Object({ a: Type.Partial(T99) })
const T97 = Type.Object({ a: Type.Partial(T98) })
const T96 = Type.Object({ a: Type.Partial(T97) })
const T95 = Type.Object({ a: Type.Partial(T96) })
const T94 = Type.Object({ a: Type.Partial(T95) })
const T93 = Type.Object({ a: Type.Partial(T94) })
const T92 = Type.Object({ a: Type.Partial(T93) })
const T91 = Type.Object({ a: Type.Partial(T92) })
const T90 = Type.Object({ a: Type.Partial(T91) })
const T89 = Type.Object({ a: Type.Partial(T90) })
const T88 = Type.Object({ a: Type.Partial(T89) })
const T87 = Type.Object({ a: Type.Partial(T88) })
const T86 = Type.Object({ a: Type.Partial(T87) })
const T85 = Type.Object({ a: Type.Partial(T86) })
const T84 = Type.Object({ a: Type.Partial(T85) })
const T83 = Type.Object({ a: Type.Partial(T84) })
const T82 = Type.Object({ a: Type.Partial(T83) })
const T81 = Type.Object({ a: Type.Partial(T82) })
const T80 = Type.Object({ a: Type.Partial(T81) })
const T79 = Type.Object({ a: Type.Partial(T80) })
const T78 = Type.Object({ a: Type.Partial(T79) })
const T77 = Type.Object({ a: Type.Partial(T78) })
const T76 = Type.Object({ a: Type.Partial(T77) })
const T75 = Type.Object({ a: Type.Partial(T76) })
const T74 = Type.Object({ a: Type.Partial(T75) })
const T73 = Type.Object({ a: Type.Partial(T74) })
const T72 = Type.Object({ a: Type.Partial(T73) })
const T71 = Type.Object({ a: Type.Partial(T72) })
const T70 = Type.Object({ a: Type.Partial(T71) })
const T69 = Type.Object({ a: Type.Partial(T70) })
const T68 = Type.Object({ a: Type.Partial(T69) })
const T67 = Type.Object({ a: Type.Partial(T68) })
const T66 = Type.Object({ a: Type.Partial(T67) })
const T65 = Type.Object({ a: Type.Partial(T66) })
const T64 = Type.Object({ a: Type.Partial(T65) })
const T63 = Type.Object({ a: Type.Partial(T64) })
const T62 = Type.Object({ a: Type.Partial(T63) })
const T61 = Type.Object({ a: Type.Partial(T62) })
const T60 = Type.Object({ a: Type.Partial(T61) })
const T59 = Type.Object({ a: Type.Partial(T60) })
const T58 = Type.Object({ a: Type.Partial(T59) })
const T57 = Type.Object({ a: Type.Partial(T58) })
const T56 = Type.Object({ a: Type.Partial(T57) })
const T55 = Type.Object({ a: Type.Partial(T56) })
const T54 = Type.Object({ a: Type.Partial(T55) })
const T53 = Type.Object({ a: Type.Partial(T54) })
const T52 = Type.Object({ a: Type.Partial(T53) })
const T51 = Type.Object({ a: Type.Partial(T52) })
const T50 = Type.Object({ a: Type.Partial(T51) })
const T49 = Type.Object({ a: Type.Partial(T50) })
const T48 = Type.Object({ a: Type.Partial(T49) })
const T47 = Type.Object({ a: Type.Partial(T48) })
const T46 = Type.Object({ a: Type.Partial(T47) })
const T45 = Type.Object({ a: Type.Partial(T46) })
const T44 = Type.Object({ a: Type.Partial(T45) })
const T43 = Type.Object({ a: Type.Partial(T44) })
const T42 = Type.Object({ a: Type.Partial(T43) })
const T41 = Type.Object({ a: Type.Partial(T42) })
const T40 = Type.Object({ a: Type.Partial(T41) })
const T39 = Type.Object({ a: Type.Partial(T40) })
const T38 = Type.Object({ a: Type.Partial(T39) })
const T37 = Type.Object({ a: Type.Partial(T38) })
const T36 = Type.Object({ a: Type.Partial(T37) })
const T35 = Type.Object({ a: Type.Partial(T36) })
const T34 = Type.Object({ a: Type.Partial(T35) })
const T33 = Type.Object({ a: Type.Partial(T34) })
const T32 = Type.Object({ a: Type.Partial(T33) })
const T31 = Type.Object({ a: Type.Partial(T32) })
const T30 = Type.Object({ a: Type.Partial(T31) })
const T29 = Type.Object({ a: Type.Partial(T30) })
const T28 = Type.Object({ a: Type.Partial(T29) })
const T27 = Type.Object({ a: Type.Partial(T28) })
const T26 = Type.Object({ a: Type.Partial(T27) })
const T25 = Type.Object({ a: Type.Partial(T26) })
const T24 = Type.Object({ a: Type.Partial(T25) })
const T23 = Type.Object({ a: Type.Partial(T24) })
const T22 = Type.Object({ a: Type.Partial(T23) })
const T21 = Type.Object({ a: Type.Partial(T22) })
const T20 = Type.Object({ a: Type.Partial(T21) })
const T19 = Type.Object({ a: Type.Partial(T20) })
const T18 = Type.Object({ a: Type.Partial(T19) })
const T17 = Type.Object({ a: Type.Partial(T18) })
const T16 = Type.Object({ a: Type.Partial(T17) })
const T15 = Type.Object({ a: Type.Partial(T16) })
const T14 = Type.Object({ a: Type.Partial(T15) })
const T13 = Type.Object({ a: Type.Partial(T14) })
const T12 = Type.Object({ a: Type.Partial(T13) })
const T11 = Type.Object({ a: Type.Partial(T12) })
const T10 = Type.Object({ a: Type.Partial(T11) })
const T9 = Type.Object({ a: Type.Partial(T10) })
const T8 = Type.Object({ a: Type.Partial(T9) })
const T7 = Type.Object({ a: Type.Partial(T8) })
const T6 = Type.Object({ a: Type.Partial(T7) })
const T5 = Type.Object({ a: Type.Partial(T6) })
const T4 = Type.Object({ a: Type.Partial(T5) })
const T3 = Type.Object({ a: Type.Partial(T4) })
const T2 = Type.Object({ a: Type.Partial(T3) })
const T1 = Type.Object({ a: Type.Partial(T2) })
const T0 = Type.Object({ a: Type.Partial(T1) })
const P = Type.Partial(T0)

function test(p: Static<typeof P>) {
    const x = p!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a![0].x
    const y = p!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a![1].y
    const z = p!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!.a!
        .a!.a!.a!.a!.a!.a!.a!.a!.a!.a![2].z
}
```

</details>

@vsviridov Is this issue related to https://github.com/sinclairzx81/typebox/issues/99 at all? I note the suggestion there to potentially leverage generic functions to construct the `RecursivePartial<T>` type. There is a high likelihood that trying to infer recursive data structures may result in the `TS2589` error, let me know if these issues are related.

**Comment by sinclairzx81** [comment]
@vsviridov Just in case this issue is related to #99 , see reference implementation below and [here](https://www.typescriptlang.org/play?ts=4.2.3#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsgPJjEQB2BANuRQEYBWGJM5AClBJljAMAZxysOXANLBaAEzgBfOADN+IOAHIAAiNkkGBYFAD0MdBhYQAHpoCwAKEcmTcALQfPX7z99--AYE+zq4ASpwArlB6AG4YaJgAPMgAfCHuQZlZ2Tlujo4Y1pCwcOaYcOEkUbEYPARCjMkpcAC8KHCFMBjyIigSnDCJsioYUHAAqs0A-H3sA4lIjnDLcADaUnCycADWGKgQKhMAugBcE+tHHdZdPbOSg8OjE81LK28zlNTAdI2V1cBxOoNBjJfpcRKTFJpBxvN5nT40egg8YXaGKZpnWgYOJjOD5JwOQrFeAqCK0LjfWgVSLRAG1erERrIK43OS9ShzcHIPgCUbEURQgAUIhIAAsMCACPCAJRnP60wEM4BM5oIV7LEh0ETwMD8QT83ptMEwAB03RgUGEImFYolBBNut5QlE0pNUAwcgiJAwgsFBBIZDWu1QOEdYCO0taqvVsM1tG1cElYEwCjaYZN21kqZaRs5MBk8jgHwsJqoiMYgvlNSBjIYgrD0sj8JLZcpFYbeJhsOW7pgUSpSBNQ-9gdWwdOiYIyY9ShjihwCGUBHZPP1VulMd7-ZQLbz9b1fPXcGX1KqCvpwKajkU+JcGVyD8fOXSAElwAwJeaiJT0k+----HxOMEwANQGaBWh3TBSz3NUu2Waxm2ggA5CIQBYUZBWlLAY1QJCMBNVD0Mw7CYwAL3wwi0IwqAsOvDcCWA+AAFFIISAjjUFJAcWIb0REoypoDkQV2Ko4jaOwuAwK4aBI0UBimLgAARNjd3uLjjzOZicBYLScBILSlAUrV4AAYVU6DOKQKVlJ0s4lP0+yjMcRSACELI42DNLgUy7J8xyfOchxFIAQQ8mD1Oss5XL8mK4AMuB3PklyTPaNoqzpGtlTrEKGMcUlyURUpRBgQUYkYCIMDOfBvxIRIygwA4UBSSM4LeRTrEg8qGEqk0CAAQhNFhBpIQaBpNHjSFEfrVgABiOE1OrvZCIC6OUaT0Oh4oIWhaFWllugUWQYAgUpxVPISY0U1AuoqgjhpNUa+sGh7Jr4mb5pNG6727Brj16GBzrDQ9RFUCDAYwC6oAUeoMCu1KyNunqCKe8aHqet7prmhbEZ+2E9vgbY9oAdypLYCDkcryRnFgbohqCMFwEhLWoGNu3ZjnOa5lY8faiBwGAD8oBNOAQpgLpwBgAHTvdM8REh47TuAGBNBENnuY1zXu15lZgedXpJRuj8KdKU7kFwAAmABWAAOABODooH4YXr3xIA) for how you might approach creating a `RecursivePartial<T>` type. Just note that TypeScript needs to know the layout of the type prior to inference. TypeBox object properties are `const` so you can infer specifically on those (and TS knows where to terminate recursive inference), but for types like `Record<K, T>` where the properties for `K` are unknown in advance, TypeScript may spark a `TS2589` error. 

Reference `RecursivePartial<T>` type below.

```typescript
import { Type, Static, TOptional, TObject, TProperties, ObjectKind } from '@sinclair/typebox'

// ------------------------------------------------------------------------
// RecursiveType<T>
// ------------------------------------------------------------------------

export type RecursivePartial<T> = T extends TObject<infer U> ? TObject<{ 
    [K in keyof U]: U[K] extends TObject<infer U> 
        ? TOptional<RecursivePartial<TObject<U>>>
        : TOptional<U[K]>
}> : never  


export function RecursivePartial<T extends TObject<TProperties>>(schema: T): RecursivePartial<T> {
    const properties = Object.entries(schema.properties).reduce((acc, [key, prop]) => {
        const mapped = prop.kind === ObjectKind ? Type.Optional(RecursivePartial(prop)) : Type.Optional(prop) 
        return { ...acc, [key]: mapped }
    }, {} as TProperties)
    return Type.Object(properties) as RecursivePartial<T>
}

// ------------------------------------------------------------------------
// Implementation
// ------------------------------------------------------------------------

const Vector = Type.Object({
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number()
})

const E = Type.Object({ vertices: Type.Record(Type.Number(), Vector) })
const D = Type.Object({ a: E, b: E, c: E })
const C = Type.Object({ a: D, b: D, c: D })
const B = Type.Object({ a: C, b: C, c: C })
const A = Type.Object({ a: B, b: B, c: B })
const T = RecursivePartial(A)

function test(value: Static<typeof T>) {
    const x = value.a!.b!.c!.a!.vertices![0].x // Note: Recursion cannot extend into the Record
    const y = value.b!.c!.a!.b!.vertices![0].y //       type as the properties for the Record are
    const z = value.c!.a!.b!.c!.vertices![0].z //       not known in advanced by the TypeScript
                                               //       compiler. Attempts to recurse into it's
                                               //       properties may lead to TS2589 error.
}
```

Let me know if that helps

**Comment by sinclairzx81** [comment]
@vsviridov Will close off this issue as I've been unable to reproduce TS2589 in TypeBox locally through typical usage. If you can provide a repro for the issue later on, please feel free to reopen and I'll take a closer look.

Cheers
S
