### ISSUE TITLE
Use cases for exhaustive type guards?

### ISSUE THREAD

**Issue by aleclarson** [sinclairzx81/typebox#1012]
I'm curious why the type guards in TypeBox need to be exhaustive. Presumedly, it affects performance, so we should have a good reason. Shouldn't it be "enough" to check the type kind? TypeScript can ensure the rest, except in cases where the type was generated outside of TypeBox (but is there a real-world use case that actually does such a thing?).

**Comment by sinclairzx81** [comment]
@aleclarson Hi!

> I'm curious why the type guards in TypeBox need to be exhaustive. Presumedly, it affects performance, so we should have a good reason. Shouldn't it be "enough" to check the type kind? TypeScript can ensure the rest, except in cases where the type was generated outside of TypeBox (but is there a real-world use case that actually does such a thing?).

TypeBox actually has 3 Guard API:

```typescript
import { ValueGuard, KindGuard, TypeGuard } from '@sinclair/typebox'
```

- ValueGuard: JS value guards
- KindGuard: (Kind-Only) Non-Exhaustive Type Guard 
- TypeGuard: Exhaustive Type Guard

For performance, TypeBox uses the KindGuard when compositing types (It's much much faster). 

As for TypeGuard, TypeBox uses this internally as a pre-flight schematic check prior to compilation (and subsequent evaluation) of JS strings in TypeCompiler. Exhaustive checking here is preferred as it is used to help mitigate malformed schematics from being able to escape out of the emitted code (where TypeGuard checks each property that contributes to an emitted JS conditional expressions)

The TypeGuard is actually used in tandem with some compiler specific checks prior to compilation, and I have been mulling moving TypeGuard to be a component of the compiler submodule, but for now, both TypeGuard and KindGuard are offered as top level imports.

Hope this brings some insight!
S
