### ISSUE TITLE
How to achieve better errros for discriminated unions

### ISSUE THREAD

**Issue by AlbertMarashi** [sinclairzx81/typebox#1017]
I am aware there is an existing library for discriminated unions, but I am wondering if there is some kind of way to use the existing `Value.Parse` functionality such that it hints to the parser which item to use.

Zod had a proposed `switch` type which would effectively allow for the developer to determine switching logic for cases where there might be multiple or complicated discriminants.

Any plans to add something like this or be able to implement it using the existing systems?

eg:
```ts
Type.Switch(Type.Union([...]), value => {
  if (value.type === "Baz") return //do something
  return false // unknown union type
})
```

**Comment by AlbertMarashi** [comment]
Just found these PRs, which seem to be related:

- https://github.com/sinclairzx81/typebox/pull/1013
- https://github.com/sinclairzx81/typebox/pull/1015

**Comment by AlbertMarashi** [comment]
The kinda core issue here is that I get a very undescriptive error for union types:
```
Expected union value
Expected all values to match
```

**Comment by sinclairzx81** [comment]
@AlbertMarashi Hiya,

TypeBox doesn't support DiscriminatedUnion because they are not part of the Json Schema specification, however you can implement them manually. In the case of generating errors for them, you can override TypeBox's error generation function and intercept custom structures and create errors for them.

The following is an example of how you might approach this.

```typescript

import { SetErrorFunction, DefaultErrorFunction } from '@sinclair/typebox/errors'
import { Type, KindGuard, ValueGuard, TSchema, TUnion } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// Guard for DiscriminatedUnion
function IsDiscriminatedUnion(schema: TSchema): schema is TUnion {
  return (
    // the schema is union with discriminantKey property ...
    KindGuard.IsUnion(schema) && ValueGuard.IsString(schema.discriminantKey) && 
    // ... and where union only contains object types
    schema.anyOf.every(variant => 
      // ... where each variant has a literal string property matching the discriminantKey
      KindGuard.IsObject(variant) && KindGuard.IsLiteralString(variant.properties[schema.discriminantKey])
    )
  )
}

// Override the global error function
SetErrorFunction((param) => {
  const { schema } = param
  return IsDiscriminatedUnion(schema)
    ? `Expected either ${schema.anyOf.map(schema => schema.properties.type.const).join(', ')}`
    :  DefaultErrorFunction(param)
})


// Create Union with discriminantKey
const T = Type.Union([
  Type.Object({ type: Type.Literal('A'), value: Type.Number() }),
  Type.Object({ type: Type.Literal('B'), value: Type.String() }),
  Type.Object({ type: Type.Literal('C'), value: Type.Boolean() }),
], {
  discriminantKey: 'type'
})

// Test
Value.Parse(T, null) // Error: 'Expected either A, B, C'
```

Additional Information on SetErrorFunction can be found below

https://github.com/sinclairzx81/typebox?tab=readme-ov-file#error-function

Will close this one out for now

Cheers!
S

**Comment by Lonli-Lokli** [comment]
I must say I also have this problem with unions, is it possible to somehow split it and understand/display actual error for one case of union?

**Comment by AlbertMarashi** [comment]
It would be really nice if we could create custom types, that can extend from the built in typebox error handling

like how was kinda mentioned in
- https://github.com/sinclairzx81/typebox/issues/858

Like a user-defined type like `DiscriminatedUnion`, but we can some how get typebox to go through our internal code for how to parse them, with the ability for us to defer back to typebox for internal values.


So, in other words, something like:


```ts
const discriminated_union_kind = symbol("DiscriminatedUnion")
TypeBox.registerType({
  kind: discriminated_union_kind
  parse(Schema: typeof DiscriminatedUnion, value: unknown) {
    let discriminant = schema.discriminant

    if (!value[discriminant]) throw new Error("Discriminant key is missing from value, expected ...")

    // inefficient example
    const Subtype = Schema.anyOf.find(sub_schema => {
        sub_schema.properties[discriminant] == value[discriminant]
    })

    if(!Subtype) throw new Error("Discriminant key ... does not exist in schema")

    // else defer to typebox's internal handling
    return Value.parse(Subtype, value)
  }
)
```
