### ISSUE TITLE
String Enums?

### ISSUE THREAD

**Issue by AlbertMarashi** [sinclairzx81/typebox#1020]
From what I read, there doesn't seem to be a type for string enums?

```ts
export const StringEnum = <T extends string[]>(values: [...T]) => Type.String({
    type: "string",
    enum: values,
})
```

I had to do something like this, but unfortunately TypeBox doesn't recognise the enums fields as valid values for the enum.

I need the strings in this format since it works nicer with OpenAI

**JSON Schema**: https://json-schema.org/understanding-json-schema/reference/enum#enumerated-values.

I know its possible to achieve with a union, but I feel as if using allOf has some slightly different semantics to enum

Additionally, I don't think my code actually checks the enum values are valid when parsing

**Comment by sinclairzx81** [comment]
@AlbertMarashi Hi,

TypeBox doesn't currently support `enum` schematics as standard, but is going to be added in later revisions. For now you can use this the following type to achieve the same result..

https://github.com/sinclairzx81/typebox/blob/master/example/prototypes/union-enum.ts

```typescript
import { TypeRegistry, Kind, TSchema, SchemaOptions, Static } from '@sinclair/typebox'

// -------------------------------------------------------------------------------------
// TUnionEnum
// -------------------------------------------------------------------------------------
export interface TUnionEnum<T extends (string | number)[]> extends TSchema {
  [Kind]: 'UnionEnum'
  static: T[number]
  enum: T
}
// -------------------------------------------------------------------------------------
// UnionEnum
// -------------------------------------------------------------------------------------
/** `[Experimental]` Creates a Union type with a `enum` schema representation  */
export function UnionEnum<T extends (string | number)[]>(values: [...T], options: SchemaOptions = {}) {
  function UnionEnumCheck(schema: TUnionEnum<(string | number)[]>, value: unknown) {
    return (typeof value === 'string' || typeof value === 'number') && schema.enum.includes(value)
  }
  if (!TypeRegistry.Has('UnionEnum')) TypeRegistry.Set('UnionEnum', UnionEnumCheck)
  return { ...options, [Kind]: 'UnionEnum', enum: values } as TUnionEnum<T>
}
```
In future this type will be provided as an enhancement to the existing Enum type.

```typescript
const E = Type.Enum(['A', 'B', 'C'])
```
Will close off this issue for now as the above should achieve what you need (also feel free to rename the type as required)

Hope this helps!
S

**Comment by benevbright** [comment]
I think it should return `type: "string"` together as it's valid enum type. https://swagger.io/docs/specification/v3_0/data-models/enums/

**Comment by TastyPi** [comment]
@sinclairzx81 is `Type.Enum(['A', 'B', 'C'])` still planned? If so, is there an issue I can follow to track it?

**Comment by sinclairzx81** [comment]
@TastyPi Hi,

>  is Type.Enum(['A', 'B', 'C']) still planned?

Yes, it's happening. `Type.Enum(['A', 'B', 'C'])` expressed as `{ enum: ['A', 'B', 'C'] }` will be available in the next release.

> If so, is there an issue I can follow to track it?

There is nothing public to track at this stage. The next version of TypeBox has been developed under private repo (which is why the main repo has been a bit quiet lately) .. but I am pushing for a mid to late September release. There is a lot going in for the next version, including some interesting new features that will take advantage of the performance provided by TypeScript 7 native compiler. It will be a big release.

Stay tuned.
S
