### ISSUE TITLE
Support for custom 'clone' function

### ISSUE THREAD

**Issue by MNorgren** [sinclairzx81/typebox#1023]
I've created a custom Unsafe type to support my MongoDb records:

```
TypeRegistry.Set('ObjectId', (schema, value) => value instanceof ObjectId); // custom type check
export const IdSchema = Type.Unsafe<ObjectId>({ [Kind]: 'ObjectId' }); // custom type schema
export type Id = Static<typeof IdSchema>;
```

However, when I run `Value.Parse(MySchema, myObject)`, my ObjectId becomes a plain object with a buffer array, which is no longer supported by Mongo.

I want to be able to provide a custom function for TypeBox to use when cloning my IdSchema.

Maybe something like this would be super helpful?
```
TypeRegistry.Set('ObjectId', {
  check: (schema, value) => value instanceof ObjectId,
  clone: (schema, value) => new ObjectId(value),
});
```

**Comment by sinclairzx81** [comment]
@MNorgren Hi,

Have you considered using a Transform type for this?

```typescript
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'
import { ObjectId } from 'mongodb'

// --------------------------------------------------------------------------
// Id Type
// --------------------------------------------------------------------------
const Id = Type.Transform(Type.String({ pattern: '^[0-9a-fA-F]{24}$' }))
  .Decode(value => new ObjectId(value))
  .Encode(value => value.toHexString())

// --------------------------------------------------------------------------
// Embedded Id
// --------------------------------------------------------------------------
const T = Type.Object({
  _id: Id,
  x: Type.Number(),
  y: Type.Number()
})

// --------------------------------------------------------------------------
// Parse
// --------------------------------------------------------------------------
const D = Value.Parse(T, { _id: '67035559d8ca4385151a33e1', x: 1, y: 2 })

console.log(D) // { _id: new ObjectId('67035559d8ca4385151a33e1'), x: 1, y: 2 }
```
Unfortunately, it's not possible to add additional callbacks on the TypeRegistry (there are too many downstream things that would be implicated by this). 

With respect to parse, Keep in mind that the Parse function is intended to be a fixed pipeline of calls to Value.* functions and it is possible to construct your own parsing pipeline. You can use TypeBox's default Parse as a starting point.

https://github.com/sinclairzx81/typebox/blob/master/src/value/parse/parse.ts#L41-L57

Historically (prior to the introduction of Parse) users would need to construct parsing functions manually. The default Parse pipeline is the library recommended defacto approach, however specifying your own Parsing pipeline is still a valid option. In saying this though, I think using Transforms for parsing MongoID is likely going to be the easiest option.

Will close off this issue for now as there isn't anything I can action, but happy to field any questions on this thread.
Cheers
S
