### ISSUE TITLE
Converting `undefined` using an optional array schema returns `[undefined]`

### ISSUE THREAD

**Issue by hpeebles** [sinclairzx81/typebox#1029]
Hey!

I've just run into an issue where I have a schema of the form `Type.Optional(Type.Array(...))`, if I call `Value.Convert` using this schema and pass in a value of `undefined` it returns `[undefined]` whereas it should return `undefined`.

Here is a minimal failing test -

```
it('Should not convert optional array if input is undefined', () => {
  const T = Type.Optional(Type.Array(Type.Number()));
  const R = Value.Convert(T, undefined); // returns [undefined]
  Assert.IsEqual(R, undefined)
})
```

**Comment by sinclairzx81** [comment]
@hpeebles Hi!

> I've just run into an issue where I have a schema of the form Type.Optional(Type.Array(...)), if I call Value.Convert using this schema and pass in a value of undefined it returns [undefined] whereas it should return undefined.

Ah, this is interesting, but I'm not too sure this is a bug. The following is the current behavior for Convert.

```typescript
const T = Type.Object({
  value: Type.Optional(Type.Array(Type.Number()))
})

const R0 = Value.Convert(T, {  });                 // {}
const R1 = Value.Convert(T, { value: 1 });         // { value: [ 1 ] }
const R2 = Value.Convert(T, { value: 'hello' });   // { value: [ 'hello' ] }
const R3 = Value.Convert(T, { value: false });     // { value: [ 0 ] } - false conversion to 0
const R4 = Value.Convert(T, { value: null });      // { value: [ null ] }
const R5 = Value.Convert(T, { value: undefined }); // { value: [ undefined ] }
```

With only R0, R1, R3 returning valid values. Note that the invalid return values are permissible, as per the readme.

> ### Convert
>
> Use the Convert function to convert a value into its target type if a reasonable conversion is possible. This function may return an invalid value and should be checked before use. Its return type is unknown.

The conversion from `undefined` to `[undefined]` would be consistent with the other invalid values.

---

I am open to discussing this more, but would need to understand the rationales for changing this logic. What would be the  reason for treating `undefined` distinctly from other kinds of property values?

Let me know your thoughts!
Cheers
S

**Comment by hpeebles** [comment]
Thanks for the quick reply!

In my use case I'm fetching data from a remote source and parsing it to my schema using `Value.Parse(...)`, which rejects invalid data.

If my schema is
```
const T = Type.Object({
  value: Type.Optional(Type.Array(Type.Number()))
})
```

And the value I get back from the remote server is `{ value: undefined }`.

Then I'd expect the parsing to be successful and it should return the input as is.

If the schema didn't have the `Type.Optional` wrapper then I'd expect the parsing to fail.

**Comment by sinclairzx81** [comment]
@hpeebles 

> And the value I get back from the remote server is { value: undefined }. Then I'd expect the parsing to be successful and it should return the input as is. If the schema didn't have the Type.Optional wrapper then I'd expect the parsing to fail. If the schema didn't have the Type.Optional wrapper then I'd expect the parsing to fail.

Hmm, the thing is that Optional doesn't mean Undefined. Optional means a property key can be absent. Here is the distinction between Optional and Undefined from a Check perspective.

```typescript
// Optional

'prop' in obj                                     // ValueGuard.HasPropertyKey(obj, 'prop')

// Undefined

obj.prop === undefined                            // ValueGuard.IsUndefined(obj.prop)
```

I guess if the server is returning `{ value: undefined }` on the assumption that undefined means the same thing as optional, you could update the type definition to align to the server assumption. Here is the output for that.

```typescript
const T = Type.Object({                           // type T = { value: number[] | undefined }
  value: Type.Union([
    Type.Array(Type.Number()),
    Type.Undefined()
  ])
})

const R0 = Value.Convert(T, {  })                  // { }
const R1 = Value.Convert(T, { value: 1 })          // { value: [ 1 ] }
const R2 = Value.Convert(T, { value: 'hello' })    // { value: 'hello' }
const R3 = Value.Convert(T, { value: false })      // { value: [ 0 ] }
const R4 = Value.Convert(T, { value: null })       // { value: null }
const R5 = Value.Convert(T, { value: undefined })  // { value: undefined }
```

You could also wrap the interior `value` in an Optional to account for cases where the key may also be absent.

```typescript
const T = Type.Object({                           // type T = { value?: number[] | undefined }
  value: Type.Optional(Type.Union([
    Type.Array(Type.Number()),
    Type.Undefined()
  ]))
})
```
Does this help?

**Comment by hpeebles** [comment]
Ahhh right I see, that all makes sense now.

I'll see if I can modify the schemas to add the union with `Type.Undefined`.

I'm auto generating hundreds of them using `ts2typebox` so I'll dig into that to see what can be done.

Thanks for the help!
