### ISSUE TITLE
Cannot read property '$id' of undefined when using Type.Ref.

### ISSUE THREAD

**Issue by kevcodez** [sinclairzx81/typebox#103]
Hi,

I am trying to set up simple references, but running into some errors, when doing so.

```
const SchemaPortfolioId = Type.String({
  $id: 'portfolioId'
});

const PortfolioParamsSchema = Type.Object({
  hid: Type.Ref(SchemaPortfolioId)
});
```

Results in

> TypeError: Cannot read property '$id' of undefined\n    at TypeBuilder.Ref (/Users/grueneberg/Documents/Github/tresor-api/node_modules/@sinclair/typebox/typebox.js:294:28)

Typescript version: 4.4.2
Typebox version: latest
Using swc as transpiler

Any help is appreciated.

**Comment by sinclairzx81** [comment]
@kevcodez Hi, What output do you see when you `console.log(...)` the following
```typescript
const SchemaPortfolioId = Type.String({
  $id: 'portfolioId'
});

console.log(SchemaPortfolioId)
```
You should see something similar to...
```javascript
{ '$id': 'portfolioId', kind: Symbol(StringKind), type: 'string' }
```
Similarly you should see the following for `PortfolioParamsSchema`
```javascript
console.log(PortfolioParamsSchema)
{
  kind: Symbol(ObjectKind),
  type: 'object',
  properties: { hid: { '$ref': 'portfolioId' } },
  required: [ 'hid' ]
}
```
TypeBox will check for the `$id` when using `Type.Ref(...)` and sets the `$ref` property in the referenced type to the `$id` of the source type. Just make sure `SchemaPortfolioId` logs the correct output in the first code snippet.

Also, just double check you're on the latest version of TypeBox, there were some changes around `Type.Ref(...)` and `Type.Box(...)` in recent revisions of TypeBox. Unfortunately, I can't provide much assistance on `swc` as I'm not very familiar with the bundler, but would assume things should be ok.

**Comment by kevcodez** [comment]
Hi @sinclairzx81 - thanks for the quick reply.

It seems to be a problem with the ES6 export/import.

The `SchemaPortfolioId` is placed in a separate `common.ts` file an exported as constant. The `PortfolioParamsSchema` is in another file that imports the `SchemaPortfolioId` using ES6 import.

.file1
```js
export const SchemaPortfolioId = Type.String({
  $id: 'portfolioId'
}); 
```

.file2
```js

import  {SchemaPortfolioId} from './file1'


const PortfolioParamsSchema = Type.Object({
  hid: Type.Ref(SchemaPortfolioId)
});
```

**Comment by sinclairzx81** [comment]
@kevcodez Yeah, that looks like a problem with the ESM module resolution and not specifically related TypeBox. If you can just confirm that the following code still causes a problem, can probably close off this issue.

### file1
```typescript
export const SchemaPortfolioId = 'test'
```
### file2
```typescript
import  {SchemaPortfolioId} from './file1'

console.log(SchemaPortfolioId) // -> should still be undefined
```
There wouldn't be much TypeBox could do to resolve this issue. Might be worthwhile having a browse through the swc documentation to see if anything stands out relating to ESM module bundling.

**Comment by kevcodez** [comment]
This is getting very weird

```js
import { SchemaPortfolioId } from './common' -> undefined
const { SchemaPortfolioId } = require('./common') -> undefined
const { SchemaPortfolioId } = require('./common.ts') -> works
```

Anyway, this is not a TypeBox issue, but rather some flawed TS setup - thanks for helping me out.

**Comment by nik-lampe** [comment]
@kevcodez have you solved this issue on your side?

I stumbled into it myself, but using tsc.

**Comment by kevcodez** [comment]
@nik-lampe Multiple things here 

- we had a JSON schema with the same filename, like common.json and common.ts (typebox) -> renamed one of the two files
- Registered the schemas in fastify using `fastify.addSchema`
