### ISSUE TITLE
Need ability to order object keys

### ISSUE THREAD

**Issue by AlbertMarashi** [sinclairzx81/typebox#1038]
I'm working on a use-case involving AI generation of JSON structured data.

It's critically important for few-shot examples of data, to be ordered as it can confuse and affect the AI's ability to learn from examples.

My understanding is that JSON keys are technically sorted in raw text form, and that the `Type.Object` keys are also sorted in the order that they are defined.

However, JSON spec doesn't specify whether order should be kept, it's up to each language/library implementation.

My issue is that I have another service (database) sending JSON data in such a way that it does not preserve key ordering.

Is it possible to have something like `Value.Parse` use the Type's property ordering rather than the incoming data's ordering?

Are there any built in features that might help workaround this issue?

**Comment by sinclairzx81** [comment]
@AlbertMarashi Heya

> Are there any built in features that might help workaround this issue?

There is no built in functionality to enforce the sequence of object property keys. TypeBox will parse values retaining the sequence they are received. This said, it is possible to write a function to handle this sequencing which could be run following a successful Parse. The following loosely achieves this for TObject only.  

```typescript
import { Type, Static, TObject } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

/** Samples property keys from TObject to reconstruct a value with keys in same order */
function Ordered<Type extends TObject>(type: Type, value: Static<Type>): Static<Type> {
  const propertyKeys = globalThis.Object.getOwnPropertyNames(type.properties)
  return propertyKeys.reduce((acc, key) => {
    return key in value
      ? { ...acc, [key]: value[key] }
      : { ...acc }
  }, {}) as never
}

// ...

const T = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
})

const R = Value.Parse(T, { z: 3, y: 2, x: 1 })
const S = Ordered(T, R)

console.log('unordered', R)
console.log('ordered  ', S)

// unordered { z: 3, y: 2, x: 1 }
// ordered   { x: 1, y: 2, z: 3 }
```

The above could be extended to support other constructs, but would need to be handled external to TypeBox as property key ordering is currently considered out of scope.

Will close off this issue for now, but if you have any follow up questions, feel free to ping on this thread.

Hope this helps!
S

**Comment by AlbertMarashi** [comment]
@sinclairzx81 how would you approach something like `TUnion` - how would we find the inner object type representing that specific value?
