### ISSUE TITLE
A compatibility problem about Exponentiation Operator of BigInt

### ISSUE THREAD

**Issue by E0SelmY4V** [sinclairzx81/typebox#1041]
Hi, I am a big fan of this project.

But when I tried to use it in a ES2015 project, I noticed that it even can't be import by my code.
The reason why is that my Vite always try to translate [`BigInt('2') ** BigInt('64')`](https://github.com/sinclairzx81/typebox/blob/295f8d9e3994f04cd7d76c613da123d89e70c61d/src/value/hash/hash.ts#L60C49-L60C76) into `Math.pow(BigInt(2), BigInt(64))`, which will lead a `TypeError: Cannot convert a BigInt value to a number`, because it seems that `**` is not allowed in ES2015.

I found that this may be the only code (at least, in my current use) which is not compatible with old editions of ECMAScript, and the solution is also clearly: `BigInt('18446744073709551616'/* 2^64 */)` or something else, and then the problem solved.

So, how about trying to fix it?

**Comment by sinclairzx81** [comment]
@E0SelmY4V Heya, thanks for reporting.

I have published a fix for this on 0.33.17. If you pull the latest this issue should be resolved.

Cheers
S
