### ISSUE TITLE
String format check does not work correctly

### ISSUE THREAD

**Issue by somnicattus** [sinclairzx81/typebox#1043]
minimal reproduction:
```ts
import { Type } from '@sinclair/typebox';
import { Value } from '@sinclair/typebox';

console.log(Value.Check(Type.String({ format: 'uuid' }), crypto.randomUUID()));
// false
```

The result was same with `format: 'date-time'` and `new Date().toISOString()`. All formats do not work?

I also checked older versions and the result was same.

I also checked `pattern` option and it worked.

**Comment by Yohe-Am** [comment]
Looks like typebox doesn't support formats out of the box according to [this](https://github.com/sinclairzx81/typebox/issues/879#issuecomment-2127501422) comment by author. Comment includes solution for how to get it working.

**Comment by somnicattus** [comment]
@Yohe-Am

Thank you so much for informing!

I'll try to find or provide a package which includes standard JSON Scheme format assertions.

**Comment by somnicattus** [comment]
https://github.com/ajv-validator/ajv-formats may the currently best choice.

I will try to provide a compact package that connects `ajv-formats` and TypeBox's `FormatRegistry`.

**Comment by somnicattus** [comment]
I released https://github.com/somnicattus/typebox-formats, which provides formats from ajv-formats.

**Comment by somnicattus** [comment]
I found [a discussion and the answer about this issue](https://github.com/sinclairzx81/typebox/discussions/853)
