### ISSUE TITLE
Enum/union of literals from string array?

### ISSUE THREAD

**Issue by mnpenner** [sinclairzx81/typebox#105]
`Type.Enum` takes in a TypeScript non-const `enum` which is nice, but something like:

```ts
EnumFromArray(['ONE_WAY','ROUND_TRIP','AS_DIRECTED'] as const)
```

It would have JSON schema:

```js
const T = {
    enum: ['ONE_WAY','ROUND_TRIP','AS_DIRECTED'],
    type: 'string',
}
```

And TypeScript type:

```ts
'ONE_WAY'|'ROUND_TRIP'|'AS_DIRECTED'
```

I just discovered you can convert const arrays to union types like this:

```ts
const foo = ['A','B'] as const
type Bar = typeof foo[number]
```

So I think it should be doable.

I tried writing it myself:

```ts
const EnumFromArrayKind: unique symbol = Symbol('EnumArrayKind')
export function EnumFromArray<T extends readonly string[]>(values: T) {
    return {kind: EnumFromArrayKind, enum: values, type: 'string'}
}
```

But tsc doesn't seem to like the symbol:

![image](https://user-images.githubusercontent.com/1112998/132941667-9ac07693-4396-4543-bad1-6ec77655f1c5.png)

Not sure how to extend typebox properly.

**Comment by sinclairzx81** [comment]
@mnpenner Hi. It is possible to create kinds of types by composing `TSchema` types from TypeBox. Usually this involves writing a function that returns one of the `TSchema` types and an appropriate JSON schema representation for that type. So long as you return `TSchema` types that matches the expected schema from your function, things should work ok.

Looking at your example, an `enum` type of this kind may be best expressed as a union of string literals as TS enums are expressed in JSON schema the same way as unions of string literals, so ideally a explicit definition would look something like..

```typescript
const T = Type.Union([
    Type.Literal('ONE_WAY'),
    Type.Literal('ROUND_TRIP'),
    Type.Literal('AS_DIRECTED')
])
```
Below shows a couple of ways to express the above in a general way, one for unions of string literals and another using a synthetic enum. I would recommend the string literal version however.

### Union of String Literals 

TypeScript Link [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsgDLAwZQEA25AqgHbAQtwC+cAZlBBBwA5AAEAzsBYl6BYFAD0MdBgBGEAB7CAUNuWY4ASRYwI+KFIDmVGnXqt2LADzIAfHAC8iANoBpOFJwANYYqBC8KAC6AFwofpFwGBo0LAAm4nDiMBYslnAA-Cg2tAwu8a6xLBgAbrTcukmQsHwArtLEHHjZVsV2DhwuickYaRlZOZbeka4AFNUMLRjisd4AdOvIkQCUscj9zsam5j3UJfZsA27uCNpwd3AkHFlw9Kd2GV7z9IviqyAEYDmCwwnncaEwq16DCB3wwWy2t3uUAwMBaUE44Iwq32M1etgYGQIhJYqARXF0jxYz2Qni6Eyh50cM28wgA8gA5ACiAH0AOoAQQAmsIcMIAEqspjsgAi3OQYsMAAURSJ+bhudLDGLOQBhZCc6XCba6fQgmlefBEUhOU3hFCuIA)

```typescript
import { Type, Static, TLiteral, TUnion } from '@sinclair/typebox'

type IntoStringLiteralUnion<T> = {[K in keyof T]: T[K] extends string ? TLiteral<T[K]>: never }

export function StringLiteralUnion<T extends string[]>(values: [...T]): TUnion<IntoStringLiteralUnion<T>> {
    const literals = values.map(value => Type.Literal(value))
    return Type.Union(literals as any)
}

const T = StringLiteralUnion(['ONE_WAY', 'ROUND_TRIP', 'AS_DIRECTED'])

type T = Static<typeof T>
```

### Enum Version

TypeScript Link [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsgKIB2AriOdXQNIapYC+cAZlBCHAHIAAgGdgVEgBsCwKAHoY6DACMIADwEAoTYsx4YUcQHMAMsBgYoBSQHkwxCFREAeZAD44AXkQBtJnHE4AGtWCC4UAF0ALhQ-CLgMNQsqABMROBEDYzgAfhRGEBZUVzi3GKoMADdLOHZtRMhYbhoJByp9QypTc0trAtcEpIxU9IAKTM6jAEofCLdRyusaDBEYnwA6TeQIqZjKWhBnfEmzCytbe2BHF3cPBE04R7gSa-gIS+uvOEXJZZF1qAYFI0EgYUajAgkMjPKZeDyjJCbdaQ6E+EjRZ61OBTHAIdiwgjpY7GU69C5tG5uB5PQEwGhQdpoTDrAqjd4UuCEzlUVAE9IEHmaOqaF5OeDIL7Erqk86snwCGwAOQoAH0AOoAQQAmgIcAIAEo2ACqioAIirkPqAJIABV1gg1uBVpqt+ooAGFKKaBDttHI5NzrBAjBAaOkYBAopp-dGA8M6ChELGnnAlarNVqvgrlertbrk09DSbzZbbVmi2aLda7VgC49Hc7XR6vVmGy63Z6KN64MnhboMInvPgiKRnP2wig3EA)

```typescript
import { Type, Static, TEnum, TEnumKey,} from '@sinclair/typebox'

type StringLiteralOptions<T> = {[K in keyof T]: T[K] extends string ? TEnumKey<T[K]>: never }

export function StringLiteralEnum<T extends (string)[]>(values: [...T]): TEnum<StringLiteralOptions<T>> {
    const options = values.reduce((acc, c) => ({ ...acc, [c]: c } ), {}) as StringLiteralOptions<T>
    return Type.Enum(options as any) as any
}

const T = StringLiteralEnum(['ONE_WAY', 'ROUND_TRIP', 'AS_DIRECTED'])

// analogous to:
//
// enum T {
//    ONE_WAY = 'ONE_WAY',
//    ROUND_TRIP = 'ROUND_TRIP',
//    AS_DIRECTED = 'AS_DIRECTED' 
// }

type T = Static<typeof T>
```

Hope that helps
S

**Comment by sinclairzx81** [comment]
@mnpenner Will close off this issue, but feel free to reply with any follow on questions if you need.

Cheers
S

**Comment by mnpenner** [comment]
Thank you so much!

The `StringLiteralUnion` solution is working well so far. Part of the reason I wanted JSON Schema enums is because I think it might produce a better error message than anyOf/const when validation fails, but I haven't ran into that yet. If so, I'll try your other solution and see how they compare. Thanks again!

**Comment by sinclairzx81** [comment]
@mnpenner Hey, you're welcome.  Just on the schema representation, you can actually implement the `StringLiteralUnion` type with something like the following (without explicitly using TypeBox schema factory methods). The important thing is that the `TSchema` return type matches the expected validation rules of the schema, this way you will get static inference and composability of the type.

```typescript
type IntoStringLiteralUnion<T> = {[K in keyof T]: T[K] extends string ? TLiteral<T[K]>: never }

export function StringLiteralUnion<T extends string[]>(values: [...T]): TUnion<IntoStringLiteralUnion<T>> {
    return {
       enum: [...values],
       type: 'string',
    } as any // note: this is also ok. But just be aware that the properties of the
             // underlying schema will show the `anyOf` and not the `enum`. This
             // is generally ok if you don't need to reflect on the schema.
}
```
Good Luck! :)
