### ISSUE TITLE
Better support for `enum: T[]`

### ISSUE THREAD

**Issue by jonahsnider** [sinclairzx81/typebox#107]
A limitation in OpenAPI v3 means `const: T` doesn't work, and instead `enum : [T]` is recommended as an alternative.

The documentation only lists one way to get something similar to that:

```js
const T = Type.KeyOf(
  Type.Object({
    x: Type.Number(),
    y: Type.Number()
  })
);
```

Could there be better support for creating enums in the resulting JSON? Maybe by adding an overload to `Type.Enum()` to accept an array of literal values? Or allowing several values to `Type.Literal()`?

**Comment by sinclairzx81** [comment]
@jonahsnider Hi, the current approach for extending TypeBox to support specialized OpenAPI types is to create a function that returns the schema you need, and reinterpret as a TypeBox `TSchema` type. Consider the following example that returns a OpenAPI `enum` type (as per issue), but is reinterpreted as a TypeBox `TUnion<[...TLiteral]>`  type for static inference.

```typescript
import { Static, TLiteral, TUnion } from '@sinclair/typebox'

type IntoUnion<T> = {[K in keyof T]: T[K] extends string ? TLiteral<T[K]>: never }

export function CustomEnum<T extends string[]>(values: [...T]): TUnion<IntoUnion<T>> {
    return { enum: values } as any // Note: it's possible to return OpenApi
                                   // compatible schemas and reinterpret
                                   // as TypeBox TSchema types. This type
                                   // is not strictly JSON schema, but so
                                   // long as it validates with the same
                                   // behavior (as per OpenAPI spec), we deem
                                   // this safe.
}

const T = CustomEnum(['Foo', 'Bar', 'Baz'])

type T = Static<typeof T> // type T = Foo | Bar | Baz
```

Also, take a look at issue #105 which goes into a bit more detail on mapping types this way, and includes an example for implementing a `enum` type also. 

Hope that helps
S

**Comment by sinclairzx81** [comment]
@jonahsnider Going to close off this issue. Feel free to reply here if you have any problems or general questions on extending TypeBox in this way. 

Cheers
S

**Comment by jonahsnider** [comment]
Thanks for the snippet. Seeing as this is a common use case for the library, would you consider making it an official feature? Or creating a `typebox-extra` package?

**Comment by sinclairzx81** [comment]
@jonahsnider Hi. Providing direct support for OpenAPI schemas isn't really on the cards for TypeBox, however I would like to offer more flexibility in the TypeBox type system to allow users to override and define their own idealized schema representations (as per example given)....but this is a ongoing work in progress. 

As for a `typebox-extra` package, I think this is probably best implemented by users themselves in their respective code bases. It's difficult for me to know exactly what should be added to a `extras` package (every user has their own requirements) and the term `extra` isn't very specific as to what it should entail.

However, consider the following which extends the TypeBox TypeBuilder to provide additional functions specific to Open API. If someone were to approach creating an installable `typebox-openapi` package, id imagine it written in the following way.

```typescript
import * as TypeBox from '@sinclair/typebox'
export * from '@sinclair/typebox'

type IntoStringLiteralUnion<T> = {[K in keyof T]: T[K] extends string ? TypeBox.TLiteral<T[K]>: never }

export class CustomTypeBuilder extends TypeBox.TypeBuilder {

    public Nullable<T extends TypeBox.TSchema>(schema: T):  TypeBox.TUnion<[T, TypeBox.TNull]> {
        return { ...schema, nullable: true } as any
    }
    
    public StringLiteralUnion<T extends string[]>(values: [...T]): TypeBox.TUnion<IntoStringLiteralUnion<T>> {
        return { enum: values } as any 
    }
}

export const Type = new CustomTypeBuilder()
```
```typescript
import { Type, Static } from './custom'

const T = Type.Object([
    option: Type.StringLiteralUnion(['A', 'B', 'C']),
    email: Type.Nullable(Type.String({ format: 'email' }))
])
```
Hope that helps
S
