### ISSUE TITLE
Lost Optional information

### ISSUE THREAD

**Issue by sorawee** [sinclairzx81/typebox#1078]
Hi! I'm very new to typebox, so my apologies if I misunderstand anything.

There are two unexpected behaviors that I found:

### Optional at top-level

Consider:

```
const Test1 = Type.Object({ a: Type.Optional(Type.String()) });
type Test1 = StaticDecode<typeof Test1>;

/*
type Test1 = {
    a?: string | undefined;
}
*/
```

This totally makes sense to me.

But now, consider:

```
const Test2 = Type.Optional(Type.String());
type Test2 = Static<typeof Test2>

/*
type Test2 = string
*/
```

The missing `| undefined` doesn't seem right to me. I guess one could say that optional only makes sense inside an object, which is very fair! However, it makes the system less compositional. I hope we could just preserve `| undefined` in the inferred type.

### Lost Optional in Module

Consider:

```
const Test1 = Type.Object({ a: Type.Optional(Type.String()) });
type Test1 = StaticDecode<typeof Test1>;

/*
type Test1 = {
    a?: string | undefined;
}
*/

const TestModule = Type.Module({
  Test: Type.Object({ a: Type.Optional(Type.String())})
});

const Test3 = TestModule.Import('Test');
type Test3 = StaticDecode<typeof Test3>;

/*
type Test = {
    a: string;
}
*/
```

The fact that `a` is optional is somehow lost. I think this one is really problematic.

Also, is there a workaround for this "Lost Optional in Module" problem? (I use Module because I need to deal with recursive schema)

Thanks!

EDITED: I found `Type.Recursive` which apparently can be used to workaround the issue!

**Comment by sinclairzx81** [comment]
@sorawee Hi, thanks for reporting!

Yes, this was a known issue. I have just a update to resolve on 0.34.1.

Just bear in mind, the Module infrastructure is very very new. The Module functionality was pushed on 0.34.0 (a few days ago), but I am still yet to roll out all the features for it (this will happen over the course of 0.34.x). You may run into bugs here and there (all related to the Type Builder + Modules). But if you do run into any problems, feel free to ping an issue.

Will close this one out for now as things should be resolved on the latest. Feel free to ping on this thread if you run into any issues though.
Cheers!
S
