### ISSUE TITLE
Cannot find module 'src/value/guard' in 0.34.1

### ISSUE THREAD

**Issue by laat** [sinclairzx81/typebox#1081]
<img width="778" alt="image" src="https://github.com/user-attachments/assets/4410e486-e179-4a31-a385-9c32668699b5">

It's probably caused by this line:
https://github.com/sinclairzx81/typebox/blob/56b760c99eb71dfba4c6b385a27a17c21ca13a1c/src/type/pick/pick.ts#L48

**Comment by nemosmithasf** [comment]
Also getting this error

**Comment by sinclairzx81** [comment]
@laat @nemosmithasf Hi, thanks for reporting!

There have been a lot of updates recently, Will push a fix for this shortly.

**Comment by sinclairzx81** [comment]
@laat @nemosmithasf Hiya,

Have just published a fix on 0.34.2. If you can test things are working your side can close off this issue.

Thanks again for reporting!
S

**Comment by nemosmithasf** [comment]
Fixed it on my end- thanks for all your good work.

**Comment by sinclairzx81** [comment]
@nemosmithasf All good :)

Will close this one off for now. Thanks again for the quick reporting!

All the best
S
