### ISSUE TITLE
Enum in Type.Module resolves to never

### ISSUE THREAD

**Issue by webstrand** [sinclairzx81/typebox#1084]
Might be related to #1058

```ts
enum Example { A, B }
const mod = Type.Module({
  Foo: Type.Object({
    example: Type.Enum(Example)
  })
});

const q = mod.Import("Foo");
type q = Static<typeof q> // { example: never }
```

**Comment by sinclairzx81** [comment]
@webstrand Hiya, thanks for reporting.

I have pushed a fix for this on 0.34.4. This issue was closed by the PR, but if you run into any problems, feel free to ping on this thread, or open an new issue.

Thanks again!
Cheers
S
