### ISSUE TITLE
Typebox with fastify uploads

### ISSUE THREAD

**Issue by AndreLeBlanc** [sinclairzx81/typebox#1086]
I am trying to find a way to upload files using fastify, typescript and typebox. Unfortunately I can't find anything matches and works. I need it to work using swagger.

The best I have gotten is:

```
const UploadSchema = Type.Object({
  file: Type.String({ format: 'binary' }), // This tells Swagger it's a file upload
  description: Type.Optional(Type.String({ maxLength: 255 })),
})


  fastify.post(
    '/upload',
    {
      schema: {
        consumes: ['multipart/form-data'], // Required for Swagger UI
        body: UploadSchema, // Body schema for file and additional fields
      },
    },

    async (req, reply) => {
      const data = await req.file()

```

Which ends with:

{
  "statusCode": 400,
  "code": "FST_ERR_VALIDATION",
  "error": "Bad Request",
  "message": "body must be object"
} 

However, the swagger is correct using this schema. If i comment out the schema, restart the server and then make the request from swagger it works. Is there a better way of implementing this?

**Comment by sinclairzx81** [comment]
@AndreLeBlanc Hi

Can you show me what the 'body' schema needs to looks like? If I can see the raw Json Schema (from documentation or code snippet), I should be able to show you how you can wrap that in a TypeBox type. 

Usually in cases like this, if the schematics are unknown to Json Schema, you're going to need to create a custom schema type. I can help you with that, but need to see the raw schematics first.

**Comment by AndreLeBlanc** [comment]
@sinclairzx81 

const UploadSchema = Type.Object({
  file: Type.String({ format: 'binary' }), // This tells Swagger it's a file upload
   fileName: Type.String(),
  description: Type.Optional(Type.String({ maxLength: 255 })),
})


Filename and description are just regular strings. File is just any file the user can choose to upload such as PDFs, images, docs etc.

If I don't add:  consumes: ['multipart/form-data'], // Required for Swagger UI

I don't get the upload functionality.

The [fastify-multipart library can be found here](https://github.com/fastify/fastify-multipart) 

Thanks for your quick reply.

**Comment by sinclairzx81** [comment]
@AndreLeBlanc Hi,

I'm still not too familiar with the Fastify multipart/form-data setup, but based on the following information.

https://github.com/fastify/fastify-multipart?tab=readme-ov-file#json-schema-body-validation

You should be able to create the type this way.

```typescript
const FileUploadSchema = Type.Unsafe<{
  myFile: Uint8Array, // <-- check this, it may be a Node ReadableStream
  hello: 'world'
}>({
  type: 'object',
  required: ['myFile'],
  properties: {
    myFile: {
      type: 'object',
    },
    hello: {
      type: 'string',
      enum: ['world']
    }
  }
})

// ...

fastify.register(require('@fastify/multipart'), { attachFieldsToBody: 'keyValues' })

fastify.post('/upload/files', {
  schema: {
    consumes: ['multipart/form-data'],
    body: FileUploadSchema
  }
}, function (req, reply) {
  console.log({ body: req.body })
  reply.send('done')
})
```

The Unsafe type lets you specify custom schematics + custom infer type. Information on Unsafe can be found at the link below

https://github.com/sinclairzx81/typebox#types-unsafe

Let me know if this helps
Cheers
S

**Comment by AndreLeBlanc** [comment]
Thank you for your help!

This works but the swagger doesn't allow file uploads:

```
const FileUploadSchema = Type.Unsafe<{
  myFile: Uint8Array // <-- check this, it may be a Node ReadableStream
  hello: 'world'
}>({
  type: 'object',
  required: ['file'],
  properties: {
    file: {
      type: 'object',
    },
    fileType: Type.String(), // This tells Swagger it's a file upload
    DriverCarRegistrationNumber: Type.String(),
  },
})

export type UploadInput = Static<typeof UploadSchema>

export async function uploads(fastify: FastifyInstance) {
  fastify.post(
    '/upload',
    {
      schema: {
        consumes: ['multipart/form-data'],
        body: FileUploadSchema,
      },
    },
    async (req, reply) => {
      const data = await req.parts()
```

![image](https://github.com/user-attachments/assets/9215e047-2986-4837-a685-d50e419be538)


```
const FileUploadSchema = Type.Unsafe<{
  myFile: Uint8Array // <-- check this, it may be a Node ReadableStream
  hello: 'world'
}>({
  type: 'object',
  required: ['file'],
  properties: {
    file: Type.String({format: 'binary")
    fileType: Type.String(), // This tells Swagger it's a file upload
    DriverCarRegistrationNumber: Type.String(),
  },
})
```

Gives the right swagger but fails with:

{
  "statusCode": 400,
  "code": "FST_ERR_VALIDATION",
  "error": "Bad Request",
  "message": "body/file must be string"
}
