### ISSUE TITLE
Serialization omitting 0-values (or just null/undefined)

### ISSUE THREAD

**Issue by nick-boxem** [sinclairzx81/typebox#1102]
When serializing it's common to want to omit fields entirely that are 'default' or 0-values, because this saves valuable space. Is there a way in typebox to accomplish this? In golang you have the struct tag `omitempty`. 

Is this possible or is it out of the scope of typebox? 

Thanks

**Comment by sinclairzx81** [comment]
@nick-boxem Hi,

> Is this possible or is it out of the scope of typebox?

Unfortunately, it is out of scope. TypeBox doesn't provide any serialization functionality. To be specific, it doesn't offer any mechanisms to convert from a JavaScript value into a structured serialized format (such as Json, Xml, MsgPack or Protobuf, etc). 

The closest it has is Transforms which are able to Encode and Decode from one JavaScript value into another JavaScript value (for example, transforming a ISO date string into a JavaScript Date object and back again), but this functionality isn't going to be useful for general purpose serialization ... for that you will want to use dedicated libraries that focus specifically on serialization for the format you want to serialize to.

In the case of something like Protobuf, TypeBox schematics are reflective, so you could use them to generate Protobuf structures from TypeBox schematics, however the mapping involved to achieve this is outside the scope of the library.

---

Hope this brings some insights. Will close off this issue for now as this functionality is out of scope.
All the best
S
