### ISSUE TITLE
Schemas in Module cannot be used as Record keys outside of module

### ISSUE THREAD

**Issue by kade-robertson** [sinclairzx81/typebox#1104]
When defining a string (or presumably, any other valid record key schema) inside of a `Type.Module`, it can be used as a schema for a record defined within the same `Type.Module`. However, if you attempt to use this key in a separate schema definition via `Type.Import`, the record type can no longer be resolved correctly.

```ts
import { Type, Static } from '@sinclair/typebox';

const Things = Type.Module({
	ThingId: Type.String({ pattern: '^\\w+\\d+$' }),
	ThingRecord: Type.Record(
		Type.Ref('ThingId'),
		Type.Object({
			one: Type.String(),
			two: Type.Number(),
		}),
	),
});

const ThingRecord = Things.Import('ThingRecord');
type ThingRecord = Static<typeof ThingRecord>; // evaluates to { [x: string]: { one: string; two: number; }; };

const OtherThing = Type.Object({
	one: Type.String(),
	two: Type.Number(),
});

const Collections = Type.Object({
	things: Type.Record(Things.Import('ThingId'), OtherThing),
});
type Collections = Static<typeof Collections>; // evaluates to { things: string };

const FixedCollections = Type.Object({
	things: Type.Record(Type.String({ pattern: '^\\w+\\d+$' }), OtherThing),
});
type FixedCollections = Static<typeof FixedCollections>; // evaluates to { things: { [x: string]: { one: string; two: number; }; }; };
```

This is using the latest (`0.34.9`) release.

**Comment by sinclairzx81** [comment]
@kade-robertson Hiya,

There was actually a bug here which is fixed on 0.34.10. But it probably isn't the fix you were expecting...

```typescript
// R is TNever
const R = Type.Record(Things.Import('ThingId'), OtherThing)
```

### TImport + Future

Unfortunately, It is not currently possible to pass a `TImport` as a parameter to any computable type (such as Record, Partial, Pick, Omit). This will be made possible in future, but as of now, the implementation and mapping required to do it is in a pending state until early 2025.

Just for some insight, TypeBox is actually being prepared for an extensive internal redesign where the entire type system will be rebuilt inline with the inference mechanisms developed for TImport. The inclusion of Module, TComputed, TImport, as well as recent updates to TRef were to make provisions for this work, as well as to help assert the design of Module at a high level...

As all types are going to be updated inline with TImport (next year), it doesn't make sense to try and integrate TImport deeply on the current infrastructure. So as of now, I am deferring things.

---

I have applied a fix for the return type for the following (for some reason it was yielding the inferred key). But the updated TNever is the correct return type until the new infrastructure goes in.

```typescript
// R is TNever
const R = Type.Record(Things.Import('ThingId'), OtherThing)
```

Hope this brings some insight (this revision is a little bit in flux while I get things line up). Happy to discuss things more if you have any questions tho. Will close up for now, but I'll add a `future` `review` tag to revisit down the line.

All the best
S
