### ISSUE TITLE
2020 JSON Schema Support

### ISSUE THREAD

**Issue by BrandonGardner2** [sinclairzx81/typebox#1106]
Hi,
 
 Is it possible to revisit the support of the 2020 JSON Schema spec? This issue from June 2022 is related but we are well into the stable release and adoption of the 2020 schema now. This would be very beneficial for utilizing any of the newer spec features without having to do Unsafe work arounds.
 
 
 

> @AlexVDW Hi. Just an update on this. I have done a fair review of the 2020 specification, and TypeBox won't be implementing this specification for the foreseeable future. There are a few awkward updates in the 2020 specification for tuples and arrays that make supporting 2020 difficult, and implementing this now may result in issues on earlier draft versions. I think the preference here will be to wait until there is enough install base for the 2020 spec, then consider porting TypeBox over to it at that time.
> 
> In the interim, I've added a new type called `Type.Unsafe<T>()` which might prove useful for constructing schemas that match the 2020 spec for OpenAPI. You can read about this new type https://github.com/sinclairzx81/typebox#Unsafe-Types. But for the time being, will be waiting on community feedback to gauge how best to proceed with 2020
> 
> Will close off this issue for now
> Many Thanks
> S
> _Originally posted by @sinclairzx81 in https://github.com/sinclairzx81/typebox/issues/169#issuecomment-1169984223_

**Comment by BrandonGardner2** [comment]
Thanks for that huge write up @sinclairzx81 ! that is super helpful.

On a side note, is there any formal support for $defs or the $ref pattern? I realize maybe that isn't a TypeBox issue outright but it seems to have compatibility problems with AJV at least.

For example,

I would expect to do something like:

```ts
const simpleSchema = T.Object({ foo: T.String() })

const parentSchema = T.Object({
  ...other,
 $defs: {
   simpleSchema
 }
})

const otherSchema = T.Intersect([
  T.Ref(simpleSchema),
  T.Object(otherSchema)
] )
```

however, you have to pass a $id field to `T.Ref` for it to work I believe and there are strict rules around an ID field not starting with `#` so you couldn't do `#/$defs/simpleSchema` for example.

This lead me to doing a little bit of a hack with Unsafe such as:

```ts
const UseDef = <T extends TSchema>(path: string) => T.Unsafe<Static<T>>({ $ref: path })
```

This is a quick write up so probably not the cleanest example but I wasn't find a clear way to achieve this without a work around similar to the above.

**Comment by sinclairzx81** [comment]
@BrandonGardner2 Hi,

> On a side note, is there any formal support for $defs or the $ref pattern? I realize maybe that isn't a TypeBox issue outright but it seems to have compatibility problems with AJV at least.

TypeBox added functionality to express $defs constructs on 0.34.0. You can use the Type.Module to create a set of cross referenced types, and use Type.Ref to reference them. TypeBox produces a $defs schema for each contained type. It also handles auto $id generation derived from the schemas property name.

[TypeScript Link Here](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUFJIR2LeAFkIAEwCuXDHAC8KYQDoVGrQAoEUuHACCALn2YDAeREArDCRjm44+2kcAcuogIhhQpgCUFBFYlnAAQn6GLu6e3qhJgcGh4VHkMXEAwpkYBgCS7DBhLB5eANpxVv6lAEoYVKYM1gwxcI0Ore2d8T1xALoRUvkycgrwhbpwxpqlZeDQXgyFPVZw-Pxws4pwC3oWuxeXV9dX+7sAJKrtLPbnN+8fu3cXdoj9nwCLt9LkJMPYGBA3LUGLFAXCgQcrlAMABHdR8DCqex1RiSOBjWHw+HAi5gWiYWDADAvRA+V5wUEYcHsbJhBgUCiEomAkkPYBYxjdLncz688jCkXvXmJP6SgG8qyM8GQ1IwGH-OW3RGXZFojECnEMVDsgkazUI65kiAU4jU+kZWlKxgskJsjnis3mqwKuD3fngkYSr1fbVWD3B6684qyiOXH0ELhcJxUbGer0+qxIBj3ZFUBjg7qctPmjO07O5-OMEYUYuan2m2Nx0N8gVbdWNi0Xci1uXA8Md73anPtcHbIMRu7dqSMk6LfBEUgAHkZECoJwAfFqGcJZ2ce5Lgb44C6cgBufciydwABkMYHwIdJ7C54Hg4oQA)

```typescript
const Module = Type.Module({
  A: Type.Object({ x: Type.Number() }),
  B: Type.Object({ y: Type.Number() }),
  C: Type.Intersect([
    Type.Ref('A'), 
    Type.Ref('B')
  ])
})

const C = Module.Import('C')   // const C = {
                               //   $defs: {
                               //     A: {
                               //       type: 'object',
                               //       required: [ 'x' ],
                               //       properties: { x: { type: 'number' } },
                               //       $id: 'A',
                               //     },
                               //     B: {
                               //       type: 'object',
                               //       required: [ 'y' ],
                               //       properties: { y: { type: 'number' } },
                               //       $id: 'B',
                               //     },
                               //     C: {
                               //       allOf: [
                               //         { '$ref': 'A' },
                               //         { '$ref': 'B' }
                               //       ],
                               //       $id: 'C',
                               //     }
                               //   },
                               //   $ref: 'C',
                               // }

type C = Static<typeof C>      // type C = {
                               //   x: number;
                               // } & {
                               //   y: number;
                               // }
```

Just keep in mind, this functionality is quite new. If you run into any problems, feel free to ping an issue.
Cheers
S

**Comment by BrandonGardner2** [comment]
@sinclairzx81 That is great. I actually missed that entirely. I think it solves my issue for the most part. Perhaps I am missing something, though.

In a large schema would there would be an issue where the module is continually reused and it is pasting in the defs every single time as well?

**Comment by sinclairzx81** [comment]
@BrandonGardner2 Heya,

> In a large schema would there would be an issue where the module is continually reused and it is pasting in the defs every single time as well?

This is a good question. At this stage, `Import` will return a $defs schema containing all definitions (irrespective of if they are being referenced or not). Because all definitions are returned, this equates to a ton of redundancy if publishing each imported type separately (but perhaps less of an issue if just validating with the schematics). Needless to say, TypeBox could be doing better here as generating publishable schematics is "in scope".

The functionality for Module went in on 0.34.0 (just over a week ago) and there is work underway to improve some of the finer details of the feature (including plans to cull Import to only include referenced types within the Module). However I am somewhat tempted to keep things as they are (at least until the next minor semver), and try to gather some information as to how users are trying to interact with Module (it's been a difficult thing to design for)

I am keen to keep a active discussion with users on the feature, and to learn of the use cases in which it's being applied. Did you want to start up a Discussion thread to go into some of the details?

Let me know.
S
