### ISSUE TITLE
Union of a Union in a module causes infinite type instantiation

### ISSUE THREAD

**Issue by noftaly** [sinclairzx81/typebox#1108]
Hello,
I was trying to use Modules using the latest version of the library, `0.34.10`, and encountered a `Type instantiation is excessively deep and possibly infinite.` error.
I narrowed it down to making a Union of a Union imported from a module, like so:
```ts
const M = Type.Module({
  Foo: Type.Union([Type.Literal(1), Type.Literal(2)]),
});
const U = Type.Union([M.Import('Foo')]); // TypeScript: Type instantiation is excessively deep and possibly infinite.
```

It works fine when using Parse:
```ts
const P = Parse('type Foo = 1 | 2');
const U = Type.Union([P.Foo]);
```
It also works fine if I put the Union inside the module:
```ts
const M = Type.Module({
  Foo: Type.Union([Type.Literal(1), Type.Literal(2)]),
  Bar: Type.Union([Type.Ref('Foo')]),
});
const U = M.Import('Bar');
```

**Comment by sinclairzx81** [comment]
@noftaly Hi, thanks for reporting. 

It is possible to work around this by assigning the Import into it's own variable.

[TypeScript Link Here](https://www.typescriptlang.org/play/?moduleResolution=99&module=199#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUDJIR2LeAFk4AXhTCAdEogATAK5cMACgRS4cAGIQIALg2ZNAVXbB5xgNppHAGWAwMKAIuYwBGAEocbwxNPwCgkIAmcIBdSKlycIBuWXlFKxs1OCVNAElwaBhjBmsIBnDchXgnIujnV3cPWrSZIA)

```typescript
import { Type, Static } from '@sinclair/typebox'

const M = Type.Module({
  Foo: Type.Union([Type.Literal(1), Type.Literal(2)]),
});

const Foo = M.Import('Foo')

const U = Type.Union([Foo])
```

Unfortunately, I don't think there is much I can do to at this stage to optimize for this case as the infer logic for modules is very complex (which is further compounded by yet more computed inference for the Union return value). I will take a look and see if there is something that can be done, but expect the Union type itself may require an update (which may need to wait until the minor semver)

Will keep you posted.
S

**Comment by noftaly** [comment]
Interesting, thanks for the quick update!
No problem, I don't actually need that. I just stumbled upon it while getting a minimal repro for another issue :)

**Comment by sinclairzx81** [comment]
@noftaly Hiya,

I was trying to find a resolution to this issue on 0.34.11, but wasn't able to find a solution that wouldn't involve a minor semver. The problem itself relates to how the legacy Type.Recursive type works (specifically the `this['params']` used to instance the inference type for Unions). 

Note that the internal implementation for Type.Recursive is somewhat in conflict to how the new Module inference works. At this stage, the inference only appears to pop out for Union types for inline definitions (as per your repro). As mentioned, the workaround for 0.34.x will be to pull the Import into it's own definition. In subsequent revisions, I will be overhauling Type.Recursive to modernize it inline with Module (meaning inline definitions will work). This is planned for, but non-actionable at this stage.

Will close up this issue for now but will mark the it as `future` and revisit down the road. If you spot any other issues though, please let me know. I am looking to gather a set of known issues related to the new Module functionality such that these can be resolved in the next minor revision (this new Module functionality is both vast and intricate, community reported issues are very helpful)

Thanks again
S
