### ISSUE TITLE
Validating modules

### ISSUE THREAD

**Issue by SebastienGllmt** [sinclairzx81/typebox#1114]
I'm trying to write an application where I want to ensure that the user's output conforms to the JSON Schema specification. The difficulty is that the content of the fields depend on each other

For example,
```json5
{
  "people": {
    "Bob": {
      "name": "Bob",
      "age": 21
    }
  },
  "company_positions": {
    "ceo": {
      "name": "Bob", // note: this name must exist in `people`
      "join_date": "2024-04-02"
    }
  }
}
```

I was pretty excited when I read about the module feature since it sounds like it would solve exactly this problem, but I couldn't find a way to check if user input is valid:
- at the type level: `Static` can only refer to a single module entry (and not validate against the whole thing)
- at runtime: none of the parsing logic accepts `Module` as an input (only `TSchema`)

Sorry if this is a feature planned but not supported yet

## Idea I tried that didn't work

I thought I might be able to hack it by extracting the names as a separate field and referencing it in both places, but unfortunately it didn't work:

```typescript
import type { Static, TNumber, TObject, TRef, TUnion, TModule, TLiteral} from '@sinclair/typebox'

type ToLiterals<T extends any[]> = {
  [K in number & keyof T]: TLiteral<T[K]>;
}[number];

// define the valid "names" first in the array
// the use it to dynamically construct 
function createData<const Names extends string[]>(name: Names ): TModule<{
  PeopleNames: TUnion<ToLiterals<Names>[]>
  People: TObject<{
    age: TNumber,
    name: TRef<'PeopleNames'>
  }>
}> {
  // ignore the implementation for now since I'm focusing on getting the types right
  return null as any;
}

const data = createData(['bob', 'joe']);
const People = data.Import("People");
type Result = Static<typeof People>; // "name" here is unfortunately `never`
```

**Comment by sinclairzx81** [comment]
@SebastienGllmt Hi! Does the following work?

[TypeScript Link Here](https://www.typescriptlang.org/play/?moduleResolution=99&module=199#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsgKoB2wEV5AMsDBlAQDZwC+cAZlBBBwA5AAEAzsCol2BYFAD0MdBgBGEAB7CAUNoUK4AWmMnTZ8xctXrpvQYByBEBnHII1WlTtGbvv-8ttZUwUR2dXdxo6AB4wlzgMDRYqABNxOHEYKCkAcwBtAF0cACUXAFd2eETktJQmFjZ2QrgAXjhCgD5WuAAKbTg4OPTqjFT0vKleVjgGDF4qpNHazOyqHJwAOi3J6eLgHIALBZr0ldzCgv6BuAB+UKcXNw8YvcOYHDytjdLxCve65isDjRWbzDoFDpXAYALhQzyo0R+f0hAEptLwytJiHRBg8IvDYniEosxhksucIT0qHjYZ8tkMCijYcghk8ogihl0EFcoBgYGUoFQUCoNvCqXiNiACGBxc5Wl00JgNvUgexZRgUZq4AR0lQMAA3VjaLi6fRwL66DFYzxwEi8ogYAAiRAIhPCxJOZNW+Up1PCtK+DJRiB5fIFQsVGA2AFkICkKhgetzrnAAAoYCBgdgYIaw1mRTzq8QorBQtMZrMYZkigDyqgAVhgSDAk2WBgQclXhUr7GUQKpWD0S224H6u5HvnMesJ05ns0NhGiU1wl9xg8bdCQ6Jk4CkXd07RgHc7CD08sJ1KphDhhPWIBhhIyANzaLdUHezyvdPeEDYASXAaAWwAIk-bNgJRF9ggwOAkUqbp8CIUhomgiBeHLOcMA6J84DNYCx2AuBgHSYDL0IgAfOBgLvDBgJfbQgA)

```typescript
import { Type, Static, TUnion, TLiteral } from '@sinclair/typebox'

// -----------------------------------------------------------
// NamesToUnion
// -----------------------------------------------------------
type TNamesToUnion<Names extends string[], Result extends TLiteral[] = []> = (
  Names extends [infer Left extends string, ...infer Right extends string[]]
    ? TNamesToUnion<Right, [...Result, TLiteral<Left>]>
    : TUnion<Result>
)
function NamesToUnion<Names extends string[]>(names: [...Names]): TNamesToUnion<Names> {
  return Type.Union(names.map(name => Type.Literal(name))) as never
}

// ...

function createData<Names extends string[]>(names: [...Names]) {
  return Type.Module({
    PeopleNames: NamesToUnion(names),
    People: Type.Object({
      age: Type.Number(),
      name: Type.Ref('PeopleNames')
    })
  }) 
}

const data = createData(['bob', 'joe']);
const People = data.Import("People");
type Result = Static<typeof People>; // "name" is "bob" | "joe";


```

**Comment by SebastienGllmt** [comment]
Thanks! Based off your work, I extended it with solve the example mentioned in my original post

**Key challenge**: you can't index inside a `Type.Ref`, so the `company_positions` can't refer to the names defines inside the `people` object

**Solution**: create a temporary `PeopleNames` key simply for type-checking purposes that is then discarded afterwards

```typescript
import { Type, Static, TUnion, TLiteral } from '@sinclair/typebox'
import type { TImport, TRecord,TString, TModule,TNumber, TRef, TObject, TDate } from '@sinclair/typebox'

// utility type equivalent to Module.Import
type GetModuleProperty<
  F extends { Import: (arg: any) => any },
  Property extends string
> = F extends { Import: (arg: Property) => TImport<infer R, any> } ? TImport<R, Property> : never;

// generate a static return type for `validateData`
type GenerateModule<Names extends TLiteral<string>[]> = TModule<{
  PeopleNames: TUnion<Names>;
  People: TRecord<TString, TObject<{ name: TRef<"PeopleNames">, age: TNumber }>>;
  CompanyPositions: TRecord<TString, TObject<{
      join_date: TDate;
      name: TRef<"PeopleNames">;
  }>>;
}>;

const temporaryKeys = ['PeopleNames'];

/**
 * To avoid users having to repeat themselves,
 * we generate the `PeopleNames` temporary key dynamically from the `People` field
 */
function generatePeople<const Data extends Static<GetModuleProperty<GenerateModule<[TLiteral<string>]>, 'People'>>>(data: Data): {
  PeopleNames: TUnion<[TLiteral<Data[keyof Data]['name']>]>
  People: Data
} {
  return {
    // temporary key created just to help with type-checking
    PeopleNames: Type.Union(Object.keys(data).map(key => Type.Literal(key))) as never,
    People: data,
  }
}

function handleData<const Names extends TLiteral<string>[]>(data: {
  PeopleNames: TUnion<Names>,
  People: Static<GetModuleProperty<GenerateModule<Names>, 'People'>>,
  CompanyPositions: Static<GetModuleProperty<GenerateModule<Names>, 'CompanyPositions'>>
}) {
  // remove the temporary keys we created just to helping with the type
  for (const key of temporaryKeys) {
    delete (data as any)[key];
  }
  return data;
}

const data = handleData({
  ...generatePeople({
    'bob': {
      age: 10,
      name: 'bob'
    },
    'joe': {
      age: 10,
      name: 'joe'
    }
  }),
  CompanyPositions: {
    'ceo': {
      join_date: new Date(),
      name: 'bob'
    },
    'cto': {
      join_date: new Date(),
      name: 'joe'
    }
  }
});

console.log(data); // see output below
// {
//   People: { bob: { age: 10, name: "bob" }, joe: { age: 10, name: "joe" } },
//   CompanyPositions: {
//     ceo: { join_date: 2024-12-11T23:16:47.662Z, name: "bob" },
//     cto: { join_date: 2024-12-11T23:16:47.663Z, name: "joe" }
//   }
// }
```

It's a little unfortunate that there needs to be some temporary key creation (which means you have to introduce a `generatePeople` utility function that adds the type, and a `handleData` function that strips the type)

Of course, you could decide to just keep the temporary type and keep it in your JSON schema, but I feel like this is a temporary solution until you can reference `$id`s deep inside structures (so that you JSON Schema could reference the `name` field directly)
