### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by thereis** [sinclairzx81/typebox#1116]
Does the library has the plan to support ESM? Currently facing the following error:

```
import { TransformDecodeError } from "@sinclair/typebox/value";
         ^^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'TransformDecodeError' not found. The requested module '@sinclair/typebox/value' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@sinclair/typebox/value';
const { TransformDecodeError } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12)

Node.js v21.7.3
```

**Comment by sinclairzx81** [comment]
@thereis Hi,

TypeBox already dual publishes CJS and ESM versions of the package (you can check the `build` directory in node_modules for `cjs` and `esm` sub directories). I believe the resolution of either CJS or ESM comes down to how Node is run, but can't remember all the details I'm afraid. 

This said, running the following in Node from a `.mjs` file should pull in the ESM version of the package.

```typescript
// file: index.mjs

import { TransformDecodeError } from "@sinclair/typebox/value"

console.log(TransformDecodeError) // prints: [class TransformDecodeError extends TypeBoxError]
```

```bash
node index.mjs
```

> Note: You can verify this is importing the `esm` version of the package by deleting the `cjs` sub directory in `node_modules/@sinclair/typebox/build` and running again.

So, not sure what the cause of the `SyntaxError: Named export 'TransformDecodeError' not found. The requested module '@sinclair/typebox/value' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:` could be, but maybe check that Node is running under ESM module resolution.

Let me know how you go.
Cheers
S

**Comment by sinclairzx81** [comment]
@thereis Heya,

Going to close up this issue as this library already publishes for ESM. Would be interested to hear a resolution to your issue tho (if it turned out to be a node, build, bundler, configuration issue). Let me know if you find a resolution to it.

All the best
S
