### ISSUE TITLE
Exclude enum values

### ISSUE THREAD

**Issue by bbenoist** [sinclairzx81/typebox#1121]
`Type.Exclude()` does not seem to work with enums the same way TypeScript does.

Do you have any fix or workaround?

Example:

```ts
import { Type, Static } from "@sinclair/typebox"

enum Pet {
  CAT = "🐈",
  DOG = "🐕",
  PARROT = "🦜",
  TIGER = "🐅",
}

/* @sinclair/typebox */

const SafePet = Type.Exclude(Type.Enum(Pet), Type.Literal(Pet.TIGER));

type SafePet = Static<typeof SafePet>;

const allowedPet: SafePet = Pet.TIGER;


/* @sinclair/typebox */

type SafePet_TS = Exclude<Pet, Pet.TIGER>

// Error Pet.TIGER is unassignable to Pet.CAT | Pet.DOG | Pet.PARROT
const allowedPet_TS: SafePet_TS = Pet.TIGER
```

[Example on CodeSandbox](https://codesandbox.io/p/devbox/node-ts-playground-s7fxc?embed=1&file=%2Fsrc%2Findex.ts)

**Comment by sinclairzx81** [comment]
@bbenoist Hi, thanks for reporting.

Unfortunately, TypeBox only has limited Enum support for some of the more advanced compositional types, like Exclude, Extract, etc. The reason has to do with TypeBox treating Enums as opaque data structures (which make them difficult to map), although TypeBox may investigate improving some of the mappings related to Enum in later versions.

You can work around the issue by representing data types via Literal and Union as follows.

[TypeScript Link Here](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUFJIR2LeAAUCUWvAC8KYQDoAMsBgYoBLgAoGgPg3AObsMAlLPmK4AERMBzeXC1pM+w8amFoC8G4CQO-aOCvDIwO7G3tp+BkYm5gzBgKA7EXJRcADCRAm+GP4pQemAEDvZTvAuEO5FusmBacGAqDsRkc5KGJqJJQCq7MDyZgDaUnD5RFiTrvWzUypqEDCLKLHG624EnuxSALoOXfC4BFQYPX3FOgCi4twArgAmGGZXODdDI+zjO3ufTZQI4OISYPDnS69BL4IikAA8YIwECoEIuVwAfFIgA)

```typescript
import { Type, Static } from '@sinclair/typebox'

const Parrot = Type.Literal('🦜')
const Dragon = Type.Literal('🐉')
const Tiger = Type.Literal('🐅')
const Cat = Type.Literal('🐈')
const Dog = Type.Literal('🐕')

const Pet = Type.Union([
  Cat,
  Dog,
  Parrot,
  Tiger,
  Dragon
])

const SafePet = Type.Exclude(Pet, Type.Union([Dragon, Tiger]))
type SafePet = Static<typeof SafePet>

```
Union and Literal structures are well represented in TypeBox, and provide quite a bit more flexibility over Enum. They are recommended if you need compositional types like Exclude.

Hope this helps
S

**Comment by sinclairzx81** [comment]
@bbenoist Hi, 

Will close off this issue for now as the Union / Literal approach is generally the more supported approach (although I will be investigating better Enum mapping in later revisions). As a fun alternative though (one that is slightly more aligned to how you might express the same in TS), you could also try the following.

[TypeScript Link Here](https://www.typescriptlang.org/play/?target=99&moduleResolution=99&module=199#code/JYWwDg9gTgLgBAbzgZRgQxsAxnAvnAMyghDgHIABAZ2ADssAbNYKAehgE8wBTAIwgAeZAFChIsRHAAKaKFW55CxUpRr0mLdlz6DWVDrXRDhwrBFpV4U7vAC802fIAUAAzKA+DcA5u2TgAfcoC8G4CQOz7+ZAGAoDuhgYAQO9HhgKg7ZC4AlCZmFvDIaATc1nYOctxOSPl4ADRwLgCiAowArgAm3AA8+ZXhIX6BUQB8qSasrHAAdGMmnDzSNnD2qBjYLZPcEATTML0T2ig5eTNz6JhYS9qrO7n5m0A)

```typescript
import { Static } from '@sinclair/typebox'
import { Parse } from '@sinclair/typebox/syntax'

const Pet = Parse(`'🦜' | '🐉' | '🐅' | '🐈' | '🐕'`)

const SafePet = Parse({ Pet }, `Exclude<Pet, '🐉' | '🐅'>`)

// ...

type Pet = Static<typeof Pet>

type SafePet = Static<typeof SafePet>

```
Will close for now, but if you have any follow up questions, please feel free to ping on this thread.
All the best
S
