### ISSUE TITLE
legacy Type.Ref's migration code is not correct

### ISSUE THREAD

**Issue by yshrsmz** [sinclairzx81/typebox#1122]
https://github.com/sinclairzx81/typebox/blob/cd61fa92c03c60d9bf38e50951a63409625796fa/src/type/ref/ref.ts#L55-L62

Here it says to migrate to the code below.

```ts
const R = Type.Unsafe<Static<T>>(T.$id)
```

But `Type.Unsafe()` can not receive string as its parameter, it needs [UnsafeOptions](https://github.com/sinclairzx81/typebox/blob/cd61fa92c03c60d9bf38e50951a63409625796fa/src/type/unsafe/unsafe.ts#L33-L35).

It shows an error like this.

```
Argument of type 'string | undefined' is not assignable to parameter of type 'UnsafeOptions | undefined'.
  Type 'string' is not assignable to type 'UnsafeOptions'.
```

**Comment by sinclairzx81** [comment]
@yshrsmz Hi, Thanks for reporting.

Ah the Ref method should have been documented more cleanly. It was actually removed on 0.34.0 but put back as a deprecated method to give users time to migrate (will keep the signature around for the next few revisions). Unfortunately, the revert of the signature was done as a quick update, and the documentation was written rapidly while I was trying to attend to other things. Sorry about that.

I have updated the documentation to the following.

```typescript

// @deprecated `[Json]` Creates a Ref type. This signature was deprecated in 0.34.0 where 
// Ref requires callers to pass a `string` value for the reference (and not a schema). To 
// adhere to the 0.34.0 signature, Ref implementations should be updated to the following.

// pre-0.34.0

const T = Type.String({ $id: 'T' })

 const R = Type.Ref(T)

//should be changed to the following

// post-0.34.0

const T = Type.String({ $id: 'T' })

const R = Type.Unsafe<Static<typeof T>>(Type.Ref('T'))

// You can also create a generic function to replicate the pre-0.34.0 signature if required

const LegacyRef = <T extends TSchema>(schema: T) => Type.Unsafe<Static<T>>(Type.Ref(schema.$id!))
```

I will publish these updates on the next npm push.

---

The PR closed the issue, but if you have any questions regarding upgrading Ref to the new signature, feel free to ping on this thread.

All the best
S

**Comment by sinclairzx81** [comment]
@yshrsmz Hiya,

> I'm using TypeBox with Fastify, and while the Module system looks nice, it doesn't work nicely with Fastify and fastify-swagger(e.g., the module can't be added with fastify.addSchema() method, and fastify-swagger generates broken OpenAPI document).

The current Module return type for Import is a `$defs` schema. Unfortunately, I don't know if there's much that can be done to improve this as imported types may contain many different referenced / dereferenced types, and those need to be embedded inside the `$defs` object so they can be referenced. Problems here may come down to how OpenAPI implementations interpret these `$defs` definitions. The Module functionality was tested against Ajv tho.

I'll give this some thought for future versions, as good OpenAPI compliance is in scope. I'll do some research on it. Thanks for letting me know.
