### ISSUE TITLE
`Optional()` always making a property `undefined`-able is incorrect

### ISSUE THREAD

**Issue by nemosmithasf** [sinclairzx81/typebox#1128]
The following two are not the same:

```
{ foo?: string }
```

```
{ foo?: string | undefined }
```

As of right now, I don't believe it's possible to define the first variant.
But if we are writing typing for JSON- it's legal to omit a property, but it's not possible to set it as `undefined`.

**Comment by sinclairzx81** [comment]
@nemosmithasf Hi,

> As of right now, I don't believe it's possible to define the first variant.

It is actually possible, but you will need to set `exactOptionalPropertyTypes` to `true` inside `tsconfig.json`.

https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes

You can also configure this setting via the TypeBox TypeSystemPolicy

```typescript
import { TypeSystemPolicy } from '@sinclair/typebox/system'
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'

TypeSystemPolicy.ExactOptionalPropertyTypes = true // default is false

const T = Type.Object({
  x: Type.Optional(Type.Number())
})

const R = Value.Check(T, { x: undefined }) // false
```
---

TypeBox will validate optional properties using the `value.x === unknown` checks as this is the generated type produced by TypeScript without configuration. When setting the ExactOptionalPropertyTypes to true, this check is updated to `'x' in value`, but you will want to make sure both tsconfig.json and the TypeSystemPolicy are configured the same to ensure validation lines up to static inference.

Hope this helps
S

**Comment by nemosmithasf** [comment]
Ah, you're right. Thanks for the tip
