### ISSUE TITLE
[Feature Proposal] Add extend function

### ISSUE THREAD

**Issue by fox1t** [sinclairzx81/typebox#12]
## Motivation
Working on complex schema can be tedious because of many common part repetitions.

## Idea
It would be helpful to have something similar to this:
```typescript
function extend<F, S>(firstSchema: F, secondSchema: S): F & S {
  if (firstSchema.type !== 'object' || secondSchema.type !== 'object') {
    throw new Error(`Only object schemas can be extended.`)
  }
  return {
    type: 'object',
    properties: {
      ...firstSchema.properties,
      ...secondSchema.properties,
    },
    required: (firstSchema.required || []).concat(secondSchema.required),
  }
}
```
Another example of this approach can be find here: https://github.com/fastify/fluent-schema/blob/master/src/ObjectSchema.js#L250

## Example
```typescript 
export const channelSchema = Type.Object({
  channel: Type.String(),
  qapla: Type.Optional(
    Type.Object({
      apikey: Type.String(),
      callOn: Type.Union([Type.Literal('PACKING'), Type.Literal('SHIPPING')]),
      reference: Type.Union([Type.Literal('rifOrder'), Type.Literal('orderNumber')]),
    }),
  ),
})

const savedDocument = Type.Object({
  _id: ObjectId,
  tenantId: ObjectId,
  createdAt: Type.String({ format: 'date-time' }),
  modifiedAt: Type.String({ format: 'date-time' }),
  createdBy: ObjectId,
  modifiedBy: Type.Optional(ObjectId),
})

export const responseSchema = extend(savedDocument, channelSchema)
```

**Comment by sinclairzx81** [comment]
Hi,

Have you tried `Type.Intersect(...)`? It should produce a schema which is the intersection of both types. The `Type.Intersect(...)` function will construct the schema using [`allOf`](https://json-schema.org/understanding-json-schema/reference/combining.html#allof)  and will statically resolve to a TypeScript [`Intersection Type`](https://www.typescriptlang.org/docs/handbook/advanced-types.html#intersection-types), (`A & B`). It should be possible to construct the combined schema with the following.
```typescript
export const responseSchema = Type.Intersect([savedDocument, channelSchema])
```
Let me know if that works.

**Comment by fox1t** [comment]
Works like a charm! Nice!
What do you think to add an alias to extend? I completely missed this because I was searching for extend instead of intersect.

**Comment by sinclairzx81** [comment]
Cool, glad that works!! :)

Just on adding an alias for `Type.Extends`, I'm fairly keen to keep the API surface area as is for the time being. The naming for `Type.Intersect(...)` and `Type.Union(...)` are derived from TypeScript's terminology for composite types. So for the following things specifically.
```typescript
Type.Intersect([...]) | allOf | A & B
Type.Union([..])      | oneOf | A | B
```
So based on this, would be keen to reserve `Type.Extends()` for some future work, potentially looking at adding some way to express [conditional types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#conditional-types) if the need ever arises ... something like the following.
```typescript
// typescript
type T = string
type X = T extends string ? 'a string' : 'not a string'

// typebox
const T = Type.String()
const X = Type.Extends(T, Type.String(), Type.Literal('a string'), Type.Literal('not a string'))
```
But for now, keen to keep the current interface for composite types as is.

Cheers !
S
