### ISSUE TITLE
v0.21: How to adapt `Type.Record` from `Type.Union([...Type.Literal(...)])` to `Type.KeyOf(...)`?

### ISSUE THREAD

**Issue by leoyli-headsup** [sinclairzx81/typebox#122]
I wonder why it was changed in v0.21 as log stated?

> Type.Record(...) updated to accept Type.KeyOf(...) instead of Type.Union([...Type.Literal(...)]).

I got this previously:

```ts
export type PropertyLocation = Static<typeof propertyLocation>;
export const propertyLocation = Type.Union([
  Type.Literal('a'),
  Type.Literal('b'),
  Type.Literal('c'),
]);

export type PropertyLocationCount = Static<typeof propertyTypeCount>;
const propertyLocationCount = Type.ObjectExact({
  types: Type.Record(propertyLocation, Type.Number()),
});
```

How should I react on this breaking change?

**Comment by leoyli-headsup** [comment]
I also wonder could we pass in `Type.Enum(...)` in `Type.Record(...)`?

**Comment by sinclairzx81** [comment]
@leoyli-headsup Hi

Sorry yes, I had to drop the previous implementation to get things quickly aligned for TS 4.5 (was a bit of a late night chasing that up), but I plan to do a bit more work on around string literal unions and keyof today. 

You can express this as the following

```typescript
// replace

const K = Type.Union({ 
    Type.Literal('a'), 
    Type.Literal('b'), 
    Type.Literal('c'), 
})

// with the following

const K = Type.KeyOf(Type.Object({ 
    a: Type.Null(), 
    b: Type.Null(), 
    c: Type.Null() 
 }))

const T = Type.Record(K, Type.String())

// equivalent to

type T = Record<keyof { a: null, b: null, c: null}, string>
```
Or just temporarily pass a `Type.Record(Type.String(), Type.String())` for the time being. I will be looking to unify `Type.KeyOf()` with string literal unions in the next update.

Apologies for the breaking change. Will fix.

**Comment by sinclairzx81** [comment]
@leoyli-headsup Have pushed a revision on `0.21.1` that re-enables union string literals as record keys. The following record Key types are now permissible in TypeBox.

```typescript
// type K = string
const K = Type.String()

// type K = string
const K = Type.RegEx(/foo|bar/)

// type K = number
const K = Type.Number()

// type K = 'A' | 'B' | 'C'
const K = Type.Union([
   Type.Literal('A'), 
   Type.Literal('B'), 
   Type.Literal('C')
])

// type K = keyof { A: number, B: number, C: number }
const K = Type.KeyOf(
  Type.Object({ 
    A: Type.Number(), 
    B: Type.Number(),
    C: Type.Number()
  })
)

// type K = keyof Omit<{ A: number, B: number, C: number }, 'C'>
const K = Type.KeyOf(
    Type.Omit(
      Type.Object({ 
        A: Type.Number(), 
        B: Type.Number(),
        C: Type.Number()
      }),
     ['C']
  )
)
```
Will amend entry from changelog and consider this issue a general regression from the TS 4.5 update. 
Many Thanks
S

**Comment by leoyli-headsup** [comment]
Wow, thank you for being so quick here, I was just coming up something like this:

```ts
function  LiteralUnion<T extends string>(literals: T[]): TKeyOf<T> {
    return _Type.KeyOf(
      _Type.Object(
        literals.reduce((union, literal) => {
          union[literal] = Type.Literal(literal);
          return union;
        }, {} as Record<T, TLiteral<T>>),
      ),
    );
};
```

**Comment by sinclairzx81** [comment]
@leoyli-headsup Hey no problem. 

I may actually revisit how TypeBox handles string union and keyof in future. Currently TypeBox keeps a specific definition for `TKeyOf` returned on `Type.KeyOf(...)` but ideally the `Type.KeyOf(...)` function should just return a `Type.Union<...TLiteral<...>>`. 

At this stage, I'm pending additional updates around this for the next revision of TypeBox as the existing schema representation for `TKeyOf` is different from the representation of `TUnion` (making it a bit awkward to reconcile), but it would be nice to unify the two.

Thanks again
S
