### ISSUE TITLE
Lost typings of schema structure - everything is now `any`

### ISSUE THREAD

**Issue by apancutt** [sinclairzx81/typebox#123]
While this is quite likely intended for performance, the inference changes in 0.21 severely impacts how we use Typebox...

JSON schemas are used as our single source of truth. They are used to validate database IO, HTTP IO, forms... the whole lot.

We make heavy use of JSON Schema `enums` (using a tweaked version of `Type.KeyOf()`) which can be reused - to keep things DRY - in all sorts of places (e.g. `MySchema.properties.myEnumProperty.enum` will return an array of allowed strings). _This is just one example of how we traverse schema instances - but it's done a lot._

Prior to 0.21, the array would be correctly typed (e.g. `('value1' | 'value2')[]`) but since all our top-level schemas are JSON Schema objects - which are now effectively typed as `{ properties: any }` - we've lost all type safety. Considering how fundamental JSON Schemas are in our codebase, type-safety is critical.

Is there are way way to get back the typings in the latest version without sacrificing any of the improvements made? I suspect generics could be a way round, but that probably reintroduces performance issues.

Reverting back to the previous version is tempting but then we'll have to live with the "excessively deep" recursion issue forever (been suffering with this for several months now, but resolved in the latest version... so kudos for that).

**Comment by sinclairzx81** [comment]
@apancutt Hi, yes sorry. The `0.21.0` update involved fairly sweeping internal changes to resolve deep instantiation issues on TypeScript 4.5. Prior to `0.21.0`, TypeBox would statically infer the output type by deep traversing the same type information you've noticed missing in `0.21.0`.  This deep traversal was triggering TypeScript recursion heuristics in 4.5, so I've needed to take a significantly different approach to optimizing static inference to keep TypeBox viable on new iterations of the TypeScript compiler. Unfortunately this resulted in temporarily losing schema type info....

I have just pushed `0.22.0` which re-adds this type information. Apologies for issue, this is largely a result of rearchitecting TypeBox's internals in response to 4.5 and enable additional inference functionality moving forward.

ChangeLog https://github.com/sinclairzx81/typebox/blob/master/changelog.md#0220

Let me know if you run into any problems. 
Cheers
S

**Comment by apancutt** [comment]
Amazing. Types have returned, and haven't seen any deep recursion issues either (yet 🤞). Huge thanks.

**Comment by sinclairzx81** [comment]
@apancutt Hey, no problem. Will close off this issue. Just keep in mind if you're using `Type.Namespace()` or `Type.Rec()`, that `definitions` has been renamed to `$def`. Everything else should be the same as before.

If you run into any problems, feel free to open another issue.

Cheers
S
