### ISSUE TITLE
Problem with generics when using the generated declaration files.

### ISSUE THREAD

**Issue by cooliopas** [sinclairzx81/typebox#125]
Hi
Since v0.21+ I have this issue.

I created repo with the minimal issue reproduction code.

[https://github.com/cooliopas/typebox_schemas](url) (shared schemas used on frontend and backend)
[https://github.com/cooliopas/fastify_api](url)

**fastify_api** has **typebox_schemas** as a dependency.

Inside fastify_api I use the generated declaration files as:

```
import { JSENDSuccessSchema } from 'typebox_schemas/lib/schemas/JSENDSuccess'
[...]
fastify.route({
    method: 'GET',
    url: '/healthcheck',
    schema: {
        response: {
            200: JSENDSuccessSchema(HealthcheckSuccessSchema),
        },
    },
    handler: [...]
    }
})
```

HealthcheckSuccessSchema is just:

```
const HealthcheckSuccessSchema = Type.Object({
    timestamp: Type.String(),
})
```

and JSENDSuccessSchema is:

```
const JSENDSuccessSchema = <T extends TSchema>(type: T) => Type.Object({
    status: Type.Literal('success'),
    data: type,
})
```

That code is working with no issues while using Typebox v0.20.6
As soon as I upgrade to Typebox v0.21+ (currently v0.22.1) it fails with this:

```
Argument of type 'TObject<{ timestamp: TString; }>' is not assignable to parameter of type 'TSchema'.
  Type 'TObject<{ timestamp: TString; }>' is not assignable to type 'TVoid'.
    Type 'TObject<{ timestamp: TString; }>' is not assignable to type '{ kind: unique symbol; type: "void"; }'.
      Types of property 'kind' are incompatible.
        Type 'typeof import("/Users/coolio/Documents/typeboxtest/fastifyapi/node_modules/@sinclair/typebox/typebox").ObjectKind' is not assignable to type 'typeof import("/Users/coolio/Documents/typeboxtest/fastifyapi/node_modules/typebox_schemas/node_modules/@sinclair/typebox/typebox").VoidKind'.ts(2345)
```

Thanks in advance.

**Comment by sinclairzx81** [comment]
@cooliopas Hi, just ensure you've updated TypeBox 0.22.1 on both projects, and double check that each reference the exact same version, which may involve building the declarations for the depended project once you've updated. (there has been significant updates from 0.21.0 and 0.22.0 inline with TypeScript 4.5, so you will want to be on the latest version)

The generated declaration files should be fine so long as each of your declarations import from `@sinclair/typebox`. It's possible that TypeScript may be interpreting the these imports differently (for example, it seems to be complaining that the symbols for `kind` are incompatible, suggesting it's seeing two versions of the same Symbol referenced from different locations).

Let me know if that helps
Cheers
S

**Comment by cooliopas** [comment]
You were right!
I fully deleted 'node_modules' and all the built files from both projects and it is working now!!
Sorry to bother you, I was sure I did that already, but seems I was doing it wrong.

Thanks for your help and for the great work on Typebox. Its amazing.
