### ISSUE TITLE
Type coercion

### ISSUE THREAD

**Issue by MichielDeMey** [sinclairzx81/typebox#126]
I noticed when using [type coercion](https://ajv.js.org/coercion.html) (specifically array) that validation would pass, but the value itself remained unchanged.

ajv instance config:
```ts
const ajv = addFormats(
  new Ajv({
    coerceTypes: 'array', // coerce arrays only
  }),
  ['email']
)
```

schema example:
```ts
Type.Object(
  {
    tags: Type.Array(Type.String())
  },
  { additionalProperties: false }
);
```

payload:
```json
{
  "tags": "foo"
}
```

I believe Typebox does not support coercion?
Would it be possible to implement?

**Comment by sinclairzx81** [comment]
@MichielDeMey Hi. TypeBox only supports JSON schema and not specific vendor functionality. Coercion of data is interesting, but as far as I know it only relates to AJV and there wouldn't be a way to inform TypeBox it it statically resolve types differently based on the configuration of AJV, at least not without TypeBox taking AJV as a direct dependency. So don't think this is something I can support.

Out of interest, what was your use case for needing this functionality?

**Comment by sinclairzx81** [comment]
@MichielDeMey Might close off this issue as I don't think ill be able to support AJV type coercion in TypeBox. TypeBox does mirror TypeScript and was wondering what a TypeScript interpretation of type coercion would look like. The only reasonable solution I could imagine was implementing TS conditional mappings downstream from the initial type where you can encode the rules for coercion. 

```typescript
interface Item {
   tags: string
   id: number
}

type Rule<T>= 
   T extends string ? string[] :
   T extends number ? number[] :
   T extends boolean ? boolean[] :
   T
 
type Coerce<T> = { [K in keyof T]: Rule<T[K]> }

type T = Coerce<Item> // { tags: string[], id: number[] }

// or optionally

type T = Coerce<Static<typeof Item>> // if Item was a TypeBox type
```

Mapping rules in this way is interesting so ill give it some more thought (it may be useful for conditionally mapping custom schema which is an ongoing work in progress), but implementing AJV specifics is generally out of scope for TypeBox.

Thanks for the suggestion tho
Cheers 
S

**Comment by MichielDeMey** [comment]
Hey @sinclairzx81, thanks for the reply.

I do agree with your thoughts that Typebox should not necessarily implement AJV-specific functionality such as type coercion, but it's nice to see that you're thinking of typing the behaviour.

---

Our use-case specifically is forcing data from query parameters or form fields to be in the form of an array.

Usually query parameters are serialized as `?tag=foo&tag=bar` resulting in the HTTP framework parsing them as an array.
e.g. `"tag" = ["foo", "bar"]`.

However, when only a single tag is present `?tag=foo`, most HTTP frameworks will interpret "tag" as a single string instead of an array of strings.
e.g. `"tag" = "foo"`

The same happens to form fields
e.g. `<input id="tag" name="tag" value="foo" />`

Hence we use AJV to coerce specific values from the body to their respective array form to prevent having to create the JSON schema as

```json
{
  "type": ["array", "string"]
  "items": {
    "type": "string"
  }
}

```

and then checking and coercing the value in the application code

```ts
const { tag } = req.query

let tags = tag
if (typeof tag === 'string') tags = [tag]

// tags will now always be an array regardless of how many were passed
```

We can still coerce everything outside the scope of AJV of course, but as you can see the schema is a bit more extensive and it requires some more application logic to deal with those values.
