### ISSUE TITLE
help: Typing MongoDB ObjectID

### ISSUE THREAD

**Issue by SherloxTV** [sinclairzx81/typebox#131]
Hi ! I'm trying to setup a pretty advance type checking system for a Fastify API using Typebox , Mongoose & Typescript.

I'm trying to create an helper function to type populatable fields in Typebox schemas:

`@helpers/typebox.ts`
```typescript
import { TProperties, TObject, TUnion, TString, Type } from '@sinclair/typebox'

export const TypeboxPopulatableField = <T extends TProperties>(Schema: TObject<T>): TUnion<[TString, TObject<T>]> => {
  return Type.Union([Type.String(), Schema])
}
```

that I then use this way:
`@modules/demo/schema.ts`
```typescript
import { Static, Type } from '@sinclair/typebox'
import { TypeboxPopulatableField } from '@helpers/typebox'

import { UserBodySchema, UserSchema } from '@modules/users/schema'

/**
 * body / entity schemas & interfaces
 */

// schema & interface for POST / PUT body
export const DemoBodySchema = Type.Object(
  {
    name: Type.String(),
    owner: UserBodySchema,
  },
  { additionalProperties: false }
)
export type TDemoBody = Static<typeof DemoBodySchema>

// extend body schema & interface for database entity
export const DemoSchema = Type.Object(
  {
    ...DemoBodySchema.properties,
    _id: Type.String(),
    createdAt: Type.String({ format: 'date-time' }),
    updatedAt: Type.Optional(Type.String({ format: 'date-time' })),

    owner: TypeboxPopulatableField(UserSchema), // <----------------------------- HERE
  },
  { additionalProperties: false }
)
export type TDemo = Static<typeof DemoSchema>

/**
 * requests / responses schemas
 */

export const createDemoSchema = {
  body: DemoBodySchema,
  response: {
    200: DemoSchema,
  },
}

export const getDemoSchema = {
  response: {
    200: DemoSchema,
  },
}
```

So far so good, as the type of the `owner` property is now:
```
TUnion<[TString, TObject<{
  _id: TString;
  createdAt: TString;
  updatedAt: TOptional<TString>;
  username: TString;
  email: TString;
}>]>
```

But I'm running into an issue when using the generated type in Mongoose:
```typescript
import mongoose, { Types } from 'mongoose'

import { TDemo } from './schema'

const Schema = mongoose.Schema

const DemoSchema = new Schema<TDemo>(
  {
    name: {
      type: String,
      required: true,
    },
    owner: {
      type: Types.ObjectId,
      ref: 'User',
      required: true,
    },
  },
  {
    timestamps: true,
  }
)

export default mongoose.model<TDemo>('Demo', DemoSchema)
```

Here I get the error:
```
Type '{ type: typeof Types.ObjectId; ref: string; required: true; }' is not assignable to type 'SchemaDefinitionProperty<string | { updatedAt?: string | undefined; name: string; username: string; email: string; firstname: string; lastname: string; roles: StaticArray<TString>; _id: string; createdAt: string; }> | undefined'.
  Types of property 'type' are incompatible.
    Type 'typeof ObjectId' is not assignable to type '"string" | { updatedAt?: string | undefined; name: string; username: string; email: string; firstname: string; lastname: string; roles: StaticArray<TString>; _id: string; createdAt: string; } | ... 6 more ... | undefined'.
```

I've been searching and experimenting for the past 4-5 hours but I can't find anything in the docs that could help me.

Do you have any idea how I could somehow type the ObjectId in Typebox, so I can use it instead of using `Type.String()` so I don't get this error anymore ?

Thanks in advance !

**Comment by sinclairzx81** [comment]
@SherloxTV Hi,

As far as I know, a `ObjectId` when serialized to JSON is a 24 character string value. So the correct way to validate that would be to use either `Type.String()` or `Type.Regex()`. The statically inferred type can only be a string. So the following should validate such a string.

```typescript
import { Type, Static } from '@sinclair/typebox'

const ObjectId = Type.RegEx(/^[0-9a-fA-F]{24}$/) // alphanumeric strings of length 24
```
However, if you want to try and support both strings and `ObjectId`, this is somewhat possible, but would be a bit outside the usual. (I wouldn't recommend)

```typescript
const TObjectId = Type.Union([
    Type.RegEx(/^[0-9a-fA-F]{24}$/),      // Serialized
    Type.Object({                         // Non-Serialized
        _bsontype:      Type.Literal('ObjectID'),  
        generationTime: Type.Integer(),
        id:             Type.Any()   
    })
])
```
I'm guessing most people receive the validated `string` value for the id, and then wrap it in a `new ObjectId(obj.id)` before passing to Mongo. It's been a while, but doesn't Mongoose allow you to pass string values for the id's?

Hope this helps
S

**Comment by SherloxTV** [comment]
Hi, thanks for you answer ! If I omit the union thing, the underlying problem is that the Mongoose types won't accept a `string` type for a `ObjectId` field when declaring the schema.
```
Type '{ type: typeof mongoose.Types.ObjectId; ref: string; required: true; }' is not assignable to type 'SchemaDefinitionProperty<string> | undefined'.
  Types of property 'type' are incompatible.
    Type 'typeof ObjectId' is not assignable to type '"string" | StringConstructor | "String" | typeof String | undefined'.
      Type 'typeof ObjectId' is missing the following properties from type 'StringConstructor': fromCharCode, fromCodePoint, raw
```

The problem is between these two parts of the code:
```
export const DemoSchema = Type.Object(
  {
    ...DemoBodySchema.properties,
    _id: Type.String(),
    createdAt: Type.String({ format: 'date-time' }),
    updatedAt: Type.Optional(Type.String({ format: 'date-time' })),

    owner: Type.String(), // <----------------------------- HERE
  },
  { additionalProperties: false }
)
export type TDemo = Static<typeof DemoSchema>
```

```
const DemoSchema = new Schema<TDemo>(
  {
    name: {
      type: String,
      required: true,
    },
    owner: {
      type: Types.ObjectId, // <----------------------------- HERE
      ref: 'User',
      required: true,
    },
  },
  {
    timestamps: true,
  }
)
```

So I guess what I'm looking for is a way of inferring / importing the interface from the `mongoose.Types.ObjectId` class into a `TObject` automatically or do I need to type it by hand (meaning it will need to be maintained) ?

Thanks a lot

**Comment by sinclairzx81** [comment]
@SherloxTV Hi. Yeah, this may not be the ideal way to approach this. TypeBox is only really useful for creating schematics for data you intend to send and receive over IO (Http, StdIo, etc). If you want to send a Mongo identifier over a network, you need to serialize it first. When you serialize a Mongo `ObjectId` in Node, it returns to you a string. So....

```typescript
const id = new ObjectId()

const json = JSON.stringify({ id })

// const json = '{ "id": "<24-character-hex-string>" }'
```
In this regard, you would create TypeBox type to ensure the receiving side gets the expected string.

```typescript
const Data = Type.Object({ 
   id: Type.RegEx(/^[0-9a-fA-F]{24}$/) 
})
```
When the receiving side receives this data, it would first validate the string, then manually convert the string into a `ObjectId`. This needs to happen "after" the validation has run.

```typescript
function receive(data: Static<typeof Data>) {

    if(!validate(Data, data)) throw Error('Invalid data received')

    const id = new ObjectId(data.id) // you need to manually create the ObjectId from string
    
    // do mongo stuff here
}
```
This last step is annoying, but is required if the Mongo driver expects type `ObjectId`. The issue really comes down to how the `ObjectId` is being serialized over the wire. Of course, there would be numerous ways to automatically convert valid `string` ids into `ObjectId`, but this extra functionality is beyond the scope of TypeBox (which will only tell you the serialized string id is valid).

Hope this helps
S

**Comment by sinclairzx81** [comment]
Will close this issue off. Good luck!

**Comment by SherloxTV** [comment]
Thanks a lot for your time !
