### ISSUE TITLE
Static type from Schema does not expand StaticArray type breaking TypeScript inferred return types in other projects TS2742

### ISSUE THREAD

**Issue by bjbrewster** [sinclairzx81/typebox#137]
Hello, 

This is a bit of a weird bug and may well be a TypeScript compiler issue due to heavy templating.  

I am creating an object schema in one TypeScript project with an array property and exporting the type using `export type Config = Static<typeof ConfigSchema>`. When I use the Config type in another project that has `tsconfig.json` compiler option `"declaration": true` to generate `types.d.ts` then I get TypeScript error TS2742 `The inferred type of "getDevices" cannot be named without a reference to '../server/node_modules/@sinclair/typebox/typebox'. This is likely not portable. A type annotation is necessary.`  

Isolated example from 2nd project:
```typescript
import { Config } from 'server/types'
interface State {
  config: Config;
}

// This line has error TS2742 which can be fixed by adding explicit return type `Config`.
export const getConfig = (state: State): Config => state.config

// This line also has error TS2742 along with all other selectors where there is an array property in object type hierarchy.
// This could be fixed by adding explicit return type `Config['devices']` but there are many other selectors that would require very deep complex access into Config type.
export const getDevices = (state: State) => getConfig(state).devices
```

On looking into this issue, I noticed all array types in objects are being reported as `StaticArray<...>` like `StaticArray<TString>` or `StaticArray<TObject<{ id: TString; enabled TBoolean; }>>` instead of `string[]` or `{ id: string; enabled: boolean; }[]`, even in the source project. All other types are expanded to simple TypeScript types as you would expect.  **For some reason, TypeScript is not expanding the StaticArray type like others**.  

If I edit the Typebox `types.d.ts` file and change interface TArray `$static` prop from `StaticArray<T>` to `Array<Static<T>>` then the error goes away and named inferred return types works.

This only seems to happen to array property in objects. For `const schema = Type.Array(Type.String())`, the type `Static<typeof schema>` is `string[]` as expected.

Here is a Code sandbox demonstrating the issue: https://codesandbox.io/s/elegant-perlman-nm0t6?file=/src/index.ts

```typescript
import { Type, Static, TLiteral, TUnion } from "@sinclair/typebox";

// StringUnion from typebox readme
type IntoStringUnion<T> = {
  [K in keyof T]: T[K] extends string ? TLiteral<T[K]> : never;
};
const StringUnion = <T extends string[]>(
  values: [...T]
): TUnion<IntoStringUnion<T>> => ({ enum: values } as any);

enum TestEnum {
  A,
  B,
  C
}

const schema = Type.Object({
  as: Type.Array(Type.String()),
  a: Type.Any(),
  l: Type.Literal("blah"),
  b: Type.Boolean(),
  i: Type.Integer(),
  k: Type.Unknown(),
  n: Type.Number(),
  s: Type.String(),
  u: Type.Union([Type.Number(), Type.String()]),
  su: StringUnion(["A", "B", "C"]),
  z: Type.Null(),
  e: Type.Enum(TestEnum),
  o: Type.Object({
    a: Type.String(),
    b: Type.Number()
  })
});

type Test = Static<typeof schema>;
```

Test has the following type signature as seen by highlighting the Test type in Codesandbox. All the types are expected except for the array type:
```typescript
type Test = {
  as: StaticArray<TString>;
  a: any;
  l: "blah";
  b: boolean;
  i: number;
  k: unknown;
  n: number;
  s: string;
  u: string | number;
  su: "A" | "B" | "C";
  z: null;
  e: TestEnum;
  o: {
      a: string;
      b: number;
  };
}
```

If you change the TArray $static prop from `StaticArray<T>` to `Array<Static<T>>` then string array is as expected:
```typescript
type Test = {
  as: string[];
  ...
}
```

Can the TArray $static prop please be updated (I can create Pull Request if you like). I'm not sure why all other template types are expanded but this one type is causing issues.  

Many thanks,
Brendan

**Comment by sinclairzx81** [comment]
@bjbrewster Hi, 

The type `StaticArray<T extends TSchema>` is just an alias for `Array<Static<T>>` which infers as `T[]`, so you should be able to use these types interchangeably. The reason TypeScript doesn't report `string[]` has to do with how the language service chooses to report on the type. 

```typescript
export type StaticArray<T extends TSchema> = Array<Static<T>>
```
So for example, consider the following example, and link [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUFIRS4CuCQjsW8ZHAC8KYQDoAglCgFUACjSZd+KBwDmpgJQP5ilwqGYUWvIWIkAPB4YEFQoAHxw-PxewCxwajbstgDaALpS5DJyikoqal7aFhi6APIiAFYYJDCm2TmKACZEBABcOpaGxmZFVjCJ9k6R0bFwUBiQsBgNcARx+ESknSb+yNZ2YW4UzptBBT4LAUEh4TI5yqrwAG4EXACuGG0a2nX1cE2EbckMABYYXFwQBg4BgAd2gXAaDFSQzgujhIlu8HmfiWqBWaySERG5Vu+QI7BmXGAs2o0HifTsaU2mUyQA)

```typescript
import { Type, Static } from '@sinclair/typebox'

{
    const T = Type.Array(Type.String())
    
    type T = Static<typeof T> // T is string[]
}

{
    const T = Type.Object({
        data: Type.Array(Type.String()) // is reported by the LS as StaticArray<TString>
    })

    type T = Static<typeof T>

    const value: T = {
        data: ['hello', 'world'] // ... but is just an alias for string[]
    }
}
```
My preference would be to retain `StaticArray<T>` as it provides a clean mechanism to further conditionally map Arrays in future (vs moving that mapping logic to the `TArray.$static` property).

This particular error looks like a might be a dependency problem between Project 1 and Project 2 (where Project 2 can't resolve TypeBox, and thus, can't infer the correct type). If Project 1 is compiled to a .d.ts, can you quickly confirm that the compiled Project 1 .d.ts appropriately imports `@sinclair/typebox` (which should make the types available to Project 2)?

**Comment by sinclairzx81** [comment]
@bjbrewster Going to close this issue. It sounds like a dependency issue. I would check that either Project 1 appropriately exports TypeBox such that Project 2, or Project 2 takes TypeBox as a direct dependency. This will allow Project 2 to infer types. 

If you're still having problems, feel free to re-open the issue and can take a deeper look. Some users do experience problems with mono repositories, so would be good to put some documentation / guidelines in place for sharing types from a common project.

Cheers
