### ISSUE TITLE
Regarding readme comments on OpenAPI

### ISSUE THREAD

**Issue by Relequestual** [sinclairzx81/typebox#138]
From OpenAPI 3.1, full JSON Schema is supported by default, and there is no divergance.
OpenAPI 3.1 does use its own JSON Schema Dialect (set of keywords) by default, which adds two keywords.
You can specify to use pure JSON Schema.

Tooling is catching up, but it might be worth mentioning this in the readme.
I guess this might also effect the implementation, but having just (re)found this library, I don't honestly know.

**Comment by sinclairzx81** [comment]
@Relequestual Hi, thanks for the info.

Would happy to update the OpenAPI documentation at some point in the future (I guess once 3.1 settles a bit). I did read OpenAPI were aligning with the JSON Schema specification (at long last), however I do still get quite a few questions on OpenAPI usage, usually around whether TypeBox should support `nullable` as per previous specifications. I feel the current documentation is fairly in tune with the current state of things, unless there was something specific you would like added/changed?

TypeBox has always been tied specifically to the JSON Schema specification and doesn't actually implement any keyword extensions for OpenAPI; so there shouldn't be any updates required to support OpenAPI 3.1. It really is good news to hear they are finally aligning with the specification. 

Cheers
S

**Comment by sinclairzx81** [comment]
@uwinkelvos Hi Thanks :) Yeah ok, can update the documentation for Open API and mention that it pertains to 3.0 and below. Just give me a day or so to read up on the current state of things in Open API.

> ... it would be really nice if those functions were available as a module instead of prosa: Something like contrib/openapi-3_0.ts. Would you be willing to accept a PR for this? 

Thanks for the offer, But I'm pretty set on having TypeBox only provide JSON Schema specific types. Extended types (such as, but not limited to OpenAPI) are best implemented downstream, either via external package, or within a given project. This is largely to avoid TypeBox having to maintain multiple specifications (where TypeBox exclusively focuses on JSON Schema drafts). Ideally I'd like to make building custom schema representations approachable as possible, so mostly interested in way to make streamlining this functionality easier without explicitly implementing extended schemas as part of the library. Unfortunately including a OpenAPI `contrib` module would require maintenance of the module, and be tangential to the goals of the project overall. Hope you understand.

Thanks again, will look at updating the documentation within the next few days.
S

**Comment by sinclairzx81** [comment]
@Relequestual @uwinkelvos Hi, can replace the OpenAPI documentation with the following copy if everyone is in agreement.

> TypeBox can be used to create schemas for OpenAPI, however users should be mindful of some disparities between the JSON Schema and OpenAPI for OpenAPI versions prior to OpenAPI 3.1. Two common instances where OpenAPI diverges is the handling nullable and string enum schemas types. The following shows how you can use TypeBox to construct these types.

Let me know
S

**Comment by uwinkelvos** [comment]
> Thanks for the offer, But I'm pretty set on having TypeBox only provide JSON Schema specific types. Extended types (such as, but not limited to OpenAPI) are best implemented downstream, either via external package, or within a given project. This is largely to avoid TypeBox having to maintain multiple specifications (where TypeBox exclusively focuses on JSON Schema drafts). Ideally I'd like to make building custom schema representations approachable as possible, so mostly interested in way to make streamlining this functionality easier without explicitly implementing extended schemas as part of the library. Unfortunately including a OpenAPI `contrib` module would require maintenance of the module, and be tangential to the goals of the project overall. Hope you understand.
That's completely valid of course. Providing it as a 3rd party module is actually way cleaner.

> TypeBox can be used to create schemas for OpenAPI, however users should be mindful of some disparities between the JSON Schema and OpenAPI for OpenAPI versions prior to OpenAPI 3.1. Two common instances where OpenAPI diverges is the handling nullable and string enum schemas types. The following shows how you can use TypeBox to construct these types.
:+1:

**Comment by sinclairzx81** [comment]
@Relequestual @uwinkelvos Cool, have made these amendments to the documentation. Thanks for reporting. Open API 3.1 sounds like it's going to be great!

Cheers
S
