### ISSUE TITLE
Inverse on Nullable(...)

### ISSUE THREAD

**Issue by maolimu** [sinclairzx81/typebox#139]
Thx for the great sample how to use a generic function to create a shortcut for nullable.

I am trying to figure out how to do the inverse - remove Type.Null() and the enclosing union from a defined property. Any direction you can head me to?

**Comment by sinclairzx81** [comment]
@maolimu Hi. TypeBox works the same as TypeScript where there is no trivial way to remove a type from a union. (other than to narrow it before use). Generally, If you have a type which has a potential to be `null`, it's usually best treat it as such, consider the following.

### TypeScript
```typescript
function test(value: string | null) {
    if(value !== null) { // narrow
        const s = value.toLowerCase() // ok - value is string
    }
}
```
### TypeBox
```typescript
import { Type, Static } from '@sinclair/typebox'

const T = Type.Union([Type.String(), Type.Null()])

function test(value: Static<typeof T>) {
    if(value !== null) { // narrow
        const s = value.toLowerCase() // ok - value is string
    }
}
```
### Extracting Type from Union

If you just need to extract a specific type from a Union, you can use the following.

```typescript
import { Type, Static } from '@sinclair/typebox'

const T = Type.Union([
    Type.Number(),
    Type.String(),
    Type.Boolean(), 
    Type.Null()
])

// Extract the type from the JSON Schema anyOf array
const A = T.anyOf[0] // TNumber
const B = T.anyOf[1] // TString
const C = T.anyOf[2] // TBoolean
const D = T.anyOf[3] // TNull

type T = Static<typeof T> // number | string | boolean | null
type A = Static<typeof A> // number
type B = Static<typeof B> // string
type C = Static<typeof C> // boolean
type D = Static<typeof D> // null
```
Just be mindful the above isn't generally recommended as there are better ways to achieve the same result without reading into the JSON Schema object, consider...
```typescript
import { Type, Static } from '@sinclair/typebox'

const A = Type.Number()
const B = Type.String()
const C = Type.Boolean()
const D = Type.Null()
const T = Type.Union([A, B, C, D])

type T = Static<typeof T> // number | string | boolean | null
type A = Static<typeof A> // number
type B = Static<typeof B> // string
type C = Static<typeof C> // boolean
type D = Static<typeof D> // null
```

Hope that helps!
S

**Comment by sinclairzx81** [comment]
@maolimu Actually, there may be a way to implement the following Utility Types in TypeBox. See this issue https://github.com/sinclairzx81/typebox/issues/140

### Exclude<UnionType, ExcludedMembers>

https://www.typescriptlang.org/docs/handbook/utility-types.html#excludeuniontype-excludedmembers

### Extract<Type, Union>

https://www.typescriptlang.org/docs/handbook/utility-types.html#extracttype-union

To implement this properly, TypeBox would need to implement some form of conditional mapping (essentially checking one schema extends another). See issue https://github.com/sinclairzx81/typebox/issues/140.

Will spend some time thinking about this, it might be a good addition to the library.

**Comment by mmunte-impeo** [comment]
@sinclairzx81 thank you so much for taking the time for such a detailed explanation. Immensely appreciated. 

I‘ve been using typebox and with fastify intensively this week. This is a very effective combination, a joy to use. 

I have re-designed the schemas and types at least 3 times by now, as with more use and knowledge of how it works, new ideas arise how to streamline things. 

For the biggest part I am defining the „complete“ schemas first, and then using mostly pick to then create narrower variants. This works well in mist cases, but here and there just picking is not enough and types need to change to/from nullable. 

I will try out your suggestions tomorrow. 

Fantastic library. Thank you!

**Comment by eladchen** [comment]
Is there a way to turn a property into a required property?

```js
const someSchema = Type.Object({
  id: Type.Optional(Type.String()),
  name: Type.Optional(Type.String()),
})

const modifiedSchema = Required(someSchema, "id", "name");
```

**Comment by sinclairzx81** [comment]
@eladchen Hi, apologies for the slow reply. It is possible to make selective properties required (or optional), but you will need to deconstruct the schema using `Type.Pick()` and `Type.Omit()` and reconstruct a new schema via `Type.Intersect()`, as follows.

```typescript
const someSchema = Type.Object({
  id: Type.Optional(Type.String()),
  name: Type.Optional(Type.String()),
})

const modifiedSchema = Type.Intersect([
    Type.Pick(someSchema, ['id']), 
    Type.Required(Type.Pick(someSchema, ['name']))
])

type T = Static<typeof modifiedSchema>

// type T = {
//     id?: string | undefined;
// } & {
//     name: string;
// }
```
Hope that helps
S
