### ISSUE TITLE
[Feature Proposal]: A way to extract sub-schemas (of properties or items)

### ISSUE THREAD

**Issue by openreply-dleinhaeuser** [sinclairzx81/typebox#140]
Hi,

I think it would be great to have a way to extract sub-schemas from a given Typebox schema.
Much like `ObjectType["propertyName"]` gives you the type of a property of an object type, a function like `Type.Extract(ObjectTypeSchema, propertyName)` would return the schema for a property.
Similarly something like `Type.Items(ArrayTypeSchema)` could return the schema that describes the type of items in the array (`ArrayType[number]` in TypeScript, I think).

**Comment by sinclairzx81** [comment]
@openreply-dleinhaeuser Hi, TypeScript supports the `Extract` utility type  https://www.typescriptlang.org/docs/handbook/utility-types.html#extracttype-union which technically could be implemented in TypeBox, however matching the union against the type would involve a fair amount of sophistication to implement. 

```typescript
type A = { a: string }
type B = { a: string }
type C = A | B
type D = Extract<A, C> // D as A
```

```typescript
const A = Type.Object({ a: Type.String() })
const B = Type.Object({ b: Type.String() })
const C = Type.Union([A, B])
const D = Type.Extract(A, C) // D as A
```
I would be happy to implement this feature, but it would require a very concise implementation of schema narrowing and produce an output schema that lines up to the TS type system. I think implementing this JSON Schema algorithm would a good first step. There would actually be two utility types worth implementing.

```typescript
/**
 * Exclude from T those types that are assignable to U
 */
type Exclude<T, U> = T extends U ? never : T;

/**
 * Extract from T those types that are assignable to U
 */
type Extract<T, U> = T extends U ? T : never;
```
Maybe the best place to start would be implementing the extends algorithm. This function would need to compare left and right schemas, and answer the question if one extends the other (based on TS union checks)

```typescript
/** Checks if left extends right using TS conditional mapping extends rules */
private Extends<Left extends TSchema, Right extends TSchema,>(left: Left, right: Right): boolean {
    return (left extends right) // todo: implement this logic
}
```

It's an interesting idea, will give this some thought.
Cheers
S

**Comment by sinclairzx81** [comment]
@openreply-dleinhaeuser Hi. Just a follow up on this issue.

I have explored implementing conditional type mapping for TypeBox here https://github.com/sinclairzx81/sidewinder/blob/extends/libs/type/extends.ts, however the implementation turned out to be too top heavy for the TypeBox, with many caveats to get true alignment with TypeScript's structural type checker.

I may review this in future once the TypeScript type system has settled down, but for now will be putting this investigation on the back burner.

Will close off this issue for now
Many Thanks
S
