### ISSUE TITLE
Feature: Generating Typebox types from JSON Schema

### ISSUE THREAD

**Issue by ShivamJoker** [sinclairzx81/typebox#141]
It would be great to have a plugin or cli tool which can convert JSON schemas into typebox schemas

**Comment by mindplay-dk** [comment]
Sounds like this might belong in [quicktype](https://quicktype.io/) maybe? It handles many input and output formats.

**Comment by ShivamJoker** [comment]
Yeah it does but it wont be in typebox format

**Comment by sinclairzx81** [comment]
@mindplay-dk @ShivamJoker Hi. I think this would be a cool feature. However as code generation would be required, such a feature is probably best expressed either as an auxiliary library (one users could run locally via CLI) or perhaps offered as a tool on a TypeBox website (something I've been considering for a while).

As this feature wouldn't be part of the TypeBox library itself, will close off this issue. I will however consider this as a feature once a TypeBox website gets put together (at some point in the future). Once where users could post JSON schema into a text area, which translates it into the best fit TypeBox type.

Thanks for the suggestion!
Cheers
S
