### ISSUE TITLE
How to build a single output schema?

### ISSUE THREAD

**Issue by mindplay-dk** [sinclairzx81/typebox#143]
How do I combine multiple types into a single output schema?

Something like this sample schema from quicktype.io:

<details>
<summary>example</summary>
<pre>
{
  "$ref": "#/$defs/Pokedex",
  "$defs": {
    "Pokedex": {
      "type": "object",
      "additionalProperties": false,
      "description": "A collection of pokémon",
      "properties": {
        "pokemon": {
          "type": "array",
          "description": "All pokémon contained in the pokédex",
          "items": {
            "$ref": "#/$defs/Pokemon"
          }
        }
      },
      "required": [
        "pokemon"
      ],
      "title": "Pokedex"
    },
    "Pokemon": {
      "type": "object",
      "additionalProperties": false,
      "description": "A 'pocket monster.' One must catch them all.",
      "properties": {
        "id": {
          "description": "A unique identifier for this pokémon.\nHigher ids generally imply rarer and more evolved pokémon.",
          "type": "integer"
        },
        "num": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "img": {
          "description": "Photographic evidence of this pokémon's existence",
          "type": "string"
        },
        "type": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Type"
          }
        },
        "height": {
          "type": "string"
        },
        "weight": {
          "type": "string"
        },
        "candy": {
          "description": "The flavor of candy preferred by this pokémon",
          "type": "string"
        },
        "candy_count": {
          "type": "integer"
        },
        "egg": {
          "type": "string",
          "enum": [
            "2 km",
            "Not in Eggs",
            "5 km",
            "10 km",
            "Omanyte Candy"
          ],
          "title": "egg"
        },
        "spawn_chance": {
          "type": "number"
        },
        "avg_spawns": {
          "type": "number"
        },
        "spawn_time": {
          "type": "string"
        },
        "multipliers": {
          "oneOf": [
            {
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            {
              "type": "null"
            }
          ],
          "title": "multipliers"
        },
        "weaknesses": {
          "type": "array",
          "description": "Types of pokémon that cause extra damage to this pokémon",
          "items": {
            "$ref": "#/$defs/Type"
          }
        },
        "next_evolution": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Evolution"
          }
        },
        "prev_evolution": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Evolution"
          }
        }
      },
      "required": [
        "avg_spawns",
        "candy",
        "egg",
        "height",
        "id",
        "img",
        "multipliers",
        "name",
        "num",
        "spawn_chance",
        "spawn_time",
        "type",
        "weaknesses",
        "weight"
      ],
      "title": "pokemon"
    },
    "Type": {
      "type": "string",
      "enum": [
        "Fire",
        "Ice",
        "Flying",
        "Psychic",
        "Water",
        "Ground",
        "Rock",
        "Electric",
        "Grass",
        "Fighting",
        "Poison",
        "Bug",
        "Fairy",
        "Ghost",
        "Dark",
        "Steel",
        "Dragon"
      ],
      "title": "type"
    },
    "Evolution": {
      "type": "object",
      "additionalProperties": false,
      "description": "A description of an evolutionary stage of a pokémon",
      "properties": {
        "num": {
          "description": "The number of the pokémon to or from which the containing pokémon evolves",
          "type": "string"
        },
        "name": {
          "description": "The name of the Pokémon to or from which the containing Pokémon evolves",
          "type": "string"
        }
      },
      "required": [
        "name",
        "num"
      ],
      "title": "_evolution"
    }
  }
}
</pre>
</details>

That is, all the types exported, with a designated top-level type.

Looking at the [reference types](https://github.com/sinclairzx81/typebox#reference-types), take the `Math3D` example - how would you go about exporting both of these as a single schema?

I need something that works with quicktype.

If I export just the namespace, there is no designated top-level type, so that doesn't work.

And `Static` doesn't seem to work with namespaces?

I've tried everything I could think of.

**Comment by mindplay-dk** [comment]
It looks like I've solved this.

I'm using a `Type.Namespace` just for the export, and manually specifying the top-level `$ref` on it:

```ts
import { Static, Type } from "@sinclair/typebox";
import { A, B, C } from "./my-code";

const namespace = Type.Namespace(
  {
    A,
    B,
    C,
  },
  {
    $ref: "A",
  }
);

console.log(JSON.stringify(namespace, null, 2));
```

This appears to produce a working JSON schema.

(well, at least it passes validation - although for some reason it [crashes quicktype](https://github.com/quicktype/quicktype/issues/1629)...)

This *only* works because every single type has a `$id` - the `Type.Namespace` method won't actually validate generated `$ref` inside the types, so if you forgot to define a `$id` for any of the types (including the top-level type) you get invalid schema. (!)

Perhaps the documentation should more clearly explain what `Type.Namespace` is intended for? It doesn't produce types that work with `Static`, and my guess is, maybe it was actually intended just for this kind of thing? Combining your individual types into a single JSON schema for output, or for run-time validation with a library?

(...this is my first real foray with JSON schema, so maybe it's just me being a clown..?) 🤡

**Comment by sinclairzx81** [comment]
@mindplay-dk Hi. 

The following is a quick rebuild of that schema using TypeBox (with descriptions and titles omitted). A TypeScript Playground link can be viewed [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwIYGcUA0cAyjNjMAMZwC+cAZlBCHAOQACuwAdpQDbZgUAPQx0GAEYQAHqwCwAKEWUI3XPACiANwh8ArhVVwAvCgB0AeQkArDJRgAKBIrhxuekAC5zpKDwDmDgCUBC5u2CAY3shmvgHBijRESAAkwAAm3qzaugbAqqxE2OnpwIbc2HwACkyYsMAYuN70lbhYNEGKyqrqKOIm5gCq3PncDgDaYTEAMmUYUJUOrABiQhisIVNmszDzi6wAkpTrmwquM3MLfEvLfKgBG6Fn5jt716xVuKiUABZUj1tXlclgB1cjzAHPC67YGsADiTD03HSkPO20u+wAShBKABrVEvDHvDR8OwwPyUAnQt5LBF4XBU9Ew-arfw-CjcfyMoH7KoQYC4AqnNE894AIT0XOFhOZ72WgigqG5RNpPwg6mVsqWABFsFB8dLqbDSBgMHxNTTWNqFv4hYoALrJNKZNhoTCsDpdBQqNTwPm4jAgIymGJWWz2JxhDLRMwHbi7fzzYJPVzuLw+cnxaUVSIxuKc5NRkD+POZgvSsSYGMAQSgC1QDhimIw9Eb4iC0p+GGAbJgpb85ZTcAA7hkYD9+1mh5RsMjUJPB2EZ3OAPoqJF98xxhNJ6UYfwloYjVQTMIilWsABMcFxIAJ561rAAchB4Dw4BoDwzpQ-LQBWG87x-GVLQARgABkA+8QNhCwQFnVBdjgABhWd0iVTpnntaVcDAbBh24NcflnY4YyfDwJF3IdsC0fwV1w-C1DIiiqLCBiCJXChcwzAdAmlEA9D4CgwD4BooCaI9RgmGJa3rRszHIkBKKgYIQnMci+GuIJsKHYcMGwXFuEaNoJJkutsAbJsWzbTAOyHIzpBgFcMB0fRyhrczLLMZtWxyNzRjssIwCgFznNcvJVA8uSrN88LykChQkkQOBnSyf1AwKWhMO6X04HS9IMGkAZQxsMlI2eSAAyDbgoos+SfIcdLqo7RJkhS6M2HywrWCyr1hGEOAAFphpG0axvGibJqm6bBsUfqUEaGA5oGmbVrW9bxq9egkXsUY4F2dQHEqjACukbxSHIKgAB5KwwCB6DyiAA1OgA+IJECXHpdAwMw+AgQJjtOsxjuq8ZwPtMwcwwTCaCAA)

```typescript
import { Type as T, Static } from '@sinclair/typebox'

const Evolution = T.Object({
  num: T.String(),
  name: T.String()
}, { $id: 'Evolution', additionalProperties: false })

const Type = T.Union([
  T.Literal('Fire'),
  T.Literal('Ice'),
  T.Literal('Flying'),
  T.Literal('Psychic'),
  T.Literal('Water'),
  T.Literal('Ground'),
  T.Literal('Rock'),
  T.Literal('Electric'),
  T.Literal('Grass'),
  T.Literal('Fighting'),
  T.Literal('Poison'),
  T.Literal('Bug'),
  T.Literal('Fairy'),
  T.Literal('Ghost'),
  T.Literal('Dark'),
  T.Literal('Steel'),
  T.Literal('Dragon')
], {$id: 'Type'})

const Pokemon = T.Object({
  id: T.Integer(),
  num: T.String(),
  name: T.String(),
  img: T.String(),
  type: T.Array(T.Ref(Type)),
  height: T.String(),
  width: T.String(),
  candy: T.String(),
  candy_count: T.Integer(),
  egg: T.Union([
    T.Literal('2 km'),
    T.Literal('Not in Eggs'),
    T.Literal('5 km'),
    T.Literal('10 km'),
    T.Literal('Omanyte Candy')
  ]),
  spawn_chance: T.Number(),
  avg_spawns: T.Number(),
  spawn_time: T.String(),
  multipliers: T.Union([T.Array(T.Number()), T.Null()]),
  weaknesses: T.Array(T.Ref(Type)),
  next_evolution: T.Array(T.Ref(Evolution)),
  prev_evolution: T.Array(T.Ref(Evolution)),
}, { $id: 'Pokemon' })

const Pokedex = T.Object({
  pokemon: T.Array(T.Ref(Pokemon))
}, { $id: 'Pokedex' })

// --------------------------------------------------------
// Test
// --------------------------------------------------------

function test(pokedex: Static<typeof Pokedex>) {
  console.log(pokedex.pokemon[0].name)
}
```

### Namespaces

A namespace is used to group a set of related types together. Namespaces can be useful for publishing a set of types used by an application (analogous to XML namespacing), as well letting you register the namespace in its entirety against AJV (vs registering each types individually). 

In this quicktype example however, the Pokedex schema is not a namespace, rather it is a normalized schema that is using interior referencing to avoid duplication (specifically for the `Evolution` and `Type` types). TypeBox does not support this form schema normalization (as it does not support interior referencing in this way), but does support exterior referencing which allows types to reference one another, but does result in multiple schemas (one for each type).

### Publishing

Typically, you would want to use a namespace to publish a set of related schemas (or types) used by your application. It's common to use a URI, typically associated with the domain in which these types relate. 

```typescript
export const NS = T.Namespace({
   Evolution,
   Type,
   Pokemon,
   Pokedex,
}, { $id: 'http://pokemon.com' })

app.get('/schemas', (req, res) => res.json(NS))
```
### Validation

For validation, you don't actually need the types to be in a single output schema, rather you would keep your types flat and register them against your JSON Schema validator. So the following registers the types using AJV.

```typescript
ajv.addSchema([Evolution, Type, Pokemon, Pokedex]) // add schemas to AJV

ajv.validate(Pokemon, {...})
ajv.validate(Pokedex, {...}) // requires that Pokemon is registered as it is referenced by the Pokedex type.
// ...etc
```

Hope this helps
S

**Comment by mindplay-dk** [comment]
Thanks for all that! 🙏

I'm not actually doing any validation - my schema is the result type for an API call, so I'm just producing a JSON schema, which I feed into quicktype for translation to C#.

Anyhow, using `Type.Namespace` to combine the types (as shown above) does work - just that every type needs an `$id` in order for `$ref` to still work.

So here's one thing I've been thinking about - and this idea might be of no use to you at all, I'm just putting it out there:

You have this `Type.Strict` method, since, as you explain in the documentation, some of the properties in your model are not strictly valid JSON schema.

It just makes me think. Why is it the schema model of the library has to closely conform with JSON schema?

`Type.Strict` kind of seems like the beginnings of a factory function that would translate from an internal model to actual JSON schema - it doesn't seem like there's any particular reason why this step would need to be optional?

I imagine some things could actually be simplified and some features improved by making the internal model to JSON schema step obligatory.

For example, the `Type.Ref` function eagerly resolves the namespace ID and defines `$ref`, which is why it's "too late" to combine things for export in my example - the keys have already been resolved.

If the library model didn't need to immediately conform with JSON schema, `Type.Ref` could keep an actual reference to another schema object instead - making it possible to resolve schema references dynamically, in a final step, where the model is converted to JSON schema.

I suspect this would simplify other things as well - for example, `Type.Ref(t, "name")` wouldn't be necessary, but I haven't looked more closely at the rest of it.

Anyhow, just thought I'd put the idea out there, in case it's useful or interesting. 🙂

**Comment by sinclairzx81** [comment]
> Why is it the schema model of the library has to closely conform with JSON schema?

The main reason is that JSON schema is a industry standard (albeit IETF pending) specification for structured data and the closest thing JavaScript has to a candidate runtime type system. TypeBox began life attempting to find strong parity between JSON Schema and TypeScript with the view that these two technologies are 90% functionally equivalent. 

However, the non standard properties `kind` and `modifier` were introduced to help to resolve some ambiguities for the remaining 10%, where the TypeScript type system can provide a more narrowed view of a type than can be reasonably expressed in JSON Schema. An example of which is `any` or `unknown` which is expressed with the exact underlying schema (i.e `{ }`) but interpreted differently by the type system.

Also, the `kind` and `modifier` symbol properties exist to enable runtime type introspection (analogous to System.Reflection in C#),  and can be used for similar purposes (such as documentation generation, remapping to XSD/WSDL, etc). Rather than inventing a custom reflection format and associated library for introspection, JSON schema provides natural navigable model which is again, a well understood industry standard.

> You have this Type.Strict method, since, as you explain in the documentation, some of the properties in your model are not strictly valid JSON schema.

Indeed, a consequence of including the `kind` and `modifier` to assist with narrowing and reflection does cause TypeBox schemas to not be strictly JSON Schema (when expressed as a object), however they are defined as non-serializable properties and thus not representable in JSON as a format.

The `Type.Strict()` function was implemented to strip out these properties (primarily in response to AJV 7), but may be deprecated in future releases of the library (as it's trivial to strip out these properties with `JSON.stringify(schema)`).

> I imagine some things could actually be simplified and some features improved by making the internal model to JSON schema step obligatory.

This is true. And a very early consideration for this library was to include some form of XSD/WSDL schema generation. This could largely be achieved by implementing some form of library defined schema model that could be remapped to XML, GQL, ProtoBuf and JSON schema.

However, the decision to focus on JSON schema is due to the fact that any custom model I defined would end up looking like JSON schema anyway. So rather than invent another specification (i.e. OpenAPI), the call was made to mandate on JSON schema only, where XSD, ProtoBuf and other formats can be mapped from JSON schema.

This decision works well for JavaScript environments where TypeBox is run.

> Anyhow, just thought I'd put the idea out there, in case it's useful or interesting.

Absolutely! All inputs from the community on the design and direction of TypeBox are extremely valuable. Thanks for sharing! :)

S

**Comment by sinclairzx81** [comment]
@mindplay-dk Sounded like you have the schema generation sorted. Will close off this specific issue, but feel free to open another on some of the design considerations. Good alignment with external languages and tools (such as C#, JSONSchema.NET) are certainly of interest to this project.

Cheers!

**Comment by mindplay-dk** [comment]
I understand the bit about following industry standards, and that's important - and yes, your model is and would be very similar to the standard, but ultimately that seems to me to be of little or no importance. You have to at least call `JSON.stringify` - whether you have to call that, or some other function, to get your JSON schema, doesn't seem important.

The key point in my comment was actually this:

> For example, the `Type.Ref` function eagerly resolves the namespace ID and defines `$ref`, which is why it's "too late" to combine things for export in my example - the keys have already been resolved.

My main point is that, if you had an actual object model, with object references instead of strings, that gives you more flexibility and freedom - you're don't need to calculate everything right away, and the model becomes more dynamic and composable. You build an object graph, and some function finalizes the object graph into JSON schema. For example, this would enable you to compute JSON paths while traversing a the graph, eliminating the need to manually `$id` everything.

Anyhow, you might have already understood what I was getting at? Either way, thanks for taking the time to discuss! 👍

**Comment by stuft2** [comment]
It may be helpful to note in the documentation that it is best practice for writing composite schema to write flat definitions using references. I arrived at this conclusion when AJV threw errors about being unable to add a schema which was already defined.

**Comment by webjunkie** [comment]
>Typically, you would want to use a namespace to publish a set of related schemas (or types) used by your application. It's common to use a URI, typically associated with the domain in which these types relate.

@sinclairzx81 Namespaces got suddenly removed. What is the replacement? How to achieve the same result?

**Comment by sinclairzx81** [comment]
@webjunkie Hi.

Yeah, `Type.Namespace()` got culled as it was a bit too inflexible and opinionated on how users need to combine publishable schemas. The substitute for namespaces is to just group schemas under a plain JS object that matches the composed single schema you need to publish. For example, here's the original namespace documentation updated to use a plain JS object.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZ-fnAC0K1WvUbNW7SvmKAskQAWAZgAicAHIEQGFmAIkMe5TrfuPs2SQjsW8ADUMEhhoABY4AF4UYQA6AHkRACtgmAAKBFk4OHEALhjMWMsAVxARDCg0gEosLLhUfLRCkrKK6tqZbIAvRriW8sqauoB3XubSgerZchwkABJgABN8hiCQ8IYKKq8ZHz9A1OgTKIKMBOTUjLq806KJtqHO+rGz-oeO7pe71sHp2bgFstGGtQlATJtyNs5LtfP44CDoAAmE5NM6JFIhK5PG6o76TR7ZBq3N6-GQzRAApYrBFQREQqHeWHwQwwUwWaKZJ6AlYstkMD4AxYYKgsfJIOrZGlhHAS+GHMEyp6S+XIurkaY7BSuDw63WqFwAVRYBAA5s4ZFq9VadTsMOJILA4EJMHLYHaAIInfBEUgAHmdGAgVFdMA9AD44FqjBAAG4VWR2h3wPZwoJu8Se6K49GXTnZSBsYi+fJSnBaqDCioYTgYOAx4AEJ3COB1djQEAELgl+UmAWh8Q+aBAmmI6YMmSJ6DwAMhu0AIS9hGIJH9wiDs-Ec4jUdj8Yn9qncBTB3TC6zcRzmLzcALwCL7HyvPMsTmQpFsVLkcUFaoVZrdYbQVhRYVt207R9jGfV9gI-Hs+ztQcoCBJ8zBfN8WFg9ZaTHW0D0dGc037ABhRcfRXAN10Iu0iO3RRozjKAEzw5MmQ3Ejz0KS90mvW97y+AAlYU0ilGovzgH8-ycADGzmH9QKgDsu1uQSqGEnsCSdBCICHAShJHKFISAA)

```typescript
import { Type, Static } from '@sinclair/typebox'

// -----------------------------------------------
// Math3D Namespace
// -----------------------------------------------

const Vector4 = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number(),
  w: Type.Number()
}, { $id: 'Vector4' })

const Vector3 = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
}, { $id: 'Vector3' })

const Vector2 = Type.Object({
  x: Type.Number(),
  y: Type.Number()
}, { $id: 'Vector2' })

const Math3D = { // console.log(Math3D)
  $id: 'Math3D',
  $defs: { 
    Vector4, 
    Vector3, 
    Vector2 
  }
}

// -----------------------------------------------
// Usage
// -----------------------------------------------

export type VertexA = Static<typeof VertexA> // hover
export const VertexA = Type.Object({
  position: Vector4, // reference via type 
  normal: Vector3,
  texcoord: Vector2
})

export type VertexB = Static<typeof VertexB> // hover
export const VertexB = Type.Object({
  position: Math3D.$defs.Vector4, // reference via $defs
  normal: Math3D.$defs.Vector3,
  texcoord: Math3D.$defs.Vector2
})

export type VertexC = Static<typeof VertexC> // hover
export const VertexC = Type.Object({
  position: Type.Ref(Vector4), // reference via $ref
  normal: Type.Ref(Vector3),
  texcoord: Type.Ref(Vector2)
})
```
The main difference is that you need to be explicit about the `$id`, but this generally this leads to more flexibly usage patterns overall.

Hope this helps
S

**Comment by webjunkie** [comment]
Thanks for the quick response. I'll try that!

**Comment by webjunkie** [comment]
Hi @sinclairzx81, sorry to use this thread again but I still have problem coming up with a fully compatible JSON schema. This is what I currently am doing to support relative references when outputting a single file:

```js
export const FileReference = Type.Object(
  {
    name: Type.Optional(Type.String()),
    description: Type.Optional(Type.String()),
  },
  {
    $id: "#/$defs/FileReference",
    additionalProperties: false,
  }
);

const someObj = Type.Object({
      description: Type.String(),
      objectSourceFile: Type.Ref(FileReference),
    });
```

I need to use the defs path in the id so that the output schema makes sense for some tools. Is that how it's intended? I just with that for a library that builds JSON schema, this would work more out of the box. Or am I missing something?
