### ISSUE TITLE
How to add conditional properties?

### ISSUE THREAD

**Issue by arrontravala** [sinclairzx81/typebox#146]
How do I add a dependent schema or if-then-else like this example?
![image](https://user-images.githubusercontent.com/47802826/150742965-ef993213-8f36-4f63-841c-e67fb4780c3f.png)
![image](https://user-images.githubusercontent.com/47802826/150742992-c0b80cc7-f843-4f6d-9d75-51142603d2a5.png)

**Comment by sinclairzx81** [comment]
Going to close off this issue for now. I may revisit conditional properties in the future, specifically the conditional regex patterns. But there are no immediate plans to support these schema representations in the near future.

Happy to continue this discussion thread if you have any thoughts on how this might look from an API and Type inference standpoint. It is worth thinking about.

Cheers!
