### ISSUE TITLE
Error when picking a property from another schema

### ISSUE THREAD

**Issue by rubenferreira97** [sinclairzx81/typebox#149]
Hi, I am using fastify new types and trying to pick a property from another schema using the following code:

```TS
const Occurrence = Type.Object({
  id: Type.Number(),
  // ... many other properties
});

const Construction = Type.Object({
  // ... many other properties
  occurrenceId: Type.Optional(Type.Pick(Occurrence, ['id'])), // Error here
});

import Fastify from 'fastify'
import { ajvTypeBoxPlugin, TypeBoxTypeProvider } from '@fastify/type-provider-typebox'
import { Type } from '@sinclair/typebox'

const fastify = Fastify({
  ajv: {
    plugins: [ajvTypeBoxPlugin]
  }
}).withTypeProvider<TypeBoxTypeProvider>()

fastify.get('/', {
  schema: {
    response: {
        200: Construction
      }
  }
}, (req) => {
    // ...code
})
```
When I try the previous code, the following runtime error is throw:

```TS
C:\project\node_modules\@sinclair\typebox\typebox.js:334
        if ($schema['kind'] !== exports.RefKind)
                   ^

TypeError: Cannot read properties of undefined (reading 'kind')
    at TypeBuilder.Deref (C:\project\node_modules\@sinclair\typebox\typebox.js:334:20)
    at TypeBuilder.Pick (C:\project\node_modules\@sinclair\typebox\typebox.js:247:29)
    at Object.<anonymous> (C:\project\build\schemas\contruction.js:12:56)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\project\build\schemas\index.js:19:14)
```

I want to pick already defined properties because they might have validations already defined.

**Comment by sinclairzx81** [comment]
@rubenferreira97 Hi, `Type.Pick(...)` is analogs the TypeScript `Pick<T, Union>` utility type. It accepts a `TObject` and returns another `TObject` containing the properties you have picked. So the resulting type would produce...

```typescript
const Construction = Type.Object({
  occurrenceId: Type.Optional(Type.Pick(Occurrence, ['id']))
});

// produces ...

type Construction = {
   occurrenceId?: { id: number }
}
```

See: https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys for more information on the `Pick` type. 

To share the `id` schema there are couple of ways to approach this. Option B would be the recommended.

### Option A

Access the property directly from the `Occurrence` properties

```typescript
const Occurrence = Type.Object({
    id: Type.Number(),
  });
  
const Construction = Type.Object({
   occurrenceId: Type.Optional(Occurrence.properties.id)
});
```
### Option B

Extract the `id` into it's own Type. This is generally preferable over accessing the internal schema.

```typescript
const OccurrenceId = Type.Number({...})

const Occurrence = Type.Object({
    id: OccurrenceId
  });
  
const Construction = Type.Object({
   occurrenceId: Type.Optional(OccurrenceId)
});
```

### Option C

Extract the `id` into it's own Type and reference via `Type.Ref()`. This allows the schema to express the `OccuranceId` as an external reference, but does require you to add the schema via `ajv.addSchema(...)`.

```typescript
const OccurrenceId = Type.Number({...}, { id: 'OccurrenceId' })

const Occurrence = Type.Object({
    id: OccurrenceId
  });
  
const Construction = Type.Object({
   occurrenceId: Type.Optional(Type.Ref(OccurrenceId))
});
```

## Kind Error

The code you posted looks correct and shouldn't throw an error (have tested locally). Just be sure you're not calling `Type.Strict()` on either the `Occurrence` or `Construction` types as these would remove the `kind` keyword from the schema.

Hope this helps
S

**Comment by rubenferreira97** [comment]
The approach that I took is also an option (picking a set of properties)? The problem was a recursive module export 🤦‍♂️ so the schema was not being loaded, nothing to do with TypeBox.

Thanks for the support. I would like to praise this project. It's really well done and solves a lot of problems.

**Comment by sinclairzx81** [comment]
@rubenferreira97 Hi, thanks :) 

Sure, using `Type.Pick(...)` is ok if you do expect `{ occurrenceId?: { id: number } }` for the output `Construction` schema and type (as TypeBox follows the same conventions as TypeScript's `Pick<...>` utility type). However, because it is only picking a single property (the `id` in this case) it may be easier to just reference the `occurrenceId` as a `number` rather than the object `{ id: number }`. So, the options A, B, C above would be ways to just reference the `number`, but your original schema is perfectly fine too if you expected `{ occurrenceId?: { id: number } }`

It sounds like you found the solution to the problem, so will close off this issue for now.

Thanks again for the kind words!
S
