### ISSUE TITLE
Object properties lose their comments

### ISSUE THREAD

**Issue by cjol** [sinclairzx81/typebox#150]
It's often useful to document type properties in TypeScript, so that they show up in intellisense:
![image](https://user-images.githubusercontent.com/1517675/152550341-9bfd74d1-efe5-4db5-af3b-5a9c4dff0a21.png)

Typebox sadly does not preserve field comments:
![image](https://user-images.githubusercontent.com/1517675/152550039-2163caed-7684-4ef5-bcc0-0ef77131518e.png)

I did a bit of digging, because other similar libraries are able to preserve the comments. I think the issue is in the definition of `StaticObject`. I don't understand the project well enough to understand what the `infer U` conditional is doing, but it seems to interfere with TypeScript's ability to forward the comments in the mapped type:
https://github.com/sinclairzx81/typebox/blob/00117295faa4b244eb1fb914f437fd6ff822fe9d/src/typebox.ts#L222

As a toy example, I tried removing it to demonstrate the problem to myself and it works on my small scale. What do you think?

```ts
// adjusted from source code to remove conditional type
type StaticObject<T extends TProperties> =
   { [K in keyof T]: T[K] };

// copied from source code
interface TObject    <T extends TProperties>                   extends TSchema         { $static: StaticObject<T>} 
declare function Object<T extends TProperties>(properties: T): TObject<T> 


type MyModel = Static<typeof MyModel>;
const MyModel = Object({
  /** This is some documentation */
  amount: Type.Number(),
});
declare const item : MyModel



console.log(item.amount);

```
 
![image](https://user-images.githubusercontent.com/1517675/152553145-52551eaf-ebcf-45a5-9a07-4a26d2a8cb1d.png)

**Comment by sinclairzx81** [comment]
@cjol Hi, Would be very much interested in having doc comments appear on object properties, but not sure if it's possible given the way TypeBox extracts property modifiers.

The conditional mapping that happens on `StaticObject` is fairly complicated, but is written this way to ensure property modifiers `default`, `readonly`, `optional` and `readonly optional` are appropriately mapped. The high level view of the mapping works as follows.

```typescript
// ----------------------------------------------------------------------------------------
// We start with TypeBox type T that needs mapping to TypeScript type S (with T
// shown below as a TypeScript type for clarity)
// ----------------------------------------------------------------------------------------

type T = {
  a: string           // default
  b?: string          // optional
  readonly c: string  // readonly
  readonly d?: string // readonly optional
}
// ----------------------------------------------------------------------------------------
// First we extract and group each property set into different object types based 
// on the properties modifiers, producing 4 object types.
// ----------------------------------------------------------------------------------------

type A = { a: string }
type B = { b?: string }
type C = { readonly c: string }
type D = { readonly d?: string }

// ----------------------------------------------------------------------------------------
// Which are combined back into a Type using intersection
// ----------------------------------------------------------------------------------------

type T = A & B & C & D

// ----------------------------------------------------------------------------------------
// however, intellisense reports the following type in editor
// ----------------------------------------------------------------------------------------

type T =  { 
   a: string 
} & { 
  b?: string 
} & { 
  readonly c: string 
} &  { 
  readonly d?: string 
}

// ----------------------------------------------------------------------------------------
// ... so we remap once more to produce the desired S type
// ----------------------------------------------------------------------------------------

type S = { [K in keyof T]: T[K] }

// ----------------------------------------------------------------------------------------
// where type S reports in editor as the following.
// ----------------------------------------------------------------------------------------

type S = {
  a: string           // default
  b?: string          // optional
  readonly c: string  // readonly
  readonly d?: string // readonly optional
}
```
Unfortunately, during the course of this mapping, TypeScript loses any comments applied to properties, but produce a clean output type in editor. Bear in mind the current strategy for mapping objects is quite old (it dates back a few years now) so there may more concise ways to construct the output object and retain the modifiers.

I would certainly be open to a PR that implements an additional mapping strategy to retain comments tho. If you're interested in having a look I would be happy to assist where I can. I would recommend experimenting with the `kinds` branch which simplifies a lot of the conditional mapping logic (and is planned for a future release).

**Comment by cjol** [comment]
Thanks for that overview. That all looks like it wouldn't interfere with comment propagation. If I get the chance to, I will play around; the test suite should make it easy enough to check I haven't broken anything in my experimentation!

**Comment by sinclairzx81** [comment]
@cjol Hi, going to close off this issue for now, but can reopen at a later time if you have any updates to report.

Many Thanks
S
