### ISSUE TITLE
Cannot Reference schemas created using the StringUnion function from the "OpenAPI" section of the Readme

### ISSUE THREAD

**Issue by jkennedy1980** [sinclairzx81/typebox#155]
Hello, Thanks for the great library.

I've found that you cannot use `Type.Ref` for schemas created using the the `StringUnion` method from the 'Open API' section of the documentation. The reason is that `Type.Store()` never gets called since the schema is directly returned. Here's a single file the demonstrates the problem:

```
import { TLiteral, TUnion, Type } from '@sinclair/typebox'

enum TestStringEnum {
    one = 'one',
    two = 'two',
    three = 'three'
}

type IntoStringUnion<T> = {[K in keyof T]: T[K] extends string ? TLiteral<T[K]>: never }

function StringUnion<T extends string[]>(values: [...T], $id?: string): TUnion<IntoStringUnion<T>> {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const schema = { enum: values, type: 'string', $id } as any
    return schema
}

const stringUnionSchema = StringUnion(Object.values(TestStringEnum), 'TestStringEnum')
console.log('stringUnionSchema: ', JSON.stringify(stringUnionSchema, null, '\t'))

const stringUnionSchemaRef = Type.Ref(stringUnionSchema)
console.log('stringUnionSchemaRef: ', stringUnionSchemaRef)
```

**The code above with throw an 'Unable to locate schema with $id 'TestStringEnum' when the `Type.Ref()` is called.** 

I was able to work around this issue by extending `TypeBuilder` and calling `TypeBuilder.Store()`:

```
import { CustomOptions, TLiteral, TUnion, TypeBuilder } from '@sinclair/typebox'

enum TestStringEnum {
    one = 'one',
    two = 'two',
    three = 'three'
}

type IntoStringUnion<T> = {[K in keyof T]: T[K] extends string ? TLiteral<T[K]>: never }

class CustomTypeBuilder extends TypeBuilder {

    StringUnion<T extends string[]>(values: [...T], options: CustomOptions = {}): TUnion<IntoStringUnion<T>> {
        const schema = { ...options, enum: values, type: 'string' } as unknown as TUnion<IntoStringUnion<T>>
        this.Store(schema)
        return schema
    }

}

 const Schema = new CustomTypeBuilder()

const stringUnionSchema = Schema.StringUnion(Object.values(TestStringEnum), { $id: 'TestStringEnum' })
console.log('stringUnionSchema: ', JSON.stringify(stringUnionSchema, null, '\t'))

const stringUnionSchemaRef = Schema.Ref(stringUnionSchema)
console.log('stringUnionSchemaRef: ', stringUnionSchemaRef)
```

I'm curious what you think the best approach is? 

- Change nothing, allow clients to extend TypeBuilder themselves and add this behavior.
- Add the `StringUnion` method to `TypeBuilder` so it can save schemas automatically. If so, it would be great to have a function that accepts a `string[]` and another that accepts a string valued enum `{ [key: string]: string }` and get's the values automatically.
- Expose the `TypeBuilder.Store()` function so it can be used without subclassing.
- Add a comment to the readme in the 'Open API' section indicating that schemas created that way cannot be referenced without subclassing `TypeBuilder`.

Thanks for the help.

**Comment by sinclairzx81** [comment]
@jkennedy1980 Hi. Approaches to adding custom Types have been long been pondered in this library. I think going forward, the recommended approach will be to extend TypeBox's TypeBuilder. There are some updates in the works to formalize the `protected` API in TypeBox (`Store()` and `Deref()`) to make it more obvious for users, but can be extended now in the way you describe.

I do have an auxiliary project that is using a modified (and to be future) version of TypeBox to augment custom types for specific domains. Extending the TypeBulider directly has been working quite in this project so ill share relevant extended types below for reference.

TypeBuilder
https://github.com/sinclairzx81/sidewinder/blob/master/libs/type/types.ts

ContractTypeBuilder
https://github.com/sinclairzx81/sidewinder/blob/master/libs/contract/type.ts

MongoTypeBuilder
https://github.com/sinclairzx81/sidewinder/blob/master/libs/mongo/type.ts

RedisTypeBuilder
https://github.com/sinclairzx81/sidewinder/blob/master/libs/redis/type.ts

I think adding a `OpenAPITypeBuilder` in downstream projects will be the way to go. Will update the documentation for extending types once I've had a chance to merge in the `kinds` branch of this repository. 

Hope this helps
S

**Comment by sinclairzx81** [comment]
@jkennedy1980 Hi, will close this issue off. I think for the time being I would recommend extending the TypeBuilder class with custom schema information if you need to use `Type.Ref()`. The only anticipated change here may be the potential renaming of `super.Store()` to `super.Create()`, so it should be ok extend the TypeBuilder if you're just mindful of this method rename in future.

I will push through more formal documentation for this approach when the next version of TypeBox rolls through. 

Thanks
S

**Comment by jkennedy1980** [comment]
No problem. I ended up with this for now:
`
import { CustomOptions, TLiteral, TUnion, TypeBuilder } from '@sinclair/typebox'

export type IntoStringUnion<T> = {[K in keyof T]: T[K] extends string ? TLiteral<T[K]>: never }

/**
 * Had to override TypeBuilder due to an issue with Enums: @see https://github.com/sinclairzx81/typebox/issues/155
 */
class GGTypeBuilder extends TypeBuilder {

    StringUnion<T extends string[]>(values: [...T], options: CustomOptions = {}): TUnion<IntoStringUnion<T>> {
        const schema = { ...options, enum: values, type: 'string' } as unknown as TUnion<IntoStringUnion<T>>
        this.Store(schema)
        return schema
    }

}

export const Schema = new GGTypeBuilder()
`

I've noted the upcoming name change - will be an easy fix.

Thanks
