### ISSUE TITLE
Single required property in a Partial object

### ISSUE THREAD

**Issue by ruanmartinelli** [sinclairzx81/typebox#159]
Hey! Is there a clever way to make a single attribute inside of `Partial` object required? 

For example, below I would like to make `z` a required property in `foo`:

```ts
const foo = Type.Partial(
  Type.Object({
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number(), // <-- this is required, all other properties are optional
  })
)
```

My use case is that I have a very large object where only a single property is required. In other words, I'm trying to achieve this type:

```ts
type Foo = {
    x?: number;
    y?: number;
    z: number;
}
```

I understand I can use `Type.Optional` on every property other than `z`, but I was wondering if there's an alternative that's less verbose.

Thanks!

**Comment by sinclairzx81** [comment]
@ruanmartinelli Hi, TypeBox tries to use similar mechanisms as TypeScript, so you could use `Pick` to select the fields you want to be optional and required, then use type intersection to reconstruct the type, so for example.

```typescript
import { Type, Static } from '@sinclair/typebox'

// ---------------------------------------------------
// TypeScript
// ---------------------------------------------------

type Foo = Partial<{
    x: number,
    y: number,
    z: number
}>

type Bar = Pick<Foo, 'x' | 'y'> & Required<Pick<Foo, 'z'>>

// ---------------------------------------------------
// TypeBox
// ---------------------------------------------------

const Foo = Type.Partial(
  Type.Object({
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number(), // <-- this is required, all other properties are optional
  })
)

const Bar = Type.Intersect([
  Type.Pick(Foo, ['x', 'y']),
  Type.Required(Type.Pick(Foo, ['z']))
])


type T = Static<typeof Bar>

// type T = {
//     x?: number | undefined;
//     y?: number | undefined;
// } & {
//     z: number;
// }
```
Hope that helps
S

**Comment by ruanmartinelli** [comment]
Hey @sinclairzx81, thanks for the speedy and in-depth reply!

The solution with `Type.Intersect` looks great, I'll use that one 💪

Thanks!

**Comment by sinclairzx81** [comment]
@ruanmartinelli That's great :) Will close off this issue for now. 

All the best!
S
