### ISSUE TITLE
Can I create an 'AnyOf' type? 

### ISSUE THREAD

**Issue by igortavtib** [sinclairzx81/typebox#161]
I have an string array and I'd like to make a type that is any string included in this string array. I've not found in the docs an AnyOf type, is it possible?

**Comment by sinclairzx81** [comment]
@igortavtib Hi, `anyOf` schemas are created via `Type.Union()` which is analogous to TypeScript union types. You can use these to create sets of allowable string values.

```typescript
type T = 'foo' | 'bar' | 'baz' // union of literal strings

const T = Type.Union([
   Type.Literal('foo'),
   Type.Literal('bar'),
   Type.Literal('baz'),
])
```
Hope this helps
S

**Comment by sinclairzx81** [comment]
@igortavtib Hi, going to close this issue off, but feel free to ping me on this issue if you still have questions. 

Cheers
S
