### ISSUE TITLE
TypeScript generics from TypeBox generics?

### ISSUE THREAD

**Issue by Mahi** [sinclairzx81/typebox#162]
Say I have the following code that creates a message type with a generic payload:
```ts
const Message = <T extends TSchema>(type: T) =>
  Type.Object({
    type: Type.String(['request', 'response']),
    id: Type.Integer(),
    payload: type,
  });
```
I can now easily create custom message types:
```ts
const PayloadA = Type.Object({
   name: Type.String(),
   age: Type.Number(),
});
type PayloadAType = Static<typeof PayloadA>;

const MessageA = Message(PayloadA);
type MessageAType = Static<typeof MessageA>;
```
However, I'd prefer not to have to pre-write all possible message types, A through Z or whatever. I'd much prefer just writing the Payload types, and then in my code use:
```ts
const handler = (message: MessageType<PayloadAType>) => { ... };
```
The problem is, I have to write it like this instead:
```ts
const handler = (message: Static<typeof Message(PayloadA)>) => { ... };
```
At which point it's simpler to just pre-write the types for all possible payload types instead.

Is it possible to have a generic TypeScript `MessageType` created from the `Message` typebox generic?

**Comment by sinclairzx81** [comment]
@Mahi Hi. At this stage, creating explicit variants for all generic types is currently a requirement (as TypeScript requires there be a value to infer from), but it does raise an interesting issue for generic TypeBox types.

I saw this pull request on the TypeScript repository come through the other day (planned for the 4.7 release) which might be of interest....

https://github.com/microsoft/TypeScript/pull/47607

So, it looks like it might be possible to infer TypeBox generic function return types without explicitly calling the function in future releases of the compiler. I will be doing some tests on this once this feature lands. 

Hope that helps
S

**Comment by sinclairzx81** [comment]
@Mahi Hi, apologies for the late reply on this. See example below for creating a generic `Message<T>` type that accepts the variants `A`, `B`, `C` and `D`. The handler signatures are defined after with the message type defined as `Static<typeof ...>`. 

[TypeScript Example Link](https://www.typescriptlang.org/play?ts=4.7.4#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsriQBYYgFwC+cAZlBCHAOQACAzsADsSAGwLAoAehjoMAIwgAPTgFgAUGokS4AWl179Bw0eMnTZvRq0BZDL14EA5hgA8yAHyWd57z98+1aiQQArzwNnaOGHAAvHCucBgKMBgCACa8KJQ0dG4AFKlEBABcKACUMW4oMgB0APKyAFYYJDC5SAWEjKUBqppefgODfp7h9k6ulQBqBFDABAIwvJ5DK6smPUEh8ACCMXCjkblomHWNza1IxVUnAHIAriCyGFC55Qyl3aqboXAAQnsHJxHGr1JotNpwWQlY4Yar3R7PV5dT7feAAYQBtjGGGBJ1B5whJGhNXhTxebw+gWCPwAIpiIkCYacwRc4KlibcHmSke9Pj0+mtBUKRljIhM4AAJeapYTPJa9LRCpUrDbU+BUaWyqC7WK5ECipwlfBEUjOaSYCDMODbNzlaKVBBqODOuCoxBswqMPb6hkYNQMVVbOAatJa-66n3Yo2EYgkM0yS1-W0VRBOl1u9qepixSORf2Bn4hmXPDERg0YaMmuPmjCJtHJ+2p1Qu11q90dejZuC5pz59RfNtFrV0su+yux+MWq00hsOtPOjMezpdnt+1QB-tqIfPbYQjslS4lACMACYAMyMd5wPoQADWaiAA)

```typescript
import { Type, Static, TSchema } from '@sinclair/typebox'

// ---------------------------------------------------------------------
// Message<T>
// ---------------------------------------------------------------------

const Message = <T extends TSchema>(data: T) => Type.Object({ data })

// ---------------------------------------------------------------------
// Message<T> Variants
// ---------------------------------------------------------------------

const A = Message(Type.Object({ a: Type.Number() }))
const B = Message(Type.Object({ b: Type.Number() }))
const C = Message(Type.Object({ c: Type.Number() }))
const D = Message(Type.Object({ d: Type.Number() }))


// ---------------------------------------------------------------------
// Message<T> Handlers
// ---------------------------------------------------------------------

const handlerA = (message: Static<typeof A>) => {
    const { data } = message
}

const handlerB = (message: Static<typeof B>) => {
    const { data } = message
}

const handlerC = (message: Static<typeof C>) => {
    const { data } = message
}

const handlerD = (message: Static<typeof D>) => {
    const { data } = message
}


handlerA({ data: { a: 123 }}) // ok

```

Also, TS 4.7 has landed, so Instantiation Expressions are possible now. You can create a generic type matching the `Message<T>(...)` function if you need with the following.

```typescript
type TMessage<T extends TSchema> = ReturnType<typeof Message<T>> // 4.7 generic method arguments passable here

// type TMessage<T extends TSchema> = TObject<{
//     data: T;
// }>
```
Hope this helps. Will close off this issue for now.

Cheers
S
