### ISSUE TITLE
Static is not imported like Type when compiling

### ISSUE THREAD

**Issue by Aliyss** [sinclairzx81/typebox#163]
### Info

To share the types used between the client and the server I have extracted the types into their own typescript project.

> On the node server everything works as expected.
> When using in production everything works on the client side as well.

However when using it with sveltekit, the types are not correctly working as expected. I am using the IntelliJ Plugin Svelte, so I'm not sure if it is IntelliJ or the Svelte Plugin acting out. Apologies in Advance if the error isn't in this package.

Basically when importing on the client side and using the types I get the following issue:

> Unresolved variable name

---

Here are the two different outputs I get when using typebox:

#### src/file.ts
```ts
/* Adapter Add */
import { Static, Type } from '@sinclair/typebox';

export const addAdapterBody = Type.Object({
	name: Type.String({ description: 'Name of the adapter' }),
});

export type IAddAdapterBody = Static<typeof addAdapterBody>
```
#### dist/file.d.ts
```ts
/* Adapter Add */
import { Static } from '@sinclair/typebox';

export declare const addAdapterBody: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
}>;

export declare type IAddAdapterBody = Static<typeof addAdapterBody>;
```

#### src/file.ts
```ts
/* Adapter Add */
import { Type } from '@sinclair/typebox';

export const addAdapterBody = Type.Object({
	name: Type.String({ description: 'Name of the adapter' }),
});
// Main change is here
export type IAddAdapterBody = import("@sinclair/typebox").Static<typeof addAdapterBody>
```
#### dist/file.d.ts
```ts
/* Adapter Add */
export declare const addAdapterBody: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
}>;

export declare type IAddAdapterBody = import("@sinclair/typebox").Static<typeof addAdapterBody>;
```

**Comment by sinclairzx81** [comment]
@Aliyss Hi. Unfortunately I am not too familiar with the Svelte tooling (but I think they require their own compiler pass to enable some of the features they provide?).

From TypeBox's perspective, if the shared library is working ok in TypeScript / JavaScript environments then TypeBox should be working as expected. TypeBox doesn't necessarily support  external compiler transforms, but If you are able to narrow down the issue to being related to svelte, I would maybe drop a quick issue on the svelte repository and see what their team comes back with. 

Ill leave this issue open for a few days, feel free to link a remote issue here and Ill keep an eye out. 

Cheers
S

**Comment by sandro-pasquali** [comment]
I've had a similar problem which may be related.

Using Node 18, and a package of type: 'module'.

Following the docs, this works:

`import { Type } from '@sinclair/typebox'`

This doesn't:

`import { Type, Static } from '@sinclair/typebox'`

With error:

`Named export 'Static' not found. The requested module '@sinclair/typebox' is a CommonJS module, which may not support all module.exports as named exports.`

When I dump the default export I see:

```
ReadonlyOptionalModifier: Symbol(ReadonlyOptionalModifier),
OptionalModifier: Symbol(OptionalModifier),
ReadonlyModifier: Symbol(ReadonlyModifier),
NamespaceKind: Symbol(NamespaceKind),
KeyOfKind: Symbol(KeyOfKind),
IntersectKind: Symbol(IntersectKind),
UnionKind: Symbol(UnionKind),
TupleKind: Symbol(TupleKind),
ObjectKind: Symbol(ObjectKind),
RecordKind: Symbol(RecordKind),
ArrayKind: Symbol(ArrayKind),
EnumKind: Symbol(EnumKind),
LiteralKind: Symbol(LiteralKind),
StringKind: Symbol(StringKind),
NumberKind: Symbol(NumberKind),
IntegerKind: Symbol(IntegerKind),
BooleanKind: Symbol(BooleanKind),
NullKind: Symbol(NullKind),
UnknownKind: Symbol(UnknownKind),
AnyKind: Symbol(AnyKind),
RefKind: Symbol(RefKind),
ConstructorKind: Symbol(ConstructorKind),
FunctionKind: Symbol(FunctionKind),
PromiseKind: Symbol(PromiseKind),
UndefinedKind: Symbol(UndefinedKind),
VoidKind: Symbol(VoidKind),
TypeBuilder: [class TypeBuilder],
Type: TypeBuilder { schemas: Map(0) {} }
```

(No `Static`)

This is an amazing library. It solves a real pain point for many using OpenApi and/or JSONSchemas.
