### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by xeoneux** [sinclairzx81/typebox#164]
Thanks for all the effort in putting up this library @sinclairzx81 
After maintaining json-schemas of requests and responses for months and getting confused multiple times (wasting time in figuring out why fastify just won't accept the schema and not throw useful errors), this library is a lifesaver!
I am finally able to move away from verbose json-schemas and use neat typescript for the DTOs 😄 
I wish I had discovered it before (found it through the fastify typescript docs)

PS: Would love to donate/buy you a coffee for typebox to keep growing

**Comment by sinclairzx81** [comment]
@xeoneux Hi, Thanks :) Glad to hear you're finding the library useful!

Also hey, thanks for the offer for a coffee (I can never have too much of the stuff :D), but I'll be all good ;) Just happy to provide the project to the community as is; and hopefully try formalize a standards based way of validating runtime data that both aligns with JS/TS convention as well as keeps pace with these JSON schema drafts. I may consider setting up donation box once TypeBox reaches 1.0 (which will include a documentation website and some schema tools), but for now, just enjoy :)

Thanks Again!
S

**Comment by sinclairzx81** [comment]
@xeoneux Thanks again for the nice comment :) but will close off this issue for now.

All the best!
S
