### ISSUE TITLE
Type.Record does not generate right type

### ISSUE THREAD

**Issue by engp8691** [sinclairzx81/typebox#165]
I have a schema defined as

import { Type } from '@sinclair/typebox'
import { commonResponses } from '../../../config/responses'

export const featureFlagResponse = Type.Object(
  {
    featureFlags: Type.Record(Type.String(), Type.Boolean()),
  },
  { description: 'OK' },
)

export const headers = Type.Object({
  accept: Type.Optional(Type.RegEx(/\*\/\*|application\/json/)),
})

export const schema = {
  security: [{ apiKey: [] }],
  tags: ['featureFlags'],
  operationId: 'getFeatureFlags',
  produces: ['application/json'],
  response: {
    ...commonResponses,
    200: featureFlagResponse,
  },
}

But the API generated from `openapi-typescript` gives me ` featureFlags: { [key: string]: string }`. What it should generate needs to be ` featureFlags: { [key: string]: boolen }`. but not string. Can you help me.

getFeatureFlags: {
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': {
            featureFlags: { [key: string]: string }
          }
        }
      }

**Comment by sinclairzx81** [comment]
@engp8691 Hi,

Just tested your `featureFlagsResponse` type and everything seems to be working as expected. Example link [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZGcZFhwSEdi3hUMRAK5QMAMR4BzAEoYWkdRjgBeFMIB0AeREArDCRgAKWXER+-tTaMHqGJiwAXA6YjuaqUAAm3mix+FAcxt4AlDipGI4AQhAQXNrsObmB5FiBSIkWJBlgxGrRDM4A0gwUtTLZsrL8-HAAtOMTk1PTM7Nzs0MjyBYwi2PzG5tb04MyQpgoAKK4yHZ4hMQkADz7GBBUwbr6RgRmFlYsGAB8cMNwABYQABuGCguz+tyOJzOCDWQUeoWeEWi8WgiSuGgy7GMODEpXKXwA3GtyLtZEA)

```typescript
import { Type, Static } from '@sinclair/typebox'

export const featureFlagResponse = Type.Object(
  {
    featureFlags: Type.Record(Type.String(), Type.Boolean()),
  },
  { description: 'OK' },
)

// -----------------------------------------------------
// Test
// -----------------------------------------------------

type TEST = Static<typeof featureFlagResponse> // hover

// type TEST = { // outputs
//     featureFlags: Record<string, boolean>;
// }
```
I'm not very familiar with `openapi-typescript` so can't be of much help there, but from TypeBox's standpoint, the `Static<typeof  featureFlagResponse>` is returning the correct type. What part of the code is producing the `featureFlags: { [key: string]: string }` type? If it's being statically resolved through TypeBox, it should produce the `Record<string, boolean>` type above (and not the `{[key: string]: string}` type you see).

The only other advice I could suggest is ensuring you're on the latest version of TypeBox.

Hope that helps narrow down the issue.
S

**Comment by sinclairzx81** [comment]
@engp8691 Hi, going to close this issue as TypeBox should be working as expected here, but feel free to drop another comment on this thread if you need a bit more help getting things working with `openapi-typescript`. If you can let me know where you're seeing the incorrect type, I might be able to help you narrow down the problem a bit more.

Best of luck!
S
