### ISSUE TITLE
ExtensionKind for opaque user-defined objects

### ISSUE THREAD

**Issue by bullno1** [sinclairzx81/typebox#166]
Currently, I'm considering using typebox for declaring RPC interfaces.
It checks most of the box:

* No code generation
* Can be used with or without ajv
* Can be used with a custom validation library
* Easy conversion to native types
* Ability to add metadata
* Runtime reflection

But there's the 1% that does not fit:

* Buffer type: arbitrary binary blob
* `Stream<T>` type: potentially infinite collection of `T`

For example: pictures, videos, news feed...

Right now, I'm using this:

```typescript
import { Type, TSchema, CustomOptions, UnknownKind } from '@sinclair/typebox';

export interface TWrapper<T> extends TSchema, CustomOptions {
    // This is to let `Static` know about the native type
    $static: T;
    // UnknownKind prevents runtime reflection code from exploring this object
    kind: typeof UnknownKind;
}

export function LocalObject<T>(options?: CustomOptions): TWrapper<T> {
    return Type.Unknown(options) as TWrapper<T>;
}
```

It fits with the rest of typebox:

```typescript
const DownloadStream = Type.Object({
    url: Type.String(),
    stream: LocalObject<NodeJS.ReadableStream>(),
});

// Static<typeof DownloadStream> works as expected:
// {
//     url: string,
//     stream: NodeJS.ReadableStream,
// }
```

* Is there a better way than this?
* Should typebox incorporate something similar to its core?

I am thinking about some sort of "ExtensionKind":

```typescript
const Tag = Symbol('StreamTag');
export const Stream = (options) => Type.Extension<NodeJS.ReadableStream>(Tag, options);
```

It would create something like:

```typescript
{
    // $static: NodeJS.ReadableStream,
    kind: Symbol('ExtensionKind'),
    extensionType: Symbol('StreamTag'),
    [Symbol('StreamTag')]: { /* options from above */ }
}
```

Extended options are attached to the unique tag symbol so that only modules aware of the type can consume it.
Keep `Tag` private and consumers would be forced to use accessor functions to unwrap type-safe options.

**Comment by sinclairzx81** [comment]
@bullno1 Hi, the current way to extend TypeBox to support additional types might look something like the following. Example link [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZRgQxsAxgGjgFWSwAsBTENPfATzFICEBXYAGwBNSo8BhRgZxgQQAeTCYIAOz5wAvnABmUIXADkAAT7AJWFmmBQA9DFqkARhAAeKgLAAoOwYNwAtK7fuPnr95++PDpwBRCxhSCQ42AhM+AJc-eITEnzs7UgtIWDgsSQE4AFUASQkYAA4AQSgoNGoAaS1IgF4UahBzFgAKFULi8srquvCVAEoU2zSM+C1QqHk0LFJ8qd6q6lFxKTg00PDpXgEhNeAcxDs4OBAtJnl5TgAZMIBzGGIAfgAuOAlGVs5T87QLFcblB7hInq8Pl8flA7DJRuNoJNipxZvMCHklhUVpsQmE2NJCCRyGgTrYzgASAQYbAfDE9LHVP7GOgfFQQUwAK1IWBgKjgfwA1vUPszSBB5PkiqUGbV6vzbHD7GN0oisro+NJgtsIjQ6ExWBwoDjtQSTPr2JxSWcwIxTCxsJL6X1qO0IGIjlJaZjnYdjk0EDIhh98HTpc6rWc4FBSDBGFAJHBnsA+AA6VDQUjtJApnNu9Z8PCi1nsrk8lR4IXhWlS5b9OWBv6KxWpFWZbJSeC6hZNCSkADucC1eNIbC75sN7RGSsccSSc-nvliwTQ4BYpFiC83W7co3buXwcCaXZTwk53JgWb+pkY104wZMKe6YZWWfOlxvwNB4I+AGYAEx4BQgIfncjzPB8ABsAAsshTg2SqigQh4oOgmBYAAPKK4oEAAfEAA)

```typescript
import { Static, TSchema, TypeBuilder, CustomOptions } from '@sinclair/typebox'

// ------------------------------------------------------------
// Extended Types
// ------------------------------------------------------------

export const UInt8ArrayKind = Symbol('UInt8ArrayKind')

export interface Uint8ArrayOptions extends CustomOptions {
  minBufferLength?: number
  maxBufferLength?: number
}

export interface TUint8Array extends TSchema {
  $static: Uint8Array
  type: 'object' 
  kind: typeof UInt8ArrayKind 
}

export class ExtendedTypeBuilder extends TypeBuilder {
  public UInt8Array(options: Uint8ArrayOptions = {}): TUint8Array {
    return this.Store({ ...options, type: 'object', kind: UInt8ArrayKind })
  }
}

export const Type = new ExtendedTypeBuilder()

// ------------------------------------------------------------
// Example
// ------------------------------------------------------------

const T = Type.Object({
  buffer: Type.UInt8Array({ minBufferLength: 32, maxBufferLength: 64 })
})

type T = Static<typeof T>
```
Also, if you're interested in RPC, you might want to checkout https://github.com/sinclairzx81/sidewinder which is currently using a modified (to be future) version of TypeBox. It implements `TypeBuilder` extensions for a variety contexts (including a JSON RPC 2.0 Client and Server). The work done on this project will eventually be brought into TypeBox in future revisions, but may provide some insights into how to extend TypeBox. 

Hope that helps
S
