### ISSUE TITLE
Support for the experimental syntax 'classProperties' isn't currently enabled

### ISSUE THREAD

**Issue by dizer** [sinclairzx81/typebox#170]
Hi, I'm trying to upgrade from 0.22 to 0.23 and getting this error:

```
SyntaxError: <...>/node_modules/@sinclair/typebox/typebox.js: Support for the experimental syntax 'classProperties' isn't currently enabled (86:13):
```

```js
// --------------------------------------------------------------------------
// TypeBuilder
// --------------------------------------------------------------------------
class TypeBuilder {
    schemas = new Map();
    /** `Standard` Modifies an object property to be both readonly and optional */
    ReadonlyOptional(item) {
        return { ...item, modifier: exports.ReadonlyOptionalModifier };
    }
```

This `schemas = new Map();` is the line from the error message. Could you please suggest if there is a way to use 0.23 without babel?

**Comment by sinclairzx81** [comment]
@dizer Hi! TypeBox is written in TypeScript, so you will need to use either TypeScript, Esbuild, SWC or Babel to transpile TypeBox into JavaScript. I think most compilers and transpilers should be able to transform the TS class properties to a constructor automatically, or at least provide configurations for this. I use Esbuild and TypeScript personally which handles this automatically, I can't be much assistance with Babel specifically as I'm not really a user of it.

For reference, you can see the TypeScript output target [here](https://www.typescriptlang.org/play?target=3#code/MYGwhgzhAEAqCeAHApgIQK4EsQBNkCdoBvAWAChpLoJgALZAWzAFkxFoBeaAO2QHdorRAAoAlNAD0EngHsALsgBc1ZMmj5MAc1pzoAWnX8Nchd2iYzwGdwhz86YHJmEARjJzxyAXyA) (note the automatic constructor assignment). However If you need TypeBox in JavaScript form specifically for other use cases, you can compile TypeBox to `.js` and `.d.ts` respectively using the TS compiler to produce these, this would remove the need for Babel.

Let me know how you get on, If you're still having problems, I may be open to moving the class property into the `TypeBuilder` constructor to make things a bit easier on legacy toolchains. 

Keep me posted.

**Comment by dizer** [comment]
@sinclairzx81 sure it is TS, but the problem is the NPM module. It does not include .ts files, only compiled JS, incompatible with all current NodeJS versions (including 18.0.0) without Babel. 

Content of 0.23.4 npm module:

```
license
package.json
readme.md
typebox.d.ts
typebox.js
```

Maybe there is a way to add .ts files into the module or transpile it to something more universal during the build/publish process?

**Comment by dizer** [comment]
I just realized that I'm implicitly using Babel as a dependency of Jest 🤦

And it's Babel didn't have support for class properties, not NodeJS itself. Upgraded Jest from 26 to 27th version and everything works as it should.

I'm sorry for disturbing you, typebox works perfectly!
