### ISSUE TITLE
How to extend functionality with ajv plugins?

### ISSUE THREAD

**Issue by kevinv519** [sinclairzx81/typebox#173]
HI there! First of all, thank you for the amazing work and effort put into this library.

I was looking into the documentation and already opened issues but I didn't find how to extend the functionality of typebox with other ajv plugins

Right now I'm trying to use [ajv-keywords](https://github.com/ajv-validator/ajv-keywords/tree/v3) specifically the regex and transform options, but I cannot understand how I would do this using typebox

Can you provide some guidance on how to achieve this if possible?

**Comment by sinclairzx81** [comment]
@kevinv519 Hi, thanks :)

Generally, if you need custom schemas that are not supported in TypeBox by default, you will need to create a custom type by specifying the schema representation, and type it should infer as. There are currently two ways to achieve this...

## Custom Type Function

```typescript
import { Type, Static, TString, CustomOptions } from "@sinclair/typebox"

export function Custom(options: CustomOptions = {}) {
   const schema =  { ...options, type: 'string', customFormat: 'xyz' } as any
   return schema as TString // assert as TString
}

const T = Type.Object({
   custom: Custom()
})

type T = Static<typeof T>
```

## Extending the TypeBuilder

```typescript
import { TypeBuilder, Static, TString, CustomOptions } from '@sinclair/typebox'

export class CustomTypeBuilder extends TypeBuilder {
  public Custom(options: CustomOptions = {}) {
    const schema = { ...options, type: 'string', customFormat: 'xyz' } as any
    return schema as TString // assert as TString
  }
}
// re-export the new TypeBuilder
export const Type = new CustomTypeBuilder()

// example

const T = Type.Object({
  custom: Type.Custom()
})

type T = Static<typeof T>

```

## In the Next Release

There will be a new TypeBox API scheduled to be released sometime around mid June that will allow you to define custom types with a new `Type.Unsafe(..)` function. This function will let you specify a generic argument and custom schema. TypeBox will infer the type based on the generic argument specified.

```typescript
import { Type, Static, SchemaOptions } from '@sinclair/typebox'

const Custom = (options: SchemaOptions = {}) => Type.Unsafe<string>({ 
   ...options, type: 'string', customFormat: 'xyz'
})

const T = Type.Object({
  custom: Custom()
})

type T = Static<typeof T>
```
Hope that helps!
S

**Comment by kevinv519** [comment]
I went for the first option and it worked! Unfortunately not as well as I expected, but that's on the behavior of the ajv validator.

Thank you very much for the prompt reply and the concise example!

Looking forward for the next release to see the new features!

Closing this now.

Best,

**Comment by Liam-Tait** [comment]
@kevinv519 I am using ajv-keywords with typebox using declaration merging to add the transform option to StringOptions.

```ts
declare module "@sinclair/typebox" {
  interface StringOptions<Format extends string> {
    /**
     * Supported transformations:
     * - `trim`: remove whitespace from start and end
     * - `trimStart`/`trimLeft`: remove whitespace from start
     * - `trimEnd`/`trimRight`: remove whitespace from end
     * - `toLowerCase`: convert to lower case
     * - `toUpperCase`: convert to upper case
     * - `toEnumCase`: change string case to be equal to one of enum values in the schema
     *
     * Transformations are applied in the order they are listed.
     *
     * @example
     * ```ts
     * const schema = Type.String({ transform: ['trim', 'toLowerCase'] })
     * ```
     *
     * @see https://ajv.js.org/packages/ajv-keywords.html#transform
     */
    transform?: (
      | "trim"
      | "trimStart"
      | "trimLeft"
      | "trimEnd"
      | "trimRight"
      | "toLowerCase"
      | "toUpperCase"
      | "toEnumCase"
    )[]
  }
}
```
