### ISSUE TITLE
Type.enum() validation repeating "must be equal to constant" error

### ISSUE THREAD

**Issue by felixjb** [sinclairzx81/typebox#174]
I am using the Type.enum() in a schema as follows:
```
const schema: {[key in keyof MyDto]: TSchema} = Type.Object({
  workspaceName: Type.Enum(WorkspaceNameEnum),
  id: Type.String(),
  scheduled: Type.Optional(Type.String({format: 'date'})),
})
```

The values are being validated with the `UsePipes` decorator from Nest.js, passing a validator which uses `Ajv` to validate a value against the schema.

When I make a request with this payload:
```
{
    "id": "abc-123",
    "workspaceName": "valid-enum-value"
}
```

I get the following error:
```
BadRequestException: data/workspaceName must be equal to constant, data/workspaceName must be equal to constant, data/workspaceName must be equal to constant, data/workspaceName must be equal to constant, data/workspaceName must be equal to constant, data/workspaceName must be equal to constant, data/workspaceName must match a schema in anyOf
```

What am I doing wrong?

**Comment by sinclairzx81** [comment]
@felixjb Hi. 

It's difficult to know without seeing the `WorkspaceNameEnum` definition. But I'm guessing that the payload of `"valid-enum-value"` probably needs to be a `number`, not a `string` depending on how you've defined it. For example consider

```typescript
enum Foo { 
  A, 
  B 
}

console.log(Foo.A) // 0 
console.log(Foo.B) // 1
```
But you can change this in the `enum` definition to use explicit strings.
```typescript
enum Foo {
    A = 'valid-enum-value',
    B = 'another-valid-enum-value'
}

console.log(Foo.A) // 'valid-enum-value'
console.log(Foo.B) // 'another-valid-enum-value'
```
If in doubt, you can check the schema with console.log.
```typescript
const schema: {[key in keyof MyDto]: TSchema} = Type.Object({
  workspaceName: Type.Enum(WorkspaceNameEnum),
  id: Type.String(),
  scheduled: Type.Optional(Type.String({format: 'date'})),
})

console.log(schema) // check to see what the definition of `workspaceName` is
```
TypeBox will use the string representation if you've defined it on the `enum`. Otherwise it defaults to the number representation (which is the default for TypeScript). You should see this in the `anyOf` schema for that property.

Hope that helps
S

**Comment by felixjb** [comment]
Hi @sinclairzx81, the definition I am using is the second one:

```
enum Foo {
    A = 'valid-enum-value',
    B = 'another-valid-enum-value'
}
```

My point is: if the value is invalid, shouldn't it return the error only once? I am getting the same error string more than once for the same request 🤔

**Comment by sinclairzx81** [comment]
@felixjb Ah right, i see. The repeated errors you see are really just a consequence of the validator (Ajv in this case), and not really related to TypeBox. In the instance of these enums, TypeBox encodes those with an array of `anyOf`, so it appears that Ajv is just stating that each schema of the anyOf array failed to validate the value. (I think Ajv has some options to flatten all errors into a single output string, that's likely what you're seeing in the output)

I think of the case of `const` (which are constant values encoded in the schema), Ajv could maybe do a better job of reporting specifically what constant value didn't validate. So would expect the error to read as the following (if A, B, C, D, E, F were valid `const` values of your enum)

```
data/workspaceName must be equal to 'A',  
data/workspaceName must be equal to 'B', 
data/workspaceName must be equal to 'C', 
data/workspaceName must be equal to 'D',
data/workspaceName must be equal to 'E', 
data/workspaceName must be equal to 'F', 
data/workspaceName must match a schema in anyOf
 ```
If you need to format a specific output, see if you have some control over the output error formatting in the libraries you're using to drive Ajv. Unfortunately, while JSON schema provides a specification for validation, no such specification exists for error reporting, but see what you can find. (I believe Ajv has a few formatting options available)

Hope this helps
S

**Comment by sinclairzx81** [comment]
@felixjb Hey, Will close off this issue as validation error formatting is a function of the validation library (Ajv), and not of TypeBox.

If you have any other queries on this, feel free to comment on this thread.

All the best
S

**Comment by felixjb** [comment]
@sinclairzx81 thank you so much for your explanation! I will try to figure this out through Ajv then.

**Comment by felixjb** [comment]
@sinclairzx81 I mentioned you in the issue I opened in the Ajv repository but I think it's worth to mention it here:

> [epoberezkin](https://github.com/epoberezkin) commented [3 days ago](https://github.com/ajv-validator/ajv/issues/1987#issuecomment-1133443022) • 
But I don’t understand - if it is enum then why it uses anyOf schema, and not enum keyword?
If typebox generates schemas with anyOf for normal enum values it’s something that should be improved in typebox, not in ajv…

Is it possible to make Type.enum() use the enum keyword instead of anyOf ?

**Comment by sinclairzx81** [comment]
@felixjb That's alright. 

> Is it possible to make Type.enum() use the enum keyword instead of anyOf ?

Unfortunately no (or at least not at this time). The reason why TypeBox opts for `anyOf` over string enums is so that it can generically express types like the following.

```typescript
type T = 'A' | 'B' | { foo: 'bar' }
```
Which can't be expressed with `enum`
```typescript
const T = {
   enum: ['A', 'B', { 
       type: 'object',
       properties: {
           foo: { const: 'bar' }
       }
   }]
}
```
But can be generically expressed with `anyOf`
```typescript
const T = {
    anyOf: [
        { const: 'A' },
        { const: 'B' },
        {
            type: 'object',
            properties: {
                foo: { const: 'bar' }
            }
        }
    ]
}
```
In this respect, TypeBox opts for the schematic that validates inline with the anticipated type in the most uniform way, but not necessarily the most compact way.

If you need to use `enum` representations, you can represent them in TypeBox using the following, but you would need to replace TS enums for string unions (which work pretty much the same)

```typescript
//--------------------------------------------------------------------------------------------
//
// StringUnion<[...]>
//
//--------------------------------------------------------------------------------------------

type IntoStringUnion<T> = {[K in keyof T]: T[K] extends string ? TLiteral<T[K]>: never }

function StringUnion<T extends string[]>(values: [...T]): TUnion<IntoStringUnion<T>> {
    return { enum: values } as any
}

const T = StringUnion(['A', 'B', 'C'])          // const T = {
                                                //    enum: ['A', 'B', 'C']
                                                // }

type T = Static<typeof T>                       // type T = 'A' | 'B' | 'C'
```
