### ISSUE TITLE
Typeguard for TSchema

### ISSUE THREAD

**Issue by avin-kavish** [sinclairzx81/typebox#177]
What would be the best way to check if a value is a JSONSchema object?

This is what I got currently,
```ts
const isTSchema = (schema: any): schema is TSchema => 'kind' in schema
```

**Comment by sinclairzx81** [comment]
@avin-kavish Hi, apologies for the delay in response.

Yes, you could implement a type guard for the `kind` property as you are. However it wouldn't be an exhaustive check and would only test that an object is "potentially" a `TSchema`, but this may work for your use case. 

> Note: To correctly test the `any` object is valid, you would need a JSON Schema document that validates JSON schema. Because TypeBox doesn't concern itself with JSON Schema validation (and encourages the use of AJV), such functionality is deemed "out of scope" for this project. However, refer to https://json-schema.org/draft/2019-09/json-schema-validation.html and https://json-schema.org/draft/2019-09/meta/validation for information on validating json schema itself.

Also as a heads up, in future, the `kind` property is to be changed to a `symbol` property in future releases. So just be a little mindful of your assertion logic around the existing `kind` property. The following outlines the change.

```typescript
// -------------------------------------
// current
// -------------------------------------
const StringKind = Symbol('String')

const T = { kind: StringKind }

// -------------------------------------
// next release
// -------------------------------------

const Kind = Symbol('Kind')

const T = { [Kind]: 'string' }
```
Hope that helps
S

**Comment by avin-kavish** [comment]
Right, yeah. Thanks for your response!

I'm not validating user defined schema. My use case is for when a function accepts a union type that includes a TSchema, so something like `TSchema | OtherType`. It's developer defined so I am assuming the `TSchema` they pass is valid.

**Comment by sinclairzx81** [comment]
@avin-kavish Hi, just a heads up. There has been a new module developed specifically for checking TypeBox schematics on `0.24.6`. Much of this work was prompted by your original issue (however needed to be implemented on the next major revision of TypeBox)

```typescript
import { TypeGuard } from '@sinclair/typebox/guard'

const T = {} as any

if(TypeGuard.TString(T)) {
    T.type === 'string'  // safe
}
``` 

The`TypeGuard` functions perform full recursive structural check against the value provided. So should offer the most assurance when checking the type.

Hope that helps!
S

**Comment by avin-kavish** [comment]
That's great!
