### ISSUE TITLE
fast-json-stringify v5 error when using Type.Union(...) inside of Type.Intersect(...)

### ISSUE THREAD

**Issue by smonn** [sinclairzx81/typebox#184]
After upgrading to Fastify v4.2.0 the fast-json-stringify module was also bumped to v5 (previously v4). It could be that this is an issue on their end, but wanted to call this out here just in case.

When using `Type.Union()` with `Type.Intersect()`, fjs v5 throws an error. The same code with fjs v4 does not.

You can see the error [reproduced in this gist](https://gist.github.com/smonn/b5ecaf9c97eb28b567e55098ae886891).

The error in question is this:

```
no schema with key or ref "schema#/properties/id/anyOf/0"
```

I would use `Type.Ref` sprinkled throughout, but that's not allowed when using `Type.Union()` since fjs considers that a typescript error:

```
Type 'TUnion<[TString, TString]>' is not assignable to type 'Schema'.
      Property 'type' is missing in type 'TUnion<[TString, TString]>' but required in type 'ObjectSchema'.
```

Any thoughts on workarounds beyond avoiding using both Intersect and Union?

**Comment by sinclairzx81** [comment]
@smonn  Hi. It is probably best to ping an issue on the `fast-json-stringify` repository for this as there isn't really anything TypeBox can do to resolve the issue. To help things along there, it would be good to include the JSON schema in the issue. 

You can produce that with the following (see console.log() below)

```typescript
const GuidSchema = Type.String({ format: "uuid", $id: "guid" });
const EmailSchema = Type.String({ format: "email", $id: "email" });
const IdSchema = Type.Union([GuidSchema, EmailSchema], {
  $id: "id",
});

const BaseSchema = Type.Object(
  {
    name: Type.String(),
  },
  { $id: "base" }
);

const SimpleSchema = Type.Object(
  {
    union: IdSchema,
  },
  { $id: "simple" }
);

// Not using intersect seems to avoid the issue, but combined usage of
// intersect and union seems to throw the error below.
const Schema = Type.Intersect(
  [
    BaseSchema,
    Type.Object(
      {
        union: IdSchema, // uncomment to trigger error
        // guid: GuidSchema, // comment out if using above
      },
      { $id: "inner_schema" }
    ),
  ],
  { $id: "schema" }
);


console.log(Schema) // use this output in the FJS issue.
```

Feel free to link back to this issue
Many Thanks
S

**Comment by smonn** [comment]
Thanks! Done. I also confirmed that, as expected, the plain JSON version of the schema also triggers the error.

**Comment by sinclairzx81** [comment]
@smonn Nice, will close this issue, but can track things over on the FSD repo. Cheers :)
