### ISSUE TITLE
AJV Validation with numbers 

### ISSUE THREAD

**Issue by joelwhiteswan** [sinclairzx81/typebox#186]
not sure this belongs here or AJV, but I'm having issues using AJV with Typebox. It seems that using numbers within an object, typescript doesn't infer the types properly for numbers in AJV. For the code snippet below
```
import { Static, Type }   from '@sinclair/typebox'
import addFormats from 'ajv-formats'
import Ajv        from 'ajv/dist/2019'

const ajv = addFormats(new Ajv({}), [
    'float',
    'int64',
    'int32',
    'date-time', 
    'time', 
    'date', 
    'email',  
    'hostname', 
    'ipv4', 
    'ipv6', 
    'uri', 
    'uri-reference', 
    'uuid',
    'uri-template', 
    'json-pointer', 
    'relative-json-pointer', 
    'regex'
]).addKeyword('kind')
  .addKeyword('modifier');

const ExampleType = Type.Object({
  a: Type.String(),
  b: Type.String()
});
const validator = ajv.compile(ExampleType);

const ExampleType2 = Type.Object({
  a: Type.String(),
  b: Type.String(),
  c: Type.Number()
});
const validator2 = ajv.compile(ExampleType2);
```

The type hint for `validator` in vscode is correct:

```
const validator: ValidateFunction<{
    a: string;
    b: string;
} & {
    [x: string]: unknown;
}>
```
But the type hint for `validator2` is
```
const validator2: ValidateFunction<{
    [x: string]: {};
}>
```
where I would expected to see properties for `a`, `b` and `c`?

**Comment by sinclairzx81** [comment]
@joelwhiteswan Hello. To use TypeBox inference, you need to use the `Static<T>` generic type. This type handles the conditional mapping between the object schema and the expected TypeScript type.

### Static&lt;T&gt;

The following demonstrates the use of `Static<T>`

[TypeScript Link here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZRgQxsAxgGjgFQE8wBTOAXzgDMoIQ4ByAAQGdgA7LAGzWCgHoYxEgCMIADwYBYAFCysEdi3j44AXgLCAdAHkRAKxJYYACgSy4l8QC5NpLQDkAriBEkoJgJQ4LlwraJ7Z1d3Lx8ZSzgALwDtYLcPT1lyJLkZIVICdRR0TCwAHgySCCoCAD44fn44IrgOKncSTjIAC0bEOBs4dhcEvH9u3vc8GMGQqAogA)

```typescript
import { Static, Type } from '@sinclair/typebox'

const T = Type.Object({
   x: Type.Number(),
   y: Type.Number(),
   z: Type.Number()
})

type T = Static<typeof T> // type inference here { x: number, y: number, z: number }
```

### Static&lt;T&gt; with Ajv

It is possible to provide the `ajv.compile(schema)` method with a generic argument hint that informs Ajv what type should use for the validationfunction. You can use this argument in combination with `Static<T>` to produce a validation function signature that conforms to your schema.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZRgQxsAxgGjgFQE8wBTOAXzgDMoIQ4ByAAQGdgA7LAGzWCgHoYxEgCMIADwYBYAFChIsOGgAmygGLQQGFtVr0GaAFYA3ALRVN26XPDR4AQRNxnL5zTqMjx67KwR2LPBecAC8SqoaUFowLAAU7CQA7nCOxrEI5ACUeADasq4MVFwQGAw4+S4MHDAAbAAsZRXOVewwAMwATI0yBcoYJKaYICRlcE2MQyN44wx9MFNjPZUkWsBco4sFABYQgexow6MzwGDGDdNLzSfGNUeXjACuUMB3BU-AplAkVCRfnAszB4PYDKbpvZ6DFZgHjzV6VQwsfymSDVX5w5pfGHAYwDBFIlGtNEXApfADmJEksgAuplZL5-IE4ABRcQHaEkIikUIEYQAOgA8iJDCQsDB0hU0AAuHmkXmoZ7sUmxbIVETSzkkOUwBVK2kyLL0gLwYxoLggjDQbleXl+cBrEgAHlQGGwDqEpAgVGZrPAXA5wgAfAHYiy2X6NXrZPx+HA-Ea4CazXNoNKAGqm83zNQPTiYfwOhBRmOuKVwQI6gDcRdccDVZe1HFJVZk0YoAbpMjjjNDvv9pA63I1AqFIrFhaWpaH8sbyvKSzrU4bitnFSw6r5ADkHiARL9lbIDZ2GcaM8moAOwtbbWB7U70JgsG7hJ7vWG+yQOkGQz72RqOpGWxjLsTyTC1zzTU9+mzXNgHzcdWxcUty0bZsEOcOtkMVVDi2cNc4HYbddygbC2yAA)

```typescript
import { Static, Type } from '@sinclair/typebox'
import addFormats from 'ajv-formats'
import Ajv        from 'ajv'

const ajv = addFormats(new Ajv({}), [
    'float',
    'int64',
    'int32',
    'date-time', 
    'time', 
    'date', 
    'email',  
    'hostname', 
    'ipv4', 
    'ipv6', 
    'uri', 
    'uri-reference', 
    'uuid',
    'uri-template', 
    'json-pointer', 
    'relative-json-pointer', 
    'regex'
])

const ExampleType = Type.Object({
  a: Type.String(),
  b: Type.String()
})
const validator = ajv.compile<Static<typeof ExampleType>>(ExampleType)

// const validator: ValidateFunction<{
//     a: string;
//     b: string;
// }>

const ExampleType2 = Type.Object({
  a: Type.String(),
  b: Type.String(),
  c: Type.Number()
})
const validator2 = ajv.compile<Static<typeof ExampleType2>>(ExampleType2)

// const validator2: ValidateFunction<{
//    a: string;
//    b: string;
//    c: number;
// }>
```

Hope that helps!
S

**Comment by sinclairzx81** [comment]
@joelwhiteswan Will close off this issue. If you have any other questions though, feel free to respond on this thread.

Cheers
S
