### ISSUE TITLE
Question About turning types to Json schema.

### ISSUE THREAD

**Issue by cesarvspr** [sinclairzx81/typebox#193]
I'm trying to do something like:

```typescript

import {Static, Type} from '@sinclair/typebox'

type ModelDTO ={
    property: string;
};

export const mySchema = Type.Object(ModelDTO)

```

But getting error:

```
'ModelDTO' only refers to a type, but is being used as a value here.
```

Is this somehow possible? If it isnt possible, is it worth a feature request?

**Comment by sinclairzx81** [comment]
@cesarvspr Hi

The following sets up the `ModelDTO` using TypeBox. Note: Generally it's ok to call the `type` the same as the `const` variable. TypeScript can determine which you mean from usage. Code below.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZQzHACyEACYYuAEWQB5OAF48hYiQA8CjBCrK1G7ToB8cfvzgAJCADcMUOF59wFrKyJBDsLPAq6lq6BijCAHQ6IgBWGCQwABRIcLl5eS6BUKhwoeEQXBgJXBAA5plRdroAlIEQcJ7AGADucCwkABYYIASyeWC0mLCoAFzxmAn4UBz1zbLka3IyVACunMRhgRgRmSC2XHONMTqtOfm5haYAtE9wAIIscASBwl-s7BBjMAwjgrvY4N1gFwuHARBgxrkyhFEHAJhApkIKHEztF7njCvkICIWD5vKovp9vhY4JkAfBvp4CMsCCJKptyEA)

```typescript
import { Type, Static } from '@sinclair/typebox'

type ModelDTO = Static<typeof ModelDTO> // Hover over type

const ModelDTO = Type.Object({          // try console.log(ModelDTO) to view schema
   property: Type.String()
})

function test(model: ModelDTO) {        // <-- As a type annotation, ModelDTO will be
   const { property } = model           //     observed as a type (not a variable)
}
```

Hope that helps
S

**Comment by sinclairzx81** [comment]
@cesarvspr Unfortunately, there is currently no JSON schema to TypeBox conversion tooling available (afaik), but has been something I've thought about as a separate project (mostly for a website orientated tool users could post JSON schema to). If you're starting with JSON schema first (from an existing specification), the only way to map that to TypeBox would be to reimplement the schemas as TypeBox manually (or implement the conversion tooling outright)

It's on my list of things to do, but wouldn't necessarily be part of TypeBox (it's somewhat out of scope of the library itself)

**Comment by sinclairzx81** [comment]
@cesarvspr This project might be more inline with what you need https://www.npmjs.com/package/json-schema-to-ts

Hope that helps

**Comment by sinclairzx81** [comment]
@cesarvspr Will close off this issue for now. But feel free to reply in this thread if you have other questions.

Cheers!
S

**Comment by cesarvspr** [comment]
Thank you for your answer. It would be a great feature to see on TypeBox, I could not find any lib that does the runtime conversion from TS Type to Schema. Or maybe create other lib for this. 

 How much effort do you think is necessary to have this feature? I am willing to contribute

**Comment by sinclairzx81** [comment]
@cesarvspr  You could also try https://www.npmjs.com/package/typescript-json-schema which generates JSON schema from TS types :)

As for writing conversion tooling, there would likely be a fair amount of work required there. I think `JSON schema to TypeBox` would be easier to approach (as JSON is a readily parseable data structure), but would require narrowing all possible JSON schema representations into the subset supported by TypeBox. As for `TypeScript to TypeBox`, Most expressible TS types can be expressed in TypeBox, but you will need to either write a TypeScript parser, or use the Compiler API to get at `interface` and `type` definitions.

I would probably put more value on the `JSON Schema to TypeBox` conversion tool as generally it's more common to happen across JSON Schema (language agnostic) than TypeScript definitions.

Would be happy to assist with technical info if you wanted to try implement one of the conversion tools :)

Regards
S
