### ISSUE TITLE
TypeCompiler not validating RegEx as expected

### ISSUE THREAD

**Issue by felix-wooliesx** [sinclairzx81/typebox#195]
Heya, I believe I've found an issue with the new TypeCompiler in regards to the usage of things like the decimal digit character class (`\d`) in `Type.RegEx`.

Instead of `Type.RegEx(/\d/)` matching digits when used with TypeCompiler's `Check`, it only appears to match the literal character `d`, while `new RegExp(/\d/)` does match a digit.

I got it to work by making the following change (`'` -> `/`) in the `String` handler, but that may have broken some other use cases 🤷

```javascript
const local = PushLocal(`const local = new RegExp('${schema.pattern}');`); // before, with '
const local = PushLocal(`const local = new RegExp(/${schema.pattern}/);`); // after, with /
```

Given this issue doesn't surface in `Errors`' `const regex = new RegExp(schema.pattern)`, as `Errors` didn't return anything for me despite `Check` failing, I'm guessing the issue is around writing that local variable to a code string.

---

Here's a runkit link to illustrate the issue via a simple regex that's intended to just match a digit: https://runkit.com/embed/fvad0bh5fq8n

Source from runkit link to make it easier to see within this github issue:
```javascript
const {Type} = require("@sinclair/typebox@0.24.12")
const {TypeCompiler} = require("@sinclair/typebox@0.24.12/compiler")

const schema = Type.RegEx(/\d/);
const validator = TypeCompiler.Compile(schema);

// Schema is created with `"\\d"` as the pattern, as expected when turned into a string
// Object {type: "string", pattern: "\\d", [Symbol("TypeBox.Kind")]: …}
console.log(schema);

// local0 still has an escaped regex string as expected
// "const local0 = new RegExp('\\d');\nreturn function check(value) {\n  return (\n    (typeof value === 'string') &&\n    (local0.test(value))\n )\n}"
console.log(validator.Code());

// -- Typebox Compiler Validation --
// false: Fails validation when it should actually pass, as it is a digit
console.log("Typebox validation: 5", validator.Check('5'));
// false: Fails validation as expected
console.log("Typebox validation: a", validator.Check('a'));
// true: Passes validation when it shouldn't
console.log("Typebox validation: d", validator.Check('d'));

// -- Escaped String RegExp Validation --
const escapedStringRegExp = new RegExp('\\d');
// true: Passes validation
console.log("Escaped String RegExp validation: 5", escapedStringRegExp.test('5'));
// false: Fails validation as expected
console.log("Escaped String RegExp validation: a", escapedStringRegExp.test('a'));
// false: Fails validation as expected
console.log("Escaped String RegExp validation: d", escapedStringRegExp.test('d'));

// -- Direct RegExp Validation --
const directRegExp = new RegExp(/\d/);
// true: Passes validation
console.log("Direct RegExp validation: 5", directRegExp.test('5'));
// false: Fails validation as expected
console.log("Direct RegExp validation: a", directRegExp.test('a'));
// false: Fails validation as expected
console.log("Direct RegExp validation: d", directRegExp.test('d'));
```

**Comment by sinclairzx81** [comment]
@felix-wooliesx Hey, good catch! The TypeCompiler is very new, so it's great to have some user feedback and issues reported.

Will submit a fix this evening.
Cheers!
S

**Comment by sinclairzx81** [comment]
@felix-wooliesx This fix should be ready on `0.24.13`. Thanks again for reporting!

Many Thanks
S

**Comment by sinclairzx81** [comment]
Will close off this issue, but feel free to ping this thread if you spot any issues there.

**Comment by felix-wooliesx** [comment]
Awesome, thanks - works perfectly :smile:
