### ISSUE TITLE
Help Wanted: Benchmarks

### ISSUE THREAD

**Issue by sinclairzx81** [sinclairzx81/typebox#196]
TypeBox now provides a runtime checker (TypeCompiler) making the library a candidate for validation benchmarking.

Project
https://github.com/moltar/typescript-runtime-type-benchmarks
Current Results
https://moltar.github.io/typescript-runtime-type-benchmarks/

Information on TypeCompiler can be found
https://github.com/sinclairzx81/typebox#Compiler

Candidate Tests Are:
- Loose Assertion
- Strict Assertion

**Comment by sinclairzx81** [comment]
https://github.com/moltar/typescript-runtime-type-benchmarks/issues/97

**Comment by satvik-s** [comment]
https://github.com/moltar/typescript-runtime-type-benchmarks/pull/940

**Comment by sinclairzx81** [comment]
@satvik-s Hi, thank you so much for submitting this benchmark! I see your PR has been merged and the results are in.

![image](https://user-images.githubusercontent.com/3048342/181908663-659c253d-4ba7-4242-9b7a-68956d9a0d4d.png)

https://moltar.github.io/typescript-runtime-type-benchmarks/

I just wanted to extend to you a personal thank you for taking the time to submit TypeBox for benchmarking. Having TypeBox included in community benchmarks caps off a very long road that dates back all the way to the very [first version](https://github.com/sinclairzx81/typebox/blob/typebox-legacy-v1/src/check.ts#L359-L374) of the library in 2017. It's been a long road towards being able to confidently offer a validation option, but I am so happy to finally see TypeBox able to be included amongst it's peers, as well as to know a community contributor was kind enough to take the time to include it.

Again, thank you so much for the help, it truly is appreciated!
Will close off this issue for now
S
