### ISSUE TITLE
Wrap json schema in typebox

### ISSUE THREAD

**Issue by avin-kavish** [sinclairzx81/typebox#204]
Is it possible to wrap an existing json schema in typebox?

```ts
const schema = {
  type: 'object',
  properties: { ... }
}

const typedSchema = t.Object(schema)
```

**Comment by sinclairzx81** [comment]
@avin-kavish Hi! Yes, you can. You can use `Type.Unsafe<T>(...)` to embed custom schemas which can compose with other TypeBox types. However you will need to tell TypeBox how to infer for the schema. See example below.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZ-figAWGFLjhDMcERhbwQREko4BzOKggBXKHBKW9dOCyMYDsjOMiwNwuAGF7GDoMGwBeRFk4KOo+PQA5AhAMAC4nGChTLEjonnjElLSM9hMsmXJZeUUABQIWFg0VNR8tAAoTDHYQ0gBKOAJ2ABMnFwMNCBRhADoAVXYWAioMFu73T2h4Egg5+ACHJLCJzBm5hYwAHl2g-YA+FoRszQKGCBEAKwwSGAZSqKgMAEdLHwMANUgBtBhUWIwBJJb6MXIw-IMAC6PzgYFomFgwF0qXuMmiMSgeSS+OaTz0RRMDAo6KiiNhBSQj1SDCpplp5UJFFk5BWchkCjgNTqcEsJ0WFLGcA8wD0pkOGAAQhJbHQRBwiNAWLJNtt-IFgiS4OE0EcAIJQKAEVAtS7GgWyR4oU14QjEEhnR4QKiGvYhFjXODCl3IN0O-ZglFAA)

```typescript
import { Type, Static } from '@sinclair/typebox'

// The TS type best matching your custom schema
export type Customer = {
    firstName: string,
    lastName: string,
}

// Pass the TS type (generic) and schema to Type.Unsafe()
export const Customer = Type.Unsafe<Customer>({
  type: 'object',
  required: ['firstName', 'lastName'],
  properties: {
    firstName: { type: 'string' },
    lastName: { type: 'string' }
  }
})

// Pass unsafe type to existing TypeBox combinators
const Customers = Type.Array(Customer)

type T = Static<typeof Customers> // type T = Customer[]
```

**Comment by sinclairzx81** [comment]
Also, you can actually use libraries like `json-schema-to-ts` with `Type.Unsafe()` to automatically infer the TS type from raw JSON schema. This might be useful if you have a lot of schemas. See revised link below which uses `FromSchema` from `json-schema-to-ts` to infer the Customer type on `Type.Unsafe()`

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChQkWIjgAxWiFwkAFhhAEK1NYwBWLCOwC0LLToLmYEOy2kzZJMy3gBhAK4e6GKA1tXTgAXkRZODghTAAuRggRIwwSGAYsSLgoDABHbz4MABN4gG0GKj4PADkCEAx0xh5q2vqAXQyZKLBaTFhgDBZ4hEyoiqhmuqHo4XiGDygOAHMGCg6oqKaYGsmlGIxZ+aWV8kyTmUoCFjg3dg8AbllZDHEFeBuPOB8-OqgwlGEAHQAVVuBCoGAAPKo6EEbBC9hAqJ9fPYfrDdAA+DEACi+qIC6IIAEpHjJ3l4Uf5xn80JgAQBBKBQAioXGUn4klwyPYoP74IikeHCRHI74BFgYoA)

```typescript
import { Type, Static } from '@sinclair/typebox'
import { FromSchema } from 'json-schema-to-ts'

export const CustomerSchema = {
  type: 'object',
  required: ['firstName', 'lastName'],
  properties: {
    firstName: { type: 'string' },
    lastName: { type: 'string' }
  }
} as const // const is required

export const Customer = Type.Unsafe<FromSchema<typeof CustomerSchema>>(CustomerSchema)

const Customers = Type.Array(Customer)

type T = Static<typeof Customers>
```

**Comment by sinclairzx81** [comment]
Will close off this issue for now. Feel free to reply on this thread if you have any other questions.
Cheers!

**Comment by avin-kavish** [comment]
Hey! I was looking at your compiler code and it looks great!

Just curious, why did you use generators over functions? Is there a performance benefit?
