### ISSUE TITLE
help !!  How can i transfer this?

### ISSUE THREAD

**Issue by SunshineH2** [sinclairzx81/typebox#207]
![image](https://user-images.githubusercontent.com/31178307/179694381-a2ba1584-361f-4a92-bbbb-815e3e786871.png)

**Comment by sinclairzx81** [comment]
@SunshineH2 Hi. TypeBox doesn't offer `TypeScript > TypeBox` translation as part of this library. The current options are:

- Manually write TypeBox types to replace your current TypeScript types 
- Use the [TypeScript Compiler API](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API) to generate TypeBox types from existing TypeScript types.

The second option would be best, but there are no community tools to do this (afaik). TypeBox can only do `TypeBox > TypeScript` auto translation (inference) with the following...

```typescript
const T = Type.Object({
   id: Type.String(),
   name: Type.String(),
   timestamp: Type.Integer()
})

type T = Static<typeof T> // type T = {
                          //   id: string,
                          //   name: string,
                          //   timestamp: number
                          // }
```
Hope this helps!
S

**Comment by SunshineH2** [comment]
thanks

**Comment by sinclairzx81** [comment]
All good :) Will close off this issue for now. Feel free to reply on this thread if you have any other questions. 
Cheers!
S
