### ISSUE TITLE
Message localization

### ISSUE THREAD

**Issue by nkabir1986** [sinclairzx81/typebox#208]
How to localize erorr messages?

**Comment by sinclairzx81** [comment]
@nkabir1986 Hi, might close off this issue for now. But will spend some time investigating i18n internationalization support for future releases (have started making provisions for this, but won't be ready until the next minor release). For the time being, I'd recommend using Ajv + `ajv-i18n` for internationalization support.

Thanks for the suggestion, it's a really good one!
Regards
S
