### ISSUE TITLE
Specify the value type of enum schema

### ISSUE THREAD

**Issue by ramilsson** [sinclairzx81/typebox#210]
Hey hello, I had a very little issue when creating my fastify app using fastify-swagger and your awesome lifesaver-library, which related to the custom StringEnum schema, described on readme:

```javascript
function StringEnum<T extends string[]>(values: [...T]) {
  return Type.Unsafe<T[number]>({ enum: values })
}
```

I know it is valid and works fine, but when I define the enum schema not specifing the type of its values, I get an empty field in the definitions (Models) in Swagger UI:  

![string_enum](https://user-images.githubusercontent.com/62929022/180658292-6f0431ae-4d43-4046-976e-244923e74635.png)

Since we have that function as an example only for string values (not number or "heterogeneous"), I suggest to specify this type in there. Maybe it will save a little time of devs like me who could face the same thing 🙂

Like that:  
```javascript
function StringEnum<T extends string[]>(values: [...T]) {
  return Type.Unsafe<T[number]>({ type: 'string', enum: values })
}

const T = StringEnum(['A', 'B', 'C']) // const T = { type: 'string', enum: ['A', 'B', 'C'] }
```  

@sinclairzx81 Let me know if I can/should submit a PR or if not :) Also would like to take this opportunity to pay my huge respects for the incredible work well done 👏

**Comment by sinclairzx81** [comment]
@ramilsson Hi! Glad you like the library! And thank you for the kind words :)

> Let me know if I can/should submit a PR or if not

Sure! Happy to receive a PR to update the documentation for the `StringEnum` example. Certainly if inclusion of `type: string` in the schema helps Open API tools produce better documentation output, that sounds like a good justification to include in the reference example in the documentation (and as `StringEnum` is already TS constrained to `string[]` so it would make sense to include there anyway).

Ill keep the issue open, feel free to send through the PR whenever is most convenient.
Many Thanks!
S

**Comment by sinclairzx81** [comment]
@ramilsson Hi! Have just quickly pushed an update for this. The documentation for `Type.Unsafe()` now reads with the following example.

```typescript
import { Type, Static, TSchema } from '@sinclair/typebox'

//--------------------------------------------------------------------------------------------
//
// Nullable<T>
//
//--------------------------------------------------------------------------------------------

function Nullable<T extends TSchema>(schema: T) {
  return Type.Unsafe<Static<T> | null>({ ...schema, nullable: true })
}

const T = Nullable(Type.String())                    // const T = {
                                                     //   type: 'string',
                                                     //   nullable: true
                                                     // }

type T = Static<typeof T>                            // type T = string | null

//--------------------------------------------------------------------------------------------
//
// StringEnum<string[]>
//
//--------------------------------------------------------------------------------------------

function StringEnum<T extends string[]>(values: [...T]) {
  return Type.Unsafe<T[number]>({ type: 'string', enum: values })
}

const T = StringEnum(['A', 'B', 'C'])                // const T = {
                                                     //   enum: ['A', 'B', 'C']
                                                     // }

type T = Static<typeof T>                            // type T = 'A' | 'B' | 'C'
```
Will close off this issue for now. Thanks for the suggestion!
Cheers
S

**Comment by ramilsson** [comment]
@sinclairzx81 Hello, my apologies for the late response, wasn't able to make it until this weekend. And big thanks to you for the update. Have a nice day!
