### ISSUE TITLE
Bug: TypeCompiler errors on `Check` when object has `-`

### ISSUE THREAD

**Issue by satvik-s** [sinclairzx81/typebox#211]
For a type like the following,

```typescript
const sampleType = Type.Object({
  'test-keyname': Type.String()
});
```

TypeCompiler will error when performing `Check` operation giving an error like

```
      ReferenceError: keyname is not defined
```

I believe this comes form the fact that `Check` does something like

```typescript
typeof value.params.test-keyname === 'string'
```

**Comment by satvik-s** [comment]
Giving a quick glance, it looks like the error might be coming from here: https://github.com/sinclairzx81/typebox/blob/ca1bc259d3ee5ea659e43683a84877aefb3207e3/src/compiler/compiler.ts#L144-L149

We end up using `.` to index in. Does it make sense to replace that with `[]` for indexing?

**Comment by satvik-s** [comment]
I updated one of the test for compiler locally and it seems to confirm the above

updated test:
```typescript
  it('Should validate with correct property values', () => {
    const T = Type.Object({
      'a-with-hyphen': Type.Number(),
      b: Type.String(),
      c: Type.Boolean(),
      d: Type.Array(Type.Number()),
      e: Type.Object({ x: Type.Number(), y: Type.Number() }),
    })
    ok(T, {
      'a-with-hyphen': 10,
      b: 'hello',
      c: true,
      d: [1, 2, 3],
      e: { x: 10, y: 20 },
    })
  })
```

error:
```
  1) type/compiler/Object
       Should validate with correct property values:
     SyntaxError: Unexpected token 'with'
      at Function (<anonymous>)
      at Object.Compile (target/test/runtime/index.js:8512:29)
      at ok (target/test/runtime/index.js:9284:26)
      at Context.<anonymous> (target/test/runtime/index.js:9776:5)
      at processImmediate (node:internal/timers:466:21)
```

**Comment by satvik-s** [comment]
here is the fix I had in mind: https://github.com/sinclairzx81/typebox/compare/master...satvik-s:fix-hypenated-indexing?expand=1

Have not created the PR yet but happy to do so if the change looks good

**Comment by sinclairzx81** [comment]
@satvik-s Hi! Thanks for reporting this issue!

The fix you have there is on the right track, however the compiler should only use that approach in cases where member expression access is unavailable (such as keys containing `-` or other non syntax expressible characters). This keeps the type checker fast (as JS engines are optimized for member expression access)

I'll take a look at this shortly

**Comment by sinclairzx81** [comment]
@satvik-s Hi, have just pushed an update for this on `0.24.22` that should resolve the issue. This update currently tests for ascii character codes only but may investigate permissible Unicode characters in future.

The following is the compiler output for hyphenated property keys (and a few other property keys).

```typescript
import { TypeCompiler } from '@sinclair/typebox/compiler'
import { Type } from '@sinclair/typebox'

const T = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number(),
  '0123-numeric': Type.Number(),
  'with-hyphen': Type.Number(),
  'with-non-member-123': Type.Number()
})

const C = TypeCompiler.Compile(T)

console.log(C.Code())

// outputs: return function check(value) {
//   return (
//     (typeof value === 'object' && value !== null && !Array.isArray(value)) &&
//     (typeof value.x === 'number') &&
//     (typeof value.y === 'number') &&
//     (typeof value.z === 'number') &&
//     (typeof value['0123-numeric'] === 'number') &&
//     (typeof value['with-hyphen'] === 'number') &&
//     (typeof value['with-non-member-123'] === 'number')
//  )
// }
```

Let me know if that works your side
Cheers
S

**Comment by satvik-s** [comment]
@sinclairzx81 that worked!

thanks for the quick fix!

i was thinking of doing it similarly but I wasn't aware/sure if there would be a perf hit if we just used `[]` for all scenarios but good to know that

**Comment by sinclairzx81** [comment]
@satvik-s Hey, that's great! :)

Will close of this issue for now. Also, thanks for trying out the new compiler!
Cheers
S
