### ISSUE TITLE
Type.RegEx ignored flags

### ISSUE THREAD

**Issue by kuongknight** [sinclairzx81/typebox#212]
```js
const re = Type.RegEx(/[A-Z]/i) // pattern -> '[A-Z]' and fastify ajv ignore i flags
```
https://github.com/sinclairzx81/typebox/blob/0848f1e3096fbb4197837ef85911d5e4adae6f33/src/typebox.ts#L816

**Comment by sinclairzx81** [comment]
@kuongknight Hi. Unfortunately, JSON schema doesn't provide a means to specify additional flags for string `pattern` properties. TypeBox extracts the `source` of the expression given on `Type.RegEx(...)` but will omit all flags.

I believe the `pattern` property is a subset of the ECMA262 regex specification which is kept simple as to remain portable. A list of supported expression syntax can be found https://json-schema.org/understanding-json-schema/reference/regular_expressions.html

Your comment suggests you're using Fastify + Ajv. Have you considered creating a custom `format`? Generally custom formats provide a lot more flexibility to validate data and can be configured via Ajv.

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@kuongknight Hi, might close off this issue as there isn't much I could implement here while still keeping to spec. My recommendation would be to look into `format` property and follow through on the following links.

https://github.com/ajv-validator/ajv-formats
https://ajv.js.org/guide/formats.html#user-defined-formats

Again, hope this helps
Cheers
S
