### ISSUE TITLE
Clarification on TypeCompiler.check vs Value.Check

### ISSUE THREAD

**Issue by chrisui** [sinclairzx81/typebox#219]
Having read the README several times and looking through the source-code to see the different path's for these two apis (`TypeCompiler.check` & `Value.Check`) it is still not entirely clear to me on their independent use cases which a) I'd be greatful with some help in understanding and b) could be an area for some improved explanation within the documentation.

With my basic reading (likely with bad assumptions), don't they do the same thing? _Ie. "validate whether a given value is correct for the given schema"_. Is there an important tradeoff I'm missing? I see the warning that `TypeCompiler` has the constraint of only understanding schema defined by typebox but as far as I can tell, so does `Value.Check` have the same constraint.

Ps. Great library & great design to really restrict the core to _just typescript and it's utilities_.

**Comment by sinclairzx81** [comment]
@chrisui Hi, thanks! 

Yes, TypeBox provides two distinct validation paths, one dynamic (slow) and the other JIT compiled (fast). They both do exactly the same thing, except one is intended for high throughput messaging, and the other is offered more as a utility.

### Value.Check(...)

The Value.Check(...) function is a utility function that implements dynamic checking on the value. It's provided as part of the `Value.*` API to enable quick type checking without needing to compile.  Internally TypeBox needs type checking during calls to Type.Cast(...), so Type.Check(...) was mostly written in service to casting (which in turn was written in service to data migrations), but is provided on the Value API for convenience. 

#### Usage

Utility scripts, data migrations and other scenarios where performance is less critical.

### TypeCompiler

The TypeCompiler is a runtime JIT compiler that generates optimized validation routines for the given type. It's somewhat similar to AJV where the generated code leans heavily on JavaScript's ability to optimize member expression access. The compiler intended for high message throughput applications (specifically it was written for Web Socket message validation) and is the recommend type checker if considering TypeBox for validation.

Additionally, the TypeCompiler is designed to be embedded in larger systems (frameworks) that standardize on JSON schema specification. It was actually originally written for [this](https://github.com/sinclairzx81/sidewinder) project, but can also be embedded into other web frameworks such as Fastify where it can help with application start up and slightly faster validation.

#### Usage

Web and Web Socket servers, high throughput messaging. A more lightweight (albeit constrained) alternative to AJV in places where AJV compilation would typically run.

Hope that helps!
S

**Comment by chrisui** [comment]
Cheers for the detailed response. Greatly Appreciated.

So if I'm following correctly the decision was made _not_ to use `TypeCompiler.check` within `Type.Cast` due to the cost of compilation? Though I presume this is cacheable? So therefore if I have a persistent service and can bear the [startup] cost of compilation then there's no real reason not to use the TypeCompiler?

---

Separately on a related note I was wondering if there was a path for typebox to handle extension/composition for refined validation? (always in an effort to avoid additional dependencies.. even if AJV is great I like how typebox can be used quite agnostic to json-schema easily enough as it's as matched with typescript).

I was imagining a `[Refine]` symbol which is added to `interface TSchema`. 

```ts
interface TSchema {
  [Refine]: value => Result
}
```

**Comment by sinclairzx81** [comment]
> So if I'm following correctly the decision was made not to use TypeCompiler.check within Type.Cast due to the cost of compilation? Though I presume this is cacheable?

This is correct. Rather than have Value.Check(...) cache the compiled schemas internally, I've felt it's better to keep these modules stateless (so no internal cache) and isolated from one another, even at the cost having having two ways to check. Conceptually you can think of the TypeCompiler and Value API's as separate isolated packages (they were actually envisioned as separate installable packages at one point)

With respect to caching, you can create a `Value.Check(...)` like function using the TypeCompiler, however users are expected to implement this externally. 

```typescript
const map = new Map<TSchema, TypeCheck<any>>()

function check<T extends TSchema>(schema: T, value: unknown): value is Static<T> {
   if(!map.has(schema)) map.set(schema, TypeCompiler.Compile(schema))
   return map.get(schema)!.Check(value)
}
```

> Separately on a related note I was wondering if there was a path for typebox to handle extension/composition for refined validation? (always in an effort to avoid additional dependencies.. even if AJV is great I like how typebox can be used quite agnostic to json-schema easily enough as it's as matched with typescript).

Not at this stage, but maybe in future. I do like the idea of a Refine symbol used for this use case, but it's unclear how this functionality would integrate with TypeBox's inference. For example.

```typescript
const T = Type.String({ [Refine]: value => new Date(value), format: 'date' })

type T = Static<typeof T> // string or Date ?
```
There's also some considerations on how this API would be expressed. My preference would be to make refinement explicit rather than implicit. Which also raise some ambiguities. 

```typescript
const T = Type.String({ [Refine]: value => new Date(value), format: 'date' })

const A= Value.Check(T, '2022-8-7') // asserts A is string

const B = Value.Refine(T, '2022-8-7') // returns B as Date
```
The TypeCompiler and Value API's are fairly new, but I am thinking about how best to express some of this higher level functionality (or if it should be expressed at all). Overall, I do feel the best course is to provide relatively low level APIs that perform operations on types and values that users can build up into custom validation pipelines rather than have it all be automatic. So, should refinement be implemented in TypeBox, it probably won't look much like AJV :) 

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@chrisui Hi, Have updated the readme to include a little bit more information about the `Value` and `TypeCompiler` modules, with a suggestion there that users should consider either Ajv or TypeCompiler if requiring faster validation.

Thanks for the suggestion to improve the documentation. Will close off this issue for now but feel free to reply on this thread if you have any other questions.

Cheers!

**Comment by chrisui** [comment]
Thanks a lot! All the above makes plenty of sense.

I think also as you explore further refinement api it would be good to separate transformation (aka. Parsing in this sense).

In typescript terminology you might even explicitly refer to this less as refinement and more as narrowing - `Narrow` (eg. you would say an [string] enum is a narrowed string - narrowed to a union of string literals).

Then `Transform` allowed for mapping types. And given here you have first class json schema support you'd likely want to define all transformations as two way transformations. 

Anyway just a few thoughts. Thanks again for your help I understanding.
