### ISSUE TITLE
Value.Cast() doesn't work as described in the docs.

### ISSUE THREAD

**Issue by aashishAuthomize** [sinclairzx81/typebox#220]
I tried replicating the Cast example given 
`import { Value } from '@sinclair/typebox/value'

const T = Type.Object({ x: Type.Number(), y: Type.Number() })

const C = Value.Cast(T, { x: 1, y: 2, z: 3 })        // const C = { x: 1, y: 2 }

`
But C still contained the extra key 'z'.

**Comment by sinclairzx81** [comment]
@aashishAuthomize Hi, thanks for submitting this issue and good spotting, the type in that example should read.

```typescript
const T = Type.Object({ x: Type.Number(), y: Type.Number() }, { additionalProperties: false })
```

Will update documentation shortly.

**Comment by sinclairzx81** [comment]
@aashishAuthomize Documentation updated https://github.com/sinclairzx81/typebox#values

Thanks again for reporting!
S
