### ISSUE TITLE
Validation for multiple types of data

### ISSUE THREAD

**Issue by chepa92** [sinclairzx81/typebox#222]
Can we validate for example for ipv4 + ipv6 + uri in same schema? Regex errors looks scary

**Comment by sinclairzx81** [comment]
@chepa92 Hi, see the section on validation here https://github.com/sinclairzx81/typebox#validation and just make sure you have Ajv setup correctly (specifically for the formats). The schema to validate all of these should be.
 
 ```typescript
 // this schema will validate one of the following formats (requires Ajv addFormats)
const T = Type.Union([
   Type.String({ format: 'ipv4' }),
   Type.String({ format: 'ipv6' }),
   Type.String({ format: 'uri' })   
])
```
Hope that helps
S

**Comment by chepa92** [comment]
Wow, nice solution, thanks :)
