### ISSUE TITLE
Question: Nullable Enum Union

### ISSUE THREAD

**Issue by SimonPiscitelli** [sinclairzx81/typebox#223]
Hello

I have a schema where the "offer status" can be a nullable enum, I have an enum object in accordance

```ts
enum OfferStatus {
    AWAITING_RESPONSE: "AWAITING_RESPONSE",
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED"
}
```

I'm building the schema following this library's preferred way

```ts
const schema = {
     // ...
     offer_status: Type.Union([Type.Null(), Type.Enum(OfferStatus)]),
}
```

The resulting json that I'm getting however is a bit convoluted:

```json
{
    "offer_status": {
        "anyOf": [
            {
                "type": "null"
            },
            {
                "anyOf": [
                    {
                        "type": "string",
                        "const": "AWAITING_RESPONSE"
                    },
                    {
                        "type": "string",
                        "const": "ACCEPTED"
                    },
                    {
                        "type": "string",
                        "const": "REJECTED"
                    }
                ]
            }
        ]
    }
}
```

Can I get any advise on how best to construct the union in a way that results in a flat `anyOf` on the resulting json schema?

**Comment by sinclairzx81** [comment]
@SimonPiscitelli Hi. By default TypeBox creates generalized `anyOf` representations for any TypeScript type that has union-like characteristics. But as you noted, the `anyOf` representation is not necessarily the most compact. JSON Schema does however provide more compact representations specifically for string union and enum like types, so the following would be your `enum` expressed in compact form.

```typescript
const T = { 
  type: 'string', 
  enum: [
    'AWAITING_RESPONSE', 
    'ACCEPTED', 
    'REJECTED', 
  ]
}
```
To generate this representation in TypeBox, you will need to use the `Type.Unsafe(...)` function to create a custom schema. Documentation on this type can be found [here](https://github.com/sinclairzx81/typebox#unsafe-types). The following shows how you can use `Type.Unsafe(...)` to express compact enum schemas.

[TypeScript Link Here](https://www.typescriptlang.org/play?ts=4.7.4#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUFKoBXTsQjs8MKBwDmAUXZyQAHmRwM4mBnYATFnBZrNAbQC6APgAUANwJc5GFgC44ewA6EORHAEpEKTg4KAwYOSgVNEwggFV2FgIqDEN7XRARDCgXVyQhTACGW3V2DQYccz0Az29fCnCpchl+fjgAWkGh4ZHRsfGJydGpXrgtcQJwLgwZvqn1jc2pmQqMOAB5KhyofCI5awBeVSJSfV2IKgOj4tOElmc4Wf0huAALCHcxRkJGUtiex1e5zgV3wtW0BVc9hiyJRqNmIMy8EOEMIb2hURiDAAggB1IkASWQ5IAcgBxAD6ACUtLgAAr7am4LQNVG8vm82YxXZVGqaBrRRhEgDCUq0rOQWgAIjz+aq1Wi+jEmiAAvYJQxmQApLRShXK9UW9WC5HEsmUmkM5lsjlc8URS0ez0xa2E6Wy+VK8Ve4OWn2MI0ms3SEMx1XWxwS2NJ5GzbpSXZ4Ei-DAgAj4163e6PXBZnMED5qr4-f6AqDA0HwEvZ3P4lIYIL7EQAKwwJBgZUTD2O9NsZ38KGE6XYwGUiLbQWpci4XFc4Rw2JeuPOESwXU6UgxLAgyyCXAgGlcTbLkWTKKrgzgHBYmD7NlLuZkQA)

```typescript
import { Type, Static } from '@sinclair/typebox'

function StringEnum<T extends string[]>(values: [...T]) {
  return Type.Unsafe<T[number]>({ type: 'string', enum: values })
}

// -------------------------------------------------------------
// Example
// -------------------------------------------------------------

type OfferStatus = Static<typeof OfferStatus> // <--- hover

const OfferStatus = StringEnum([              // const OfferStatus = {
  'AWAITING_RESPONSE',                        //   type: 'string',
  'ACCEPTED',                                 //   enum: [
  'REJECTED'                                  //     'AWAITING_RESPONSE',
])                                            //     'ACCEPTED',
                                              //     'REJECTED'
                                              //   ]
                                              // }

type Schema = Static<typeof Schema>           // <--- hover

const Schema = Type.Object({
   offer_status: Type.Union([Type.Null(), OfferStatus]),
})

console.log(Schema)                           // <--- inspect schema
```
Hope this helps!
S

**Comment by sinclairzx81** [comment]
Will close off this issue, but feel free to reply on this thread if you have any other questions!

Cheers
S

**Comment by SimonPiscitelli** [comment]
This should work.

Thank you for you time

**Comment by abuaboud** [comment]
Hi @sinclairzx81 and @SimonPiscitelli,

In our case, we want to preserve the `Enum` type. Here’s an example:

```ts
enum OfferStatus {
    AWAITING_RESPONSE: "AWAITING_RESPONSE",
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED"
}
```

Using `StringEnum` will infer the type as a string. However, we prefer not to do this since the enum is already used in our codebase. At the same time, we want to expose the OpenAPI spec.

We have created the following:

```ts
export function NullableEnum<T extends TEnum<any>>(schema: T) {
    const values = schema.anyOf.map(f => f.const);
    return Type.Optional(Type.Unsafe<Static<T> | null>({ type: 'string', enum: values, nullable: true }));
}
```

@sinclairzx81 I am adding this here in case if it make sense for you, you could include it in the readme a long side the `StringEnum`
https://www.npmjs.com/package/@sinclair/typebox#:~:text=T%20%3D%20Array%3Cnumber%3E-,Unsafe%20Types,-TypeBox%20supports%20user

Thank you so much,
Mo.
