### ISSUE TITLE
Possibility to compile to graphql (input)types

### ISSUE THREAD

**Issue by ilijaNL** [sinclairzx81/typebox#224]
This is a really great project and I use it every day!
Might be a little bit offtopic but I was wondering if it is possible to compile to graphql types and input types from typebox objects since they are somewhere in between json schema and typescript types. If you have any idea and guidelines I am willing to contribute since this can make writing graphql mutation a lot easier.

**Comment by sinclairzx81** [comment]
@ilijaNL Hi, TypeBox was actually written with this use case in mind :) All the current TypeBox types are reflectable and can be used to generate other type representations (including GraphQL). 

```typescript
const T = Type.Object({
  x: Type.Number(),
  y: Type.Number()
})

// Generate GQL Types from Schematics
T.type             // 'object'
T.properties.x     // { type: 'number' }
T.properties.y     // { type: 'number' }
T.required         // ['x', 'y']
```
Additionally, the TypeBox `Type.Function(...)` and `Type.Constructor(...)` types are provided allow you to frame callable functions, which could be used to map onto GQL mutations and queries. The following is a rough Idea.

```typescript
const CreateUserRequest = Type.Object({ ... })
const CreateUserResponse = Type.Object({ ... })

const GQLContract = Type.GQLContract({
  mutations: {
     createUser: Type.Function([CreateUserRequest], CreateUserResponse)
  }
})

const graphql = new GraphQLTypeBox(GQLContract )

graphql.mutation('createUser', (context, request) => {
   return { ... }
})
```
If you were interested in exploring a GQL implementation, I would be happy to provide guidance on that. Also if you're interested, I currently I manage https://github.com/sinclairzx81/sidewinder which uses a similar design to the above (but is built for JSON RPC 2.0). Sidewinder is the intended design for more advanced integrations of TypeBox, so can be used as a reference point for a possible GQL project.

You can experiment with the link below.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AAmGA7sAHa1QD0AxhIzFAIbswSAKFCRYiOAHUMAIwDKGKADdg7LLgJFSlGvSYtWFRUsXDR0eEmkyAwgBtgGbjnyFi5KrQbNFHB08EhIVZWOABaCMio6JjYuPiExPjg0JsuHn4YFPCk3Lz8gqigzkYKeDTuPgE4AF4UdAwAOgqMgQAKBCE4brgjZUUALkQuntGSXmpqEiG0TEaAMQBXRgFgLjaAbVmmgDlFkBlFNoBKABp6ub2Do+OAXXPtxqvDqBPjke7sIWx37ML-gGAsLZBTKVQYP5AqHQuLFLhlXrGcG1OCMehSWSglRqNotKowX59bFNEAYGAACwg1Da40mJHObXY-m4AElqOdeOcZMdagA+YajEKjUYAH2F4rFwpFHzgQvFcEl8u6ip6AGpInAwLw+CAKHA2rwhox9i8uUaTYp3oLQvKVbaZXKJUq1RrlsAAI6LLBMxzOXTcYB4RxQB02iWhpXqiJwUkUqmo3ikuBMPCKKAYaiuLQlVpZa2hiOjKNhODpmCLKCMZOMVNQdOZ3h6gAGxuuUCbhZ60tGZYrVd4cFVcBkcG+vyFMMnU+y9l9WQnU8XQLhpXgPoCKLRdAxtmZMFx6Xx5xI5JgMDAAxCjWvjRIvxKCPTFEWdngdV4dF4wDXe8a7F4dh2DSExTOcACM4HvI6CrOrBTpKtK0F2nBzrIS60bagA5vsAR6o2+qxpS1BDGUUBMJhHLmm2ZqohaUBQWGMEoShYrZF2zEocWMZkkRCZJimaYZlmxA5vibHKuJg4ak+L7wMAzati8TZAA)

Happy to discuss more, but hope the above provides some initial ideas on how one could approach a GQL implementation.
Cheers!
S

**Comment by ilijaNL** [comment]
Thanks for your quick reaction. I checked the sidewinder project. I really like the idea to have a contract defined as a json schema with types, which then can be used in typescript and non typescript environments. An additional benefit of using a json contract is that is serializable, thus can generate code on other platforms by introspecting the contract via http, and is similar to graphql's SDL/introspection query. However, for small projects, I like to define the "contracts" in a code first approach, let me explain what I mean by that in code, using your snippet from issue https://github.com/trpc/trpc/issues/2453:

[Typscript playground](https://www.typescriptlang.org/play?#code/PTAEFpK6dv4YpyXQFAg2AzgSwHYDGANgIa4BOAXgB4AcAjKAGSi7G4BWpWWEqAwUOGo0uALYAHAPYUALqADeoAOIVSkgBYBFADIBlQpoCm40qAC+oAGYVp40AHIA5uq0BHYo4DcYqbIVlADFSbDlcawBPAAViAFdnAgBBbEiiSxs7BwAia1DwqOzfND4AYVJ8UAAjY1B8UnFjABNQOzi5YwpQMApjbGliADdOtGMaGXlQJuMSUl6bOKJw6Uq2jooAHlKVjpoFAF4lCwAaUABJfGtO4yJasY78JuxQABVIyWMLq97b0EO3j5fa63AB8AApBqQOE1SHJZAAuUAANShuBhy3wQUWhAxAEpEQAlaTtTpbHb3U5An6EYwgkogc5SYimG5yWG4FZTYxs9ijcYBLmzebWbEY0CEXqw4xqDSaTyGExmMn4XYHI6nAnGdxxPpqiqRcFrPqIpIUdSRDZEkmbbYqimgfUgkGnQjkvaIsG9bW6wlanVhXF-EGgW2q-GqNw6AxGUykYoMkJhCKRNhMlkq9mc6Y84h8iYKaZC2oipYcyoS4xSxMFGLxRL4ZWqv7q0Ca71hZuOz3EjrYE1m0gWq3rRv2x3O8VuuQer3+6etv26wP7YOh+7h6vJ2IJZKpIjxsAiI-HpB8c6XdRhChxHFxXp8E+Pp+QEpjfOgOTvWpUgGfS7AmkNiCUB7huJ5Xi-KkbhpSlg0OMFgNYZQCEkdpETOSxcQAbUcHtULkRwAF1ujATRcGcEwugAawIaYWk-D5X35SYCHWPIaQgwF-2pWpFDQUBWkrJoVmIFMULQ0BFio-BpAAd3wfjBNIYT8FE0A8IkqSZPktALCY99WM6djak1fohmMLFSxWaI5gablSTXPZKXwfDgz4gTXTtd0QynRTxPnC58N0-SBUMihjIXMzhksnEy1HJzz2+aC7j2MDnl-KDbmc-DTgAeXaVylEUsFJFs8Q+0igZotFMsbPURoR0cuRnO+DLuOSjZMpg89XJBcMf0g9rbk6obuvyuRXOCvNQrtcLSA43LJAxbB4uaxKAJSh5wLapKsp69o8oK9o3L8lyJMC9pFI0+dxqCgTeii4xfUemKMVWlqNtOOQyOwHD-KIr6fpw66iLpPTppY2aIpRaFM0xGrOXc0AwWwGMzERfVwwhKEdURLS5PwZdg3xnTwYY79uIuNj5uMS04NbEDUseZ5h1JfVTnZthuPOYMAH4ioErCAGkudAKjjEiaRrHOQj0OF4jdNARF8GMYYKBCyZydAFI8GcfAqaMmmNgAWW5TRpBaUDmdAK8CGcD6eMZrb0sG3buoutbbuO5tNVdCgmhNs2LdOMF-PQ7ido2ka3eMbLjqJ9aKEjnjo8+0AvbkJ0SnpQ9nzzkQ+FZ9WGXz0vBBKQsyHmWZsBZnsHKnB3kqdtLOL-GPm2T5LnOpjirfA6Qqk4GY1UUCwToE1Cqg4QhQG9CgLUUgTTe+i2W+t238Ht0Al-2tbd4zxTwV3+pGkRFfzaaU5d+kJaywqxblvexPu73w6JuOxTwyL5+utj89e61FYDrci+soZGwvsHF+e0Pbv16iUSecRp64FnuIdocMNi70gZbJm4FN7b13rAneAkBKHwEsfEhdQ7LnyDlfYhJDb7LURI-e+v9Rr-yIRnOkAlwytnrjaRu0D3bgI4sA2uoCDZzUAtgpuMCzqeyOpnMG2cS7lwZJIOsBAHzlz8O+ZQv5Tj6DZOEQgpwXgKljBkWw9gnAAAE8BEDIJQYA5MqjSBoI4XRAp9Ffm2FIdgnQrFZDsQ42YzjXHuOAK6fxzIKCeIhgoEssVOS-gAELuJhmiDBLx17bQsWYcEqNFSkERC8QMSNPIdhjIQKindfH2EkAEigAA6PxjTmQozRqQXEilehyDvJUbG8QnqSXwNJAmCckYCQiMjAAhNUqirSTA1KGTqXEgZvp2FkqAAAomaWQYJHAXEhNCUAJydSOB6ZQvpAyzk42MIpPS4M3wzUAW3dJNA-65JdlxDuSNrqIm+rgX6jh-rEX7ulfJ5h+ZGPZIQDYQKQVguDMrVWIxwaqIEHwOI2BSDOAeZi0QaBKkKCNBQAAIsYawBBcBikOGSjYY8zFfg+X-cEaSMmonRGWQMDINiQAdM8cwGidwKWafPSIhzqWPAAPo4s6I4U4SMw5t2ablIeI8wTKBoKUr8zSABycRxA1AoGCXEpxIi6o+Aao1JqzWYWOFdRRVrjA2uNZ0M1jr7p9CqiMrVXN8KYSDALEhJKlCgBoBajIhx-K7xuRQSoNBQAAGpQCREeY6iwuJmloOMWWQ5FYpRyuwAqpVu8VWqvVcPHE-qdWqsNe6015q00urdXawMWavUMOdfW21HrzVxp9eZD0yF5FBpXCGyh3r+kJoDe0ZpSbU3+WaemyhTyel8HjfgIVdzTkyg8MQKFH5NCwnFBUaotR5UtCqCmfUoBXCyk8DbToatQClRqXih5YaH0HqPYcQtHR91ykPV0sEWEyWUulbSsshEQ4Jy1Vm3EvgGSCRnduh0u60Q2HyMmN9mjKjfVPYQc9NRJIlpaLJWlmhsNJiiM03oiQwj9uJSsDseRaO1lFc2ADFkcNRG3PWMDEGqU0oxLB5G8Gx7rOQ2AO90hvqBNsHZWSsgqIlCAA)

As you can see this is similar to TRPC, however I think TRPC is doing to much things out of the box. 
Back to graphql. I think the hardest thing to do is to convert from jsonschema to graphql SDL. There are some open source packages like https://github.com/lifeomic/json-schema-to-graphql-types but the seems rather to be limited. I wonder if typebox provides any additional information which can be used to generate a valid graphql SDL.

Perhaps it is better to get in touch online to discuss this further.

Thank you

**Comment by sinclairzx81** [comment]
@ilijaNL See https://replit.com/@sinclairzx81/GraphQLCompiler#index.ts for an example of compiling TypeBox types into GraphQL IDL. This implementation is a quick draft, but you should able to take what's here and extend as you need (just copy and paste from the `repl.it` environment).

As for integration into server infrastructure, it should be possible to map the return type of `Type.Contract(...)` over tRPC, Fastify or Sidewinder. You can use `Static<...>` to extract to parameters and return types from the `Type.Function()` definitions for inference when doing that integration.

Hope this helps!
S

**Comment by ilijaNL** [comment]
Thank you very much, you are a legend. I have last question: how does typescript perform when having a large contract with sidewinder? Say 500+ queries/mutations? Does it have the same issues as trpc when having a lot queries/mutations?

**Comment by sinclairzx81** [comment]
> how does typescript perform when having a large contract with sidewinder? Say 500+ queries/mutations? Does it have the same issues as trpc when having a lot queries/mutations when inferring the client?

Ah, I don't have exact benchmarks for type inference, but I do currently use Sidewinder for some very large microservice backends with dozens of contracts (with hundreds of functions, and many more types). In my experience, the type inference performance is quite fast (even for recursive types). I should probably push the framework a bit more.

I can't really speak for tRPC as I've only briefly looked at it when someone asked me about TypeBox integration. Based on the comment from KATT on https://github.com/trpc/trpc/issues/2453, it seems like Ajv or TypeBox is not going to be a priority for them. I did briefly draft an updated trpc API for them to be supportive of both Zod and TypeBox using a type plugin (HKT) infrastructure [here](https://www.typescriptlang.org/play?#code/PTAEFpK6dv4YpyXQFAlAFQEoAUBhUPAJwHsAXSgTwAcBTDYJ0ANQEMAbASwBN2qJAFxMWoUAGMyAOwDOFNlz4CyJUAF5QAClkSAFvQC27IdgCUGgHzaAblwCu9U-ekBraWQDu0i+usv3L2lRTABRAA92Q1pOJxCwcUkZeVByewp6NU0KEloJADo0jJIAHgBvAF8AGlAASWkAM0z6aQl6Sy0OHn5BM3yAR0cSai18sb7DdIFuGVHx+MSkuQUJHhaFbNyC1e51koo6ejIG1LJ0zI6AcjH8y7MF2W5WznZuEgAvcIAOAEYF1ABgKBwIBaBYIIhkKhKBYAC0yLxwdDkSioWDuNFVAoAFSgdiyUDvUANciGUCXd4Iy5g3j0VbsEj0YkuCQUGbSUDw3hdZRsmQlLCgejhDLSXgE975LlYQ4AQWk1A6ugMxlMWDMpi0dk4jmcbg83l8-n1QTQtPpjNAT2KDXYbU5CPqTUZrSZwtF4uwhydzVdoDKaHEZwotHSpgoem4sgA2pcnqGKJcALpCkUtT2S6VyhWgAD8hPyT2d+0jMbj0gTyespmk9BsmTQFTBmFRrbbqBYMoYACEyOEke3B0OoOjMSQFGUvQwagBlCjTCQ1LAz-RGdigCrE0nkgACj2erxIwAODAARn3qWa6S9LQ0WXyOV36L3wjyeuyBamPQTl6vjEq-xMcxNW1XVQACA0fCscCTW8K8LSZa1Mlte0nxfH0XXtd10x-b1Gl9e0AyDdIE3DUtY3jdJky-HDsBXFV13zOcFxLKMKIrKik2rUBa3rEhG2bMBh2EwcWBwYMGxbETpJRMEpGWU5ziyUAcjyNBCgk0pKhqLkMJaNoOi5N9phke4BiGEZLnYXheEuGoiKtDiKFMSUyFPAArOkKC0SdA0ScIXPyaR7EMU9Mi0Mwaj88RqEC4LQvCiw-IqSK-ODUiC3isKSAiqo-MZWQyE4etNUnSiFBS6CHPEeSUkncIamoDcNEchNotSegKHsEgOXCUAAGpQGoZK8pS9TPG4CM9NdAVDnQ-DMPaLQ0L7YyHwsTBGWMWh1MGTJLNkexTzs-0-PKtVDnyAB5DyvJ89qAqneh8gAORC7Lcva2Knte97EuS1LiJDMMfrehKcsBjrCuKpxtDKpyNyNU7FlqidQAaobms0cr2sZLqevRiAhpGxt7jQVHJDWaQNhUrZ8h2PYTyOE4iguLRrjGO5yeSBRrN4Fr2E8V4Vipih8j5nz0dMH5GtMAAmRHuYUw7TwFoXJsp3ZqfyFXJcemWhvlxXBIgGSRM7fACFMJ0SHxHJ7FZbrGCks3hzBYVaCxFTDjqBan2mtoSgAMRosVcIYAP6BqWprE0LQQ4AMn9VqQdqRHY3SzjQEwSMAHMDDUVwnlpfmmfd8JPfHRybTtJl-YW-SmQcxlrJkTgmvOmDAjg8QW94Numsz5yu8ggS0A9r2kJIFCmRwehofrIP73ZPAGSiTrMhKAgZAyEVo6c6wHPk3fh+36n3TOpzracseJ6rqeZ9AOeF-oJfWgfLed-dffnUb0PPXrr-V0+8Ew1CuiRdIh8-JaFoGvQwshTDPyKovZeMhV620MBvUoZ8T4-0yIAgi9ASiRxAZAywGpfbOgIYtYhDdgGgHAcDCglhb4V0nufaetcGG0AfLIT+5896UMIf-cO9ASG+1AQwiBzDkYp2HvUNqQMMqMMUVDZBsMkEwzfqyD8ODv5CMWjUCMbFyyViTEY8ilwh5VlYZXBQD8uFrXZNoh8sidCAVMOwBUFCtQOFhhBIISMAlwSbGgJmBjxJKXqDXQOOBY5PxEU-TSJQvHUBqKkmoRZMh1GsPmBy0YADSjlQCuHoNQY4dQkzW0KUmRsoAax1gbGEn2GECCi2ichWuJQ4ktRwIkyJxQUkKnScMxyzocl5lkYU4ppTyknFqFUuoNTElzHFiQXOCCxnZPVNBLJagACqkzVkMg2aYaMNwsBJiRqQMghgoxEP2dxXiDZNwNL4uXOx3sGCgFlLIR4udpAdM4YHAAsp1PQCJEnyBIE8XOeDFqJOoY3UhFAwHSPiXPKQJBeAlDBRGBENQtCdwwkima4iFGQKRiSvCQDA7iJUWQk2rthIW0IIgzSA5mXthpNeBkTJ6R-KSUpfhuCDF-2wmHJ6kcWqkraPvGJbo0ySrcp5VkLVKhQL8qGU8PAJCgAmlNOhgcXrumlRKgBNLCEdG1LyVQpgnEyBceyChAzN56MESakU5KOEzxYVqo6urQB7WGCUdqeKIX83NQSaFsKoqLApai0A7UGUUD8h0dq0h16mHDQSpNiwyA8PZJsq6hbkgiv0d6yRKaWHiBdck91ibvUKtAEnX5-zAU+q6Tm3g8LkUSPSGiphlg-XiG1YGyY84P5hvBZCqNoAY3SDhXmxICa42JBTWmrQGas2gG7WuoMpa5CmBLbw8tgjK0DqkUOvyFChWDIbb2+hQLH6tr+dwAFz6u0zp7WKp9TlB0JmHWPF2XK2ysqtqAF669ZCwLaJy0DqIeUIR4tB2DTJVJ6ocn5O+Cg7zv3ZIpe9X8RTquqL+rCSqLURyNUyTQsqlo2p6HaxQ3QTLSCdaZdlwqH3kfaH5bDbCq54Z0TITWew+lztdaUDJeJRmpOHVodMntrSmAXbnChrT2mdtiSwpsQA), but I'm doubtful they will adopt this design (even though it does try to optimize their inference paths through caching interfaces)

Might close off this issue for now, if you wanted to setup a repository for the GQL stuff, feel free to ping me over there. May be able to help with a GQL initiative down the road (maybe helping out with the inference if you need)

Cheers!
S

**Comment by ilijaNL** [comment]
Thank you for your guidelines en help. Let's see if I can come up with a better alternative to type-graphql with help of typebox

**Comment by teague2** [comment]
Any updates on this?
