### ISSUE TITLE
 Type.String pattern with unicode RexExp flag

### ISSUE THREAD

**Issue by ak211** [sinclairzx81/typebox#225]
Hi,

I would like to validate object with TypeCompiler.Compile. The object has only one string property with a special pattern:
name: Type.String({ pattern: '/^[\\p{sc=Latn} .-]*$/u' }). It causes complie error with this pattern, but work fine with an easier pattern like ^[a-z]*$

sorry if this is not a Typebox but javascript syntax issue, I'm newbie..

"@sinclair/typebox": "^0.24.28"

Here is the snippet:
```
import { Static, Type } from '@sinclair/typebox'
import { TypeCompiler } from '@sinclair/typebox/compiler'

export const latinOnly = Type.Object({
  name: Type.String({ pattern: '/^[\\p{sc=Latn} .-]*$/u' }),
});
export const latinOnlyCheck = TypeCompiler.Compile(latinOnly);
console.log([...latinOnlyCheck.Errors('Ákos')]);
console.log([... latinOnlyCheck.Errors('$NotJustLetters§')]);
```

And the compile error:
```
:~/myProjects/sinclairTypebox$ ts-node demo.ts
/home/.../myProjects/sinclairTypebox/node_modules/@sinclair/typebox/compiler/compiler.js:385
        const func = globalThis.Function(code);
                                ^
SyntaxError: Unexpected token 'return'
    at Function (<anonymous>)
    at Object.Compile (/home/.../myProjects/sinclairTypebox/node_modules/@sinclair/typebox/compiler/compiler.js:385:33)
    at Object.<anonymous> (/home/.../myProjects/sinclairTypebox/demo.ts:7:44)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module.m._compile (/home/.../.nvm/versions/node/v18.6.0/lib/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Object.require.extensions.<computed> [as .ts] (/home/.../.nvm/versions/node/v18.6.0/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

the regex above works well in browser's developer console this way:
/^[\p{sc=Latn} .-]*$/u.test('a')
true
/^[\p{sc=Latn} .-]*$/u.test('Á')
true
/^[\p{sc=Latn} .-]*$/u.test('%') 

How should the above regex be used?

Thanks in advance

**Comment by sinclairzx81** [comment]
@ak211 Hi. Currently the TypeCompiler only supports a subset of the ECMA262 regular expression syntax. So expressions flags (such as the unicode `u` specifier) and `{sc=Latn}` specifiers are not currently supported at this time (however there are plans to support custom string `formats` in later releases)

You can read up on the supported ECMA262 regular expression subset at the link below.

https://json-schema.org/understanding-json-schema/reference/regular_expressions.html

In the meantime, it should be possible to use Ajv for unicode validation support. The following is a quick setup using TypeBox with Ajv to validate this expression by way of custom format.

```typescript
import { Type, Static } from '@sinclair/typebox'
import Ajv from 'ajv'

const ajv = new Ajv()

// -------------------------------------------------
// add custom format
// -------------------------------------------------

ajv.addFormat('latin', {  type: 'string', validate: (x: string) => /^[\p{sc=Latn} .-]$/u.test(x) })

// -------------------------------------------------
// create type and compile
// -------------------------------------------------

const T = Type.String({ format: 'latin' })

const F = ajv.compile(T)

// -------------------------------------------------
// test
// -------------------------------------------------

console.log(F('a')) // true
console.log(F('Á')) // true
console.log(F('%')) // false
```
Hope this helps!
S

**Comment by ak211** [comment]
Hi @sinclairzx81 , 

Thanks for the quick reply and suggestion, it will work.
So this is not a bug, I think this issue can be closed.

Best regards
Ákos

**Comment by sinclairzx81** [comment]
@ak211 Hi. Just a quick update on this. Have just added a new `Formats` module that should support Unicode and other forms of custom string validation. This module is shared between the TypeCompiler and Value modules internally. Documentation on the feature can be found https://github.com/sinclairzx81/typebox#formats

This issues example code implemented by way of the new formats module below.

```typescript
import { TypeCompiler } from '@sinclair/typebox/compiler'
import { Format } from '@sinclair/typebox/format'
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'

// set the format before using TypeCompiler or Value

Format.Set('latin', value => /^[\p{sc=Latn} .-]$/u.test(value))

// the following will validate unicode / latin

const T = Type.String({ format: 'latin' })

const R1 = TypeCompiler.Compile(T).Check('Á') // true

const R2 = Value.Check(T, 'Á')                // true
```
Cheers
S

**Comment by jtlapp** [comment]
I'll be trying the format feature in a moment -- thanks for this -- but I did want to comment that his behavior is scary.

I have a well-tested regex that uses the `/u` unicode flag. I dropped it into a `Type.Regex()` and handed the program an invalid string. TypeBox accepted the string.

I'm exposing my regexes as constants, so it isn't immediately obvious to me which of my constants can be used with `Regex` and which cannot. I have to look them up each time or else append a special suffix to the constant name, in order to prevent me from making this mistake.

If it's not possible to have `RegEx` support the `/u` switch, I'm thinking that the type compiler needs to throw if it's ever handed the switch. Otherwise -- scary!

**Comment by sinclairzx81** [comment]
@jtlapp Hi!

Unicode switches are a limitation of JSON Schema patterns (which only support a subset of the ECMA262 spec (linking again for documentation on the supported subset https://json-schema.org/understanding-json-schema/reference/regular_expressions.html), as well as options like ignoring case sensitivity. 

There's currently some checks to prevent control character escapes in patterns here https://github.com/sinclairzx81/typebox/blob/master/src/guard/guard.ts#L93 (which should prevent compilation as the compiler will report the string as an invalid type), but could implement some additional checks to assert for additional switches. 

I'll take a look into this.

**Comment by jtlapp** [comment]
BTW, stored formats work great. Thanks so much!

Also, it looks like you should be able to check `/someregex/u.flags`, equal to `'u'` in this example.

**Comment by jtlapp** [comment]
Now that IE is dead, I'm not sure why JSON Schema shouldn't support Unicode. Check out [this table](https://caniuse.com/mdn-javascript_builtins_regexp_unicode).
