### ISSUE TITLE
Add type property to Enum and KeyOf

### ISSUE THREAD

**Issue by jsbrain** [sinclairzx81/typebox#226]
I'm wondering why `Type.Enum` and `Type.KeyOf` don't have an option for setting the json schema type.

Like I'm seeing a lot of schemas that look like this:

```ts
const T = {
  type: 'string',
  anyOf: [
    {
      type: 'string',
      const: 'x',
    },
    {
      type: 'string',
      const: 'y',
    },
  ],
};
```

where the `type` property is required by some libraries for proper functionality.

But typebox creates this:

```ts
const T = {
  anyOf: [
    {
      type: 'string',
      const: 'x',
    },
    {
      type: 'string',
      const: 'y',
    },
  ],
};
```

I know this is now possible to achieve via `Type.Unsafe` but I was just wondering why it's not in `Type.Enum` and `Type.KeyOf` anyways as an optional parameter? Is it actually not json-schema compliant?

If I want to have exactly the output from `Type.Enum` but just with the `type` property set to 'string' I'd need to re-create the `anyOf` schema as of now, basically re-creating the whole `Enum` type and add the prop.

Ideally I'd like to piggyback on the already existing `Enum` and `KeyOf`. Is there any reason against this?

**Comment by sinclairzx81** [comment]
@jsbrain Hi. You can pass the `type` property on the last argument for that type. For example..

```typescript
const T = Type.Union([
  Type.Literal('A'),
  Type.Literal('B')
], { type: 'string' }) // pass as optional property

// produces....

const T = {
  type: 'string',
  anyOf: [
    { const: 'A', type: 'string' },
    { const: 'B', type: 'string' }
  ]
}
```
This also works with `Type.KeyOf(...)`
```typescript
const T = Type.Object({
  A: Type.String(),
  B: Type.String(),
})

const K = Type.KeyOf(T, { type: 'string' })

// produces....

const K = {
  type: 'string',
  anyOf: [
    { const: 'A', type: 'string' },
    { const: 'B', type: 'string' }
  ]
}
```
If you need to use the string `enum` JSON schema keyword (which isn't supported by TypeBox, but is common in OpenAPI tooling), you can create schemas of that form using the `Type.Unsafe(...)` function.

Hope this helps!
S

**Comment by jsbrain** [comment]
Oh wow I didn't realize that `SchemaOptions` allows passing arbitrary props to the schema. I was totally depending on the props showing in Intellisense and didn't even try :D.

Well thanks for the clarification.

Absolutely love the project btw. definitely one of the best libs I've seen so far.
So damn useful, keep it up! 🔥
