### ISSUE TITLE
Does typebox support coercing types during validation/check?

### ISSUE THREAD

**Issue by jessekrubin** [sinclairzx81/typebox#227]
example:

```typescript
const portSchema = Type.Object({
  PORT: Type.Integer({ coerce: true }),
})
const validate = TypeCompiler.Compile(portSchema)
const isok = validate.Check({
  PORT: '123'
})
console.log(isok) // false
```

**Comment by sinclairzx81** [comment]
@jessekrubin Hi. The TypeBox compiler does not coerce values during validation (it always treats values as immutable). If you need this functionality though, Ajv does support coercion to some degree. See https://ajv.js.org/coercion.html.

If using the compiler, you can test for numeric string values with the following.

```typescript
import { Type } from '@sinclair/typebox'

const Port = Type.RegEx(/^(0|[1-9][0-9]*)$/)
```
However the coercion from `string` to `number` will need to be explicit via `parseInt(port)`

Hope this helps!
S

**Comment by jessekrubin** [comment]
@sinclairzx81 thanks a lot!! I was mostly just curious.

**Comment by sinclairzx81** [comment]
@jessekrubin Hi, just a update on this. I have just implemented automatic type coercion to the `Value.Cast(...)` API. This functionality is available on `@sinclair/typebox@0.24.31` as standard.

The `Value.Cast(...)` function remaps any value into a target type while retaining as much information of the original value as possible. You can use this to resolve environment variables to their correct types (and provide default values if variables are omitted)

```typescript
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'

// ---------------------------------------------------------------------------
// Describe values on process.env (with fallback defaults)
// ---------------------------------------------------------------------------

const Environment = Type.Object({
    PORT: Type.Integer({ default: 5000 }),
    URL: Type.String(),
})

// ---------------------------------------------------------------------------
// Use Value.Cast(...) to cast variables into appropriate types
// ---------------------------------------------------------------------------

const environment = Value.Cast(Environment, process.env)

console.log(environment)

// environment = { URL: '', PORT: 5000 }
```

### Conversion Rules

```typescript
// ---
const T = Type.String()
Value.Cast(T, null)   // ''
Value.Cast(T, 1)      // '1'
Value.Cast(T, '2')    // '2'
Value.Cast(T, 3.14)   // '3.14'
// ---
const T = Type.Number()
Value.Cast(T, null)   // 0
Value.Cast(T, 1)      // 1
Value.Cast(T, '2')    // 2
Value.Cast(T, '3.14') // 3.14
// ---
const T = Type.Integer()
Value.Cast(T, null)   // 0
Value.Cast(T, 1)      // 1
Value.Cast(T, '2')    // 2
Value.Cast(T, '3.14') // 3
// ---
const T = Type.Boolean()
Value.Cast(T, null)   // false
Value.Cast(T, 1)      // true
Value.Cast(T, 0)      // false
Value.Cast(T, 2)      // false
Value.Cast(T, 'true') // true
Value.Cast(T, 'TRUE') // true
Value.Cast(T, 'True') // true
Value.Cast(T, 'TruE') // false
```

Hope that helps!
S

**Comment by jessekrubin** [comment]
@sinclairzx81 youre a mensch! Thanks that will be super super useful! 

Just curious, does the fastify-typebox-type-provider package handle the validation?

**Comment by sinclairzx81** [comment]
@jessekrubin You're welcome!

> Just curious, does the fastify-typebox-type-provider package handle the validation?

By default, Fastify uses Ajv under the hood, however there is an option to override Ajv to use the TypeCompiler for slightly faster validation. See docs below.

https://github.com/fastify/fastify-type-provider-typebox#type-compiler

Note that I'm only partially involved with the TypeBox Type Provider package these days, so any issues using the compiler with fastify is best raised with the Fastify team. However if you want to experiment with custom validation pipelines, it's pretty easy to your roll you own validation compiler, see code below

https://github.com/fastify/fastify-type-provider-typebox/blob/main/index.ts#L23-L39

Hope that helps!

**Comment by jessekrubin** [comment]
@sinclairzx81 thanks so much! does the `Cast`-ing work with booleans that are strings of numbers?

Example:

```typescript
const T = Type.Boolean()
Value.Cast(T, '1')   // true
```

**Comment by sinclairzx81** [comment]
> does the Cast-ing work with booleans that are strings of numbers?

This wasn't originally implemented, but I do think it makes sense to support this as `'1'` would coerce to `1`, which in turn coerces to `true`. Have updated on `0.24.33` to support this conversion.

**Comment by jessekrubin** [comment]
@sinclairzx81 you are too kind!

**Comment by tanishqmanuja** [comment]
Can someone explain this ?

![image](https://github.com/user-attachments/assets/40439d97-fc41-4a01-9f76-cf25ce6d47e9)

**Comment by jessekrubin** [comment]
I am only guessing but it does not coerce strings to integers (?) so it replaces with a value in the schema

What version of typebox are you on?

**Comment by tanishqmanuja** [comment]
Latest - 0.33.7
