### ISSUE TITLE
Type Inheritance and Composability

### ISSUE THREAD

**Issue by lhrinaldi** [sinclairzx81/typebox#232]
Hello! I've just discovered `typebox`  and I'm really excited about how it simplifies the usage of JSON schema, thank you for this package.

I'm currently using `Objection.js` and this lib has the idea of extending classes to share things like automatic id generation, timestamps and other functionalities. And uses the `jsonSchema` property to validate when inserting/updating values to the database.

To get quickly to the point, I'm trying to inherit from this `BaseModel` class and compose child json schema objects, but without any success because using intersection or union comes up with a different type of the parent class property.

For example:

```ts
import { Type } from '@sinclair/typebox';

const parent = Type.Object({
  id: Type.Optional(Type.String()),
  createdAt: Type.Optional(Type.String()),
  updatedAt: Type.Optional(Type.String())
})

const standalone = Type.Object({
  id: Type.Optional(Type.String()),
  createdAt: Type.Optional(Type.String()),
  updatedAt: Type.Optional(Type.String()),
  name: Type.String(),
});

const composed = Type.Intersect([
  parent,
  Type.Object({
    name: Type.String(),
  }),
]);


const standaloneId = standalone.properties.id;
const composedId = composed.properties.id;
```

![image](https://user-images.githubusercontent.com/1268808/188708813-d4bc1854-1506-49e9-a510-5b341055795d.png)

![image](https://user-images.githubusercontent.com/1268808/188708856-96f8d6dd-7f64-40f1-b424-93f03c5280b4.png)

As you can see both types are different and so it ends up causing TS errors. I've tried but couldn't find any other issue related to this. Is there any other way to compose typebox objects?

[Stackblitz Sandbox](https://stackblitz.com/edit/typescript-kaj3zj?file=index.ts)

**Comment by sinclairzx81** [comment]
@lhrinaldi Hi, thanks for reporting this issue.

I've had a look, and it appears there was a bug with the inference logic where it was dropping `readonly` and `optional` modifiers on intersection (the intersected schema representations were ok though) I have pushed an update on `0.24.37` that should resolve the inference issue. Let me know if that helps.

> Is there any other way to compose typebox objects?

Using `Type.Intersect()` is the correct way to combine multiple object schemas. Note that TypeBox doesn't implement a typical `Type.Extends()` (as in class inheritance) and instead opts for type Intersection as it's generally more flexible. So would recommend keeping on with your current approach.

### Type.Intersect future changes

Just note, if you're tying logic to TypeBox schemas for things like DB Model generation, just be a bit mindful that `Type.Intersect()`'s schema representation may change in later releases. Currently TypeBox manually intersects to produce an Object type (which is convenient for enumerating the intersected objects properties), but there may be plans to express this type via `allOf` in later releases...for example.

```typescript
const A = Type.Object({ a: Type.Number() })
const B = Type.Object({ b: Type.Number() })

const T = Type.Intersect([A, B]) // future: expressed as allOf: [A, B]
```

Hope this helps
S

**Comment by lhrinaldi** [comment]
@sinclairzx81 Wow, that was super fast! Thanks for the fix I can confirm it's working now.

![image](https://user-images.githubusercontent.com/1268808/188767282-bb6f42c1-54e2-4f36-9d23-5d42a94a95d9.png)

---

re: Future changes

I'm not using for model generation only for validation, it uses `Ajv` behind the scenes and I think they're compliant to JSON schema, so if it follows the spec I think that's fine.

Not sure if I should close the issue but feel free to do it. :)

**Comment by sinclairzx81** [comment]
@lhrinaldi All good :) Will close this one off.

Cheers

**Comment by webjunkie** [comment]
> `Type.Intersect()`'s schema representation may change in later releases. Currently TypeBox manually intersects to produce an Object type (which is convenient for enumerating the intersected objects properties), but there may be plans to express this type via `allOf` in later releases...for example.

Just as a side note: using `allOf` or similar comes with its own massive problems:
https://stackoverflow.com/a/23001194/62421

So I rather like the current approach...
