### ISSUE TITLE
Typescript Compilation Error in latest Version

### ISSUE THREAD

**Issue by denny99** [sinclairzx81/typebox#233]
With the update to 0.24.36/37 our pipeline failed with the following ts compilation error:

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/1826849/188805033-0c5ddb49-cc08-4621-a6f1-ade755fe0688.png">

**Comment by rexxara** [comment]
same issue
node_modules\.pnpm\@sinclair+typebox@0.24.37\node_modules\@sinclair\typebox\typebox.d.ts(107,21): error TS2536: Build:Type '"properties"' cannot be used to index type 'T[K]'.

**Comment by sinclairzx81** [comment]
@denny99 @rexxara Hi, thanks for reporting. Am investigating .... 

Which version of TypeScript are you using?

**Comment by denny99** [comment]
I am using ~4.6.4. We are limited to this version due to our other frameworks (e.g. NestJS)

**Comment by ipeshev** [comment]
We are using 4.3.5.

**Comment by DavidAbgaryan** [comment]
add   "@sinclair/typebox": "0.24.34", to dev dependency  it may help
"author": "",
  "license": "ISC",
  "devDependencies": {
    "@sinclair/typebox": "0.24.34",
    "@types/jest": "^28.1.7",
    "@types/jsonwebtoken": "^8.5.8",
    "@types/node-cron": "^3.0.1",

**Comment by RomanKamlykov** [comment]
I added "@sinclair/typebox": "0.24.34" to devDependencies, it solved the problem.

**Comment by ipeshev** [comment]
@DavidAbgaryan great, but in our case we have to change it in 40+ repos, will wait for patch.

**Comment by sinclairzx81** [comment]
Hi everyone. Thanks for the heads up. There was a update that went through late last night to resolve a inference problem for intersected modifier properties. However the implementation seems to have caused an issue in TypeScript versions less than 4.7.x. I have just pushed an update on `0.24.38` that should resolve the issue for TypeScript versions >= 4.1.5.

Apologies for the inconvenience, will investigate setting up some tooling to track previous compiler versions for future inference updates.

Cheers
S

**Comment by sinclairzx81** [comment]
@denny99 Will close off this issue for now, but if you're still having issues on CI, please don't hesitate to let me know. Thanks again for reporting this issue!
