### ISSUE TITLE
Unsafe string union as Record key

### ISSUE THREAD

**Issue by zedeus** [sinclairzx81/typebox#234]
I can't find a way to replicate this with TypeBox:
![image](https://user-images.githubusercontent.com/9434921/188831792-c2d5cdb6-9edd-4dd6-8cab-468ed5c6357d.png)

As per docs, there's this string union implementation using Unsafe:
```ts
export function StringUnion<T extends string>(
	values: T[],
	options: SchemaOptions
) {
	return Type.Unsafe<T>({ ...options, type: "string", enum: values });
}
```

However, this does not work:
```ts
const Union = StringUnion(["a", "b", "c"]);
const Map = Type.Record(Union, Type.Number());
```

Error:
```ts
schemas/custom.ts:17:25 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(key: TUnion<TLiteral<TLiteralValue>[]>, schema: TNumber, options?: ObjectOptions): TObject<never>', gavethe following error.
    Argument of type 'TUnsafe<"a" | "b" | "c">' is not assignable to parameter of type 'TUnion<TLiteral<TLiteralValue>[]>'.
      Property 'anyOf' is missing in type 'TUnsafe<"a" | "b" | "c">' but required in type 'TUnion<TLiteral<TLiteralValue>[]>'.
  Overload 2 of 2, '(key: TNumber | TString, schema: TNumber, options?: ObjectOptions): TRecord<TNumber | TString, TNumber>',gave the following error.
    Argument of type 'TUnsafe<"a" | "b" | "c">' is not assignable to parameter of type 'TNumber | TString'.
      Property 'type' is missing in type 'TUnsafe<"a" | "b" | "c">' but required in type 'TString'.

17 const Map = Type.Record(Union, Type.Number());
                           ~~~~~

  ../../node_modules/@sinclair/typebox/typebox.d.ts:256:5
    256     anyOf: T;
            ~~~~~
    'anyOf' is declared here.
  ../../node_modules/@sinclair/typebox/typebox.d.ts:231:5
    231     type: 'string';
            ~~~~
    'type' is declared here.
```

Workaround:
```ts
export function StringUnion<T extends string>(
	values: T[],
	options: SchemaOptions = {}
) {
	return Type.Unsafe<T>({
		...options,
		type: "string",
		enum: values
	}) as TString & { static: T };

}
```

**Comment by sinclairzx81** [comment]
@zedeus Hi. 

This is actually a design intent for `Type.Unsafe()`. TypeBox only composes for a strict subset of JSON Schema (essentially all the type representations listed [here](https://github.com/sinclairzx81/typebox#types-standard)), so when you move into a unsafe type, TypeBox can no longer assert that the schema structure can compose. If you need composability, then you need to remap from `Unsafe > Safe`

In the case of `Type.Record()`, the `Key` must be either `TString`, `TNumber` or `TUnion<TLiteral<string>>`, so the best approximation for `StringEnum` is `TUnion<TLiteral<string>>`. You can achieve this remapping with the following.

[TypeScript Link Here](https://www.typescriptlang.org/play?ts=4.6.4#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsgKoB2AzgQGbYrXARXkAywMGUBANjhZtkEZAFcw-DHAC+celAgg4AcgACNYFRL8CwKAHoY6DACMIAD1UAoG4cNwAtC9dv3Hz1+8+f9x-hQ2gDmAKJU4iCiANIYqP7OvknJKSl2GJaQsHAmmHgwQVTBwlSiXDx8-DQAPMgAfHAAvHAlohJSGLUNGTxUACY0cNqMUHhwNnCTcAD8iHAA2tFDVHAA1nEQ9HgAugBceIvbcD0Y-YM0BSEzKOW8AtW4h3X7yLeV1ReFwXXzR-ITUxeb3unxCP226Uy0HguRkgRC4UiMTiXSaKGOll6A2YtAYnWGvDg0QaANm8KKrQgwKq1WJGKxgwJow44ym1xZJzON24d34H0uRXB10oVFYVGqHAaLxK1V+JLZ+yoGAAboSAYqVbw7PRxDpiGx8l9EVEILFULV6adsSK6Ix+V86nUABQ0EgACwwIAILwAlPtyWEIiazaiEADgPQnQBCACCUD4qAAdMAaHGEy73Z6CInTpEfT6cm6lAB3OChePQJ2qACSVGVAmAfUNCKDqh9AKgGBg4igKzQmETJQzHq9OaDia9YCd61QTQa-Ywiep07i+YLBEGAeNyPN9RssjsDkSqRPp9SCS3QbgTo3cEwoz6EBIkVOhH1VHbR7P35-Xm1upId9myKY0LU5bFQSKOUnXrfhxAwGh9nmRMUOQbYCzDSZO27XsUFMQdcTtZB5iDMxeG2Z0kFhfZVEg4JVBwXMQH2WD4MGWR2wPBJfx4niElCSwCHAaRuN4sTTzsEg2AudFmkvSInXmVQYwYtQACFVNUABhVR0Mk6T4AAJTRBdE0MjApKgPonXk4M4idZAfXIfCAydfM4CPKTaCMl4AHkzAAKwsmBqkwtlwoiyKouimLIqPOAYxeAMAG4AVi9KMsy8L4rUpKBWCVKsqK4rovirS8q+QqSuq6qj1kOo7FhOBjLkt9SGqWFNmahoatio8mpaxA0t6ka+scBL9joqrRpmqKcsm-Lptm5apjKhbKuGlblrqoA)

```typescript
import { Type, Static, TUnsafe, TUnion, TLiteral, UnionToTuple } from '@sinclair/typebox'

// -----------------------------------------------------------------
// StringEnumToKey
// -----------------------------------------------------------------

export type StringUnionToLiterals<T> = UnionToTuple<T> extends infer S 
    ? { [K in keyof S]: S[K] extends string ? TLiteral<S[K]>: TLiteral<string>[] } 
    : TLiteral<string>[]

export type StringEnumToKey<T> = T extends TUnsafe<infer K> 
  ? StringUnionToLiterals<K> extends infer L 
    ? L extends TLiteral<string>[] ? TUnion<L> : TUnion<[]> 
    : never 
  : never

function StringEnumToKey<T extends TUnsafe<string>>(schema: T): StringEnumToKey<T> {
  if(!Array.isArray(schema.enum)) throw Error('Invalid StringEnum')
  return Type.Union(schema.enum.map(key => Type.Literal(key))) as StringEnumToKey<T>
}

// -----------------------------------------------------------------
// StringEnum (as per documentation)
// -----------------------------------------------------------------

function StringEnum<T extends string[]>(values: [...T]) {
  return Type.Unsafe<T[number]>({ type: 'string', enum: values })
}

// -----------------------------------------------------------------
// Example
// -----------------------------------------------------------------

const T = StringEnum(['A', 'B', 'C'])

const R = Type.Record(StringEnumToKey(T), Type.String()) // const R: TObject<{
                                                         //  A: TString;
                                                         //  B: TString;
                                                         //  C: TString;
                                                         // }>

type R = Static<typeof R>                                // type R = {
                                                         //  A: string;
                                                         //  B: string;
                                                         //  C: string;
                                                         // }

```
Hope this helps!
S

**Comment by sinclairzx81** [comment]
@zedeus Might close off this issue as this is the intended design for unsafe types.

I may give some thought to making it easier to map between `safe` and `unsafe` type representations in future releases. The runtime logic to remap into a safe type likely won't change, but there may be some potential to simplify recomputing the type (and avoid some of the complexity of `StringEnumToKey` and `StringUnionToLiterals` in the example above). Will investigate in the next significant release.

Cheers
S
