### ISSUE TITLE
Idea: Weight option for Union Casts

### ISSUE THREAD

**Issue by Bubz43** [sinclairzx81/typebox#235]
If I'm understanding the code correctly, when `Value.Cast` encounters a union of objects, it finds the most correct one and runs with it. For situations where there might be similar objects in the union and you have a specific key differentiating them, a weight option could help ensure correctness.

```ts
const UnionWeight = Symbol.for("TypeBox.UnionWeight");

enum Kinds {
  Foo = "foo",
  Bar = "bar",
}

const Foo = Type.Object({
  kind: Type.Literal(Kinds.Foo, { [UnionWeight]: 1000 }),
  // ... other properties
});

const Bar = Type.Object({
  kind: Type.Literal(Kinds.Bar, { [UnionWeight]: 1000 }),
  // ... other properties
});

const FooBar = Type.Union([Foo, Bar]);

// cast.ts
score += entries.reduce(
  (acc, [key, schema]) =>
    acc +
    (ValueCheck.Check(schema, references, value[key])
      ? schema[UnionWeight] ?? 1
      : 0),
  0
);
```

This might not actually end up being needed in practice, but thought I would throw it out there.

**Comment by sinclairzx81** [comment]
@Bubz43 Hi. Thanks for the suggestion :) 

Yeah, Union resolution for casting has been somewhat difficult to get right. I think the most ideal way to handle this would be to introduce a discriminator / tagged union field to the underlying schema (same as what's supported for [JSON TypeDef](https://jsontypedef.com/docs/jtd-in-5-minutes/#discriminator-schemas)). Unfortunately, discriminators fall outside the JSON schema specification, and I'm somewhat reluctant to include an additional `Symbol` specifically for unions (at this stage anyway), so this would rule out a weight `Symbol` also.

I've actually been working on the cast scoring algorithm tonight. The following is the updated algorithm that should be going up on the next npm publish. Code [here](https://github.com/sinclairzx81/typebox/blob/cast/src/value/cast.ts#L34-L55)

```typescript
  function Score(schema: Types.TSchema, references: Types.TSchema[], value: any): number {
    if (schema[Types.Kind] === 'Object' && typeof value === 'object' && value !== null) {
      const object = schema as Types.TObject
      const keys = Object.keys(value)
      const entries = globalThis.Object.entries(object.properties)
      const [point, max] = [1 / entries.length, entries.length]
      return entries.reduce((acc, [key, schema]) => {
        const literal = schema[Types.Kind] === 'Literal' && schema.const === value[key] ? max : 0
        const checks = ValueCheck.Check(schema, references, value[key]) ? point : 0
        const exists = keys.includes(key) ? point : 0
        return acc + (literal + checks + exists)
      }, 0)
    } else {
      return ValueCheck.Check(schema, references, value) ? 1 : 0
    }
  }
```
At the heart of this scoring system is the idea that it's possible to derive the correct sub schema by running relatively simple heuristics against the value being casted. Objects have been a bit of a problem though, so the updated algorithm now factors for a property's existence, whether the property type checks and whether a property is matching a literal const value (suggesting that property is likely intended as a discriminator). The updated algo now also scores proportionally to the property count to prevent large schemas biasing other schemas where literal values have matched.

I think overall, the design of `Value.Cast()` should be more intuitive than hard science (given the fairly quantum nature of union resolution). I may revisit this algorithm in future however, as it's possible a Bayesian inference strategy may be the best overall solution.

Thanks for checking out that code though and for the suggestion! Explicit weighting is a good idea (and will give it some thought for maybe expressing in a another form (one that can be understood by non-JS systems)). But for now, will keep on with the internal scoring system for the `0.24.x` release.

Cheers!
S

**Comment by Bubz43** [comment]
The updated `Score` function looks quite robust. Going to close the issue.

Thanks for the awesome library!
