### ISSUE TITLE
Better documentation of changes

### ISSUE THREAD

**Issue by Xhale1** [sinclairzx81/typebox#238]
I love this library and really appreciate your work @sinclairzx81 😄 

Would it be possible to better document changes in each npm release? The changelog hasn't been updated in a month and every commit simply says "Next" which makes it difficult to stay on top of what's new and what changed.

**Comment by sinclairzx81** [comment]
@Xhale1 Hi, thanks for the kind words.

Yes, I should make more of an effort to keep the changelog current. Most of the recent 'Next' updates are documented under their respective PR's. I do plan to summarize these changes in the changelog once I feel the 0.24.x release had stabilized (this release has been quite a large body of work), however documenting each incremental change made to refine this release has been quite challenging (but the readme should reflect all current functionality)

At a high level, with the exception of changes to Type.Intersect() and the recent addition of Type.Never(), pretty everything else added to the library (Compiler, Value, Format, Guard and Conditional) is new and constitutes the entirety of the 0.24.x release. Each Next commit can be interpretted as incremental refinements, bug fixes and minor design updates that are difficult summarize in bullet points (especially given the frequency these changes have needed to be rolled through)

Apoligies for the lack of changelog updates though, but hope this brings a bit of high level insight into what's been  #changing. Will strive ammend the changelog accordingly with a full summary of updates within the next few weeks.

Cheers!
S

**Comment by sinclairzx81** [comment]
@Xhale1 Hey, will close off this issue. For now I would recommend checking the PR's from #185 onwards to get a sense of what's been changing. As mentioned, will update the changelog in the coming weeks.

Thanks for the suggestion! (It's good to know people were reading that changelog) :)
S

**Comment by kevinlul** [comment]
Seconding this, it's hard to keep up with what's up 😅

**Comment by sinclairzx81** [comment]
Updated changelog can be found https://github.com/sinclairzx81/typebox/blob/master/changelog.md.

Apologies for the delay.

Cheers
S
