### ISSUE TITLE
Cast does not account for Type.Array options

### ISSUE THREAD

**Issue by Bubz43** [sinclairzx81/typebox#239]
When casting a value to `Type.Array` `minItems`, `maxItems`, and `uniqueItems` aren't taken into consideration.  This leads to a situation where `Value.Check` on a just casted value is false.

```ts
const T = Type.Array(Type.Integer(), { uniqueItems: true });
const castedA = Value.Cast(T, [1, 1]);
Value.Check(T, castedA); // false - casted is still [1, 1], should be [1]
```
Presumably it should work something like this:

```ts
it("Should remove duplicates if uniqueItems is true", () => {
  const T = Type.Array(Type.Number(), { uniqueItems: true });
  const value = [1, 1, 2, 2];
  const result = Value.Cast(T, value);
  Assert.deepEqual(result, [1, 2]);
});

it("Should should fill up with defaults to minItems", () => {
  const T = Type.Array(Type.Number(), { minItems: 3 });
  const value = [1, 2];
  const result = Value.Cast(T, value);
  Assert.deepEqual(result, [1, 2, 0]);
});

it("Should should truncate to maxItems", () => {
  const T = Type.Array(Type.Number(), { maxItems: 3 });
  const value = [1, 2, 3, 4];
  const result = Value.Cast(T, value);
  Assert.deepEqual(result, [1, 2, 3]);
});
```
The situations where you have multiple options set at once, like `uniqueItems` and `minItems`, can become a bit weird though, possibly leading to a type which is impossible to cast to. Maybe require having a default value set in those situations, or after `Value.Cast` is completed, check the final result with `Value.Check` and throw an error if it fails. The latter would probably be worthwhile regardless, otherwise could easily start using a casted value assuming its correct when it actually isn't.

**Comment by sinclairzx81** [comment]
@Bubz43 Hi. Hmmm, yes the current array casting behavior doesn't look quite right. 

I do agree that minItems and maxItems should be implemented accordingly (with maxItems potentially truncating, and minItems appending the array). I also agree partially that reducing `[1, 1]` to `[1]` on uniqueItems would be expected (and required given that the casted value is currently invalid). However it's unclear if cast should just prohibit `uniqueItems` outright, or run more exhaustive checks on potentially generative values if `minItems` is specified (ideally would prefer to avoid additional checks post generative values if possible)

Ill do some investigations on this! (some of this may pertain to generative record properties also)
Cheers
S

**Comment by sinclairzx81** [comment]
@Bubz43 Hi. This logic has been implemented on `0.24.40`. TypeBox will now cast `minItems`, `maxItems` and `uniqueItems` as per your suggestion. Just be mindful that a potential exists for schemas with `uniqueItems` to fail with when configured for `minItems` (for example, when the unique `Set<T>` results in an array less than the `minItems` length). In these instances, you will get a `ValueCastArrayUniqueItemsError` thrown. There is one additional type check required for `uniqueItems` only. 

I've included your units tests above within TypeBox's tests for reference, along with some other tests around this functionality that you can view here https://github.com/sinclairzx81/typebox/blob/master/test/runtime/value/cast/array.ts#L63-L136 to check the error cases. I think the functionality should be good to go.

Let me know if things look good yourside, and if so, ill close off this issue.
Cheers!
S

**Comment by Bubz43** [comment]
Looks good. Don't have any use cases for `minItems + uniqueItems` myself, just noticed that its an annoying edge case. Only part I'm a bit curious about is:
```ts
  it('Should throw when casting arrays with uniqueItems and no value or default value', () => {
    Assert.throws(() => Value.Cast(Type.Array(Type.Number(), { uniqueItems: true }), null))
  })
```
If its just `uniqueItems` isn't defaulting to an empty array, without having to explicitly specify it, fine?  An empty `uniqueItems` array is perfectly valid. It isn't a big deal to specify `default: []`, but it feels a bit off that 
```ts
const T = Type.Array(Type.String(), { uniqueItems: true });
const fromEmptyArray = Value.Cast(T, []) // works
const fromUndefined = Value.Cast(T, undefined) // throws
```
as I think a quite common use case will be using `Value.Cast` to fill in missing properties.

Anyway, its also fine to leave it how it is, so feel free to close the issue. Thanks for the speedy implementation.

**Comment by sinclairzx81** [comment]
@Bubz43 All good. Just on the following.

> If its just uniqueItems isn't defaulting to an empty array, without having to explicitly specify it, fine? An empty uniqueItems array is perfectly valid. It isn't a big deal to specify default: [], but it feels a bit off that

This throw is due to cast being dependent on Value.Create() for value generation when the incoming value isn't an array (i.e, when it's null or undefined). Because Value.Create() mandates a array schema must specify a default value when using `uniqueItems`, this error should be present in casts also (as casts are essentially a parameterized creates)

```typescript
// error: array must specify a default value if using uniqueItems
const A = Value.Cast(Type.Array(Type.Number(), { uniqueItems: true }), null)

// ok
const B = Value.Cast(Type.Array(Type.Number(), { uniqueItems: true, default: [] }), null)
```
I did spend some time looking at this, and at this stage mandating that uniqueItems have a default value for both casting and value creation is going to be easiest to reason about moving forward. Ill leave the current functionality to simmer for this revision, but may revisit for the 0.25.0 release.

Will close off for now!
Cheers
S
