### ISSUE TITLE
feat: allow TString to accept generic parameter for "format"

### ISSUE THREAD

**Issue by smiley-uriux** [sinclairzx81/typebox#246]
My specific problem is trying to extract string properties with a `date` format, so I can infer the return type of a function that converts any date strings to Date() instances. So something like this:

```
export const Resource = Type.Object({
    name: Type.String(),
    expiresAt: Type.String({ format: 'date' }),
});

const resource = convertDateStrings(Resource);
resource.createdAt.toISOString();
```
But since TString is not generic, I don't see a way to properly infer the passed `format` value as a string literal. It always comes back as a simple `string`. I was able to add generic support to TString with just a few line changes and my utility worked as expected and it didn't seem to cause any downstream typing issues. Here is what I'm trying to achieve:

```
type StaticWithDates<O extends TObject> = Static<
    O & {
        properties: {
            [P in keyof O['properties']]: O['properties'][P] extends TString<'date'> ? TUnsafe<Date> : O['properties'][P];
        };
    }
>;

type Test = StaticWithDates<typeof Resource>;
// now inferred as:
// {
//       name: string;
//       expiresAt: Date;
// }
```

Now I still have my work cut out for me, since the utility doesn't handle nested objects, arrays, etc, but I'm just really gauging feasibility at this point. BTW, is there any technique or utility type that the library exports that would help perform this kind of conditional transformation exhaustively?

**Comment by sinclairzx81** [comment]
@smiley-uriux Hi, have just pushed an update to make TString accept an optional generic `format` argument. There is actually some plans to make all TypeBox schema properties generic in this way, but starting with TString for this particular use case makes sense. 

As for utility types to do the remapping you describe, there isn't anything provided by TypeBox to do this automatically, but I may investigate a HKT utility type in later releases. For now you can achieve remapping string formats using the following on the `0.24.42` update.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/PTAEFpK6dv4fAsAKBKAygFwIZYJYDGASgKYC2OADquovQ43KqvuVQPYBOWoAVKBwBnUABUAnlVIiAZlw7lQAcgACQ-ADtCAGxz4uwLJNIAjDgA8lLNGFEcAJhwBcoAAoBXXgEF79-AQ4NHG1QADFuSl4ySioqTQBzUGJ3bWlQAAlSLlJUUnNOHlAjKUxcAhIKanCuSIAeUNA8rFINexEhLC4EgD5QAF5UUCGwxvNm1pElezxSJVAAflAAERnQJ0HhhqaWtuV3Lm05xYBVYgAZNY2hjq6NeOs8gt5i0lK8ImjqWtFR8d2JKRCAB0ogwhAAFpVegMUMMxL8diIAdIQQB5EwAK1IhCwtU0Miybl6iwA3qAANoAaVAmlAAGtSOIODI3ABdFzYd4VGK1VxU1m9AC+l1hwx+2wmYmMwNEoncVFSeI0BK4RIWoDJVJpGnpjOZbI5ZQ+lSovP5QpFcPFY0RUsBIOOGnwgSVKrVpIp1NpDKZLNc7Le5U+pr5lIFoEF5I07nIJiyrMtYoRkuRMq8XC4OHErsJrmJoHTmeznKDJt53V661FQ2tfyR0pB2Fu8RzqtC+ZLxpi1Tq7cTNYbncI3261loYCYk6nyBsoAAouYcOxUuOINP19PrGwnhq7a9hXIFMo1JodHoDC8zJZrIRAh1lqs+nugU2EgAKMkyCJ4FxTGZzQUAEpUFvDR72OA5+mfV87g-UAvxqH89gOADgJQEC714H4n2RIF0SxHEPyuUAOExbEsBcXD8PIuD9m0FwIJCICABpiJwDMs0o4wgULLM3yosjCLJaZmhcFZmmY0A6IYyCgMA1jqyKeVUi4qQQWU0g33JcTSEkxjWXk4j3CdQJVNIIFHWdDQtJ0vSDgMhS4RuBIxJmBSgLHFAXnhJ8h2DWoXn1URenQbzsI1Yi4Si6KYqi9A4VIgiKIixTYrS9L4pi6TQFOM4AG5IvSoq4rAOFBQK1Liqq0BMqGdiixcElCuqoraqikTSFc5oKpa3q2rhbLcp63rqrayNWWGkbirarANJcbS3Jy84Juaqbora4yrK614AB8lvy1a1rhNrnLubbJqO2L0EFVAgA)

```typescript
// -----------------------------------------------------
// StaticRemap
// -----------------------------------------------------

import * as Types from '@sinclair/typebox'

// Todo: Put Additional Format Remapping Rules Here
export type StaticRemapFormat<F extends string> =
    F extends 'date' ? Date :
    F extends 'url' ? URL :
    string

export type StaticRemap<T extends Types.TSchema> =
    T extends Types.TObject<infer P> ? { [K in keyof P]: StaticRemap<P[K]> } :
    T extends Types.TTuple<infer P> ? { [K in keyof P]: StaticRemap<P[K]> } :
    T extends Types.TUnion<infer P> ? { [K in keyof P]: StaticRemap<P[K]> }[number] :
    T extends Types.TArray<infer P> ? Array<StaticRemap<P>> :
    T extends Types.TString<infer F> ? StaticRemapFormat<F> :
    Types.Static<T>


// -----------------------------------------------------
// Example
// -----------------------------------------------------

import { Type } from '@sinclair/typebox'

const Date = Type.String({ format: 'date' })
const Url = Type.String({ format: 'url' })

const T = Type.Object({
    object: Type.Object({ url: Url }),
    array: Type.Array(Type.Object({ date: Date, url: Url })),
    tuple: Type.Tuple([Date, Url]),
    union: Type.Union([Date, Url]),
    string: Date,
})


type T = StaticRemap<typeof T> // type T = {
                               //     object: {
                               //         url: URL;
                               //     };
                               //     array: {
                               //         date: Date;
                               //         url: URL;
                               //     }[];
                               //     tuple: [Date, URL];
                               //     union: Date | URL;
                               //     string: Date;
                               // }

```
Just note, I'm currently trialing the generic TString on the 42 publish. Depending on if this has caused issues, I may revert and defer to the next minor release, but the update should be ok.

Hope this helps
S

**Comment by smiley-uriux** [comment]
Wow this is amazing. Really appreciate the quick response and example!
