### ISSUE TITLE
nullable is not working with Static generic usage

### ISSUE THREAD

**Issue by stearm** [sinclairzx81/typebox#248]
**typebox version**: `^0.24.42`

I followed the documentation to create a `Nullable` type as:

```typescript
export function Nullable<T extends TSchema>(schema: T) {
  return Type.Unsafe<Static<T> | null>({ ...schema, nullable: true });
}
```

or

```typescript
const Nullable = <T extends TSchema>(type: T) => Type.Union([type, Type.Null()]);
```

and I'm using it as:

```typescript
export const GetAnalysisResponseT = Type.Object({
  id: Type.Number(),
  name: Type.String(),
  description: Nullable(Type.String()),
  assets_ids: Type.Array(Type.Number()),
  status: StringEnum(Object.values(AnalysisStatus)),
  result: Type.Any(),
  user_id: Type.Number(),
});
```

but I'm getting this as the derived type:

![Screenshot 2022-09-19 at 12 51 01 PM](https://user-images.githubusercontent.com/14802795/191001920-8b85d2bf-8931-4727-8084-c15df454c505.png)

Am I doing something wrong?

**Comment by sinclairzx81** [comment]
@stearm Hi, just make sure you're using `strict: true` in your tsconfig.json. Also, TypeBox requires TypeScript 4.1.5 at a minimum.

Have tested your schema [here](https://www.typescriptlang.org/play?strict=false#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsriQBYYgFwC+cAZlBCHAOQACAzsADsSAGwLAoAehjoMAIwgAPTgFgAUGpIQBveADkArsNGzhGOAF44AHmRwMCmBgEATXiko06APgAU0zABcKACUFl4oMgB0AKoCwFo+ANr+2BGYkQZGPsEAusFqavaQsHCa2vAA4hgwAIICBMKo-LwAShi8kNoYtpZo6QDysgBWGCQwPghqcHDAzkF9GBn6ILIYUNlYU3D1IBjzUfhQggDmG1vO7SRHYMRaQZnGpj4LkYcn2cGbqtMEvLzVvAA+rNePt0jUoFACKhnlEDCs1h8vtMoO1DDAwYs6jDPlt9P8oMC5mlFvDVutcaoGMEANwFVQpFAWPCEYgkKwpCDMOBVWr1RrNNodLT-ZBeIA) and everything should be ok.

Let me know if that helps
S

**Comment by stearm** [comment]
with `strict: true` it is working, I forgot this when bootstrapping the project! Thank you 🥇
