### ISSUE TITLE
TSelf type passing

### ISSUE THREAD

**Issue by marklai1998** [sinclairzx81/typebox#249]
It is not possible to pass the `TSelf` to the nested part of the recursion while exporting the the the nested part separately
```ts
export const a = (recursivePart: TSelf) => Type.Object({ // TSelf destroy the type here
  nestedField: Type.Array(recursivePart),
})
export type A = Static<ReturnType<typeof a>> // nestedField will be unknown[] instead of ResursivePart[]

export const b = (recursivePart: TSelf) => Type.Object({ // TSelf destroy the type here
  nestedField: Type.Array(recursivePart),
})
export type B = Static<ReturnType<typeof b>> // nestedField will be unknown[] instead of ResursivePart[]

export const recursivePart = Type.Recursive(
  self => Type.Union([a(self), b(self)]),
  {
    $id: 'formBlock',
  }
)

export type ResursivePart = Static<typeof recursivePart>
```

Is it possible that TSelf keep the "self" part?
```ts
export const b = (recursivePart: ResursivePart) => Type.Object({ // somehow to keep it ResursivePart type
  nestedField: Type.Array(recursivePart),
})
export type B = Static<ReturnType<typeof b>> // then nestedField will be ResursivePart[]

export const recursivePart = Type.Recursive(
  self => Type.Union([b(self)]), // not sure what type "self" would be
  {
    $id: 'formBlock',
  }
)
export type ResursivePart = Static<typeof recursivePart>

```

**Comment by sinclairzx81** [comment]
@marklai1998 Hi. Singularly recursive types can be expressed in TypeBox using generics as you are, but they need to be written somewhat carefully to allow inference to work. Note the type inference is still a bit of a work in progress, with TypeBox somewhat up against technical constraints of the TS type system.

I can perhaps offer a couple of advanced examples of using this form of recursion if it's helpful. Ill submit these below in case your existing recursive data structure can be refactored inline with these examples.

### Renderable Scene Graph

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsrhgDYBmcAvnDVBCHAOQACAzsAHYkqBYFAD0MdBgBGEAB7sAsAChlo0XAC0W7Tt179Bw0d2r1uEhj4Y4AcSgEwACzgBRWQXBUMpzcb-+Aw2VlDFlIWDgJTDgAeSkAKwwSGABmABE4AF48QmISAB4AJQwYAFcoPjRMfKiMCDo4xOT0gD4WkLDoeBIIPm54RqTUjOz85DhQmEsAE24USloWgAo+CGmMAC4UAEoslpRJADpB5KWEZThIyS2qjEOAGWAp+yol9hPh9m2sC7hV9e4NyOAEEoPZUCs1hhtsp6DCVEpQuF4LU4ABZDDcZzZfBEUhFErlSqSGqSerozGONodZFwHp9eAYrFZOBjCayKZ8Wbzag0Zb-TY7PYHTDHBJDM6-WpA0WPZ4EV7sJmOL4-JSXAWAkV3UHgyHreFw4KIzoRVEAYQ8GHsLNxeQJZQqt1JmHJlpA1oI1JNtPp-Tg7s9LLZkxmcwovP5UJuu0y+1uYqaMEl6qumBldzlnsVgfsqt+mozh11BAhAsN8JpXTT1keAHNHPAcbl8cVHcTqrVyfXG96kdW-fAe03WeNQ1zwws+frBchY-Gjh8U5dpdqHk9s29h-nU4W1yWy1CK8a1L5Aue-D57hAINxqKhIo4IKUG-ByQRuD4L9+jKYfP2IkED85gAOShRA4EOKCGH-U1uiEbg5g+dJ2U5bkwPWCCoMOGClFPAD4OAilmXHdDwKQbDcPwuC6QQuZcwIVCwzgDDrAo6D6Fg306LgYcmInFjyMgjjjQImtBMw5s8QKLs6FY9ofQHXp-VYlkE2KEhyl4AA3DAZ2FBMAFU+GAXolgAbV+ZC0hnb5fmVWy1UuBjHN+YdbOUABdbZKyUGhSgEYhejgKAZmtGctlY3ZzlTU8YDWCAtn4bhMGSP5wMca1vCUTiESAA)

<details>
   <summary>Expand Renderable Scene Graph Code</summary>

   ```typescript
import { Type, Static, TSelf } from '@sinclair/typebox'

// ------------------------------------------------------------
// Scene Graph Example
// ------------------------------------------------------------

export type Object3D = Static<ReturnType<typeof Object3D>>
export const Object3D = <T extends TSelf>(node: T) => Type.Object({
  type: Type.Literal('Object3D'),
  nodes: Type.Array(node)
})

export type Mesh = Static<ReturnType<typeof Mesh>>
export const Mesh = <T extends TSelf>(node: T) => Type.Object({
  type: Type.Literal('Mesh'),
  nodes: Type.Array(node)
})

export type Camera = Static<ReturnType<typeof Camera>>
export const Camera = <T extends TSelf>(node: T) => Type.Object({
  type: Type.Literal('Camera'),
  nodes: Type.Array(node)
})

export type Light = Static<ReturnType<typeof Light>>
export const Light = <T extends TSelf>(node: T) => Type.Object({
  type: Type.Literal('Light'),
  nodes: Type.Array(node)
})

// ---------------------------------------------
// Loosely thought of as
// ---------------------------------------------
//
// export class Node { ... }
// export class Object3D extends Node { ... }
// export class Mesh extends Node { ... }
// export class Camera extends Node { ... }
// export class Light extends Node { ... }

export type Node = Static<typeof Node>
export const Node = Type.Recursive(node => Type.Union([
  Object3D(node),
  Mesh(node),
  Camera(node),
  Light(node)
]))

function render(node: Node) {
  // todo: inspect node here
}

```

</details>

### Expression Syntax Tree

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUGUMA2AZjrjAIYzADGcAvnEVBCHAOQACAzsAHbUFywKAHoY6DACMIADzYBYAFBKRIuAFpNW7Tt179BwzpVqAojLBQMXHhF4orGExqOu37g0qUYL0eOMw4ACE+cihUAHlMKEpoOABeODJKGgAeACUMGABXKF40TFSAjAgiYNDwqIwYmGgAPjrvX1g4ajsueBDeMMjo2KgEuAAKAEoEupQJADoAVV5gOyGAbSU4ScwpgBlgGGryAiG2AGo2EaxV9Ywtnb2DtnVT88U1gqvt3Zi7gCpHi9frj77Q4iU5KAC6Iy8ih8kBaxTg71u5ks1ls9kSySo1AyWVy+QkRQkpQRN0+yKsNgWvAaTVh8DavA6JMBBHJqKpg1SyDgPl2vAAJlw8IQiHUhrwIPyMAAuFBjeITf4RSQAKww1BgQwQF2Ksv+iM+hwAwu0YGzKXZfs84AA3fbZGWXKYAQV4qFGSjokOU0Oa-gk5W64XNaMGmLSmRyeVehMwxK6PRDVJpvrprVNgcTFgpocSXJ5Mj5guFxDFEqlevliumyrVGq1OokeumBqBbATwez7MtZwuED6tSgso7vT2g9GTzWBAwRBgsvL2AuUGAAHMABZzuALz3e2l+ODw5DVIOoJN2MMULE4qP4wrFYlHvJZlEW6mNVP7hlMx8ns-ouD5ryGACkKyD4KW4qSo6yBVk6tbqpq2rWrqTqtncP7PjmVJWmsDL8jsVLNhscxUssFxrCOf6QVKvbWmsaFUQu3prBCk4HlADoAGr2o6C5sUQ+xcBg3EEA685QTuUIwvu8ImoyMDOpSK68CAwHwBil4Rri0YEveZRyR0ik8Mpqm8DAKbSS0X7wAZClKSpamctyQEgSWorUdBsFKqqCENshTaoaSba2UZq4OWZOG2mEwDkJI05EVcZDLrwK4ThcMJYXYCWzPMiwrHRmadi+aIebRaz0UFrJdq+pUXBCkk+qoLgeC1rjOJsEAQEJBCoAea4QNk67wMS5BcM4rUTYYJjOJZ9KCDYSSoGZ5AyAAclBiBwFM230DNfqtPNQoMdVoYucWuBLRQa0bUg21TLtihNbNB2jUKlEnRyZ1Chdy3XVKm13Q9T37QIr0oMemHdvYX2Lb963-bdO10HtaagwtIX2aZ8Awz9V3wxgANI1J+3wrjK34xeKTYnpsN41B77PdZtPkxtiT-Jk1C5DwNoYEMQz4150wkXlFzHcVpEC2x73i4skt-BDRWZbw-NQWVcAY8Z4WagL4IjLuj1qJNRvG84f4OBgBOmCAOzjcbdstVCRDZPwVB2F8cBWzsHmymTf0YCMsoAJKAnFGDB2O0CpB0yUrhMSFrFwADuOzUGuwwLlMxRjPH5XUKNBNsLZf5sLKOflXAVg3nAqDAIQ-JblBUx2qJTgFcjBV50J7DS0rJeIORucZtOs6DEsd2e5qGfDzAIxglMKoQHwhzsMx5fpvJFerhuo-j9bk+N8uQ2z-Pi-K2wK8D2sld4tXtcEPXAAGQwACQINPDCvxn-YR1AH8IIfG4vQPwHu3cuncC4YUVlDPuZdB4bzwgRc8iQx7bQnh5KYCDXa8GPgvJe59QQFVwhmGAHFhI8R3qgve6CSFcR4rPS+68mQCQIEJESDoKFTDQRnZhrC6FggYdfPIt865wCfi-BAmCqRejgAAfmGK-GhZCW7SNlOInhSiHRehGMAtuA9wHsA1mFLGMCGFMztMuWK05BgZ3MTFUOpiMwZShhwrhjcnGvhwafZeBC14V20vYGuIiH5M1frYyxGAGCJFfu4tEdAdHl1AQ9dutt7apKMKbGQ5BwDThSWkvJugoRM2QI4H2l0Wb-USDnFChdTShRMmpNgbEwmh1lGwIgnVGnpQ+llfuBVqk92gWxNY38ajQFaScIZcBp6lwYf0iop5um8E6YQuAIz+jjOWb46Zm1qlF0WY0qKLdZQAEZ6CTKvlvTcSBdmmmLjgZuYk4AACYHoJMmQAq5syArtnmXchhazBwbPOVMmcVy4AMLWDc+SdzDmPIAMzgpWXQYFHzS6It8ZC75kCFkyyWTgCF698JYLRQSzFmBWl7NxQc0lsLHSKPRRi5FDLfGKLYY6JANKoUdBhTSh5joAAszK15MoJeotlJKVnly5WafZ+LJXlT5bKAArEKhJqrXnlUSe3ZJigmYmgqXAFBnCqHFItp4vBF8fRfggNOKYBAICpX1f7OATUmbtIgIMPmpyjjPLGD6oYCL-VDEUWMORQx+VjFUUqvWesgA)

<details>

<summary>Expand Expression Syntax Tree</summary>

```typescript
import { Type, TSelf, Static } from '@sinclair/typebox'

// ------------------------------------------------------------
// Expression Tree
// ------------------------------------------------------------

export type BinaryOperator = Static<ReturnType<typeof BinaryOperator>>
export const BinaryOperator = () => Type.Union([
  Type.Literal('+'),
  Type.Literal('-'),
  Type.Literal('*'),
  Type.Literal('/')
])

export type LiteralExpression = Static<ReturnType<typeof LiteralExpression>>
export const LiteralExpression = <T extends TSelf>(node: T) => Type.Object({
  type: Type.Literal('ConstExpression'),
  value: Type.Any()
})

export type BinaryExpression = Static<ReturnType<typeof BinaryExpression>>
export const BinaryExpression = <T extends TSelf>(node: T) => Type.Object({
  type: Type.Literal('BinaryExpression'),
  operator: BinaryOperator(),
  left: node,
  right: node
})

export type TernaryExpression = Static<ReturnType<typeof TernaryExpression>>
export const TernaryExpression = <T extends TSelf>(node: T) => Type.Object({
  type: Type.Literal('TernaryExpression'),
  condition: Type.Union([
    BinaryExpression(node),
    LiteralExpression(node)
  ]),
  trueValue: node,
  falseValue: node
})

export type ConstAssignment = Static<ReturnType<typeof ConstAssignment>>
export const ConstAssignment = <T extends TSelf>(node: T) => Type.Object({
  type: Type.Literal('ConstAssignment'),
  variable: Type.String(),
  expression: Type.Union([
    BinaryExpression(node),
    LiteralExpression(node)
  ])
})

// ---------------------------------------------
// Loosely thought of as
// ---------------------------------------------
//
// export class SyntaxNode { ... }
// export class LiteralExpression extends SyntaxNode { ... }
// export class BinaryExpression extends SyntaxNode { ... }
// export class TernaryExpression extends SyntaxNode { ... }
// export class ConstAssignment extends SyntaxNode { ... }

export type SyntaxNode = Static<typeof SyntaxNode>
export const SyntaxNode = Type.Recursive((Node) => Type.Union([
  LiteralExpression(Node),
  BinaryExpression(Node),
  TernaryExpression(Node),
  ConstAssignment(Node)
]))

// ------------------------------------------------------------
// Expression Tree Emit
// ------------------------------------------------------------

function* Emit(node: SyntaxNode): IterableIterator<string> {
  switch (node.type) {
    case 'ConstExpression': {
      return yield node.value
    }
    case 'BinaryExpression': {
      const left = [...Emit(node.left)].join(' ')
      const right = [...Emit(node.right)].join(' ')
      return yield `(${left} ${node.operator} ${right})`
    }
    case 'TernaryExpression': {
      const condition = [...Emit(node.condition)].join(' ')
      const trueValue = [...Emit(node.trueValue)]
      const falseValue = [...Emit(node.falseValue)]
      return yield `((${condition}) ? (${trueValue}) : (${falseValue}))`
    }
    case 'ConstAssignment': {
      const variable = node.variable
      const expression = [...Emit(node.expression)].join(' ')
      return yield `const ${variable} = ${expression}`
    }
  }
}

// ------------------------------------------------------------
// Example
// ------------------------------------------------------------

const Tree: SyntaxNode = {
  type: 'ConstAssignment',
  variable: 'foo',
  expression: {
    type: 'BinaryExpression',
    operator: '+',
    left: {
      type: 'BinaryExpression',
      operator: '+',
      left: { type: 'ConstExpression', value: 1 },
      right: { type: 'ConstExpression', value: 2 }
    },
    right: {
      type: 'BinaryExpression',
      operator: '+',
      left: { 
        type: 'ConstExpression', value: 3 
      },
      right: { 
        type: 'TernaryExpression', 
        condition: { 
          type: 'ConstExpression', 
          value: true 
        }, 
        trueValue: { 
          type: 'ConstExpression', 
          value: 4 
        }, 
        falseValue: { 
          type: 'ConstExpression', 
          value: 5 
        } 
      }
    }
  }
}

const Code = [...Emit(Tree)].join(' ')

console.log(Code) // const foo = ((1 + 2) + (3 + ((true) ? (4) : (5))))
```

</details>

Currently, the above examples are the envisioned Type.Recursive() usage, however I am open to discussions on better ways to communicate this usage. Recursive types are a fairly complex topic, but you're on the right track using generics with `TSelf`. 

Hope these examples help, happy to discuss more if you need.
Cheers
S

**Comment by marklai1998** [comment]
@sinclairzx81  Thanks
In fact, I'm updating from older version that uses `TAny` and started getting errors from the latest one.

I definitely tried your example with the `<T extends TSelf>` approach but no luck(always getting never[] or unknow[]) along with other force type casting approaches (that makes the code ugly). Now I just type the recursive part separately to make it work first.

Actually, I much prefer the `TAny` approach from prev version

I know typescript can do recursive but not so sure how to bridge it with TypeBox as it requires the `Type.Recursive` function for the Jsonschema side to work.

I think the first arg of the `Type.Recursive` callback has to be `any` as a tradeoff, I personally don't think anybody would need to use this arg in their code(I mean need it well typed, no one will temper with it anyway?) as it just serves TypeBox purpose
```
export type Light = Static<ReturnType<typeof Light>>
export const Light = (node: Node) => Type.Object({ // I need this to be node for the Light type to work
  type: Type.Literal('Light'),
  nodes: Type.Array(node)
})

export type Node = Static<typeof Node>
export const Node = Type.Recursive(node => // this cannot be node... so any would be a good fit?
{
return Type.Union([
  Light(node) // this needs to be node
])
}
)
```

**Comment by sinclairzx81** [comment]
@marklai1998  Hi!

> In fact, I'm updating from older version that uses TAny and started getting errors from the latest one.

The previous Type.Rec() has been deprecated in favor of Type.Recursive() that generates more terse JSON schema and supports recursive type inference through `TSelf`. But if you are upgrading, it's actually possible to replicate the legacy Type.Rec() using Type.Unsafe() (see documentation [here](https://github.com/sinclairzx81/typebox#types-unsafe)). The following re-implements the pre-0.24.x `Type.Rec()` function that used the `TAny` self parameter. You should be able to substitute `Type.Rec()` for `Rec()` below.

```typescript
import { Type, Static, TSchema, TAny, SchemaOptions } from '@sinclair/typebox'

// pre-0.24.0: Recursive
function Rec<T extends TSchema>(callback: (self: TAny) => T, options: SchemaOptions = {}) {
  const $id = options.$id || ''
  const self = callback({ $ref: `${$id}#/$defs/self` } as any)
  return Type.Unsafe<Static<T>>({ ...options, $ref: `${$id}#/$defs/self`, $defs: { self } })
}


type Node = Static<typeof Node>
const Node = Rec(self => Type.Object({
  id: Type.String(),
  nodes: Type.Array(self)
}))

console.log(Node)
```

> I know typescript can do recursive but not so sure how to bridge it with TypeBox as it requires the Type.Recursive function for the Jsonschema side to work.

It's true that recursive types have been difficult to get right, but I do feel that TypeBox should strive further for correct type inference. Unfortunately, correct inference requires having to construct schemas within the constraints and limitations of the TS compiler. Making recursive schemas easier for end users is an ongoing research project on my part (there's still work to do!)

> I think the first arg of the Type.Recursive callback has to be any as a tradeoff, I personally don't think anybody would need to use this arg in their code(I mean need it well-typed, no one will temper with it anyway?) as it just serves TypeBox purpose

Currently, 0.24.x treats `TSelf` as an opaque reference that you can think of it as `TAny`. Because those examples above pass `TSelf`  generically and because `TSelf` is opaque, when you do infer; TypeBox will pass the generic `TSelf` to a kinded type (HKT) to lazily evaluate at the call site (vs eager which would require infinite recursive evaluation of the type). The evaluation strategy in 0.24.x is pretty complex (it took many months of research and waiting for TS enhancements to implement), but is generally the preference moving forward...

In terms of it's use, I currently use it for some of my own projects (for example [recursive form](https://forms.sinclairzx81.repl.co/) generation), so will be continuing to support it in future releases. Additional enhancements to it are planned to be built around the current type architecture (this is an ongoing research project of mine).

Let me know if the `Type.Unsafe()` example above helps upgrade you to 0.24.x :)
Cheers
S

**Comment by marklai1998** [comment]
@sinclairzx81 I'm getting TS error with `Type.Unsafe()`

My code:
```ts
export const b = <T extends TSelf>(recursivePart: T) => {
  const typeCastedRecursivePart = Type.Unsafe<ResursivePart>(recursivePart) // force casting it back to ResursivePart
  return Type.Object({
    nestedField: Type.Array(typeCastedRecursivePart),
  })
}
export type B = Static<ReturnType<typeof b>>

export const recursivePart = Type.Recursive(
  self => Type.Union([b(self)]),
  {
    $id: 'formBlock',
  }
)
export type ResursivePart = Static<typeof recursivePart>
```

Error:
```
'b' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions. ts(7023)
```

**Comment by sinclairzx81** [comment]
@marklai1998 See below

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsriQBYYgFwC+cAZlBCHAOQACAzsADsSAGwLAoAehjoMAIwgAPTgFgAUGowLIsONMxwAggB5kcTTAwCAJrxSUadAHxwAvHkLESRgEoYYAVygBNEwjPQwIZjgCE0c4jS1oeBIIAV54ejcTMwULa1sKaloCRwAKKAwSQP4ANwwABQJYAC4UAEpXZwQ1ODgKgKCUGQA6AHlZACtKmFLu1V7egQx0jCsAMWAMYStWkIxhgygoAlRyyurgOsbYNqwexja1BjUE7XhwuAAhOGzzSxs7EUnK53ERSD4-IFgjIwjJInBZLF4qpNG84Ck0vBZCDfrl-gV7MUyhUqlBag0mjBdh0XF17v0oUNMGNJtNZvdFssLOtNttdiNDsdTiSLldKbd7gxHqpnuoUYkdB9fLxRRSdG58GCvOF4SKyZc1TBHK8kujUuk+ud9WL1Uz9r5SeTSrwtlFaXbhgBVATAVKlADacA50Wdrol8wWslDwmY4YAurdEHAACTAHZcZjQECfYQQEgAa04DxeqgkEjgAFoq9Wa7W6-WG42m821GW8ECCK3y82e72+-2KyWMbwIMJ9rmAOZnR0G64waXD0fjiBTgjT1VztoL81L4aT0pRvXkzfSruVgcXy99s8ASQEzAwFSEGDPV7f77rJeY-iExFSui5B051KGoCGEfwMFaZUN3FRBg2DUDwP2JYVh5LYrDgNsYCoYBbAAd2gfNeCeL8fxIP8BAA9IDBAsCINaYwdSiI9Z0pRwOjmBYgwjXpEIg4YUO5DZ0Mw8tsNwuACKgIiSLlb9f19SiLHST5aKQ1pPlhTBdStY82I4+CeLgPjkK5VZhO2UTdBw-DCOImU1CAA)

```typescript
import { Type, Static, TSchema } from '@sinclair/typebox'

export type A<T extends TSchema> = Static<ReturnType<typeof a<T>>>
export const a = <T extends TSchema>(recursivePart: T) => {
  return Type.Object({
    nestedField: Type.Array(recursivePart),
  })
}

export type B <T extends TSchema> = Static<ReturnType<typeof b<T>>>
export const b = <T extends TSchema>(recursivePart: T) => {
  return Type.Object({
    nestedField: Type.Array(recursivePart),
  })
}

export type ResursivePart = Static<typeof recursivePart>
export const recursivePart = Type.Recursive(self => Type.Union([ 
    a(self),
    b(self),
]), { $id: 'formBlock' })

// ------------------------------------------------------------------
// Schema
// ------------------------------------------------------------------

console.log(recursivePart)
console.log(a(recursivePart)) // Alternatively a(Type.Ref(recursivePart))
console.log(b(recursivePart))

// ------------------------------------------------------------------
// Inference
// ------------------------------------------------------------------

function testRecPart(value: ResursivePart) {
    
    value.nestedField // this works
}

function testA(value: A<typeof recursivePart>) {
    
    value.nestedField // this works
}

function testB(value: B<typeof recursivePart>) {
    
    value.nestedField // this works
}

```

**Comment by sinclairzx81** [comment]
@marklai1998 Hi, Going to close this issue as TypeBox recursive types should be working to spec. Note that there are technical constraints in TypeScript to consider when creating recursive types, and TypeBox can't really shield you from those currently. However as mentioned, there is ongoing research being done to make recursive types a bit more intuitive to use (and possibly enable mutually recursive inference when TS permits this), but for now, there isn't much that can be done to ease complexities at this time. 

See `Type.Rec()` / `TAny` backport using `Type.Unsafe()` if you need to continue using the old schema representation / setup. 

Will close this issue for now.
Cheers
S
