### ISSUE TITLE
Commits and Changelog

### ISSUE THREAD

**Issue by jsbrain** [sinclairzx81/typebox#255]
I noticed the changelog is basically stale and commit messages don't contain helpful messages.

It's hard to keep track on updates like that and for a library with over 8 million downloads per week providing proper commit messages and keeping the changelog up-to-date should be a priority in my opinion.

Is there a particular reason for this or anything you might need assistance?

Leveraging build tools like [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/) and [husky](https://github.com/typicode/husky) might be right way moving forward 🤓

**Comment by sinclairzx81** [comment]
@jsbrain Hello.

Refer to https://github.com/sinclairzx81/typebox/blob/master/changelog.md for an update of all the latest functionality that has been rolling through for the `0.24.x` release. I had been meaning to summarize these updates, so have updated this evening with associated PR's included.

> It's hard to keep track on updates like that and for a library with over 8 million downloads per week providing proper commit messages and keeping the changelog up-to-date should be a priority in my opinion....Is there a particular reason for this or anything you might need assistance?

Many of these updates that have been rolling through pertain to some fairly significant enhancements to the library over the past few months (with `Next` commits essentially a constant / fairly sweeping drive to stabilize all this new functionality in preparation for the next significant release). Given I'm the primary developer implementing these updates and pushing things through, I don't feel there is any huge need to be particularly descriptive on the commit messages (preferencing descriptive PR overviews instead if warranted). As such, I've have left very descriptive comments left on each PR that has lead up to the current version (linked in changelog). However, I expect this situation to change once the next release is ready to begin (which is relatively soon), and commit messages will resume to normal.

Apologies if this has caused some confusion in the interim, appreciate the `Next` commits are probably not ideal, and may wind up eventually being squashed in future.

> Leveraging build tools like [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/) and [husky](https://github.com/typicode/husky) might be right way moving forward

I may actually seek to adopt some of the conventions in [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/) moving forward, but probably not at this time. Not very keen on husky though.

Cheers
S

**Comment by jsbrain** [comment]
Thanks for the quick response and the clarification!

And don't get me wrong, I know the drill. I work on most of my projects alone and one could argue there's no need to be particular descriptive but actually even after going through my own code after some time has passed I realize without proper commit messages one can get lost very quickly. So at one point I started enforced conventional-commits via husky and now it's just become a habit and I actually don't need to enforce anything anymore.

And in case there has already been a lot of description anywhere else (Issue, PR) I usually simply just link to that, e.g. `fix: #123`. So anyone checking the commit immediately get's the information required.

But I think there are many good ways to do it.

Thanks again for the quick response and the updated changelog, my confusion is gone 😃 

Keep it up!
