### ISSUE TITLE
Option to fail validation if payload contains properties not in schema

### ISSUE THREAD

**Issue by rasmusrim** [sinclairzx81/typebox#256]
I would like Typebox to fail validation if the payload contains a property which is not defined in the schema.

Schema:
`Type.Object({ firstName: Type.String()});`

JSON:
`{ "firstName": "Brad", "lastName": "Pitt" }`

Should fail because lastName is not defined in schema.

Would it be possible to add an option to do that really strict validation? It would help us find properties passed from the backend which are not really necessary.

Or is that maybe already possible in some way?

Thank you for making such a great library!

**Comment by sinclairzx81** [comment]
@rasmusrim Hi. You can use `additionalProperties: false` on the `Type.Object({ ... })` type.

```typescript
const T = Type.Object({
  firstName: Type.String()
}, { additionalProperties: false })
```

Information on this property can be found here http://json-schema.org/understanding-json-schema/reference/object.html#additional-properties

Hope this helps!
S

**Comment by rasmusrim** [comment]
Perfect. Thank you so much!

**Comment by sinclairzx81** [comment]
@rasmusrim No problem :) Will close off this issue.
