### ISSUE TITLE
Got typescript error when using with recently released TS 3.9 and fast-json-stringify

### ISSUE THREAD

**Issue by apyrkh** [sinclairzx81/typebox#26]
TS 3.9 and `fast-json-stringify^2.0.0`

```typescript
import { Type } from '@sinclair/typebox';
import fastJson from 'fast-json-stringify';

enum Enum {
  A = 'A',
  B = 'B',
  C = 'C',
}
const schema = Type.Object({
  param1: Type.String(),
  enum: Type.Enum(Enum, { type: 'string' }),
});

const stringify = fastJson(schema);  // <=== this string doesn't pass ts type validation
stringify({});
```

Workaround:
```typescript
const schema = Type.Object({
  param1: Type.String(),
  enum: {
    enum: Object.values(Enum),
    type: 'string',
  },
});
```

**Comment by sinclairzx81** [comment]
@apyrkh

Apologies for the delay. Are you able to get in touch with the `fast-json-stringify` guys and get their thoughts on making the `enum` type property optional to support varying types?

TypeBox currently allows for varying enum types 'string' and 'number' as TypeScript enum syntax allows for it. As such it omits the `type` property based on the example provided at this link...

https://cswr.github.io/JsonSchema/spec/generic_keywords/#enumerated-values

> The enum keyword also allows us have different types in the list of allowed values. Consider the schema:

```json
{
 "enum": ["Two", 2, true, null]
}
```
```typescript
// allowed in TypeScript
enum Example {
  A = 'Two',
  B = 2,
}
```
Feel free to link back to this issue. There are technicalities around appropriately inferring the correct type, and how to properly deal with varying enum values in TypeBox. But am interested to see what the 'fast-json-stringify' come back with on this.

**Comment by fox1t** [comment]
Hi. Since that issue I decided to drop the use of enum in favor of:
`enum: Type.Union([Type.Literal('A'), Type.Literal('B')])`
Both, serialization and TS types checks works as expected. The generated JSONSchema, on the other hand, differs from enum, but the check is almost the same.

**Comment by sinclairzx81** [comment]
Hi @fox1t, Thanks for getting back. Glad you found a good work around. :)

Not too sure what can be done for the enum case if TypeBox is to allow both `string` and `number` enum types. Given that the `type` appears to be optional for `enum`, I'm tempted to close off this issue.

Will leave open for a week or so in-case someone wants to weight in with thoughts or rationales. 

Thanks Again
S
