### ISSUE TITLE
Feature Request: Improved Diff/Patch array support via LCS

### ISSUE THREAD

**Issue by smiley-uriux** [sinclairzx81/typebox#272]
I was really excited to see the Value Diff/Patch stuff land and thought I'd be able to utilize it for a basic collaborative editing feature I'm working on. Only issue is that the array diff support is a little too naive and treats inserting elements into the middle of arrays as a series of updates followed by a single insert at the end. This makes it pretty much unusable for the collaborative update use case whenever arrays are involved. Ideally it could leverage a basic LCS (longest common subsequence) algorithm to help capture that sort of change without producing an update patch per element following the insert index. Even if it only handled arrays of primitive elements it would open the door for many new use cases.

I realize that this library was never meant to be a replacement for a fully featured json diff library, but with a little smarter array handling, it would have supported my use case without bringing in another dependency. Cheers!

**Comment by smiley-uriux** [comment]
Upon reflection, I think the implementation would be non-trivial and out of scope for this library.

**Comment by sinclairzx81** [comment]
@smiley-uriux Hi. Thanks for the suggestion. This is actually something id like to look at in future revisions and would be in scope for TypeBox. 

Currently the edit operations are limited to only to `insert`, `update` and `delete` for simplicity (and general diff / patch correctness), but as you've seen, are not granular enough to support efficient mid array edits. Implementing LCS in some form would be ideal, but would likely need a new set of operations to handle more efficient handling of arrays....

Originally, I had intended to implement https://jsonpatch.com/ for the edit operations which would support inserting data mid array. However the complexities of generating these edits proved quite challenging (and I actually needed a working solution in the short term so opted for the current set of operations). 

The design of `Value.Diff()` and `Value.Patch()` does treat the `Edit` type as an opaque data structure that can be changed to anything, so supporting jsonpatch in future would be feasible. The key will be efficiently generating edits as fast as possible so the Diff / Patch could be used in real time protocols. Note these functions were written for collaborative editing as well as games, so finding ways to quickly check nested `[{ ... }, { ... }, { ... }]` for value equality (as well as handling nested array element updates) would be super important.

Happy to discuss more if you have some ideas. Currently I don't think there exists a standard way of producing fast efficient edits for JavaScript Object and Array data, so establishing a algorithm for handling this might require some research. I agree it would be massively useful for many use cases, from simple `HTTP PATCH` to Operational Transforms (OT) for hierarchical data structures. 

Thanks again for the suggestion!
S

**Comment by sinclairzx81** [comment]
Just linking https://github.com/sinclairzx81/sidewinder/blob/master/libs/value/hash.ts#L29-L161 which is a candidate defacto fnv1a64 hashing function being considered for the `Value.*` API.

For deep comparisons of two object arrays, this hash function may potentially be fast enough to compute two `bigint[]` left and right sequences, then deriving LCS on the these sequences (rather than trying to base the algorithm on deep equality checks)

```typescript
const L = [{...}, {...}, {...}, {...}]
const R = [{...}, {...}, {...}, {...}, {...}]

const LH = L.map(V => Value.Hash(V)) // [44, 22, 123, 222, 111]
const RH = R.map(V => Value.Hash(V)) // [44, 22, 100, 123, 222, 111]
                                     //          ^ insert(2)

```
For consideration
