### ISSUE TITLE
Intersecting Unions does not work 0.25.5

### ISSUE THREAD

**Issue by Zajozor** [sinclairzx81/typebox#276]
This is a re-opening of #201 
There you mention that this should be solved from 0.25.0, unfortunately the code
```
Type.Intersect([
    Type.Object({ password: Type.String() }),
    Type.Union([
      Type.Object({ username: Type.String() }),
      Type.Object({ email: Type.String() }),
    ]),
  ]);
```

still fails with `Type 'TUnion<[TObject<{ username: TString<string>; }>, TObject<{ email: TString<string>; }>]>' is missing the following properties from type 'TObject<TProperties>': type, properties`

The solution proposed in #201 (to rewrite it in a way where we don't intersect unions) does not really work for us.

You also provided a snippet in #201:
```
// --------------------------------------------------------------------------------------
// TIntersectAllOf<T> (unevaluatedProperties requires draft 2019-09)
// --------------------------------------------------------------------------------------

export type IntersectSchemaArray<T extends TSchema[]> = IntersectReduce<
  unknown,
  IntersectEvaluate<T, []>
>

export type TIntersectAllOf<T extends TSchema[]> = ReturnType<
  typeof IntersectAllOf<T>
>

export interface IntersectAllOfOptions extends SchemaOptions {
  unevaluatedProperties?: boolean
}

export const IntersectAllOf = <T extends TSchema[]>(
  allOf: [...T],
  options: IntersectAllOfOptions = {}
) =>
  Type.Unsafe<IntersectSchemaArray<T>>({
    ...options,
    [Kind]: 'IntersectAllOf',
    allOf,
  })
```

Is there any downside to using this `IntersectAllOf` ? Can you help me understand the risks involved in using the "Type.Unsafe" part :) ?
Is there any plan to include this `IntersectAllOf` the library ?

thanks for making Typebox, it's amazing :) !

**Comment by sinclairzx81** [comment]
@Zajozor Hi, and thanks :)

Yeah, this is a known limitation that was introduced in the `0.24.0` release to solve some compositional issues related to using intersections with utility types like `Partial`, `Required`, `Pick` and `Omit`. In `0.24.0`, the ability was added to allow intersected types to be passed to utility types (a very useful feature), but came at the cost of losing the ability to intersect unions (a less used feature). The `0.24.0` opted for the more useful to allow time to properly investigate solving the union intersection issue (which has been a long standing challenge to get right in the library)

There are quite a few technical reasons why intersected unions are a challenge, with the most recent information on the issue found https://github.com/sinclairzx81/typebox/issues/187#issuecomment-1295393810. Unfortunately, I don't envision this functionality being resolved before the end of the year (but is very much a high priority for the library, so will be looked at again when I get some time to sit down with some of the complexities)

#### Type.Unsafe

`Type.Unsafe()` is an API to that allows you to define a custom schemas with custom inference rules. The name `unsafe` was chosen to highlight that "TypeBox cannot make assurances that the schema and inference type match" and that "users are responsible for ensuring the schema and static type line up correctly". Also the name "unsafe" was selected to draw analogs to languages like C# an Rust that use the keyword to provide an escape hatch in cases where you need to do something specific outside the usual rules of the language.

Type.Unsafe is actually safe to use. The main downsides are that Unsafe types cannot be used with TypeBox's TypeCompiler and Value API's (so you will need to use Ajv for your validation)

#### IntersectAllOf 

The `IntersectAllOf` type is actually the pre-0.24.0 version of `Type.Intersect()` and is provided as a fallback (as this was a breaking change in the 0.24.0 release). It should be ok to use so long as you're using Ajv to validate your data. 

When the Intersected Union issue does get resolved, the resolved schemas will match that of `IntersectAllOf` so you should be able to swap things over to the `Type.Intersect()` when things are ready.

Hope this help!

**Comment by Zajozor** [comment]
@sinclairzx81 Thank you so much for the explanation! I realised I never got back to you, but we did end up using IntersectAllOf for now.

I really appreciate your complete, elaborate, quick and understandable answer :) 🙏🏻 

I believe there is no open issue to track re-introducing Intersecting Unions, but I'll leave it to you whether you want to keep this open or not.

Thanks!

**Comment by sinclairzx81** [comment]
@Zajozor Hey, thanks for the follow up! :) I'm glad to hear `IntersectAllOf` was a workable solution in the interim.

Yeah, I might close off this issue for now (as it was a documented breaking change in `0.24.x`) and look at setting up a new issue that formally documents this limitation and provides the `IntersectAllOf` workaround. Ill see about setting this up sometime next week when I get a bit of free time over the holiday break.

All the best!
S
