### ISSUE TITLE
How to remove additional properties with cast but allow in check

### ISSUE THREAD

**Issue by F43nd1r** [sinclairzx81/typebox#278]
Hi, we're facing the problem where we want to accept unknown properties in our input but then remove them.
E.g.
```typescript
        const T = Type.Object({
            foo: Type.String(),
        })
        const obj = { foo: "bar", bar: "foo" }
        if (!Value.Check(T, obj)) throw Error()
        console.log(Value.Cast(T, obj))
```
We have a `Type` as shown (deeper nested than in this example, could contain arrays of objects etc.)
We want to allow any unknown properties during `Check`, but then remove them during `Cast`. Is it possible to configure this somehow?

I'm aware of `additionalProperties = false`, but this would reject any input with unknown properties as well.

**Comment by sinclairzx81** [comment]
@F43nd1r Hi, You can try the following which should remove the additional properties and retain the static type of `R`.

```typescript
const T = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
})

const R = Value.Cast({ ...T, additionalProperties: false }, { x: 1, y: 2, z: 3, w: 1 })

// const R = { x: 1, y: 2, z: 3 }
```

**Comment by sinclairzx81** [comment]
This may handle the array case.

```typescript
function RemoveAdditionalProperties<T extends TObject>(object: T): T {
  return {
    ...object,
    additionalProperties: false,
    properties: Object.keys(object.properties).reduce((properties, key) => {
      const schema = object.properties[key]
      if (TypeGuard.TObject(schema)) {
        return { ...properties, [key]: RemoveAdditionalProperties(schema) }
      } else if (TypeGuard.TArray(schema) && TypeGuard.TObject(schema.items)) {
        return { ...properties, [key]: { ...schema, items: RemoveAdditionalProperties(schema.items) } }
      } else {
        return { ...properties, [key]: schema }
      }
    }, {})
  }
}

const T = Type.Object({
  x: Type.Object({
    x: Type.Number(),
    y: Type.Number(),
  }),
  y: Type.Object({
    x: Type.Number(),
    y: Type.Number(),
  }),
  a: Type.Array(Type.Object({
    x: Type.Number(),
    y: Type.Number(),
  }))
})

const R = Value.Cast(RemoveAdditionalProperties(T), {
  x: { x: 1, y: 2, z: 3 },
  y: { x: 1, y: 2, z: 3 },
  z: { x: 1, y: 2, z: 3 },
  a: [{ x: 1, y: 2, z: 3 }, { x: 1, y: 2, z: 3 }]
})
console.log(R)

// const R = {
//  x: { x: 1, y: 2 },
//  y: { x: 1, y: 2 },
//  a: [ { x: 1, y: 2 }, { x: 1, y: 2 } ]
// }
```

**Comment by F43nd1r** [comment]
Thanks, we forgot nested objects in our implementation. Here's the cleaned up version:
```typescript
const noAdditionalProperties = <T extends TSchema>(schema: T): T => {
    if (TypeGuard.TArray(schema)) {
        return { ...schema, items: noAdditionalProperties(schema.items) }
    }
    if (TypeGuard.TObject(schema)) {
        return {
            ...schema,
            additionalProperties: false,
            properties: Object.fromEntries(Object.entries(schema.properties).map(([key, value]) => [key, noAdditionalProperties(value)])),
        }
    }
    return schema
}
```
Should be equivalent to yours as far as I can tell.

**Comment by AaronPorts** [comment]
Can I use a similar approach for TIntersect? Next code cast error: _Intersect produced invalid value. Consider using a default value._
```` typescript
if (TypeGuard.TIntersect(schema)) {
    return {
      ...schema,
      allOf: schema.allOf.map((item) => noAdditionalProps(item)),
    };
  }
````

**Comment by sinclairzx81** [comment]
@AaronPorts Hi :)

You can use similar techniques to update all TB schemas, so remapping each `allOf` via `noAdditionalProps` should work ok.

Just note that the error `Intersect produced invalid value. Consider using a default value.` usually occurs when you call functions like `Value.Create()` and `Value.Cast()` with an illogical schema; where an illogical schema is one that will never pass validation, for example.

```typescript
const T = Type.Intersect([Type.String(), Type.Number()]) // string & number is illogical
//  ^ can't be both string and number simultaneously
```
Intersections are quite notorious for this. Consider the following illogical schema T. The additionalProperties constraint makes it illogical as T can't be both `{ x: number }` and `{ y: number }` simultaneously. 

```typescript
const T = Type.Intersect([
   Type.Object({ x: Type.Number() }, { additionalProperties: false }), // expect exactly { x: number }
   Type.Object({ y: Type.Number() }, { additionalProperties: false }), // expect exactly { y: number }
])
```
JSON Schema recommends only constraining (or making a schema closed) as a last step. However using the `noAdditionalProperties` to remap would be ok, but would recommend wrapping this in a function like the following.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUHkBGAVhgMYw7ICSAdjBlAM6nwC+cAZlBCHAOQACDYNRIAbAIbAoAehjoM+CAA9eAWABQoSLERwAauNEBXDHDadufQcLGSZczIqXSAboZNr1G6dLhQM1OIgpuIkJNAAJsIA5qKoGuxGIjDAENRwALLiYJgRNHSMzAA8yHAYSnTUEQx4RMwA2gC6AHwAFAwkABYYIOIMAFxw9QB0o8iNAJSDVLT0TGQlzYgacKt+GDBGUOlomMP5c8ztXT19w71gx929cAC8Swgra8-h1AzwSOIRUSlphgAKXEwsGAGAYOFGw387zMdzgHWu4iez1W-k223WML6tWIZGRZgmcGxIzGkw0LA0GleMNKt0y2VyB0KZFa9XxuwwwwIuJgrSQSmm8mGADkjCB8PRWoSWDhPt9gL9AqJARBgSkwYN2IYmASsOyhdyjkhUIK9qLxZLpbKifLFQCgfR1QMONrTCwJhoyV51NSIKJOaIINFWgZjJyAML+cR0VrICaEny6AVwAAMOBNqbMQA)

```typescript
import { Type, TObject, TIntersect } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// rename accordingly
function MappedIntersect<T extends TObject[]>(schemas: [...T]): TIntersect<T> {
    return Type.Intersect(schemas.map(schema => {
        const { additionalProperties, ...rest } = schema
        return rest as TObject
    }) as [...T])
}

const T = MappedIntersect([
    Type.Object({ x: Type.Number() }, { additionalProperties: false }),
    Type.Object({ y: Type.Number() }, { additionalProperties: false })
])

console.log(Value.Create(T)) // { x: 0, y: 0 } - works!
```
Hope this helps!
S
