### ISSUE TITLE
'modifierSymbol' breaks type inferrance

### ISSUE THREAD

**Issue by peternedap** [sinclairzx81/typebox#28]
When upgrading typebox from 0.9 to 0.10 I get the following error when using `Type.Optional`:

`Exported variable has or is using name 'modifierSymbol' from external module ".../node_modules/@sinclair/typebox/typebox" but cannot be named`, e.g. when defining 

```
export const optionalStringType = Type.Optional(Type.String());
```

Usually the suggested fix is to define the type, but the whole reason I use typebox is that it can infer types.

**Comment by sinclairzx81** [comment]
Hi, TypeBox uses the `modifierSymbol` as a key to augment the type with readonly or optional (which are used in object inference). 

Are you able to produce a repro of the issue? Given its a `Symbol` it shouldn't be possible to redefine (which would make the issue unresolvable), so curious how its happening. The `modifierSymbol` is exported on TypeBox though, but I can't imagine a situation where you would need to import it for the purposes of inference.

**Comment by peternedap** [comment]
Yes, I've created one [here](https://github.com/peternedap/typebox-example)

**Comment by sinclairzx81** [comment]
Cool, thanks. I have published an update that should resolve your repro. Version is 0.10.1. (reminder that you will need to install the `@types/node` dev dependency for it to build)

@geekflyer Just chiming you in on this one. The issue is related to exporting key symbols from TypeBox. Have reverted to using the Symbol unions (as we previously discussed) to resolve this particular issue. Wondering if there is a workaround to allow Symbol keys to be exported in this fashion. Open to your thoughts on this one.

**Comment by peternedap** [comment]
Thanks for the quick fix. Seems to work correctly now.

**Comment by peternedap** [comment]
I was a bit too quick. It seems that the fix breaks `Type.Optional`, such that the type obtained via `Static` does not allow `undefined` as a valid value. I've updated my example repo to include this.

**Comment by sinclairzx81** [comment]
@peternedap Heya, That's actually not an issue. `Readonly` and `Optional` modifiers only work in the context of a `Type.Object()`. For example...
```typescript
// the following type
const x = Type.Optional(Type.String())

// loosely translates as...
const x?: string = '' // invalid syntax
```
When `Optional` and `Readonly` are used outside a `Type.Object()`, TypeBox will ignore the `Optional` and just resolve to the `string`. The closest JSON schema compatible representation would be something like...

```typescript
// use a union
const T = Type.Union([Type.String(), Type.Null()])

 // X -> string | null
type X = Static<typeof T>
```
