### ISSUE TITLE
how to default Type.Number to null 

### ISSUE THREAD

**Issue by aircraftpromax** [sinclairzx81/typebox#29]
example 
jobTitleId: Type.Optional(Type.Number())

when request body is
{
  "industryGroupId": null
}
how can i defualt jobTitleId to null now it is 0

**Comment by wtospit** [comment]
This issue will be fixed by this PR #30 
Please consider

**Comment by aircraftpromax** [comment]
> This issue will be fixed by this PR #30
> Please consider

thank @wtospit

**Comment by sinclairzx81** [comment]
@aircraftpromax Hi, `null` is treated as a kind of value in TypeBox inline with the JSON schema representation [here](https://json-schema.org/understanding-json-schema/reference/null.html). There is a subtle difference between making a nullable, and making a property optional, consider the following.

### current
```typescript
const T = Type.Object({
   jobTitleId: Type.Optional(Type.String())
})
// translates to
type T = {
   jobTitleId?: string // string | undefined
}
```
### recommendation
```typescript
const T = Type.Object({
   jobTitleId: Type.Union([Type.Null(), Type.String()])
})
// translate to
type T = {
    jobTitleId: null | string
}
```
Can you try the second example and see if it fits your use case? Note, you can also use `Type.Optional(Type.Union([Type.Null(), Type.String()]))` if you need `string | null | undefined` as possible values.

**Comment by aircraftpromax** [comment]
Hi @sinclairzx81 sinclairzx81 
> that mean if i need ``` number  | null ```
my configuration should be like this right ?
> ```ts
> const T = Type.Object({
 >    jobTitleId: Type.Union([Type.Null(), Type.Number()])
> })
>// translate to
> type T = {
  >   jobTitleId: null | number
> }

**Comment by sinclairzx81** [comment]
@aircraftpromax Hi, yes, that looks correct to me if you expect a `null` or a `number`, if you expect `undefined` also, you drop in a Optional as follows.

```typescript
const T = Type.Object({
   jobTitleId: Type.Optional(Type.Union([Type.Null(), Type.Number()]))
})
// translates to
type T = {
  jobTitleId?: null | number // undefined | null | number
}
```

**Comment by sinclairzx81** [comment]
Will close off this issue. Please feel free to reopen if you run into any problems with the `Type.Union(..)` implementation. Cheers

**Comment by erfanium** [comment]
@sinclairzx81 
```ts
Type.Union([Type.Null(), Type.Number()])
```

will generate this json schema:
```json
"anyOf": [
  {
    "type": "string"
  },
  {
    "type": "null"
  }
]
```

but ajv documentation suggest another schema for nullable values:
https://ajv.js.org/json-schema.html#type



```json
{
  "type": "string",
  "nullable": true
}
```

and
```json
{
  "type": ["string", "null"]
}
```
