### ISSUE TITLE
Check uuid string

### ISSUE THREAD

**Issue by truemoroz** [sinclairzx81/typebox#293]
```js
Value.Check(Type.String(), '5ab8221a-8814-456c-b62b-060b63a149fb')  // true

Value.Check(Type.String({ format: 'uuid' }), '5ab8221a-8814-456c-b62b-060b63a149fb') // false
```
How to check if string is uuid?

**Comment by sinclairzx81** [comment]
@truemoroz Hi!

The TypeBox `Value` and `TypeCompiler` modules do not implement any built in string formats by default, but you can define them via the [Formats](https://github.com/sinclairzx81/typebox#typecheck-custom-formats) module. Once defined, they become available to both `Value` and `TypeCompiler` modules.

I've just added an quick example [here](https://github.com/sinclairzx81/typebox/blob/master/example/formats/additional.ts) that configures TypeBox for a number of formats defined in the [ajv-formats](https://www.npmjs.com/package/ajv-formats) package. You will need to replicate this in your project and just ensure the `AdditionalFormats.Configure()` method is called before any type checking.

### Example

```typescript
import { Type } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'
import { AdditionalFormats } from './formats/index'

AdditionalFormats.Configure() // configures uuid and other formats

const T = Type.Object({ id: Type.String({ format: 'uuid' }) })

const R1 = Value.Check({ id: '62bbbdfa-9059-439f-8b4f-260d2f03b764' }) // const R1 = true

const R2 = Value.Check({ id: 'invalid' })                              // const R2 = false
```

Hope this helps
S

**Comment by sinclairzx81** [comment]
Will close off this issue for now. Note, TypeBox may implement the standard formats in subsequent revisions (for all formats listed under the `format` string union), but for now, custom formats are intended to be opt in for the compiler and value modules.

Happy to field any follow up questions getting setup with these formats. 
All the best!
S
