### ISSUE TITLE
Type.Array() fails on single array item

### ISSUE THREAD

**Issue by vaneatka** [sinclairzx81/typebox#296]
I have this kind of validation schema

someProperty  = Type.Union([
  Type.Null(),
  Type.Array(
    Type.Object(SomeObjectType)
  ),
])

when I send more than one array items in that object it works fine, Null also works ok.

But when you send only one array Item it fails the validation with the message "someProperty must be null, someProperty  must be array, someProperty  must match a schema in anyOf"

    "fastify": "^4.5.3",
    "@fastify/type-provider-typebox": "^2.3.0",
    "@sinclair/typebox": "^0.24.30",

**Comment by sinclairzx81** [comment]
@vaneatka Hi! Try the following

Instead of
```typescript
const someProperty = Type.Union([
  Type.Null(),
  Type.Array(
    Type.Object(SomeObjectType)
  ),
])
```
Try unwrapping `SomeObjectType`
```typescript
const someProperty = Type.Union([
  Type.Null(),
  Type.Array(SomeObjectType),
])
```
In TypeBox, wrapping an object in another object `Type.Object(Type.Object())` will an invalid. I may consider putting a catch for this in later versions.

Let me know if that helps
S

**Comment by vaneatka** [comment]
@sinclairzx81 the exact code is 
`
Type.Union([
  Type.Null(),
  Type.Array(
    Type.Object({
      id: Type.Number(),
      wid: Type.Number(),
      zid: Type.String(),
      lid: Type.String(),
      cid: Type.String(),
      hid: Type.String(),
    })
  ),
]);
`

if this is how your proposal says, then it does not work

**Comment by vaneatka** [comment]
@sinclairzx81 thanks for that, I can only presume that the problem is somewhere in other package if it works with Ajv.

this is the provider setup
so I can blame only the provider or fastify :)

import fastify from 'fastify';
import type { TypeBoxTypeProvider } from '@fastify/type-provider-typebox';

const server = fastify({
  logger: true,
}).withTypeProvider<TypeBoxTypeProvider>();

export default server;

**Comment by sinclairzx81** [comment]
@vaneatka All good :) Note, the provider project "should" be ok as the call to `withTypeProvider()` is basically an empty function that only sets up Fastify for type inference (code [here](https://github.com/fastify/fastify/blob/main/fastify.js#L561-L563)). If you're chasing down the issue, would probably keep an eye on how the type is used with Fastify request types.

Will close off this issue for now, but feel free to link back to this issue for reference if you want to submit an issue downstream.

All the best!
S
