### ISSUE TITLE
suggestion: create github release along with new tags

### ISSUE THREAD

**Issue by boywithkeyboard** [sinclairzx81/typebox#299]
you should add a simple workflow to create a github release once you publish a new version, so we can easily see all the changes :)

if you agree, i could create a pr for this.

**Comment by sinclairzx81** [comment]
@unvented Hi! Apologies for the delay in reply (have just returned from a break over the holidays)

Thanks for the offer to set this up. I like the idea of setting TypeBox up with GH releases, but probably only once the library reaches a 1.0 state (as there is still a bit of churn going on for some of the libraries internals). For now, I am opting to manually tag each minor / revision [here](https://github.com/sinclairzx81/typebox/tags) and keep the changelog updated [here](https://github.com/sinclairzx81/typebox/blob/master/changelog.md) with anything significant added to the library. Also I am tracking via PR's so there's good descriptive notes on what's been added / changed.

There are some plans to give TypeBox a fairly significant overhaul this year (mostly focusing on enabling a programmable compiler for custom types that can be JIT compiled) as well as quite a few enhancements to the type composition API. I think once this is carried out, TypeBox will be in a good position to go 1.0, and would like to consider GH releases from that point on.

Would you be interested in submitting the PR at a later date once TypeBox reaches 1.0?
Many Thanks!
S

**Comment by unvented** [comment]
@sinclairzx81 yeah, fine for me. Let's just keep this issue open for now!

**Comment by joshmeads** [comment]
Hey @sinclairzx81 just letting you know the [changelog](https://github.com/sinclairzx81/typebox/blob/master/changelog.md?rgh-link-date=2023-01-02T08%3A14%3A13Z) did a disappearing act with the 0.26.x releases.

Thanks! 👍🏻

**Comment by joshmeads** [comment]
New [changelog location](https://github.com/sinclairzx81/typebox/tree/master/changelog) as of `0.26.x` for anyone referencing this issue. 👍🏻

**Comment by sinclairzx81** [comment]
@boywithkeyboard Hey, might close this issue off for the time being. I do actually intend to explore GH releases once TB reaches 1.0, but as there is still quite a bit of churn in these pre-1.0 revisions, adding GH releases now would result in quite a bit of unnecessary noise as internals to the codebase continue to evolve (with new revisions published)

Just for a heads up, I am aiming for an official 1.0 later on this year (sometime late 4th quarter), and will likely put together a list of things I could use community help with at that time. In the interim, the current tagged revisions located at the link below should provide enough revision history. 

https://github.com/sinclairzx81/typebox/tags

Thanks again for the offer take a look at this, will be interested in resuming this at a later time.
Cheers
S
