### ISSUE TITLE
documentation: comparison with other validation solutions

### ISSUE THREAD

**Issue by mcgaw** [sinclairzx81/typebox#301]
Hi. I'm investigating libraries to do form validation in a TS web app. While I'm sure this library would accomplish the task, it seems a little more complicated to use than some of the others like zod etc. (given that you have to hook it up with AJV, although I completely understand why this is the case).

Any thoughts appreciated. Thanks!

**Comment by sinclairzx81** [comment]
@mcgaw Hi. You don't necessarily need AJV to validate with TypeBox. TypeBox implements a portion of the JSON Schema specification for built in types only. Running in the browser you can use `Value` module to check the correctness of a form.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAWABQoSLERwAao3oBXLLgJFSlGg2ZsOmHr1YA3GfMFDhtCNQrwAwrMtEMUAGLRiAXhScAdAHkuAKwxaGAAKBGE4CLwWS2pGEAwALg9MTwBlGCgaAHNggEoAGnCIphi4xOSMNIzsvMKhbFzhU3NLOAAlOHdpOUqrAAtAgGtgmzt4pxd8iVZWODMLeA73DPlwqKhS+KSSABNGPQwSOrgSmFit0goQYBg+4wagA)

```typescript
import { Type } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

const CustomerForm = Type.Object({
   firstname: Type.String(),
   lastname: Type.String(),
})

const R = Value.Check(CustomerForm, { // const R = true
 firstname: 'dave',
 lastname: 'smith'
})
```
> While I'm sure this library would accomplish the task, it seems a little more complicated to use than some of the others like zod etc.

The main difference between TypeBox and Zod is TypeBox does not couple schematics with validation, so you do need to pull a separate package (be it Ajv, Value or TypeCompiler) to validate a value based on the schematics. Aside from this aspect, both libraries should be functionality equivalent.

> comparison with other validation solutions

Ah, I don't really like to compare libraries as we're all trying to achieve the same goal (runtime type safety in TypeScript) and are all more or less functionally the same. I do maintain some benchmarks however for the top performing validation libraries which you can find [here](https://sinclairzx81.github.io/runtime-type-benchmarks/), but not sure this would constitute as a documentation thing.

What did you have in mind for the documentation?

**Comment by sinclairzx81** [comment]
@mcgaw Hi, thanks for the insight.

> It might also be fair to point out that the Options section shows use of { format: 'email' }, which is not supported out-of-the-box, unless I'm mistaken. Might be worth linking to the Custom Formats section?

At this stage, the TypeCompiler and Value modules do implement many of the JSON schema options (essentially what's been typed for the options), however they don't implement the `formats` (yet). Note that Ajv tends to provide formats as an [auxiliary package](https://ajv.js.org/packages/ajv-formats.html) and TypeBox may do the same future (but currently undecided whether to include formats in this package or another).

For now, you can source the formats from the `ajv-formats` package if you need to support standard formats using Value or TypeCompiler. See link here https://github.com/ajv-validator/ajv-formats/blob/master/src/formats.ts. Alternatively, a combination of Ajv and TypeBox does work well (and was originally the intended way to use TypeBox)

> I've decided to use the library, as I found the API to be pleasant to use. I understand that you're reluctant to "sell" the project by putting library comparisons in the documentation, and that's fair. Just that it's a crowded space and would be a shame if it was getting overlooked.

Cool, hope TypeBox helps you out with runtime typing JavaScript! :)  As for the library getting overlooked, this is actually a running theme for the library :D I may make some comparisons once the library goes 1.0 (likely in a website), but for now, just trying to innovate in the runtime validation space and help to solve the problem of JavaScript not having a strong type system :)

Will close off this issue for now. 
Cheers!
S
