### ISSUE TITLE
Unknown string format 'uri'

### ISSUE THREAD

**Issue by yeongjet** [sinclairzx81/typebox#304]
'uri' is valid format option by default, but reports: `Unknown string format 'uri'`:
```ts
Type.String({ format: 'uri', ...options })
```
do I need to set it by myself? like:
```ts
Format.Set('uri', (value) => IsUri(value))
```

**Comment by sinclairzx81** [comment]
@yeongjet Hi!

Yes, that's right. TypeBox does not provide any built in string formats by default. This may change in future revisions, but for now, you must implement the format through the `Format.Set('uri', (value) => IsUri(value))` mechanism.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAWABQoSLERwAao3oBXLLgJFSlGg2ZsOmHr1YA3GfMEjw0eEgBi0EI3iLCxclTpMW7TjtZ5rt48KtQNjAAdADKGDAAFCSyUMAkADRwkQZyGACUcAC8AHxwrAB6kQD8AFwA2owAtABeALqVtQAMVQCcANQAOlXBdQBUpeklpZ2sxaPpxeUFnRT9ACSswMEwGBRRqfLp6cLCtBDU6yjZKJxhMHHUAOaRSN6BtqWksfE4mbtC+4fwAEon0mlggBhAAWGFoAGtIsgkiQwIQYBB9vRSqxWAATIjMajBfYgUoADiaABYAEysMC2EGsXSoADENRIOyEewOFAg9AwwXoEBuP0yaLgF3kQA)

```typescript
import { Type } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'
import { Format } from '@sinclair/typebox/format'

Format.Set('uri', (value) => /^(?:[a-z][a-z0-9+\-.]*:)(?:\/?\/)?[^\s]*$/i.test(value))

const T = Type.String({ format: 'uri' }) 

const R = Value.Check(T, 'protocol://domain.com:8042/path/x/y#z')

console.log(R) // true
```
It is possible to use some of the formats provided on the `ajv-formats` package [here](https://github.com/ajv-validator/ajv-formats/blob/master/src/formats.ts) if you need. TypeBox may provide a similar auxiliary package in future. 

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@yeongjet Will close this one. Built in formats may arrive in a future release, but for now, you will need to explicitly specify them.

Cheers!
S

**Comment by samuelstroschein** [comment]
@sinclairzx81 Typebox not supporting JSON schema formats out of the box is very weird.

Typebox is positioned as a JSON schema builder. Requiring manual format definitions for built-in formats is a) unexpected, b) will lead to deviating formats for buil-in formats like `uri` and c) (if formats are only valid for typebox) breaks interop.

**Comment by sinclairzx81** [comment]
@samuelstroschein Hi,

>  Requiring manual format definitions for built-in formats is a) unexpected, b) will lead to deviating formats for buil-in formats like uri, and c) (if formats are only valid for typebox) breaks interop. Defining a schema in typebox with JSONSchema unsupported formats seems to entail that the validation library can not be swapped. If the validation library can't be swapped/typebox schemas break interop, a major appeal of typebox is diminished.

I do agree about deviating formats, however as far as I know, there is not fixed set of format validators that would constitute a set in which to deviate from (I don't think the ecosystem has a central "package of truth" that implements all the formats under the specification). The closest approximation to one I have found is Ajv's [ajv-formats](https://github.com/ajv-validator/ajv-formats) package, of which I've ported some of these functions for adhoc usage in TypeBox.

https://github.com/sinclairzx81/typebox/tree/master/examples/formats

Note: I am somewhat hesitant to include these formats in the TypeBox package as they are ported directly from the `ajv-format` package for compatibility; and to enable them to be used with the `FormatRegistry` (and I don't know how to adequately give accreditation to the original developers (other than simply use MIT license notices, which I personally don't feel is adequate)) but as Ajv is so prominent, they would be the closest approximation to standard set that exists. But if you know of another implementation, I'd be interested to learn of that.

But with the above in mind, I am actually considering spending some time investigating what would be required to develop a full set of specification compliant format validators (from scratch) and potentially publishing as a separate package `@sinclair/formats`. The usage of these formats would be:

```typescript
import { IsEmail, IsUriReference } from '@sinclair/formats'
import { FormatRegistry } from '@sinclair/typebox'

FormatRegistry.Set('uri-reference', value => IsUriReference(value))
FormatRegistry.Set('email', value => IsEmail(value))
```
Here, the format validators would be usable with the FormatRegistry, or used as quick check functions (with or without TB). I've often thought such a package "should" exist, but as one doesn't currently (again, afaik), TypeBox omits all built in formats with a perspective that should such a library be built, it would be better to use that than something TypeBox implemented internally (as all validators could share from the same set). I suspect this reasoning is what lead Ajv to publish a separate `ajv-formats` package.

Certainly open to thoughts around this.

**Comment by samuelstroschein** [comment]
Thanks for the in-depth reply. 

I take away that the FormatRegistry concept is undesired for our use case, and maybe typebox itself. Using FormatRegistry will lead to interop problems. It would be interesting to know how many ppl use `FormatRegistry` and for which use cases (seems like Regex can achieve the majority of use cases).  

> Ajv is so prominent, they would be the closest approximation to standard set that exists. But if you know of another implementation set, I'd be interested to learn of that. 

Sounds like Ajv is the standard to default to. I don't know another library.

**Comment by sinclairzx81** [comment]
> I take away that the FormatRegistry concept is undesired for our use case, and maybe typebox itself. 

If you don't want to use the FormatRegistry, have you considered just using Ajv as your validator?

#### Documentation on Setting Up Ajv

https://github.com/sinclairzx81/typebox#typecheck-ajv

####  Documentation on Ajv String Formats

https://ajv.js.org/guide/formats.html#string-formats

**Comment by samuelstroschein** [comment]
> If you don't want to use the FormatRegistry, have you considered just using Ajv as your validator?

Yep. We prefer to have only one dependency (typebox). Solved our issues with Regex'es :)
