### ISSUE TITLE
feature request: generate json schema enum

### ISSUE THREAD

**Issue by trim21** [sinclairzx81/typebox#310]
I'm using typebox with fastify to generate json schema.

And I'm using some generator in my client side it support to generate ts enum from json enum with some vendor properties like x-enum-varnames

But current `Enum` is JSON schema `anyOf`, is it possible to create a new method or someway to create a json schema enum like this?

```
"typeId": {
            "description": "integer test case for #349",
            "enum": [1, 2, 3, 4, 6, 8],
            "type": "integer",
            "x-enumNames": [
              "dog",
              "cat",
              "tiger",
              "mouse",
              "house",
              "3-headed-monkey"
            ]
          }

```

https://github.com/oazapfts/oazapfts/commit/8db31c274ab7dfb492066f2b00a8fbf7c3bd395f

**Comment by sinclairzx81** [comment]
@trim21 Hi,

You can do this with `Type.Unsafe(...)` which allow you to create arbitrary schematics as well as define the type inference rule. See example below.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjriQBYYgEDyYxEAdgM5wC+cAZlBCHADkAAVbBmJADYFgUAPQx0GAEYQAHoIBQ27gFcJTZnACSzGBgDmGKAFFmukAB5kcDGvPMAJu3shl1gG0AXQA+AAoANwJJXQxWAC44AIA6VOQgnAhGYBYEvCoaemzcuABeRA4ASkRNODq4KAwYXSgjNExkgFU2Am4MZwDffyhQsKRU5KzDVhxFTETBcXMrKEEcDF9EqJi4zkrNDm0SXPgXctNl6zsHMICARhwAJhwAZhwAFhwANhwADgzEPUgbV6p44iQoMBiswFktLNY4OZWPASARWBgeNA4ABiF7vACcaxBdUEagAtBsHAA5AggOKCRIBYlAoSeCAWIks+qCVEwTlcoTEFb8rmCEAQXTokUswSUCVSrDMoGCF5k6gEMGeMni5gAawwqC0QKCB32mjmGLOeEIxBIjgtEG4KBCdTkckRShQZTgdzgAB84I9-XAXsH3sGvsHfkA)

```typescript
import { Type, Static, SchemaOptions } from '@sinclair/typebox'


function IntegerEnum<T extends number[]>(values: [...T], options: SchemaOptions = {}) {
    return Type.Unsafe<T[number]>({ ...options, type: 'integer', enum: values })
}

const T = IntegerEnum([1, 2, 3, 4, 6, 8], {       
    description: 'integer test case for #349',
    'x-enumNames': [
        'dog',
        'cat',
        'tiger',
        'mouse',
        'house',
        '3-headed-monkey'
    ]
})

type T = Static<typeof T>  // type T = 1 | 2 | 3 | 4 | 6 | 8
```

Hope this helps
S

**Comment by trim21** [comment]
> @trim21 Hi,
> 
> You can do this with `Type.Unsafe(...)` which allow you to create arbitrary schematics as well as define the type inference rule. See example below.
> 
> [TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjriQBYYgEDyYxEAdgM5wC+cAZlBCHADkAAVbBmJADYFgUAPQx0GAEYQAHoIBQ27gFcJTZnACSzGBgDmGKAFFmukAB5kcDGvPMAJu3shl1gG0AXQA+AAoANwJJXQxWAC44AIA6VOQgnAhGYBYEvCoaemzcuABeRA4ASkRNODq4KAwYXSgjNExkgFU2Am4MZwDffyhQsKRU5KzDVhxFTETBcXMrKEEcDF9EqJi4zkrNDm0SXPgXctNl6zsHMICARhwAJhwAZhwAFhwANhwADgzEPUgbV6p44iQoMBiswFktLNY4OZWPASARWBgeNA4ABiF7vACcaxBdUEagAtBsHAA5AggOKCRIBYlAoSeCAWIks+qCVEwTlcoTEFb8rmCEAQXTokUswSUCVSrDMoGCF5k6gEMGeMni5gAawwqC0QKCB32mjmGLOeEIxBIjgtEG4KBCdTkckRShQZTgdzgAB84I9-XAXsH3sGvsHfkA)
> 
> ```ts
> import { Type, Static, SchemaOptions } from '@sinclair/typebox'
> 
> 
> function IntegerEnum<T extends number[]>(values: [...T], options: SchemaOptions = {}) {
>     return Type.Unsafe<T[number]>({ ...options, type: 'integer', enum: values })
> }
> 
> const T = IntegerEnum([1, 2, 3, 4, 6, 8], {       
>     description: 'integer test case for #349',
>     'x-enumNames': [
>         'dog',
>         'cat',
>         'tiger',
>         'mouse',
>         'house',
>         '3-headed-monkey'
>     ]
> })
> 
> type T = Static<typeof T>  // type T = 1 | 2 | 3 | 4 | 6 | 8
> ```
> 
> Hope this helps S

yes， thanks
