### ISSUE TITLE
Feature request: Discriminated unions

### ISSUE THREAD

**Issue by MollariDev** [sinclairzx81/typebox#313]
[AJV Discriminator](https://ajv.js.org/json-schema.html#discriminator) - granted its behind a flag but allows for much clearer error messages over anyOf and better performance. I attempted this myself but the types are not working perfectly as I am unable to use Strict to get the base types. My typescript skills are lacking unfortunately.

```ts
type KeysOfType<O, T> = {
  [K in keyof O]: O[K] extends T ? K : never;
}[keyof O];

function discriminatedUnion<T extends TObject[], U extends KeysOfType<T[number]['properties'], TLiteral>>(
  discriminator: U,
  oneOf: [...T]
) {
  return Type.Unsafe<[...T]>({
    type: 'object',
    discriminator: {
      propertyName: discriminator,
    },
    required: [discriminator],
    oneOf,
  });
}
```

While the end schema works perfectly, it is the types I am struggling with. I have been testing some things using this package for the last day and really like the performance gains via AJV vs Zod but the current project validates against large discriminated unions and using the normal anyOf (Type.Union) gives a ton of errors not specifically pertaining to that schema just due to the nature of anyOf vs a discriminator via oneOf.

**Comment by sinclairzx81** [comment]
@MollariDev Hi, 

I really should make some of the TypeBox's internal utility types more well documented (I'll make a note of this for future revisions). But have a look [here](https://github.com/sinclairzx81/typebox/blob/master/example/extensions/union-oneof.ts) for a implementation of union via `oneOf`. This implements the schema as well as sets things up for compilation with the TypeCompiler / Value modules if you need those.

```typescript
import { Kind, TSchema, SchemaOptions, Static } from '@sinclair/typebox'
import { Custom } from '@sinclair/typebox/custom'
import { Value } from '@sinclair/typebox/value'

function UnionOneOfCheck(schema: UnionOneOf<TSchema[]>, value: unknown) {
  return 1 === schema.oneOf.reduce((acc: number, schema: any) => (Value.Check(schema, value) ? acc + 1 : acc), 0)
}

export interface UnionOneOf<T extends TSchema[]> extends TSchema {
  [Kind]: 'UnionOneOf'
  static: { [K in keyof T]: Static<T[K]> }[number]
  oneOf: T
}

/** Creates a Union type with a `oneOf` schema representation */
export function UnionOneOf<T extends TSchema[]>(oneOf: [...T], options: SchemaOptions = {}) {
  if (!Custom.Has('UnionOneOf')) Custom.Set('UnionOneOf', UnionOneOfCheck)
  return { ...options, [Kind]: 'UnionOneOf', oneOf } as UnionOneOf<T>
}
```
Hope this helps!
S

**Comment by sinclairzx81** [comment]
@MollariDev Hey, will close off this issue. 

TypeBox can be extended to support additional types using the above mechanism. Unfortunately there is a little bit of sophistication reconciling the schematic to the intended static type (you will need some familiarity with type mapping in TS).  I will give some thought to making this process simpler down the road, but for now, additional types above and beyond the built in type sets will need to be implemented this way. 

If you have any follow up questions, please feel free to reply on this thread.
Cheers!
S
