### ISSUE TITLE
'default' option dosen't work

### ISSUE THREAD

**Issue by yeongjet** [sinclairzx81/typebox#318]
```ts
export const dto = Type.Object({
    name: Type.String(),
    photo: Type.String({ default: 'http://abc.jpg' })
})

export const dto2 = Type.Object({
    name: Type.String(),
    photo: Type.Optional(Type.String({ default: 'http://abc.jpg' }))
})

const obj = {
    "name": "cellar",
}
// error: { path: '/photo', message: 'Expected required property' }
const checkedObj = dto.Check(obj)
// missing photo property 
const checkedObj = dto2.Check(obj)
```
Both `dto` and `dto2` doen't works, I want the `checkedObj` has `photo` property by default like:
```json
{
    "name": "cellar",
    "photo": "http://abc.jpg"
}
```
I know this can be achieved in Joi using `Joi.string().default('xxx')`，but how to do in typebox?

**Comment by sinclairzx81** [comment]
@yeongjet Hi,

TypeBox doesn't automatically use the `default` value during validation. Instead it has a separate function (`Value.Cast`) that can used optionally to make an incorrect value correct. It works by using value coercion first and uses `default` as a fallback if type coercion is not possible. Note that converting values like this is an expensive operation so it's only something you ideally want to run if validation fails. The following uses `Value.Check()` to test first, documentation on `Value.Cast()` can be found [here](https://github.com/sinclairzx81/typebox#values-cast)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgNQIYBsCuBTOBfOAMyghDgHIABAZ2ADsBjdVYKAehgE8xsAjCAB5sAbhhzkAsAChQkWIjgAVbtgA0SgMoMAFthCp1GmKhjAG+IiTJVajZqw4r+AyVOmFMjUxDpwAwroMANYAPIpw2AIw2HQAJtSaOnqoAHwAFNRJ+gBcSuqiWNi5nkF0EADudACUuUYmZmEpiNJwcFDYMJhQvmiFAHQB2MEZWQZwBThVcAD842K4ub04A6jUMCO6+vnzVdJ40tIMPmtKcAC8Sip9APK8AFZD6wgtcAK5yjx9AHKYILzYUDSSFi2EIqEw6BguQAjPgqqoXpx3lcfn8AUC4CCwRCoXAAExwhFSVoAL2Rn1R-0BwNB4MhuQAzISXuVydhvr8qRisXTcQAWOF7XZuKRHOgnZDnfyBIJpRTqJAvN5waF4hnqVqarXa7VsNhwCBBRG5cgMvHQ8ganXWzV6uBHAEMXDEUhwOi-AFmOBrKD0ADmcBgEDdnIBLzJFDK8GwwhicFQIbRUEtWrtQeM6HQnDg9AKwFi6kw1FwPJxLztrIoIGA1FsfvINtT+urtf9heLmNpZakeGFh2OEHQ7PQED9aWQUztSGVqvVcCRcDN0PUEbnlYFeCAA)

```typescript
import { Value } from '@sinclair/typebox/value'
import { Type, TSchema, Static } from '@sinclair/typebox'

// user defined check function. Will either return the value if correct, or the 
// casted value on fail. Will always return a value of T.
function Check<T extends TSchema>(schema: T, value: unknown): Static<T> {
  return Value.Check(schema, value) ? value : Value.Cast(schema, value)
}

const T = Type.Object({
  x: Type.Number({ default: 1 }),
  y: Type.Number({ default: 2 }),
  z: Type.Number({ default: 3 }),
  w: Type.Number({ default: 4 })
})

const V = Check(T, { 
  x: 123,                    // ok
  y: '321',                  // coerce from numeric string to number
  z: 'not even a number',    // totally invalid, use default
  // w: 'missing'            // missing, use default
})

console.log(V) // { x: 123, y: 321, z: 3, w: 4 }
```

Note also, if you're using Ajv to validate, you can use the `useDefault` option as Ajv is able to automatically use default through configuration. Information on this option can be found https://ajv.js.org/options.html#usedefaults
Hope this helps!
S

**Comment by yeongjet** [comment]
It still cast successful even `w` is string, I want to reject it if type is incorrect, and how to get errors?

**Comment by sinclairzx81** [comment]
@yeongjet Hi. That's correct. If using `Value.Cast()` there will be no error (as this function always produces a value matching the expected type while "retaining as much information from the original value as possible"). Also note, the TypeBox type checker will only test if the value matches the expected type and if it doesn't it is simply considered `false` / 'incorrect`. In this respect the `Value.Cast()` can be used as a fallback in some scenarios where you need a value...but in all other cases, you may want to consider using Ajv to type check as I think it provides the functionality you're looking for.

The TypeBox type checkers only implements the recommended functionality for `default` keyword. The following is a bit more information on the default keyword.

https://json-schema.org/understanding-json-schema/reference/generic.html

> The default keyword specifies a default value. _This value is not used to fill in missing values during the validation process_. Non-validation tools such as documentation generators or form generators may use this value to give hints to users about how to use a value. However, default is typically used to express that if a value is missing, then the value is semantically the same as if the value was present with the default value. The value of default should validate against the schema in which it resides, but that isn’t required.

Have you considered using Ajv for validation?

**Comment by yeongjet** [comment]
Thanks for your advise, but the syntax of Ajv schema is more complex, I want less codes to write :)

**Comment by sinclairzx81** [comment]
@yeongjet Just for reference, TypeBox types are fully compatible with Ajv, the following implements the above using Ajv with `useDefaults: true`...

```typescript
import Ajv from 'ajv'
import { Type, TSchema, Static } from '@sinclair/typebox'

const ajv = new Ajv({ useDefaults: true })
function Check<T extends TSchema>(schema: T, value: unknown): value is Static<T> {
  return ajv.validate(schema, value)
}

const T = Type.Object({
  x: Type.Number({ default: 1 }),
  y: Type.Number({ default: 2 }),
  z: Type.Number({ default: 3 }),
  w: Type.Number({ default: 4 })
})

const V = { }
Check(T, V)    // V is mutably assigned to here...

console.log(V) // { x: 1, y: 2, z: 3, w: 4 }
```
Cheers
