### ISSUE TITLE
Feature request: Require key if another key is present

### ISSUE THREAD

**Issue by Matix-Media** [sinclairzx81/typebox#319]
Basically if `key1` exists, `key2` should exist too.

**Comment by sinclairzx81** [comment]
@Matix-Media Hi! Thanks for the suggestion.

Conditional sub schemas have had some looking into recently, but it's unclear if they will be implemented in TypeBox's type checkers as these are only designed to match the capabilities of TypeScript (and where conditional sub schemas are very much in the realms of runtime conditional logic, which is a little out of scope). 

There may be a potential for `if/then/else` schema keywords to be introduced in subsequent releases (as these can be used to refine validation requirements for existing types without changing the type), but `dependentRequired` and `dependentSchemas` may not as these can change the semantics of the type and there is no clear analog to an equivalent TypeScript type.

With this said, if you do need conditional sub schemas, Ajv may be a better option for validation. TypeBox can model conditional sub schemas on the SchemaOptions for any given type, which can be passed to Ajv for validation. Conditional schema examples below.

### dependentRequired

The following tests If the property `y` is defined, and if so, property `z` is required. Note that `dependentRequired` is part of the 2020 specification. This should provide a solution to the "Basically if key1 exists, key2 should exist too" query.

```typescript
import Ajv from 'ajv/dist/2020'
import { Type } from '@sinclair/typebox'

const T = Type.Object({
  x: Type.Number(),
  y: Type.Optional(Type.Number()),
  z: Type.Optional(Type.Number()),
}, {
  dependentRequired: { // if 'y' is defined, expect 'z'
    'y': ['z']
  }
})

const ajv = new Ajv()
const R1 = ajv.validate(T, { x: 1 })             // const R1 = true
const R2 = ajv.validate(T, { x: 1, y: 2 })       // const R2 = false // expected 'z' property
const R3 = ajv.validate(T, { x: 1, y: 2, z: 3 }) // const R3 = true
const R4 = ajv.validate(T, { x: 1, z: 3 })       // const R4 = true
```

### dependentSchemas

Similar to the above, the property 'z' is required if `'y' is defined. The `dependentSchema` keyword can be used to augment an existing schema object with additional properties. This keyword requires the 2019 minimum specification. 

```typescript
import Ajv from 'ajv/dist/2019'
import { Type } from '@sinclair/typebox'

const T = Type.Object({
  x: Type.Number(),
  y: Type.Optional(Type.Number())
}, {
  dependentSchemas: { // if 'y' is defined, expect additional augmented 'z' property
    'y': Type.Object({
      z: Type.Number()
    })
  }
})

const ajv = new Ajv()
const R1 = ajv.validate(T, { x: 1 })             // const R1 = true
const R2 = ajv.validate(T, { x: 1, y: 2 })       // const R2 = false // expected 'z' property
const R3 = ajv.validate(T, { x: 1, y: 2, z: 3 }) // const R3 = true
const R4 = ajv.validate(T, { x: 1, z: 3 })       // const R4 = true
```

### If Then Else

As mentioned, conditional if then else keywords may make it into TypeBox in subsequent releases as they can be used to refine types (and static conditional TS logic can be produced to match the type somewhat). Below we conditionally check the value of `x` and refine `y` to be a literal number based on a the value of `x`. 

```typescript
import Ajv from 'ajv'
import { Type } from '@sinclair/typebox'

const T = Type.Object({
  x: Type.Union([Type.Literal(1), Type.Literal(2)]),
  y: Type.Number()
}, {
  if: Type.Object({        // if x == 1
    x: Type.Literal(1)
  }),
  then: Type.Object({      // then y == 1
    y: Type.Literal(1),    // ... refine number to literal
  }),
  else: Type.Object({     // else y == 2
    y: Type.Literal(2)    // ... refine number to literal
  })
})

const ajv = new Ajv()
const R1 = ajv.validate(T, { x: 1, y: 1 }) // const R1 = true
const R2 = ajv.validate(T, { x: 1, y: 2 }) // const R2 = false // y != 1
const R3 = ajv.validate(T, { x: 2, y: 2 }) // const R3 = true
const R4 = ajv.validate(T, { x: 2, y: 1 }) // const R4 = false // y != 2
```

Additional information on conditional sub schemas can be found [here](https://json-schema.org/understanding-json-schema/reference/conditionals.html) which details more of the workings of these kinds of schemas. As mentioned, the `if/then/else` keywords are being considered for object schema validation / refinement but may not make it in for some time. 

For now the recommendation is to use Ajv for these scenarios, but certainly open to thoughts.

**Comment by Matix-Media** [comment]
I'd really appreciate the dependentRequired because it would make type validation in for example fastify much more simple as you simply define the body Format in one object without alot of boilerplate.

**Comment by sinclairzx81** [comment]
@Matix-Media Hi,

Fastify is using Ajv under the hood for validation, so you should be able to use `dependentRequired` in Fastify today (as given by the example above). However you may need to check Fastify / Ajv is configured to validate against the draft 2020-12 specification.

```typescript
import Ajv from 'ajv/dist/2020'
```
I'm not sure what specification / version Fastify uses under the hood by default. But if you can ensure it's using 2020, the dependentRequired keyword should work. It might be worth pinging the Fastify project check, however I can recommend a reference example from the TypeBox Fastify TypeProvider project that you should be able to modify to override the default.

See [here](https://github.com/fastify/fastify-type-provider-typebox/blob/main/index.ts#L23-L39) for how to implement a validator for Fastify (replacing the TypeBox TypeCompiler for Ajv 2020)

And [here](https://github.com/fastify/fastify-type-provider-typebox#type-compiler) for how to configure Fastify to override the default.

There might be an easier way to configure this however, so may be worth getting in touch with the Fastify devs just to check.

Hope this helps.

**Comment by Matix-Media** [comment]
Fastify uses ajv version 8. But when I pass the the option `dependentRequired`, as show here:
```ts
            schema: {
                params: Type.Object({ id: Type.String() }),
                body: Type.Object(
                    {
                        username: Type.Optional(Type.String()),
                        password: Type.Optional(Type.String()),
                        newPassword: Type.Optional(Type.String()),
                    },
                    {
                        dependentRequired: {
                            password: ["newPassword"],
                        },
                    }
                ),
            },
```

It fails at startup, saying that it cannot compile the schema because `dependentRequired` is an unknown keyword.
```
FastifyError [Error]: Failed building the validation schema for POST: /api/v1/user/:id, due to error strict mode: unknown keyword: "dependentRequired"
    at Boot.<anonymous> (D:\Development\JS\new-car-booking-system\node_modules\fastify\lib\route.js:359:21)
    at Object.onceWrapper (node:events:627:28)
    at Boot.emit (node:events:525:35)
    at Boot.emit (node:domain:489:12)
    at D:\Development\JS\new-car-booking-system\node_modules\avvio\boot.js:160:12
    at D:\Development\JS\new-car-booking-system\node_modules\avvio\plugin.js:275:7
    at done (D:\Development\JS\new-car-booking-system\node_modules\avvio\plugin.js:200:5)
    at check (D:\Development\JS\new-car-booking-system\node_modules\avvio\plugin.js:224:9)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9) {
  code: 'FST_ERR_SCH_VALIDATION_BUILD',
  statusCode: 500
}
```

**Comment by sinclairzx81** [comment]
@Matix-Media Heya, might close of this issue for now as it seems more related to general Fastify configuration. Can track things over on https://github.com/fastify/fastify/issues/4549. 

Cheers!
S

**Comment by 786maan** [comment]
> @Matix-Media Hi, ROMANEMPIRE 
> 
> Fastify is using Ajv under the hood for validation, so you should be able to use `dependentRequired` in Fastify today (as given by the example above). However you may need to check Fastify / Ajv is configured to validate against the draft 2020-12 specification.
> 
> ```ts
> import Ajv from 'ajv/dist/2020'
> ```
> 
> I'm not sure what specification / version Fastify uses under the hood by default. But if you can ensure it's using 2020, the dependentRequired keyword should work. It might be worth pinging the Fastify project to check, however I can recommend a reference example from the TypeBox Fastify TypeProvider project that you should be able to modify to override the default.
> 
> See [here](https://github.com/fastify/fastify-type-provider-typebox/blob/main/index.ts#L23-L39) for how to implement a validator for Fastify (replacing the TypeBox TypeCompiler for Ajv 2020)
> 
> And [here](https://github.com/fastify/fastify-type-provider-typebox#type-compiler) for how to configure Fastify to override the default.
> 
> There might be an easier way to configure this however, so may be worth getting in touch with the Fastify devs just to check.
> 
> Hope this helps.
