### ISSUE TITLE
Unknown type

### ISSUE THREAD

**Issue by JSteunou** [sinclairzx81/typebox#32]
Hi,

first thank you for this great tool!

Do you think it is possible do add the [unknown](https://www.typescriptlang.org/docs/handbook/basic-types.html#unknown) type?

**Comment by hixus** [comment]
I would like to have unknown as well. Probably underlying jsonschema would remain same as with "any" but the type inferred would be "unknown"

**Comment by sinclairzx81** [comment]
@JSteunou @hixus Hi, apologies for the late reply. 

Just to let you know. `Type.Unknown()` has been added as of `0.12.0`. This works the same as `Type.Any()` but statically infers as a `unknown` as per @hixus 's suggestion. 

Will close off this issue. Thanks for the suggestion!
S

**Comment by JSteunou** [comment]
Great job!
