### ISSUE TITLE
Feature Request: SchemaOptions for custom type

### ISSUE THREAD

**Issue by joshuaavalon** [sinclairzx81/typebox#321]
## Problems
Consider the following code
```ts
import { Type } from "@sinclair/typebox";
import { TypeSystem } from "@sinclair/typebox/system";

const CustomFunctionType = TypeSystem.CreateType(
  "CustomFunction",
  (opts, value) => value instanceof Function
);

console.log(Type.Object({ bar: CustomFunctionType() }));
```

It outputs

```
{
  type: 'object',
  properties: { bar: { [Symbol(TypeBox.Kind)]: 'CustomFunction' } },
  required: [ 'bar' ],
  [Symbol(TypeBox.Kind)]: 'Object'
}
```

There is not way to define things like `description`.

**Comment by sinclairzx81** [comment]
@joshuaavalon Hi,

You can define both inference type and the options via generic arguments on `CreateType<Infer, Options>`. The following extends SchemaOptions into a CustomFunctionTypeOptions type which is passed on the second generic argument (the inference type is the first)

[TypeScript Link Here](https://www.typescriptlang.org/play?ssl=9&ssc=55&pln=9&pc=56#code/JYWwDg9gTgLgBAbzgFQJ5gKYGELmAGwyjgF84AzKXOAcgAEBnYAOwGN8BDYKAehnQwAjCAA8erXGAJEaAWABQoSLEQoBAZVQMYGEKQpU99Jm07c+A4WIZadIOYvDR4SNJgA0cdTA4xgrT3VWAAtdDgB5MD8IZgZ9SmpjFnYuXn5MKwcFHh44AFoCwqLiktKy8oq87Ny3DDgAEQxyFmBo5mr8yq7unuKFBRYdKHIOVjqsAFdtXAAxCbY22si2uIwRHWYAEzig0JAIqOAYuIQFOHOcuGYIHQAuOFQICbhWDmY4DFbQ4jWNza8QmFlkdYnAOHEAO51YIcABu0KIGHcZwuuWgcAAVlN4GBwTtAftgcc4JtuBhWDB8Kg4DAIDTQnAGOSYv8AOYYZhEfxwFFwS4cKCsiYgDnwGJwLBQDC+DC1AB0cAAgvgGBBPI9ngK6td4PhQK0MP9aZjsTz5Oc+bldkDDsdPG9qch1DSBC83nBBHUpoaKOiILbYgqFCR+vIJLF4JNpiA5gsQbU4ABeNSYTTaXRyyXSnS1AA8sYpIM8UdpMfmhZiSwDDAAfAAKFEAIhLs3LbUbyPNcDr-pWnlhHHwEwwAEokzW4AOh3UWNo3mMIOQ4AW2pa4L2QXFgHEW2W45WBETYgoR6HLr0L5eyh0AKIiDjgQgdK8vl+h8PaFBJlMYOXhQQYuSMB1qcXbkBAED3LuK7xgIIEkhgDCsFAwABvcNCtHEHAUG2II0KQp7yCQhEKOkdTIN+3i+P4uZkYuKATpcFHbqo4GQcuuHiiG8gKB+kbfrUOB4IQUCZpI0h1sgJHyFgmahKwADW8FsfcdZjomE4IGQxFrhACkKEAA)

```typescript
import { TypeCompiler } from '@sinclair/typebox/compiler'
import { TypeSystem } from '@sinclair/typebox/system'
import { Type, Static, SchemaOptions } from '@sinclair/typebox'

// --------------------------------------------------------
// Type Definition
// --------------------------------------------------------

interface CustomFunctionTypeOptions extends SchemaOptions {
   // note: you can either extend SchemaOptions as we have here,
   // or just pass SchemaOptions directly to the second generic 
   // argument on CreateType. Also, you are not limited to just 
   // SchemaOptions, any TS type can be used for options.
}

const CustomFunctionType = TypeSystem.CreateType<Function, CustomFunctionTypeOptions>(
  "CustomFunction",
  (options, value) => value instanceof Function // options is CustomFunctionTypeOptions
)

// --------------------------------------------------------
// Example
// --------------------------------------------------------

const T = Type.Object({
  foo: CustomFunctionType({ description: 'its a function' })
})

type T = Static<typeof T> // T is { foo: Function }

const C = TypeCompiler.Compile(T)

C.Check({ foo: () => {} }) // ok
```
Note that the `TypeSystem.CreateType` is fairly rapid way to construct a type, for more advanced inference requirements (for example inferring parameters and return types), you may want to consider using the more low level `Custom` and `Format` modules. An example using these can be found under the [extensions](https://github.com/sinclairzx81/typebox/tree/master/example/extensions) directory of this repo.

Also, the CreateType (and TypeSystem module) is a relatively new addition to the library. Looking for feedback on the design (specifically for the ability to create extension types for various infrastructure), so if you have any thoughts, please let me know.

Hope this helps
S

**Comment by joshuaavalon** [comment]
@sinclairzx81 Thanks you for the quick reply. I will study the examples.
