### ISSUE TITLE
Docs on how to import/compile third party jsonschema type into typebox?

### ISSUE THREAD

**Issue by loynoir** [sinclairzx81/typebox#329]
### Reproduce
Seems cannot directly use third party jsonschema type.

```ts
const packageJsonSchema = {
  // content from https://json.schemastore.org/package.json
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "JSON schema for NPM package.json files"
   // ...
}

type PackageJson = Static<
  // @ts-expect-error
  typeof packageJsonSchema
>

const T = Type.Object({
  foo: Type.String(),
  // @ts-expect-error
  bar: packageJsonSchema
})
type T = Static<typeof T> 
```

**Comment by sinclairzx81** [comment]
@loynoir Hi, 

You can embed third party JSON Schema with the `Type.Unsafe` type, however using this type has the following caveats.

1) TypeBox won't be able to automatically infer the static type for you. You will need to tell it how to infer (see below)
2) You will have to use Ajv as the TypeBox TypeCompiler and Value modules only operate on a strict subset of JSON Schema.

### Example

The following is an updated example using `Type.Unsafe` and the `json-schema-to-ts` package to infer from raw JSON Schema. I've also updated  the schema for `package.json` so you can see the inference coming through. Note you may need to implement the types for `PackageJson` manually (with TS `interface` and `type` keywords) if you notice inference performance of `FromSchema` degrade with large schemas (i assume package.json will have a fairly extensive schema, so this may be the case)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChQkWIjgAxWiFwkAFhhAEK1NYwBWLCOwC0LLToLmYEOy2kzZJMy3hgCJANYEA5hgAUqbsGtq6cAC8iLJwcEKYAFyMECJGGCQwDFhxcGC0mLDAGCwpCHnx7AQgGOUJwikMHlAc-gwUuTLx8QBuGFBsZvWJdYwtbR3kXT1wACalJK1gxMNKo00T7O2dlXA+GKgA7tBzZeuNjARQUASoOXDAMDrnSBvjMK3bU7vdPQQAVxgmmgI0uzU+k1+sy4pAw7BYYze4K2O2meysyxgrz28XeDDSGSyOVx+UKA2IpXK6L+swIczmT2AZgIXAACuTilSLskPl80XsabMFph2AtOCUcbSevjCZlsjNZmSIEVKa8hUr6YzVtV2Zy1WDeRD+VNBYr4gtegARDCi8UkSXlUmy9LyknS+IFFUUx2IDV0hlMll671c14NI2o03S8h5WMySgEFhwNwI+D8fjzMwMeBUaCBeAMJMp9zZOAAQlkslGcDZ3j8gRCZmiKjU4RsAB5RhAqPl6wFgqF27oAHxVmSpjwoFtoTAAOgA8q6sgAKCp-PMQFKzjBz-D8lcASkVImu2+Ec4AqgiCFQMB2674B032COV14n42h9ZdIfZOQ-xcGQa2QFt8CIUgu2EHsUBHOAMwjDBpxiJBNxSVEcFPKAUgBdgfHYCAjnYCggA)

```typescript
import { Type, Static } from '@sinclair/typebox'
import { FromSchema } from 'json-schema-to-ts'

const packageJsonSchema = {
  type: 'object',
  properties: {
    name: { type: 'string' },
    version: { type: 'string' },
    description: { type: 'string' },
    keywords: { type: 'array', items: { type: 'string' } },
    author: { type: 'string' },
    license: { type: 'string' },
    scripts: {
      type: 'object',
      properties: {},
      additionalProperties: { type: 'string' }
    },
    dependencies: {
      type: 'object',
      properties: {},
      additionalProperties: { type: 'string' }
    },
    devDependencies: {
      type: 'object',
      properties: {},
      additionalProperties: { type: 'string' }
    }
  }
} as const // don't forget 'as const' !

// Use the json-schema-to-ts FromSchema type to infer raw JSON Schema
type PackageJson = FromSchema<typeof packageJsonSchema>

const T = Type.Object({
  foo: Type.String(),
  bar: Type.Unsafe<PackageJson>(packageJsonSchema) // use inferred PackageJson on generic
})

type T = Static<typeof T> // type T = { foo: string, bar: { name: string, version: string, ... } }
```
Documentation on `json-schema-to-ts` can be found [here](https://github.com/ThomasAribart/json-schema-to-ts)

Hope this helps
S

**Comment by sinclairzx81** [comment]
@loynoir Hey, hopefully the above info helped, so will close off this issue.

All the best!
S

**Comment by loynoir** [comment]
@sinclairzx81

To validate the mixed jsonschema type and typebox type T, which method is recommended?

- seperately
```js
typeboxValidate(t)
ajvValidate(t.bar)
```

- just ajv at top
```js
ajvValidate(t)
```
