### ISSUE TITLE
Union with Type.Undefined() produces any

### ISSUE THREAD

**Issue by invalidred** [sinclairzx81/typebox#33]
Using `Type.Undefined()` in union always yields `any`

<img width="717" alt="Screen Shot 2020-08-18 at 4 44 32 PM" src="https://user-images.githubusercontent.com/5270458/90563982-9628d080-e172-11ea-9c2d-fec3376f3eaa.png">

I would expect _mediaUrl_ to be a union of `string | null | undefined`, however I see `any`

TSC version: 3.8.3
Also thanks a lot for working on this project :)

**Comment by sinclairzx81** [comment]
Hi,

Thanks for letting me know. The `Type.Undefined()` is actually part of the extended TypeBox API and isn't intended to be used as part of `Type.Object({})` schemas (in the current version of TypeBox anyway, this may change in later revisions of this project). The extended set of types provided by TypeBox are detailed here https://github.com/sinclairzx81/typebox#typebox--typescript-1

As an alternative, you can replace `Type.Undefined()` with `Type.Optional()` which modifies the object property with both `undefined` and `? - possibly undefined` on the inferred object type.

#### Example
```typescript
const Nullable = <G>(T: G) => Type.Union([T, Type.Null()]) 

const TNews = Type.Object({
    mediaUrl: Type.Optional(Nullable(Type.String())),
    link: Nullable(Type.String())
})

type News = Static<typeof TNews>

// type News = {} & {
//     mediaUrl?: string | null | undefined;
// } & {
//     link: string | null;
// }
```
Also ensure you have `strict: true` enabled in your `tsconfig.json`. I have tested on TS 8.3.8 and should work ok. Note that future revisions of TypeBox may mandate on latest versions of the TS compiler. (TypeScript inference rules do change from time to time and this project will seek to align with the most current releases of TypeScript moving forward).

Hope this helps :)

**Comment by invalidred** [comment]
That can work. Thank you for taking the time to respond, really appreciate your help. Also thank you for creating a wonderful library. Cheers.
