### ISSUE TITLE
Unable to use export TypeBox types from a separate library

### ISSUE THREAD

**Issue by marcustut** [sinclairzx81/typebox#330]
I have a library that exports a TypeBox object such as the following:

```ts
export const IndicatorSchema = Type.Object({
   // ...some definitions here
});
```

it was built using `tsup` and published a git repository. Then in another library I imported it and try to use it locally like this:

```ts
const example = Type.Record(Type.String(), IndicatorSchema);
```

It seems like a straightforward use case and I expected it to work however I got these errors from tsc instead:

```ts
src/strategy.ts:26:15 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(key: TUnion<TLiteral<TLiteralValue>[]>, schema: TSchema, options?: ObjectOptions | undefined
): TObject<never>', gave the following error.
    Argument of type 'TString<string>' is not assignable to parameter of type 'TUnion<TLiteral<TLiteralValue>[]>'
.
      Property 'anyOf' is missing in type 'TString<string>' but required in type 'TUnion<TLiteral<TLiteralValue>[
]>'.
  Overload 2 of 2, '(key: TString<string>, schema: TSchema, options?: ObjectOptions | undefined): TRecord<TString
<string>, TSchema>', gave the following error.
    Argument of type 'TUnion<(TObject<{ type: TLiteral<"INDICATOR_NODE">; id: TString<string>; data: TObject<{ in
dicator_type: TLiteral<"INDICATOR_SUPERTREND">; comparator: TObject<{ supertrend: TOptional<...>; direction: TOpt
ional<...>; bar_color: TObject<...>; buy_sell_signal: TObject<...>; }>; params: TObject<...>; }>; }> | ... 46 mor
...' is not assignable to parameter of type 'TSchema'.
      Property '[Kind]' is missing in type 'TUnion<(TObject<{ type: TLiteral<"INDICATOR_NODE">; id: TString<strin
g>; data: TObject<{ indicator_type: TLiteral<"INDICATOR_SUPERTREND">; comparator: TObject<{ supertrend: TOptional
<...>; direction: TOptional<...>; bar_color: TObject<...>; buy_sell_signal: TObject<...>; }>; params: TObject<...
>; }>; }> | ... 46 mor...' but required in type 'TSchema'.

26   indicators: Type.Record(Type.String(), IndicatorSchema),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  ../../node_modules/.pnpm/@sinclair+typebox@0.25.21/node_modules/@sinclair/typebox/typebox.d.ts:295:5
    295     anyOf: T;
            ~~~~~
    'anyOf' is declared here.
  ../../node_modules/.pnpm/@sinclair+typebox@0.25.21/node_modules/@sinclair/typebox/typebox.d.ts:29:5
    29     [Kind]: string;
           ~~~~~~
    '[Kind]' is declared here.
```

So it seems like the `[Kind]` type got lost in the process of making it as a library?

**Comment by sinclairzx81** [comment]
@marcustut Hi!

You should be able to export TypeBox types from a shared library, but I can't really provide much information on specific tooling like `tsup` (as I'm not really a user of it).

**Versions**

If the library exports types from `typebox@0.25.21` and your application is using `typebox@0.25.23`,  TypeScript may flag this as the `Kind` symbol may be interpreted as a different incompatible symbol type if imported across different versions. Just make sure your application is using the same version of TypeBox as the library you're importing.

Let me know if that helps
Cheers!

**Comment by marcustut** [comment]
Yes indeed, you're correct. After I've upgrade them to the same version then it works now. However, from a library standpoint how do I make sure the users of my library has the same version of `typebox`? Is this what `peerDepdency` tries to solve?

**Comment by marcustut** [comment]
Or I can just simply pin the version in my library to a specific version and when it's installed, npm will make sure that both machines has to same version of typebox

**Comment by sinclairzx81** [comment]
@marcustut Good to hear that solved the issue!

Yeah, two options might be to lock to a fixed `version` or have the shared library take on TypeBox as a `peerDependency`. A `peerDependency` should allow you to upgrade to the latest versions of TypeBox across both shared library and application, so I'm thinking that might be the way to go. 

Anyway, hope this helps! :) Will close off this issue for now as it sounds like things are largely resolved, but if you have any other questions on the versioning side, feel free to reply on this thread.

Cheers!
S
