### ISSUE TITLE
Adding validation for strings using formats

### ISSUE THREAD

**Issue by Rantoledo** [sinclairzx81/typebox#341]
Hi,

I'm trying to add validation to some strings in my project.
I'm using fastify and typebox.

I tried to use formats:

I tried importing format:
```
import { Format } from '@sinclair/typebox/format';

namespace AdditionalFormats {

    const ACCOUNT_ID_REGEX = /(^account-)[a-zA-Z0-9]{8}$/
    function isValidAccountId(value: string) {
        return ACCOUNT_ID_REGEX.test(value);
    }

    export function Configure(): void {
        Format.Set('account-id', (value) => isValidAccountId(value))
      
    }
}
AdditionalFormats.Configure();
```

Then I tried to use TypeSystem:

```
import { TypeSystem } from '@sinclair/typebox/system';
const ACCOUNT_ID_REGEX = /(^account-)[a-zA-Z0-9]{8}$/
TypeSystem.CreateFormat('account-id', (value: string) => {
    return ACCOUNT_ID_REGEX.test(value);
});
```

And added to string format:
```
const AccountIdParams = Type.Object({
    accountId: Type.String({ format: "account-id"})
});
```

after adding to the parameter in my routes, im getting error saying:
"Failed building the validation schema for GET: /.../:accountId/...., due to error unknown format "account-id" ignored in schema at path "#/properties/accountId"

What am I missing here?

**Comment by sinclairzx81** [comment]
@Rantoledo Hi! Are you using the TypeCompiler? 

https://github.com/fastify/fastify-type-provider-typebox#type-compiler

```typescript
import { TypeBoxTypeProvider, TypeBoxValidatorCompiler } from '@fastify/type-provider-typebox'
import { Type } from '@sinclair/typebox'
import Fastify from 'fastify'

const fastify = Fastify().setValidatorCompiler(TypeBoxValidatorCompiler)
```
Note, the `Format` and `Custom` modules will only configure the TypeBox TypeCompiler module, not Ajv module which Fastify uses as a default. If you're already on Ajv for your validation, you can find some information on adding additional formats at the link below.

https://ajv.js.org/guide/formats.html

```typescript
ajv.addFormat("identifier", /^a-z\$_[a-zA-Z$_0-9]*$/)
```
Hope this helps
S

**Comment by sinclairzx81** [comment]
@Rantoledo Hi, I might close off this issue as it seems related to Fastify integration. Happy to discuss the `Format` module specific to TypeBox here, but for Fastify integration, would recommend submitting an issue to either the `fastify` repository, or the `@fastify/typebox-type-provider` repository. 

Relevant Project links below.

https://github.com/fastify/fastify (this is you're using Ajv)
https://github.com/fastify/fastify-type-provider-typebox (this if you're using the `TypeBoxValidatorCompiler` plugin as per previous comment)

If you ping me there, happy to help further.

Cheers!
S

**Comment by Rantoledo** [comment]
Thanks for the comment. I'll take a look
