### ISSUE TITLE
store created json schema as file

### ISSUE THREAD

**Issue by xddq** [sinclairzx81/typebox#345]
Thanks for the great library!

Sorry to bother, but how can I store the created JSON schemas to a file? Is this possible within this library?

**Comment by sinclairzx81** [comment]
@xddq Hi!

TypeBox types are just plain old JavaScript objects, so you can use `JSON.stringify()` on them to write them to disk as strings. The following would write the type `Vector3` to disk using NodeJs.

```typescript
import { Type } from '@sinclair/typebox'
import * as Fs from 'node:fs'

const Vector3 = Type.Object({ x: Type.Number(), y: Type.Number(), z: Type.Number() })

Fs.writeFileSync('Vector3.json', JSON.stringify(Vector3, null, 2), 'utf-8')
```
If you have multiple schemas, you can either write them individually (as above), or combine them under a top level `$def` schema.
```typescript
import { Type } from '@sinclair/typebox'
import * as Fs from 'node:fs'

const Vector3 = Type.Object({ x: Type.Number(), y: Type.Number(), z: Type.Number() })
const Vector2 = Type.Object({ x: Type.Number(), y: Type.Number() })
const Scalar = Type.Object({ x: Type.Number() })

const MathTypes = { $defs: { Vector3, Vector2, Scalar } }

Fs.writeFileSync('MathTypes.json', JSON.stringify(MathTypes, null, 2), 'utf-8') 
```
Hope this helps!
S

**Comment by sinclairzx81** [comment]
@xddq Hi, might close off this issue as `JSON.stringify()` should be all that's required write schemas to disk :)

All the best!
S
