### ISSUE TITLE
Remove reliance on value of `this`

### ISSUE THREAD

**Issue by birjj** [sinclairzx81/typebox#355]
This appears to be a problem throughout the library, due to the use of `this`.

## Issue

In JavaScript (and TypeScript by extension), the value of `this` changes depending on how a function is called. This leads to hard-to-debug bugs, and usage patterns that seem fine not working - and not being caught by TypeScript's type checker. For example:

```typescript
import { Type } from "@sinclair/typebox";
import { TypeCompiler } from "@sinclair/typebox/compiler";

const TypeVector = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
});
const isVector = TypeCompiler.Compile(TypeVector).Check;

// above compiles fine, and TypeScript sees `isVector` as type `(value: unknown) => value is { x: number; y: number; z: number; }`
// but when we try to use it:

isVector({ x: 0, y: 0, z: 0 });

// TypeError: Cannot read properties of undefined (reading 'checkFunc')
//    at Check (.../@sinclair/typebox/compiler/compiler.js:58:21)
//    at ...
```

## Potential fixes

The library should bind the value of `this` for any externally exposed methods. This could either be done by re-writing them to arrow functions:

```typescript
export class TypeCheck<T extends Types.TSchema> {
  /* ... */
  public Check = (value: unknown): value is Types.Static<T> => {
    return this.checkFunc(value)
  }
}
```

Or by explicitly calling `.bind` in the constructor:

```typescript
export class TypeCheck<T extends Types.TSchema> {
  constructor(private readonly schema: T, private readonly references: Types.TSchema[], private readonly checkFunc: CheckFunction, private readonly code: string) {
    this.Check = this.Check.bind(this);
  }
  /* ... */
}
```

Using either of those two ways, the value of `this` inside the `Check` method will always be the instance of `TypeCheck` it was defined on.

**Comment by sinclairzx81** [comment]
@birjj Hi,

The implementation of `TypeCheck<T>` and other instance types are typical JavaScript class implementations, so I'd need a very good reason to implement non-standard internal binds that work above and beyond standard JavaScript scoping rules for `this`. For extracting the `.Check()` function from `TypeCheck`, the following two approaches work and are inline with standard JavaScript `this` behaviors.

### Option 1

```typescript
const typecheck = TypeCompiler.Compile(schema)

const check = typecheck.Check.bind(typecheck) // external bind(), inline with standard JavaScript
```

### Option 2

```typescript
function compile<T extends TSchema>(schema: T) { // retain instance `this` in closure.
  const typecheck = TypeCompiler.Compile(schema)
  return (value: unknown) => typecheck.Check(value) // instance CallExpression, works fine.
}

const check = compile(Type.String())
```
While I partially agree that being able to retain `this` without explicit external `.bind()` for the scenario you describe is a nice thing to be able to offer users, I do have many reservations about implementing specific behaviors for classes that are at odds with standard JavaScript. In general, it's far easier to point users at the JavaScript `class` specification than it is to try and justify why TypeBox would chose to implement something different.

In my experience, implementing classes using standard JavaScript scoping rules leads to less confusion as users don't need to second guess whether or not a library author internally implemented `.bind()` or not. Everyone should know what a `class` is, and the implication of calling members on the class without an instance. Also I don't think libraries should be implementing fixes like this to compensate for behaviors not support natively by the language, especially for behaviors so intrinsic to the language.

This is most likely a "wontfix", but am open to hearing more justification for internally implementing behaviors above and beyond the JavaScript class spec. Do you have any reference links on this?

**Comment by sinclairzx81** [comment]
It's noted that Node itself doesn't implement internal `.bind()` on it's class-like implementations either.

```typescript
import * as fs from 'fs'

const stat = fs.statSync('package.json')

const isFile = stat.isFile

isFile() // TypeError: Cannot read properties of undefined (reading '_checkModeProperty')
```

**Comment by sinclairzx81** [comment]
@birjj Heya, might close this one off as I'm quite keen to keep things as they are (with the explicit external `this` `.bind()`). Like I say, I do get the intent for wanting to handle this automatically (and internal to the library), but generally I feel it's better to keep inline with expected JavaScript class behavior, even if it's unexpected / unusual behavior when contrasted with other languages.

If you have you some references on this though, will be happy to read over them. I'm actually quite curious to see how many authors are implementing the internal `.bind()` as per this suggestion.

All the best!
S

**Comment by birjj** [comment]
I think this is a broader discussion, with proponents on both sides - across the JS landscape. The language design choices behind the behavior of `this` appear poorly made to me - they are simply too fragile, with few if any positives. It's a design choice that the JS world has explicitly tried to move away from, by introducing arrow functions, but old syntaxes (class syntax, or the earlier explicit prototype manipulation) still have all the issues that come with `this`.

While I don't have many resources to link to, since I don't follow the JS blog post landscape particularly closely, I know that it is a [common pattern in old React](https://legacy.reactjs.org/docs/handling-events.html) to work around the issues with `this` using either of the two patterns I mentioned. While not particularly authoritative, it's also a common topic of discussion on StackOverflow (see e.g. https://stackoverflow.com/a/45898085).

It appears to me that the rationale is fairly simple: if a function is exposed to somewhere outside your own code, where you might not know how it is eventually called, then you should ensure correctness of the code by binding `this` (or by explicitly mentioning how it should be called in the documentation, but that seems cumbersome and easily overlooked) - otherwise you have no way of knowing whether your code will actually work.

That being said, you are fully within your right to choose to go with the old handling of `this` (not least because breaking changes are frustrating).
