### ISSUE TITLE
[feat] add some test cases for `TypeCompiler.Compile`

### ISSUE THREAD

**Issue by loynoir** [sinclairzx81/typebox#358]
### Feat
Add some test cases for `TypeCompiler.Compile`.

### Related
https://github.com/sinclairzx81/typebox/issues/353
https://github.com/sinclairzx81/typebox/issues/356

**Comment by sinclairzx81** [comment]
@loynoir Hi,

There are already extensive unit tests for the `Compile()` function implemented by way of the type assertion unit tests. The `Ok(T, ...)` and `Fail(T, ...)` assert functions will run a compilation per type `T`, as well as run checks to ensure the compiled (JIT) check routine matches the assertion check implemented by way of `Value.Check()`. These tests are fairly extensive (with the member expression functionality falling under expected assertion behavior for types of `TObject`)

- Compile Checked for `Ok(...)`
  - https://github.com/sinclairzx81/typebox/blob/master/test/runtime/compiler/validate.ts#L66
- Compile Checked for `Fail(...)`
  - https://github.com/sinclairzx81/typebox/blob/master/test/runtime/compiler/validate.ts#L97
- Test cases for issues [353](https://github.com/sinclairzx81/typebox/issues/353) and [356](https://github.com/sinclairzx81/typebox/issues/356)
  - https://github.com/sinclairzx81/typebox/blob/master/test/runtime/compiler/object.ts#L129-L150
- Additional Unicode (UTF-16) tests
  - https://github.com/sinclairzx81/typebox/blob/master/test/runtime/compiler/unicode.ts
  
Did you have something else in mind to test the `.Compile()` function in isolation?

**Comment by loynoir** [comment]
> Did you have something else in mind to test the .Compile() function in isolation?
Are there generated-code-syntax-check to prevent similar bug again?

If yes, I'm OK to close.

**Comment by sinclairzx81** [comment]
@loynoir Will close this off as there are already extensive tests implemented for the Compiler. But if you have some suggestions to either enhance or define a new category of compiler test that asserts specifically for the evaluated JIT routine (not including Type assertion tests), would be happy to explore and potentially implement.

Cheers!
S
