### ISSUE TITLE
0.26.5: Unable to correctly cast numbers inside Record

### ISSUE THREAD

**Issue by RuneSP** [sinclairzx81/typebox#360]
I'm trying to use typebox to parse strings to numbers in a record, eg:

```
const recordSchema = Type.Record(
  Type.String(),
  Type.Number()
);

const convertedValue = Value.Convert(recordSchema, { "EUR": "400" });
const castValue = Value.Cast(recordSchema, convertedValue);
console.log({ convertedValue, castValue });
```

Returns:

`{ convertedValue: { EUR: '400' }, castValue: { EUR: 0 } }`

In version 0.25, Value.Cast would correctly parse '400' to a number inside a Record.

**Comment by sinclairzx81** [comment]
@RuneSP Hi, 

Thanks for reporting. I have just pushed an update on `0.26.6` to resolve this. There was a bit of refactoring going on in the 0.26.0 release extracting the conversion logic from the cast logic, and it appears that Record conversion was missed (sorry about that). I've also included union conversions in this update also.

Let me know if this helps
Cheers
S
