### ISSUE TITLE
`TypeCompiler` doesn't work well with `Type.Record` when properties like `minProperties` is set

### ISSUE THREAD

**Issue by SunnySunnyOMG** [sinclairzx81/typebox#362]
It looks we check the `min/maxProperties` for `Type.Object` but we don't do the same for `Type.Record`?

## how to reproduce
```ts
import { Type } from '@sinclair/typebox';
import { TypeCompiler } from '@sinclair/typebox/compiler';

const schema = Type.Record(Type.String(), Type.String(), {
  minProperties: 1,
});
// get validator
const C = TypeCompiler.Compile(schema);
```
then check an empty object
```ts
// pass an empty object
C.Check({}); // expected: false, but, actual: true
```

**Comment by sinclairzx81** [comment]
Will close off this issue for now as the `minProperties` and `maxProperties` constraints should be good on `0.26.7`, but feel free to reply on this thread if you run into any issues with the new assertions.

All the best!
S

**Comment by SunnySunnyOMG** [comment]
thanks @sinclairzx81  for the quick fix!!
