### ISSUE TITLE
new ts 5.0 const generic enum?

### ISSUE THREAD

**Issue by trim21** [sinclairzx81/typebox#367]
ts 5.0 new feature const generic type https://github.com/microsoft/TypeScript/pull/51865

```ts
Type.Enum(
      {
        s3: 's3',
        FS: 'fs',
      } as const,
      { default: 'fs },
    )
```

could become

```ts
Type.Enum(
      {
        s3: 's3',
        FS: 'fs',
      } ,
      { default: 'fs' },
    )
```

without `as const`

**Comment by sinclairzx81** [comment]
@trim21 Hi, thanks for the suggestion :)

At this stage, I'm holding off on `const` generics to ensure backwards compat for TS `4.2.3`, but will review places where const generics would applicable in later revisions of the library (likely when TS 5.0 has been around for a few months). For now, the following is still the recommended way to express `Type.Enum`; using an auxiliary `enum` structure (or alternatively a literal union)

```typescript
import { Type, Static } from '@sinclair/typebox'

enum Foo { A, B, C }

const T = Type.Enum(Foo)

function test(value: Static<typeof T>) {
    switch(value) {
        case Foo.A: return console.log('Foo.A')
        case Foo.B: return console.log('Foo.B')
        case Foo.C: return console.log('Foo.C')
    }
}

test(Foo.A)
test(Foo.B)
test(Foo.C)
```
Btw, Is the explicit expression of `{ s3: 's3', FS: 'fs' }` a common way to express enums over using the language supported `enum`?. I remember hearing something about explicitly specifying enums the way you have being a preference for some developers, but can't remember the details / rationales as to why.

Anyway, hope this brings some insights into the future plans for `const` generics in TB
S

**Comment by trim21** [comment]
> Btw, Is the explicit expression of { s3: 's3', FS: 'fs' } a common way to express enums over using the language supported enum?

I only need to write it once in a object, so I just write a inline enum. So I don't need to create a ts enum.

I'm actually using it as a union, not enum here.

**Comment by sinclairzx81** [comment]
> I'm actually using it as a union, so I don't need to write this:

I mean as opposed to this (using an enum with string values)

```typescript
enum StorageOptionEnum {
    s3 = 's3',
    fs = 'fs'
}

const StorageOption = Type.Enum(StorageOptionEnum) // const StorageOption = { // produces a union structure
                                                   //   anyOf: [
                                                   //     { type: 'string', const: 's3' },
                                                   //     { type: 'string', const: 'fs' } 
                                                   //   ]
                                                   // }

function store(value: Static<typeof StorageOption>) {
    switch(value) {
      case StorageOption.s3: return console.log('StorageOption.s3')
      case StorageOption.fs: return console.log('StorageOption.fs')
    }
}

store(StorageOption.s3)
store(StorageOption.fs)
```
Side note, I see that TS 5.0 actually [treats all enums as unions](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#all-enums-are-union-enums) now, wondering if TypeBox should yield infer union (as opposed to the original `enum`). May take a closer look at this.

**Comment by trim21** [comment]
Yes I know, I just don't want to write it twice 😆 I write literial value in case.

It already yield infer union I think? I try `console.log(t.Enum)` and it's a union kind.
