### ISSUE TITLE
Type.Union() should result in anyOf instead of oneOf

### ISSUE THREAD

**Issue by sunaurus** [sinclairzx81/typebox#37]
This code:

```
const FirstSchema = Type.Object({foo: Type.String()})
const SecondSchema = Type.Object({foo: Type.String(), bar: Type.Optional(Type.String())})
const Union = Type.Union([FirstSchema, SecondSchema]);
```

Generates the following schema:

```
    {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "foo": {
              "type": "string"
            }
          },
          "required": [
            "foo"
          ]
        },
        {
          "type": "object",
          "properties": {
            "foo": {
              "type": "string"
            },
            "bar": {
              "type": "string"
            }
          },
          "required": [
            "foo"
          ]
        }
      ]
    }
```

The issue is that it uses oneOf instead of anyOf - oneOf means that objects may match **exactly one** schema, but in TypeScript, unions work like anyOf, not oneOf. With anyOf, objects must match **at least one** schema.

For example, this is valid TypeScript:

```
type FirstType = {
  foo: string;
}

type SecondType = {
  foo: string;
  bar?: string;
}

type UnionType = FirstType | SecondType;

const test: UnionType = {foo: "test"};
```
However, `{foo: "test"}` will not match the `Union` schema shown above, because:
```
JSON is valid against more than one schema from 'oneOf'.
```

Would you accept a PR that changes oneOf to anyOf for `Type.Union()`?

**Comment by sinclairzx81** [comment]
@sunaurus Hi, This update has been published to npm along with a variety of other updates to better align with TypeScript 4.0. Thanks for the PR on this. Updates in `@sinclair/typebox@0.12.0`.

Cheers
S
