### ISSUE TITLE
Type.Omit doesn't work when Kind is specified

### ISSUE THREAD

**Issue by ashervb** [sinclairzx81/typebox#384]
```typescript
const Foo = Type.Object({
  x: Type.String(),
  y: Type.Unsafe<bigint>({ [Kind]: 'BigInt', type: 'string' }),
})

const Bar = Type.Omit(Foo, ['y'])
console.log(Bar)
```
Results in:

```
{
  type: 'object',
  properties: {
    x: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' },
    y: { type: 'string', [Symbol(TypeBox.Kind)]: 'BigInt' }
  },
  required: [ 'x', 'y' ],
  [Symbol(TypeBox.Kind)]: 'Object'
}
```

Applying `Strict`:

```typescript
const Foo = Type.Object({
  x: Type.String(),
  y: Type.Strict(Type.Unsafe<bigint>({ [Kind]: 'BigInt', type: 'string' })),
})
```

Results in:

```
{
  type: 'object',
  properties: {
    x: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' },
    y: { type: 'string' }
  },
  required: [ 'x', 'y' ],
  [Symbol(TypeBox.Kind)]: 'Object'
}
```

Now omitting the kind:

```typescript
const Foo = Type.Object({
  x: Type.String(),
  y: Type.Unsafe<bigint>({  type: 'string' }),
})

const Bar = Type.Omit(Foo, ['y'])
console.log(Bar)
```
Results in:

```
{
  type: 'object',
  properties: { x: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' } },
  required: [ 'x' ],
  [Symbol(TypeBox.Kind)]: 'Object'
}
```

**Comment by sinclairzx81** [comment]
@ashervb Hi, thanks for reporting.

Yeah, there's been quite a few updates recently to TypeBox type composition to try and make composition more strict. TypeBox needs to derive information from the `[Kind]` when handling user defined types with the TypeCompiler, so the updates would treat unregistered `[Kind]` as invalid (which was breaking composition as objects with invalid properties are not considered objects anymore, which is a bit too strict)

I've eased up the composition type checks on `0.27.8` so this issue should be fixed. Associated PR with changes and tests can be found at the link below.

https://github.com/sinclairzx81/typebox/pull/385

Thanks again for reporting. If you have any other issues around this, please let me know (am trying to catch regressions like this early given the changes, so bug reports like this are very helpful)

All the best!
S
