### ISSUE TITLE
How to set "default" without changing source schema

### ISSUE THREAD

**Issue by erwinstone** [sinclairzx81/typebox#388]
For example I have schema
```typescript
const active = Type.Boolean()
```
I want the schema to have default value without changing it to `Type.Boolean({ default: false })`.
Is there a way something like
```typescript
active.setDefault(false)
```
So that I can use it like:
```typescript
schema: {
  body: Type.Object({
    active: active.setDefault(false),
  }),
},
```
I know I can set the "default" property in a new line like
```typescript
active.default = false
```
but I find it inconvenient that way, what do you think ?

**Comment by sinclairzx81** [comment]
@erwinstone Hi,

TypeBox only supports the `Type.Boolean({ default: true })` option passing style, not the fluent style of `Type.Boolean().Default(true)`. The reason for this is to ensure the return type of `Type.Boolean({ ... })` is a pure JSON Schema object (with no non-standard properties or functions applied to that object). The option passing style helps to keep TypeBox types compliant with strict JSON schema compliant validators (like Ajv), as well as keeps TS type inference fast (as chaining functions will cause TS inference performance to degrade)

It's noted, the fluent style is typical in libraries like Yup and Zod. TypeBox doesn't implement the style for the above reason, however a reference implementation of the fluent style can be found https://github.com/sinclairzx81/typebox/blob/master/example/typemap/typemap.ts which replicates the Zod API by layering TypeBox's option passing interface with a Zod-like fluent interface.

The following should be possible with Fastify

```typescript
import t from './typemap' // you will need to copy this file into your project.

schema: {
  body: t.object({
    active: t.boolean().default(false),
  }).schema(),
},
```
Just note, the fluent interface is only provided as a reference example (it's not published as an official package), and hasn't had extensive testing. The example may be promoted to an official package one day, but for now, you will need to copy and paste the file into your project to use.

Hope this helps
S

**Comment by erwinstone** [comment]
Thanks for the helpful answers as always
