### ISSUE TITLE
Feature Request: Indexed Access Types

### ISSUE THREAD

**Issue by jayalfredprufrock** [sinclairzx81/typebox#391]
This could very well be out of scope for Typebox since it doesn't really have much bearing on JSON schema, however I would certainly find it very useful. Here is my use case.

When I'm modeling inheritance (_sparingly_) in the backend, I often use a base type which I then extend (using Type.Composite) with an object containing a discriminating union type along with extra properties specific to that subtype. So something like this:

```
const SchemaBase = Type.Object({
    id: Type.String(),
    name: Type.String()
});

const ExtendedType1Schema = Type.Composite([
    SchemaBase,
    Type.Object({
         type: Type.Literal('type1'),
         ...extraProps
     })
]);

const ExtendedType2Schema = Type.Composite([
    SchemaBase,
    Type.Object({
         type: Type.Literal('type2'),
         ...extraProps
     })
]);

const FinalSchema = Type.Union([ExtendedType1Schema, ExtendedType2Schema]);
```

This works great and allows type narrowing based on the `type` property as expected. But sometimes I want to reference the type in another schema. With typescript I could just use `FinalSchemaType["type"]` to get back a literal union of all the types. It would be amazing if typebox had some kind of `Type.Index(FinalSchemaType, "type")` that would behave like typescript for type inference and produce the equivalent JSON schema. This might be impossible but wanted to ask nevertheless!

BTW, love all the recent development. Building on top of this library has proven to be a wise choice and my entire team agrees!

**Comment by sinclairzx81** [comment]
@jayalfredprufrock Hi! Hey, it's great to hear you're getting good value from TypeBox :)

Indexed Access Types are actually under consideration as a compiler transform target. They've recently had some looking into while developing some external [compiler transform tooling](https://sinclairzx81.github.io/typebox-workbench/?share=ZXhwb3J0IGludGVyZmFjZSBUIHsNCiAgeDogbnVtYmVyDQogIHk6IG51bWJlcg0KfQ0KDQp0eXBlIEkgPSBUWyd4J10gLy8gVEIgbmVlZHMgaW5kZXhlZCBhY2Nlc3NvciBzdXBwb3J0IQ0KDQo%3D) for TypeBox (written to assert TS alignment). At this stage, I have a rough idea on how to approach the implementation, but will draft a high level description below for consideration and future reference (note: I may not get around to the implementation for a while)

## Indexed Access Types

It is currently possible to index into an object in the following way.

```typescript
const T = Type.Object({ x: Type.Number(), y: Type.String() })

const X = T.properties['x']                          // type X = T['x']
```
However indexers are not uniform for intersection and union types
```typescript
const T = Type.Intersect([
  Type.Object({ x: Type.Number() }),
  Type.Object({ y: Type.String() })
])

const X = T.properties['x']                          // I want to write this

const X = T.allOf[0].properties['x']                 // ... but need to write this
```
Indexers can be made uniform with a new `Type.Indexed` type
```typescript
const T = Type.Intersect([
  Type.Object({ x: Type.Number() }),
  Type.Object({ y: Type.String() })
])
const X = Type.Indexed(T, Type.Literal('x'))         // const X = Type.Number()
```
With the expectation that the indexers support the following advanced usage
```typescript
type A = { x: number }
type B = { y: string }
type I = A & B

type U = I['x' | 'y']                                // type U = number | string

const A = Type.Object({ x: Type.Number() })
const B = Type.Object({ y: Type.String() })
const I = Type.Intersect([A, B])

const U = Type.Indexed(I, Type.Union([               // const U = Type.Union([
  Type.Literal('x'),                                 //   Type.Number()
  Type.Literal('y')                                  //   Type.String()
])                                                   // ])
```
Will leave this issue open for now. Happy to discuss this feature in more depth if you have any suggestions on the above design.
Cheers!
S

**Comment by smiley-uriux** [comment]
Yup this is pretty much exactly what I had in mind. Additional advanced usage to align with TypeScript would ideally include extracting array and record item types as follows:

```
const A = Type.Array(Type.String());
const I = Type.Indexed(A, Type.Number());                 // type I = string

const R = Type.Record(Type.String(), Type.Number());
const I = Type.Indexed(R, Type.String());                 // type I = number
```

This is really more of a "nice to have" since I would almost certainly build the item schema separately before combining with `Type.Array()` or `Type.Record()` but nevertheless this could be considered expected behavior.

**Comment by smiley-uriux** [comment]
Realizing I'm mixing user accounts here...this happens to be my work handle but I'm actually the OP.

**Comment by sinclairzx81** [comment]
@smiley-uriux I think these should be achievable

```typescript
const A = Type.Array(Type.String());
const I = Type.Indexed(A, Type.Number());                 // type I = string

const R = Type.Record(Type.String(), Type.Number());
const I = Type.Indexed(R, Type.String());                 // type I = number
```
The `Type.Array()` indexer will interesting. Currently TypeBox draws distinction between Records and Arrays (as the JSON Schema specification draws these distinctions), but it should in theory be possible map it through an indexer none the less.  There's been a little bit of churn internal to TypeBox recently trying to get Records and Objects in sync (as TypeBox has varying representations for finite and infinite keys), so will likely need to investigate interpreting Arrays as a kind of keyed Object type (presumably where `Type.KeyOf(Type.Array(Type.String()))` yields a `Type.Number()`)

Will investigate.

**Comment by sinclairzx81** [comment]
@jayalfredprufrock Hi. Have just published provisional support for Indexed Access Types on 0.28.0. Information on the feature can be found on the [PR](https://github.com/sinclairzx81/typebox/pull/395) or changelog located [here](https://github.com/sinclairzx81/typebox/blob/master/changelog/0.28.0.md). The following is now supported.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAWABQw2hGoV4yOAF4UnAHQB5LgCsMtGAAokcPfoOGDrVnA6YUsxHF4AuONQCuILhigAaOKnuSoNAOY4RsHCBnbymAoAcs6uUFoAlJ7BKfqh+t4RGAoAyjB+1P6JqanC2AnCouKScACSVmiRtdQAJhi8WsiejdkA0hioSnidCQnGpuZY9XLIANoA1gMQeCgAuuklm1vBJiUAehvbR1u7qU4ubnAAPnC+AcJAA)

```typescript
import { Type } from '@sinclair/typebox'

const T = Type.Object({                    // type T = { x: number, y: string }             
    x: Type.Number(),                   
    y: Type.String()                  
})

const I = Type.Index(T, Type.KeyOf(T))    // type I = T[keyof T]
                                          //          ^
                                          //          number | string
```
The type inference logic to support this across Object, Intersect, Union, Tuple and Array types turned out to be fairly sophisticated, but should be more or less in tune with TypeScript. Will close of this issue for now, but let me know if you spot any issues with the implementation.

Cheers!
S

**Comment by jayalfredprufrock** [comment]
Absolutely amazing! I'll be curious to see what the solution looks like :)
