### ISSUE TITLE
`Static` should be better on known length array

### ISSUE THREAD

**Issue by loynoir** [sinclairzx81/typebox#392]
```ts
const schema = T.Array(T.Literal(42), { minItems: 1, maxItems: 1 })

type actual = Static<typeof schema>
// type actual = 42[]

type expected = [42]
```

**Comment by sinclairzx81** [comment]
@loynoir Hi!. This is already supported with `Type.Tuple`

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwIYGcUA0cAyjNjMAMZwC+cAZlBCHAOQACuwAdpQDbZgUAPQx0GAEYQAHqwCwAKEWUI3XPFyUAFhhDY4AXhQA6ZAFcwfDAAoA2smMAZYDAxRsfawBYATAEoAXT9FRTFMHEoYMw9DEjIKSgAeMIwIejhNHT0APjhhYTgUiKiYo1tfAKA)

```typescript
import { Type as T, Static } from '@sinclair/typebox'

const schema = T.Tuple([T.Literal(42)])

type actual = Static<typeof schema> // type actual = [42]
```
Note, it's not possible to have `Type.Array` infer tuples from min/max constraints as these constraints may specify large values. Also TypeScript has limits to the amount of types (or element types in this case) it can generate from numeric values (like min and max). Tuples types required the element types be explicit (not generative). This is inline with TypeScript syntax for tuples also.

```typescript
type tuple = [42]
const tuple = T.Tuple([T.Literal(42)])

type array = 42[]
const array = T.Array(Type.Literal(42))
```
Hope this helps
S

**Comment by sinclairzx81** [comment]
@loynoir Will close off this issue for now as this functionality is already supported with tuple types. But feel free to reply on this thread if you have any questions on the above.

Cheers
S
