### ISSUE TITLE
optional properties?

### ISSUE THREAD

**Issue by danbrauer** [sinclairzx81/typebox#4]
Hi!  It is possible to define an optional object property?

What I mean is something that, in Typescript, would be defined like `b` below:

```
type MyType = {
   a: string,
   b?: string 
}
```

In this case, `a` must be there but `b` may be absent.

We at first thought this could be defined with something like this, with typebox:

```
const MyTypeSchema = Type.Object({
   a: Type.String(),
   b: Type.Optional(Type.String())
})
```

But that's not quite the same.  It leads to a type like this:

```
type MyType = {
   a: string,
   b: string  // <--- we'd want `b?: string`
}
```

Just wondering if we're missing something with respect to optional properties, or if the project does not allow them?

Thank you!
Dan

**Comment by sinclairzx81** [comment]
Hi,

Yeah, good spotting :) Its actually something that needs doing. Both Optional and ReadOnly modifiers need implementation, with Optional being particularly relevant to JSONSchema.

Had a couple of attempts at puzzling through it, and recall there might be a need for an additional support type outside of `TBase<T>` to hang `TOptional<TBase<T>>` off. As of this version of, Optional maps to `T | undefined`.

You're welcome to have a try solving it. Any PR would be hugely welcome.

**Comment by sinclairzx81** [comment]
https://github.com/microsoft/TypeScript/issues/24951

**Comment by danbrauer** [comment]
I won't be able to try a PR anytime soon, but thank you for replying and confirming.  --Dan

**Comment by webberwang** [comment]
The issue was closed with any resolution? doesn't seem possible to do

```typescript
interface User {
  name?: string
}
```

We can only do

```typescript
const User = Type.Object({
  name: Type.Optional(Type.String())
})

interface User {
  name?: string | undefined
}
```

**Comment by sinclairzx81** [comment]
@webberwang Hi, This is a very old issue :) 

You can actually configure TypeBox to assert for the following
```typescript
interface User {
  name?: string
}
```
This is configured via the `TypeSystemPolicy.ExactOptionalPropertyTypes` setting.
```typescript
import { TypeSystemPolicy } from '@sinclair/typebox/system'
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'

TypeSystemPolicy.ExactOptionalPropertyTypes = true

const T = Type.Object({
   x: Type.Optional(Type.String())
})

Value.Check(T, { x: 'hello' })    // true
Value.Check(T, { })               // true
Value.Check(T, { x: undefined })  // false
```
If you enable this setting, it's good to enable this for `tsconfig.json` also so TypeScript and TypeBox line up semantically.
```json
{
   "compilerOptions": {
      "exactOptionalPropertyTypes": true
    }
}
```
Just be mindful that this feature is only available if you validate with the Value or TypeCompiler modules. If you use Ajv, then this setting has no effect.

Hope this helps
S

**Comment by webberwang** [comment]
> @webberwang Hi, This is a very old issue :)
> 
> You can actually configure TypeBox to assert for the following
> 
> ```ts
> interface User {
>   name?: string
> }
> ```
> 
> This is configured via the `TypeSystemPolicy.ExactOptionalPropertyTypes` setting.
> 
> ```ts
> import { TypeSystemPolicy } from '@sinclair/typebox/system'
> import { Value } from '@sinclair/typebox/value'
> import { Type } from '@sinclair/typebox'
> 
> TypeSystemPolicy.ExactOptionalPropertyTypes = true
> 
> const T = Type.Object({
>    x: Type.Optional(Type.String())
> })
> 
> Value.Check(T, { x: 'hello' })    // true
> Value.Check(T, { })               // true
> Value.Check(T, { x: undefined })  // false
> ```
> 
> If you enable this setting, it's good to enable this for `tsconfig.json` also so TypeScript and TypeBox line up semantically.
> 
> ```json
> {
>    "compilerOptions": {
>       "exactOptionalPropertyTypes": true
>     }
> }
> ```
> 
> Just be mindful that this feature is only available if you validate with the Value or TypeCompiler modules. If you use Ajv, then this setting has no effect.
> 
> Hope this helps S

Works great thanks! The `tsconfig.json` part did the trick 🙏 I might have missed that in the docs
