### ISSUE TITLE
[feat] Get rid of `namespace XXX {}` 

### ISSUE THREAD

**Issue by loynoir** [sinclairzx81/typebox#401]
This issue is sub issue of https://github.com/sinclairzx81/typebox/issues/399

`TypeRegistry.Entries` is not used at all, but bundled.

Because `namespace XXX {}` is generated to tree-shake unfriendly code.

Related to a long standing issue https://github.com/microsoft/TypeScript/issues/27604

```ts
export namespace TypeRegistry {
  const map = new Map<string, TypeRegistryValidationFunction<any>>()
  export function Entries() {
    return new Map(map)
  }
  export function Clear() {
    return map.clear()
  }
  ...
```

```js
var TypeRegistry;
(function(TypeRegistry2) {
  const map = /* @__PURE__ */ new Map();
  function Entries() {
    return new Map(map);
  }
  TypeRegistry2.Entries = Entries;
  function Clear() {
    return map.clear();
  }
  TypeRegistry2.Clear = Clear;
  ...
})(TypeRegistry || (TypeRegistry = {}));
```

**Comment by loynoir** [comment]
Not sure how much size would decrease if get rid of `namespace XXX {}`.

But it must be a big code change, and takes time.

If I have time to implement such PR, are you willing to get rid of `namespace XXX {}`? @sinclairzx81

**Comment by loynoir** [comment]
@sinclairzx81 

For example,

**Before**

```ts
export namespace TypeRegistry {
  const map = new Map<string, TypeRegistryValidationFunction<any>>()
  export function Entries() {
    return new Map(map)
  }
  export function Clear() {
    return map.clear()
  }
  ...
```

```ts
TypeRegistry.Clear()
```


**After**

```ts
const map = new Map<string, TypeRegistryValidationFunction<any>>()
export function TypeRegistry__Entries() {
  return new Map(map)
}
export function TypeRegistry__Clear() {
  return map.clear()
}
```

```ts
TypeRegistry_Clear()
```

**Comment by sinclairzx81** [comment]
@loynoir Hi,

The namespaces need to stay. They may be turned into isolated modules in later versions, but for now they need to remain as they are (as they are used to organize the module code)

Will close this one off.
