### ISSUE TITLE
codegen improvement

### ISSUE THREAD

**Issue by loynoir** [sinclairzx81/typebox#417]
**Brief**
codegen improvement

**Prev**
https://github.com/sinclairzx81/typebox/issues/396

**Reproduce**

```js
import { TypeCompiler } from "npm:@sinclair/typebox@0.28.7/compiler";
import { Type } from "npm:@sinclair/typebox@0.28.7";

console.log(
  TypeCompiler.Code(
    Type.Object({
      x: Type.String(),
      y: Type.Array(Type.Any(), { minItems: 0, maxItems: 0 }),
    })
  )
);
```

**Actual**

- Unused value in `value.y.every(value => (true))`

- one space + `)`, not aligned to `return (`

```js
return function check(value) {
  return (
    (typeof value === 'object' && value !== null && !Array.isArray(value)) &&
    (typeof value.x === 'string') &&
    Array.isArray(value.y) && value.y.every(value => (true)) &&
    value.y.length >= 0 &&
    value.y.length <= 0
 )
}
```

**Expected**

- No unused value

- two spaces + `)`, aligned to `return (`

```js
return function check(value) {
  return (
    (typeof value === 'object' && value !== null && !Array.isArray(value)) &&
    (typeof value.x === 'string') &&
    Array.isArray(value.y) &&
    value.y.length >= 0 &&
    value.y.length <= 0
  )
}
```

### Additional
```js
    Array.isArray(value.y) &&
    value.y.length === 0
```

**Comment by sinclairzx81** [comment]
@loynoir Hi, thanks for reporting.

Um, I'm not sure this is worth fixing these in the current iteration of the compiler. Note, there are actually plans to re-implement the compiler at some point to support stack variables, function hoisting, for loop iteration, and a couple of other things. Any minor output changes made to this implementation may (or may not) make it across to the newer compiler, so putting effort into refining the current implementation would likely prove a wasted effort.

For now, I'm somewhat keen to keep things relatively "unsophisticated" until I've had a chance to write better infrastructure to support more "type aware" optimizations (for example omitting `.every()` in the `any` and `unknown` case), or forward allocating stack variables to reduce multiple calls to the same function. Keeping things nice and simple is going to help with the implementation of the new compiler.

Also note, minor formatting changes (such as the misaligned `)`) are not necessarily part of the compiler. While the compiler does currently try to produce somewhat well formatted code, it's not actually intended to be a feature (it's more a debugging assist for me). Emitted code written to disk is likely going to be run through end user formatting tools (like `prettier`)  so the preference for formatting is to perhaps omit newlines and spaces entirely in subsequent versions.

There's still plenty of optimizations to do on the compiler! Incidentally, as you seem interested in code generation, you might be interested in https://sinclairzx81.github.io/typebox-workbench/ which is currently a WIP code gen transform library for TypeBox.

Project Link here https://github.com/sinclairzx81/typebox-workbench
Cheers
S

**Comment by sinclairzx81** [comment]
@loynoir Hey, might close this one off as these updates are not likely to be applied to the current compiler, but will consider omitting the `.every()` check for `any` and `unknown` on the next if the updated version continues to use JS array functions (they may be replaced with loops in later revisions)

For the formatting, ill have a look at retaining the current format as best I can. 2-character tab spaced, and try keep things moderately readable.

Will report back on this thread once this work has been carried out.
All the best!
S
