### ISSUE TITLE
Type declarations fail to typecheck in TS 4.7 - 4.8

### ISSUE THREAD

**Issue by Abe27342** [sinclairzx81/typebox#419]
Typebox's index.d.ts file fails to typecheck using typescript 4.7 and 4.8. This causes issues for consumers using these typescript versions with `skipLibCheck: false`.

This issue is a follow-up to the recent discussion on #120 (the original issue is old and fixed, but a different type ends up giving the same ts compiler error).

I've constructed a trivial reproduction of the issue [here](https://github.com/Abe27342/typebox-repro). Instructions:

1. `npm i`
2. `npm run build`

Expected: build succeeds
Actual: build fails with TS2589 due to hitting the type instantiation limit while checking assignability of types in TComposite's declaration:

![image](https://user-images.githubusercontent.com/5222607/235007282-2fa83e52-9406-403e-93db-b8394ffff450.png)

I think @sinclairzx81's suggestion to reproduce the issue on TS playground doesn't work because they don't expose the full set of compiler options, and I'm guessing they skip included library type-checking. In the reproduction above, you can confirm that enabling `skipLibCheck` in tsconfig allows successful compilation.

This issue seems to only reproduce in TS 4.7 and 4.8.

**Comment by sinclairzx81** [comment]
@Abe27342 Hi, thanks for the reproduction. 

Yes, this `TComposite` type continues to be a problem (and is only provided for the purposes of backwards compatibility for the recent `TIntersect` representation change). Under the new model for static types however, the work TS needs to do to resolve `TComposite` correctly is very expensive. 

I will take a look at things over the next few days and see if there's a viable resolution. Failing this I may need to drop the composite type (although my preference would be to retain the type the short term)

Will keep you posted

**Comment by sinclairzx81** [comment]
@Abe27342 Hi, Have pushed an update on `0.28.8` that should resolve this. Have tested on your repro and things should build fine. There are still outstanding issues with this `TComposite` type (which ill need to address in subsequent updates) but this should resolve the immediate type instantiation issues you see on compilation.

Thanks again for the letting me know about this (and the repro), will close off this issue for now, but if you do experience any problems, please let me know and can re-open this thread.

All the best
S

**Comment by Abe27342** [comment]
Excellent, thanks for the fast turnaround!
