### ISSUE TITLE
TSchema from json schema

### ISSUE THREAD

**Issue by russell-dot-js** [sinclairzx81/typebox#429]
Hi @sinclairzx81,

I've seen the example codegens, but I was wondering if there was any plan to support creating a TSchema from json at runtime. I know that TSchema is a valid JSON schema at runtime, but the goal is to go in the opposite direction (for type safety only).

Take the following example:

```
// borrowing JSONSchemaType from ajv, but I'd imagine typebox could expose a type that represents a valid JSON Schema
async function pretendThisIsAnApiThatWasCalledRemotely<T>(payload: unknown, schema: JSONSchemaType<T>) {
  const desiredTypeboxSchema = TSchema.from(schema);

  // this should be T but adding this line here to further exemplify the desired typechecking
  type static = Static<typeof desiredTypeboxSchema>;

  if(!Value.check(desiredTypeboxSchema, payload)) {
    throw 400;
  }
}
```

Obviously, this can all be done with ajv, but considering that Typebox has faster runtime type checking, we'd like to stick with a single library (typebox).

**Comment by sinclairzx81** [comment]
@russell-dot-js Hi, 

This was recently considered on https://github.com/sinclairzx81/typebox/discussions/421, and I do think TypeBox could do a better job here (but probably as an external library at this time as there is room for interpretation for a few types). However, I am very much open to experimentation for runtime type mapping, as well as static inference for raw JSON Schema (with a possible future inclusion of a `Type.From(...)` type), but it needs some thought.

To achieve, it would require preprocessing the JSON Schema into the [Standard Subset](https://github.com/sinclairzx81/typebox#types-standard) supported by TypeBox, Noting that TypeBox only supports a small subset of the specification used to specifically to map to TS type representation. The preprocess step would need to recursively pattern match on the given raw schema, and return a `Type.*` best matching that schematic.

As TypeBox opts for the most "general" schema representation for any given type, mapping convenience schematics (like `enum`) into the TB type representation should be possible. Unsupported representations (such as `oneOf`)  may need some thinking though (or implementation to the compiler, even if the type can't be formally expressed in TS). 

The following is a quick draft implementation if you want to experiment around.

```typescript
import { Type, TProperties, TSchema } from '@sinclair/typebox'

// -------------------------------------------------------------------------
// TypeResolver: Resolves TSchema types from raw JSON Schema
// -------------------------------------------------------------------------

export namespace TypeResolver {
  // -------------------------------------------------------------
  // Guards
  // -------------------------------------------------------------
  type ObjectLike = Record<keyof any, unknown>
  function IsNumber(value: unknown): value is number {
    return typeof value === 'number'
  }
  function IsArray(value: unknown): value is unknown[] {
    return globalThis.Array.isArray(value)
  }
  function IsObject(value: unknown): value is Record<keyof any, unknown> {
    return typeof value === 'object' && value !== null
  }
  // -------------------------------------------------------------
  // Resolvers
  // -------------------------------------------------------------
  function FromAllOf(schema: unknown[]): TSchema {
    return Type.Intersect(schema.map(schema => From(schema)))
  }
  function FromAnyOf(schema: unknown[]): TSchema {
    return Type.Union(schema.map(schema => From(schema)))
  }
  function FromObject(schema: ObjectLike): TSchema {
    const properties = schema.properties ? globalThis.Object.keys(schema.properties).reduce((acc, key) => {
      const property = IsArray(schema.required) && schema.required.includes(key) ? From((schema as any).properties[key]) : Type.Optional(From((schema as any).properties[key]))
      return { ...acc, [key]: property }
    }, {} as TProperties) : {}
    return Type.Object(properties, { ...schema })
  }
  function FromArray(schema: ObjectLike): TSchema {
    if(IsNumber(schema.minItems) && IsNumber(schema.maxItems) && schema.minItems === schema.maxItems && IsArray(schema.items) && schema.items.length === schema.minItems) {
      return Type.Tuple(schema.items.map(schema => From(schema))) // constrained arrays are tuples
    } else {
      return Type.Array(schema.items as any, { ...schema })
    }
  }
  function FromString(schema: ObjectLike): TSchema {
    if(IsArray(schema.enum)) { // special case for string enum (OpenAPI)
      return Type.Union(schema.enum.map(value => Type.Literal(value as string)), { ...schema })
    } else {
      return Type.String({...schema})
    }
  }
  export function From(schema: unknown): TSchema {
    if(!IsObject(schema)) return Type.Never()
    if(IsArray(schema.allOf)) return FromAllOf(schema.allOf)
    if(IsArray(schema.anyOf)) return FromAnyOf(schema.anyOf)
    if(schema.type === 'object') return FromObject(schema)
    if(schema.type === 'array') return FromArray(schema)
    if(schema.type === 'string') return FromString(schema)
    if(schema.type === 'number') return Type.Number({ ...schema })
    if(schema.type === 'boolean') return Type.Boolean({ ...schema })
    if(schema.type === 'integer') return Type.Integer({ ...schema })
    if(schema.type === 'null') return Type.Null({ ...schema })
    return Type.Never()
  }
}
// -------------------------------------------------------------------------
// Examples
// -------------------------------------------------------------------------

// TString
const A = TypeResolver.From({ type: 'string' })

// TNumber
const B = TypeResolver.From({ type: 'number' })

// TBoolean
const C = TypeResolver.From({ type: 'boolean' })

// TUnion<TLiteral[]>
const D = TypeResolver.From({ type: 'string', enum: ['A', 'B']})

// TArray<TString>
const E = TypeResolver.From({ type: 'array', items: { type: 'string' } })

// TTuple<[TString, TNumber]>
const F = TypeResolver.From({ type: 'array', items: [{ type: 'string' }, { type:'number' }], minItems: 2, maxItems: 2 })

// TObject<{ x: TNumber, y: TOptional<TNumber> }>
const G = TypeResolver.From({ 
  type: 'object',
  required: ['x'],
  properties: {
    x: { type: 'number' },
    y: { type: 'number' }
  }
})

// TIntersect<[TObject<{ x: TNumber }>, TObject<{ y: TNumber }>]>
const H = TypeResolver.From({
  allOf: [
    { type: 'object', required: ['x'], properties: { x: { type: 'number' } } },
    { type: 'object', required: ['y'], properties: { y: { type: 'number' } } },
  ]
})

// TUnion<[TObject<{ x: TNumber }>, TObject<{ y: TNumber }>]>
const I = TypeResolver.From({
  anyOf: [
    { type: 'object', required: ['x'], properties: { x: { type: 'number' } } },
    { type: 'object', required: ['y'], properties: { y: { type: 'number' } } },
  ]
})

```
The above is a very quick draft (there may be bugs), but should cover most typical types expressed in raw JSON Schema. 

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@russell-dot-js Heya, going to close off this issue also. For now, parsing into TSchema from raw JSON Schema is a little bit out of scope for TypeBox, but may pick this up at a later time. I think at minimum, the expectation would be that this feature would not only be able to parse the JSON Schema in the subset supported by TypeBox, but also infer the correct type (if possible)

```typescript
// Can infer
const T = Type.From({                                        // const T: TUnion<[TNumber, TString]>
   anyOf: [
    {type: 'number'}, 
    { type: 'string' }
  ]
})

// Can't infer
const T = Type.From(fs.readFileSync('schema.json', 'utf-8')) // const T: TSchema
```
This can partially be achieved today with libraries like `json-schema-to-ts` in tandem with `Type.Unsafe` (if using Ajv), but an integrated solution in TB is would be a fair way off.

Would be open to community experimentation around this feature, with inclusion in as an `example` in the short term. But for now, need to put this on the back burner to pick up at a later date.
All the best
S

**Comment by michaelbuehlmann** [comment]
Have there been any updates on this? This feature would be super nice to have!

**Comment by sinclairzx81** [comment]
@michaelbuehlmann Hi,

I will likely add this feature to TypeBox at some point in the future but am currently pending its inclusion until TypeBox is ready to drop support for TS 4.x. In the meantime, I've included a prototype implementation for the community to experiment with at the following URL.

https://github.com/sinclairzx81/typebox/blob/master/example/prototypes/from-schema.ts

Prototypes are a good way to get involved helping to define new features. For this specific feature though, it's going to be really important to ensure it's able to correctly remap arbitrary schematics into specific TB type schematics. You can test the prototype by copy and pasting this module into your project...

### Usage

The following shows general usage

```typescript
import { Type } from '@sinclair/typebox'

import { FromSchema } from './from-schema'

// ------------------------------------------------------------------
// Parser
// ------------------------------------------------------------------

const T = FromSchema({         // Parses as: TObject<{
  type: 'object',              //   x: TNumber,
  required: ['x', 'y', 'z'],   //   y: TNumber,
  properties: {                //   z: TNumber
     x: { type: 'number' },    // }>
     y: { type: 'number' },
     z: { type: 'number' }
  }
} as const)


// ------------------------------------------------------------------
// Transformations
// ------------------------------------------------------------------

const X = Type.Partial(T)

const Y = Type.Omit(T, ['z']) 

const Z = Type.Mapped(Type.KeyOf(T), K => Type.Union([
  Type.Index(T, K),
  Type.Null()
]))
```

Give FromSchema a try, let me know your thoughts
Cheers!
S

**Comment by michaelbuehlmann** [comment]
Awesome, thanks so much. I'll give it a try and report back!

**Comment by michaelbuehlmann** [comment]
One issue I noticed: defaults for enum types are currently not parsed. I changed
```ts
function FromEnum<T extends SEnum>(T: T): TFromEnum<T> {
    return Type.UnionEvaluated(FromEnumRest(T.enum))
}
```
to
```ts
function FromEnum<T extends SEnum>(T: T): TFromEnum<T> {
    return Type.UnionEvaluated(FromEnumRest(T.enum), T)
}
```
which seems to work well! Thanks again!
