### ISSUE TITLE
custom string formats?

### ISSUE THREAD

**Issue by jcamden** [sinclairzx81/typebox#43]
Hey sinclairzx81,
Thanks for the awesome package. I'm having an issue adding custom string formats. The CustomOptions interface seems to indicate that you had in mind some way to do this, probably using delicious generics, but I was unable to sort it out. I've been basically hacking it with module augmentation:
```
import { CustomOptions } from '@sinclair/typebox';

declare module '@sinclair/typebox' {
  interface CustomOptions {
    format?: 'mongoId' | 'jwt';
  }
}
```
But this is bad. I've been trying to figure out the intended way to use Custom Options, but now I'm hungry and tired. Can you just tell me the answer? Thanks :)

**Comment by sinclairzx81** [comment]
@jcamden Hi, thanks.

You're actually on the right track with respect to augmenting `CustomOptions`. Or at least, this is the current design TypeBox takes to allow for this. I am open to a more generics based approach, and there may be additional options to explore in TS 4.x. 

The following code should work, which is based on the PR submitted here. https://github.com/sinclairzx81/typebox/pull/14

```typescript
import { Type } from '@sinclair/typebox'

declare module '@sinclair/typebox' {
  interface CustomOptions {
    format: 'custom-format-1' | 'custom-format-2';
  }
}

const T = Type.Object({
  foo: Type.String({ format: 'custom-format-1' }),
  bar: Type.String({ format: 'custom-format-2' })
})
```

I'm certainly open to suggestions for a better interface to support extending custom formats. If you have any thoughts, let me know :) 

Cheers
S

**Comment by sinclairzx81** [comment]
@jcamden I've just taken another look at this and made an update that allows you to pass any custom format. The `Type.String(..)` now accepts a generic string type argument for the format. 

```typescript
const S1 = Type.String({ })                                   // ok
const S2 = Type.String{{ format: 'uuid' })                    // ok
const S3 = Type.String<'mongoId'>({ format: 'mongoId' })      // ok
const S4 = Type.String({ format: 'mongoId' })                 // ok - inferred T as <'mongoId'>

type ExtendedFormat = 'mongoId' | 'jwt'
const S5 = Type.String<ExtendedFormat>({ format: 'mongoId' }) // ok
const S6 = Type.String<ExtendedFormat>({ format: 'jwt' })     // ok
const S6 = Type.String<ExtendedFormat>({ format: 'foo' })     // error
```
With this, you should still get editor intellisense for the standard formats while letting you add any additional format you like.

![image](https://user-images.githubusercontent.com/3048342/98853507-95b38380-249c-11eb-8636-d442619385a8.png)

I think this is probably a more intuitive solution than augmenting the module. The main thing I wanted to retain here was editor intellisense over format type safety. This approach lets one constrain the format to a known extended format set if necessary. This seems to be a pretty good middle ground. 

Updates on `0.12.4`. Let me know how you go.
Cheers
S

**Comment by jcamden** [comment]
That is perfect. Thanks very much!
