### ISSUE TITLE
[feat] generation of typebox code from json schema

### ISSUE THREAD

**Issue by jamesrusso** [sinclairzx81/typebox#433]
I'm working on a project where I have data being processed in both python and typescript (seems like a common scenario). I really enjoy TypeBox on the TS side, but I'd like to have some authoritative definition for the underlying data types and it seems like a JOSN scheme would be a good format for that. 

I'd prefer to not have to keep both the TypeBox and Pydantic definitions in sync manually, but it might just be the easiest option. 

Any thought about adding a feature where given a JSON schema, you could generate TypeBox code? This would be similar to 
[the pydantic generator](https://docs.pydantic.dev/latest/datamodel_code_generator/), but for typebox?

**Comment by sinclairzx81** [comment]
@jamesrusso Hi,

The TypeBox library does not support code generation of this kind (as it's primarily focused on schema construction at runtime, not parsing and/or cli code transformation). However, there are some tools being written for offline TypeScript > TypeBox transformation [here](https://sinclairzx81.github.io/typebox-workbench/).  This is an auxiliary side project which may support JSON Schema > TypeBox code generation in future, but probably not for a while.

### Type.From(schema)

There is some [consideration](https://github.com/sinclairzx81/typebox/issues/429#issuecomment-1537098172) as to whether TypeBox should support dynamic loading of JSON Schema at runtime (which would be more attune to the focus of the library). This would probably be added to the library as a experimental feature to start with, and potentially promoted to `Type.From({ ... })`  should the feature prove useful.

```typescript
// current
const T = Type.Unsafe<string>({ type: 'string' })

// proposed
const T = Type.From({ type: 'string' })
```
Hope this brings some insight
Cheers
S

**Comment by xddq** [comment]
@sinclairzx81 
Mhhh, what do you think about me taking a chance to implement this? I feel like it is an interesting topic overall and it might help bridging the gaps.

Typebox does "only" support JSON schema draft 06, that is correct, isn't it? So I guess a decent first limitation would be to only allow this for JSON schemas with the draft 06?

**Comment by sinclairzx81** [comment]
@xddq Hi! 

> Mhhh, what do you think about me taking a chance to implement this? I feel like it is an interesting topic overall and it might help bridging the gaps.

Sure! For code generation (i.e. transforming code at build time), this would need to be implemented as an external project (`jsonschema2typebox`). For `Type.From(...)` mentioned above, there is a preliminary implementation of this on the comment  https://github.com/sinclairzx81/typebox/issues/429#issuecomment-1537098172, but I would hold off on this side of things for the time being (as I have a couple of ideas here which I may be looking into in the short to medium term)

> Typebox does "only" support JSON schema draft 06, that is correct, isn't it? So I guess a decent first limitation would be to only allow this for JSON schemas with the draft 06?

Yeah, TypeBox partially supports draft 2019-09 with `unevaluatedProperties` only, but is generally tied to Draft 6. For code generation, most of the work will be reading in and pattern matching on JSON Schema and producing "best fit" `Type.*` that matches for each schema representation. I anticipate there will be some awkward parts handing references and other constructs, but for more problematic schema representations, you may be able to generate `Type.Unsafe` for those.

If you did want to have a go at implementing a JSON Schema > TypeBox code transform, I could potentially add a ecosystem list to the TypeBox readme (as quite a few users are asking for code generation)

**Comment by jamesrusso** [comment]
@xddq Let me know what I can do help and contribute.  Sounds like a fun project!

**Comment by xddq** [comment]
Sure, I will hit you up! I guess I will spin up a skeleton project and message/invite you then. I don't know if it will do it today, tho.

Would json schema draft 06 be fine for your use case? @jamesrusso 

I think before starting we should also make sure that users wanting this feature are using this spec?🤔

**Comment by jamesrusso** [comment]
I'm sure draft 06 would be fine for my use case.  I don't use anything that exotic. just date and uuid formats on the string and some enums.

**Comment by xddq** [comment]
@jamesrusso Hey!

I did spin up a skeleton project and sent you an invite. I added most of what is needed to "get going", for more please check the README there. It is probably a good idea to create a discussion post in the new repo before doing stuff.

**Comment by xddq** [comment]
@sinclairzx81 Hey!

I am a little lost on the JSON schema -> TypeBox task.
The code can currently parse the types specified by [schema draft-06](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-01#section-4.2) and their schema options accordingly to their corresponding TypeBox types. I still have to do $defs and $refs, but thats no dealbreaker.

However I did not find any mentions about stuff like `anyOf`, `const`, `not` etc.. in the specification. But these are mentioned in the [typebox standard types](https://github.com/sinclairzx81/typebox#standard-types).

Is there a **source of truth** I can look into to implement the JSON schema to TypeBox logic? I thought the schema draft-06 specification would be sufficient. But basing it on this it would lack many of the mentioned "standard types" in the docu?

I did send you an invite if you want to take a look at the current state of the code (perhaps this better reflects my problems?).

Thanks for any help :]

**Comment by sinclairzx81** [comment]
@xddq Heya, accepted the invite (but probably won't be able to contribute much code at this stage), However, I'll give a rundown of the things you mentioned here, but can probably move specific questions into `schema2typebox`.

## Non-Mappable Keywords ($def, oneOf, etc)

TypeBox by default only produces only a subset of the JSON Schema specification (a subset used to match the TypeScript type checker), so you may come across some constructs that do not have a direct mapping to TypeBox types. Examples of this would be `oneOf`, `$def`, `$recursiveAnchor`, etc. 

There's a couple of approaches you can take here. The first is to generate a `Type.Never({ /** non-mappable */ })` which gives an indication to the user that this particular schema cannot be mapped. Alternatively, you can use `Type.Unsafe<unknown>({ ..schema here })` if you detect that part of the schema cannot be mapped (which would provide a unsafe usable mapping, and where the user can implement the generic `<unknown>` argument themselves to capture the semantics of the type.

For `$defs` specifically, as this type is usually used to group related schemas, you could generate the following.

```typescript
const D = { $defs: { Vector4: { ... }, Vector3: { ... }, Vector2: { ... } }


const D = {
   $defs: {
      Vector4: Type.Object({ x: Type.Number(), y: Type.Number(), z: Type.Number(), w: Type.Number() }),
      Vector3: Type.Object({ x: Type.Number(), y: Type.Number(), z: Type.Number() }),
      Vector2: Type.Object({ x: Type.Number(), y: Type.Number() })
   }
} as const

type Vector4 = Static<typeof D['$defs']['Vector4']>
```
## anyOf

The `anyOf` schema maps to `Type.Union()`. Note, TypeBox only has one way to express union types (`anyOf`), so there may be cases where you come across schemas expressed as the following (which would need to be remapped to `Type.Union()`)

```typescript
const T = { type: ['string', 'null'] }

const T = Type.Union([ // remap to `anyOf`
  Type.String(),
  Type.Null()
])
```
## const

A `const` schema will generally map to `Type.Literal()`. These are explicit literal values of `string`, `number`, `boolean`

```typescript
const A = { const: 'hello' }
const B = { const: true }
const C = { const: 42 }

const A = Type.Literal('hello')
const B = Type.Literal(true)
const C = Type.Literal(42)
```
## not

TypeBox does actually support `not` in two places. The first is `Type.Never()` which produces `{ not: {} }`, and the other is `Type.Not(N, T)` which implements type negation (which actually isn't supported in TypeScript). It's unlikely either of these types would be satisfactory for existing schemas, so the recommendation is probably to use `Type.Unsafe<...>({ ... })` for these (but would need to see some specific cases of this)

## Summary

In all, JSON Schema provides fairly unconstrained options for users to define all sorts of archaic data structures (which is sometimes compounded with OpenAPI which extends the specification with things like `nullable`). TypeBox's general approach is to enforce reasonable constraints for the kinds of schematics permissible in the specification (meaning you are likely to come across some existing schematics that don't naturally map into anything). In some cases, `Type.Never()` may be applicable, in others `Type.Unsafe<T>({...})` may be required. The decision to opt for one over the other will have to be a call made in `schema2typebox` (but happy to provide insights and help you make that call if you ping me on issue threads there)

Hope this helps!
S

**Comment by xddq** [comment]
@sinclairzx81 Hey!

Alright. Thanks for the insights on the cases I mentioned. No worries about not contributing, you possibly jumping into discussions/decisions if needed is a great help already!

I probably misphrased my post. My main problem was **what** to implement instead of **how** to implement (your examples will still be helpful to me, thanks!). Because I did not find any mentions of *anyOf, not, const, enum* etc. in the specification draft 06. However, they are specified in the meta schema for draft 06 so I now have the source of truth I was looking for.

**Comment by sinclairzx81** [comment]
@xddq Hey, all good :)

Let's move schema generation discussions over to the https://github.com/xddq/schema2typebox project moving forward. Once the schema generation project is a bit further along, let's drop a link under the ecosystem list. 

Will close up this issue for now
Good work!
S

**Comment by gorbak25** [comment]
@sinclairzx81 Hey! The link to schema2typebox is broken :(

**Comment by xddq** [comment]
The first useable version is released under [schema2typebox npm](https://www.npmjs.com/package/schema2typebox?activeTab=readme) and [schema2typebox github](https://github.com/xddq/schema2typebox)

I hope it can be helpfil :]
