### ISSUE TITLE
Type.Not doesn't check for property existance

### ISSUE THREAD

**Issue by abuaboud** [sinclairzx81/typebox#437]
I've come across an issue, Validation seems to be returning `true` when validating an object that lacks a defined, required property. 

Here's a minimal code snippet that reproduces the issue:

```ts
import { Type } from '@sinclair/typebox'
import { TypeCompiler } from '@sinclair/typebox/compiler'

const nonNullableUnknownPropType = Type.Not(Type.Null(), Type.Undefined())

const propsValidator = TypeCompiler.Compile(Type.Object({
  property: nonNullableUnknownPropType
}))

console.log(propsValidator.Check({}));  // Returns true
```

Version:  0.28.10

In this code, I'm using the `TypeCompiler.Compile` function to create a validator, `propsValidator`, with a schema where 'property' is not allowed to be `null` or `undefined`. However, when validating an empty object, the `propsValidator.Check({})` function call returns `true`, indicating that the empty object is valid per the schema. 

I would expect this to return `false` as the 'property' does not exist in the object. I attempted to wrap `nonNullableUnknownPropType` with `Type.Required`, but the behavior persisted.

Is this the intended behavior of the library or could it be a bug? Any clarification would be greatly appreciated.

Once again, I want to thank you for this exceptional library. It's become the heart of [@activepieces](https://github.com/activepieces/activepieces). Your work is greatly appreciated! <3

**Comment by sinclairzx81** [comment]
@abuaboud Hi! Thank you for the kind words, it's great to hear TypeBox is providing good value! :)

So, had a quick look at this and it was indeed a bug related to `undefined` properties. TypeBox does implement TypeScript's undefined property checks (as well as `exactOptionalPropertyChecks`), but this was not implemented for `Not` or `Intersect` types. I've pushed a fix for this on `0.28.11`. Let me know if this helps!

### Not<N, T>

Just on this comment. 

> In this code, I'm using the TypeCompiler.Compile function to create a validator, propsValidator, with a schema where 'property' is not allowed to be null or undefined.

In the example provided. Just be mindful this type will disallow `null` but allow `undefined`. Note, the Not type consists of two types, the first is the disallowed (or not) type, the second is the allowed type. Consider the following where we disallow for `null` or `undefined`, but allow for every other possible type (so we use unknown for the second type)

```typescript
// Allow all values except null or undefined. 
const T = Type.Not(Type.Union([Type.Null(), Type.Undefined()]), Type.Unknown()) // < infer as unknown

console.log(Value.Check(T, null))        // false
console.log(Value.Check(T, undefined))   // false
console.log(Value.Check(T, 1))           // true
console.log(Value.Check(T, 'hello'))     // true
console.log(Value.Check(T, true))        // true
console.log(Value.Check(T, {}))          // true
console.log(Value.Check(T, []))          // true
```
In typical usage, the left type should be a sub type (or in the set) of the right type (which is true above as null and undefined are of the set of `unknown`). Another example might be the following where we allow for a infinite set of possible string values, but substract (or not) specifically "A" or "B" from the infinite set.

```typescript
const T = Type.Not(Type.Union([
   Type.Literal('A'), // Literal A and B are in the set of type string
   Type.Literal('B'),
]), Type.String())
```

A little bit of extra information about the `Not` type can be found here https://github.com/sinclairzx81/typebox/blob/master/changelog/0.26.0.md#Standard-Type-Not

Hope this helps
S
