### ISSUE TITLE
feature: typed keys

### ISSUE THREAD

**Issue by ShaunSHamilton** [sinclairzx81/typebox#454]
👋 

I am wanting to type something like:

```typescript
const somethingDynamic = "typebox";
{
  user: {
    [somethingDynamic]: {}
  }
}
```

But, it does not seem possible to create a schema for this in TypeBox. Specifically, I would have thought:

```typescript
{
  user: TypeBox.Object({
    [TypeBox.String()]: TypeBox.Object({})
  }
}
```

I do not see a way to do this in the docs, but might just be missing something simple.

**Comment by sinclairzx81** [comment]
@ShaunSHamilton Hi,

You can use a `Record<K, V>` type for this.

```typescript
// TypeScript
type T = Record<string, {}> 

// TypeBox
const T = Type.Record(Type.String(), Type.Object({ }))
```
Note: It's recommended to replace the `Type.Object({ })` (or `V`) value type with something more specific if you know the kinds of values. Alternatively, a `Type.Unknown()` might be a better type to use.

Hope this helps! Will close off this issue for now.
Cheers
S
