### ISSUE TITLE
New version stopped working with Fastify schema validation

### ISSUE THREAD

**Issue by rhlsthrm** [sinclairzx81/typebox#46]
We are using Typebox for our Fastify schema validation. Example:
```ts
server.post<{ Body: NodeParams.RequestSetup }>(
  "/setup",
  { schema: { body: Type.Intersect([...]), response: {
    200: Type.Object({
      ...
    }), 
  } },
  async (request, reply) => {
    ...
  },
);
```

Getting this error on requests now:

```
node:258) UnhandledPromiseRejectionWarning: Error: schema is invalid: data.allOf[0].properties['meta'].properties['kind'] should be object,boolean
    at Ajv.validateSchema (/root/node_modules/ajv/lib/ajv.js:178:16)
    at Ajv._addSchema (/root/node_modules/ajv/lib/ajv.js:307:10)
    at Ajv.compile (/root/node_modules/ajv/lib/ajv.js:113:24)
```

Any idea what is going on?

**Comment by sinclairzx81** [comment]
@rhlsthrm Hi,

TypeBox stores a `kind` `Symbol` property that might be causing you issues. I'm guessing perhaps one of your `Intersect` types uses a `kind` property? I am open to renaming `kind` if this is the case. Can you confirm?

**Comment by rhlsthrm** [comment]
@sinclairzx81 we actually aren't using `kind` anywhere in the types. The one in question is:

```
const BasicChannelServerResponseSchema = {
  200: Type.Object({
    channelAddress: TAddress,
  }),
};
```

This was working before the new version.

**Comment by sinclairzx81** [comment]
@rhlsthrm Hi, There isn't too much information to go on here. Are you able to post the `TAddress` type? Optionally, you could log the schema just to check everything looks ok.

```typescript
console.log(Type.Object({
    channelAddress: TAddress,
}))
```
As far as I can recall, there hasn't been any notable schema changes to `Type.Intersect()` in recent updates, so things should work as expected. There has been some deprecations in v4 however, but these should show up as compiler errors, not ajv validation errors. If you can provide more information (previous version you were on, the full schema, etc) I can take a look this side.

**Comment by rhlsthrm** [comment]
Hi @sinclairzx81, actually I'm looking again and seeing that this isn't related to the Fastify stuff at all. It's coming from param validation within our code. We had a property in our schema called `meta` that was defined like:

```ts
const meta = Type.Object(Type.Any())
```

We changed it to:

```ts
const meta = Type.Any()
```

This is not ideal since we want our validation to ensure that it is an object, but we can work around it for now. Thank you for the help.

**Comment by sinclairzx81** [comment]
@rhlsthrm No problem :) If it's helpful though, perhaps instead of using a `Type.Any()`, you could try..

```typescript
const T = Type.Dict(Type.Any()) 
// T = { [key: string]: any }
```
This makes `T` always be an `object` with a set of arbitrary keys that might not be known in advance. You can narrow the `Type.Any()` down too if you know the expected types for the properties. 
```typescript
const T = Type.Dict(Type.Union([Type.String(), Type.Number()])) 
// T = { [key: string]: number | string }
``` 
The `Type.Dict(...)` type was previously known as `Type.Map(...)`. Was renamed in v4.

Hope this helps
S
