### ISSUE TITLE
How to check the assignment between types?

### ISSUE THREAD

**Issue by ExpandOcean** [sinclairzx81/typebox#464]
Hello, thanks for your great work!
Does typebox support runtime assignment checking between types? If so, how can I do it?
Maybe somthing like TypeChecker.isTypeAssignableTo(T1,T2)?

**Comment by sinclairzx81** [comment]
@ExpandOcean Hi,

It's possible to test for structural assignment using the `.Extends()` type. This type is mostly used for conditional / associative types, but implements the same structural assignability checks as in TypeScript. You can use the result of this check to determine assignability at runtime if you need. Consider the following TypeScript then TypeBox implementations.

### TypeScript

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4FgBQz-IAeAXMiAK4C2ARtADS4HICepFN0uAvrrqJLEQoAQpkYESZKrSgM8BVlI6zx+AF5tpnHDxy4A9PuQBhOCDTJayAM5go5BGHJQ4AG1fNkca9eABzEAgAE2QwAHtkUQB+ZAAKeFdrCABKXDBmAAcUYwBGZABeCwhCSBAg60jkGLtyFFIEpN4cQxMzSqtbe0dnNw8vH39AkPCLGNialLTM7IAmAsri0vLR0Ps65AaUIA)

```typescript
interface A {
    x: number,
    y: number
}

interface B {
    x: number,
    y: number,
    z: number
}

// Can A be structurally assigned to B ? (false)
type C1 = A extends B ? true : false

// Can B be structurally assigned to A ? (true)
type C2 = B extends A ? true : false 
```
### TypeBox

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAWABQw2hGoV4AQTgBeFJwB0AeS4ArDLRgAKBMLgG4vAFwLMigHIBXEFwxRtASgA0+w6lNpz12-afDsR2FRcUk4ACE5MwwVdU0dPSFDI08lHzsHFzcDD2jLGwynVyTDAC9U7wK-IKFA4KFWVjgAYUZqOBk7OEkoKy0rKEZ6elQ4RgoqAHNqDAATOBgICLgAfjhtPCGKDBqxCXhmgEYorxiAUV4YDGpZim0pZwjH08UAGWArwfptGF6d56U70+Qw2Wx2NWEjRabWWXR6fRgAyGIzGE2A0zmCyWMjWPz+u1CBwATCclBcrjc7uFHg88kD7CDflZ-nSPgzvpt6NtHI4gA)

```typescript
import { Type } from '@sinclair/typebox'

const A = Type.Object({
    x: Type.Number(),
    y: Type.Number()
})

const B = Type.Object({
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number()
})

// Can A be structurally assigned to B ? (false)
const C1 = Type.Extends(A, B, Type.Literal(true), Type.Literal(false))

// Can B be structurally assigned to A ? (true)
const C2 = Type.Extends(B, A, Type.Literal(true), Type.Literal(false))
```

Additionally, If you need something a bit more low level, you can use the `TypeExtends` utility. TypeBox's conditional types are built on top of this utility (which handles structural assignability checks). You can use it to write a more specialized function to just return a boolean value (vs having to check the return type expressed as a type)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUGUDGAFhiAIY64ykzD45qYCiAHjBgHYAmAzvehizZduAJQzcArgBt4AXzgAzKBBBwA5AAFuwdvimlgUAPQx+AIwjM1AWABQdjM0iw4pzHACS3AILdtAc3ZSMykMMUkZAB4AGThHIR48IhJyOBE41g5E5AJiMgA+OABeOEpqWhjC+KzuUqoafEiRQoB+VygJDDgALkVSKW4MOzsjACpRlHEYWuAFNLhgWtI-YEDg0NcIOFjRowcnaHgFCV0aCHZPHxW1kIwYjITanOSyHHTq4SS80nyACiletEcFBeiIAJS9Ly+AJBW7haQwGJvQoIOxwdFwbgAd2AMCIvwYAkywgAdIIav9gWCwYg0Rj6fhll1CeThPCZCSAKrsYDnXpQDAwCRQC4wDpdZaXaGrWGhdmIoFpfJ0+noxmDFD8Vk8eUk5Di-mC4Wi8VwSVQ66ysLiBFIpUq1Xq5la4k6m0cgBi-UGhqFIr6AwltQtMPW1oiCuRDtkdhj9ls+HO3HgIgAjMUpZawwT+CTKFAdP5fmC+Jg82LC8WaUYjO1OnZE+xk2kAEwZkMy7OE8sF9hFkuassAOQkIDMGCgVbgNYDgzsQA)

```typescript
import { Type, TSchema, Static, TypeExtends, TypeExtendsResult } from '@sinclair/typebox'

export type IsAssignableResult<L extends TSchema, R extends TSchema> = Static<L> extends Static<R> ? true : false

/** Tests if R is assignable to L */
export function IsAssignable<L extends TSchema, R extends TSchema>(l: L, r: R): IsAssignableResult<L, R> {
    switch(TypeExtends.Extends(l, r)) {
        case TypeExtendsResult.Union: return true as IsAssignableResult<L, R>
        case TypeExtendsResult.True: return true as IsAssignableResult<L, R>
        case TypeExtendsResult.False: return false as IsAssignableResult<L, R>
    }
}

const R1 = IsAssignable(Type.String(), Type.String()) // true
const R2 = IsAssignable(Type.String(), Type.Number()) // false
```
Hope this helps!
S

**Comment by sinclairzx81** [comment]
@ExpandOcean Hi,

Might close off this issue as the above should be enough to test assignability. But feel free to reply on this thread if you have any follow up questions.

Cheers!
S
