### ISSUE TITLE
Possible to have `static` be a Symbol instead?

### ISSUE THREAD

**Issue by chrisui** [sinclairzx81/typebox#468]
Apologies if already discussed - a search revealed nothing relevant. Purely to create a separation between what is "standard" and what is "special" would we be able to use `[Static]` as the property for static inference rather than `.static`?

Ie. from

```ts
export interface TSchema extends SchemaOptions, TKind {
    [Modifier]?: string;
    [Hint]?: string;
    params: unknown[];
    static: unknown;
}
```

to

```ts
export declare const Static: unique symbol;

export interface TSchema extends SchemaOptions, TKind {
    [Modifier]?: string;
    [Hint]?: string;
    params: unknown[];
    [Static]: unknown;
}
```

While I'm here, not quite sure what `params` is referring to and perhaps that could also follow the same pattern?

_Thanks for being responsive on all my issues btw!_

**Comment by sinclairzx81** [comment]
@chrisui Hi!

Yeah, have considered possibly expressing both `static` and `params` as symbols (it's a relatively straight forward update, and might help communicate potentially inaccessible properties), but for now keen to keep on with the `static` and `params` to avoid breaking changes (updating these would be a minor semver, and would need to be sure that symbols are the correct expression of these fields)

Both `static` and `params` are long term properties of `TSchema`, both are phantom properties used to cache type information (used to optimize on inference), but are largely informal in lieu of a convention to express phantom / type associated information. The `static` property is the computed `output` type (some libraries would just call it `output`), the `params` is an accumulated parameter used for recursive type inference (where `params` is derived from the `TThis` in `Type.Recursive`)

I do think they are terrible names, where `static` could be renamed to `output` and `params` possibly renamed to `input` or `deferred` or something. But they've existed for so long, I rarely think about them.

I guess my only reservation about making them symbols is that TB already uses symbols for non-serializable runtime compositing information (specifically, `Kind`, `Modifier` and `Hint`), and that phantom properties do not neatly fit this category (as they are not used in compositing at all). In a perfect world, TS would allow something like the following.

```typescript
interface TSchema {
  hidden static: unknown
  hidden params: unknown[]
}
```
In terms of breaking changes though, I have seen some users obtaining the inferred type using `typeof T.static` (as below), but also take note of the inference requirement when using symbols (one more thing to import)

```typescript
const T = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number(),
})

type T = typeof T.static // same as Static<typeof T>

// which if making a symbol, would be

import { type Infer } from '@sinclair/typebox' // can't reuse Static, so we call the symbol Infer (tbc)

type T = typeof T[Infer] // but this might be a bit awkward.
```
I might look into renaming these fields in later revisions, and might opt for symbols (not really sure), but ideally it would be good if there was a general convention established for runtime type libraries. I believe the author of Zod was considering something (here's a [tweet](https://twitter.com/colinhacks/status/1634284724796661761)), but until there's something more formally accepted by the community, it's hard to justify changing anything :D

Hope that brings a bit of insight!
Cheers
S

**Comment by sinclairzx81** [comment]
@chrisui Hey, might close this one off for now. 

I may revisit this in the next revision , but may also just keep an eye on emerging community conventions for type specific phantom properties like this. Two libraries to keep an eye on would be Zod (as mentioned) and ArkType (which is another emerging library in this space). If there's general agreement on an idealized way to represent these types of properties happening elsewhere, TypeBox will likely adopt in keeping with convention (as well as to assist inference integration with libraries like tRPC).

Will mark the issue with a consideration tag and defer for later review.
All the best!
S
