### ISSUE TITLE
JSON Schema const type

### ISSUE THREAD

**Issue by seangenabe** [sinclairzx81/typebox#47]
JSON schema has a `const` type since draft 6: https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.1.3

While this is "functionally equivalent to an "enum" with a single value," is there any particular reason why this isn't being used?

**Comment by sinclairzx81** [comment]
@seangenabe Hi, no reason in particular other than `enum` is expected to cast the widest net in terms of validators. However, I'd like to standardize on draft 6 (as a minimum requirement for validators). I am happy to accept PR's if you prefer to see `const` used over `enum` in the places where it's applicable.

Ill leave this issue open for the time being.
Cheers
S

**Comment by sinclairzx81** [comment]
Will close off this issue. For the time being keeping on with `enum` should be fine as it's largely identical to the singular `const`, but may review again in future. Thanks for letting me know.

**Comment by wyozi** [comment]
Hello again :)

I have a usecase where I believe this would be required. I'm trying to build a type that can accept any of given disjoint unions:

```ts
const ItemAddedEvent = Type.Object({
  name: Type.Const('item.added'),
  // ...
})

const ItemModifiedEvent = Type.Object({
  name: Type.Const('item.modified'),
  // ...
})

const Event = Type.Union([
  ItemAddedEvent,
  ItemModifiedEvent
])

type X = Static<typeof Event>
// should be { name: 'item.added' } | { name: 'item.modified' }
```

Is there a way to achieve this currently or does this need const?

**Comment by sinclairzx81** [comment]
@wyozi Hi, You can achieve this using `Type.Literal(...)`. Example [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUFJIR2LeAEkYGEAEEAJpoyaAogDcM7eAF4UwgHQB5EQCsMJGAAoEUuHHYEQGAFwXMSwAZYFUoAi5nBlC1SwJtXQYASix3OHidTX80QPwoDgBzZySpchLZeUU4FTUAWQhNYCpgXUNjMwCMG3tHFzcPLx9sqxCwiKiYkEsQBqaWzWTUjxnG5t1h3Jh89iKSspk5BXg2kzhzHK6AVXZgeWcAbTSajQT9IxMl6tUQetX5k5gUgAuuUqABXTjEeRwO4Yd4wfz4IikAA8QkwECocABAD4kog0h4WAB3UIkAAWzjh7Usgww+P6HiZHhIBBYGEYkzirwY-kOLAgXC6XAgRWpJm5mSSAG44CIoBgCABraWE5lwVnsznfaazNYLPmVQXC0VU+G6v66GVyhXK1XM8ilIA) and below

```typescript
import { Type, Static } from '@sinclair/typebox'

const ItemAddedEvent = Type.Object({
  name: Type.Literal('item.added'),
  added: Type.String()
})

const ItemModifiedEvent = Type.Object({
  name: Type.Literal('item.modified'),
  modified: Type.String()
})

const Event = Type.Union([
  ItemAddedEvent,
  ItemModifiedEvent
])

function on(event: Static<typeof Event>) {
    switch(event.name) {
        case 'item.added': console.log(event.added); break;
        case 'item.modified': console.log(event.modified); break;
    }
}
```

Hope this helps
