### ISSUE TITLE
Template literals don't work as documented

### ISSUE THREAD

**Issue by cmcnicholas** [sinclairzx81/typebox#472]
I have tried to implement the template literals as described in the documentation https://github.com/sinclairzx81/typebox#template-literal-types

but the typings are either incorrect or the documentation is wrong here (see image), it expects a `TTemplateLiteralKind`

![image](https://github.com/sinclairzx81/typebox/assets/41394833/0b9bcfec-535c-4387-bd9c-d636bb1f09fd)

Version: `0.28.5`

**Comment by sinclairzx81** [comment]
@cmcnicholas Hi,

The TemplateLiteral DSL syntax was only added on `0.28.9`.  If you update TypeBox you will be able to use this functionality.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZ-fnAC0K1WvUbNW7avmLkGcDxgYAMsBNQCXOAEEAJvYz24EdimEAhCXAAMAOgAmAA5-Xz1lHSjomKVZWRI3FnhbOABeD0x-AyMiMwsMKy4ACgBtWThMjH9zS2tihn5IZIYASiwKqv98KA4Ac2L2zrQs2sL6xoBXFkK2jplKkeqAOUmQEULB2QBdVviZIUw7dLxCYhIAHkOMCCo7AD59hUjY17e4mWecsGN8upsACK4Ux2RzOVzuJbecR+IKhACcEXeyJi+0S7GSKBOS2yhh+eTGRQaTQgyX4ABIEMleuw+uR+NNChSEOw1hsoOQ2vtrliMvgiKQrsJbih7kA)

```typescript
import { Type, Static } from '@sinclair/typebox'

// ------------------------------------------------
// TemplateLiteral Added on TypeBox 0.28.0
// ------------------------------------------------

const A = Type.TemplateLiteral([
  Type.Literal('/post'),
  Type.String(),
  Type.Literal('/user'),
  Type.Number()
])

type A = Static<typeof A>

// ------------------------------------------------
// TemplateLiteral DSL Added on TypeBox 0.28.9
// ------------------------------------------------

const T = Type.TemplateLiteral('/post/${string}/user/${number}')

type T = Static<typeof T>
```
Note: TypeBox supports both variations, with the DSL useful for quick patterns, and the former useful for compositing template literals from existing / exterior types.

Hope this helps
S

**Comment by sinclairzx81** [comment]
@cmcnicholas Will close off this issue as the string DSL syntax is available on the latest versions of TypeBox.

If you have any follow up questions, please feel free to reply on this thread.

Cheers
S
