### ISSUE TITLE
Value.Check , Unknown string format 'uuid'

### ISSUE THREAD

**Issue by liaddrori1** [sinclairzx81/typebox#475]
I'm trying to use Value.check and Value.Errors to validate Schema. 

I'm getting this error 
"Unknown string format 'uuid'" 

I used the Type.String('uuid') in my schema.

I saw a way to add those formats into Ajv. 
But I'm trying to use the Value.Check and not Ajv

**Comment by sinclairzx81** [comment]
@liaddrori1 Hi,

TypeBox doesn't implement any formats by default, but you can add them using the following (which makes them available to the compiler and value modules)

```typescript
import { Type, FormatRegistry } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// Implement Format Registry Function
FormatRegistry.Set('uuid', (value) => /^(?:urn:uuid:)?[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$/i.test(value))
//                   ^
//                   |
//                   +------------+ // format should match registered name
//                                |
const T = Type.String({ format: 'uuid' }) 

const R = Value.Check(T, '628d5f7e-56ca-4c66-a722-5e124ad833a6') // rfc4122 format

console.log(R)
```
A set of common formats (essentially those in `ajv-formats`) can be found [here](https://github.com/sinclairzx81/typebox/blob/master/example/formats/standard.ts) (from which the uuid pattern above was lifted). You will need to setup the formats you need for your application, or copy/paste the linked module into your project and `import` it to configure them.

Hope this helps!
S

**Comment by liaddrori1** [comment]
Tnx
