### ISSUE TITLE
Type `examples` as the `Static` type

### ISSUE THREAD

**Issue by Jazcash** [sinclairzx81/typebox#477]
Currently `examples` is typed as `any`. Is there a reason this couldn't be typed with `Array<Static<typeof schema>>`?

**Comment by sinclairzx81** [comment]
@Jazcash Hi

Which examples are you referring to?

**Comment by Jazcash** [comment]
> Which examples are you referring to?

The `examples` property of `SchemaOptions`

**Comment by sinclairzx81** [comment]
@Jazcash Oh, 

Both the `examples` and `default` properties technically could be `Static<T>` but I treat them as `any` as the specification doesn't mandate that the values match the expected type (although in practice they probably should match, it's just that I can't force it as a strict type here as users may need more flexibility (mostly as these properties are used with auxiliary tooling, code generation, value generation, documentation, etc)). 

To be honest, I can't see a reason why these properties are defined as `any` and not typed as `unknown`. I might actually update them in the next revision.

**Comment by sinclairzx81** [comment]
@Jazcash Hi,

> It'd be cool if it were possible to override the type on a per project basis using declare or something, for people who are aware the type isn't strictly adhering to the spec, but they accept that risk in exchange for the typing benefits.

Yeah, these properties are difficult to type as they could technically be anything, including things like.

```typescript
// Assumes the tooling is able to invoke functions where `default` is `() => Static<T>`.
const Time = Type.Integer({ default: () => Date.now() })
```
... and where global module augmentation via `declare` is a bit too far reaching. I'll give this some more thought for later revisions (I do think things could be done a bit better here), but will retain the `any` type for these revisions and update to `unknown` on the next minor semver (as the change from `any` to `unknown` is technically a breaking change). Will check the feasibility of making properties generic in revisions following that.

Will close this issue for now, but mark as `future` + `enhancement` and pick this up down the road.

### Value Generation

Just on json-schema-faker, you might be able to use TypeBox's  `Value.Create()` to generate type safe data. Most of the schemas use reasonable defaults, but you can override the default by specifying the `default` property (not `examples`)

```typescript
import { Value } from '@sinclair/typebox'

const T= Type.Object({
  x: Type.Number(),
  y: Type.Number({ default: 123 }),
})

const V = Value.Create(T) // { x: 0, y: 123 }
```
This function returns deterministic data (so not random selections from examples), but could potentially look at adding this functionality in at a later time. Just thought I'd mention this.

Thanks for the insights!
All the best!
S
