### ISSUE TITLE
ValueErrorType is mismatch

### ISSUE THREAD

**Issue by mlazuardy** [sinclairzx81/typebox#478]
Im trying to use `ValueErrorType` for my custom message formatting condition, on Number type, it looks like the Enum inside ValueErrorType is not matching with the `error.type`

`ValueErrorType.NumberMinumum` return `33` while `error.type` return 34 ( maximum )

and also take a note that it looks like NumberMinumum is typo

**Comment by sinclairzx81** [comment]
@mlazuardy Hi, thanks for reporting!

Hmm, that looks like a typo to me. I'll push a fix for this shortly.

**Comment by mlazuardy** [comment]
@sinclairzx81 sure!
