### ISSUE TITLE
Typescript 5.1.6: Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by p-kuen** [sinclairzx81/typebox#484]
Similar as stated in #119 the same error occurs with Typescript version 5.1.6:

```
node_modules/.pnpm/@sinclair+typebox@0.28.20/node_modules/@sinclair/typebox/typebox.d.ts:179:167 - error TS2589: Type instantiation is excessively deep and possibly infinite.

179 ] extends [TArray, TNumber] ? AssertType<T['items']> : K extends TTemplateLiteral ? TIndexReduce<T, TTemplateLiteralKeyRest<K>> : K extends TUnion<TLiteral<Key>[]> ? TIndexReduce<T, TUnionLiteralKeyRest<K>> : K extends TLiteral<Key> ? TIndexReduce<T, [K['const']]> : TNever;
                                                                                                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/.pnpm/@sinclair+typebox@0.28.20/node_modules/@sinclair/typebox/typebox.d.ts:179
```

I tested it on Typescript version 5.1.5 and it works, so it's just the difference in these two patch versions. (see https://github.com/microsoft/TypeScript/compare/v5.1.5...release-5.1).

Maybe it's a bug in the TypeScript version but as the problem already occurred with this package some time ago, I thought I will report it here.

**Comment by sinclairzx81** [comment]
@p-kuen Hi, thanks for the heads up. Will investigate.

**Comment by sinclairzx81** [comment]
@p-kuen Heya,

Have a patch for this that should be ready on TB `0.29.0` (so minor semver). Will look to publish this within the next 24 hours or so (as there is some other changes due to roll through on this revision). Will notify when TB has been published with the fix.

Thanks again for reporting!

**Comment by sinclairzx81** [comment]
@p-kuen Hi,

This patch should be applied on `0.29.0`. If you can just give things a quick test your side, can close up this issue. Again, thanks for reporting the issue so promptly (was actually good timing given the revision going out). 

I still don't know if this was a bug in the compiler or intended functionality, but ended up being a breaking change in inference behavior on a semver PATCH revision (5.1.3 -> 5.1.6). Generally these issues lead to better / faster inference in TB, but sorta wish there was a way of being notified of potential breaking changes prior to compiler publishing on npm, I may do some looking into.

All the best!
S

**Comment by p-kuen** [comment]
Hi, thanks for the quick fixes.
Unfortunately I am using typebox through the @fastify/type-provider-typebox package which is currently bound to 0.28.x versions.
So I have to wait until an update from this package until I can test it in my environment.
I will give an update after I checked it again.

Thanks again!

**Comment by knicola** [comment]
confirming 0.29.x fixes the issue

**Comment by sinclairzx81** [comment]
@knicola Hi, thanks for confirming!

@p-kuen May close off this issue for now as the issue appears resolved and the type provider may take some time to update. Note the Fastify organization manages this provider, so to help fast track things, just open and issue or submit a PR to bump the `peerDependency` there. Can CC me on that repository if there's any issues with the update.

Thanks all!

**Comment by p-kuen** [comment]
Alright, thanks for the hint! I created a PR in fastify/fastify-type-provider-typebox#90.

**Comment by SimenB** [comment]
> sorta wish there was a system of being notified of potential breaking compiler changes prior to TS publishing on npm, I may do some looking into.

They publish [nightlies](https://www.npmjs.com/package/typescript?activeTab=versions), so one thing you _could_ do is set up a cron job in this repo to at least run your tests. Might catch these before release?

**Comment by sinclairzx81** [comment]
@SimenB Hi! That's a great idea! :)

Have just setup a GH Action to run a build against TS `latest` and `next` once daily. Was also looking into [typescript-error-deltas](https://github.com/microsoft/typescript-error-deltas) the other day where I think TS track regressions their side across a number of community packages. I may see if they'll accept a PR to include TB in their test suite. Could probably add quite a few type mapping libraries to their tests as these kinds of libraries do tend to push out the extents of the compiler.

Thanks again for the suggestion!
All the best
S

**Comment by jessekrubin** [comment]
@sinclairzx81 Love it when my build fails and there's already a fixed version!
