### ISSUE TITLE
NullKind is not defined

### ISSUE THREAD

**Issue by msinton** [sinclairzx81/typebox#49]
For version 0.12.7

Having a schema that includes Null(), e.g.

```
const schema = Type.Union([
  Type.Null(), 
  Type.string()
])
```

And calling my api that contains this schema, I get the error:
`NullKind is not defined`

Downgrading to `0.10.1` resolves the problem.

**Comment by sinclairzx81** [comment]
@msinton Hi, Just a quick question, are you using `fast-json-stringify`? The `NullKind` Symbol is defined in TypeBox, but some serializers use code `eval()` which loses track of the type. The `NullKind` Symbol was added in recent versions and has caused problems with serializers that `eval()`. 

Let me know.

**Comment by msinton** [comment]
Hi @sinclairzx81 
Yes, we have `fast-json-stringify` pulled in as a dependency of `fastify`

**Comment by sinclairzx81** [comment]
@msinton I have gotten a quite a few issues like this over the past few months. Recently I have made a few PR's on the `fast-json-stringify` project to resolve these issues as they are not resolvable in TypeBox. See the following PR which fixes a few issues (specifically the Symbol not found errors that occur in the evaluated stringify code).

https://github.com/fastify/fast-json-stringify/pull/272 
https://github.com/fastify/fast-json-stringify/pull/280
https://github.com/fastify/fast-json-stringify/pull/282
https://github.com/fastify/fast-json-stringify/pull/283

I believe these updates were published to npm `fast-json-stringify@2.4.1`, but Fastify is still pulling minor version `fast-json-stringify@^2.2.1`. As an option, you could try pulling the latest `fast-json-stringify` dependency, or file an issue on the `fastify` project asking them to update to the latest `fast-json-stringify` version. 

Feel free to link back to this issue.
Hope this helps!
S

**Comment by sinclairzx81** [comment]
@msinton See referenced issue on the `fastify` project. Will close off this issue once they've responded.

Thanks for letting me know.
S

**Comment by mcollina** [comment]
> I believe these updates were published to npm fast-json-stringify@2.4.1, but Fastify is still pulling minor version fast-json-stringify@^2.2.1. As an option, you could try pulling the latest fast-json-stringify dependency, or file an issue on the fastify project asking them to update to the latest fast-json-stringify version.

This is not correct, a fresh install of fastify will pull v2.4.1 correctly. Otherwise you can always update your dependency tree using `npm update --depth 9999` to update your dependency tree and pull the latest fast-json-stringify if you installed prior to that. I highly recommend you to either disable lockfiles or use dependabot/snyk/renovate to keep your dependencies up-to-date.

**Comment by sinclairzx81** [comment]
@mcollina Thanks! Will close off this issue :)

**Comment by msinton** [comment]
Thank you both @sinclairzx81 @mcolina
