### ISSUE TITLE
Add this project to the JSON Schema implementations page

### ISSUE THREAD

**Issue by gregsdennis** [sinclairzx81/typebox#491]
The [JSON Schema implementations page](https://json-schema.org/implementations.html) lists a lot of implementations that provide a variety of services.  I think this project is pretty unique among them in that it doesn't _generate_ a schema, but it provides a nice interface for users to _declare_ a schema.

I think it would be a good idea to list this project on the implementations page.  If you'd like to do that, we invite you to [submit a PR](https://github.com/json-schema-org/json-schema-org.github.io/pulls) ([example](https://github.com/json-schema-org/json-schema-org.github.io/pull/516)).

**Comment by sinclairzx81** [comment]
@gregsdennis Hi! Thank you for the invitation! :) Will try and take a look at submitting a PR later this week. 

All the best!
S

**Comment by sinclairzx81** [comment]
@gregsdennis Hey, sorry for the delay on this. I might close up this issue for now though, but will submit to the implementations page once I've taken a look at 2020 tuples (as per https://github.com/sinclairzx81/typebox/issues/490), will mark as a `todo` for now and revisit in the near future.

Thanks again for the invite! :)
All the best
S
