### ISSUE TITLE
[feat] runtime detectable union scenario

### ISSUE THREAD

**Issue by loynoir** [sinclairzx81/typebox#493]
### Problem

Below is a very simple reproduce, split from nested object with union type.

Given N scenarios, need to check about N+1 to 2N times.

`Type.RegEx(/ComplexA0/)` maybe replace with anything else, like `Type.String()`

```typescript
const schemaBefore = Type.Union([
    Type.Unsafe<OpaqueComplexA0>(Type.RegEx(/ComplexA0/)),
    Type.Unsafe<OpaqueComplexA1>(Type.RegEx(/ComplexA1/)),
    Type.Unsafe<OpaqueComplexA2>(Type.RegEx(/ComplexA2/)),
    Type.Unsafe<OpaqueComplexA3>(Type.RegEx(/ComplexA3/))
])

if (check(schemaBefore, val)) {
    if (typedRegexTest<OpaqueComplexA0>(/ComplexA0/, val)) {
        // val type safe: OpaqueComplexA0
    }

    if (typedRegexTest<OpaqueComplexA1>(/ComplexA1/, val)) {
        // val type safe: OpaqueComplexA1
    }

    if (typedRegexTest<OpaqueComplexA2>(/ComplexA2/, val)) {
        // val type safe: OpaqueComplexA2
    }

    if (typedRegexTest<OpaqueComplexA3>(/ComplexA3/, val)) {
        // val type safe: OpaqueComplexA3
    }
}
```

### Feat

Given N scenarios, need to check about N times.

Consider typescript, the scenario value should be `unique symbol`, else I think not safe to infer correct type.

```typescript
const schemaAfter = Type.Union([
    Type.Unsafe<OpaqueComplexA0>(Type.RegEx(/ComplexA0/, { scenario: SComplexA0 })),
    Type.Unsafe<OpaqueComplexA1>(Type.RegEx(/ComplexA1/, { scenario: SComplexA1 })),
    Type.Unsafe<OpaqueComplexA2>(Type.RegEx(/ComplexA2/, { scenario: SComplexA2 })),
    Type.Unsafe<OpaqueComplexA3>(Type.RegEx(/ComplexA3/, { scenario: SComplexA3 }))
])

const ctx = check(schemaAfter, val)
if (ctx.ok) {
    if (ctx.scenario(SComplexA0)) {
        // val type safe: OpaqueComplexA0
    }

    if (ctx.scenario(SComplexA1)) {
        // val type safe: OpaqueComplexA1
    }

    if (ctx.scenario(SComplexA2)) {
        // val type safe: OpaqueComplexA2
    }

    if (ctx.scenario(SComplexA3)) {
        // val type safe: OpaqueComplexA3
    }
}
```

**Comment by sinclairzx81** [comment]
@loynoir Hi,

I'm not sure I follow. For the given union example, there would be a maximum of 4 checks (one per regex). Also as you've shown, you can hint at the expected inference type (which would need to be tested and narrowed upon successful validation)

```typescript
import { Type, Static } from '@sinclair/typebox'

const T = Type.Union([
  Type.Unsafe<'a0'>(Type.RegEx(/a0/)),
  Type.Unsafe<'a1'>(Type.RegEx(/a1/)),
  Type.Unsafe<'a2'>(Type.RegEx(/a2/)),
  Type.Unsafe<'a3'>(Type.RegEx(/a3/))
])

function test(value: Static<typeof T>) {
  switch (value) { // ...switch handles the narrowing
    case 'a0': return 0
    case 'a1': return 1
    case 'a2': return 2
    case 'a3': return 3
  }
}
```
Alternative, you can reduce to a single check using something like the following (although you would move those 4 checks to the regex evaluator)

```typescript
import { Type, Static } from '@sinclair/typebox'

const T = Type.TemplateLiteral('${a0|a1|a2|a3}')  // const T = { 
                                                  //   type: 'string',
                                                  //   pattern: '^(a0|a1|a2|a3)$',
                                                  // }

function test(value: Static<typeof T>) {
  switch (value) { // ...would still need to narrow
    case 'a0': return 0
    case 'a1': return 1
    case 'a2': return 2
    case 'a3': return 3
  }
}
```
Is this what you mean?

**Comment by loynoir** [comment]
@sinclairzx81 

No, I mean something not literal.

Actually, it would be nice to able to capture regexp groups.

And I think `checker/validator` are just a boolean type optimised parser.

**Comment by sinclairzx81** [comment]
@loynoir Ah, I see what you mean.

This is an interesting idea, but let me have a think about it. Branded types have come up in the past (of which I've been unable to implement), but representing them at runtime properties for `RegEx` specifically could be interesting (especially as this type was recently moved from `Standard` to `Extended` (which gives it a bit more room to maneuver). I might not be able to do the `unique symbol` (as symbols don't serialize) but other string metadata might.

I'll give this some more thought

**Comment by sinclairzx81** [comment]
@loynoir Heya,

Going to close this as I don't think this will be feasible to implement. While it would be possible to encode additional brand information into a Regex schema, TypeBox handles union cases generically (so it would need special handling just for Regex, or require non-standard branded keywords to be permissible for all types, which I'm not prepared to do)

I think this case is interesting, but generally too niche to be supported in the library. TypeBox however does support `Type.TemplateLiteral` which works the same as the TypeScript feature and can narrow for finite expressions (so is type safe as TS can reason about the template literal) so the recommendation would be to use that, or restructure your schematic to avoid validating multiple regex expression through Union (as all Regex types evaluate purely as `string` so cannot trivially be narrowed without TS support for RegexPattern inference)

All the best!
S
