### ISSUE TITLE
[feat] `zod.instanceof(Error)`

### ISSUE THREAD

**Issue by loynoir** [sinclairzx81/typebox#494]
```ts
// Argument of type 'ErrorConstructor' is not assignable to parameter of type 'TConstructor<any[], any>'.
// Type 'ErrorConstructor' is missing the following properties from type 'TConstructor<any[], any>': 
// static, type, instanceOf, parameters, and 3 more.

Type.InstanceType(Error)
```

**Comment by sinclairzx81** [comment]
@loynoir Heya

The `Type.InstanceType` expects arguments of `TConstructor`. It mirrors the TS utility type [here](https://www.typescriptlang.org/docs/handbook/utility-types.html#instancetypetype).

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUFJIR2LeAGE4AXhTCAdEvmKoAVxIxoACgDaAXRxpMmgPIiAVhiMmEUuJ7jiAXBtsAcvogIhhQJgCUWB5eqH42GJpBIWGR0V5wAF7xWsmh4RFS5BGFsrrwyGr+iQCSCoScGAkmSqVCmChV+ESkADztGBBUKAB8Gfz8cAOd6u4Z8wuLixNevnDswfkA3DFLe-srnnHrm2E7+xdLh1l+GylQ55dPXivkQA)

```typescript
import { Type, Static } from '@sinclair/typebox'

const C = Type.Constructor([], Type.Object({
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number()
}))

const T = Type.InstanceType(C)

type T = Static<typeof T>    // type T = {
                             //   x: number;
                             //   y: number;
                             //   z: number;
                             // }
```

### z.instanceof

Unfortunately, TypeBox can't implement the `z.instanceof(T)` function as it only supports types that can be expressed / encoded in schema form, and types like `Type.InstanceOf(Blob)` do not have a formal way to express them in schematics. TB does make some exceptions for `UInt8Array`, `BigInt` and `Date` schematics as they can be encoded using `cbor` / `msgpack` (as well as handling encoding of the values themselves). But that's the extent of types currently planned for Extended support in TB (for now)

You can however write a custom type to check for `instanceof` if you need.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYGVUGcYYhwC+cAZlBEQOQACuwAdgMYA2AhsFAPQzoYAjCAA9uuPARDUAUKEixEcAGrtWAVwwlylGvSZtOPPpiGiAbqo0y50eEjSYtFKnDoMWHLr36mZ05hCM+HAAolCUUA6aALwo-Dj4hAB0UQA8YREAfAAU1BnQUdQANHDZAPolFuoYAJRw0ZlwVRpwTPjsLBgQZKHh0DXS-oHByPVxmEkA8gIAVhjMMNkI0nCrcBh9UABcvRFR2QPEA0NB8ABKAIxjKtVJAMIAFvMA1tnIJctr65s7jBgA7rtoLkOt8ItRDscAqc4GcAEzXSwYe5PZivd6IFZrDYRHbURgQeCgnHQGRHQbQ3AQVjI1gQADm2UuJXhdW43DgMCgLTIqlwGEG0iAA)

```typescript
import { TypeSystem } from '@sinclair/typebox/system'
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'

const ErrorType = TypeSystem.Type<Error>('ErrorType', (_, value) => value instanceof Error)

const T = Type.Object({
    error: ErrorType()
})

const R1 = Value.Check(T, {
    error: new Error('an error')
})

const R2 = Value.Check(T, {
    error: 'not an error'
})

console.log(R1, R2) // true false
```
Hope this helps
S

**Comment by loynoir** [comment]
@sinclairzx81 

Are `Value.Check` and `TypeCompiler.Compile().Check` the same thing?

**Comment by sinclairzx81** [comment]
> Are Value.Check and TypeCompiler.Compile().Check the same thing?

The `Value.Check` is dynamic / interpreted checking (relatively slow performance), `TypeCompiler` is JIT compiled (fast). Both support custom types, however note the `TypeCompiler` will call out to the callback function provided on `ErrorType` (in the example) when it needs to check this type (so it uses the slow path for custom types specifically)

I'll be looking at ways to support JIT compiled custom validation in later revisions
