### ISSUE TITLE
[feat] zod schema transform parse

### ISSUE THREAD

**Issue by loynoir** [sinclairzx81/typebox#495]
```ts
const schema = z.string().trim();

schema.parse(' x ')
// 'x'
```

Maybe to solution to https://github.com/sinclairzx81/typebox/issues/493

**Comment by loynoir** [comment]
Would be nice to have something like below within typebox.

```ts
const schema = z
  .union({
    ax: z.string().regex(aregx).transform_regex_groups().brand<{ ay: AOpaque }>(),
    bx: z.string().regex(bregx).transform_regex_groups().brand<{ by: BOpaque }>()
  })
  .transform_union_scenario()

type expected = { scenario: 'ax'; value: { ay: AOpaque } } | { scenario: 'bx'; value: { by: BOpaque } }
const parsed: expected = schema.parse(val)
```

**Comment by sinclairzx81** [comment]
@loynoir Heya,

Unfortunately, I can't support chained functions on the schematics (as they pure metadata and should contain no functions). This is actually one of the nicer features of Zod, and I'm still looking for good options to express this under the constraints of TB.

Currently there are discussions happening on https://github.com/sinclairzx81/typebox/issues/343 which partially relate to this functionality (so will close off this issue as a partial duplicate), but very much open to API design proposals. I'm somewhat interested in the `io-ts` design as their combinators are a bit closer to TypeBox, but still need a proposal that provides similar functionality without direct modification of the schematics (or augmenting a schema with functions). It's a difficult design problem.

Can discuss more on 343
Cheers!
