### ISSUE TITLE
Is there a way to make `additionalProperties` false by default?

### ISSUE THREAD

**Issue by MatanYadaev** [sinclairzx81/typebox#497]
I read this GH issue https://github.com/sinclairzx81/typebox/issues/82 and I understand the design decision, but in my project, I need to disallow additional properties. Adding it to every object is tedious, messy, and honestly, I'm sure me and my team will forget to add it many times. It makes sense to us to make it false by default.

Is there a workaround to make it?

**Comment by sinclairzx81** [comment]
@MatanYadaev 

> Currently, I managed to do it using this extended Type, but I'm pretty sure that are other types and side effects I didn't take into account, for example Type.Record / Type.Intersect.

TypeBox will omit the `additionalProperties` constraints on objects composed via `Type.Composite`, but you can implement a function (as you have in your example), to apply `additionalProperties: false` based on rules you define (for example, you may wish to apply the `additionalProperties`  constraint over IF all objects have this constraint). These rules can vary on a case to case basis; so TB tries not to take an opinionated view, but the code you have in your example is the correct way to approach implement those rules. 

You're on the right track :)
