### ISSUE TITLE
[Q] Is there a way to express "property A is Optional if property B is set" and viceversa?

### ISSUE THREAD

**Issue by AntonioAngelino** [sinclairzx81/typebox#498]
I need to validate the following JSON objects. Both properties "A" and "B" cannot be optional simultaneously. If "A" is undefined, then "B" must be set to pass the checks (and vice-versa).

```json
{ 
"a": "This is valid",
"c": "test",
"d": 123
}
```
```json
{ 
"b": "This is valid",
"c": "test",
"d": 123
}
```

```json
{ 
"a": "This is valid...",
"b": "...too",
"c": "test",
"d": 123
}
```

```json
{ 
"c": "Invalid!!!",
"d": 123
}
```

Is there a way of doing it with TypeBox? Thank you.

**Comment by sinclairzx81** [comment]
@AntonioAngelino Hi, might close up this issue.

Will be looking to implement `if/then/else` in subsequent updates to the Compiler (which are due for an update), may also take a look at `dependentRequired` as part of that work also, however I don't expect updates to be done before September, so for now, do recommend Ajv for these kinds of conditional schematics.

> Also, with the previous example, just note you can also replace `Type.Not(Type.Any())` with `Type.Never()` which is semantically the same (and may read a little clearer)

```typescript
const T = Type.Object({                   // this schema must pass
  a: Type.Optional(Type.String()),
  b: Type.Optional(Type.String()),
  c: Type.Optional(Type.String()),
  d: Type.Optional(Type.Number())
}, {
  if: Type.Object({                       // but if this schema passes (allowing c, d only)
    c: Type.Optional(Type.String()),
    d: Type.Optional(Type.Number())
  }, { additionalProperties: false }),
  then: Type.Never(),                     // then never
})
```
If you have any follow up questions, feel free to reply on this thread.
All the best!
S
