### ISSUE TITLE
[Q] What's the best way to extend a schema?

### ISSUE THREAD

**Issue by AntonioAngelino** [sinclairzx81/typebox#499]
Hi there,

What's the best way to create "abstract" typebox schemas that can be extended?

I have complex JSON objects to validate, but most of them are just a variation of the basic ones.

I also have to mix them with ajv as suggested by @sinclairzx81 ( https://github.com/sinclairzx81/typebox/issues/498 ).

Any hint? Thank you 🙏

**Comment by sinclairzx81** [comment]
@AntonioAngelino Heya,

Take a look at `Type.Intersect` or `Type.Composite`. These types allow you to compose multiple schemas together.

```typescript
const A = Type.Object({ a: Type.Number() })
const B = Type.Object({ b: Type.Number() })
const C = Type.Object({ c: Type.Number() })

const T = Type.Composite([A, B, C]) // type T = { a: number, b: number, c: number }
```
Both `Type.Intersect` and `Type.Composite` can be used to express extend / derived schematics.

```typescript
const Base = Type.Object({
  // base type properties here
})

const Derived = Type.Intersect([Base, Type.Object({
   // derived / extended properties here.
})])
```
Hope this helps
S

**Comment by AntonioAngelino** [comment]
Thank you @sinclairzx81 !

**Comment by sinclairzx81** [comment]
@AntonioAngelino All good :) 

Will close off this issue for now.

Cheers
S
