### ISSUE TITLE
lose types when exporting

### ISSUE THREAD

**Issue by bitlab-code** [sinclairzx81/typebox#50]
Hi,
there is an issue when export the types (may be with `Type.Union`)

consider the following
**module-a**
```Typescript
import { Type, Static } from "@sinclair/typebox";

export const roleSchema = Type.Union([
  Type.Literal("ADMIN"),
  Type.Literal("MEMBER"),
]);
export const permissionSchema = Type.Union([
  Type.Literal("SUPERADMIN"),
  Type.Literal("CONTROLPANEL_ACCESS"),
]);
export const userSchema = Type.Object({
  uid: Type.String(),
  email: Type.String(),
  role: roleSchema,
  permissions: Type.Array(permissionSchema),
});

export type User = Static<typeof userSchema>
```
Inside `module-a` everything work fine, in fact 
```Typescript
type User = {} & {} & {} & {
    uid: string;
    email: string;
    role: "ADMIN" | "MEMBER";
    permissions: StaticArray<TUnion<[TLiteral<"SUPERADMIN">, TLiteral<"CONTROLPANEL_ACCESS">]>>;
}
```

The issue is when we import the types into another module

**module-b**
```Typescript
import { User } from "module-a"
// we lose types
type User = {} & {} & {} & {
    uid: string;
    email: string;
    role: any;
    permissions: StaticArray<TUnion<TSchema[]>>;
}
```

**Comment by sinclairzx81** [comment]
@bitlab-code Hi. Have tested this locally and can't seem to reproduce the issue.

![screenshot](https://user-images.githubusercontent.com/3048342/107376514-547b5000-6b2d-11eb-9e4a-7606e1a5bd9f.png)

Just verify you're on TypeScript version 4.1.x and that `"strict": true` is enabled. Locally I'm running TypeScript `4.1.3` for the language service in vscode. This should be working ok. Note: TypeBox makes use of recent variadic generics on the Union and Intersect types as well as leaning on the recent recursion limits that were bumped in latest versions of the compiler.

Hope this helps, let me know how you go. 
S

**Comment by bitlab-code** [comment]
Hi @sinclairzx81 , I'm running Typescript `4.1.3`.
I have not explained the problem well, I meant when you import into another library.
_My case_:
I have a library with all the configs and I've imported this library (as dependence in `package.json`) into various relative projects (web app, mobile app, server side)

**Comment by sinclairzx81** [comment]
@bitlab-code Hi, still having some problems reproducing this issue. See below screenshot shows a compiled `test-module` which contains the original `User` type and schemas along with associated `.d.ts` file. The `src/index.ts` file imports `test-module` from `node_modules`. 

![screenshot](https://user-images.githubusercontent.com/3048342/107467687-eb85ed80-6ba9-11eb-8d8c-457b8f58f6c2.png)

The contents of the files in the `test-module` package are listed below. You can try and copy and paste these into a `node_modules/test-module` directory and see if that works. The code below was compiled with `$ tsc test-module/index.ts --declaration`. The `package.json` was manually created.

#### package.json
```json
{
    "main": "index.js",
    "types": "index.d.ts"
}
```
#### index.js
```javascript
"use strict";
exports.__esModule = true;
exports.userSchema = exports.permissionSchema = exports.roleSchema = void 0;
var typebox_1 = require("@sinclair/typebox");
exports.roleSchema = typebox_1.Type.Union([
    typebox_1.Type.Literal("ADMIN"),
    typebox_1.Type.Literal("MEMBER"),
]);
exports.permissionSchema = typebox_1.Type.Union([
    typebox_1.Type.Literal("SUPERADMIN"),
    typebox_1.Type.Literal("CONTROLPANEL_ACCESS"),
]);
exports.userSchema = typebox_1.Type.Object({
    uid: typebox_1.Type.String(),
    email: typebox_1.Type.String(),
    role: exports.roleSchema,
    permissions: typebox_1.Type.Array(exports.permissionSchema)
});
```
#### index.d.ts
```typescript
import { Static } from "@sinclair/typebox";
export declare const roleSchema: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ADMIN">, import("@sinclair/typebox").TLiteral<"MEMBER">]>;
export declare const permissionSchema: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"SUPERADMIN">, import("@sinclair/typebox").TLiteral<"CONTROLPANEL_ACCESS">]>;
export declare const userSchema: import("@sinclair/typebox").TObject<{
    uid: import("@sinclair/typebox").TString;
    email: import("@sinclair/typebox").TString;
    role: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ADMIN">, import("@sinclair/typebox").TLiteral<"MEMBER">]>;
    permissions: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"SUPERADMIN">, import("@sinclair/typebox").TLiteral<"CONTROLPANEL_ACCESS">]>>;
}>;
export declare type User = Static<typeof userSchema>;
```
Let me know if that works for you
Cheers
S

**Comment by bitlab-code** [comment]
thank you very much @sinclairzx81 for your time and for the code posted,
it helped me understand that I have to look for the problem elsewhere.

I use `tsdx` for typescript package development and building generate the follow .d.ts:
```TypeScript
import { Static } from "@sinclair/typebox";
export declare const roleSchema: import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TSchema[]>;
export declare const permissionSchema: import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TSchema[]>;
export declare const userSchema: import("@sinclair/typebox").TObject<{
    uid: import("@sinclair/typebox").TString;
    email: import("@sinclair/typebox").TString;
    role: import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TSchema[]>;
    permissions: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TSchema[]>>;
}>;
export declare type User = Static<typeof userSchema>;
```

while building manually, with the `tsc ./src/index.ts --declaration`, as in your example... generate a correct .d.ts file:
```TypeScript
import { Static } from "@sinclair/typebox";
export declare const roleSchema: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ADMIN">, import("@sinclair/typebox").TLiteral<"MEMBER">]>;
export declare const permissionSchema: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"SUPERADMIN">, import("@sinclair/typebox").TLiteral<"CONTROLPANEL_ACCESS">]>;
export declare const userSchema: import("@sinclair/typebox").TObject<{
    uid: import("@sinclair/typebox").TString;
    email: import("@sinclair/typebox").TString;
    role: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ADMIN">, import("@sinclair/typebox").TLiteral<"MEMBER">]>;
    permissions: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"SUPERADMIN">, import("@sinclair/typebox").TLiteral<"CONTROLPANEL_ACCESS">]>>;
}>;
export declare type User = Static<typeof userSchema>;
```

may be something in my `tsconfig.json` is wrong (`tsdx build` = `tsc -p tsconfig.json`)

Thank you very much, I think we can close this issue, `TypeBox` has nothing to do with it

**Comment by sinclairzx81** [comment]
@bitlab-code Hi, No problem :) Just had a quick look at `tsdx` and it appears they are using TypeScript `3.7.3` which is missing quite a few necessary features (mainly tuple variadics) that emerged in TypeScript `4.1.x` and that TypeBox depends upon. This would explain why the `TSchema` expansion isn't working correctly. Can check the `tsdx` dependencies here https://github.com/formium/tsdx/blob/master/package.json#L99

You can try submit a issue to the `tsdx` repository and see if they are able to bump the compiler version to 4.1.x. That should resolve the issue. Good Luck! :)
S
