### ISSUE TITLE
[feature request]: Method for clearing all named formats

### ISSUE THREAD

**Issue by jtlapp** [sinclairzx81/typebox#503]
I'm trying to port several test suites from jest to vitest. Unfortunately, it seems that vitest does not have the exact equivalent of jest's `--runInBand` feature, which both runs files sequentially and isolates their modules.

As a result, TypeBox gives me many errors of the form:

`Error: Duplicate string format 'MULTI_LINE_UNICODE' detected`

It would be nice to have a method that clears out all named formats without having to specify the names, so I could run this method before each test.

I suspect this isn't a common problem because DIJ is all the rage, so it's common to register with an object rather than a module.

**Comment by jtlapp** [comment]
Well, I did finally find a configuration of vitest that would do that job, so I'm not in deed of this feature, at least under present circumstances.

**Comment by sinclairzx81** [comment]
@jtlapp Hi,

It's actually possible do this through the `TypeRegistry` and `FormatRegistry` namespaces.

```typescript
import { TypeRegistry, FormatRegistry } from '@sinclair/typebox'

FormatRegistry.Clear() // clears all custom formats
TypeRegistry.Clear()   // clears all custom types
```
The `TypeSystem` module interacts with these registries, but only provides an "ergonomic-ish" API to handle custom type and format creation (and it needs a bit of work). However, calling the `.Clear()` methods directly will erase everything in the registry.

Hope this helps!
S

**Comment by jtlapp** [comment]
Oh perfect! You're quite the forward thinker. Thanks!

**Comment by jtlapp** [comment]
My vitest configuration wasn't doing the job after all, so I tried your code above. It works for the formats, but I do have one custom type. The effect of putting all three lines at the top of each test module is it eliminate my duplicate format errors and to never allow a custom type to be defined. I'm not sure what's going on, but I'll need to look into eliminating my custom type.

**Comment by jtlapp** [comment]
Oh wait. I instead moved the following lines to the top of the file that declared the custom types, and now things work.

```ts
import { TypeSystem } from "@sinclair/typebox/system";
TypeRegistry.Clear(); // clears all custom types
```

**Comment by jtlapp** [comment]
It's also permanently clearing formats, only with formats I haven't been able to figure out a workaround.

**Comment by jtlapp** [comment]
Things would be a lot easier if TypeBox didn't error on duplicate formats or custom types, or if there were a way for me to suppress the error.

**Comment by jtlapp** [comment]
Okay, I have my workaround for duplicate formats:

```ts
export function MultiLineUnicodeString(options?: StringOptions) {
  ignoreDuplicates(() =>
    TypeSystem.Format("MULTI_LINE_UNICODE", (v) =>
      MULTI_LINE_UNICODE_REGEX.test(v)
    )
  );
  return Type.String({ ...options, format: "MULTI_LINE_UNICODE" });
}

function ignoreDuplicates(defineType: () => void) {
  try {
    defineType();
  } catch (e: any) {
    if (e.message.includes("Duplicate")) return;
    throw e;
  }
}
```

**Comment by sinclairzx81** [comment]
@jtlapp Heya, 

If it's easier you can just go straight to the `FormatRegistry` to register the format also, the registries do not throw on duplicate rather they just overwrite the previous format if specified.

```typescript
FormatRegistry.Set('uppercase', value => value.toUpperCase() === value)

// is equivalent to

TypeSystem.Format('uppercase', value => value.toUpperCase() === value)
```
The same is true for the `TypeRegistry` where sometimes it's easier to use that if you need more fine level control, particularly for generic custom types (see the prototype [typedef](https://github.com/sinclairzx81/typebox/blob/master/example/typedef/typedef.ts#L187-L199) example of how the TypeRegistry is used for those cases)

I haven't actually used vitest so can't provide too much information there, however the TypeSystem should import as singleton (as it's a module). So so long as the call to register the format is executed once (typically somewhere at the start of a program / test program), things should be ok.

Again, hope this helps :)
Cheers
S

**Comment by jtlapp** [comment]
That worked perfectly and is much cleaner. Thank you.

You seriously do think of everything.
