### ISSUE TITLE
How to use Typebox with JSON Schema draft 6 keyword contains

### ISSUE THREAD

**Issue by Yukimotochern** [sinclairzx81/typebox#505]
https://json-schema.org/draft-06/json-schema-validation.html#rfc.section.6.14
I see from the doc that Typebox is supporting json schema draft 6 but can not find how to use the `contains` keyword. Any idea how to implement?

**Comment by sinclairzx81** [comment]
@Yukimotochern Hi,

You can pass the `contains` keyword on the options for `Type.Array`, but just be mindful that you will need to use either Ajv or other JSON Schema validator to validate them (as TypeBox currently doesn't implement assertions for this keyword).

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAWABQoSLDgBBAFYA3fIWIlGswUOGtWcRlCiNUcEAFcK8ABaMZWDPQwgM1eLQgPm1GgHM4GYDFMYocACMADRwAExw0HAAzMJO1CYocAC8KJwAdBI6egAUaJjpAHKGIFz+OQCUoQjCcHDxMK4UAFxpBQCqbs45ANq1dW0Y6QAyPv6M9DmBVf11+UOjMOOTYTNCA4MjY7qT0RX9ALr7QtjHcc6JynKp1BgA7pKylecJ8ABKgSlasukyE8AAE0YSzyoR6IXCoWioQALEcNgMNHAYFBDBgXok3hFUldfv8gSDkGCIWEofCERskSi0Rj3tEvri-vRAcCMKC4ODQmFyRSEVTUeihPFMTCGT8mSzCcTQgB2Hm8xGaamC4XvACsYpkeOZBLZRI5coqCoVSLwEwogoxEBs6XoEHcOQ+oSxzuhcDeMOdaoqQA)

```typescript
import Ajv from 'ajv'

// array must have element containing either 1, 2 or 3
const T = Type.Array(Type.Number(), {
  contains: Type.Union([
    Type.Literal(1),
    Type.Literal(2),
    Type.Literal(3)
  ])
})

const ajv = new Ajv()
const R1 = ajv.validate(T, [1, 2, 3, 4])       // true
const R2 = ajv.validate(T, [1, 2, 3])          // true
const R3 = ajv.validate(T, [1, 2])             // true
const R4 = ajv.validate(T, [1, 7])             // true
const R5 = ajv.validate(T, [7])                // false

console.log(R1, R2, R3, R4, R5)
```
The above option passing will work for `minContains` and `maxContains` keywords also. I'll look at implementing validation support (both TypeCompiler and Value) in the next minor revision.

**Comment by sinclairzx81** [comment]
@Yukimotochern Hiya,

Will close this issue off for now, but will take a look at implementing validation for `contains` in the next revision. As per suggestion above, have a look at using Ajv for validation in the interim.

All the best!
S
