### ISSUE TITLE
Read other properties value

### ISSUE THREAD

**Issue by mlazuardy** [sinclairzx81/typebox#507]
is there anyway to read other properties value within especially when using `Typesystem`?
in this case i want to create validation for `password confirmation` which the field need to read the `password` field value

**Comment by sinclairzx81** [comment]
@mlazuardy Hi,

You can pass options for the custom type into the `TypeSystem.Type` method. These are passed as generic arguments. The first argument is the inference type (i.e. `Credential`), the second argument is any options used to when validating the type (i.e. `CredentialOptions`)

The following example implements a Credential type that passes both inference and options types.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYGVUGcYYhwC+cAZlBEQOQACuwAdgMYA2AhsFAPQzoYAjCAA9uuPARDUAsAChQkWIhT8S5SjXpM2nHn0xDhM2XO7c4AWivWbtu-YeOnp8wGEoGACYZGMYO1YVTBdLJzDwiIc5DGFFeCYCKDJ2Zgw4dy8fPwCAeTA-CEZcRDk4OABXXAxXQrIuEAAuOCEIVgx2RjliaNjoeN8MJJS0jO9ff0CEUrgwdlxcAHdoTyb8KCYAc2nmWvqAflWYdcYt2W7ZHaL4UayJuABeIOwJQgA6NEwAHhvxgIAadIeMbZVh5ApFAB8AApqD8QdQAVCIPlgIVcACAG4BcoYACUDwhJVkZWAZChAEIofoMBAyHAsawcQ97o9qBABAArDDMGDUOAAMn59OxaXJLLgjHKrFYuPxHhg5SgjHIASqcGmpIpMNm8yWUE8fKYwsZaUFcGptONONeOsWy2ZrLWm2osrg8sVyuSrCqGrJyPBuFelWquygIHxU2JZTgmsp1EudTDhuVDKZZotdNTGFeCfqDrg1CdJxdcowCqVKu9GGmZTM5uAYCaqAg5TguAAFi3WJ56yBNm32GQ0hgAI7lVXmiAzQZkaBEAKBZhA24BODMdvcgDWgbbGDSrCYm+aGFYEAWNbgZgvdfbMBgYFwDTMjAg3g5gegG247DAwG4S-QGAIFeW8QFYABiAD8ggPw+xOXBBz3McAnYCwBGvbgL1jKEsxtOY7X1fNcNzMNXXdCsvTVOtPEKah4GDAsWXuPlyWmc4ynI5UjhxLpcTkEJIkEoTnFkOsAFUEI2atRPMYS5Pkiw5AUPplAANRFNQKCoAstBYDguF4fhDG4LNjDkS58DgAAxOcHieV4ck5bkYChSMyiXTJflYJo4QmVyKiqGpGETRpzSgJliD4s4oos+AACUAEY7PUk1XlcDdmE3KEbLDAE3LXZcvKafKyltPUVgLMrlgRC8SNC6gqv1YwynOSLzLReKACZkpFNKMqynKQDy7ZCpBYqL0aiqGvw8qaqjdzQ3qybOuakheP4i40VabNTw2KFEoBOLOvxOtuLSSiMCAA)

```typescript
import { TypeSystem } from '@sinclair/typebox/system'
import { Type } from '@sinclair/typebox'

// -------------------------------------------------------
// Credential Type
// -------------------------------------------------------
export interface CredentialOptions {
  useConfirm: boolean
}
export interface Credential {
  password: string
  confirm?: string
}
const Credential = TypeSystem.Type<Credential, CredentialOptions>('Credential', (options, value) => {
  if(!(typeof value === 'object' && value !== null)) return false 
  if(!('password' in value && typeof value.password === 'string')) return false
  if(options.useConfirm) {
    if(!('confirm' in value && typeof value.confirm === 'string')) return false
    // tip: you should timing safe equals to perform all credential checks. see link below
    //
    // https://nodejs.org/api/crypto.html#cryptotimingsafeequala-b
    //
    if(!(value.password === value.confirm)) return false // don't use '===' !
  }
  return true
})

// -------------------------------------------------------
// Usage
// -------------------------------------------------------
import { Value } from '@sinclair/typebox/value'

const Form = Type.Object({
  credential: Credential({ useConfirm: true })
})
const R1 = Value.Check(Form, {
  credential: {
    password: 'password',
    confirm: 'password'
  }
})
const R2 = Value.Check(Form, {
  credential: {
    password: 'password',
    confirm: 'password2'
  }
})

console.log(R1, R2) // true false
```
Hope this helps
S

**Comment by sinclairzx81** [comment]
@mlazuardy Hi, might close off this issue. 

If you have any follow up questions on the implementation above, or need to additional functionality from custom types, feel free to ping a reply on this thread.

All the best!
S

**Comment by mlazuardy** [comment]
@sinclairzx81 thank you! i think i have planed to use that technique but what i mean is accessing other properties value on the same level / child props within Type.Object as we usually use Type.Object as a form validation

**Comment by carere** [comment]
@sinclairzx81 I have the same question as @mlazuardy , I used Zod & Validbot, and I decided to use Typebox since Elysia is using Typebox, but I have some tought time understanding this specific option.
I also need to verify "confirm password" flow with TypeBox. I thought there was an API like superRefine from Zod or rawCheck from Valibot, but it seems that I need to use the way you propose here.
Unfortunatly, I don't want to propose the `useConfirm` option, nor create a nested object for storing password & confirm.

I just want to check if the two value are equal and I want it handled by the Form:
```ts
const Credential = TypeSystem.Type<Credential>("Credential", (_, value) => {
  if (!value) return false;
  if (typeof value !== "object") return false;
  if (!("password" in value && typeof value.password === "string")) return false;
  if (!("confirm" in value && typeof value.confirm === "string")) return false;
  return value.password === value.confirm;
});

export const resetPasswordSchema = Type.Object({
  password: Type.String({
    minLength: 12,
  }),
  confirmPassword: Type.String({
    minLength: 12,
  }),
});
```

How can I combine the two in order to have a flawless API to work with ?

Thx
