### ISSUE TITLE
Usage with latest ajv leads to "unknown keyword kind"

### ISSUE THREAD

**Issue by kimmobrunfeldt** [sinclairzx81/typebox#51]
ajv has released a new strict mode https://github.com/ajv-validator/ajv/blob/master/docs/strict-mode.md#strict-mode, and the example in the readme doesn't work. One should turn off the strict mode:

```typescript
  const validate = new Ajv({ strict: "log" }).compile(PostSchema);

  const postData = {
    title: data.title,
    createdAt: data.createdAt,
    slug: data.slug,
    tags: data.tags,
    description: data.description,
    path: `/posts/${data.slug}`,
  };

  const isValid = validate(postData);
  if (!isValid) {
    console.error(validate.errors);
    throw new Error(`Invalid data found for post`);
  }
```

**Comment by sinclairzx81** [comment]
@kimmobrunfeldt Hi, thanks for letting me know about this.

Currently TypeBox uses the `kind` property to differentiate between structurally similar schemas (for example `{ }` could mean `any` or `unknown` when mapped), so TypeBox uses the `kind` Symbols to conditionally map in these cases. As a work around you can try something like the following where `JSON.stringify(...)` will omit the `kind` Symbol properties.

```typescript
// should omit the 'kind' property from the schema. 
const validate = new Ajv({ strict: "log" }).compile(JSON.parse(JSON.stringify(PostSchema)));
```
Or as mentioned, disabling strict mode in Ajv would also work. (but personally I like the idea of a strict mode for schemas)

I might take another look at this, it would be nice to remove the `kind` property entirely and still have things resolve. I'll leave this issue open for the time being.

**Comment by sinclairzx81** [comment]
Just as a follow up, the following is the TypeScript behavior for structurally similar types. It illustrates why there is a currently need for the `kind` property to discriminate on the type when mapping. Link [here](https://www.typescriptlang.org/play?#code/PTAEGUBcCcFcGNK2gQwDZoJ6gM4EsBbPNFaUSTABwFMcA6AKAYptABUBVAOwGsuB7AO5dQAXlABvUAF9mVauwCCXbKDVjJMpiFAcc1MgBNqAMzxdqh8vNAAKWLwHCAlExYKAwrByR+BDZyOQlzaYADqCtQAHjSI7OT8oNC0-GgAbgq+oAAGDnzBAOSgABYG1AA0oABGsJDV1PAo3p7evv54OKAMOj5wiMjoWLiExKQJOWzKmNnkpUkp6ZbWrB2gBSgqBXQQiZCl3WA85laU0Pw00BQl1GiUnWzy4PDQeJR1hngmJmVckHgokEycxQlFO5xeAMy8gOoHMs1oCka+nobhsbA0Xh8flA0UBXEM9ymoAA-KANtgAFygPJOLhAA).

```typescript
// Structurally similar types.

type TUnknown = { }
type TAny     = { }

// User defined type (unknown)

type Custom = TUnknown

// We expect T to resolve to `unknown' here, but because Custom is 
// structurally similar to `TAny` the resolved type is 'any'. So the
// kind property helps TypeScript differentiate the appropriate type
// in these cases.

type T = Custom extends TAny ? any : unknown
```
One possible solution for the `kind` property may be to turn it into a sort of `phantom` property that tricks TypeScript into thinking the property exists (allowing the type to be discriminated), but is deleted from the underlying schema object (avoiding the need to `stringify/parse` the schema before use when using `strict` mode).

As a side note, the Rust language has a `std::marker::PhantomData` type that can be used for strangely similar scenarios (primarily for resolving type T when using generics where T doesn't necessarily exist on the struct and where the type system can't infer the type through usage). So the introduction of some kind of phantom type wouldn't be too unheard of, it just raises the question as to whether something like this makes sense in TypeScript.

https://doc.rust-lang.org/std/marker/struct.PhantomData.html

I'm open to thoughts and suggestions on this.

**Comment by sinclairzx81** [comment]
@kimmobrunfeldt I have just pushed an update on `@sinclair/typebox@0.12.8` that adds a `Type.Strict()` function that strips out the non-strict properties on the schema. I've flagged the function as experimental (as its simply doing the `stringify/parse` approach as mentioned). But does give you an option for working with strict mode in the API itself. I've updated the documentation around this [here](https://github.com/sinclairzx81/typebox#strict). Note the type resolution should work as before.

```typescript
const T = Type.Strict(Type.Object({
   name: Type.String()
}))

type T = Static<typeof T> // { name: string }
```

I don't think I'll be able to remove the `kind` properties from the underlying schemas, and there is also a `modifier` symbol that wouldn't be valid in strict mode either. I think `Type.Strict()` is a reasonable middle ground. But let me know how you go.

Will leave this issue open for the time being.
S

**Comment by patdx** [comment]
I just noticed this update to typebox library. The idea to strip the extra properties seems nice and offering strict mode seems handy. For what it's worth, I believe I had already gotten TypeBox working with Ajv v7 under strict mode like so:

```ts
import Ajv from 'ajv';

const ajv = new Ajv({
  allErrors: true,
});

//  support TypeBox in Ajv 7
ajv.addKeyword('kind');
ajv.addKeyword('modifier');
```

If you decided to explore the phantom types idea more, this sounds similar to the [`Opaque type` concept](https://github.com/sindresorhus/type-fest/blob/main/source/opaque.d.ts).

Also, it looks like the `modifier` is evaluated at runtime? If that idea were to be explored more, I wonder if modifier data could be [stored in a WeakMap](https://modernweb.com/private-variables-in-javascript-with-es6-weakmaps/). However I think that would break copying like `const newObject = { ...oldObject }`. Anyways, I am happy with the solutions already available.

**Comment by sinclairzx81** [comment]
@patdx Hi, thanks for the suggestions and for the work around for Ajv 7. If it's ok with you, I may change the readmes validation section to include your example given Ajv now defaults to strict mode. I think configuring AJV to support these properties gives people some additional options to pick from when setting up schema validation, so it's most appreciated :) 

So at this stage, I've flagged the `Type.Strict(...)` as experimental so will see how it goes. To be honest, I'm not too happy that TypeBox schemas can't feed directly into Ajv without configuration (even if minimal), so I may revisit things like `WeakMap` for the modifiers and phantom types down the road.

I'm actually really open to feedback around this. Both `WeakMap` and phantom types are totally possible, but I have some reservation about the phantom types being navigatable properties to the user as well as the need to coerce pretty much every type to have non-existent properties (still a requirement for TS conditional mapping). Somehow having `kind` and `modifier` be clear and present seems the lesser of two evils. Hmmm.

Anyway, things to think about :) Thanks again!
S

**Comment by patdx** [comment]
Hi @sinclairzx81, yeah of course, feel free to re-use that snippet of code however you wish. FYI, the `  allErrors: true,` line should be unrelated.

> Somehow having kind and modifier be clear and present seems the lesser of two evils

Yeah, it's tricky...I'm tempted to agree that it's better to keep it simple too.

But, for what it's worth, I was introduced to this project through Fastify and have just been using it for simple schema verification. (And it's working great, thank you very much 🙏 ) So I don't think those kinds of changes would have any great effect on me.

Also, since Fastify users do not usually initialize Ajv directly, it may be helpful to have a default mode that works for them with no extra changes? I just checked, and it looks like Fastify is still using Ajv v6 by default and [planning to upgrade to v7 soon](https://github.com/fastify/fastify/issues/2742), which would activate the strict mode.

**Comment by sinclairzx81** [comment]
Thanks for the heads up on this guys. 

Have just moved the project specs over to Ajv 7 and updated the documentation with @patdx's recommendation for getting Ajv 7 configured for TypeBox. Have additionally included the available string formats that the Ajv team have moved into a separate package `ajv-formats` in case that's useful.

Have moved a bit of documentation around with `Type.Strict()` given it's own section of the readme and details a bit about why `kind` and `modifier` properties are required. Still going to flag `Type.Strict()` as experimental, but feel its good to give people options (Although I think @patdx 's configuration of Ajv is likely the best avenue for projects).

Will close off this issue for now
Many Thanks :)
S
