### ISSUE TITLE
String `format` not working, how to use default values, AOT Schema compilation

### ISSUE THREAD

**Issue by oliverfunk** [sinclairzx81/typebox#524]
I have three questions/issues.

I need a way to do a performant runtime schema validation and output the correct type (object), including default values.

I wrote a helper method that nearly does this:

```js
const tbValidator = <S extends TSchema>(schema: S) => {
  return (value: unknown) => {
    if (Value.Check(schema, value)) return value;
    throw new SchemaValidationError(Value.Errors(schema, value)); // prints .First() nicely
  };
};
```

Say I have the following:
```js
import { Type as t } from "@sinclair/typebox";

const foo = t.Object({
  a: t.String({ minLength: 1 }),
  b: t.Number({ minimum: 1, default: 10 }),
  c: t.Object({
    d: t.String(),
    e: t.Number({ minimum: 1, default: 10 }),
  }),
});

const fooValidator = tbValidator(foo);

const testA = { a: "a", b: 1, c: { d: "", e: 1 } };
const testB = { a: "a", c: { d: "" } };
const testC = { a: 1, c: { d: "", e: 1 } };

console.log(fooValidator(testA)); // pass: { a: 'a', b: 1, c: { d: '', e: 1 } }
console.log(fooValidator(testB)); // fails, would like the output to be { a: 'a', b: 10, c: { d: '', e: 10 } }
console.log(fooValidator(testC)); // should fail because 'a' is not a string (only, not because b is also missing)
```

I'm pretty sure I could get something to work by hacking around with `Value.Cast` or `Value.Convert` but I wanted to know what the recommended approach is?
How do I go from some `unknown` to an object with validated data, including default values (for fields not present in the input)?

The next thing is this code fails:

```js
const eml = t.String({ format: "email" });
const emlValidator = tbValidator(eml);
console.log(emlValidator("foo@bar.com"));
```

With the following:
```js
{
  "type": 52,
  "schema": {
    "format": "email",
    "type": "string"
  },
  "path": "",
  "value": "foo@bar.com",
  "message": "Unknown string format 'email'"
}
```

This fails for any format from `StringFormatOption` I pass in.

Do I need to register the format somewhere?

I see in the tests a `createAjv` function is used:
```js
export function createAjv(references: AnySchema[]) {
  return addFormats(new Ajv({}), ['date-time', 'time', 'date', 'email', 'hostname', 'ipv4', 'ipv6', 'uri', 'uri-reference', 'uuid', 'uri-template', 'json-pointer', 'relative-json-pointer', 'regex'])
    .addKeyword({ type: 'object', keyword: 'instanceOf', validate: schemaOf })
    .addKeyword({ type: 'null', keyword: 'typeOf', validate: schemaOf })
    .addKeyword('exclusiveMinimumTimestamp')
    .addKeyword('exclusiveMaximumTimestamp')
    .addKeyword('minimumTimestamp')
    .addKeyword('maximumTimestamp')
    .addKeyword('minByteLength')
    .addKeyword('maxByteLength')
    .addSchema(references)
}
```
But why can't the internal `Value.Check` function do this? Why do you need to use Ajv?

Finally, is there some way to do an AOT compilation of a schema, save it to a file and then use that file during runtime schema validation?

I'm using Cloudflare Workers and cannot call `TypeCompiler.Compile` during runtime.
It would be great to be able to do this step beforehand (as a pre-build step) and just use compiled version (as I'm assuming it would be more performant).

Thank you!

Using `@sinclair/typebox@0.30.4`

**Comment by sinclairzx81** [comment]
@oliverfunk Hey all good :)

Will close off this issue for now. Keep an eye out for the next revision. I plan to be adding new some built in infrastructure for default formats (a subset of those listed for `StringFormatOptions` which includes `email`) and there is a new `Transform` type being considered that may be able to partially assist with default value generation (albeit explicitly). These should appear on `0.31.0` (it's a big revision)

All the best!
S
