### ISSUE TITLE
ArrayMaxItems validation return ArrayMinItems ValueErrorType

### ISSUE THREAD

**Issue by mlazuardy** [sinclairzx81/typebox#526]
the issue can be found here

https://github.com/sinclairzx81/typebox/blob/master/src/errors/errors.ts#L179

**Comment by sinclairzx81** [comment]
@mlazuardy Hi, thanks for reporting.

There is a PR in the waiting that's done a lot work on TypeBox's error reporting, I picked up on this error during that work. This PR should be published in within the next few days. But you can get the fix now by installing the `dev` package.

```typescript
npm install @sinclair/typebox@dev
```

Will flag this as a bug for now, and close off once the next revision is published.
Cheers
S

**Comment by sinclairzx81** [comment]
@mlazuardy Hiya,

Hey, thanks again for reporting this issue. Error types should all be fixed on `0.31.0` :)

Will close off this issue for now 
All the best
S
