### ISSUE TITLE
unexpected behavior with `Record` key validations

### ISSUE THREAD

**Issue by samuelstroschein** [sinclairzx81/typebox#527]
## Problem 

Using key validations for `Record` leads to unexpected behavior because `{ additionalProperties: false }` is not automatically set. 

## Reproduction 

See https://stackblitz.com/edit/typescript-y4fsgz?file=index.ts. 

## Expected behavior

Given that a Record is not native to JSON Schema, the expected behavior is to resemble TypeScript. In that case, { additionalProperties: false } needs to be automatically set by `Type.Record` along with the pattern properties. 

Tricky decision. The generated JSON Schema is valid. But, it took me 1h to debug this problem until I found an explanation in the JSON Schema docs https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties.

**Comment by samuelstroschein** [comment]
I just fixed our schemas, going for `Record` sets `{ additionalProperties: false }` seems logical. I am adding `{ additionalProperties: false }` everywhere now.  

```ts

settings: Type.Record(
			Type.String({
				pattern: "^(?:[a-z]+(?:-[a-z]+)*)?\\.[a-z]+(?:-[a-z]+)*$",
				description:
					"Settings are key-value pairs. The key must be conform to the `{namespace}.{key}` pattern. The value must be a JSON.",
				examples: ["example.plugin-sqlite", "example.lint-rule-missing-message"],
			}) as unknown as TTemplateLiteral<[TLiteral<`${string}.${string}`>]>,
			Type.Record(Type.String(), Type.Any(), {
				// see https://github.com/sinclairzx81/typebox/issues/527
				additionalProperties: false,
			}),
			{
				// see https://github.com/sinclairzx81/typebox/issues/527
				additionalProperties: false,
			},
		),
```

**Comment by sinclairzx81** [comment]
@samuelstroschein Hi,

This was actually documented on the Revision [0.28.0]( https://github.com/sinclairzx81/typebox/blob/master/changelog/0.28.0.md#Record-Types-Allow-Additional-Properties-By-Default) changelog as a breaking change. Unfortunately it's one that needs to stay to meet the compositional requirements for the library (which are tied to the capabilities of JSON Schema composition (as per that link)). The change was especially unfortunate for Record types with numeric keys.

The view TypeBox takes here with respect to Object and Record types, are that users will need to explicitly opt into additionalProperties: false (as would be the case if writing Json Schema by hand). This largely to avoid generating anything extra that the user might find surprising (from a Json Schema perspective) or generating anything that breaks Json Schema composition (with note to `allOf` intersection + `unevaluatedProperties`)

### Workaround

You can avoid some of the duplication by implementing a generic type that automatically applies the additionalProperties constraint. A common pattern for Object types to create a `StrictObject` generic type, the following would be the Record version.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjgEoYnQAmA0hqjsriQBYYgHP5TAB2Ac2aVqUGjlYcuAeTDEI-AM5wAvnABmUCCDgByAAJKBJADYFgUAPQx0GAEYQAHnoCwAKA8YnkWHGrK8LykMKK0cAC8cAA8dHDeMBj8NCph4gxMcABq8U6JySos7JwEAHwAFHQAXHB0OFk1WTgQ8sCKSjVSJXIKypGIqgCUNchpNLH1pZGlHnAodgB0Y5VwBIXBQvU4SAu7Lb1KOAQ0NMC9BKYACtqYsMAYHZoXShhqg6sqBPyoHh5WVqtTKZViczm1+Bc4GAbhg7g8nqYXh4Akp4ABBfrBEihKi0cpoTBLDCCACiPnKegAeuUAPxVADaBAAtAAvAC6AGpaVUmYzWZzBgAqQY0gA6ooWfPZXLpvOZ0qFABI9INmIsAHIAVxA9lh5UGg2R7XgACFMTA+NjlgSMAtkJwwOZEgAZM6wi4UjhAiCKhAARgAPgAmAMAZlUKrVhK1Or1BqNgTgAGFzZacWIaPjFhtBPqo7aY7qoPrDe4UfAACKpkLWjXaot5+bR+tx0seWyYOAYqL4IikaIdjAQDRdmbuQdwM09wjEEgDuzDydjicp6d9ueDxdJ5d2OBVtez+eYLdjjxAA)

```typescript
import { Type, Static, RecordKey, TSchema, TString, TRecord, SchemaOptions } from '@sinclair/typebox'

export const StrictRecord = <K extends RecordKey, V extends TSchema>(K: K, V: V, options: SchemaOptions = {}): TRecord<K, V> =>
  Type.Record(K as TString, V, { ...options, additionalProperties: false }) as any

// all additional properties false
const A = StrictRecord(Type.RegExp('^(?:[a-z]+(?:-[a-z]+)*)?\\.[a-z]+(?:-[a-z]+)*$'), Type.Number())
const B = StrictRecord(Type.TemplateLiteral('hello${1|2|3}'), Type.Number())
const C = StrictRecord(Type.String(), Type.Number())
const D = StrictRecord(Type.Number(), Type.Number())

type A = Static<typeof A>
type B = Static<typeof B>
type C = Static<typeof C>
type D = Static<typeof C>


```
Hope this helps
S

**Comment by sinclairzx81** [comment]
@samuelstroschein Heya,

It sounded like you found the `additionalProperties: false` constraint (which is recommended for record types). Will close off this issue for now as things are working as per design, but happy to answer any questions on this thread regarding Record constraints and how it relates to other compositional aspects of the library (also, I should probably include some documentation related to this)

All the best!
S

**Comment by samuelstroschein** [comment]
@sinclairzx81 thanks for the reply. I was expecting internal reasons to justify the unexpected behavior. 

Again, thanks for the fast reply!
