### ISSUE TITLE
`TypeSystem.AllowArrayObjects` has gone

### ISSUE THREAD

**Issue by samchon** [sinclairzx81/typebox#535]
Updated to the latest version of typebox, and TypeSystem configurations all be disappeared.

https://github.com/samchon/typia/actions/runs/5906512984

**Comment by sinclairzx81** [comment]
@samchon Heya,

I carried out some internal refactorings on `0.31.0` (so minor semver revision). The type system policies have been moved from TypeSystem to TypeSystemPolicy. The rename was noted as a breaking change on the revision 31 [changelog](https://github.com/sinclairzx81/typebox/blob/master/changelog/0.31.0.md)

### 0.30.0

```typescript
import { TypeSystem } from '@sinclair/typebox/system'

TypeSystem.AllowArrayObjects = true
```

### 0.31.0

```typescript
import { TypeSystemPolicy } from '@sinclair/typebox/system'

TypeSystemPolicy.AllowArrayObject = true
```

Documentation on these can be found https://github.com/sinclairzx81/typebox#typesystem-policies. 

Cheers!
S

**Comment by sinclairzx81** [comment]
@samchon Heya,

Will close off this issue as the rename is documented breaking change on revision 31. Just update to the policy settings to use the new `TypeSystemPolicy` and everything should be working as before.

Cheers!
S
