### ISSUE TITLE
Difficulty with Making Items Optional in New Schema Using Pick/Omit

### ISSUE THREAD

**Issue by yanmifeakeju** [sinclairzx81/typebox#536]
Hello,

I've been attempting to use the pick and omit functions to create a new schema while making specific items optional, but I'm encountering difficulties. I've included the relevant code snippet below:

```typescript
export const UserSchema = Type.Object(
  {
    id: Type.Number(),
    userId: Type.String({ format: 'uuid' }),
    email: Type.String({ format: 'email' }),
    username: Type.String({ minLength: 2, maxLength: 15 }),
    password: Type.String({ minLength: 8 }),
    lastLogin: DateSchema,
  },
  { additionalProperties: false },
);

export const createUserProfileSchema = Type.Pick(UserSchema, ['email', 'password', 'username']);
export const findUserProfileSchema = Type.Pick(Type.Optional(UserSchema), ['email', 'username', 'userId']);

type t = Static<typeof findUserProfileSchema>;
// expect fields to be optional, but still required. 
``` 

Thanks. I'd appreciate your help.

**Comment by yanmifeakeju** [comment]
Bummer.  I think what I'm looking for is partial.

`export const findUserProfileSchema = Type.Pick(Type.Partial(UserSchema), ['email', 'username']);`

**Comment by sinclairzx81** [comment]
@yanmifeakeju Hi :)

Yeah, Partial let's you apply optionality at an object level, Optional applies modifiers at the property level. But great to see you found the solution!

All the best
S
