### ISSUE TITLE
Create schema from existing type

### ISSUE THREAD

**Issue by Salkcid** [sinclairzx81/typebox#538]
Is it possible to use type-first approach with Typebox?
By type-first approach I mean something like this 👇

```typescript
import { Type } from '@sinclair/typebox'

type User = { id: string; age: number };

// should show an error until I add `age: Type.Number()`
const T = Type.Object<User>({
  id: Type.String(), 
});
```
This exact method doesn't work in Typebox, but is it possible to accomplish something similar without resorting to this? 👇

```typescript
import { Type, Static } from '@sinclair/typebox'
import type { Equal, Expect } from '@type-challenges/utils'

type User = { id: string; age: number };

const T = Type.Object<User>({
  id: Type.String(), 
});

type MustBeTrue = Expect<Equal<User, Static<typeof T>>> // will show an error
```

**Comment by sinclairzx81** [comment]
@Salkcid Hi,

You can use Unsafe types to wrap regular types to override the inference.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChQkWHCGZEcAKIBHAK4EuONeMwl4lGnUZNlGALQkAFrq4Z2Acwwt+W4lxbSZsqzgAVRYMKDgAXlVgABMALjgWGCgOFwBuOAI3BPYtEBEwijTZWX5+OAB3KAIwTLgIEQArDGM4Dkz2OC12FgIqbCU7YBY4JxgRmAhEo2AqVDrkXCVhJSmOfvCCFgA6WRIIHvhkSJRhbaCevowAHhCwgD4ACjRMbYB5JpaYR4RZODb4qdXvgUq5HgBKHCycjg8ElGSBACyWiSACEMMgoFoMCcDEYYNdNDouLdQlAcPgiKRrlYIFQUPdGXAyvUANZAA)

```typescript
import { Type, Static } from '@sinclair/typebox'
import type { Equal, Expect } from '@type-challenges/utils'

type User = { id: string; age: number };

// wrap a object in an unsafe, this lets to specify a TS type to infer as.
const T = Type.Unsafe<User>(Type.Object({
  id: Type.String(), 
}))

type MustBeTrue = Expect<Equal<User, Static<typeof T>>> // ok
```
Just be mindful that the above would put the schema validation and TS type out of sync (so this is generally not recommended). But the option is there if you need this for some novel use case.

Hope this helps
S

**Comment by Salkcid** [comment]
@sinclairzx81, thanks for a fast reply!

Why should I use `Type.Unsafe` here though, if it will skip the typechecking and will make `type MustBeTrue = Expect<Equal<User, Static<typeof T>>> ` always be true?

If we remove `Type.Unsafe` and leave `Expect<Equal<...>>` it will work ([link to ts-playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&jsx=0&module=1&exactOptionalPropertyTypes=true#code/MYewdgzgLgBAghAnmYAxAriqBLcMC8MAFAIZIrECUBAfDAN4wC+lAdKJFAE7rBQhcYZGBiy4wAYXDQefAQG4AsACgO0GAH1sAWwAOA2ISJgS2gKYAuGDOxgA5tXx0wZgO7xyaTH3FEA5H4ANDAABlxmUOhcYDA6+lxQ-gAWUFC6EBYA9JnAACZgrBAA1oi6JMBFrLlmAG6ZACT0JuZMfpQhlESUSsoqcQYwUKVmDDAAylAkOMDMMABmXCDaMH4AAhC2wAA2JNhcmUO6ZgBGIAAefn16A4cjjACiAI7oJFvB92dHfLMLSyurtwAtMAkq8tmZ7GYIJl0DgthBLr0kaRPFRaAwVDAYGpYIwACrDWaEEiuXawLTXBL+dabHZ7A7DU4XajCW4gOaxSmJNYbFB0-a3JltHqYwaEgCqEDMgkIjGwuSsNns8iEdksMDA6G0x2lzBFyixOJgeIIxuGrAA8scAFZmPhEeiirHyqwEo6sCZcWx2LqBUUsfVY24wACy6GgACEzHieCNCB8vlAADxPF5bJOS6XBCZTbDAJNsjl4mglmDZQZJbAQGCubBbLbWJIgdwkGLSxZcFSio14gBMprdZktNrtiUdBqxsQVZvdnu9vqdqvVg9YADktTquAuJwGuxPg2HI9HY-3459Rynnq8M1KuNnJtMC8N2cbeyW6OWoJXq65wH4oCoLBdPqQA)), but it won't be DX-friendly -- no autocompletion, no indication where exactly we typed wrong type and the main issue being that developer must not forget to use `Expect<Equal<...>>`  for every schema.

Is there a way to typecheck schema based on some type? Like in ajv, for example:

```typescript
type User = { id: string; age: number };

const schema: JSONSchemaType<User> = {
  type: 'object',
  additionalProperties: false,
  properties: {
    id: { type: 'string' },
    // will show an error because I forgot to add `age: { type: 'number' }` here
  },
  required: ['id', 'age'],
};
```

**Comment by sinclairzx81** [comment]
@Salkcid Heya,

> Why should I use Type.Unsafe here though, if it will skip the typechecking and will make type MustBeTrue = Expect<Equal<User, Static<typeof T>>>  always be true?

Sorry, I may have misunderstood your question. If you need TS to report an error for an incomplete type, you can approach it this way.

[TypeScript Link Here](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&jsx=0&module=1&exactOptionalPropertyTypes=true#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUHkBGAVhgMYw7IDKMUwAdgOYUByAriPhlHAL5wBmUCCDgByAAIBneiQA2AQ2BQA9DHQZ8EAB6iAsACgDazHACqkrnAC8iOMAAmALjiSa9BgG448hhmd12Tm4eDwMDZWU4ACUMMFlgEnkYDDgYAAsU80tjFPlJbxQAIVT1ADojdRQs7htkAmIyAB4kB2cqN0YcHz8UNg5LHgA+MP0IuAAFIUxYVDFu0Tt8kGBJaUY7OhKTURanFw7PXgX8VngoDABHViUMew2tlIMSCDpXFDbq6xQy+tIYAAoEAY4HY9mhMKVqLRGP8AJQ4Aw8WEeIA)
```typescript
import { Type, TObject, TString, TNumber } from '@sinclair/typebox'

type User = { id: string; age: number };

// Replicate the User type as a TB type.
type TUser = TObject<{ id: TString, age: TNumber }>

// Property 'age' is missing in type '{ id: string; }' but required in type 
const T: TUser = Type.Object({
  id: Type.String(), 
});
```
Alternatively, if duplicating a TB type to match a TS type is undesirable, you can map from a TS type into a TB type using something like the `From<T>` type below.

[TypeScript Link Here](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&jsx=0&module=1&exactOptionalPropertyTypes=true#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUHkBGAVhgMYw7IDKMUwAdgOYUByAriPhlBQEIQQAbDAEM6LDADcucAL5wAZlAgg4AcgACAZ3okBw4FAD0MdBnwQAHqoCwAKDsnMcAKqbpAXkRxgAEwBccJo09AwA3HDCDBgBdOycULKhdnaGhnAA4hh0XMIwGBEoPHCO+fio3nQ0EJqYZCHFABb5VMWmDqZwAGJKIAA8yAB8cJ52cChwGBZ5dD6acABKpNA+vQAKSpiwqADSGKg4rHQA1nQQAO50QwD8eESkML1IANrbFXBHexDyKAC6Ad3KfovH5DGRDPyjcaTaazQLBRhwG5UeEMOAQ2xjZATKZZWGxDjSJFsAkJdGY7EwubmQQiOiIwr8ISiNGQ5DMSRcZK2VJwdYQTYmNSRDCqbxzEDATTaBH0VpOVRIXwBIK0RjhGSi-CseBQDAAR1YBgwPjeJTgdhIEDoQRQ-x6vVcXCGnjQmAAdARiGQABQISFKlCmN3UVUMb0ASjsMnDoSAA)


```typescript
import { Type, TObject, TString, TNumber, TBoolean, TNever } from '@sinclair/typebox'

type User = { id: string; age: number };

// Generate a TB type by introspecting the TS type
type From<T> = 
  T extends Record<PropertyKey, unknown> ? TObject<{ [K in keyof T]: From<T[K]> }> :
  T extends string ? TString :
  T extends number ? TNumber :
  T extends boolean ? TBoolean :
  TNever

// Property 'age' is missing in type '{ id: string; }' but required in type 
const T: From<User> = Type.Object({
  id: Type.String()
});
```
Note, TypeBox doesn't provide any built in type mapping infrastructure to handle mapping from TS to TB types, but does provide ways for users to perform this mapping themselves (within the constraints of the TS type system)

Does this help?

**Comment by Salkcid** [comment]
@sinclairzx81, yes, it does help, thanks! I'll consider using the second variant if I'm able to expand on it to meet my needs.

As an aside, does TypeBox not provide built-in type mapping due to the design philosophy of the library (implying that there's no possibility of such a built-in feature appearing in future versions), or is it due to some other reason (leaving open the possibility that such built-in feature might appear in the future)?

**Comment by sinclairzx81** [comment]
@Salkcid All good on the second variant :)

> As an aside, does TypeBox not provide built-in type mapping due to the design philosophy of the library (implying that there's no possibility of such a built-in feature appearing in future versions), or is it due to some other reason (leaving open the possibility that such built-in feature might appear in the future)?

It's not so much a design philosophy as much as it is avoiding adding functionality that can't be fully mapped through the type system. I would certainly consider adding the `From<T>` type if I found a way to map everything fully. Unfortunately, there are some TS constructs that appear as blind spots to the TS type system, with union and intersect types being the main ones. So only really consider adding types if I can capture mappings 1-1 (which is more a design constraint than a philosophy)

That said, I am generally on the look out for ways to add additional mapping types to TB (as users do ask about certain kinds of mappings from time to time). Here's one currently under consideration for the TypeCompiler's TypeScript code generation result.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZJCOxbxkcALwphAOgDyIgFYYSMABQJZcOOIBcmzFvxQOAcxMBKLBbipbae45d3TxlLAC9fbQD2Vw8vAHcI+2QAVzAuDBMAbT8MBxgnaKC7XIA5ZJARDCh3AF1YkOpE3IAxZM5iRSycrTKKqtqcboA1CGAAE3c3WXIpuRkhTBR1PEJiEgAeBYwIKhQAPktDy35+OAALCAA3KupoFFw4LdktvGX8IlIo503hHf24E7nK43Kh3ZAPZQFZyPYSyWSAgC0SORKNRaPRGMxWOxOKx8P4+JWHxIX3WyD2+MJZxgMDALGsJ2cwBgZ2SIi0ChA-DYnB4fFC4gAHABGQTCMTifgiLgQET8BRKGD8DDiAjgdIsfhgWgwCBbTXKYkIyEuLQwFiUmSI3E2212+042SgSCwRBwLwAVXYwEUyAgKTS2C8AEEWCwqjBgpZQ+HYDkcCGwxGAEoYZRR+4kM4YEAEBMNZDB9ioDOFqBQAglryFlioTgASRgVSI0FLACFgM56+xI9W2xAIOkCOxSwBhRSQ5LGVvVgAiRCDBda7R9I+rjebuqgpe7TecVR3Paq4eM+csyAAMszm1whgQuMlF+er02K1xSyUMNdt9WSnqP8kXDvr+5SVNu7oFnohinhB546GAHTsPepYAAq0CAwDhqhtCYLAwBpqWqYEGMihcFWBapiQyRQGw1yEUY0BjPRVCll8Z73KgFSDqWyBnJhPGpOkpZemMGBUBwGBMbBKBequ7HIB6HAwIKwblpWpYjOMwSUDQdCMKwHDcLwAhbBK0hWqcDpWdZ9qEt2JBQDmGA9oSNlue5GKyCqLrwC89mOSAzkwG2BDhssSAgLYJrRAA3I8UX5C4FBeeIPkwos-lOT2IXhsKABs4VwJFjDNAwcUwLYDAAAzCmVjBVQwlW1XFDC1ZVABMdUMJ1lUAMxdf1lUACxdSNlUAKxdZNlV5V1s2VQA7F1S2VYKXVrZVACcXXbZVwZ1cGlVtnVbaVaOdWjpVs51bOlUAKJ1XdlWlXFzSVQ1yUyN50C+cIcCZYF2WhRgwpVYVxUMNt5Xvc19WNYwsOtfD3VdT1jD9S1g2MCNLVjYwk0tdNjCzS182MEtLUrYwa0tRtjBQ-TyMfeQKVpX5nABUFqbfuGZJwCqTbsGMLBwNFzgHBoqgC85wtwAABgAJAgHBUDcF7kErKs3Mm5By3AAD88tKwDXNfseGDrMmewawg6t674rM-elGD-RzWUwMgpAANZ89LQsi2LOBtvz4iC7LJtA+GEtLH7stexgqB-MHhtttkNRwLY7Bm1AjuuuzDnu5+oe+6HMsB4l0RByHYcixHwXA9HUul-7cAxhG6xtjgdc5RgeyZAwIAMDUXiG23sAd13buA-XUf9zAQ9eL41dl0byvsKrUBwOrmvr9rusj1vy8t2PMAT67BfTz3fcDwvDSWIbisICf6x157JA+xeQd7DgYvW8bU9BSLqfZMX9953wzqvZ+r9vbrE-nANs39RYV3FjbHWctF5wCzt+XOv0MoAJ7CXGuSCoRV1jrXfBM8XYaG7sDUG0c67c3Ni-ChQDmEX1NjzC25Iv4UgsnADyAiBGEneGsUk5JXKCMkdZQk2oMA0nwlABEnZ2DQAwDg52RJRHINkooQhK9wRZhzAQTINRG5H1lpkLWm84FaFsVYuAyZh4NENsmcxIsTHSXvqvERnxkHrBPjkWBexrboPAbYR+PiSR+ICcIIJ1s4AAB84BK0iV8HR7B-FJlgKmZQltglgMsOE0JgJZHyKqEo5wKjHLqJeKk5Bu5zbGD0S3Ax2ZcwmLMWQuAljd7WJwLYrQ9jHEH1cV0jxXgvERNWL4qEmTYwe1iRefJoSjjhJSdMqJsyYmYDiZQAAZMkhAdSoQNJokYU+J8cnAOWRguWoTvp5z+sclwaEIC4SEM02WyBXnvPwiwHAABpNxxCXCN0yAC9OXTkDwUQveMk4LTFwAOcgIiJF2BkXhRC3hkzHLEVIqgQ5ALyD61sOs4kpJtlcIRTchovgEXAuhQhVccLkDUoPo-IlJLDnPOiHMiMgTWVYpCRgwVkLm5fNRfizFpj2W4rRWRQl5BSVHI2RSrJCydmippYU1eRLlU8u+JS6VNKSmOTKYo5RqialPNVcgn5EY-mfJFt8nCDqCJwCBV0sWHTlievFe4+xNi7G9IcU4lxwLxnOO8baqE9rYCoDJDgZ+cDf7CtpdG8ldrXXxsTa3dVsCf7IPyXFMlWjY3ZuIGmXNz8QEguiB0tNEC7kyLNZWi1lSrVfVSk7WpMaXkEArIFV8LAnWZjacYmoXdgW-2WE3IhPSN5b36cGxdwyZDhrGendlYAB1qgAPrGyVdyvtvKjVLMbU2ndg6D0IHrEe0tMyXB8rjIs-JOAH2bP7YOuRx5n0wCuXkye7CCH1iA5zSOIMqraqKS2uRbaKlVLUV2tmNrM1QgDOkUdrSjE+slhGwNy7BkhscdJDd-rulbvAQ-D9ar5mBPPQUw4ayVVoafWet9x7WPRAwxbS5aZrkXpg8hntqGy0uBfDeLDEm3x3gfL3Wd07kEG3lgwJWyByAMHtqvdTxTTilPg5a6pwnHmLANVh3AhjcwS2rAyosBLDYMGHKgBgGcbNQtUhWBN9jcAHGoyxsTvKfPkBMfbNz5Gax1hIBuCsW51jed8-LUMkXosEGlBgFLsWaN+KC3sULBYGUdi7D2ZTDARCdiUi52w0k536P7IODAw4StiHq8OSrYWiHIHHIqKAU5Yv2JQjgIZCW5ZZziHAEwWXY27qHb+gbcNrZuHUAcSbT6ra61c-lqF84mwle2xgNrm3wvLmMKuOLIa5tDeU3LCb-nH3RBQtNn9NF1hzeqgwBbS3OMBe+GtvL54GUNP3JvB+7BQJVD+zHcLpyTyn3i1dm7BrofnPWEFtwEOastIy9AM7i6fNXZS2lrHUB1grcC9bXLG3-tQuk3CuHfmDU064CjkJlPIcdc-N+ErWCqgHap+FsoQEueAS4Lztn+jehgSF30KAouMdfL-PABzbQvYqLiOwWXDKoLI7p-LJApPnBxsrSO3ASb83pL9Dx9Y8dE67B84WqEDbKC61sO1-RryMK8x13Ld3mELb6+Z+QCn1hXctMooxHHNwLvEeG2HqAYwSe3c-bylC1t32J9JGtoPIeJVGGorRC2Xv-dBfRwy1MVAI+bzx-Tk93xi+s7l86r4JWxYa6hbgTiYguDN474OVv4XeKYSuwMkvULLde8yPry3QWagj-CyJMSEkxglbaKJcSWcxh946+kiveBhsI5r9v1Hs+OuaSXw5y4owN-14ZYpHsKk1L2cYLf5SHnKyi4YMr1X6uASnC9CwAgqscAg+Ki7ACIjkLAg4lwqW6QQAA)

All the best!
S

**Comment by YaoKaiLun** [comment]
> ```ts
> User
> ```

@sinclairzx81 
How to modify if "User" is an interface, i got the error "Property 'not' is missing in type 'TObject<{ id: TString; age: TNumber; }>' but required in type 'TNever'."

```
interface User { id: string; age: number };
```

**Comment by sinclairzx81** [comment]
@YaoKaiLun Here's a quick update (changed `unknown` to `any` on Record value). Should work for both `type` and `interface`.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUHkBGAVhgMYw7IDKMUwAdgOYUByAriPhlBQEIQQAbDAEM6LDADcucAL5wAZlAgg4AcgACAZ3okBw4FAD0MdBnwQAHqoBQ1+jC7zhJDHACqm6UmAATAFxwmjT0DADccMIMGAF07JxQsqG2hoZwAOIYdFzCDhEoPHAmmHD4qHD2SpqYZCGFABauVIWm1kWuAGJKIAA8yAB8cAC8cNZwKHAYFg50PppwAEqk0D7dAApKmLCoANIYqDiiqAMA-HhEpDDdSADa2+V0cADWexDyKAC6AZ3KvbfvAzIBn5RuNJtNZoFgow4KcqFCGHBgWNkBMppkIbEONJYWwsQkkaC0TM5uZBCIHrC+GTRIiQchmJIuMlUusIJsTGpIhhVOU5iBgJptND6M1iqpvP5IbRGOEZDz8Kx4FAMABHVgGDA+e6i1zWEgQOhBFBfLrdDxcAbDNCYAB0BGIZAAFAgQb4AtaMDbqNKGI6AJRYawyP2hIA)

```typescript
import { Type, TObject, TString, TNumber, TBoolean, TNever } from '@sinclair/typebox'

interface User { id: string; age: number };

// Generate a TB type by introspecting the TS type
type From<T> = 
  T extends Record<PropertyKey, any> ? TObject<{ [K in keyof T]: From<T[K]> }> :
  T extends string ? TString :
  T extends number ? TNumber :
  T extends boolean ? TBoolean :
  TNever

// Property 'age' is missing in type '{ id: string; }' but required in type 
const T: From<User> = Type.Object({
  id: Type.String(),
});
```

**Comment by YaoKaiLun** [comment]
@sinclairzx81 thanks for a fast reply! It works! But now I am also confused about how to make it works for Intersect and optional

```
interface Base { name: string; }
interface User extends Base { id: string; age: number };

const base: From<Base> = Type.Object({
  name: Type.String()
});

const T: From<User> = Type.Intersect([
  base,
  Type.Object({
    id: Type.String(),
    age: Type.Number(),
  }),
]);
```

```
interface User { id: string; age?: number };

const T: From<User> = Type.Object({
  id: Type.String(),
  age: Type.Optional(Type.Number()),
});
```

**Comment by sinclairzx81** [comment]
@YaoKaiLun Just for fun, the following maps optional properties

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4FEBuAhgDYCuhM2KA8gEYBWGAxjDsgMoxTAB2A5mwBypELQxQ2AIQgRiGQjzbUwMYBB4khGfOLgBfOADMoEEHADkAAQDOvJsULAoAehjoMtCAA9zAKF-OznAAShjWsjrWcFAYAI6kThgAJnAKKRAqahrEcCAQScCGwOLWvm6YIczQSQAywADWGHAAvJVM1QA8AAommLCoANIYqDgKqAB8Ze5wyqrqJEOo1h3IcBhelDxJUaHtULUNGOMteF72pEkYHUgA2gNwvHCNqBCGKAC6AFwoaxsYWzsqvsOgM2Hd3scAPxwHjaXTfe56G7PV4fHCkLYYIqwpKTcpNULxRJJRbLVbrTbbNrVOqNY6tXBnMiXa5wO4PHhPYao5BfH4U-5U3adUEocFQuD3b6wnRQfTI7lvXnozHY5J46YAMRMIGFwN8cH5fwB1OBPQy4jci1GPAmOANIV+lMBewOjROhISMSSK3GWAd1HuApNKLewROsyyC2GZL9DuCQeNVNDP1anuJpN9ODgvnpeCIZAoVwQDvZj0DfOQkfmxA62tMHWC4smBgAZIhS-dHgm+fWQCtxb49JMAkEAOL-cRF1IoSRwfFwWioDlcCDWTAsXh8ecACyaHHn7imFT7vpaDvJSZdNMOcGhVYYzBgdZ1ep9yHGx0+F6dgqi1i4Lc7xQThuH4OBv0NS9nRhEQxDle9hFEeEf2DKlPFkeROXvaRMIUCCL0EOEoH8XhKCgQxCCYJoAFVrF0JBgCSb4ALAvgAG5Uj4DBIWlODdD0dj-ECOBzT6NwLEIbjzAeKIQGAaxbHAx4F3MRjmLgVit04vQZNoUh4BiIlvQ5Q8Kl8doeAAlBvlPOjxDzNBMAAOjoRgWAAChLQ0mO+JyMGc0Ctw8gBKf1DSkjA-PcVzMhrDz-OcpD4NCkKhxC9igA)

```typescript
import { Type, Evaluate, TObject, TString, TNumber, TBoolean, TOptional, TNever } from '@sinclair/typebox'

// Resolves required and optional modifiers
type RecordLike = Record<PropertyKey, any>
type OptionalKeys<T extends RecordLike> = Exclude<{ [K in keyof T]: T extends Record<K, T[K]> ? never : K }[keyof T], undefined>
type RequiredKeys<T extends RecordLike> = Exclude<{ [K in keyof T]: T extends Record<K, T[K]> ? K : never }[keyof T], undefined>
type FromRecord<
  T extends Record<PropertyKey, any>, 
  R extends RecordLike = Required<T>,
  OK extends keyof R = OptionalKeys<T>,
  RK extends keyof T = RequiredKeys<T>,  
> = Evaluate<{
  [K in OK]: TOptional<From<R[K]>>
} & {
  [K in RK]: From<T[K]>
}>

// Generate a TB type by introspecting the TS type
type From<T> =
  T extends RecordLike ? TObject<FromRecord<T>> :
  T extends string ? TString :
  T extends number ? TNumber :
  T extends boolean ? TBoolean :
  TNever

interface User { id: string; age?: number };

// Property 'age' is missing in type '{ id: string; }' but required in type 
const T: From<User> = Type.Object({
  id: Type.String(),
  age: Type.Optional(Type.Number())
});
```
Will leave other TS constructs to you :) 
All the best
S
