### ISSUE TITLE
Utility Types: Partial, Required, Omit, Pick

### ISSUE THREAD

**Issue by sinclairzx81** [sinclairzx81/typebox#54]
It might be interesting to implement a subset of TypeScript's [Utility Types](https://www.typescriptlang.org/docs/handbook/utility-types.html). I expect this functionality would only apply to schemas of type `TObject<Properties>` and have the following behavior.

```typescript
const Vector3 = Type.Object({
   x: Type.Number(),
   y: Type.Number(),
   z: Type.Number()
})

const PartialVector3 = Type.Partial(Vector3)         // { x?: number, y?: number, z?: number }

const RequiredVector3 = Type.Required(PartialVector3) // { x: number, y: number, z: number }

const Vector2 = Type.Pick(Vector3, ['x', 'y'])       // { x: number, y: number }

const Vector2 = Type.Omit(Vector3, ['z'])            // { x: number, y: number }
```
Having the ability to partial on a `Type` may help applications that use partial objects to update records in CRUD scenarios. Not having the ability to `Partial<T>` on a common type would lead to duplication of that type (one for `Required` and one for `Partial`). For consideration.

**Comment by iSplasher** [comment]
I would very much be interested in Omit

**Comment by sinclairzx81** [comment]
@iSplasher Hey thanks. I've actually setup a branch called `utility-types` to explore implementing this feature. I've written rough type mappings for `Required`, `Partial`, `Omit` and `Pick` tonight but currently pending implementation of the schema code. 

Mappings [here](https://github.com/sinclairzx81/typebox/blob/utility-types/src/typebox.ts#L169-L184)

Stuff Todo [here](https://github.com/sinclairzx81/typebox/blob/utility-types/src/typebox.ts#L399-L417)

For the schema code, I guess I'm looking for the most nimble implementation possible. Ideally, there should be no recursion when mapping the schema (except for the `clone`) with the utilities only operating on object schemas 1 level deep (inline with TypeScript). 

Possibly something like the following.

```typescript
/** `UTILITY` Omits property keys from the given object schema. */
public Omit<T extends TObject<TProperties>,  K extends Array<keyof T['properties']>>(schema: T, keys: [...K]): TOmit<T, K> {
  const next = clone(schema) // to implement
  if(next.required) {
    next.required = next.required.filter(key => !keys.includes(key))
  }
  for(const key of keys) {
    delete next[key]
  }
  return next
}
```
Also open to suggestions around the mapping code (some of it is quite long winded). Probably won't get much time to look at implementing the rest for a week or so, so if you're keen to help, I'd certainly be open to PR's :)

**Comment by sinclairzx81** [comment]
@iSplasher Have implemented these types on the latest package `@sinclair/typebox@0.14.1`. Documentation in the readme under `Utility Types`. Marking this issue closed :)

Cheers
S
