### ISSUE TITLE
Nullable string defaults to "" when not using format

### ISSUE THREAD

**Issue by Fritiof** [sinclairzx81/typebox#546]
Hello,

I'm using Fastify with these versions of deps:

 "@fastify/type-provider-typebox": "^3.5.0",
 "@sinclair/typebox": "^0.31.2",
 "fastify": "^4.21.0"

And I noticed today after upgrading from typebox 0.25 that my tests started failing when using a request object like so

```
export const RequestBody= Type.Object({
  ....
  email: Type.Union([Type.String({ format: 'email' }), Type.Null()]),
  phone: Type.Union([Type.String(), Type.Null()]),
})
```

The request body is:

```
{
 email: null,
 phone: null
}
```

What the route handler gets in request.body:

```
{
 email: null,
 phone: ''
}
```

The key difference is that I'm using the format option on the email property of the typebox object and not for the phone property.

If I set a format on the phone property as well then it's possible to null it.

**Comment by sinclairzx81** [comment]
@Fritiof Hi,

This sounds more like a Fastify question than a TypeBox one. There hasn't been anything changed in TypeBox relating to Object and String schematics (or the way formats are handled), so I'm not too sure why you would receive a `phone: ''` (empty string) when passing `null` on the request, but it may have something to do with Fastify's configuration of Ajv (possibly `useDefaults` which will automatically set values if you specify `default` properties on the schematic), but I'm not too sure based on the information above.

You should be able to compare `0.25.x` to `0.31.x` by console logging the schematics and comparing them.

```typescript
export const RequestBody = Type.Object({
  ....
  email: Type.Union([Type.String({ format: 'email' }), Type.Null()]),
  phone: Type.Union([Type.String(), Type.Null()]),
})
console.log(RequestBody) // prints the Json Schema (compare for 0.25.x and 0.31.x)
```
Note that TypeBox is generally only used to produce schematics for routes, but doesn't usually take part in data processing or validation (unless you're using the [validationCompiler](https://github.com/fastify/fastify-type-provider-typebox#type-compiler), in which case, I would recommend using Ajv if that's was you were using previously)

Outside of this, this may be a question best asked on the Fastify repository. 
Hope this helps!
S

**Comment by sinclairzx81** [comment]
@Fritiof Heya, 

Might close off this issue as it sounds like it relates more to Fastify request handling than TypeBox (which is only providing the schematics, and these wouldn't have changed since 0.25.0 (to the best of my knowledge)). If you have a bit more detail regarding the issue though, I'm happy to help on this thread as best I can, alternatively feel free to post an issue on the Fastify repo and link back to this issue (can discuss things there)

All the best!
S

**Comment by Fritiof** [comment]
Thanks a lot, I appreciate the rapid response and thorough explanation! 🙏
