### ISSUE TITLE
Type.Any() is not working with Fastify response schmea

### ISSUE THREAD

**Issue by SzHeJason** [sinclairzx81/typebox#55]
example
```ts
export const responseSchema = Type.Object({
  code: Type.Number(),
  subcode: Type.Number(),
  message: Type.String(),
  data: Type.Dict(Type.Any()) ,
})
```

Getting a error when reply send

``` ts
const Controller: FastifyPluginCallback = (server, options, next) => {
  server.post(
    '/:moduleName/:action',
    {
      schema: {
        body: bodySchema,
        params: paramsSchema,
        response: {
          '2xx': responseSchema,
        },
      },
    },
    async (request, reply) => {
      reply.send({
        code: 0,
        subcode: 0,
        message: 'ok',
        data: {
          a: '123',
        },
      })
    }
  )
  next()
}
```

```
Error: Cannot coerce 123 to undefined
```

Fastify@3.13.0
@sinclair/typebox@0.12.9

**Comment by sinclairzx81** [comment]
@SzHeJason Hi, this might be an issue with `fast-json-stringify` (the JSON serializer Fastify uses). As a quick test, can you try the following.

```typescript
//-------------------------------------------
// replace this
//-------------------------------------------

export const responseSchema = Type.Object({
  code: Type.Number(),
  subcode: Type.Number(),
  message: Type.String(),
  data: Type.Dict(Type.Any()) ,
})

//-------------------------------------------
// ... with (raw JSONSchema from TypeBox)
//-------------------------------------------

export const responseSchema = {
  type: 'object',
  properties: {
    code: { type: 'number' },
    subcode: { type: 'number' },
    message: { type: 'string' },
    data: { type: 'object', additionalProperties: {} } // possible 'any' issue here.
  },
  required: [ 'code', 'subcode', 'message', 'data' ]
}
```
Give this a try and see if the problem still exists. Note you can also print this schema with `console.log(Type.Strict(responseSchema))`.

I've actually submitted a few PR's to `fast-json-stringify` to resolve a couple of issues with `any` type schemas. It's possible the empty schema on `additionalProperties: {}` may have been overlooked. If so, you can submit the raw JSONSchema as an issue on `fast-json-stringify` and link back to this issue.

Let me know how you go 
S

**Comment by SzHeJason** [comment]
Get same error after replace. 
But change `additionalProperties` to `true` is working
```ts
const Controller: FastifyPluginCallback = (server, options, next) => {
  server.post(
    '/:moduleName/:action',
    {
      schema: {
        body: bodySchema,
        params: paramsSchema,
        response: {
          '2xx': {
            type: 'object',
            properties: {
              code: { type: 'number' },
              subcode: { type: 'number' },
              message: { type: 'string' },
              data: { type: 'object', additionalProperties: true }, // possible 'any' issue here.
            },
            required: ['code', 'subcode', 'message', 'data'],
          },
        },
      },
    },
    async (request, reply) => {
      reply.send({
        code: 0,
        subcode: 0,
        message: 'ok',
        data: {
          a: '123',
        },
      })
    }
  )
  next()
}
```

**Comment by sinclairzx81** [comment]
@SzHeJason Looks like an issue with `{}` schemas in `fast-json-stringify`. Would you be able to create an issue on that repository and link back to this issue?

For reference, there is information about the objects applied to `additionalProperties` noted [here](http://json-schema.org/understanding-json-schema/reference/object.html). Specifically the section that reads.

```
If additionalProperties is an object, that object is a schema that will be used to validate 
any additional properties not listed in properties.

For example, one can allow additional properties, but only if they are each a string:

{
  "type": "object",
  "properties": {
    "number":      { "type": "number" },
    "street_name": { "type": "string" },
    "street_type": { "type": "string",
                     "enum": ["Street", "Avenue", "Boulevard"]
                   }
  },
  "additionalProperties": { "type": "string" }
}
```
So essentially if `additionalProperties` is an `object` then that object schema is used to validate any unknown properties found on the object. The expectation here is that `{}` should allow any property to be assigned to the object (satisfying the `Type.Dict(..)` schema type). This is most likely an oversight.

**Comment by sinclairzx81** [comment]
@SzHeJason Have submitted a PR that should resolve this issue. Will need to wait on the `fast-json-stringify` maintainers to give the green light however. Will close off this issue once things go through.

**Comment by SzHeJason** [comment]
Awesome , Thank you
