### ISSUE TITLE
Support a function like zod preprocess

### ISSUE THREAD

**Issue by mirageN1349** [sinclairzx81/typebox#553]
Zod Preprocess: https://github.com/colinhacks/zod#preprocess:~:text=%3B%0A//%20%3D%3E%20ZodBoolean-,Preprocess,-Zod%20now%20supports

**Comment by sinclairzx81** [comment]
@mirageN1349 Hi, 

Have you tried Value.Convert?

```typescript
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'

const T = Type.Object({
  number:  Type.Number(),
  string:  Type.String(),
  boolean: Type.Boolean(),
  date:    Type.Date(),
  invalid: Type.Number()
})

const V = Value.Convert(T, {  // const V = {
  number: '3.14',             //   number: 3.14,
  string: 1001,               //   string: '1001',
  boolean: 'false',           //   boolean: false,
  date: '2023-08-27',         //   date: 2023-08-27T00:00:00.000Z
  invalid: 'hello'            //   invalid: 'hello' <--- unmapped
})                            // }

```
This function performs a value coercion by attempting to map values into their target type. This function returns `unknown` as any value that can't be mapped is left as is. The function is intended to be used to preprocess values prior to check (typically when reading in string encoded values from http headers, querystrings and url parameters)

Does this help?
S

**Comment by mirageN1349** [comment]
@sinclairzx81, Can I write such code using Convert? I tried but didn't find a solution.
 
```ts
 AllOWED_ARRAY: zod
    .preprocess(
      JSON.parse,
      zod.array(zod.enum(SOME_ENUM)),
    )
```
I validating process.env with typebox and need to turn Json into array before validation. 

Thanks for the fast feedback

**Comment by mirageN1349** [comment]
I need to intercept the value at the time of validation, convert it to an array and pass it to the typebox for type check

```ts
export const envSchema = Type.Object({
   AllOWED_ARRAY: Type.Array(Type.String(Type.Number())),
});
```

Then this code gets into the fastify env-schema and I have no control over it
<img width="562" alt="image" src="https://github.com/sinclairzx81/typebox/assets/56263427/38eafbec-5d09-4860-a2c7-b6d9fa1d6d97">

**Comment by sinclairzx81** [comment]
@mirageN1349  Hiya,

Yes, you can use TypeBox to parse env values, however keep in mind that TypeBox is somewhat different to Zod in that it breaks down parse functions down into their constituent operations, meaning you will need to construct your own `env` parsing function by combining the TB Value functions in a way meaningful to your program. The following shows Convert (and optional Cast) inline with the Zod variant. 

```typescript
enum Foo { A = 1, B = 2, C = 3 }

const E = Type.Enum(Foo)                             // same as: const E = Type.Union([
                                                     //   TLiteral<1>,
                                                     //   TLiteral<2>,
                                                     //   TLiteral<3>,
                                                     // ])

const T = Type.Array(E)                              // An array of E

const json = '["1", "2", "3", "4"]'                  // Json containing a string array of numbers

const converted = Value.Convert(T, JSON.parse(json)) // const converted: unknown = [1, 2, 3, '4']
                                                     //
                                                     // note: All values are mappable to the variants
                                                     // of the enum/union (E) except for '4' which is
                                                     // an unknown union variant. This value should be 
                                                     // checked before use.

const check = Value.Check(T, converted)              // const check = false ('4' is invalid)
                                                     //
                                                     // If true, you can use this value, otherwise....

const casted = Value.Cast(T, converted)              // const casted: Foo[] = [1, 2, 3, 1]
                                                     //
                                                     // you can use cast to cast the value to correct
                                                     // type. This function isn't recommended for env
                                                     // parsing and will replace any invalid value with
                                                     // a default value (replacing '4' with the first
                                                     // union variant)

const value = casted                                 // the final value
```
Additionally, if you're looking for a TypeBox version of `.parse()` this is called Value.Decode. You may not need it for this particular use case, but documentation on decoding (and transforming) can be found at the link below (which may provide alternative ways to parse env values)

https://github.com/sinclairzx81/typebox#types-transform

Hope this helps
S

**Comment by mirageN1349** [comment]
In my case, I don't have access to the env variable at the schema level. It is fully handled by fastify under the hood. I can't figure out how I can then get the value at the schema level and set it to Convert so that it executes while fastify is running on my schema

**Comment by mirageN1349** [comment]
Perhaps I do not understand the principle of typebox correctly and I cannot hang up a callback that will execute fastify env schema before checking types

**Comment by sinclairzx81** [comment]
@mirageN1349 This may be more of a Fastify question than a TypeBox one. But the following implements a basic env parse function based on the information provided thus far.

```typescript
import { Type, Static, TSchema } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// Parses process.env for the given schema
export function ParseEnv<T extends TSchema>(schema: T): Static<T> {
  const converted = Value.Convert(schema, process.env) // process.env here
  const checked = Value.Check(schema, converted)
  if(checked) return converted
  const error = Value.Errors(schema, converted).First()!
  throw Error(`Parse: ${error.message} ${error.path}`)
}

// Some env variables to parse.
const T = Type.Object({
  NODE_DEV: Type.Boolean(),
  NODE_PROD: Type.Boolean()
})

const env = ParseEnv(T) // Error: Parse: Required property /NODE_DEV
```
In Node, the `process.env` is accessible globally (so you can read from it from anywhere). How this ties into Fastify callbacks is really a question specific to Fastify. However if Zod can parse out env's in a Fastify context, the same would be possible for TypeBox, but you would need to write the function yourself (as above) as TB doesn't provide any convenience functions, only functions you can combine into your own functions to carry out some task.

**Comment by mirageN1349** [comment]
Ok, I'll try to write a custom validate function and use it in fastify.
Thank you very much @sinclairzx81
