### ISSUE TITLE
Too deep type instantiation when creating generic transform schema.

### ISSUE THREAD

**Issue by HamishWHC** [sinclairzx81/typebox#554]
Hi, I'm back with a new issue. Haven't managed to simplify this much yet, but the error appears from this generic schema function:

```ts
// Schema to match either T or T[], but always decoding to T[].
export const ArrayOrSingle = <T extends TSchema>(schema: T) =>
	Type.Transform(Type.Union([schema, Type.Array(schema)]))
		.Decode((value) => (Array.isArray(value) ? value : [value]))
		.Encode((value) => (value.length === 1 ? value[0] : value));
```

The error I am getting is `Type instantiation is excessively deep and possibly infinite. ts(2589)`

Weirdly, this error disappears if I save the file, and then reappears when saving another file. Running a full type check on my project via the `svelte-check` command shows the error though.

This error has only occurred on >= 0.31.3 (since the change to DecodeType). Testing it on 0.31.2, the error does not appear.

Also, the types returned by this function when actually used in my schemas are correct: e.g. calling this function with `Type.String()` has a return type of `TTransform<TUnion<[TString, TArray<TString>]>, string[]>`, which is correct.

My best guess is that the logic is fine but the type is complex enough that it is hitting TS' limit, likely due to the extra layer of indirection added by DecodeModifier.

Since the types do seem to work, despite the error in the generic case, a simple `// @ts-ignore` works as a workaround, but I wanted to raise the issue in case it can be fixed or someone else encounters it after upgrading.

**Comment by sinclairzx81** [comment]
@HamishWHC Heya, You can try the following...

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsriQBYYgHnJQEB2AzgGbQhwC+c7UCNwDkAAVbBmJADYFgUAPQx0GAEYQAHsICwAKFCRYiOADUC0gK4Ze-QSPGSZcxcszqNCgG7mrO3XoUFPGpaAjgYCDg6GGo4DGAYGigUOGgUAG0AXRxVC3hzAHcCVFY4ABMMEggyyQBzcMjkLIA6PQwNQ3gqtngAQSgmVAB5KFw66WsAXjgAHmQ4jRgMZjLSihC6AD4AClYNggAuFABKI+RGFg4uOZx8IlI5zazNuEnNvQBINExmi7ZOKAgbbfDDNACqzGAEGY23SexodHIKma-UGu32x0yx2Onw+zQAIpVqhhtttvJYMMdXi9tqjis1gKw6agyT5KXAAPxwclWOBHdI8jBYuAEUosVA43QfPEAUSkxNJgqpbzgrIpzQmzFqiVek2mAEZOdy2ekAAyZPnGinYkVi5ioPQBILIDCsGB6bpulLTZkjMZaibA5H4KB1bbYx26T19V6mNkEokVYE4YQ0aTSCDCKlwHO5vO5wJwaNwXqx9KpjDpzOZD3Qr0AIVjZnVhKqSeQOHLaYzwmF+f7heLjemXcrPZrUbr8AAwk3462FR24KOq8IUwVoNIyr3s3BB1O4LORxXV+vN9uJ7WenB8XP1XK2ySl71d-233n99fb9MTz3I0A)

```typescript
import { Type, Static, TSchema, TTransform } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// Schema to match either T or T[], but always decoding to T[].
export const ArrayOrSingle = <T extends TSchema>(schema: T): TTransform<T, Static<T>[]> =>
  Type.Transform(Type.Union([schema, Type.Array(schema)]))
    .Decode((value) => (Array.isArray(value) ? value : [value]) as any) // TS will return a `union` here for the ternary
    .Encode((value) => (value.length === 1 ? value[0] : value)) as any

// Test
const T = ArrayOrSingle(Type.String())

const A = Value.Decode(T, 'hello')              // const A = ['hello']
const B = Value.Decode(T, ['hello'])            // const B = ['hello']
const C = Value.Decode(T, ['hello', 'world'])   // const C = ['hello', 'world']

const D = Value.Encode(T, A)                    // const D = 'hello'
```
Note the ternary conditional return inside Decode is problematic as TS will interpret the return type as a potential `union`. To get around this, it's possible to use `any` to stop TS from trying to infer, and we add an explicit TTransform return type for the ArrayOrSingle generic function.

I'm ok with this popping out inference limits for this specific use case as the type is extremely complex from a type mapping perspective (as T is mapped into a union array of T[] through instantiation expression). There may be ways to optimize the inference such that the transform is derived from a pre-computed type on `TSchema`, but an update here wouldn't be available for a long time. For now, the additional modifier inference types added are ok (as it correctly maps the type)).

**Comment by HamishWHC** [comment]
Ah, yeah I tried to pull some `as unknown as TTransform...` stuff but it was still causing problems, but I hadn't tried using `any`.
