### ISSUE TITLE
Add comparison to Zod

### ISSUE THREAD

**Issue by ViktorQvarfordt** [sinclairzx81/typebox#556]
We're impressed with this package's type inference performance compared to Zod and other alternatives.

It would be great to have a comparison table in the readme showing the differences and similarities to similar libraries to help engineers make an informed decision.

**Comment by sinclairzx81** [comment]
@ViktorQvarfordt Hi, Thanks for the suggestion and sorry for the late reply on this.

Generally I try to keep direct comparisons to other ecosystem libraries out of the TypeBox readme (preferring to link to [external](https://moltar.github.io/typescript-runtime-type-benchmarks/) sites for the purposes of objectivity and third party assessment). However, I do make an exception for Ajv (which is used to track performance regressions across both projects and to give TypeBox something to measure relative performance to). I actually squirrel these benchmarks away at the bottom of the readme to try and limit any influence they might have when developers are making library selection (and not to discourage them from using Ajv)

As for Zod, TypeBox is very similar with a similar feature set, but I don't think I'm in a position to make an objective comparison. The best I can do is provide a technical overview of TypeBox's feature set (which is already in the readme). For direct comparison, this is probably best left to third parties (as they are much more likely to have an objective perspective than if the library authors are writing the comparisons themselves)

I am very much open to ways I can improve communicating TypeBox's feature set to developers (helping them to make better informed decisions) but would like to do so without promoting the TypeBox feature set over the feature sets offered by other ecosystem projects. I generally feel it's better to have concise information about a project, than have comparisons that steer developers towards one project over another.

Hope you understand
All the best!
S

**Comment by ViktorQvarfordt** [comment]
Makes sense. Thank you!
