### ISSUE TITLE
[feat] Provide ability to return schema, which its type is strict subset of json schema

### ISSUE THREAD

**Issue by loynoir** [sinclairzx81/typebox#559]
**Related Problem**

https://github.com/typescript-eslint/typescript-eslint/issues/7549

**Feat**

```ts
{
  type expected = {
    additionalProperties: false
    type: 'object'
    properties: { a: { type: 'string' }; b: { type: 'string' } }
    required: ['a']
  }

  // @ts-expect-error: TODO: https://github.com/typescript-eslint/typescript-eslint/issues/7549
  const schema: expected = Type.StaticSpec(
    Type.Object(
      {
        a: Type.String(),
        b: Type.Optional(Type.String())
      },
      { additionalProperties: false }
    )
  )

  void schema
}
```

**Comment by sinclairzx81** [comment]
@loynoir Hi, Sorry, I meant to respond to this earlier. 

---

I don't think this will be possible in TB as it only tracks generics for fields that contribute to the inference result (so can't map for the explicit properties `additionalProperties` and `required` defined for `expected`). To make this type assignable, you would need to create properties covariant to the TObject type (vs the more strict contravariant properties of `expected`)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUEEAm+wMwEAdgIYA2AClBJrMBgM5wC+cAZvSHAOQABFsDIBjKhWBQA9DHQYARhAAe-ALAAoLRhWRYceZjgBRPRjHwAvIi1w4MmXDLkAtGIpgYAVygZ8cAAUFGQBDCTk1EGoEN5wHmTxECAgGGTwMAAWrBhwsTAAlAV2cBSExKSUtPSMJKwA-ABceOURVXQMGEysWCV+AI7e0v5NcCwwUKIA5gDaALq9mvaO8Z4+fvglRhjN-BCKAFYWMBpLcGA1XXUszUgl9hS3hgq745NkU-wci-b2ik-bV4TaZfdglMGaCFaMTkcZjMTZECPUzmSxwGxoTAAOgA8odjoESgh7qVmpiMFiAMrAj6BAo-X7-FAKXFeSrUQLkqk0qZ04pndgMpBlIhtagdWrMG7cagsXIQgpAA)

```typescript
export type Expect = {
  // non-captured (and optional (you can comment these out))
  additionalProperties?: TAdditionalProperties,
  required?: string[],
  // captured
  type: 'object'
  properties: { 
    a: { type: 'string' },
    b: { type: 'string' }
  }
}

const schema: Expect = Type.Object(
  {
    a: Type.String(),
    b: Type.Optional(Type.String())
  },
  { additionalProperties: false }
)
```
Alternatively, you can express the same type with the following.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUHkBGAVhgMYw7IDKMUwAdgOYW5gzAR0CGANnAL5wAZlAgg4AcgACAZ3olunYFAD0MdBnwQAHuICwAKAMYtkWHDWY4AUROl4AXjxE7AHgQG4cTgC4U1WoxYHnD4vsgsbBw8LlQ09AwAfAZ8SYb6JBzS8NIkABYYID7WtmRwjmiYAHQExGQAFMHu+p6eRRUYlf7xdQCUQc0toSjq1azsXNx17Z1xjL09wXz9nkicACZrwJETAAoimLDAGNK+gjzSGPwGPUA)
```typescript
import { Type, TObject, TString, TOptional } from '@sinclair/typebox'

export type Expect = TObject<{
  a: TString,
  b: TOptional<TString>
}>

const schema: Expect = Type.Object(
  {
    a: Type.String(),
    b: Type.Optional(Type.String())
  },
  { additionalProperties: false }
)
```
In both cases however, the `required` and `additionalProperties` fields are not captured in generics (as these properties do not contribute to the inference result). While I do think that `required` property might be reconcilable (derived from the RequiredPropertyKeys) the optionality of this type (and compute overhead computing for it) is a bit too much of a cost to take on (at this stage).

---

As for TAdditionalProperties. I've spent time looking into this. It is technically ossible a to create a type analogous to the following...

```typescript
const T = Type.Object({
  x: Type.Number(),
  y: Type.Number()
}, {
  additionalProperties: Type.Boolean()
})
// equivalent to
type T = {
  x: number,
  y: number
} & {
  [key: string]: boolean
}
```
However this functionality is pending as additional properties of TSchema is an undocumented (future) feature that will be further expanded upon when TB moves closer to Draft 2012-12 (as there is some cross over here with conditional schematics, dependentRequired and other keywords). For now though, the current functionality is locked in place until other parts of the codebase have stabilized.

Hope this brings some insight. Will close for now as there isn't much that can be done in the short to medium term, but will certainly revisit in later revisions.
All the best
S
