### ISSUE TITLE
Support `Type.Intersect` in `Value.Convert`

### ISSUE THREAD

**Issue by santicalcagno** [sinclairzx81/typebox#582]
Hi @sinclairzx81, thanks for this library!

Wondering if there are any limitations or plans for supporting intersections in `Value.Convert`. Here's an example:

```js
import { Type } from '@sinclair/typebox';
import { Value } from '@sinclair/typebox/value';

console.log(
  JSON.stringify(
    Value.Convert(
      Type.Intersect([
        Type.Object({ foo: Type.Number() }),
        Type.Object({ bar: Type.String() })
      ]),
      { foo: '1', bar: 'test' } // Logs {"foo":"1","bar":"test"}
    )
  )
);
```

Thanks again!

**Comment by sinclairzx81** [comment]
@santicalcagno Hi, that's a good idea :)

Have just published a revision (0.31.13) that supports conversion of intersected object types...

```typescript
const T = Type.Intersect([
  Type.Object({ foo: Type.Number() }),
  Type.Object({ bar: Type.String() })
])

const A = Value.Convert(T, { foo: '123', bar: 321 })

console.log(A) // { foo: 123, bar: '321' }
```
For conversion of intersections with mixed types, TypeBox will select the first intersected type for conversion.


### Case A: Intersected Non Exclusive Object Types 1

The following selects number for the conversion (so no conversion is possible)

```typescript
const T = Type.Intersect([
  Type.Number(),
  Type.Object({ x: Type.Number() }),
  Type.Object({ y: Type.Number() }),
])
const A = Value.Convert(T, { x: '1', y: '2' }) // { x: '1', y: '2' }
```
### Case B: Intersected Non Exclusive Object Types 2

The following selects number for the conversion (conversion is possible for numeric looking values)

```typescript
const T = Type.Intersect([
  Type.Number(),
  Type.Object({ x: Type.Number() }),
  Type.Object({ y: Type.Number() }),
])
const A = Value.Convert(T, '123')   // 123
```
### Case C: Intersected Non Exclusive Object Types 3

The following selects `{ x: number }` for the conversion. The `y` property is not converted.

```typescript
const T = Type.Intersect([
  Type.Object({ x: Type.Number() }),
  Type.Object({ y: Type.Number() }),
  Type.Number()
])
const A = Value.Convert(T, { x: '1', y: '2' }) // { x: 1, y: '2' }
```
I may take a look at additional narrowing for intersected types in later revisions, but this should solve the immediate problem of intersect values not being convertible.

Hope this helps!
S

**Comment by santicalcagno** [comment]
Wow that was _fast_. Thank you!

My use case is actually a little bit more complex, I'm leaving it here in case you want to take a look at it in the future. I want to differentiate limit/offset-paginated requests vs cursor-paginated requests, so I'm doing something like this:

```js
export const requestParamsSchema = Type.Partial(
  Type.Intersect([
    Type.Object({
      limit: Type.Number(),
      variant: Type.String(),
      color: Type.Union([
        Type.Literal('red'),
        Type.Literal('blue'),
        Type.Literal('green')
      ])
    }),
    Type.Union([
      Type.Object({ cursor: Type.Number() }),
      Type.Object({ offset: Type.Number(), totalCount: Type.Boolean() })
    ])
  ])
);
```

In the meantime as you said I can either write it as a `Union` of two types with repeating properties (which I'm probably going to do), or treat `cursor`, `offset` and `totalCount` as strings.

**Comment by sinclairzx81** [comment]
@santicalcagno Hiya,

Unfortunately, It's not possible to support deeply nested union / intersection conversions at this time. But may take a look at it in future. The most I can support currently is composited object intersections (types compatible with Composite) as these naturally evaluate into TObject types (which are convertible). 

There will be some updates to Composite types at a later time to try and generalize them for TSchema, and once I've been able to do that, it will be more feasible to investigate more complex conversions (as well as provide better support for casting and value creation). For now tho, would recommend simplifying the object to fit within the current implementation if you need this functionality (just try and avoid the unions if you can, the property types should be ok)

Will close off this issue now, but will mark the issue as "future" to take another look down the road
All the best!
S
