### ISSUE TITLE
Is it needed to call the Type.Foo() Function every time?

### ISSUE THREAD

**Issue by gotjoshua** [sinclairzx81/typebox#587]
Is there any (important) difference between T and P in this code:

```ts
import { Type, Static } from '@sinclair/typebox'

const PointNum = Type.Number()

const T = Type.Object({                            
  x: Type.Number(),                                
  y: Type.Number(),                                 
  z: Type.Number()                                  
})                                                   
 
const P = Type.Object({                            
  x: PointNum,                                
  y: PointNum,                                 
  z: PointNum                               
})                                                   
                                                          
type T = Static<typeof T>  
type P = Static<typeof P>  
```

I mean, [it is clear](https://github.com/sinclairzx81/typebox/blob/6b27faba280aefed60fb598e1b05896e603b221d/src/typebox.ts#L3057) that 
there will different "instances" of plain objects each resulting from: 
```
{ ...options, [exports.Kind]: 'Number', type: 'number' }
```
and thus resembling:

![image](https://github.com/sinclairzx81/typebox/assets/8686454/42aaf35f-8771-4d26-85e3-5dede7749add)

but they will not match a reference equality test, and i didn't dig quite deep enough into the code to find out if that is relevant.
So, i ask...

**Comment by sinclairzx81** [comment]
@gotjoshua Hi, these two types are equivalent and you don't need to call `Type.*` if the type has already been created (as per `PointNum`). You can test assignability in the following way....

```typescript
import { Type } from '@sinclair/typebox'
const PointNum = Type.Number()

const T = Type.Object({                            
  x: Type.Number(),                                
  y: Type.Number(),                                 
  z: Type.Number()                                  
})                                                   
 
const P = Type.Object({                            
  x: PointNum,                                
  y: PointNum,                                 
  z: PointNum                               
})


// type L = T extends P ? true : false
// type R = P extends T ? true : false

const L = Type.Extends(T, P, Type.Literal(true), Type.Literal(false))
const R = Type.Extends(P, T, Type.Literal(true), Type.Literal(false))

// true true
```
TypeBox doesn't factor referential equality between types (specifically referential values, so it's fine for `T !== P`). It will only operate on the data structures encoded in those values.

Hope this helps
S

**Comment by gotjoshua** [comment]
> It will only operate on the data structures encoded in those values.

brilliant.

Many thanks for the quick and detailed answer!
