### ISSUE TITLE
Question: Enum and Unions

### ISSUE THREAD

**Issue by btd** [sinclairzx81/typebox#59]
Hi, thanks for awesome project.

I have a question about union types and enums. We do not use ts enums because they are not supported in babel typescript. But for example such simple type:
```ts
type M = 'single' | 'married'
```

Could be expressed as:
```js
{
type: 'string',
enum: ['single', 'married']
}
```

So that if i would write it like this with typebox:
```ts
const M = Type.Union([ Type.Literal('single'), Type.Literal('married') ])

/*
{
  kind: Symbol(UnionKind),
  anyOf: [
    { kind: Symbol(LiteralKind), type: 'string', enum: [Array] },
    { kind: Symbol(LiteralKind), type: 'string', enum: [Array] }
  ]
}
*/
```

so my suggestion is to allow to put union of literal values of the same type to be encoded as enum. WDYT?

**Comment by btd** [comment]
Probably it makes more sense in this case to define new type, like a mix of Literal and Union:
```ts
export type TLiteralUnion     <T extends TValue>   = { kind: typeof LiteralUnionKind, enum: T[], type: 'string' | 'number' | 'boolean' }

public LiteralUnion<T extends TValue>(items: T[], options: CustomOptions = {}): TLiteralUnion<T> {
        // there missing check items.length > 0
        const type = reflect(items[0])
        // there missing check type not unknown
        return { ...options, kind: LiteralUnionKind, enum: items, type  }
    }
```

**Comment by sinclairzx81** [comment]
@btd Hi, thanks for the suggestion :)

I do actually like the JSON schema `enum` representation. However at the moment, I'm planning on keeping on with the current `anyOf` implementation of as it generalizes well across all types. 

I think an implementation of `enum` would likely sit under `Type.Union()` as a optimization of the current schemas (as opposed to adding a new Type to support this usecase). Also, I am currently looking at what is involved in providing a `Type.KeyOf(...)` implementation and trying to avoid complications with respect to union handling as `keyof T` would map to an `TUnion`. For example.

```typescript
const T = Type.Object({
   x: Type.Number(),
   y: Type.Number()
})

const K = Type.KeyOf(T) // TUnion<[TLiteral<'x'>, TLiteral<'y'>]>

type K = Static<typeof K> // 'x' | 'y'
```
Will leave this issue open. There may be other ways to optimize schemas (possibly via a `Type.Optimze(T)` as a companion to `Type.Strict(T)`). Or user space implementations to remap schemas by inspecting the schema `kind` property.

Thanks again
S

**Comment by btd** [comment]
Sounds good, thanks for response

**Comment by sinclairzx81** [comment]
@btd Thanks for the follow up. I think I might close off this issue. After a bit of thought it's probably better to have down level tooling reduce literal unions to `enum` schemas if necessary. However I have actually updated the `literal` schemas to use draft 6 `const` in light of your suggestion. This should hopefully make them a little more concise than before. Hopefully it's a good compromise :D 

```typescript
const T = Type.Union([
  Type.Literal('a'),
  Type.Literal('b'),
  Type.Literal('c'),
])

// produces

const T = {
  anyOf: [
    { const: 'a' },
    { const: 'b' },
    { const: 'c' },
  ]
}
```
Thanks Again!
S

**Comment by wyozi** [comment]
Hey, thanks for the library!

I was under the impression that surely such a core typescript feature would have first class support, so I searched the documentation quite a bit before stumbling upon here. Just mentioning this as my third party experience seeing this library for the first time.

Union and Literal works okay, but at least swagger tends to generate more annoying schemas than a dedicated enum type. Having the pretty common case of union of literals be optimized to native TS / Json schema representation would be amazing!

Thanks

**Comment by sinclairzx81** [comment]
@wyozi Hi, thanks :)

I may look into this in the future as a possible optimization. Part of the problem of implementing this now is that there would need to be two distinct type inference paths for unions (one for literals and one for everything else) as well as additional complexity added to the `Type.Union()` method. 

The preference for `anyOf` is that it naturally generalizes to both literals and other types; as well as semantically meaning the same as a pure `enum` variant. It also allows for mixing and matching `literal` with other types inside the `union` (which TypeScript also allows for).

That said, I may look into this again once TypeBox's internals have stabilized a bit (there has been some updates to how the type inference works recently, so will be finalizing on those updates first before looking at getting more sophisticated on the `union` front).

Thanks for the feedback!
S

**Comment by Meriyemelhajoui** [comment]
Hey , how I can represent this using Typebox Types : 
enum : 
  0: "on"
  1: "off"  ?
