### ISSUE TITLE
Question/Feature Request: Support for multiple types

### ISSUE THREAD

**Issue by mikicho** [sinclairzx81/typebox#592]
Hey,
In JSON schema, we can do the following:
```
{
    "type": ["string", "null"]
}
```
Ref: https://json-schema.org/draft/2020-12/json-schema-core.html#section-7.6.1

Can we do the same with Typebox without using `Union`?

**Comment by sinclairzx81** [comment]
@mikicho Hi,

Yes, you can use Type.Unsafe to create custom schematics

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZJCOxbwAcgFcuPEVwz4oHAOZwAvCmEA6AKpKCVDAB5l+9kYA+cdhq4A+ABRIhTAAuOABtBidDBhwGT00GAF0KAEpZWUCMOHVNAm1dGGcjU3wiUnsMiCosr1ydPUNvIA)

```typescript
import { Type, Static } from '@sinclair/typebox'

const NullableString = Type.Unsafe<string | null>({ type: ['string', 'null'] })

type NullableString = Static<typeof NullableString>
```
This will work with Ajv (or other JSON Schema validator), however if you want to use the type with TypeBox validators, you will need to register the schematic as a Kind first.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoXowJQwHNgBnGKVHAaWADsATHAZRgEMZgBjOAXzgBmUCCDgByAAKl6XADZtgUAPQw8AIwgAPMQFgAUKEixEcAGptZAVwx9Bw0ZOl05C5aswbNSgG4XruvX0lJThCEnIMKDhaRn00TDCyClQAOmYMGAAKMQA5S1l5NVkMVih6IjEcTIB9HF8rDABKOABeAD44dwwIATh661aWlvFyMroKuAAfSb6-GyHhunzZRv19Lgg6cjg8grYikopy1txMFIBVLbYBDAAeUeOZpYK2zKQAbRiGAF0ALnFdoViqVypVOnh-u8xA9xmCxM9ZGJvnxVoE9F0dst9sCjuMTqwONxbl0epi9gcQeM2ms9OYGikAMIACwwXAA1plAdjDmMiDgxCyChAxM04HBgp0oNZ9HTrIyWezOViKbi+XAEaKxWKJRRpbS5vLWRyuSreThLIwMAJ6BgGM0JQILKQMPogA)

```typescript
import { Type, TypeRegistry, Kind, Static } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// Register Kind
TypeRegistry.Set('NullableString', (_, value) => typeof value === 'string' || value === null)

const NullableString = Type.Unsafe<string | null>({ [Kind]: 'NullableString', type: ['string', 'null'] })

type NullableString = Static<typeof NullableString>

Value.Check(NullableString, 'hello')   // true
Value.Check(NullableString, null)      // true
Value.Check(NullableString, undefined) // false
```
Hope this helps
S

**Comment by mikicho** [comment]
Thanks for the quick response!
I'm using Typeox with Fastify, so I guess this would work for me.
May I ask why this is not supported natively?

**Comment by sinclairzx81** [comment]
@mikicho Heya

> May I ask why this is not supported "natively"?

TypeBox schematics are selected to represent TS types in the most generalized form, not nessasarily the most compact form. The anyOf schematic (i.e. Union) can express all forms of union (including the nullable string above) however the dual type (as above) can only express simple primitives and doesn't extend to more complex types. JsonSchema can express the same structures many different ways, TypeBox formalizes on the most general way, but provides the Unsafe type to let less general forms to be expressed (noting certain schematic forms are required by some tooling)

Hope this brings some insight
Cheers
S

**Comment by mikicho** [comment]
Yes indeed. Thanks!!
