### ISSUE TITLE
[HELP] Export static types to d.ts file

### ISSUE THREAD

**Issue by SeanReece** [sinclairzx81/typebox#595]
Sorry if this is a stupid question. Really not sure if this is the right place to ask this but I'm really confused about this. Any help is appreciated.

I have an API where we are using typebox to generate JSONSchema for fastify validation and we're converting that to a static type using `Static<typeof MySchema>` and using that with `@fastify/type-provider-typebox`. This is working amazingly.

The problem comes when I want to take those static types and export them as an npm module so that the types can be used outside the API application. I just want plain static types in a d.ts without requiring typebox as an external dependency. 

### Simple reproducible example

*test.ts*
```ts
import { Type, Static } from '@sinclair/typebox'

const user = Type.Object({
  name: Type.String(),
  email: Type.String({ format: 'email' }),
  age: Type.Number({ minimum: 18, maximum: 99 }),
})

export type user = Static<typeof user>
```

Then I compile the declaration file like so

`tsc --declaration --emitDeclarationOnly test.ts`

typescript then compiles and outputs the `test.d.ts` with the typebox import and the full schema declaration

*test.d.ts*
```ts
import { Static } from '@sinclair/typebox';
declare const user: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
    email: import("@sinclair/typebox").TString;
    age: import("@sinclair/typebox").TNumber;
}>;
export type user = Static<typeof user>;
export {};
```

### Expected

*test.d.ts*
```ts
export type user = {
    name: string;
    email: string;
    age: number;
};
```

Is this possible? Is there some tsconfig that might help with this? Thanks in advance.

**Comment by sinclairzx81** [comment]
@SeanReece Hiya,

Might close off this issue as there isn't much that TB can do to have it generate the direct TS type. There is some [upstream work](https://github.com/sinclairzx81/typebox/blob/const/src/compiler/annotation.ts#L36-L147) being considered that would generate a raw TS annotation from TB type, but using this would require manually generating each type (and wouldn't involve the TS compiler) so not really a solution to .d.ts generation.

Happy to answer any other questions on this thread if you have anyway, but will close off for now.
All the best
S

**Comment by galah92** [comment]
Hi @sinclairzx81 I got the exact issue - my TB Static types are big and complex and I'm looking for a way to (ideally) export them to a file, or make it such that it'll be easy to explore the generated types.

Can you please share your recommendation on the matter? Thanks.
