### ISSUE TITLE
Type checking for SchemaOptions?

### ISSUE THREAD

**Issue by IndependentCreator** [sinclairzx81/typebox#596]
```
const shortString = Type.Object( {
    ss: Type.String( { maxLength: 3 } ),
} );
console.log( [ ...Value.Errors( shortString, { ss: "1234" } ) ] );

const shortStringTypo = Type.Object( {
    ss: Type.String( { maxlength: 3 } ),
} );
console.log( [ ...Value.Errors( shortStringTypo, { ss: "1234" } ) ] );
```
Results in:
 ```
[
  {
    type: 50,
    schema: { maxLength: 3, type: 'string', [Symbol(TypeBox.Kind)]: 'String' },
    path: '/ss',
    value: '1234',
    message: 'Expected string length less or equal to 3'
  }
]
[]
```
because the second object specifies `maxlength` instead of `maxLength`

Currently, typescript doesn't flag this mismatch. However, if I hack my local copy of typebox to remove `[prop: string]: any;` from the `SchemaOptions` interface, typescript will give me the compile-time message I'm looking for: 
```
Argument of type '{ maxlength: number; }' is not assignable to parameter of type 'StringOptions'.
  Object literal may only specify known properties, but 'maxlength' does not exist in type 'StringOptions'. Did you mean to write 'maxLength'?
```
Is there some way to achieve this without modifying the typebox code? Thanks!

**Comment by sinclairzx81** [comment]
@IndependentCreator Hi,

Unfortunately, I don't think there's much that can be done to make this more strict than it is (other than explicitly defining the options type externally). TypeBox doesn't restrict the kinds of properties assignable on SchemaOptions as users may need to assign all sorts of additional metadata on a schema above and beyond the formal properties. 

TypeBox should show type errors if the assigned property value is invalid, just not if the property is incorrectly typed (as this would be breaking for many users). One possible approach you can take is the following.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/LAKAlgtgDg9gTgFwAQG8kBUCeUCmAaJAZQTjADsBzAeSgTBjIGckBfJAMzhgiQHIABRuQDGAGwCGYOAHoE2HACMYAD16hQOZbERI5uIiTDCExUpRp0GzALxIACkYDWAHlPlqtekzyg+EcgAyOJQIABa8SAA+vrwQ4spBIeGgAHzqIMJWyOhItli4AHRulAAUaL5I-mSJFGEAXEgAjAAMPiBIlfGiwbWhDQBMzaBsjOJ0jOxgOMxuxsUelkwAlOlAA)

```typescript
import { Type, StringOptions } from '@sinclair/typebox'

export type StrictStringOptions = Pick<StringOptions,
 'minLength' |
 'maxLength'
>

const T = Type.String({ 
  minLength: 10,
  maxlength: 20
} satisfies StrictStringOptions)
```
Hope this helps
S

**Comment by IndependentCreator** [comment]
Hi Sinclair, 

Thanks very much for the prompt reply and for the hint about `satisfies`! 

My use case calls for strict enforcement of a specific set of options which are a mix of pre-defined options and some extras for my application. Users will need to create their own options objects in order to configure the system. It looks like there are a couple of things I could do to help them spot mismatches:

1. I could define the interface for the options using typebox, and throw an exception at runtime if the user's object doesn't match the interface. The downside to this is the extra runtime overhead for something (a programmer error) that we would prefer to identify at compile time. Perhaps I would recommend only enabling this during development.

2. I could document that they should use `satisfies MyAppOptions` when creating their Objects, in order to spot any potential mismatches at compile time. It's not ideal because users have to opt into it, but perhaps it's reasonable to expect that they will, if it is clearly documented. 

Anyway, thanks again and feel free to close this one.
IC
