### ISSUE TITLE
Is there any standard to validate mongodb _id without using ajv

### ISSUE THREAD

**Issue by sailingwithsandeep** [sinclairzx81/typebox#597]
``` 
const CustomObjectId = TypeSystem.Format('ObjectId', (value?: string) => {
            const data = new ObjectId((value as string).toString());
            return ObjectId.isValid(data);
        });
``` 
i tried something like this but it's converting _id to buffer when i do ```Cast```
What am doing wrong?

**Comment by sinclairzx81** [comment]
@sailingwithsandeep Hi,

There are a couple of ways you can approach this. One was might be to register a custom type that simply checks a value is a `ObjectId`. Another way (and possibly recommended depending on your use case) would be to use Transform Types that can both validate and decode strings into `ObjectId`.

The following are high level examples you can experiment with, just choose which ever approach best works for your application.

### Type Registry

The following assumes you have an existing Objectid, and you just want to check it's correct. It works by registering a new type Kind "MongoId" that performs an `instanceof` check on a value.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeQEYCsCmBjGBJAEzgF84AzKCEOAchAgDsBzCA1GgWAChRJZE4ANQCGAGwCumEuUrUaAAQDOwBtlHDgUAPQwAnmEyoIADy0A3MZM49w0eEgAq+zABo4AaRUE3TgwCVMJmBFGChdaQoqWiUVNQ1tPQMjY2tuX0wAoJCwgDoAZUwYAAoaAFlGFkIaNyKAfTcLCUwASjgAXgA+OEbJOBUQ4VVMCDIUDBx8AmbubmxGELhy5ghCdrh0nIBVBkVhMkwAHjQsXEIOoqQAbU8GAgBdAC5aJcqCGhJprln5+D8ARjWIiaOQAwgALHAAayKLxW3jgDEwAHcxidJkVmq04NicbjsVotHBQr0isE+jsYINsJhkKNjhNCJ9vhS4H4AEyAyyYUEQ7DQ2GENw0ABsAFYAAwAZn2kuFf0lwhwbOFBAALJLUH8AJyigAcuporQJ5DEiikpMUCIg8H6lKGtNRDKmMy4cx2EFE3NEECYRX+bnZzSAA)

```typescript
import { ObjectId } from 'mongodb'
import { Value } from '@sinclair/typebox/value'
import { Type, Kind, TypeRegistry } from '@sinclair/typebox'

TypeRegistry.Set('MongoId', (_, value) => value instanceof ObjectId)

const MongoId = Type.Unsafe<ObjectId>({ [Kind]: 'MongoId' })

const R1 = Value.Check(MongoId, new ObjectId())             // true (is instanceOf ObjectId)

const R2 = Value.Check(MongoId, '6503fe3613aec26d43b19588') // false (is not instanceOf ObjectId)

console.log(R1, R2)
```


### Transform Types

The following assumes you have a `string` value (representing a ObjectId identifier) and you want to validate that this string is correct AND convert into an ObjectId if it is. This approach is useful is you're receiving Mongo identifiers in Json, where it's easier to transmit the string identifier (noting ObjectId cannot be serialized to Json)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeQEYCsCmBjGBJAEzgF84AzKCEOAchAgDsBzCA1GgWAChRJZE4ANQCGAGwCumEuUrUaAAQDOwBtlHDgUAPQwAnmEyoIADy0A3MZM49w0eEgAq+qaQpVaSlWo3a9Bo8bW3FpacAC0EZFR0TGxcfEJiUnxwaEAsowshKmpcA4AFlJkEKKiEADuKkxwwIpwwnAwUMIMisVQ1H5SMPnC8OXNYHUNik1V9QxEvKKYIJgMMHUEOKxSLUTz2Ku5ZOKqMMCMdT199aUV9XCjUOMwEHCoUlsMZpiwmFML9w0QGDj4BAAdHlCjUGAw3lcxsw4M8YBpWrkGmA+jA3gw4OV8sBsPkanVxIoPo1vooifwek9oFB-jVlgtgGRgJD2iBTo92lJlltloDcskBYKhcKktxMMY+PBnqM4BlmBBCHAALx5ZyAhzNVqsgAUTgMgIAytCmNqkCiYGioAwAFy0AB6AG0AAxhACcwjCZAAgmEAGIAXQQACYACzEAAkNBIAEpo9w4HBAQARFbLbUWCRSJUAPjgEPKKD+uEI6csmFj8cTAFFVKtS5nlbmM5JAXcjTdmNqK1xuPyRf2B4O4rkAKqKYRMTB9ocz2dC3tcEJwADCNL6mGGcHo8rgvywuGARGuVW40vgh+VecwBbQ+4BXdbEHbVS7C6XGpabWgnWcdVxOAAa3qJgERlSkoQ7aoaTAGkiQWPpDgxbUGAgeBwNvf5FWg2D5nhA5GDjLgzzgL1LxETNAWXQpsAA7U5SyAgABo6UI3IAE0IHEWEWm40ohDLZNU26e5uVWS5jxhZspBUO5Lgw4sCFPI54AAITIgSUx5TA6MyBUmJYt9QkBYySMmXjRH4iiay0kk4E2MT0KLAEHmEGiwVkkZjSU1p4GXdSrNrNN6L05iVNYoijhKTBATKE0vVC5jl3Cpc51StKUkXUIjQQ7BNLEgAyOBsoObBrO2TLcgAdUKDFCVuTUvw6Rpf2Yyoek4+BRIIcZoDswLxm1YRhiMV5o2Y3ROK3YRdExWo8TuXJFHEVBRmAGBxDRIq8JxAAeBxc0JCcil64qcTy5Y9tzdYtpysqLv22zfnhFRGlBXJ7OWIhrq64kujqbVlgMSYetq8dJ0IlL0qhqGF14OwBFO3KhOYxG7pcGR3AUZRVHUTQdGcAIgkyuAxykRHzuknzMGEIgIDIG6StslQyEhH6iCaT9WWagxuC6PJL3JoSdq6OnZV0whcyXeSAUMkmiQZnE0bBUZqdp+nEaZhgWagPqtPZhqua6XnnBJgXttKwLMGF5xReCiW4CXCSmCAA)

```typescript
import { ObjectId } from 'mongodb'
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'

// ---------------------------------------------------------------------------------------
// MongoId
//
// The following is a transform type that wraps a string and implements decode and encode
// functions that allow a string to be converted into a objectId. The inner string contains
// a pattern which is used to assert the correct identifier format before decode.
// ---------------------------------------------------------------------------------------
export const MongoId = Type.Transform(Type.String({ pattern: '^[0-9a-fA-F]{24}$' }))
  .Decode(value => new ObjectId(value))
  .Encode(value => value.toString())


// ---------------------------------------------------------------------------------------
// Usage
// ---------------------------------------------------------------------------------------

// Creates a mongo objectid string
const id = new ObjectId().toString()

// Transform types check against the string representation (not the ObjectId representation)
const A = Value.Check(MongoId, id)

// You can call Value.Decode to decode a string value into a ObjectId
const B = Value.Decode(MongoId, id)

// ... And call Value.Encode to encode the ObjectId back into a string
const C = Value.Encode(MongoId, B)

console.log(A, B, C)

// ---------------------------------------------------------------------------------------
// StaticDecode & StaticEncode
//
// When using transform types, without decoding or encoding (as above), you may wish to
// substitute Static<T> usage for StaticDecode<T> and StaticEncode<T> to obtain the 
// encoded and decoded types (depending on usage)
// ---------------------------------------------------------------------------------------

import { StaticDecode, StaticEncode } from '@sinclair/typebox'

// Use StaticDecode instead of Static to infer decoded transform type
type T = StaticDecode<typeof MongoId> // ObjectId

// Use StaticEncode instead of Static to infer encoded transform type
type U = StaticEncode<typeof MongoId> // string
```

Hope this helps
S

**Comment by sailingwithsandeep** [comment]
@sinclairzx81 i think this what i neeed thanks for the quick reply 👍

**Comment by yudiz-sandeep** [comment]
Hey @sinclairzx81 i want to assign objectId to this type and it will throw type error and union type was bad experience for me what do you suggest ?

**Comment by sailingwithsandeep** [comment]
Hey @sinclairzx81  i want to assign objectId to this type and it will throw type error and union type was bad experience for me what do you suggest ?

**Comment by sailingwithsandeep** [comment]
@sinclairzx81 i am using this for now
```  userId: Type.Optional(
        Type.Union([
            Type.Unsafe<ObjectId>({ [Kind]: 'MongoId' }),
            Type.String({ pattern: '^[0-9a-fA-F]{24}$' }),
          
        ])
    ),```

**Comment by sailingwithsandeep** [comment]
Also one mroe thing do i have register for each schema or it will be register on each schema after defining it once

```
TypeRegistry.Set('MongoId', (_, value) => value instanceof ObjectId)
```
