### ISSUE TITLE
TypeCompiler support of formats? e.g. email?

### ISSUE THREAD

**Issue by lominming** [sinclairzx81/typebox#598]
I believe the `TypeCompiler` does not support formats? For example: `format: 'email'`?
`Type.String({format: 'email})` will invalidate a normal email string like `test@test.com`.

I cannot use ajv because it does not validate functions.

What is the best way to support validation of build-in string formats and functions?

**Comment by sinclairzx81** [comment]
@lominming Hi,

TypeBox doesn't include any strings formats by default, but you can add them with the FormatRegistry (this works for both Value and TypeCompiler modules)

```typescript
import { Type, FormatRegistry } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

FormatRegistry.Set('email', value => /^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i.test(value))

const T = Type.String({ format: 'email' })

const R1 = Value.Check(T, 'user@domain.com') // true

const R2 = Value.Check(T, 'not-an-email')    // false
```

I've ported a few common formats from the [ajv-formats](https://ajv.js.org/packages/ajv-formats.html) package which you can find [here](https://github.com/sinclairzx81/typebox/tree/master/examples/formats). You can use these formats in your project if you need them, but you will need to configure them manually.

```typescript
import * as Formats from './formats'

FormatRegistry.Set('email', Formats.IsEmail)
```
TypeBox may include these as defaults in later revisions. 
Hope this helps
S

**Comment by sinclairzx81** [comment]
@lominming Hiya,

Might close off this issue as the above should allow you to validate emails and other formats. I will be looking into adding a suite of default RFC compliant formats at some point into the future, but for now, the process of adding string format validation is somewhat manual. But if you have any questions on the above, feel free to reply on this thread.

All the best!
S

**Comment by lominming** [comment]
@sinclairzx81 Thank you for the prompt response. This works great! I may try to port over more formats down the road. Thanks!

**Comment by tsujp** [comment]
@sinclairzx81 I think it would make more sense for `FormatRegistryValidationFunction` to have the following type:

`(value: unknown) => boolean;`

over the current:

`(value: string) => boolean;`

This way `TypeGuard` and `ValueGuard` can more easily be used for narrowing as right now it would produce a union.

**Comment by sinclairzx81** [comment]
@tsujp Hi, the registry function's value argument should already be typed as string. It's definition is below.

```typescript
export type FormatRegistryValidationFunction = (value: string) => boolean
```

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgMWiAhjASgUwObADOMUAnnAL5wBmUEIcA5AAKHAB2AxgDbrBQB6GKTA4ARhAAejALAAoeaigZs+IiVIA6AMo4YACkYwcxRgBo4+gG7puAVxwBKOAF4AfHBIPnAgXAAWEFY4UEA)

![image](https://github.com/sinclairzx81/typebox/assets/3048342/74bba424-67db-4eef-8690-f239c72aaeee)

**Comment by tsujp** [comment]
> @tsujp Hi, the registry function's value argument should already be typed as string.

It is typed as `string` currently. Excuse me I derped out and misread the specification, the `format` key is only for strings hence `value: string`; I thought it was for strings or numbers both hence my suggestion for `value: unknown`.

All is good sorry for the confusion!

**Comment by ChuckJonas** [comment]
> I will be looking into adding a suite of default RFC compliant formats at some point into the future, but for now, the process of adding string format validation is somewhat manual

@sinclairzx81 ya, it would be great to have feature parity with `ajv-formats` or just the ones listed as "[defined" JSONSchema formats](https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-validation-00#rfc.section.7.3). 

I'm so close to having `typebox` as the only dependency in my project ❤️

**Comment by sinclairzx81** [comment]
@ChuckJonas Hi!

This is being planned for, and will be added once I've managed to put together full suite of RFC compliant (and DoS free) format checkers. The addition of formats will still require configuration (and still be principally opt in) with TypeBox supporting the following API.

```typescript
import { IsEmail, IsUuid } from '@sinclair/typebox/format'
import { FormatRegisistry } from '@sinclair/typebox'

// format functions can be called directly.
const R = IsEmail('user@domain.com')

// or configured on the format registry
FormatRegistry.Set('email', IsEmail)
FormatRegistry.Set('uuid', IsUuid)
```
I'm open to community help to gather the format checkers, so if you're really good with regex and/or reading through format RFC documents, am certainly open to having some help putting all these format checkers together :)

For now, you can use (copy/paste) the example formats in https://github.com/sinclairzx81/typebox/tree/master/example/formats. 

Hope this helps!

**Comment by ChuckJonas** [comment]
oh nice! I had a feeling you might already have something like these examples, but didn't manage to find it...  

I actually just did a very quick and dirty port of `ajv-formats` so that I could have full feature parity in the meantime

Here's a [gist (untested)](https://gist.github.com/ChuckJonas/74d9cfb6ba46244ef4eaa5818c06987b)   in case anyone else needs the same.
