### ISSUE TITLE
Build in support for es6 `Map` & `Set`

### ISSUE THREAD

**Issue by ole-thoeb** [sinclairzx81/typebox#606]
Similar to #280, I think it would be great if the `Map` and `Set` collections were built in.

Is this a feature that is wanted? In #280 some reasons against adding `bigint` are mentioned. Are these still relevant as `Type.BigInt()` now exists? 
I'm using typebox only with the TypeCompiler for schema validation, so I don't know how it would affect the other use-cases.

If this feature is desired, I will be happy to try to implement it myself.

**Comment by sinclairzx81** [comment]
@ole-thoeb Hi,

Unfortunately, Map and Set are still out of scope for TypeBox, however Transform types may provide the next best thing.

### Set&lt;T&gt;

[TypeScript Link Here](https://www.typescriptlang.org/play?target=9#code/JYWwDg9gTgLgBAbzgNQIYBsCuBTOBfOAMyghDgHIABAZ2ADsBjdVYKAehgE8xsAjCAB5sAbhhzkAsAChQkWIjgAVbrgLFSFGvSYt2XHvwGSp0hhDrV4AQTgBeJSoB0VqFFScAFMp6OAcphBebCgPAEpQ6Wk2NiU3C0JoMhc3TgAeOgCgqAA+OBgIOABlbBh0zODs03NLJTsHH0U46gSoEA8rCKk4OEcAEWwzABNsD1EsXFtcumwAdyKS0bFscOluxwBRRghhxfG7XIBtR2OxnABdTqqLeGGh7EG6tHG+ge2RxQAaOAOABi+ARi+ACYLnBovNShlAhUrjVsFthg97E8cBsEe8vrc3oNQt0wTFku4ytCctIgA)

```typescript
const A = Type.Array(Type.Number())

// Transform Array<number> to Set<number>
const T = Type.Transform(A)
  .Decode(value => new Set(value))
  .Encode(value => [...value])

const decoded = Value.Decode(T, [0, 1, 2]) // Set<number>
const encoded = Value.Encode(T, decoded)   // Array<number>
```

### Map&lt;K, T&gt;

[TypeScript Link Here](https://www.typescriptlang.org/play?target=9#code/JYWwDg9gTgLgBAbzgNQIYBsCuBTOBfOAMyghDgHIABAZ2ADsBjdVYKAehgE8xsAjCAB5sAbhhzkAsAChQkWIjgAVbrgLFSFGvSYt2XHvwGSp0hhDrV4AQTgBeJSoB0AJWxmoAEwAUyno4DKMFD0AOZeAJQANA5+AHKYILzYUBHh0tJsbEpQqBaE0GSu7h4APJbBdCHRdAlJUAB8cDAQcACyqGBlQaHVtcn1puaWSnYx2I6KOXkFXlZpUnBwjgAibhAe2F6iWLi2jXTYAO5tHV4A8rwAVm4wjth03djUW2LY4e-Si44Aoozrm9scHZGhdrgxbuoQL9Hs9AW95oMLPANmYNh5Rmgdis1hsfNEEAIAFxwACM0U4xIATHhwnBMidOuUenAaol+ojhvdUdh0fZMTgfn9cYpoij-h5aYspfSitBSkzKr02Q1pEA)

```typescript
const A = Type.Record(Type.String(), Type.Number())

// Transform Record<string, number> to Map<string, number>
const T = Type.Transform(A)
  .Decode(value => new Map(Object.entries(value)))
  .Encode(value => Object.fromEntries(value))

const decoded = Value.Decode(T, {x: 1, y: 2}) // Map<string, number>
const encoded = Value.Encode(T, decoded)      // Record<string, number>
```

Does this help?

**Comment by npdev453** [comment]
How do you imagine Map and Set validation should be work out of box? Every value should be equal to `master` Map/Set or only keys should be limited by name of some `Array` or values should be restricted by some type? 

Also I think there could be the same problem that this classes also cant be mirrored into/from JSON (mean `JSON.parse`), but you able free to create any custom types and his validators for any classes thorough TypeSystem.  

There are an example for `Set` that allow only string: https://github.com/sinclairzx81/typebox#types-1
```js 
import { TypeSystem } from '@sinclair/typebox/system'

const StringSet = TypeSystem.Type<Set<string>>('StringSet', (options, value) => {
  return value instanceof Set && [...value].every(value => typeof value === 'string')
})

const T = StringSet({})                              // Pass options if any

const A = Value.Check(T, new Set())                  // const A = true
const B = Value.Check(T, new Set(['hello']))         // const B = true
const C = Value.Check(T, new Set([1]))               // const C = false
```

--- 
But I see in the dark corner something like:
`Type.Class<>(Map)` or
`Type.Class<>(Map, (a: Map, b: Map)=>compareFn)`  or
`Type.Transform -> Object.toEntries -> validate as Type.Array()`

But seems like its more about real-time JS objects validations that cloud be little bit out of TypeBox built-ins design.

**Comment by npdev453** [comment]
> ### Set<T>
> ### Map<K, T>

@sinclairzx81, but can you show please how this Transform can work in context of validation? Can't found in docs. It can't be directly set to the scheme or how?

**Comment by sinclairzx81** [comment]
@npdev453 Hi, 

> How do you imagine Map and Set validation should be work out of box? Every value should be equal to master Map/Set or only keys should be limited by name of some Array or values should be restricted by some type?

Map and Set won't be added to TypeBox as they are standard library collection types (not JSON or CBOR representable types). They are analogous to List<T> (C#) or Vec<T> (Rust) or other higher language construct that provides operations on data (and not constructs that can be naturally encoded for transmission over the wire). Because Map and Set are class instances, and provide operations on collections (and because there is no well defined way to serialize these constructs in a cross language interoperable way) I am very reluctant to add them.

Note that exceptions are made for Function, Constructor, Promise and Iterator as these types are useful to describe callable interfaces. For an example of where they are used, see https://github.com/sinclairzx81/sidewinder

> but can you show please how this Transform can work in context of validation? Can't found in docs. It can't be directly set to the scheme or how?

### Transforms + Reader and Writer

The following implements a generic Reader and Writer type that accepts instances of `TSchema`. Internal to these types, there are calls to the Encode and Decode functions which remap the value given by the user into a wire format able to transmitted (or written to disk) in some serialized fashion. 

In the example below, the caller of these types reads and writes `Set<number>`, but the internals of these types will automatically convert the Set into a Array prior to either sending or writing to disk. 

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYGELmAGwygBoV1sALDAYwGs4BfOAMylzgHIABAZ2ADtq+AIbAoAehjkARhAAe46rjAEiHALAAoUJFiIymUsgDK1KiGGljMYTGDUAIjQgATDIxZsQnXgKGiJKUxZOQ1NLXFxOABaWLj4hMSk5JTUlIiogHUoYBgiDJi0ouKS4q0MOV14fx4eOGzcogAeZDgKvP4XOpMzDAsAPkQtODgoDGEXCH58VDgAYl66AC4DShpaFv7huCV+HhgoAFdqGGgACh5eixXkAEohzRGRmApgHgA6Bao6OABeVZweEIUHegJUhAuV2Et22DG2AHccnkzgA3YT4Q4YFbWWz2JxKNybe4IbYjXb7NqCVwYFx-OAvN6fRa0d4AUSpblR6Mx90icHhBHw9IobHhcGAzDgaIx7jecH4EHgEElPXMwlJcD5iMalIJNLgLlswnpEDgPFwGHhVDGsK0cM0fNKTudToKACVxm4oAUXb6-UlypVoNURLU4B6Js1Wu0MJ1uqY1YMSY9Rp6pjN5sybuQsN8NsgtinyQdjqcoJC1TdiRqGR8vus6WhMGDVCCWxDLmqYSn7SMxhMzrdsTY7I5nISCw8njsphTY3raf9+Id8ELp+v13z+7T59TaYabJ52OaQJbrRgNWMYIcoPxhYz63R3vjqWdd24XLyogLV8LReLJWlTFxTqBUlRVBM+nVHs7R9f14L9ApWTkYRwEIOCEMw0otGLFBG3Id5kCgYQ9mYaAQDOJsMHeABBKBiNQSiCIAOUOEBpCIQdbm7EZn3HDAuRlP5Bn4S04GMDAYEEnkeLgNkOQEoD3F+QYAG13g0pSAF1uxw2d4G3Ig6VEsUIy9Sju1w7U8igYyxIaGyLL0vZ4B4SS6UMkFt0HLRrKId4-IuSTbiAA)

```typescript
import { TypeCompiler, TypeCheck } from '@sinclair/typebox/compiler'
import { Type, TSchema, StaticDecode } from '@sinclair/typebox'

// ----------------------------------------------------------------
// Writer
// ----------------------------------------------------------------
export class Writer<T extends TSchema> {
  readonly #check: TypeCheck<T>
  constructor(schema: T) {
    this.#check = TypeCompiler.Compile(schema)
  }
  write(value: StaticDecode<T>) {
    const encoded = this.#check.Encode(value) // will throw if value is not of TSchema
    // write encoded data to somewhere
  }
}
// ----------------------------------------------------------------
// Reader
// ----------------------------------------------------------------
export class Reader<T extends TSchema> {
  readonly #check: TypeCheck<T>
  constructor(schema: T) {
    this.#check = TypeCompiler.Compile(schema)
  }
  read(): StaticDecode<T> {
    const encoded = null               // read encoded data from somewhere
    return this.#check.Decode(encoded) // will throw if value is not of TSchema
  }
}
// ----------------------------------------------------------------
// Example
// ----------------------------------------------------------------
const T = Type.Transform(Type.Array(Type.Number()))
  .Decode(value => new Set(value))
  .Encode(value => [...value])

const reader = new Reader(T)
const writer = new Writer(T)
const set = reader.read()
writer.write(set)
```
Note in the above, the `read()` or `write()` will `throw` if either the Encode or Decode functions fail to type check. You can think of these functions as analogous to Zod's `parse()` function which throws if data is invalid. Note that the data is checked against the schema representation (in this case, an array of numbers), and not the Set<number> object.

Documentation on these functions can be found

https://github.com/sinclairzx81/typebox#types-transform
https://github.com/sinclairzx81/typebox#values-encode
https://github.com/sinclairzx81/typebox#values-decode

Does this help?

**Comment by ole-thoeb** [comment]
Ok, I understand that when it comes to serialisation `Map` and `Set` are kind of strange.

For validation, i got a generic version using custom types
```ts
const MapTypeImpl = TypeSystem.Type<Map<any, any>, { key: TypeCheck<any>; value: TypeCheck<any> }>(
    "Map",
    (options, value) => {
        if (!(value instanceof Map)) {
            return false
        }
        for (const [key, val] of value) {
            if (!options.key.Check(key) || !options.value.Check(val)) {
                return false
            }
        }
        return true
    }
)

export function MapType<K extends TSchema, V extends TSchema>(key: K, value: V): TUnsafe<Map<Static<K>, Static<V>>> {
    const keyCheck = TypeCompiler.Compile(key)
    const valueCheck = TypeCompiler.Compile(value)
    return MapTypeImpl({ key: keyCheck, value: valueCheck })
}
```
It is not super straightforward and a bit cumbersome to need the wrapper function. I just thought that a version provided by the library greatly improves the experience.

Thanks for all the replies! I never considered using transformers. I'll check how it fits my use-case.

**Comment by sinclairzx81** [comment]
Hey, all good. 

I do appreciate some of the TB abstractions are quite low level and do need some implementation to use effectively, mostly this is to satisfy integration use cases, but if it's helpful, maybe take a look at the following examples where type-safe versions of Map, Set, Array have been implemented for reference (perhaps helpful to orientate towards anticipated usage of TB)

https://github.com/sinclairzx81/typebox/tree/master/examples/collections

Will close off this issue for now, but if you have any other questions, feel free to ping on this thread.
All the best!
S

**Comment by npdev453** [comment]
@sinclairzx81 
Ah, I see that Decode fn was added to TypeCheck not for a long time ago. Btw, I don't see that in docs, this why I ask you question about validation pur Transformers. 

Also seems like I can't validate something like this? 
```ts
const T = Type.Transform(Type.Array(Type.Number()))
    .Decode((value) => new Set(value))
    .Encode((value) => [...value]);

const inputSchema = Type.Object({
    stateName: Type.String(),
    setUno: T,
    setDos: T,
});

const inputValidator = <T extends TSchema>(schema: T, input: Static<T>) => {
    return TypeCompiler.Compile(schema).Errors(input);
};

const result = inputValidator(inputSchema, {
    stateName: 'a',
    setUno: new Set(),
    setDos: new Set().add(2),
});

console.log('inputValidator', result);
// > ValueErrorIterator { iterator: Object [Generator] {} }
```

**Comment by sinclairzx81** [comment]
@npdev453 Heya, 

Just back to your original query (and based on your last example). If you just want to validate `Set<T>` or `Map<K, T>`, you can implement custom types for these (except it's very complicated to do so as you need to handle the structural type, the validation logic, dependent schematics and the inference)

The following is how I'd implement these as custom types (a very scary raw implementation below)

```typescript
import { Type, Kind, TSchema, Static, TypeRegistry } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// ------------------------------------------------------------------------
// MapType<K, T>
// ------------------------------------------------------------------------
export interface TMapType<K extends TSchema = TSchema, T extends TSchema = TSchema> extends TSchema {
  [Kind]: 'MapType',
  static: Map<Static<K>, Static<T>>
  key: K,
  value: T
}
TypeRegistry.Set('MapType', (options: TMapType, input: unknown) => {
  if(!(input instanceof Map)) return false
  for(const [key, value] of input) {
    if(!Value.Check(options.key, key)) return false
    if(!Value.Check(options.value, value)) return false
  }
  return true
})
export function MapType<K extends TSchema, T extends TSchema>(key: K, value: T): TMapType<K, T> {
  return { [Kind]: 'MapType', key, value } as any
}
// ------------------------------------------------------------------------
// SetType<T>
// ------------------------------------------------------------------------
export interface TSetType<T extends TSchema = TSchema> extends TSchema {
  [Kind]: 'SetType',
  static: Set<Static<T>>
  value: T
}
TypeRegistry.Set('SetType', (options: TSetType, input: unknown) => {
  if(!(input instanceof Set)) return false
  for(const value of input) {
    if(!Value.Check(options.value, value)) return false
  }
  return true
})
export function SetType<T extends TSchema>(value: T): TSetType<T> {
  return { [Kind]: 'SetType', value } as any
}

// ------------------------------------------------------------------------
// Usage
// ------------------------------------------------------------------------
const T = Type.Object({
  map: MapType(Type.String(), Type.Number()),
  set: SetType(Type.Number())
})

type T = Static<typeof T>

const R = Value.Check(T, {
  set: new Set([1, 2, 3]),
  map: new Map([['A', 1], ['B', 2]])
})

console.log(R) // true
```
So this will validate `Map` and `Set` (and give correct type inference) but it's something you would want to hide away as some utility module somewhere (and it's very awkward to implement types this way), Just note that TypeBox provides many different ways to approach type validation, schema construction, type mapping and various other aspects. Unfortunately to be flexible enough to support all these cases (some documented, some not), a lot of the implementation can get fairly in depth.

However if TypeBox were to implement Map and Set (as per suggestion), the internal implementation would look a lot like the above example. So if you just want to support Map and Set as extension types, the above should handle that for you. For mapping from JSON to Map and Set (for example, receiving Json data via Http Post to transform into Map and Set), use Transforms.

It's complex, but do hope this helps.
All the best
S
