### ISSUE TITLE
`TypeSystem.Type` options lose prototype when embeded in `Type.Object`

### ISSUE THREAD

**Issue by ole-thoeb** [sinclairzx81/typebox#609]
I noticed that the code I posted in #606 fails with a runtime error if embedded in a `Type.Object`, then compiled with `TypeCompiler` and run.
A simpler example with a (strange) `Set` validator:
```ts
const SetType = TypeSystem.Type<Set<any>, { element: TypeCheck<any> }>("Test", (options, value) => {
    return value instanceof Set && [...value].every(value => options.element.Check(value))
})

const StringSet = SetType({ element: TypeCompiler.Compile(Type.String()) })

const Obj = Type.Object({
    set: StringSet,
})

const setCheck = TypeCompiler.Compile(StringSet)
const set = new Set(["a", "b", "c"])
setCheck.Check(set) // true as expected

const objCheck = TypeCompiler.Compile(Obj)
const obj = { set }
objCheck.Check(obj) // expected true but fails with TypeError
```
The above code fails at runtime with `TypeError: options.element.Check is not a function`.
Tested in version `0.31.17`.

When checking in the debugger I saw that `options.element` has no longer a prototype. It was probably lost during some copy operation, but I was unable to confirm that.

**Comment by sinclairzx81** [comment]
@ole-thoeb Heya,

This implementation is generally against the design of TypeBox which preferences keeping validation logic and schematics separated. TypeBox needs to clone and and remap schematics so it cannot provide assurances that the prototypes will be retained, so mostly you want to ensure that only metadata that describes the type is stored in the schema, and you want to move validation routines "outside" of the schematic.

Some of the implementation requirements you've mentioned have been right up against the extents of TypeBox's design (and the TypeSystem module itself is due for an update to better capture these kinds of requirements (specifically generic types expressed via TypeSystem.Type)), but the following should handle this particular use case while keeping validation and schematics separated. 

```typescript
import { TypeSystem } from '@sinclair/typebox/system'
import { TypeCompiler } from '@sinclair/typebox/compiler'
import { Type, Static, TSchema, SchemaOptions } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// incremented per generic instance
export let SetTypeOrdinal = 0 

// options for the set
export interface SetTypeOptions extends SchemaOptions {}

// creates a new set type
export function SetType<T extends TSchema>(schema: T, options: SetTypeOptions = {}) {
  const elementCheck = TypeCompiler.Compile(schema)
  return TypeSystem.Type<Set<Static<T>>, SetTypeOptions>(`SetType<${SetTypeOrdinal++}>`, (_, value) => {
    return value instanceof Set && [...value].every(value => elementCheck.Check(value))
  })(options)
}

type A = Static<typeof A>
type B = Static<typeof B>

const A = SetType(Type.Number())
const B = SetType(Type.String())

console.log(A, B) // note the `Kind`

const R1 = Value.Check(A, new Set([100, 200]))
const R2 = Value.Check(B, new Set(['1', '2']))

console.log(R1, R2)
```
Note that the above implementation needs to track an `ordinal` per generic instance type (as `Set<string>` and `Set<number>` are two seperate types). There are planned updates here to make this TypeSystem.Type a bit more intuitive when constructing generic types (and extending TypeBox types has been an ongoing effort to get right), but the above is one way you can approach it under the current design.

However, for more advanced cases, I would recommend looking at the [TypeRegistry](https://github.com/sinclairzx81/typebox#typeregistry-type) which provides raw access to TypeBox's internal register (and from which the TypeSystem.Type  API is calling into). I have generally found this to be far more flexible than using TypeSystem.Type, and you can find a full reference implementation of how to use it https://github.com/sinclairzx81/typebox/blob/master/examples/typedef/typedef.ts

Will close up this issue for now as retaining prototypes and functions falls outside TypeBox's design (so not a bug), but I am happy to continue this conversation to perhaps discuss a better overall design for TypeSystem.Type (as this function should provide this functionality in a more intuitive way), however getting the API right has proved elusive. 

All the best
S

**Comment by ole-thoeb** [comment]
I agree that the solution is strange and feels a bit hacky.  It was the best solution I could come up with. The other basically being the one you are suggesting. While it does not crash, it feels super hacky to spam the TypeRegistry. 
This was the motivation why I asked in #606 if a built-in solution is planned.

I don't quite see how using the TypeRegistry directly can solve my problem. If I want to use compiled validators inside, I still need to pass them through the options or create many different types.

There are workarounds like putting a plain function in the schema. An adapted version of your `SetType`  from #606:
```ts
interface TSetType<T extends TSchema = TSchema> extends TSchema {
    [Kind]: "SetType"
    static: Set<Static<T>>
    value: T
}

TypeRegistry.Set("SetType", (options: TSetType & { checkValue: (v: unknown) => boolean }, input: unknown) => {
    if (!(input instanceof Set)) {
        return false
    }
    for (const value of input) {
        if (!options.checkValue(value)) {
            return false
        }
    }
    return true
})

function SetType<T extends TSchema>(value: T): TSetType<T> {
    const check = TypeCompiler.Compile(value)
    return { [Kind]: "SetType", value, checkValue: v => check.Check(v) } as any
}
```

I guess, what I actually want is to write my own generic types that can be composed with other types and compiled to fast check function. I read somewhere that work is being done on a prototype that goes in this direction. Finding a good API for that seems really hard.

In the meantime, I think the README under [TypeRegistry](https://github.com/sinclairzx81/typebox#typeregistry-type) could benefit from an example that gets passed another schema.
Also, a note somewhere that you are not supposed to pass classes to options/schemas might be helpful.
