### ISSUE TITLE
Infer a type based on an Enum value

### ISSUE THREAD

**Issue by ErikTheBerik** [sinclairzx81/typebox#612]
Is it possible for TypeBox to infer the type of a field based on the current value of a different field?
Basically, I want to do the following:

```ts
enum InternalType {
    Number = "number",
    String = "string",
    SpecialType = "special_type"
}

const SomeType = Type.Union([
    Type.Object({
        Type: Type.Literal(InternalType.Number),
        Data: Type.Number()
    }),
    Type.Object({
        Type: Type.Literal(InternalType.String),
        Data: Type.String()
    }),
    Type.Object({
        Type: Type.Literal(InternalType.SpecialType),
        Data: Type.Object({ Value: Type.String() })
    })
]);
type SomeType = Static<typeof SomeType>;

// This shows the error because Data should be a number
const wrongType: SomeType = {
    Type: InternalType.Number,
    Data: "wrong"
};

// this is fine
const correctType: SomeType = {
    Type: InternalType.Number,
    Data: 42
};
```

Without having to "duplicate" the Type.Object. Since if I decide to change the general structure, I'll have to change it in 3 different places. So I'd like to define SomeType as:

```ts
Type.Object({
    Type: Type.Enum(InternalType),
    Data: Type.Union([Type.Number(), Type.String(), Type.Object({ Value: Type.String() })])
});
```
or

```ts
Type.Object({
    Type: Type.Enum(InternalType),
    Data: Type.Any()
});
```

And then separately tell TypeBox  what type should the field "Data" be based on the value of the field Type. Is this at all possible?

**Comment by sinclairzx81** [comment]
@ErikTheBerik Hi,

> Is it possible for TypeBox to infer the type of a field based on the current value of a different field?

Yes, you can perform conditional type mapping in TypeBox which can handle "some" cases, but may not be applicable in this case. Some information on the feature can be found https://github.com/sinclairzx81/typebox#types-conditional

> And then separately tell TypeBox what type should the field "Data" be based on the value of the field Type. Is this at all possible?

There are ways to map associated types in TypeBox (i.e. Literal to Data Type), but would recommend keeping things simple and explicit in this case as Unions with literal discriminator keys are very common and don't require much in the way of boilerplate. However if you want to experiment, the following conditionally maps from one of the Literal values into one of the Data types. 

```typescript
import { Type, Static, TLiteral } from '@sinclair/typebox'

export enum InternalType {
  Number = "number",
  String = "string",
  SpecialType = "special_type"
}

// Maps a Literal to Data Type
export const LiteralToData = <T extends TLiteral>(value: T) => {
  return (
    Type.Extends(value, Type.Literal(InternalType.Number), Type.Number(),
      Type.Extends(value, Type.Literal(InternalType.String), Type.String(),
        Type.Extends(value, Type.Literal(InternalType.SpecialType), Type.Object({ Value: Type.String() }),
          Type.Never())))
  )
}

const SomeType = Type.Union([
  Type.Object({
    Type: Type.Literal(InternalType.Number),
    Data: LiteralToData(Type.Literal(InternalType.Number))
  }),
  Type.Object({
    Type: Type.Literal(InternalType.String),
    Data: LiteralToData(Type.Literal(InternalType.String))
  }),
  Type.Object({
    Type: Type.Literal(InternalType.SpecialType),
    Data: LiteralToData(Type.Literal(InternalType.SpecialType))
  })
]);
type SomeType = Static<typeof SomeType>;
```
You may be able to use this as a basis for further mapping, but again, would recommend keeping things simple for this usercase.

Hope this helps
S

**Comment by ErikTheBerik** [comment]
Thanks a lot for your response @sinclairzx81 

I will go with the union even if there is some extra boilerplate (it is way easier to understand, so it's definitely the right approach), but I might play around a bit with the code you shared :)

I don't quite understand what Extends, Extract and Exclude do, so this will be a good time to read on it a bit. 

Thanks again.
