### ISSUE TITLE
How do I make this typecheck strictly?

### ISSUE THREAD

**Issue by thelinuxlich** [sinclairzx81/typebox#616]
I don't know why this is happening:

![image](https://github.com/sinclairzx81/typebox/assets/5043/32b8a44d-d2d0-4449-b3ff-02796eefc03a)

**Comment by sinclairzx81** [comment]
@thelinuxlich Hi. 

This is actually a characteristic of TypeScript, Consider the following examples

---

### TypeScript Example

Not that TypeScript is permissive of additional properties if the assignment is indirect.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKlC8UDeUCGAuKA7ArgWwCMIAnKAXwFgAoagMxywGNgBLAeyynqYAoA3VABscETDACUySjSoB6WVAC0y6tUYcAzsCgDh0RCgxQAjABooBTACZyUeVADkBB1BYa0AEw8tWHIQAViNkhiUFUqbkZ+IRFJKHiExKT4+zYAa3DInkNMMwtrcjjkuwUSIOJMAEFiAHN8CCxtNlooUEhHHOx8ImIAbnyuwhJ+shc3bDZtVA0NFhqsVAJBaGA2KGpiza2k+zBUYlQ8CGASKGbW8GgHGAcAOiA)

```typescript
type T = { a: number }

function func(value: T) {}

// ---

const value = { a: 1, b: 2 } // 'b' is additionalProperty

func(value)                  // ok - indirect assignment

func({ a: 1, b: 2 })         // error: Argument of type '{ a: number; b: number; }' is not assignable to 
                             // parameter of type 'T'.
```

---

### Inline Fastify Route Example

So from the above, you can update your Fastify route to pass the value directly on the send function. This will give a type error. 

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgMQIYGcbAGYE8AKANgK4DmwAdgILq4UDGAKrmAKYBGEAHnAL5zYoEEHADkAAWwYseAPQwWrALRghAN2AATVlCUK2nLqICwAKFCRYiOMzZ8BQkRPSV6hVMCjzFhk6bP0EBSYcELEMKwAXCjSOAQk5NS0DLYc3HAAvHAYdPRwABTYAJSZAHyIZnACAHSkrDD5AESy7IQQ9ADW9AAWHhQA+jBQqMGo9FhB6LKRWo0ANBWmVVXoPawgqNEIlctVYKjDIOjRqdUA8uwAVqzj+dtLu8taJ4rVAMpDlKT5RXM7u7xfv9llBWOhIMEootHssAEwABnhLzY5yuNwawJhSF66G6yNY70+FG+JV4C0xjyQqE0mmAEwoqEI+CEbFgwDB0SkhHQrD4FKqRQpvGBwoeZOyyTy+VBAEcFqD0CUMuV7rtQTBiFAKKEwdUeRRNHc4Di8WJRAtMKgNcc4LC+IKHlVZLIYa63Y8AHpwKhQUjEECsCjwCDYOD6XmibEYU2YKBfADccEt1uiFH97B0id4ojgwHQcAoEHgwOd7rL7owLlIDNavJgEDg+0O9R0cBDYcUYijuOisYTfFE1R2gLMvCAA)

```typescript
import { FastifyPluginAsyncTypebox } from '@fastify/type-provider-typebox'
import { Type } from '@sinclair/typebox'

const route: FastifyPluginAsyncTypebox = async (f) => {
  f.get("/blockchain_transactions/:id", {
    schema: {
      params: Type.Object({
        id: Type.String(),
      }),
      response: {
        200: Type.Object(
          { hash: Type.String() }, 
          { additionalProperties: false }
        )
      }
    }
  }, async (req, res) => {
    return res.send({ hash: '', status: 2 })
    //                          ^ Argument of type '{ hash: string; status: number; }' is not 
    //                            assignable to parameter of type '{ hash: string; }'.
  })
}
```

---

### Exterior Fastify Route Example

Alternatively, you can extract the params and response types into exterior types, and use type assertions when initializing the value.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgMQIYGcbAGYE8AKANgK4DmwAdgILq4UDGAKrmAKYBGEAHnAL5zYoEEHADkAAWwYseAPQwWrALRghAN2AATVlCUK2nLqICwAKFCRYiOMzYAaOAGUYqLPT4ChIiekr1CqMBQ8oqGJqZm+qxwAEKEEPQA1vQAFoEUjFCoFOio9FgQFABKrACOxKyY+KhZIOhwALxOLm4APFEQ2LHxSanpmdm5+cCFJeWVMNW16AB8kYrdCclplAM5eQXFlZA5rABMAAwHjc2uwPTtip2LvSsZWevDo9uF6PtHcxGm9K-wcUt9VYPIabMYVKo1VB1E62VgAOgA8uwAFasfIACgQZjgcC0AC4bIo4c4oJRSOiAJRmXhU76-G7LfrAjYjLboHZvQ7HJqwxEotEwTHYnFwNLoFIE3kksmU6kOJCoTSaYCbVCEfBCNiwYCVAlSQhvPi0sw-HLwITEGCsAloTA4AgkcjUWgMWGGE4YOjudHYCmNGaIYXYOGkViCgBEsnYPUZlAA+jBmU8crI8Vpw-LhTj0KlWCBUASsaYRSKwJC6gT-rcmYMWc9xhDpnYsyKoC9doWWyWuZWY4D7rXkyV2a93gcu3wW7xhbwHJ6GHB0W3Sg42+g-Q0A0WW6bMHA18RCDBewC7msQazhxyxyckGKJWJRA5MK5iOgCXtJ8WRbJZCX-wBgFAcBIEgQAenALa-qBMFwEiqL5HAhAqjoapwPmuBwIUhCYeyaL2nAiQUBAADuFBwKoEBalglRzhQmhiC+MBvqIcCaBAlSQd+OLQbBIHEfArBcMAe6UHAURiHeGAPpgpIUKQADcfDhCWbbMVA5FrnCbz0UulSHjAtI4jS1JAA)

```typescript
import { FastifyPluginAsyncTypebox } from '@fastify/type-provider-typebox'
import { Type, Static } from '@sinclair/typebox'

type BlockchainTransactionRequestParams = Static<typeof BlockchainTransactionRequestParams>
type BlockchainTransactionResponse200 = Static<typeof BlockchainTransactionResponse200>

const BlockchainTransactionRequestParams = Type.Object({
  id: Type.String()
})
const BlockchainTransactionResponse200 = Type.Object({
    hash: Type.String()
}, { additionalProperties: false })

const route: FastifyPluginAsyncTypebox = async (f) => {
  f.get("/blockchain_transactions/:id", {
    schema: {
      params: BlockchainTransactionRequestParams,
      response: {
        200: BlockchainTransactionResponse200
      }
    }
  }, async (req, res) => {

    const result: BlockchainTransactionResponse200 = { hash: '', status: 2 }
    //                                                           ^ 
    //                        Object literal may only specify known properties, and 'status' does 
    //                        not exist in type '{ hash: string; }'
    return res.send(result)
  })
}
```
Optionally, you can use the `satisfies` keyword here which tends to give better indication as to what properties are additional.
```typescript
const result = { hash: '', status: 2 } satisfies BlockchainTransactionResponse200
```

---

### AdditionalProperties and UnevaluatedProperties

Note that the additionalProperties and unevaluatedProperties constraints do not contribute to the type inference result. These are runtime constraints only and will only implicate the runtime checking of values (not static assertions of typed value). To ensure static assertions, implementations should use TypeScript techniques (as above) to ensure no additional properties are passed.

Hope this helps
S

**Comment by thelinuxlich** [comment]
Thanks a lot for the thorough explanation @sinclairzx81 , I can understand now how Typebox behaves. Unfortunately I think I will have to look into other alternatives, as it doesn't feel right for me that I'd need to manually cast the type of the response, I'm basically doing the compiler's job :(

**Comment by thelinuxlich** [comment]
Actually I'm very wrong about this, it's just how TS behaves, pardon me.
