### ISSUE TITLE
Puzzling type inference with intersection types

### ISSUE THREAD

**Issue by cwhitemaddox** [sinclairzx81/typebox#619]
Hi @sinclairzx81,

I ran into something puzzling with the type inference of Typebox intersection types and I was wonder if the following example is expected behavior. If so, are you able to shed some light on why?

Here's a minimal case illustrating the surprising type inference:

```ts
import { Static, Type } from "@sinclair/typebox";

enum ObjectType {
  Type1 = "type1",
  Type2 = "type2"
}

export const object1 = Type.Object({
  type: Type.Literal(ObjectType.Type1),
});
export const object2 = Type.Object({
  type: Type.Literal(ObjectType.Type2),
});

const intersection = Type.Intersect([
  object1,
  object2,
]);
export type Intersection = Static<typeof intersection>; // type Intersection = never
// that wasn't what I was expecting...


export const object3 = Type.Object({
  type: Type.Literal(ObjectType.Type1),
});
export const object4 = Type.Object({
  type: Type.Literal(ObjectType.Type1),
});

const intersection2 = Type.Intersect([
  object3,
  object4,
]);

export type Intersection2 = Static<typeof intersection2>;
// type Intersection2 = {
//   type: ObjectType.Type1;
// } & {
//     type: ObjectType.Type1;
// }
// huh... that works as expected...
```

If I swap out the the enum values in the objects for literal strings (e.g. change `Type.Literal(ObjectType.Type1)` to `Type.Literal("type1")`) it doesn't change the behavior.

**Comment by sinclairzx81** [comment]
@cwhitemaddox Hi,

This is actually standard behavior for intersections. Consider the following.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZRgQxsAxgGjgFQE8wBTOAXzgDMoIQ4ByAAQGdgA7LAGzWCgHoYxEgCMIADwYBYAFCz+-AsORYowMDFkJZcOENIE4AXkR7hALkYBBBhTgAyU-pKWGAIVuUFZg-mNx2EgA3EihZcll5RSJSNwktHTgsCHYWeD8TGJIAOgBJdhhQlhIsGAAKAG1E3SzsgHkRACsS8qRnS1qAGWBCqDQuMoYbAEoKYZxqpVJ6ppaytospnO7e-sGPUfJhxIBdYYBuSJldZ0MTVAxsAB5nCCoCAD5dZ5fX71OMgODQ8KO-uRkQA)

```typescript
import { Static, Type } from '@sinclair/typebox'

// TypeScript
{
  type T = { type: 'A' } & { type: 'B' } // type T = never
}

// TypeBox
{
  const T = Type.Intersect([
    Type.Object({ type: Type.Literal('A') }),
    Type.Object({ type: Type.Literal('B') })
  ]);

  type T = Static<typeof T>              // type T = never
}
```

---

### Explanation

This behavior relates to how TypeScript evaluates illogical types as `never`. For example, consider the intersection of two distinct primitive types

```typescript
type T = string & number    // never - cannot be both string AND number
```
TypeScript is permissive of these kinds of intersections (and doesn't forbid their construction). Instead the compiler will naturally evaluate the type as `never` when asserting at usage sites. Consider the following function which replaces primitives with two string literal types, A and B.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygCgG4EMA2IKAXIgOQCCZiAZOQEJkCUiA3gL6ID0XyAFjDSJQkWAkQRcYMHCiIARigkF8KACYBYAFDbUGTJWaJjJ02ZM9EKAE7W41xAFpEg8lQA0CkHJlyyjbV10LH8jc3DTSxs7B2dXUM95b0RfNzIgA)

```typescript
function test(value: 'A' & 'B') {} // this function cannot be called

test('A')                  // error - is 'A', but not 'B'

test('B')                  // error - is 'B', but not 'A'
```
If we extrapolate this concept out to object types (as per your example), you can see that the intersection of two objects with the same property key but with a non-intersectable property type would yield a similar illogical type.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygCgG4EMA2IKAXIgN7ICeADiYgOQCC9iAvogGTlW2n0BCLVgEpyrALAAoKagyYKUGnSZDRidRsQB6LYhQAnfXH2IAtDxSIYaRGDhRE-KTPRYFSvoLZrN6nXsNjMwsrGzsHRiA)

```typescript
function test(value: { type: 'A' } & { type: 'B' }) {}

test({ type: 'A' })        // error - type is not B

test({ type: 'B' })        // error - type is not A
```

---

### Relation To Json Schema

As with TypeScript, Json Schema is also allows for the expression of illogical schemas, with an illogical schema resulting in a schematic that can never validate against a value.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKlC8UDkBBJUBkyBCSCwAUIQPTFQCWAzlMABbSUCGAttI9YwEYD2AbtAAoAxowB2o7sCidoPOsjRQxAExxIAlIUJDuoylLiIA3koA2pgPIAzAFxQA2iZ17gd1OgC+AGihPd+t1woDwBdYKA)

```typescript
type T = 'A' & 'B'

// is the same as above (cannot be both 'A' and 'B')

const T = { allOf: [{ const: 'A' }, { const: 'B' }] }
```
TypeBox allows for these types inline with TypeScript and Json Schema

Hope this helps
S

**Comment by cwhitemaddox** [comment]
Hi @sinclairzx81,

This makes total sense. I appreciate the explanation. Looking back at the code I pulled my minimal example from, I should have been using `Type.Union()` for that section -- using `Type.Intersection()` is illogical (as you're `'A' & 'B'` example demonstrates).

:pray: Thanks again
