### ISSUE TITLE
Mapping types erasing schema type

### ISSUE THREAD

**Issue by tsujp** [sinclairzx81/typebox#622]
I'm attempting to write a typed router and I'm stuck on what I think is a TypeBox issue or a fundamental quirk of TypeScript. I've spent a few hours trying to solve it myself but cannot figure out where the real error is coming from but I think I've narrowed it down.

The goal is to define a function interface which takes a route path and a schema object where every slug (parameterised route variable) must be in the schema object and both must have no extra keys with respect to each other. I can achieve this but subsequently calling `Static` on the schema object results in said type erasure.

Using a proper `Type.Object` as the schema object prevents type erasure but loses the slug and schema object key checking.

Here's my best attempt thus far:

```typescript
type ToLower<T extends readonly string[]> = { [K in keyof T]: Lowercase<T[K]> }

const methodsUpper = ['GET', 'POST', 'PUT', 'DELETE'] as const
const methodsLower = methodsUpper.map((v) => v.toLowerCase()) as unknown as ToLower<
   typeof methodsUpper
>

type HttpMethods = typeof methodsLower[number]

// Creates a string union route path segments. Effectively splitting at each
//   `/` where each split is a member of the union.
type TakeSegments<P extends string> =
	P extends `/${infer Path}`
		? Path extends `${infer Segment}/${infer Rest}`
			? Segment | TakeSegments<`/${Rest}`>
			: Path
		: never

type TakeSlug<P extends string> =
	P extends `{${infer Slug}}`
		? Slug
		: never

type TypedRouter = {
	[M in HttpMethods]: <
		Path extends string,
		ValidationSchema extends TProperties,
	>(
		path: Path,
		validation: TPickProperties<ValidationSchema, TakeSlug<TakeSegments<Path>>>,
		handler: (ctx: Static<TObject<ValidationSchema>>) => Response
	) => Response
}

const foo: TypedRouter = {}

foo.get(
	'/foo/{bar}/lorem/{ipsum}/{dolor}',
	// Using Type.Object fixes inference but breaks slug-key checking.
	{
		bar: Type.Integer(),
		ipsum: Type.String(),
		dolor: Type.Boolean(), // Comment me to receive a type error about missing key `dolor`
		// extra: Type.String(), // Uncomment me to receive a type error about additional key `extra`
	},
	(ctx) => {
		ctx.bar // Type is `unknown`, expect `number`.
		ctx.ipsum // Type is `unknown`, expect `string`.
		ctx.dolor // Type is `unknown`, expect `boolean`.

		return new Response('Foo bar')
	}
)
```

**Comment by sinclairzx81** [comment]
@tsujp Hi,

Um, I don't think this is a TypeBox bug, but this usage would be running up against the extents of the TS compiler and inference capabilities. I had a quick hack around and largely ran into the same issues. I've tried to make the supporting types a bit more obvious here (you can test them individually), but the main issue seems to be TypeScript losing track of the specific `TSchema` when evaluating the type with this usage pattern.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjgKIBuBANgK5HZwCqAdsBK8hMnWDU2S4SACwwgCOZAAUoETLGAYAznAC+cAGZyQcAOQABZcFYkaBYFAD0MdBgBGEAB56AsACgPVq3AC0-gMCg4JDQsPCIrx8ACRgYMABZDBgRCAATZSi-CJzcvPyPDCdIWDhbTBQIABkIAHcMKAAeZDgimAxWDLgoDAI0zhpUOGUYKBMAcwBtAF0APjgAXkQ4SYBpOBM4AGsMVAhNFGmALjga+qgSAmUMZrW59ULi6HhyjDhY+KSU9NUl1-24CBkqkMmcGpNWHQQPYGtMPCROCNAcCfswwApFis9ABxcjIPQ4PTSADyuHxhOkzHJ+gAIuQqnjyHppnArnAEawRvDEfAgd9QXUGpi+SDlGiFAA6CRgAAUMsoAEpFvNKBKYNVBVAAMJXDAyhVKtl0VhbVh1Vis1TcMFNDxwe3-A4i1HohoeWZZfJe70+rLSAhQa6en0h0OhR4lF52OD+wMYLUQcCcDowZSNaStJztTqqEZjVjjeZLDNtDpdAAGVgAJAgTJohf6Umpyx4AJAAfhjRBEmezFZrdaFuAw4yBrBgamrtdY9agcAASioJy33K37Z3h6OU3AAD5duMJpOsFNpys1xcjZse1etk6NkRtk7Hyhu9xFSNlaOx664ejjNMllmZa5qMExFjGvbAXA5YIAOM5Dn+ajNnAG5-nAT4YC+UARs8n4VN+GCyPIDS2GwHCsM0kE5sMoEFuBBG-nQ-7pgG1yHpAx7jmmyCzNe764a8+7XERCi2AAcgQQLcVRXR5mBmJkZw3C8PwNwESJJGoIpFE8XxTylIJBHEvYABWGAkDAGmKColGltRckFjM4F2igMmqJMg5zlUbk0fm4w4BKgWeQuPkOVM0xwu49rrsskwAPobBaVQsicQiiOIBDqHAABkQkYMZZkWVZxA2fO8wufaJwIGowZhnVYZZAAarQwBpEQ5EFeZMC1fVvVejhBlfqxGDNTQrXtZwnUWbZQH2bR-l4Ji6lyKJqASVJzS8ZiuChfNMxwC5nZULQDDtCxcZTZZK0kUoaa4LxLlVTVb76VGFT4O1JCjeNxCTaZXWbZiLR2V0MjXdZqidggLlrIl2y7ACyDHHghDECQtyrHMHgaBhWE9X1BORO43goHYaTzhAdDtNhxM+IT9NE-xg0VGgmDk5T1OYtDUXRZMCRwx8iQohkyONBV0WAX2IF+Vg4v2i0xbDd9bW-awl3pte9qzDK4tgN2d6yzz9rUGNKvkalOAk5hJ0TRaiNwPKwCZdIpBbHA0DuykDRKrUwA0DQcAiAQL4oDtNAQNcZRQAQJBuwC4wdA0pB4SoEri0HnQCFAJwyhZTgnB9aPK7b6s8UqCzzBeHFBjz5eVyo1cYNj+MM63-hZOQTiSapLdtwzHhpOZ5g9OyPJaBAECpWTFNU6+mgTxKCcwDrPN6FY88QFYCD2AGk7hz0IBb8AYDKFCk4IP0+9qASLkk8wxgFqTmASpdWjAE4KiJbOHQkG89hU3AewPQCBbFzH+XwOwhjpVjhMNOPNubRUAQGKez8ACS44RwNH1IbRBx9T4gBQRgCU+A-LYPFpfaAhCJQACEJ4CAIKwbBcASaHjHLyN46pujmQwMAEOmVBINDkHOAgjgAEgGAMoB+4x4ZDHLBQqAK5EFWyzNHKhJCJhMLvqYRMbDkRlAgFw3+vC3j8OjIIj2IiOasjSGkYAqtaAyOgm0aOij1A4IdnnOuiBxZ5wlDvOcJNWZvAkdBY0ppzTlhwO+Lq0FITQgaOWOBiDfF4KhMwnwQSNiqHLGEs0tRWCRMzJgCy0EwqJJ8TAJwEp5HpKfsE7JuSIlROKDE8sjgID0IKUk6KPQYB0CgBaY8tQFwN0RHqPQAAxCeSCoB6AVC5Z68z3BAA)

```typescript
import { Type, Static, Evaluate, UnionToTuple, TSchema, TProperties } from '@sinclair/typebox'

// ------------------------------------------------------------------
// HttpMethods
// ------------------------------------------------------------------
export type ToLower<T extends readonly string[]> = { [K in keyof T]: Lowercase<T[K]> }
export type HttpMethods = typeof methodsLower[number]
const methodsUpper = ['GET', 'POST', 'PUT', 'DELETE'] as const
const methodsLower = methodsUpper.map((v) => v.toLowerCase()) as unknown as ToLower<
   typeof methodsUpper
>
// ------------------------------------------------------------------
// Parse
// ------------------------------------------------------------------
export type ParseComponents<P extends string> = P extends `/${infer Path}`
	? Path extends `${infer Segment}/${infer Rest}`
	  ? Segment | ParseComponents<`/${Rest}`>
		: Path
	: never
export type ParseSlugs<P extends string> = P extends `{${infer Slug}}` ? Slug : never
export type ParsePropertyUnion<T extends string> = ParseSlugs<ParseComponents<T>>
export type ParsePropertyNames<T extends string> = UnionToTuple<ParsePropertyUnion<T>>
export type ParseObjectProperties<T extends string[]> = 
  T extends [infer L extends string, ...infer R extends string[]]
    ? { [_ in L] : TSchema } & ParseObjectProperties<R> 
    : {}
// ------------------------------------------------------------------
// ValidationObject
// ------------------------------------------------------------------
export type ParseValidationObject<T extends string, S = ParsePropertyNames<T>> = S extends string[] 
  ? Evaluate<ParseObjectProperties<S>>
  : {}
export type StaticValidationObject<T> = T extends TProperties ? {
  [K in keyof T]: Static<T[K]>
} : never
// ------------------------------------------------------------------
// TypedRouter
// ------------------------------------------------------------------
export type TypedRouter = {
    [M in HttpMethods]: <
      P extends string,
      T = ParseValidationObject<P>
  >(
    path: P,
    validation: T, // evaluation of T (via Pick or other) will have TS lose track of generic types.
    handler: (ctx: StaticValidationObject<T>) => Response
  ) => Response
}
// ------------------------------------------------------------------
// Example
// ------------------------------------------------------------------
declare const foo: TypedRouter
foo.get(
  '/foo/{bar}/lorem/{ipsum}/{dolor}',
  // Using Type.Object fixes inference but breaks slug-key checking.
  {
    bar: Type.Integer(),
    ipsum: Type.String(),
    dolor: Type.Boolean(), // Comment me to receive a type error about missing key `dolor`
    // extra: Type.String(), // Uncomment me to receive a type error about additional key `extra`
  },
  (ctx) => {
    ctx.bar // Type is `unknown`, expect `number`.
    ctx.ipsum // Type is `unknown`, expect `string`.
    ctx.dolor // Type is `unknown`, expect `boolean`.
    return new Response('Foo bar')
  }
)
```
So, the above does do inference, however the `extra` property is allowed (which is probably not desirable). Unfortunately, I can't seem to have TS retain the generic TSchema AND ensure additional properties are disallowed. So, not too sure here...however, you can repro TS losing track of generics by forcing TS to evaluate the type (this also prevents disallowed properties, but at a cost of losing inference)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjgKIBuBANgK5HZwCqAdsBK8hMnWDU2S4SACwwgCOZAAUoETLGAYAznAC+cAGZyQcAOQABZcFYkaBYFAD0MdBgBGEAB56AsACgPVq3AC0-gMCg4JDQsPCIrx8ACRgYMABZDBgRCAATZSi-CJzcvPyPDCdIWDhbTBQIABkIAHcMKAAeZDgimAxWDLgoDAI0zhpUOGUYKBMAcwBtAF0APjgAXkQ4SYBpOBM4AGsMVAhNFGmALjga+qgSAmUMZrW59ULi6HhyjDhY+KSU9NUl1-24CBkqkMmcGpNWHQQPYGtMPCROCNAcCfswwApFis9ABxcjIPQ4PTSADyuHxhOkzHJ+gAIuQqnjyHppnArnAEawRvDEfAgd9QXUGpi+SDlGiFAA6CRgAAUMsoAEpFvNKBKYNVBVAAMJXDAyhVKtl0VhbVh1Vis1TcMFNDxwe3-A4i1HohoeWZZfJe70+rLSAhQa6en0h0OhR4lF52OD+wMYLUQcCcDowZSNaStJztTqqEZjVjjeZLDNtDpdAAGVgAJAgTJohf6Umpyx4AJAAfhjRBEmezFZrdaFuAw4yBrBgamrtdY9agcAASioJy33K37Z3h6OU3AAD5duMJpOsFNpys1xcjZse1etk6NkRtk7Hyhu9xFSNlaOx664ejjNMllmZa5qMExFjGvbAXA5YIAOM5Dn+ajNnAG5-nAT4YC+UARs8n4VN+GCyPIDS2GwHCsM0kE5sMoEFuBBG-nQ-7pgG1yHpAx7jmmyCzNe764a8+7XERCi2AAcgQQLcVRXR5mBmJkZw3C8PwNwESJJGoIpFE8XxTylIJBHEvYABWGAkDAGmKColGltRckFjM4F2igMmqJMg5zlUbk0fm4w4BKgWeQuPkOVM0xwu49rrsskwAPobBaVQsicQiiOIBDqHAABkQkYMZZkWVZxA2fO8wufaJwIGowZhnVYZZAAarQwBpEQ5EFeZMC1fVvVejhBlfqxGDNTQrXtZwnUWbZQH2bR-l4Ji6lyKJqASVJzS8ZiuChfNMxwC5nZULQDDtCxcZTZZK0kUoaa4LxLlVTVb76VGFT4O1JCjeNxCTaZXWbZiLR2V0MjXdZqidggLlrIl2y7ACyDHHghDECQtyrHMHgaBhWE9X1BORO43goHYaTzhAdDtNhxM+IT9NE4JABCPQEFsACS8FNDxQM+cFxIoXAAu46+JPReLEuS1L0twAAelo0AkG8mEnRNFpiD0Mta9rOu69FHgDW9bxoJg5OU9TmLQ1F0WTAkcMfIkKIZMjjQVdFgF9iBflYG79otMWw3fW1v2sJd6bXvaswym7YDdnePvW-a1BjcH5EnCzvQc1zm04CT9hyDs6sNBgbsiAQnQCFAJwyhZTgnB9aNB2rYc8UqCzzBeHFBtbbcdyoXcl+4z0kwzo8hFk5BOJJqn42Po8eGk5nmJrHJIpoEAQKlZMU1Tr7rxAErjMk0fW3oVj71YCD2AGk40NA4iX8AYDKFCk4IP0d9QGoBIuSTzDGAWUmmAJSXS0MAJwKhEqzg6ErOA9gqZwNZlsXMf5fA7CGOlEgWwJgShclbcW18q5AIwBKTm7Qj5QH1AncWT8X4gC3sA-AfkqFuw-tABhJCmYbwEOXKhcASaHjHLyN46pujmQwMAF8rI8LKygHIOcBBHAIJAMAZQADxjwyGOWNhUAVzixJm0KABAOESiYRMPhf9TCJiEciMoEAxFK0kW8TKgkGjyNZEo+AfQ0jABDrQTR0FDEED0eoahcAa4wCcL3RAbta4SkIfwnwJs3iqOgsaU05pyw4HfF1aCkJoQNHLLgxO7JIkSloVCRJxCNiqHLOks0tRWBZMzJgCy0EwpFNiWUnRVTkk1LSSaBpTTsnFFyeWRwEAeFNOKeLHoMA6BQAtMeWoC5+6Ij1HoAAYhvOBAY9AKhcs9A57ggA)

```typescript
type BreakInfer<T> = T extends infer O ? O : never
//                                   ^ force evaluation here                                                          

export type TypedRouter = {
    [M in HttpMethods]: <
      P extends string,
      T = ParseValidationObject<P>
  >(
    path: P,
    validation: BreakInfer<T>, // broken here
    handler: (ctx: StaticValidationObject<T>) => Response
  ) => Response
}
```
I expect there would be a way to implement this (it might just take some refactoring and deep diving into various ways to express this form of mapping), but yeah, I don't think this is specifically related to TypeBox.

Hope this helps
S

**Comment by sinclairzx81** [comment]
@tsujp Hi!

Hey, might close off this issue as this isn't really related to TypeBox. But I noticed that `-n-` (https://github.com/somebody1234) of the TS discord server produced a pretty great working solution, so will link this below for reference.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsgApQSazAYDO5A8gEYBWGJM5uJAFhhAE4AXzgAzaiDgByAAINgAOxIAbAsCgB6GOgysIAD1kBYAFAXt2uACEIwNRihgNMDHAYwArhIkWSCGUvOH4YGDAAWQwYfggAEwY4AF44AG1ZAHMY2RxZSC9cuTBvGCLZeIwnd1kAXTgCJMDgmAsMI0hYOD1MOAAJcKiYuMSU7v0ICVDB6NiEhjTlbxBWZ1qLCx6PZAIAawxcDEyQDGUYBgAeCjh292VRrygVTIA+FIsASGvb09GAA20ABIECoJM48EcTmdRECQcowVA4AAlRgwUR-T4fAD8EOOp3gAB8UHsDpD8ZcAcCUV50S9MQAuODfIx3f6w0Hgw546EY8wffk4rlQ1p8-mM5QYABuzg25i2xP2uDU3kyVxuLN+SUezzeyU+zNZST+CGBHMRSpVonRmMFysyDLgEulUCsNgAovc4IZHM5XEQMLL5WhMPEkRBSuDUghPmlInAVP0ZsN5rVGRdMRQiPx1Ya4JSENrlJl0VhMQA1AhqYDxIjAII5zUoKg0ZzERilvkvAAUmLAWcZmdiHf5ksr1drQXFUvBP3uSQrVZrxHrOIopF2FwX4+XyjgADJkVxoPELjtFXbTySheSrlmXi9eAIhAQHwqDhez6Tuedb7F729GS3Jc62UYcPn4Ah7icKBGS7bgjEZfBaxIC4ADkglQ7w1A0VgnFPNhOG4Tcx2AoJ-wAShSN5qUgYJsE+SjkmoxhaIYANzFEWVKnUAgoA8ZoQgkCAIEZYMMFDcN3BdSxzCEiAADpshgHs+VkbQ5O0BBWF4mE1GgIRNOAMAGGWGEEHiCA9KgURck+aNRW0mCUH0eSAEkziOZwu3IsCjJMkBRJc5gwB3SsuzE+T8CeItvJ8zELKswLMHk+xLIwSDvJwaw4AAYQgEBhWebp+GALU4iw+I4ECcANATAhDFKOAQFKpQizgfZUDzBLoD+eTMWy24oAIJKMEimBosyTK4GygBVVR8sKtrYlKzxwzUSrqr9OqGvgAh4niYBQrUdqME6v5BoIXrPlEDs4GmmxkEEKqYCMOA+yGk4pM8cr1sdXjqAAd2KjwtiSRp1UwbhxK9KoIABvq+Tgl7GLeeyPmygA9LFMXg+THPuuA3Q6Lh4D+JYVmcXl+WyuAsdlflcb85YCaJyHScLTI4CJbx7gwCQVHEqn0ZsO66ZkhmXvk7rEWy1mSbzQw0sgoWadp7HxY+XGLpZ4nuGKlaYAgGGGl3ZxqERLtKwBghUAYSjp13YApnOlkhr+eMkh56rhWhhNYg8Bgn2EGGSAIbw2PjMowbgUdF08O1+pFtX6Y+PifCgXcJSBmigjYrtZAAMWEr1eNkcjro7cvzCAA)

```typescript
import { Type, Static, TProperties, TObject, TSchema } from '@sinclair/typebox'

// Boilerplate stuff
const httpMethods = ['get', 'post', 'put', 'delete'] as const
export type HttpMethods = typeof httpMethods[number]

type TakeSegments<P extends string> =
	P extends `/${infer Segment}/${infer Rest}`
		? Segment | TakeSegments<`/${Rest}`>
		: P extends `/${infer Segment}`
			? Segment
			: never

type TakeSlug<P extends string> =
	P extends `{${infer Slug}}`
		? Slug
		: never
// End boilerplate

type TypedRouter = {
	[M in HttpMethods]: <
		Path extends `/${string}`,
		Validation extends TProperties,
	>(
		path: Path,
		validation: never extends Validation ? Pick<Validation & Record<TakeSlug<TakeSegments<Path>>, TSchema>, TakeSlug<TakeSegments<Path>>> : Validation,
		handler: (ctx: Static<NonNullable<TObject<Validation>>>) => Response,
	) => Response
}

declare const foo: TypedRouter

foo.get(
	'/foo/{bar}/lorem/{ipsum}/{dolor}',
	{
		bar: Type.Integer(),
		ipsum: Type.Optional(Type.String()),
		dolor: Type.Boolean(), // Commenting this should complain about missing key `dolor`.
		// extra: Type.String(), // Uncommenting this sould complain about additional key `extra`.
	},
  // The ctx parameter should narrow the types as expected below.
	(ctx) => {
	// ^?
		ctx.bar // Expect `number`
		//  ^?

		ctx.ipsum // Expect `string | undefined`
		//   ^?

		ctx.dolor // Expect `boolean`
		//   ^?

		ctx.extra // Expect this to be an error (always) even if `extra` is uncommented in the schema because it's a valid slug
		//   ^?

		return new Response('Foo bar')
	},
)
```
Quite an interesting type level puzzle this one :) Will close off this issue for now
All the best!
S

**Comment by tsujp** [comment]
> @tsujp Hi!
> 
> Hey, might close off this issue as this isn't really related to TypeBox. But I noticed that `-n-` (https://github.com/somebody1234) of the TS discord server produced a pretty great working solution, so will link this below for reference.

Hey hey, as you know (we just chatted in Discord, but also stating here for clarity) that was me asking there! `TypeHole` in Discord had a good very-close solution too.

I was going to say in your original reply why chose:

```typescript
export type StaticValidationObject<T> = T extends TProperties ? {
  [K in keyof T]: Static<T[K]>
} : never
```

versus

```typescript
export type StaticValidationObject<T> = T extends TProperties
  ? Static<TObject<T>
  : never
```

The former will incorrectly infer `ipsum: Type.Optional(Type.String())` whereas the latter will correctly infer it.

An educated guess is that `Static<TObject<T>>` is correctly evaluating optional or readonly properties as `TObject`'s `static` field is of type `PropertiesReduce` which itself is constructed of type `PropertiesReducer` which is doing said evaluation whereas `Static<T[K]>` for a simple type like `Type.String()` whose `static` field does not comprise of type `PropertiesReducer` is simply returning `string`.
