### ISSUE TITLE
"removeAdditional" with TypeCompiler 

### ISSUE THREAD

**Issue by mahendraHegde** [sinclairzx81/typebox#628]
currently TypeCompiler throws the error if the schema has `additionalProperties: false`, but it would be good to optionally ignore and remove additional properties like [AJV does](https://ajv.js.org/guide/modifying-data.html#removing-additional-properties), i dint find anywhere how to achieve it, is it possible?

**Comment by sinclairzx81** [comment]
@mahendraHegde Hi,

Unfortunately, TypeBox doesn't support the `removeAdditional` in the TypeCompiler. However you can replicate similar functionality with the following.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYGELmAGwyjgF84AzKXOAcgAEBnYAOwGN8BDYKAehnQwAjCAA8erXGAJEaAWABQoSLEQoBAGhQBlVgAsMIDqQpUQtRi3Zde-TMJFz5C8gFc2MYBGZwceQgHVgGF0IFxgAQQATSKDPZg58AB5kOAwRGAxmSIZtPQMOAD4ACgY8wwAuFABKRAU4OAlmBnh2Lww4AF5VADpe0v1DUjq4SIxCDIb8NoBtGg5o2K8EgAUqTFhgDAYaAF1hqAwYFyhvNExfKUIobovpErKOKoUSBQVG5pROtUxugHlBABWGFYMCKCGGIkqZww3QAci4QIIiEUquphqgoQI4QikVAUWj5PUAF6Yn7wxHIp7yEiacGEuDzGIeJb4VYQdYeLaVcgJBgYZ5Ut5eD6BYJfaG3K43SR3ZBU97wUUhMJfSUYJWhCILZnxfBFOUKIA)

```typescript
import { TypeCompiler } from '@sinclair/typebox/compiler'
import { Type, TSchema } from '@sinclair/typebox'

function CompileWithoutAdditional<T extends TSchema>(schema: T) {
  const clone = { ...schema }
  delete clone['additionalProperties']
  return TypeCompiler.Compile(schema)
}

const T = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
}, {
  additionalProperties: false
})

const With = TypeCompiler.Compile(T)
const Without = CompileWithoutAdditional(T)
```
Hope this helps
S

**Comment by sinclairzx81** [comment]
@mahendraHegde Hi,

Will close off this issue as `removeAdditional` isn't liable to be part of TBs validation. If you have any questions though, feel free to reply on this thread.

All the best
S

**Comment by mahendraHegde** [comment]
Hi @sinclairzx81 , thanks for the answer, but removeAdditional flag wont remove the `additionalProperties:false` from  schema, but removes additonal fields from data
ex:
```
const T = Type.Object({
  x: Type.Number(),
}, {
  additionalProperties: false
})
const compiled = TypeCompiler.Compile(T,{removeAdditional:true})
let data = {x:1,y:2}
compiled.Check(data) 
console.log(data) //{x:1}
```
this is what ajv does btw, this will help in cases working with schemaless databases where you would want to insert incoming data with less or no processing.

**Comment by sinclairzx81** [comment]
@mahendraHegde Hi, Sorry for the delayed reply on this.

The Check functions provided by the TypeCompiler and Value modules will only check a value is correct as defined by the schematic (and return a boolean result). The Check function will not modify the value in any way, but you can use some of TypeBox's other functions to remove additional properties.

### Remove Additional Properties (after Check)

You can use the Cast function to remove additional properties. This function will return a value derived from the original value and ensure it matches the intended schematic. By passing a schema with additional properties false, it will ensure those properties are removed.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsriQBYYgFwC+cAZlBCHAOQACAzsADsSAGwLAoAehjoMAIwgAPTgFgAUKEixEKGQGF2YYMIxRGLNhx78ho8VJnyFEkgaMmV68NHhIAagWEAVwwzVnYuPkERMUlpTEcJADcA4I81ZkChYggBOF0oDCIMfChSGAAFAiheEwAeZDgMBRgMAQATXhRKGjoAPgAKXmpaAgAuFABKRDU4OAkJOBdwNzghnvowAl4atrhZVDhAmqgAOhnFnN54OIxhkgBrOABeHUx9ZeNT98NjQeG6CbnAowQJQXL9ZJBDDjTL3AQQADuAgm43wRFI9V6zyxCHOs3mixoDzgMBocEhwTgBHaJKobARcGAzEZAkhwDaeMZzH6AEIbnd7iddET7hCUhgJlNSfS4AIMAyAKJQNhQfr8kUnJUq3hiqETE4AMXEV36Ex5JxAGG2BAA5hLOQSCIEbZaBPAjiZVv96AjgKSqW02n7gDkAuU2JhYMArSwAjVOS4BFdVjBSiQYN0Rs9tCdc2sRjgCIHg6HhOGIJHiFbxsw4yEGA6Fh7FltrhA4Ow-QGg9kBAE4GAIyYq7xOcDQbl-FCha3Bqmypm6DgKfbVLMG6oN4nkw0XmhMCcAPKyABWtxg-Vxa7gCnG+4wJwAcoEQLITKasOdUHeZE+X2-VQmT9rwALx-A9n1fd9AU3GC1G3eBdGzfJChaEoykqap32QODVAQuAAEFkMvG9xgARhwb84AAJhwMC4AAZkYKZZlYuYFggR4AFptFvOAKLgKjaLgeimI3eDLngAAhYikD4gShLo8YGJwBFxgAFmY9iO243jyMo8ZhNExg1DUIA)

```typescript
import { Type, Static, TSchema } from '@sinclair/typebox'
import { TypeCompiler } from '@sinclair/typebox/compiler'
import { Value } from '@sinclair/typebox/value'

function CreateStrictParser<T extends TSchema>(schema: T) {
  // compile schema passed by user.
  const typecheck = TypeCompiler.Compile(schema)
  return (value: unknown): Static<T> => {
    // check the value and throw if invalid
    if(!typecheck.Check(value)) throw new Error(typecheck.Errors(value).First()!.message)
    // augment user schema with additionalProperties false
    const strictSchema = { ...schema, additionalProperties: false }
    // use cast to omit additional properties
    return Value.Cast(strictSchema, value)
  }
}
const T = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
})

const C = CreateStrictParser(T)

const A = C({ x: 1, y: 2, z: 3 })       // ok - { x: 1, y: 2, z: 3 }

const B = C({ x: 1, y: 2, z: 3, w: 4 }) // ok - { x: 1, y: 2, z: 3 }
```
This is a different setup to Ajv where operations performed on values is programmable (so not configurable). TypeBox provides quite a few additional functions to perform variable mapping and value translations. You can read about them here https://github.com/sinclairzx81/typebox#values

Hope this helps
S

**Comment by mahendraHegde** [comment]
@sinclairzx81 this is perfect, works for me.. I just have one question why not `cast` first and then `check`? if want to keep additionalProperties at schema definition level? is there an issue? the reason being, i dont want to remove additional props from all schemas may be, i cant determine on the fly(inside CreateStrictParser) because some schema as complex unions.

**Comment by sinclairzx81** [comment]
@mahendraHegde Hi

> I just have one question why not cast first and then check?

The Cast function will always succeed even if the value is invalid. Any invalid properties, array elements, etc will be reassigned to default values during the Cast. Because casting will always succeed, it's better to Check first to ensure the value being Cast is correct (and can be safely casted)

**Comment by mahendraHegde** [comment]
> @mahendraHegde Hi
> 
> > I just have one question why not cast first and then check?
> 
> The Cast function will always succeed even if the value is invalid. Any invalid properties, array elements, etc will be reassigned to default values during the Cast. Because casting will always succeed, it's better to Check first to ensure the value being Cast is correct (and can be safely casted)

got it. thanks for the quick response.
