### ISSUE TITLE
Typebox doesn't correctly infer `...Type.Rest(Type.Array(...))`

### ISSUE THREAD

**Issue by jackyzha0** [sinclairzx81/typebox#632]
I have a TS Type that is the following:

```ts
export type NodePath = ['a' | 'b', ...Array<number>];
```

I've tried making the associated Typebox type:

```ts
export const NodePathSchema = Type.Tuple([
	Type.Union([
		Type.Literal('a'),
		Type.Literal('b')
	]),
	...Type.Rest(Type.Array(Type.Number()))
])
type NodePath = Static<typeof NodePathSchema>
//   ^ got:      ["a" | "b"]
//   ^ expected: ["a" | "b", ...number[]]
```

Is there any way to spread the Type.Array into the tuple?

**Comment by sinclairzx81** [comment]
@jackyzha0 Hi

At this stage, the Type.Rest() utility only operates on types that accept a generic / variadic array argument. These types include Type.Tuple, Type.Intersect and Type.Union with the utility extracting the interior variadic argument where the size is known.

[TypeScript Link Here](https://www.typescriptlang.org/play?ssl=6&ssc=83&pln=3&pc=1#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwBEAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAbgCwAKFG0I1CvACCcALwpOAOgBKGaQAo0mZQElqMDFAoZaMTQG0dGZQDkAriC7HNASgA0S3QGUYUGgBzdwBdNzc4VlY4CSlZAC44a0dnYy9kPwDqQJDxSWk4ACEFb1t1LRtlAFVqYEkrSpSXKHd0lUyg0PC4Hp6omPz4QsTkp2b0juzckViCgGESyvKLSuQHMHoMBpUm109S5UngtzCI3sjo2fg5keRdqAn-IOmruAARRZVl7RUZKChGKgfrp7u5uucIZDIf1Xm8RiEgA)

```typescript
const A = Type.Rest(Type.Intersect([Type.Number(), Type.String()])) // const A: [TNumber, TString]
const B = Type.Rest(Type.Union([Type.Number(), Type.String()]))     // const B: [TNumber, TString]
const C = Type.Rest(Type.Tuple([Type.Number(), Type.String()]))     // const C: [TNumber, TString]
const D = Type.Rest(Type.Array(Type.Number()))                      // const D: []
```
Note: Type.Rest returns a fixed length TypeScript tuple type containing TB types. It can be used in certain mapping scenarios, typically to concatenate fixed length tuple elements.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwBEAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAbgCwAKFG0I1CvACCcALwpOAOmQBXMPQwAKANppMygHJqQXDFG0BKALpXxk6XABCCpYfWadu5b4MZlACUMaW0ZKwAaOF9VFWDQ8LsHKXgAYTd-VQ0tPRjM+JhtZ0jovziQwuKkkQkUuAARDJVPHJ8ywwLtVJK88tDuuyA)

```typescript
const A = Type.Tuple([Type.Number()])
const B = Type.Tuple([...Type.Rest(A), ...Type.Rest(A)])
const C = Type.Tuple([...Type.Rest(B), ...Type.Rest(B)])
const D = Type.Tuple([...Type.Rest(C), ...Type.Rest(C)])
```
> Is there any way to spread the Type.Array into the tuple?

Unfortunately no, but would be open to a proposal on how best to express this type. The issue currently is that `...number[]` is unbounded, which makes it difficult to reconcile with TypeBox's inference (which primarily operates on fixed / known size variadics), but also reconciling this type as Json Schema (where there would be a need to define a schematic to express unbounded arrays of varying types)

One thing you can do however is use Type.Unsafe to express the type

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwBEAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAbgCwAKFG0I1CvGRwAvCk4A6AKpTGeDAB4A2iUYk4AH1JcSAGjhLr1AK4guGKDoC6LgHwAKBKLh+OmABccADkjFBQjKgh5r5+rKxwMBAAJhDBGLxgUBgUFHAAVhSScBS0ABYYIIxwlTmi2ACUQA)

```typescript
const T = Type.Unsafe<["a" | "b", ...number[]]>({
   type: 'array',
   // todo: express json schema here
})
```
But you would need to define the schematic (as TypeBox doesn't currently implement schematics to express unbounded tuple arrays). If you have a proposal for what such a schematic should look like, would be happy to review integration at some point into the future. 

Hope this helps
S

**Comment by sinclairzx81** [comment]
@jackyzha0 Hiya,

Hey, might close off this issue as unbounded types (`...number[]`) are generally not supported in TypeBox (today at least). But would be interested in finding ways to support this into the future. I wouldn't expect this functionality to land soon though, but may investigate again once TB moves to the Json Schema 2012-12 specification (as there may be few more options available)

Will close off for now.

All the best
S

**Comment by jackyzha0** [comment]
Sounds good, thank you for the response! Will forward to my team. Looking forward to the support but we'll likely use `Type.Unsafe` for now
