### ISSUE TITLE
Typebox Discriminated Unions

### ISSUE THREAD

**Issue by lifeiscontent** [sinclairzx81/typebox#633]
Hi there, I've spent some time trying to figure out a way to create discriminated unions and it seems this works:

here's an explanation of how it works:

1. the property that is going to be used as the discriminator need to be defined in the object
2. allOf is used with the `if/else` JSON Schema directives where if `operator` matches
3. we check the rest of the fields if they match

having a Discriminated Union in TypeBox improves the DX of error representation because you don't have weird errors from the other types in (like you currently get with a `Type.Union`) e.g. `$root` will say there's any error about `allOf`

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "operator": {
      "type": "string"
    }
  },
  "required": ["operator"],
  "allOf": [
    {
      "if": {
        "properties": {
          "operator": {
            "const": "add"
          }
        }
      },
      "then": {
        "properties": {
          "a": {
            "type": "number"
          },
          "b": {
            "type": "number"
          }
        },
        "required": ["a", "b"]
      }
    },
    {
      "if": {
        "properties": {
          "operator": {
            "const": "subtract"
          }
        }
      },
      "then": {
        "properties": {
          "a": {
            "type": "number"
          },
          "b": {
            "type": "number"
          }
        },
        "required": ["a", "b"]
      }
    },
    {
      "if": {
        "properties": {
          "operator": {
            "const": "divide"
          }
        }
      },
      "then": {
        "properties": {
          "a": {
            "type": "number"
          },
          "b": {
            "type": "number"
          }
        },
        "required": ["a", "b"]
      }
    },
    {
      "if": {
        "properties": {
          "operator": {
            "const": "multiply"
          }
        }
      },
      "then": {
        "properties": {
          "a": {
            "type": "number"
          },
          "b": {
            "type": "number"
          }
        },
        "required": ["a", "b"]
      }
    },
    {
      "if": {
        "properties": {
          "operator": {
            "const": "square"
          }
        }
      },
      "then": {
        "properties": {
          "a": {
            "type": "number"
          }
        },
        "required": ["a"]
      }
    }
  ]
}
```

here's an example implementation I put together, but not sure if I'm doing everything correctly.

```ts
export function DiscriminatedUnion<
  T extends TObject[],
  TDiscriminator extends keyof Static<T[number]>
>(schemas: [...T], discriminator: TDiscriminator): T[number] {
  return Type.Object(
    {
      [discriminator]: Type.Union(
        schemas.map(
          schema => schema.properties[discriminator as keyof TProperties]
        )
      )
    },
    {
      allOf: schemas.map(schema => ({
        if: Type.Pick(schema, [discriminator]),
        then: Type.Omit(schema, [discriminator])
      }))
    }
  ) as T[number]
}
```

**Comment by sinclairzx81** [comment]
@lifeiscontent Hi,

Unfortunately, at this stage, TypeBox won't be implementing a DiscriminatedUnion type as standard. But as above, it is possible to construct this union representation (and inference) using the current TypeBox API outside the library. Below is a quick update to the type (just fixing up the return type and deriving the broader base object discriminator type)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUHkBGAVhgMYw7ICqAdsBNTgMowCGMwJFAClBJrMAwBnOAF84AM14g4AcgACQ4NRIAbFsCgB6GOgz4IAD1kBYAFChIsOAEFCAN0nS5LB6bPmtWuAFo--gMCg4JDQsPCwz29kABFgIRIoUGU2DAATGjpqKN8IvPyCwsDzDEMreGUYDCgJFhIMFDiEpJAUqozaegAeZDhSquo0kWQCYjIAbQBdOABeOCmAPj7DAaG8IlJ4BHM4OCFWdhIALjhmNg4ezO7kBYWduBZVVVwJE6RgV-Wx8jgYAAsMNQTiMNmQxFNzKIckUYbC4X4ck1EslqKkOllofCsdjQiUytB4BIAK4qdj0OBIlptdJXag9ZarYajTZTCiUlFsaAMwFrADWGFQEAkpwOF2Q42oRJA+Gqk1uAAoEgCQCwhCdxgA6LXISY4NLxZGtVEwaDA9lGzlQACUZoNVONNM6dJuiHuJHo+weTxesz2JGVqo1KrAiv9GBVsyW8u2Zl2uw+wL0Gq4HF5oYDOHG+uaHJNUEmVqw912-0BicwGtwrRg6fDLEz2cNbWgutdsbjuy8cD4ZNRqhOYCgGHsgPgLDS+t7jzgg741XYwm71F+AOXukwcHlpUwYPoqlQcEb9stVuLcfHk6yjx4c4EwnLGA1AElBqVayqG3bcy2rXAz6JT3bADAM7bwhAwVRNkkTRPSPb8oF+PQHhEVEoF4AB3dJN1UYAqigR5CxXQFD2qYAR1+CA4HwXhx0Qis3Q9eBUIwtANzmJU6yEcYAAZJg1Wd+AXLi4ItPNkLgflBWFZAb0EwQhEmBjqE9aiIHHViGjmDSNQAURWHkhHlZiIHQjSKCTZgkmoABzeVCO0yzlFswizw7Nz3JQJM9MZIyWDQkyzM8isADkpRlKA7PMkKwuqSK-3bDzErjbTvIM3z-NMvQosfAAhCAIEglhqDi7S8oKjAisi1ykvc7TguHWKrSakC4C7CBQXgNJhCbY0uRAIkVIaVTxxwYzMLSOAcLwx4RHDGUJyw5QvWeYU-Pw1AlM9AT53k30kCzL9RJbE5hrSDSxHuIcYCJKBl205kyGjOAtX43g5MXMQcCQR4VrEX9VQeagNrMKEzC7HEIchnwckoIQWGsjBMSh5HYXMd1lPgXo5nNal0XoeVxnue6OujM91wwB8NQAGVw6pHnlWQADVNmgAAmWRCzPQxKdC6VGqLBK4FQHmYoilqAIF3Zie+UnBfJymaem1QGeZshoAAZg5yW425oLH158KqsF4W9Y1A3+bPAAvEW+bF+4JaJpMHprGMO3l03Fbp5WmZZqAABYta5m3Dc543g4twXrdN82xe13Z0PDu2gMA1tZHJjnzHMcmUF9M5Di6cmhRQO4PDMdHPVcRw5moDB0NsBw7MzsuPXKjVVAgWzK41exHmANJUnlZAvviks9BOH21agdntd1gBGbWTdZyEmrRlvILbjv5S7nucP7qpB+H+53YnvNNZnk55-uRftaj9Xl8A8vW-bzuHG73u94wA-EBHuiKbkVW8wB3PnAS+7Zr73FvtrBOcA-b3ybl2R+69n7ygAFKMFwMFDU+wrLWQ+KgL+kong4FZk1IAA)

```typescript
import { Type, TObject, TUnion, Static, TProperties } from '@sinclair/typebox'
import Ajv from 'ajv'

// ----------------------------------------------------------------------------
// TDiscriminatedUnion
// ----------------------------------------------------------------------------
export interface TDiscriminatedUnion<T extends TObject[] = []> extends TObject {
  static: Static<TUnion<T>>
  allOf: { if: TObject, then: TObject }[]
}
// ----------------------------------------------------------------------------
// DiscriminatedUnion
// ----------------------------------------------------------------------------
export function DiscriminatedUnion<T extends TObject[], TDiscriminator extends keyof Static<T[number]>>(schemas: [...T], discriminator: TDiscriminator): TDiscriminatedUnion<T> {
  const allOf = schemas.map(schema => ({
    if: Type.Pick(schema, [discriminator]),
    then: Type.Omit(schema, [discriminator], {
      // optional: prevent additional properties on then type
      additionalProperties: Type.Index(schema, [discriminator]) 
    })
  }))
  // select first discriminator type as narrowed (literal), then derive to broad type.
  const narrowType = schemas[0].properties[discriminator as keyof TProperties]
  const broadType = Type.Extends(narrowType, Type.String(), Type.String(), 
                    Type.Extends(narrowType, Type.Number(), Type.Number(), 
                    Type.Extends(narrowType, Type.Boolean(), Type.Boolean(),
                    Type.Never())))
  // object descriminator must be broad, narrowed literals embedded in allOf array
  const properties = { [discriminator]: broadType }
  return Type.Object({ ...properties  }, { allOf }) as any
}
// ----------------------------------------------------------------------------
// Usage
// ----------------------------------------------------------------------------
const T = DiscriminatedUnion([
  Type.Object({
    type: Type.Literal('Vector2'),
    x: Type.Number(),
    y: Type.Number()
  }),
  Type.Object({
    type: Type.Literal('Vector3'),
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number()
  }),
  Type.Object({
    type: Type.Literal('Vector4'),
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number(),
    w: Type.Number()
  })
], 'type')

type T = Static<typeof T>

const ajv = new Ajv()

console.log(ajv.validate(T, { 
  type: 'Vector2',
  x: 1,
  y: 2
}))
console.log(ajv.validate(T, { 
  type: 'Vector3',
  x: 1,
  y: 2,
  z: 3
}))
console.log(ajv.validate(T, { 
  type: 'Vector4',
  x: 1,
  y: 2,
  z: 3,
  w: 4
}))

// console.log(JSON.stringify(T, null, 2))
```
So, the reason TypeBox cannot implement this type as standard is because both TypeScript and Json Schema have no concept of explicit union discrimination. Remember, TypeScript has a structural type system and does not explicitly discern tagged properties for union discrimination; and the language is permissive of unions of any data structure (not just objects and with or without property discriminators). 

While the TypeScript language does support type narrowing, this achieved via control flow checks and not something directly encoded into the representation of a type. Additionally, Json Schema has no agreed upon representation for discriminated unions. Because of this, TypeBox can't really adopt anything without working above and beyond TypeScript (potentially leading to difficulties with inference) or Json Schema (where different representations may be required)

---

### Represent DiscriminatedUnion as Union

Note, some users opt for the following form (adding an additional `discriminator` property to the existing union (which does require `.addKeyword('discriminator')` if using Ajv under strict). This would look as follows.

```typescript
const T = Type.Union([
  Type.Object({
    type: Type.Literal('Vector2'),
    x: Type.Number(),
    y: Type.Number()
  }),
  Type.Object({
    type: Type.Literal('Vector3'),
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number()
  }),
  Type.Object({
    type: Type.Literal('Vector4'),
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number(),
    w: Type.Number()
  })
], {
  discriminator: 'type'
})
```
The additional metadata of `discriminator` can be used to select the union variant discriminator. This is most often used in some code generators when mapping a structural union to nominal type system (usually a base class containing the discriminator field and derived classes for each variant).  Alternatively, code generators can derive discriminators by taking the common property (i.e. `type`) across each union variant. Such mapping however is a above and beyond the scope of TypeBox.

### Alternative Specifications (JSON Type Definition)

Note that while the Json Schema specification doesn't have an explicit concept of discriminated unions, the JSON Type Definition specification does. I've actually implemented a reference TypeBox version of the JSON Type Definition specification which does support DiscriminatedUnion as standard (this is currently offered as a separate module you will need to copy and paste to use)

Relevant links below:

[Specification](https://jsontypedef.com/)
[TypeBox-TypeDef](https://github.com/sinclairzx81/typebox/blob/master/examples/typedef/typedef.ts)
[TypeBox-Representations](https://github.com/sinclairzx81/typebox/blob/master/examples/typedef/readme.md#types)
[Ajv-Support](https://ajv.js.org/json-type-definition.html#discriminator-form)

### Summary

So, unfortunately, I can't implement DiscriminatedUnion as standard, however, TypeBox does track experimental / prototype types that may be included in future revisions of the library (or simply referenced by users who need a type). You can find the current set of prototypes [here](https://github.com/sinclairzx81/typebox/tree/master/examples/prototypes). You're more than welcome to submit a PR to include the DiscriminatedUnion to this set. 

Hope this helps
S

**Comment by sinclairzx81** [comment]
@lifeiscontent Hi,

Hey, might close off this issue as adding DiscriminatedUnion as a standard type is generally out of scope (at least for now). However, I may look at adding the above implementation to the example [prototypes](https://github.com/sinclairzx81/typebox/tree/master/examples/prototypes) for future consideration (also, as a lot of people ask about this type, it would be good to keep a reference implementation around)

For now, as it is possible to implement the DiscriminatedUnion type outside of TypeBox (as per original example), this is generally the recommended way to express this type under the current revisions of the library (but will review again in future)

All the best
S

**Comment by lifeiscontent** [comment]
@sinclairzx81 thanks for your response, I tried using your implementation but I received an error

```
Type instantiation is excessively deep and possibly infinite.

8 export interface TDiscriminatedUnion<T extends TObject[] = []> extends TObject {
                   ~~~~~~~~~~~~~~~~~~~]
```

I've seen this a few times when using `Type.Index` but TypeScript is saying its for `TDiscriminatedUnion` which doesn't appear to be using this type.

**Comment by sinclairzx81** [comment]
@lifeiscontent Hi,

Can you share the full type being constructed? (It may be possible to optimize, happy to take a look)

**Comment by lifeiscontent** [comment]
@sinclairzx81 thanks for the response, this is what I get from running `tsc --noEmit` on version `5.1.3` of TypeScript

```
export interface TDiscriminatedUnion<T extends TObject[] = []> extends TObject {
                   ~~~~~~~~~~~~~~~~~~~


Found 1 error in src/v2/schemas/api.schema.ts:8
````

**Comment by lifeiscontent** [comment]
so I have not even used the schema, but TypeScript itself is not happy it seems with this type

**Comment by sinclairzx81** [comment]
@lifeiscontent Heya,

Here's an updated version with support for 5.0.4 (and presumably 5.1.3, although I can't test on the TSP, but should work ok)

[TypeScript Link Here](https://www.typescriptlang.org/play?ts=5.0.4#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUHkBGAVhgMYw7ICqAdsBNTgMowCGMwJFAClBJrMAwBnOAF84AM14g4AcgACQ4NRIAbFsCgB6GOgz4IAD1kAoUJFhwAgoQBuk6XJZ3TJrVrgBabz99--AYFBwSHBbh7IACLAQiRQoMpsGAAmNHTU4V6h2Tm5eX4mGIYW8LqYKNGx8SCJMClp9ABKwhCqthgAPMhwRXXUySLIBMRkANoAugB8cAC8KD2GfQNwo8oSGFBwADILS4PDpORwAHSnaxtwjbsY-ftEhxPjJnBwAPxwzGwcHVvTAD4VGJxBLUJKpWhNFptTqNaYALkQomecEKxWg8GUdSgEhYJAwgKqILBDWoXWutzw9zG41mKym5OWQyp8AQyKErHYJARUSB1Vq9Qh1GaQla7S6k2RLFUqlwEgRSGAcspIyOMAAFjduQcyGIJiYke4svljSbTZlKsCaqC6uD0plTQ7HdlUSVJABXFTsehwC1860C9Jk3o3RnamATCi+okwaAMkQAawwqAgEg+HO+yFG1DdIHwGymkwAFLENSAWEIEaNTsdkOMcMledHoNyo1a2NAAJQtxttm0k8WIZEkejsuBSmWpuYljBloTHMtgYskUssWbTQusl4vRXcvTHLgceNLlc4UYNwm96DjDtYZEvdWalB73A1GDHmcsU-ny21K84Tdbi8hp8F6oKqAiYBQBg7TUPALDJA2oFSnAkF8Bs7DCHA3oPtQcBlBgd5bvBiHpFKPBoQIwi7pgxwAJL9EU75ll+Pa-lA14ooBogdsi3E8UBHhCBgqiHJImijt+frtps+FjiIoJQLwADuKRwIWqjAFiUo3nhGq4ckGzAO0eEQHA+C8PBeF7kOI7wApyloOUU7Lh+QijAADOMxyofwGFuZJTabOWcCJsmqbIORvmCEITwvMO1CjuZEDwY5+JzKlxwAKKLCGQiFvZEBKalFB7sw8TUAA5oWOkZWVyhVTphGAc1LVPjR2V7PlLCKYVxVtRgxwAHI5nmUDVSVNHDbmGzjZxrXzYBGUdblXU9UVegTQNABCECtBgLDULNGU7XtB3jU1C0tRlg3QTNHb3fxcDAcycAGRebFwCAbqJfiSXwTgBUqckcAaVpqgiDOeYIapyhjtKspjopLCoDZCXwD56HRbSSBnqx1pXgif3JKlYjIlBMBulAuEZWGG4nKcGOUSIYj-nDE5iB2cljtQKMGh4ToC4LviZJQQgsBVBGGkL0tOiY8Wjt0cytvytr0IWozIjTzIboR+HUQNWyaRsUqFrIABqhzQAATLIN6EYY+tDSNd23oBqCO1No3VbxdsvFrKo64Bev9cchtg6bFtkNAADMtuu1uDsh57LuEe7SfO2NvtbgAXh7Gfey83Hx-7hyB1uwcZWHxuqBHltQAALHH9t59Nmfxy8afXfnWcvLn6et+dgFKS3XuPdxJh1nI+G2yYJiyYraZfCQHT4SmKASnLtljnYtLUBgSnWHY3ubwle3HKoEBVc4tjHLYUrAMkSSFsgrPIsH5t1zb8eJwAjPHadW31PdE+IoRLn0voWa+t976PzqM-V+949AIg-lHKAsdv4Ij-siAB8c+7RyATxeWZ8L5XzsNAjSsCMDwMQHNd+kcYwN1kBguAWCO4IitrghE0d47DzgPXAhs9DRELASQwsAApRguBBrHHZOVCqipUDUOzNKHAVt7pAA)

```typescript
// ----------------------------------------------------------------------------
// TDiscriminatedUnion
// ----------------------------------------------------------------------------
export type TDiscriminatedUnionResolve<T extends TObject[]> = 
  T extends [infer L extends TObject, ...infer R extends TObject[]]
    ? Static<L> | TDiscriminatedUnionResolve<R> 
    : {}
  
export interface TDiscriminatedUnion<T extends TObject[] = []> extends TObject {
  static: TDiscriminatedUnionResolve<T>
  allOf: { if: TObject, then: TObject }[]
}
```
Hope this helps

**Comment by vanya2h** [comment]
@sinclairzx81 fixed a little bit your typings:
```
// ----------------------------------------------------------------------------
// TDiscriminatedUnion
// ----------------------------------------------------------------------------
export type TDiscriminatedUnionResolve<T extends TObject[]> = 
  T extends [infer L extends TObject, ...infer R extends TObject[]]
    ? Static<L> | TDiscriminatedUnionResolve<R> 
    : never // <-- CHANGED FROM {}
  
export interface TDiscriminatedUnion<T extends TObject[] = []> extends TObject {
  static: TDiscriminatedUnionResolve<T>
  allOf: { if: TObject, then: TObject }[]
}
```

**Comment by sinclairzx81** [comment]
@lifeiscontent Hiya,

Unfortunately no. The Composite type was updated (literally yesterday) to generalize for `TSchema[]` (previously it was constrained to `TObject[]` only), making it compatible with Intersect and Union. However Composite is still limited only to constructs known to TypeBox (not user defined structures)

The reason for this is that Composite needs to compute each property of the return TObject, of which it may need to Intersect or Union each property derived from structures passed on the `TSchema[]` parameter. This following shows the Implicit and Explicit implementation of Composite for the types A and B, and note that the properties are pulled through TIndex for R2 (which is what R1 does implicitly through the type system)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAWABQw1qxScKcGBDgBhIpCowMw2hGoV4AQTgBeCZgB0AeS4ArDLRgAKBMLhxeALkMYjAOQCuILhig2AJTC2MFC6prwAEL6bqYWVrb2Qo4ucd6+-kEhYaLiAJLg9MC0wPAK4BDKquEaWnAASgCMsWjGFUplGDYA2toANHBRALq5QmJwAKK8YMWl5YpVXWp18A0ATK2c8ZbWdg5Orm3u+dQqUBSJvY43t3dwE8gAFsBSr3Dq4F4qACZwoLMSmV6Kh8NB5ItqgdHMcjKcfhheDYBnAeiR+KN+tC4vDETYooM0Riwo5RjkgA)

```typescript
import { Type } from '@sinclair/typebox'

// Types to Composite
const A = Type.Object({
  x: Type.Number()
})
const B = Type.Object({
  x: Type.Number()
})

// Implicit Composite
const R1 = Type.Composite([A, B])

// Explicit Composite
const R2 = Type.Object({
  x: Type.Intersect([               // This is computed implicitly for Composite
    Type.Index(A, ['x']),
    Type.Index(B, ['x'])
  ])
})
```
So, in order for user defined types to work with Composite, there are two main requirements needed of that type.

- The type can produce enumerable keys (not shown above, by used in the Implicit version to derive property key `x`)
- The type can be indexed with those keys (shown above)

As of today, I don't know a way to make this work for custom schematics (as many of these details are hard coded into TypeBox's inference and schema compositor). But it is possible to have this work if you're willing to express schematics known to TypeBox (for example, expressing TDiscriminatedUnion via TUnion)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUHkBGAVhgMYw7ICqAdsBNTgMowCGMwJFAClBJrMAwBnOAF84AM14g4AcgACQ4NRIAbFsCgB6GOgz4IAD1kBYAFChIsOAEFCAN0nS5LB6bPmtWuAFo--gMCg4JDQsPCwz29kABFgIRIoUGU2DAATGjpqKN8IvPyCwsDzDEMreGUYDCgJFhIMFDiEpJAUqozaegAeZDhSquo0kWQCYjIAbQBdOABeOCmAPj7DAaG8IlJ4BHM4OCFWdhIALjhmNg4ezO7kBYWduBZVVVwJE6RgV-Wx8jgYAAsMNQTiMNmQxFNzKIckUYbC4X4ck1EslqKkOllofCsdjQiUytB4BIAK4qdj0OBIlptdJXag9ZarYajTZTCiUlFsaAMwFrADWGFQEAkpwOF2Q42oRJA+Gqk1uAAoEgCQCwhCdxgA6LXISY4NLxZGtVEwaDA9lGzlQACUZoNVONNM6dJuiHuJHo+weTxesz2JGVqo1KrAiv9GBVsyW8u2Zl2uw+wL0Gq4HF5oYDOHG+uaHJNUEmVqw912-0BicwGtwrRg6fDLEz2cNbWgutdsbjuy8cD4ZNRqhOYCgGHsgPgLDS+t7jzgg741XYwm71F+AOXukwcHlpUwYPoqlQcEb9stVuLcfHk6yjx4c4EwnLGA1AElBqVayqG3bcy2rXAz6JT3bADAM7bwhAwVRNkkTRPSPb8oF+PQHhEVEoF4AB3dJN1UYAqigR5CxXQFD2qYAR1+CA4HwXhx0Qis3Q9eBUIwtANzmJU6yEcYAAZJg1Wd+AXLi4ItPNkLgflBWFZAb0EwQhEmBjqE9aiIHHViGjmDSNQAURWHkhHlZiIHQjSKCTZgkmoABzeVCO0yzlFswizw7Nz3JQJM9MZIyWDQkyzM8isADkpRlKA7PMkKwuqSK-3bDzErjbTvIM3z-NMvQosfAAhCAIEglhqDi7S8oKjAisi1ykvc7TguHWKrSakC4C7CBQXgNJhCbY0uRAIkVIaVTxxwYzMLSOAcLwx4RHDGUJyw5QvWeYU-Pw1AlM9AT53k30kCzL9RJbE5hrSDSxHuIcYCJKBl205kyGjOAtX43g5MXMQcCQR4VrEX9VQeagNrMKEzC7HEIchnwckoIQWGsjBMSh5HYXMd1lPgXo5nNal0XoeVxnue6OujM91wwB8NQAGVw6pHnlWQADVNmgAAmWRCzPQxKdC6VGqLBK4FQHmYoilqAIF3Zie+UnBfJymaem1QGeZshoAAZg5yW425oLH158KqsF4W9Y1A3+bPAAvEW+bF+4JaJpMHprGMO3l03Fbp5WmZZqAABYta5m3Dc543g4twXrdN82xe13Z0PDu2gMA1tZHJjnzHMcmUF9M5Di6cmhRQO4PDB7wAE04HiOBqAgeBSzgd00Kg8m0cYuBK60pMAGEIHACAlCqAnkGyysSYQCR8spxybLsgCC0zsx0c9VxHDmagMHQ2wHDsxfl-KjVVAgWzV41exHmANJUnlEfEHiks9BOH21agdntd1gBGbWTdZyEmrb5SB8j4nwcGfC+V8h63yQPcd2z88ya3ficL+9wf7ayjurP+gF96QUPsfeUp9z44QgRgG+X1750QpnIVWeYA6ILgMg9sqD7joO1gnOAftMGLy7Ngx8wD5QAClGC4GChqfYVlrIfFQKQmuRIng4FZk1IAA)

```typescript
import { Type, Static, TUnion, TObject } from '@sinclair/typebox'

// ---------------------------------------------------------------------------
// TDiscriminatedUnion (via TUnion)
// ---------------------------------------------------------------------------
// Represent TDiscriminatedUnion as TUnion. Add non-standard discriminator field as metadata only.
export interface TDiscriminatedUnion<T extends TObject[] = [], D extends DiscriminatorKeysOf<T> = never> extends TUnion<T> {
  discriminator: D
}
// Derive candidate discriminator keys from the TObject[] (taking only keys common to all objects)
export type DiscriminatorKeysOf<T extends TObject[], Acc = unknown> =
  T extends [infer L extends TObject, ...infer R extends TObject[]]
   ? DiscriminatorKeysOf<R, Acc & keyof L['properties']>
   : Acc

// Just return a Union structure here (and optionally assert D is a common property of each object)
function DiscriminatedUnion<T extends TObject[], D extends DiscriminatorKeysOf<T>>(objects: [...T], discriminator: D): TDiscriminatedUnion<T, D> {
  return Type.Union(objects, { discriminator }) as never
}

// -------------------------------------------------------------------
// Example
// -------------------------------------------------------------------
const T = DiscriminatedUnion([
  Type.Object({
    type: Type.Literal('Vector2'),
    x: Type.Number(),
    y: Type.Number()
  }),
  Type.Object({
    type: Type.Literal('Vector3'),
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number()
  }),
  Type.Object({
    type: Type.Literal('Vector4'),
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number(),
    w: Type.Number()
  })
], 'type')

// Squash the union into a singular object (with type: 'Vector2' | 'Vector3' | 'Vector4')
const A = Type.Composite([T])
type A = Static<typeof A>

// Composite Squashed union with { foo: string }
const B = Type.Composite([A, Type.Object({foo: Type.String()})])
type B = Static<typeof B>
```
The above TDiscriminatedUnion would function as a typical tagged union structure (as the common type `type` would be enough to discriminate a variant of the union, both at runtime, and in TypeScript), with the additional `discriminator` metadata used to signal what property of the union is used to discriminate when publishing (and possibly leveraged by nominal type systems to generate an analogous type)

This is currently the "state-of-the-art" in TypeBox, I'll keep trying to think up ways of making types with fully custom schematics composable through the type system, but as of today, working within the constructs provided by the type system is the only way to ensure compatible with each of TypeBox's compositor functions.

Hope this helps
S

**Comment by lifeiscontent** [comment]
@sinclairzx81 did you fix this recently? I'm no longer seeing type issues with Type.Composite

**Comment by sinclairzx81** [comment]
@lifeiscontent Hi,

Yes, there's been a little bit of work done on Composite + Union recently, mostly to correct an issue with Non-Distributive compositing of Union types. The details are a little long winded, but the following is the current supported and not supported functionality for Composite + Union (as it relates to recent updates)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUFKT9+KYQCEJcALRwAchHZqAIsBYwowEQFdiANwxwAFLjNhIsDABMAlFLhwSOo3ABhOABeRUwAOgC6SDYYDFsAbS9vMIxwgFV2YB1E5JSUtAiAeREAKwwSGFskAgAuVPD8E3YAc1t3CncsPPyGkvLK6rgResK0po42jvIunoBdWfyx8P6KqqQSUeFwzTMQEQwods7u7wXkoUwUELxCYhIAHkuMCCpAgD4pchk5BTHcEgmMDwDTaXQGIwmcxWGz2RzOOIeC7CQI3Ww9Gr1SGTChwAA+GOGWOMOO+3g6ADJED1NnB2HsDlBkmS4M9rqEEAkANJwDhwADWGFQr0Cc3qAW5c0oVIQ32+sjg8lSAKBILgEJJ0OA1js2ngLHh0ERnm8bL0D2Q7xunJ5fMFwreyDFKEl0sQ8tNKKCoXR+UxcGxrVxBL9RIDJKDLMp1PytPp+0OzORV2QN3NAStSr1AcNLlc4QLBdQGBgXyAA)

```typescript
import { Type, Static } from '@sinclair/typebox'

{ // TypeBox - Non-Distributive (Supported)
  const C = Type.Composite([
    Type.Union([
        Type.Object({ a: Type.String() }),
        Type.Object({ b: Type.String() }),
    ]),
    Type.Object({ c: Type.Number() }),
  ])
  type T = Static<typeof C>
}

{ // TypeScript - Non-Distributive (Supported)
  type C = (
    { a: string } |
    { b: string }
  ) & {
    c: number
  }
  type T = {[K in keyof C]: C[K]} & {}
}

{ // TypeScript - Distributive (Not supported)
  type D<T> = {[K in keyof T]: T[K]} & {}

  type C = (
    { a: string } |
    { b: string }
  ) & {
    c: number
  }
  type T = D<C> // Not supported.....yet
}
```
There are plans to support the distributive property of TS generic arguments (so 3rd example), but it's not clear whether this functionality will appear on the existing Composite type or a new Evaluate type, however resolving for these finer cases will likely be in the next significant version of TypeBox, where I'm currently leaning towards the following API.

```typescript
const C = Type.Evaluate(Type.Intersect([
  Type.Union([
      Type.Object({ a: Type.String() }),
      Type.Object({ b: Type.String() }),
  ]),
  Type.Object({ c: Type.Number() }),
]))

type C = Static<typeof C> // type C = {
                          //   a: string
                          //   c: number
                          // } | {
                          //   b: string
                          //   c: number
                          // }
```
Hope this brings some insights!
Cheers
S

**Comment by Lonli-Lokli** [comment]
Seems like solution from https://github.com/sinclairzx81/typebox/issues/633#issuecomment-1890304484 does not work (using 0.32.35)
