### ISSUE TITLE
No typescript error generated when using nested TypeBox types

### ISSUE THREAD

**Issue by sanderalvin** [sinclairzx81/typebox#636]
Hello

When using nested TypeBox types, then in some cases TypeScript errors are not generated. 

Here is quite small code snippet where the issue is reproduced (on line 39 in `problematicFunction` body). 

Using latest version  "@sinclair/typebox": "0.31.17"
Using typescript version "typescript": "5.2.2"

```
import { Static, Type } from '@sinclair/typebox';

export type OA = Static<typeof OA>;
export const OA = Type.Object({
	uuid: Type.String(),
});

export type OAEnriched = Static<typeof OAEnriched>;
export const OAEnriched = Type.Object({
	uuid: Type.String(),
	uuid2: Type.Union([Type.Null(), Type.String()]),
});

export const OS = Type.Object({
	items: Type.Array(OA),
});

export type OSEnriched = Static<typeof OSEnriched>;
export const OSEnriched = Type.Object({
	items: Type.Array(OAEnriched),
});

export type OR = Static<typeof OR>;
export const OR = Type.Object({
	things: Type.Array(OS),
});

export type OREnriched = Static<typeof OREnriched>;
export const OREnriched = Type.Object({
	things: Type.Array(OSEnriched),
});

// when you comment out this function, then error from problematic function also disappears
function showProblem(or: OR): OREnriched {
	return or;
}

function problematicFunction(ors: OR[]): OREnriched[] {
	return ors; // this should trigger TS error, function signature expects OrderEnriched[] but Order[] is returned
}

```

When using native TS types instead of TypeBox, then the issue does not exist:
```
export type OA = {
	uuid: string;
};

export type OAEnriched = {
	uuid: string;
	uuid2: string | null;
};

export type OS = {
	items: OA[];
};

export type OSEnriched = {
	items: OAEnriched[];
};

export type OR = {
	things: OS[];
};

export type OREnriched = {
	things: OSEnriched[];
};

function showProblem(or: OR): OREnriched {
	return or;
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function problematicFunction(ors: OR[]): OREnriched[] {
	return ors; // this  triggers TS error, which is good!
}

```

**Comment by sanderalvin** [comment]
Coworker made even a smaller [isolation](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZRgQxsAxgGjgFQE8wBTOAXzgDMoIQ4AiAAQGdgA7LAGzWCgHoYxEgCMIADwYBuAFAyS4yLDhDSKEGi5cSUIqTHi9ZALwp0mLAB5VJCFXWbtu4QaMA+WQqXwsEdi3hkDS0dI1dhOFMjADoAeREAKxIsGAAKBBk4OG0ANxIuAEYALgJhOMTktIysrNz8gCYSmPiklPTMmqyqCAgmstQoDgBzVIBKHA6s8nGO6Ynp2XlFaHgbOAAhYCGh0JcJI0izDGxrYTsNrZ3nfX3hDyXvOF9-eE3t3ZvDCKiylsr22okPKFPqkcqtKqTbJAhqgkjg-7VTrUHpw6IDYZjCbIuAiNBQNEY9gjGadOazGYLORUACunEwfjgYFoIm0GgsADE6SlgH5UtAWCUgo4PqJbqQANoAXVGJTeVzC4pI0sQHSgJBgNKg7DgAqkcH4-DglksAFpTSoABbAFhwFiWiA0rgAEzgOloUBk5Dka2FISgADljnkDqYkXUQarOhHGlHkd1enaYINibIyWmKLJyIs1vKdEHMCHvnGI8U44DgbGkZ0EyUAimhhnOniCUmG03M7Ms4tafTeTr2BAYAAFFls45YLl9vkCoXBJwF4BFyUyuWXfPBkhGFVI9Wa7W6qAsfWG41mi0wa22+2Ol1uqAer0yIA)

**Comment by sinclairzx81** [comment]
@sanderalvin Hi, thanks for reporting

Yes, this is a very odd TS issue (and I'm mostly at a loss to explain it other than it being some TS optimization for deeply nested types). I do actually have a vague recollection of this popping up a few years back on an earlier version of the compiler, and I don't recall there being a easy solution (not without dropping TypeBox functionality)

I've submitted a ticket to the TypeScript repo to dig a bit deeper into the issue (or to try get some insights into it). You can track things on ....

https://github.com/microsoft/TypeScript/issues/56138. 

### Workaround

In the meantime, you can get around this issue by implementing your own version of `Static<T>` (which is very easy to do). See the following link which resolves the issue.....

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUGUDGAFhiAIZwC+cAZlBCHAEQACAzsAHb4A2pwUAehjoMAIwgAPRgG4AULOGY4uGKRjB8AHmRwMEmBg4ATVniIlSAPjgBeFAG0A5K1Xr8jgLpwBAuDELAptycGPKKGHCBAKIAjgCupNyaAII4AELWdsm6+oYmcGlwAPwFOQbGptklMFBxEQBcNImsDU3cLXIKIspk3NwAcmrAAG4YaEp2CLJwcNwYo9wAjI1TMzNzCwBMK9NrM9QQEI0uUJwA5nJ7FJeUcteyepCwft24vXNQ42KSX7bKrhpNOEINQeoluF9xBICMQyJY5I9oPB8BAOC4wX1IZIYRY-l8AHQAeVEACsMPgYAAKVazeYYJaNAnEskU6m7dZ07jbFAiImk8lUml7A5HHmYfEqU4cM6UgCU7Mo8pmFHlKvkXSUaWAZ0G6lGv0muw29OWiAVxq5Oz2+0Oxxq5xue1EpCgdqlFwV92VdwREie8HCBW1WIkBv+Qy0wNBWrOIZxcN9-rgKLR8BjcfMZDxvOZArZHIWpqZ-NZQtpW0ZOZLgoVNtFBMl5zlWFrcGdrrFGAl9ulcs9SsVsjV8jm8FY72ZIcab3BGE+IihYYQFtNy853IQIsajHH4MYFAPslHbe1k4Xkka6fPoe6kxXKwtG63TFE2sYOHb29fZ33h+Pu76ZldRGDBp3eYD9VvRB72g9cVmfRhv1-CgjwweBvyAoZRkvbUILGKC10LB84MQBCkI-F0vzfA8UNkHwUACUxAkiLhoCgAVZAw0kQz+ADuDPTAoU6ejkGIFo4BdCIUSgdiKU409STw3iJ0UrCMDkLiSR4uw+MwvV1Pks49JA5TwQE74JE6DUIgAJQwVg4m4GBtMiVhYgSJIr0En4RBwGc+jnEMvmsej-GY1hCAgRyjDbCJqGaUJ6JmAA9IprLgOyHKcpS7GieJEk0GM8K+PzwLU4LvF8MLTAiqLuBi0Q4oSujfBStKgA)

```typescript
import { Type, TSchema } from '@sinclair/typebox'

type Static<T extends TSchema> = T['static']
```
Just note this version of `Static<T>` won't support recursive type inference, but all other types should work as expected. 

Hope this helps
S

**Comment by RyanCavanaugh** [comment]
I'm still working on the bug from the TypeScript side, but a key part of this is `P` here:
```ts
export type Static<T extends TSchema, P extends unknown[] = []> = (T & { params: P })['static']
```
Intersecting `{ params: P }` can't change the type of `(T & { params: P })['static']` - what's it doing here?

**Comment by sinclairzx81** [comment]
Hey, thanks for taking a look into this.

> Intersecting { params: P } can't change the type of (T & { params: P })['static'] - what's it doing here?

The P parameter is being used specifically for recursive inference (via HKT intersect). The P is used to capture the `This` argument (and return) in the following type.

```typescript
const T = Type.Recursive(This => Type.Object({
  id: Type.String(),
  nodes: Type.Array(This)
}))
```
With the supporting types...
```typescript
export interface TThis extends TSchema {
  [Kind]: 'This'
  static: this['params'][0] // captured here
  $ref: string
}
export type TRecursiveReduce<T extends TSchema> = Static<T, [TRecursiveReduce<T>]>
export interface TRecursive<T extends TSchema> extends TSchema {
  [Hint]: 'Recursive'
  static: TRecursiveReduce<T>
}

...

declare function Recursive<T extends TSchema>(callback: (thisType: TThis) => T): TRecursive<T>
```
It is possible to omit intersection from `(T & { params: P })['static']`, and just `T['static']` but would come at a cost of losing singular recursive inference in TypeBox (although there may be more elegant ways to express this)

**Comment by sinclairzx81** [comment]
Related Issue https://github.com/microsoft/TypeScript/issues/55535
Related PR https://github.com/microsoft/TypeScript/pull/55638

**Comment by sanderalvin** [comment]
Thank you for investigating this @sinclairzx81 and @RyanCavanaugh!

Am I understanding correctly that this [PR](https://github.com/microsoft/TypeScript/pull/55638) fixed the issue on TS side and it will be fixed with the next TS version update?

I will use the workaround until then time

**Comment by sinclairzx81** [comment]
@sanderalvin Hi,

> Am I understanding correctly that this PR https://github.com/microsoft/TypeScript/pull/55638 fixed the issue on TS side and it will be fixed with the next TS version update?

Not exactly. From my understanding, the https://github.com/microsoft/TypeScript/pull/55638 PR was an updated compiler strategy for better handling deeply mapped types (where the compiler would give up checking deep properties after a few levels). Unfortunately, it appears TB is unable to take advantage of the updated compiler strategy due to the way it handles recursive mapped inference.

As this issue seems to be related to compiler internals, there isn't much TypeBox can do to resolve things at a library level (at least there's no trivial resolution to the issue I can think of). There may however be an alternate inference strategy offered by the TS team that may prove more conducive towards internal compiler optimizations, will need to track https://github.com/microsoft/TypeScript/issues/56138 for updates and commentary from the team and community regarding this.

For now, the recommendation would be to leverage the user defined `Static<T>` if you need exact assertions for deep objects. 
Hope this brings some insights
Cheers
S

**Comment by sinclairzx81** [comment]
Possible library level workarounds (but not sure how well this would scale)

[Workaround 1](https://www.typescriptlang.org/play?#code/PTAEFpK6dv4YpyUIFAlAdQPYCcBrAQzxwFcA7AEwC5QALAF0YAcBnGkAcwEtH6yAIwB0AYxwBbYBJ6jSbHADNGwACoBPFgFMAynJ4sVPNmzJa2wAKwA2AIwBmABwYwqN+4+ev4NGkWVRRh4cClA8LVEyPDYeADctDW0ACh4KFjJGOgAlCKiY+IBJNIyAbQBdAEps3Oi4rQB5DPTGctAAbzRQMK1GKNDU5oBuUExFIh4AGzpBDNAtAA9tQK0qUCozUEYcNa1DelAJnhlGNABfPwCgkNBFVL4EzS0U4szQIubyqtBG1lKy9s63V6eH6L2GmBwBDOvkw3jh8IRqBcoBykVq8WRiKx2KxaAWLHwjE2jxRNXyWneswAvKAdIwiEFRAAeRiPJSktHkymMAB8eMWhNA4gobCJqLydW5oBpiS0wnF6KeqnoxmlPNAsuE9UEACsIowkm1QICJlp4hNbHRNdq9YFDYCuqbzQAmK2PLW6-X2ro+g5mrQTexu7Qe20Gjq+31OgMAFmDcptXojkd9ihwOCtKrYDsjpwqOa6eZzRcL+bz+fxgtZ2g5EviP2a0tp9MZLLZilriobGT5lbwROFos75O7RJl7oV5KSytVVPV1s9dqNJv9FvjoaTOejE1dGvdiaXBb95qDe5DB-DR8dq7jZ4Ti8vKdT6czxgANFefYISK-s0-QCWub5r6gFFuWMKuDiUHQW4yIAGJ3IwWiYjBqFobA-IEv2xI1lKNJ0gyshtto7Lcr2ArYYORJ4XeG6Hte5qWrRF7ej6267guYasVGq6npxm7-tut78fR-43C+tF0ngqRcEkFQfv+gEgcBPqgWWFYUUS1ZaN8TTUs2hHMtp7KjuRWEDiEQ6jk2ImPseAZMbZ3H2Tu64scmPEnm5D7OZ5sbeVxHlPmmGaSYw0kULJ8mfl0354OuUkyXJClPkpqkqaWgJgfmKHoXlqHIgRjLGrC+VlVBmFViSAAKpDaP2PDmAAEkQbAzm1jxMqoczzEh1BsBqtU4PVQTmOqNLLl0JQANKgKkoAEFo6jsqoZR0C1bVZrKXUzWU6oLH1VADeFGwAPygLYoB0AADMaAElIty0dqtPWHQNqSKFoeAondXTnZdB1aP1P0FudJ06QWdBjBMbAQz6dAUP6eC+H2Wkkht7Xbd1gPA6oej0FoEhEONgLY71QNHRq7WgGDeAbHQpOvRTA2qBeTIfV9oDVeq51DSNjVsBjW2ddzV2-dDsMo5pOE6UVRFk29Gr44TRBvlzTPA5QBAUDgADuFCtDS5RqxtTZC8YWM8uNoCmzjlPg7953TqAABk7SgCwJBEBIHDq3mJQAOSioZAf-CMYDhJydQewy9CAlagfB4yodian4c3IhOme-wEEQOV+eIsieOiATRO5QXFeeJV2GpEheBjKIOnF6XRAAl0SeyHQWs6-rgKe3g3u+93esG2U0KlZXk+wZgrMPuXU8L+gqMy4NdVfaNA00qi+BUEyooRVwavNyrZmCrXX0N03bMK8zq-DevAv7eTuPK0Tbcy3QAc4A+AeAh3oh0CNDNOaoRHorTWgZVsqhdpq34MYQO-dB6h3VOcc4E9F4YIwjPRKkV56YPwdXIk5965EEbkrcKMkNaU2Pm-ZM2lP77xkr-duLZO6gEYbgtBkF8E8J8DPdqeDeEL0ISAuul8qZZioSzV+rc6GPE-nAtgzD2GsIAZsLMCCvY+1DiUa6Y8uF5yEZgouk46iCKMZXER2kNSmPiDkdYjcupSKViXE+TY5bMlUGrEoqhbFaHsWQRxqgeR7REcQ8RviyR1CcXbaRriiZP0VjQ2RgJ6GgADpHOsWhlH-ytH4gJQS+QGIscYmejxzElPziIqgEQJgkB0hQb25hPZkNlO-Ze-gKCBGCKEPxMTn7UJkTyJIogiATAmN+UQBA6BJEUbKK07UKhqg1F8SJUd4hdT5F0DplwenfAfP0pJfMH5jSSCwNeDVzBWlWdfLZPVzI3F2dcHBUUrQvOhGgIAA) (Inline)

[Workaround 2](https://www.typescriptlang.org/play?#code/PTAEFpK6dv4YpyUIFAlAdQPYCcBrAQzxwFcA7AEwC5QALAF0YAcBnGkAcwEtH6yAIwB0AYxwBbYBJ6jSbHADNGwACoBPFgFMAynJ4sVPNmzJa2wAKwA2AIwBmABwYwqN+4+ev4NDwkt8RlAAb1ANbVAAX1BFUglQAHIAATYeClEAGyIePGBGTS1BHAAPBLQ0RUpRRh4cClA8LVEyPFSANy1wrQAKNJYyRjoAJSaW9q0ASQp+xgBtAF0ASmHR1p4OgHkBmYWQtFAGrUYW+r6BgG5QTEVsjLpBAdAtYu1qrSpQKjNQRhxPrUM9FAGT8fDQkQqVRqdRiaT4nQKvWmAzoUx2SzoW1YA12wX2h2OeFOyMYl0wOAI4PKmG8tLp9NQLlAI2aaw6TIZnK5nLQzwCeCC+QiLLG60mJNAAF5QDpGEQaqIADxCrRKZmrcZogYAPl5L0CoHEFDYQRFbPFMylYQKwjN426qnoxil2ut2mEG0EACsmoxuqF8RktB0MrY6F0Pd7ff78QcgyGAEzhm2en3VGMHTPA4NaDL2ZPu1PRvFZrPx3MAFgLWkjab9JdLWcUOBw4adbFjpcii07B27nf7fZ73Z7fINKvVrPGWMt0tl8tkyoKartYpnOr1-KCRpNk9Fm22j2lEdXHQd7ZdbprRfTAbjOdD1drxc75YySavz9vvezIfzn5vesf3vEMqwAqNv0bJsWzbYwABpgMzQQSFgjsoKiHtG0HTNsP7EdqVcbkiOItwmQAMThRgtA5EjaLo2BN3HApQC1II5zlBUl20NVWN1McBUNOpd1Yq0I0AjNf1zMNwLrCSQNzD8xIgoDGzff8lNkhtVIfMCNJfdCDmbVtP1lPA0i4bpFgQ9DsKzWyMPxPDR31ASJ3XNiZQ4xcVTVdy+Jc7chKCdzRJTZSJLfaS9MgzM30UsLNJ-NSn3ErTSzfXSEv0gyjKfUzzMs6yDOQvA8sYMyKAsqzEPsocB0whz+xo+iWtopl5wVUBugANS0NYYQTAB+HsaVasaiN8fwDQAKlAIg2CvBbYkkRIUjSTJslyFUilKcp+MFZjVDIFggwACXmx1jC6RVVCeYoqOoBaujYYRVD0egtAkIgFldaV8Vu54HqoBbZjSRQ+tAAAZO6gaegoXre0QPq+uDQGEdGwYhoYYa0R7Fte97Pu++Z5k7QbQHOthLqpgpFUh11Adx4Gfjwb4f3J8q2cbcNjrOi722uoZXU7OgbgyNhqMY1zmIABVIbQBR4cxKep66Afupm4e0BG5ZwBWanMX6QlAfFZgAaVANJQAILR1DVVR5joFWBdp1RzfmBmNbxzmtFAcnbFAOgAAYTaiWYbbtxQwnmHG8cxvBmVDg5-dj5nsd7DnWd93tRaIcXs8zXP872gKfmY52rtd1OtfMAmkaJ37-ur-HVAAYSC1nqnwRV49AGXUd7oW-bCXmtArmntEVGXPdhlnvkz74nf5yvJ6Hmgm8ZvHntesioVqCge4ocGE-7y2j6x11yaOk6x+XietCnmfNbn32F99peqZd1fXXXg51dn7eqhAKH2PjKS+fd5Z9QNmwce10dA-yTv-Z+gCphUVaL6EBEN4HD2vnzT+K8H7YN-mEZugCACqFB96YITtgq+o9YG0yIRvL2zNAG4Ifr3WhI8b4MMnkwv+pD4avQAIJ4DwEQdQ1CwHD14YQn+zCAFCNULrGQEspFcNkYqfhJDN6sKUcItg6h0gTDQfKbunDwGaO0UgreSiTF9TMXgdRli75wPkQI3RNcEbU2Hj7QOScxYSxLluMuEQOqLhsXo7WddkZEFRjLZulACAUBwAAdwoLsaUCxUaUytJo1Q2oja5M8S-JO5MHSgAAGTGxYCQIgEgOB9wwrMBIJoFyiASDHK4YBGhTjFKAWp-B8ThhaW0hUnSDKTO6bCShVEBnynoEAA) (Integrated)

**Comment by sinclairzx81** [comment]
@sanderalvin Hi, 

Hey, can confirm this issue has been resolved on the nightly builds of TypeScript. You can test by installing the following.

```bash
$ npm install typescript@next  # installs TS 5.3-dev
```
I'm not sure when TypeScript 5.3 is scheduled for release, but it's unlikely I'll be updating TypeBox with the above workarounds (as they would almost certainly implicate performance). For now, the recommendation will be to keep on with the user defined `Static<T>` or simply `typeof T.static` if you need deep property assertions.

```typescript
const T = Type.String()

type T = typeof T.static // this also works
```
I may close up this issue for now as there is nothing to action in TypeBox, but will be keep an eye on the TS 5.3 release and possibly notify on this thread (just as a reminder to upgrade). 

Thanks for reporting this issue!
All the best
S

**Comment by sanderalvin** [comment]
@sinclairzx81

I tried with a TS nightly build and I cannot concur that the issue is 100% fixed.

Check out [this example](https://www.typescriptlang.org/play?ts=5.3.0-dev.20231031#code/JYWwDg9gTgLgBAbzgZRgQxsAxgGjgFQE8wBTOAXzgDMoIQ4ByAAQGdgA7LAGzWCgHoYxEgCMIADwYBuAFAz+-OADkAgvgCSANQCicbQA0VAWQAKAGV0Baazdu25Q0ihBouXJRmAA3EkScBeRBk4ELguEh8uAEYALiDQhLCIki4AJjiEYMTsqggIOJYYKA4Ac1lskPJy0KqZWplHMgAhYBKPTB8-MkDMhPDI2PiK-pT0oYrQ3Py4QuL2MqyJkJE0KAKi0urs2oTa+oUCAHcIOAATEhIwLkI4dhJCklO4RpY4Eu8yLGgoEix4EigtCgMioAFdOJgIOxbp4fE1VgAKMCrNAgOLIFxudofLoAbQAugBKOItNqw3zCAnjOA-GCgqDQ5FQVGychyA52Tk2dmKfAATRM2iaAHl9HpDKYLHAuVyHMJnK4uF0xOIunBAqhPFgADyNCBUBVuZUSLoAPlkX3YhUNSuEKrVgS6ADphSIAFa-GAI3qhEbROLOlSAtCEBHO10ev7exaJP1jQPB0Ph92e6NLSZ5APCJ2oOYlBGEnAx3aEwsx8ilosV2QNeWk42q+Ua9CYHV6g31u0m4TmmSW62d0j2psEbMR1M+kJ+wYJ5lJscpqOT2PJNJZ0hOoNzsMLyNe5cTKbrkg5jbzAtF9PLVbH095i-FmqV8vP6s86jgv7AKHUPJIlFojaDZdMScCDqI3ZOJkBwhLS9KMgBsgHGy8iKAAwvSPzsDA1zPAAFsAryEXAHBfICnpOnA6jwCwoJgJALCPM8Jx4WgPhwACQJwGgRHQgAROw5LwlAfEceIqJXCQqFUQahAQKCcCfnQIAkNhcB8VMoloGIPgBgRryHMAbhvB8HGAtAcAImRPx-HAIgkKxXjflAhLSeosnyYpnDKap8AaXkon2VwECHHpxGGcZSjCvgJnsZxFkIqR3yenZDlsc5rlghC37QisUD-sygEYoqwGUkSJKtKVpBUsucEMnATIsnU75ZV+P5TAVqLopitpDpBJCgeBw5QdJsEkHS9WNSASGKChHIygtMhAA)

I am expecting a TS error on line 58, but it is not there.

**Comment by sinclairzx81** [comment]
@sanderalvin Hi,

Hmm, have also tested and also note the behavior (on 5.3.0-dev.20231031). These issues are very much related to compiler level optimizations (and possibly caching issues) and there isn't much I can do to resolve at a TypeBox level (not without dropping recursive inference or potentially hindering inference performance (as per workaround)). 

There is however a way to get TS reporting the error, either using the custom Static<T> (as mentioned previously), or you can implement things this way (expressing the return type as a generic)

[TypeScript Link Here](https://www.typescriptlang.org/play?ts=5.3.0-dev.20231031#code/JYWwDg9gTgLgBAbzgZRgQxsAxgGjgFQE8wBTOAXzgDMoIQ4ByAAQGdgA7LAGzWCgHoYxEgCMIADwYBuAFAz+-OADkAgvgCSANQCicbQA0VAWQAKAGV0Baazdu25Q0ihBouXJRmAA3EkScBeRBk4ELguEh8uAEYALiDQhLCIki4AJjiEYMTsqggIOJYYKA4Ac1lskPJy0KqZWplHMgAhYBKPTB8-MkDMhPDI2PiK-pT0oYrQ3Py4QuL2MqyJkJE0KAKi0urs2oTa+oUCAHcIOAATEhIwLkI4dhJCklO4RpY4Eu8yLGgoEix4EigtCgMioAFdOJgIOxbp4fE1VgAKMCrNAgOLIFxudofLoAbQAugBKOItNqw3zCAnjOA-GCgqDQ5FQVGychyA52Tk2dmKfAATRM2iaAHl9HpDKYLHAuVyHMJnK4uF0xOIunBAqhPFgADyNCBUBVuZUSLoAPlkX3YhUNSuEKrVgS6ADphSIAFa-GAI3qhEbROLOlSAtCEBHO10ev7exaJP1jQPB0Ph92e6NLSZ5APCJ2oOYlBGEnAx3aEwsx8ilosV2QNeWk42q+Ua9CYHV6g31u0m4TmmSW62d0j2psEbMR1M+kJ+wYJ5lJscpqOT2PJNJZ0hOoNzsMLyNe5cTKbrkg5jbzAtF9PLVbH095i-FmqV8vP6s86jgv7AKHUPJIlFojaDZdMScCDqI3ZOJkBwhLS9KMgBsgHGy8iKAAwvSPzsDA1zPAAFsAryEXAHBfICnpOnA6jwCwoJgJALCPM8Jx4WgPhwACQJwGgRHQgAROw5LwlAfEceIqJXCQqFUQahAQKCcCfnQIAkNhcB8VMoloGIPgBgRryHMAbhvB8HGAtAcAImRPx-HAIgkKxXjflAhLSeosnyYpnDKap8AaXkon2VwECHHpxGGcZSjCvgJnsZxFkIqR3yenZDlsc5rlghC37QisUDajFJDiDAqmnK84HDqQBKmv+zKARiirAZSRIBtScEMnATIsnU75ZV+P5TLVqLopitpDpBJCgRVE1BDBNIkHSHVdSASGKChHIyptMhAA)

```typescript
function bar<T extends BigTypeboxType[]>(param: SmallTypeboxType[]): T {
    return param; // this now errors
}
```
While not ideal, this forces TS to correctly evaluate the type. 

It would be worth submitting this issue to the TypeScript repository as they seemed fairly receptive to resolving this problem (and it was flagged as a TS bug, not a TypeBox one). At most, TypeBox can produce an accurate type (as reported by the language service, but statically asserting that type is very much the responsibility of the compiler).

Did you want to submit a new issue to the TS repo?

**Comment by sanderalvin** [comment]
Created a issue: https://github.com/microsoft/TypeScript/issues/56291
