### ISSUE TITLE
how to create a Partial type which only allows for a minimum number of properties from the type its selecting from

### ISSUE THREAD

**Issue by lifeiscontent** [sinclairzx81/typebox#637]
```ts
const UpdateBySlugBodySchema = Type.Partial(CreateBodySchema, {
  minProperties: 1
})
```

I had assumed this would only allow properties from from `CreateBodySchema` but that does not appear to be the case.

when using:

```ts
const UpdateBySlugBodySchema = Type.Partial(CreateBodySchema, {
  minProperties: 1,
  additionalProperties: false
})
```

this also doesn't seem to create an error in the scenario that a property is provided, but is not a part of `CreateBodySchema` do you have some suggestion on how I could achieve something like this in TypeBox?

**Comment by sinclairzx81** [comment]
@lifeiscontent Heya, this seems to work ok?

```typescript
import { Type } from '@sinclair/typebox'

import Ajv from 'ajv'

const T = Type.Partial(Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
}), {
  minProperties: 1,
  additionalProperties: false
})

const ajv = new Ajv()
console.log(ajv.validate(T, { }))            // false - expect 1 property
console.log(ajv.validate(T, { x: 1 }))       // true  - have 1 property
console.log(ajv.validate(T, { x: 1, y: 2 })) // true  - have 2 properties
console.log(ajv.validate(T, { w: 1 }))       // false - have 1 property, but is unknown
```

**Comment by lifeiscontent** [comment]
@sinclairzx81 it must be due to how fastify configures Ajv this is probably out of scope, but for some reason when using the typebox provider there, rather than having the handler validate the incoming type and returning a 400 error, it allows it through to the handler which is the expectation I had that doesn't seem to be working as expected.

**Comment by sinclairzx81** [comment]
@lifeiscontent Heya, all good.

> it must be due to how fastify configures Ajv this is probably out of scope, but for some reason when using the typebox provider there, rather than having the handler validate the incoming type and returning a 400 error, it allows it through to the handler which is the expectation I had that doesn't seem to be working as expected.

Hmmm, perhaps, although I would expect this schema to be ok. If you wanted to submit an issue to the Fastify repo, it can be helpful to just serialize the TB type with `console.log(UpdateBySlugBodySchema)` and show them the raw schema. 

I know Fastify has some fast json serialization [tech](https://github.com/fastify/fast-json-stringify) it derives from the schematics, and the additional constraints on the schema might be causing some issues (though it would only relate to sending data on responses). But in all, if you can repro the schema for the Fastify team, that should help resolve things. 

Alright to close up this issue?

**Comment by lifeiscontent** [comment]
@sinclairzx81 yeah, that's a good idea, thanks for your time. Really appreciate your responses and the way you conduct yourself in open source. It's been a pleasure chatting, take care :)

**Comment by lifeiscontent** [comment]
@sinclairzx81 I put an issue together here: https://github.com/fastify/fastify/issues/5104

their team is saying that they're seeing differences in the thing you put together, any ideas? Sorry, I realize this is out of scope, but given the breadth of knowledge you obviously have around JSON Schema, you might have some ideas.

**Comment by sinclairzx81** [comment]
@lifeiscontent Heya,

So, I've taken another quick look at this. Based on the configurations in Eomms reproduction code, there might be a bug with Ajv related to the `removeAdditional` and object constraint checking for `minProperties`.

Minimum reproduction below.

```typescript
import { Type } from '@sinclair/typebox'

import Ajv from 'ajv'

const T = Type.Partial(Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
}), {
  minProperties: 1,
  additionalProperties: false
})

const ajv = new Ajv({ 
  removeAdditional: true             // This setting will mutate the value being validated
                                     // and remove any non-specified properties. Try setting
                                     // this value to false.
})     

const value = { w: 4 }               // this is a value to validated. We expect this value to
                                     // be mutated as 'w' does not exist on the schema.

console.log('before', value)         // printing the value before validation
                                     //
                                     // 'value = { w: 4 } 

console.log(ajv.validate(T, value))  // validating and printing the result. we expect the value
                                     // to mutate on this line.
                                     //
                                     // true

console.log('after', value)          // this is the value after validation
                                     //
                                     // 'value = { }
                                     //
                                     // Note: The removeAdditional has discarded the 'w' property,
                                     // however the value is left in an invalid state as the schema
                                     // expected minProperties: 1. 
                                     
                                     // The expectation here is that the validate call should check 
                                     // the value post mutation, in which case, we would expect false
                                     // to be returned for validate(). This may be a bug.
```
This is very much outside the scope of TypeBox (as you say), but you're free to use the above reproduction if you want to submit an issue to the Ajv about it. I think there is a lot of room for interpretation here though, and the current functionality may be intended.

In terms of Fastify, you might be able to disable the Ajv `removeAdditional` flag via configuration if this validation behavior is not desirable. There's quite a bit of documentation on this available here https://fastify.dev/docs/latest/Reference/Validation-and-Serialization/#validation-and-serialization.

Again, hope this helps
S
