### ISSUE TITLE
Validating negative numbers for some template literals

### ISSUE THREAD

**Issue by eugeneduda** [sinclairzx81/typebox#638]
Hello

I've tried to make a template literal:

```ts
const percentage = Type.TemplateLiteral([Type.Number(), Type.Literal("%")]);

type Percentage = Static<typeof percentage>;

const value: Percentage = "-5%"   // no problem

TypeCompiler.Compile(percentage).Errors(value)   // Expected string to match '^(0|[1-9][0-9]*)%$'
```

I think either the check should succeed because there is no problem with the static type, or there should be a problem with `value: Percentage = "-5%"`

I tested with `0.31.18` version

**Comment by sinclairzx81** [comment]
@eugeneduda Hi,

It might be better to express this type with Type.RegExp(), however the following should work for positive and negative integer percentage values using template literals.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUKEixEcAGoEuAVwwVqteszacefQcLHj+ANxXrpUkhHYt4AOTgBeFMIB0yDOB4wMADLA-lAqABQMALQAJAjsqiAiGFDkAKQMAJRw2fz8cCRQGEQa-r7FLNTQcJBsxGYaBOwAJnDsGADmRMD11UQh9jZ2DnAACq7umF4+YH6BwcnhDLHxiclpmVKD9vAAquNokzvswHZhANqOOCMAulnZ9w+Pj7n5dCIcJdOzFRxwqsd2OBhQpgQosDDsfwtAgVRqoADyVAymy2w2Q+083jK-iCIXCZx2tyexJetkSHzgHBgEDgpRmxTgXHmoS4QJBYIhULgAHdggALOCFdoYcTI4niiWSqX3F5SaXyhUS0lDeDotwIOWKrVal7ZISYABcjAcUA47QYWE12utUt1vRg-SNDAAemFImEAAwAHzOAEZIgBOa5nD2B64AKgyqS9np9-qDIbDkdSGWiFqtNszTztZ1wqESEC4YQOGAAQhIPABpDhNDLXJ1Y+k45kqaRZ9vPPLkTb6jRqvCEYgkAA8vYgVBQAD4Oy9eyhxgADZYJJIpVILuBeuALmJxFdrdebWz2QsYDxcCDtMLKNRngDCfIwJAA1sWcFFfR70hk7ra8jAoHUVFT3PS9r0se9HxfN9GE-b9fz-WlAIwYCuDPC8rxvdQPAfJ9X2Qd8v0yBDEIAoDjxYECMPA28cKg-DCOInU8ioFRwVQ9CwKwyC8JgqJ4MVF5WK4cEgA)

```typescript
import { Type, Static } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

const N = Type.TemplateLiteral('-${number}%')   // create templates for positive and negative patterns
const P = Type.TemplateLiteral('${number}%')

const U = Type.Union([N, P])                    // combine templates in union (represented as anyOf)


const T = Type.TemplateLiteral([U])             // combine into template literal (represented with regex)
                                                // 
                                                // const T = {
                                                //   type: 'string',
                                                //   pattern: '^(-(0|[1-9][0-9]*)%|(0|[1-9][0-9]*)%)$',
                                                //   [Symbol(TypeBox.Kind)]: 'TemplateLiteral'
                                                // }

type T = Static<typeof T>                       // type T = `${number}%` | `-${number}%`

console.log(Value.Check(T, '-10%'))             // true
console.log(Value.Check(T, '10%'))              // true
console.log(Value.Check(T, '0%'))               // true
console.log(Value.Check(T, '0'))                // false
console.log(Value.Check(T, '-%'))               // false
```
Just note that the `${number}` terminal represents only integer numbers, and numbers without a leading `0`. For this reason a RegExp might be better to capture decimal values. That might look as follows.

```typescript
const Percentage = Type.RegExp(/^-?(0(\.\d+)?|[1-9]\d*(\.\d+)?)%$/)

console.log(Value.Check(Percentage, '-10%'))       // true
console.log(Value.Check(Percentage, '10.4%'))      // true
console.log(Value.Check(Percentage, '0.0%'))       // true
console.log(Value.Check(Percentage, '0%'))         // true
console.log(Value.Check(Percentage, '100.999%'))   // true
console.log(Value.Check(Percentage, '0100.999%'))  // false
```
For TS template literal inference, you can wrap the RegExp in a Unsafe and explicitly define the type.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUFKGY4ABSIwMUdizgBeOAAoABgBIE7AK4gRq8gFI9cAD5w9AWiOnzlm-ceuzFqOQA6H3d-TwdnYL9AyI89AEoZEgh1eAVVEgx2QgBzDC0UYQCAVXUCKgwAHiUYFTUWAD4dNEwAgCUMbIBRcTAdfgA9JwB+HQAGHQAdAImAEwBqOKG7AG0ARicATgBdWYAqSen5xbirA344hNlhRXTMnLztfCJSCrkMCCobqAysglz6oA)

```typescript
type Patterns = (`${number}%` | `-${number}%` | `${number}.${number}%` | `-${number}.${number}%`)

const Percentage = Type.Unsafe<Patterns>(Type.RegExp(/^-?(0(\.\d+)?|[1-9]\d*(\.\d+)?)%$/))

type Percentage = Static<typeof Percentage> // Infers as Patterns
```
Hope this helps
S

**Comment by eugeneduda** [comment]
Thank you
