### ISSUE TITLE
Union errors are too generic

### ISSUE THREAD

**Issue by blake-mealey** [sinclairzx81/typebox#640]
Hey, thanks for the great library.

We're using quite a few `Union`s and are finding that the type errors which it generates are hard to debug as they don't provide specific details.

When we have a large schema with a union and none of the union options match due to a schema diff deep in the object, we only get the error "Expected Union value" with the path to the start of the union.

Is there something we can do to get the cause of the union mismatch?

TypeBox Version: `0.31.15`

**Comment by sinclairzx81** [comment]
@blake-mealey Hi!

There are ways to generate more fine grained union errors, however error generation for unions tends to explode into many many errors as the reporter would report errors for the intended union variant (the one you're trying to match) as well as variants you might not be interested in matching (leading to a lot of noise).

Do you have any suggestions of what you would like to see reported for union errors? Also, would you be able to produce an example Type/Schema + some data to trip the error reporter. It's quite helpful to have a concrete example type to reason about, as well as some example data + the expected errors that should be reported for that data.

**Comment by blake-mealey** [comment]
That makes total sense. At the moment, I'd rather get everything rather that nothing since I have nothing to go on. However, I could see that changing when I have to parse through hundreds of errors.

Here are a few thoughts:

1. Could the compiler have a special case for unions with discriminator fields? We often use unions with a `type: Literal` field to distinguish between the union. Maybe if there was a special way to construct these, the compiler could use that info to improve errors by first checking the discriminator field and then only reporting errors for that union option.
2. Could the sub-errors reference which union schema they came from? This way, I could do the work of checking the discriminator field myself to see which union it should be matching, then filter the sub-errors based on that.

Here's a somewhat contrived example which illustrates the case:

```ts
const ObjectSchema = Type.Union([
  Type.Object({
    status: Type.Literal('active'),
    dependent: Type.String()
  }),
  Type.Object({
    status: Type.Literal('cancelled'),
    dependent: Type.Null()
  }),
])
```

In our case, `dependent` tends to be a very large schema with many potential failures.

**Comment by blake-mealey** [comment]
Potential discriminator union API:

```ts
const ObjectSchema = Type.DiscriminatedUnion("status", [
  Type.Object({
    status: Type.Literal('active'),
    dependent: Type.String()
  }),
  Type.Object({
    status: Type.Literal('cancelled'),
    dependent: Type.Null()
  }),
])
```

With this API, all of the options for the union would have to extend `TObject` and would need a unique `status` property.

**Comment by sinclairzx81** [comment]
@blake-mealey Hi,

I've recently reviewed this issue, but still not ready to move forward with additional generated errors at this time. However, I have added some new additional functionality to TypeBox's error reporting system, where additional information about the error is sent to it's error message generation function. You can read about the updates made at the following URL

https://github.com/sinclairzx81/typebox/blob/master/changelog/0.32.0.md#error-parameter

The following intercepts Union errors, allowing for custom error message generation.

```typescript
import { SetErrorFunction, DefaultErrorFunction } from '@sinclair/typebox/errors'
import { TypeGuard } from '@sinclair/typebox'


SetErrorFunction(({ schema, errorType, path, value }) => { // as destructured object
  if(TypeGuard.IsUnion(schema)) {
     // todo: use destructured params to generate more fine grained 
     // union error messages. Below just returns the default
     return 'Expected Union value'
  }
  
  // just return standard TB error
  return DefaultErrorFunction({ schema, errorType, path, value })
})
```
So, this will let you intercept and generate a more apt string message, but doesn't support the generation of more errors. I've made these updates to let users have a bit more control over what message gets generated, and there should be enough here to experiment with re-checking the union at this level to produce a better message. If there is some community work done to define a good algorithm for union error generation, I will consider updating TB to use that algorithm internally, but for now, going to keep things as they are until the works been done to define an "idealized" union algo.

Will close off this issue for now, but if you have any questions on the new error reporting functionality, feel free to reply on this thread.

All the best!
S
