### ISSUE TITLE
Value.Decode outputs a "never" type

### ISSUE THREAD

**Issue by wasd171** [sinclairzx81/typebox#641]
Hello! I have encountered an issue with `Value.Decode`:

```
const ExampleType = Type.Union(
	(['a', 'b'] as const).map(value => Type.Literal(value))
)
const example = Value.Decode(ExampleType, 'a')
```

^ this would give me a `typeof example = never` instead of `'a' | 'b'`
However, providing generic values outputs a correct type:

```
const ExampleType = Type.Union(
	(['a', 'b'] as const).map(value => Type.Literal(value))
)
const example = Value.Decode<typeof ExampleType, Static<typeof ExampleType>>(
	ExampleType,
	'a'
)
```

^ this gives me `typeof example = 'a' | 'b'`

`@sinclair/typebox: 0.31.18`
`typescript: ~5.2.2`

**Comment by sinclairzx81** [comment]
@wasd171 Hi,

The issue has to do with the definition of `ExampleType` where the parameter passed to `Type.Union` is a union array of literal strings (where it should be a tuple of TLiteral strings). TypeBox can only resolve the correct type when passing fixed length tuples. The following shows the actual and expected value of ExampleType.

```typescript
const ExampleType = Type.Union(
	(['a', 'b'] as const).map(value => Type.Literal(value)) 
)    // actual - TUnion<TLiteral<"a" | "b">[]> (incorrect)
     // expect - TUnion<[TLiteral<'a'>, TLiteral<'b'>]> (correct)
```
To make this type work correctly, you will need to implement the `.map()` logic in the type system (as TypeScript cannot infer types for `as const` when used with `.map()`). The following should achieve this.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUFUB2wE+OyAMsDBlAIYA2cAvnAGZQQhwDkAAgM7B8AYzo1gUAPQx0GAEYQAHlwBQoSLERwAavQCuGJq3adeA4aPFSZ8hRIBuejCuUYF6+NMxwAsjTDIICipaOgAeZDhXKnwAEz44PhgoQQBzAG0AXQA+OABeOGU4FEiFaLi4NMEWajgyErL4xOT8FJwAOg6qmoAleoxYxqTUzIzCorgAfgrySmp6ULIs9o7ff0DZkNDurIyC8bgALgrR5QkJFBk4GAg4ED8EoZb4wWu8QmJQtI62meD6bOUQmIiTgAGVHikCER8Hk4OE+gMHs10tkABQOOj6PhHL4dZAZACUeRyaEwbShxFRYwxWLadzA6McxIuZKCczojMxGAJBOURJo8WQFPwoVWATZm2QWSyykBwPgAFEFDRwHQMKSDPlwcjhai0lwaFwcFxZFxCeMznAgVAoBghDAjkL3iK0r92aEDVwligJfMTV6AXL8CCaZrtI42gARO0QGIYVFKlVgNUanD4XR0OhEy3W232o6huDAeKeuAAH24pqAA)

```typescript
export type MapToLiteral<T extends string[]> = 
  T extends [infer L extends string, ...infer R extends string[]]
    ? [TLiteral<L>, ...MapToLiteral<R>] 
    : []

// Type to map strings into TUnion<[...TLiteral]>
const StringUnion = <T extends string[]>(values: [...T]) => Type.Union(
  values.map(value => Type.Literal(value))
) as TUnion<MapToLiteral<T>>

const ExampleType = StringUnion(['a', 'b'])   // correct: TUnion<[TLiteral<'a'>, TLiteral<'b'>]>

const value = Value.Decode(ExampleType, null) // correct: value is 'a' | 'b'
```
I've added the `StringUnion` type above as you may want to reuse this type mapping again (it's very common to abstract common mappings into utility functions like this)

Hope this helps
S

**Comment by sinclairzx81** [comment]
@wasd171 Heya,

Will close off this issue for now as the above should resolve things. 

All the best!
S

**Comment by divmgl** [comment]
@sinclairzx81 snippets like these are [absolutely crucial](https://github.com/sinclairzx81/typebox/issues/641#issuecomment-1776554478).

Thoughts on potentially adding them to the library? Aside from the snippet in this comment, which I just added, I also have this smaller piece of code which helps with nullables:

```ts
export const Nullable = <T extends TSchema>(schema: T) => Union([schema, Null()])
```

**Comment by sinclairzx81** [comment]
> Thoughts on potentially adding them to the library? Aside from the snippet in this comment, which I just added, I also have this smaller piece of code which helps with nullables:

Unfortunately I can't. Nullable is neither a Json Schema or TypeScript type. In both systems, nullable is expressed as a union of `T | null`, so TypeBox just aligns to these same rules (and requires one to explicitly state the type as a union)

```typescript
type T = string | null // TS: union

const T = { anyOf: [{ type: 'string' }, { type: 'null' }] } // JS: union

const T = Type.Union([Type.String(), Type.Null()]) // TB: union
```
Of course, this can be wrapped in a user defined generic function (as above)

```typescript
type Nullable<T> = T | null

const Nullable<S> = (s: S) => ({ anyOf: [s, { type: 'null' }] })

const Nullable = <T extends TSchema>(schema: T) => Union([schema, Null()])
```
TypeBox prefers generic functions to express particular representations like this.

Hope this helps!
S

**Comment by truumahn** [comment]
Might not be the best place to comment this but I'd like to highlight the dangers of your suggested Nullable union @sinclairzx81 .

Consider using the `Nullable` generic wrapping a Union:

```ts
const MySchema = Type.Object({
  superUnionProp: Nullable(Type.Union([Type.String(), Type.Number()])),
})
```

it would unwrap to something like this:

```ts
const MySchema = Type.Object({
  superUnionProp: Type.Union([Type.Union([Type.String(), Type.Number()]), Type.Null()]),
})
```

Which adds unnecessary complexity to the union which should be flat and AFAIK unions directly in unions don't work. I've came up with this that might be a little less error prone:

```ts
import { type TSchema, Type } from "@sinclair/typebox";

export const NullishUnion = <T extends TSchema[]>(...schema: T) => {
  return Type.Optional(Type.Union([...schema, Type.Null()]));
};
```

TypeBox is an awesome library, I really enjoy working with it, I'd be really happy if there were more good examples and snippets available.
