### ISSUE TITLE
Email format validation issue

### ISSUE THREAD

**Issue by MariuzM** [sinclairzx81/typebox#654]
I'm using Hono framework to make validation, and i have noticed that it does not work, so i have raised an issue.

https://github.com/honojs/middleware/issues/238

But checking more I'm not 100% if this is the issue with hono

```ts
import { Type } from '@sinclair/typebox';
import { Value } from '@sinclair/typebox/value';
import { Hono } from 'hono';
import { validator } from 'hono/validator';

const app = new Hono();

const schema = Type.Object({
  email: Type.String({
    format: 'email',
    minLength: 1,
  }),
});

app.post(
  '/',
  validator('json', (c) => {
    console.log('🚀 ~ c:', c);
    console.log('🚀 ~ Is Valid?:', Value.Check(schema, c));
  }),
  (c) => {
    return c.text('Hello Hono!');
  }
);

export default app;

```

With `format: 'email',` i get `false` when i should be getting `true`. When i disable it then i get `true`

<img width="1007" alt="image" src="https://github.com/sinclairzx81/typebox/assets/36937039/d720c773-aa12-4580-afcd-6ce63cd91c1a">

**Comment by sinclairzx81** [comment]
@MariuzM Hi,

TypeBox does not automatically check for string formats (such as `uuid`, `email`, `ipv4`, etc), so you will need to configure the formats you want to use via [FormatRegistry](https://github.com/sinclairzx81/typebox#typeregistry-format). For example, the following would configure an `email` format. Just make sure you register the format prior to any calls to `.Check()`

```typescript
import { Type, FormatRegistry } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// Add this line somewhere before your calls to check. This will globally register the format.
FormatRegistry.Set('email', value => {
  return /^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i.test(value)
})

const T = Type.String({ format: 'email' })

const R1 = Value.Check(T, 'user@domain.com')
const R2 = Value.Check(T, 'not-an-email')

console.log(R1) // true
console.log(R2) // false
```
> TypeBox may include default string format checkers in future (which is pending RFC compliant format checkers). These would still need configuration (as above). 

If you need some common formats, take a look at https://github.com/sinclairzx81/typebox/tree/master/examples/formats which includes ports of the [ajv-format](https://www.npmjs.com/package/ajv-formats) library for various RFC compatible formats. The email regular expression in the example above is from the formats examples (which is a heavily vetted email expression and should be safe to use)

Hope this helps
S

**Comment by MariuzM** [comment]
Thank you this worked, i switched from Elysia to Hono looks like Elysia had this already built in
