### ISSUE TITLE
How to ref a schema that was not defined by typebox?

### ISSUE THREAD

**Issue by OmarAlkadri** [sinclairzx81/typebox#659]
How can I create a userID whose reference is the same as users

i use feathersjs V5 and typeBox

export const usersSchema = Type.Object(
  {
    _id: ObjectIdSchema(),
    email: Type.String(),
    date: Type.String({ format: 'date' }),
    password: Type.Optional(Type.String()),
    userID: ObjectIdSchema(),

    user: Type.Ref(usersSchema),
  },
  { $id: 'Users', additionalProperties: false }
)
Block-scoped variable 'usersSchema' used before its declaration.ts(2448)
users.schema.ts(13, 14): 'usersSchema' is declared here.

**Comment by sinclairzx81** [comment]
@OmarAlkadri Hi,

I think Feathers may be on an older version of TypeBox, but the following is possible using current versions.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAKAG0I1CvABKGCpDFYAvCk4A6APJcAVhlowAFAgFw4AVwoYoALiWZlUvAB4OmCHjgBVM1AB8ukh-MkAJRwrKwmZnBcGHjQWAAm0TQYcQLYgUIiYvD+UHCKaDbqWjr6cNSMIBhWBRjKAMowUDQA5rrB2AA0iHAAJMBxVn6eJDjpAkA)

```typescript
const Response = Type.Object({
  user: Type.Ref<typeof User>('User') // use before defined
})

const User = Type.Object({ name: Type.String() }, { $id: 'User' })
```
If running on older versions, you can achieve a similar result using Type.Unsafe

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUFJIR2LeACUMLSAoxwAvCmEA6APIiAVhhIwAFAilw4AVxYYoALl2Y9AVQUEqGADz4RKR+QpgQVHAejlAAfDFWcAAkUBhUrgxRTgwUAJRw-Pz2jnAiqdCaACapHBgVUuQ5MnIK8JlQ2m4YhiZmlkjsBCAYrmju+FAcAOYWeeQ4SInAFelt2Q0yQA)

```typescript
const Response = Type.Object({
  user: Type.Unsafe<Static<typeof User>>({ $ref: 'User' }) // use before defined
})

const User = Type.Object({ name: Type.String() }, { $id: 'User' })
```
This should get around the "Block-scoped variable 'usersSchema' used before its declaration.ts(2448)" error.

Hope this helps
S

**Comment by sinclairzx81** [comment]
@OmarAlkadri Hi, 

Going to close off this issue for now. But if you have any follow up questions, feel free to reply on this thread.

All the best!
S
