### ISSUE TITLE
question: composition of "primitive" schemas?

### ISSUE THREAD

**Issue by boneskull** [sinclairzx81/typebox#660]
Hello maintainer,

I'm looking at migrating from Zod, and I'm trying to determine the canonical way to do something like this:

```ts
const NonEmptyString = Type.String({minLength: 1, description: 'A non-empty string'});

const MyObj = Type.Object({
  someKey: NonEmptyString // <-- I want to set a custom description here. context!
});
```

Using `Type.Intersect([NonEmptyString], {description: '...'})` seems like a hack; is `Type.Ref()` the preferred way to do this?

My use-case is this: I intend to provide a JSON schema (e.g., a config file), but _also_ want to use the same system to do runtime validation of user-provided code (think: plugins).  While Zod works well enough for this, it's slowing VSCode to a crawl, which is why I'm here.  😄   

Thanks!

**Comment by sinclairzx81** [comment]
@boneskull Hi,

The general recommended way to approach this would be to make the constraint type `NonEmptyString` reusable by turning it into a function. This allows you to reuse the predefined constraint `minLength` and is inline with how generic type patterns work in TypeBox also.

---

### NonEmptyString

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUZTAB2A5gPJgzAREDOcAvnAGZQQhwDkAArcQMYAbAIbAoAehjoMAIwgAPTgCgl-GrXgA5GgFFwU-IVJwAvHAAUEStToAuQ8XLX1pxAwCUpgHwppAOgdScyQ-UKsqdRwQYgAZDFIYAAtbOABGRncVNTp4AFlUQ1dtIj1KAoJHYLgAEwxafkJnIhTOAEE4IhoAWgx9VDgNIxJODIBuLPU81DIZACtXNEw-GdmMfhhgpTgB9gwAaQxUFOLSgwqgpFr6xojmrlbOpIwoDu7esoHz4YylD1GgA)

```typescript
import { Type, StringOptions } from '@sinclair/typebox'

const NonEmptyString = (options:StringOptions = {}) => Type.String({ ...options, minLength: 1 })

const MyStr = NonEmptyString({ description: 'A non-empty string' });

const MyObj = Type.Object({
  someKey: NonEmptyString({ description: 'Another non-empty string' })
});
```

---

### Clone

Another approach might be to clone the type. This can be achieved using something like the following...

```typescript
const Clone = <T extends TSchema>(schema: T, options: SchemaOptions = {}): T => ({ ...schema, ...options })
```

TypeBox includes a built in clone utility that ensures the schematics are deeply cloned (which is recommended to avoid JS shared referencing and unintended mutation of schematics)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUGUDGAFhiAIY4HFkDyYMwEAdgM45qYDCANkxnAL5wAZlAgg4AcgACzYI3xdSwKAHoY6DACMIADwkAoffibN43XnAC8cADzI4GHTAyMAJszxESpAHwAKZi8yAC4UHAg6BhZQym9aehMrRH4ASlD7Sx8UDXNGDAA6dgwAoPI4CISWFMNjFngAOSYAUXB1XBgoOQBzJKL89s7GLr8kEDkAGRcumEJQgEYcVwxAzsimUIkAQThGJgBaEjpUOFNBrokBaqMTeABZVGpNACtejXzHp4x8GBH9OBOxBgANIYVChXLFRqMFpHAbdHBIJYrYBrRgbTa7GYYKA7faHdQnDrdC6pfSpADcQA)

```typescript
import { Type, TSchema, SchemaOptions, TypeClone } from '@sinclair/typebox'

const Clone = <T extends TSchema>(schema: T, options: SchemaOptions = {}): T => TypeClone.Type(schema, options)

const NonEmptyString = Type.String({ minLength: 1, description: 'A non-empty string' })

const MyObj = Type.Object({
  someKey: Clone(NonEmptyString, { description: 'Another non-empty string' })
});
```

---

### Summary 

The recommended approach would be the first option as that mitigates shared JS referencing without the need to clone, but cloning the type is also perfectly fine (even with shared referencing so long as you treat types as immutable)

Hope this helps
S

**Comment by boneskull** [comment]
Thanks!
