### ISSUE TITLE
Date timezone 

### ISSUE THREAD

**Issue by MutedOne** [sinclairzx81/typebox#662]
Date must be auto format to system time zone not zulu

**Comment by sinclairzx81** [comment]
@MutedOne Hi,

TypeBox doesn't have a specific format for Date (although iso8601 is common under the JSON Schema specification),

TypeBox does however have the numeric Date constraints `exclusiveMaximumTimestamp`, `exclusiveMinimumTimestamp`, `maximumTimestamp`, and `minimumTimestamp` which are based UTC (specifically January 1, 1970, UTC+0) (so not GMT/Zulu). This numeric timestamp is given by the JavaScript `Date.getTime()` function and will return a common timestamp offset irrespective of time zone.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime

Implementations are expected to transform any non-system Dates into UTC+0 offsets to make use of these constraints (including transforming other time coordinate systems). Note also that these constraints are non-standard (as is the Date type)

Hope this helps
S

**Comment by sinclairzx81** [comment]
Might close off this issue for now. If you have any follow up questions, please feel free to reply on this thread.

All the best!
S
