### ISSUE TITLE
Type.Recursive doesn't work

### ISSUE THREAD

**Issue by YaoKaiLun** [sinclairzx81/typebox#663]
I use typebox to check [slate.js](https://github.com/ianstormtaylor/slatez) model, like below:

```
import { Descendant } from 'slate';

const textSchema = Type.Object({
  text: Type.String(),
});

const paragraphSchema = Type.Recursive(() => Type.Object({
  type: Type.Literal('paragraph'),
  children: descendantSchema,
}));

const headingSchema = Type.Recursive(() => Type.Object({
  type: Type.Literal('heading'),
  children: descendantSchema,
}));

const elementSchema = Type.Union([
  paragraphSchema,
  headingSchema,
]);

const descendantSchema = Type.Union([elementSchema, textSchema]);

const contentSchema = Type.Array(descendantSchema);

export function checkContentSchemaByTypebox(content: Descendant[]) {
  const C = TypeCompiler.Compile(contentSchema);
  const result = C.Check(content);
  if (!result) {
    const error = [...C.Errors(content)];
    if (error) {
      throw error;
    }
  }
}

checkContentSchemaByTypebox([
  {
    "type":"paragraph",
    "children":[
       {
          "text":"Hello World!"
       }
    ],
    "id":"uVSLh3PYr1xB"
 },
]);
```
But it doesn't work, the error detail:
![image](https://github.com/sinclairzx81/typebox/assets/11460856/6d16707b-6921-4c8a-95b3-03586a7599a8)

And i tried use Type.Recursive、Type.Recursive、Type.Unsafe, but none of them work

```
const paragraphSchema = Type.Recursive(() => Type.Object({
  type: Type.Literal('paragraph'),
  children: Type.Array(descendantSchema),
}));
```

```
const paragraphSchema = Type.Object({
  type: Type.Literal('paragraph'),
  children: Type.Array(Type.Ref<typeof descendantSchema>('DescendantSchema')),
});

const descendantSchema = Type.Union([elementSchema, textSchema], { $id: 'DescendantSchema' });
```

```
const paragraphSchema = Type.Object({
  type: Type.Literal('paragraph'),
  children: Type.Array(Type.Unsafe<Static<typeof descendantSchema>>({ $ref: 'DescendantSchema' })),
});

const descendantSchema = Type.Union([elementSchema, textSchema], { $id: 'DescendantSchema' });
```

Does Typebox has the function like [zod's lazy function](https://github.com/colinhacks/zod#recursive-types)?
```
const paragraphSchema: z.ZodType<IParagraph> = z.object({
  type: z.literal('paragraph'),
  children: z.lazy(() => descendantSchema.array()),
});
```

**Comment by sinclairzx81** [comment]
@YaoKaiLun Hi,

You can implement this type in the following way. Note that `elementSchema` is the only recursive type (it's actually a union of all possible types) and the interior `This` type is passed is passed to each variant as a generic argument.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYGELmAGwyjgF84AzKXOAcgAEBnYAOwGN8BDYKAehnQwAjCAA8erXGAJEaAKFCRYiFAIA0yAMqsAFhhAdSFKiFqMW7Lr36ZhIubJ484AWldv3Hz1+8-ffh04AooQgGMwwDAEufjGxcfGyEswM8DAYIjBauvpwALwqmAB0APKCAFYYrDAAFAiycHBpGQBcBRiFGjBQLADm1QCUsiSDSSlwYBxQHD1TYNpZegb5ADzIcOlpzAAmDCgL+gB81Qw6i63I-XkHbSXllTV1DdYY5wKFADLAaVP41TQTUxmHDmNH6qnqcB0BC2UDCryKAEEoFNUMdTvpLkMRhBkvBdBwtr19ks4Kt1hkwjs9uiOEcTtkOOdLrlrmgiqUKlVahDnvD2p9vhxfjR8YTmD1QeCGlD8DC4TckSi0QzBsNEjixhgQmFMjS8jcAEqVACuUCYADcMNVkNpgLsWTcAKrMYA46oAbTgjjgztdzDgAGo4EbWKaLRgeRtiVLxpNprN5jTrbaGGCIaKiUmbXbBgBdfqDdW4yE4za6hn6tntRUcVFavQ64mF73xVtt9tRZAYFJRdt9-s+WRFsanVgAa0rAhweEIUEK06khGqSTLTaHo3gBv1o7H890449EKQEKeAlaIowBN6NFUcBPkNtsthzFa7vvDWPDS-X95tAz4pvO9v2-GU5RfOA32A4CkCaGBz10fB8AgGhSBjKCP0aDZzwAd2gWUUJId8v1zIDgMI78SIhQj83XDUIEIQokL6A1+iAA)

```typescript
import { TypeCompiler } from '@sinclair/typebox/compiler'
import { Type,TSchema } from '@sinclair/typebox'

// ------------------------------------------------------------------
// Elements
// ------------------------------------------------------------------
const textSchema = Type.Object({
  text: Type.String()
})
const paragraphSchema = <T extends TSchema>(schema: T) => Type.Object({
  type: Type.Literal('paragraph'),
  children: Type.Array(schema) 
})
const headingSchema = <T extends TSchema>(schema: T) => Type.Object({
  type: Type.Literal('heading'),
  children: Type.Array(schema)
})
const elementSchema = Type.Recursive(This => Type.Union([ // Union + Recursive
  textSchema,
  paragraphSchema(This),
  headingSchema(This)
]))

const contentSchema = Type.Array(elementSchema)

// ------------------------------------------------------------------
// Test
// ------------------------------------------------------------------

const check = TypeCompiler.Compile(contentSchema)

const R = check.Check([
  { 
    type: 'heading', 
    children: [
      { 
        type: 'heading', 
        children: [
          { text: 'hello' },
          { text: 'world' }
        ] 
      }
    ] 
  }
])

console.log(R)
```
> Does Typebox has the function like [zod's lazy function](https://github.com/colinhacks/zod#recursive-types)?

TypeBox only supports immediate initialization of types, either via Recursive or Ref.


Hope this helps
S

**Comment by sinclairzx81** [comment]
@YaoKaiLun Hi,

Might close off this issue for now as the above is generally how you would approach recursive union types under TypeBox. Just note in the example given, I've updated the `children` property to be an array (I'm not familiar with `slate.js` but assume this property should be an array). I also moved the `textSchema` into the `elementSchema` union making `descendantSchema` unnecessary.

If you have any follow up questions, feel free to reply on this thread.
All the best
S

**Comment by YaoKaiLun** [comment]
@sinclairzx81 That's awesome! It solved my problem perfectly.  Thanks you so much! I had previously used  [myzod](https://github.com/davidmdm/myzod), which performed better than zod, but it still wasn't enough. However, typebox has the ultimate performance.
