### ISSUE TITLE
Auto remove duplicated schemas in Type.Union?

### ISSUE THREAD

**Issue by ExpandOcean** [sinclairzx81/typebox#668]
Hi, is it better to auto remove duplicated schemas in Type.Union like what Typescript does? 

```ts
type s = { foo: string } | { foo: string };
// {foo:string}

const schemaS = Type.Union([
  Type.Object({ foo: Type.String() }),
  Type.Object({ foo: Type.String() }),
]);
// union of two {foo:string}

```
Thanks!

**Comment by sinclairzx81** [comment]
@ExpandOcean Hi,

I would actually like to do this, however this functionality probably won't land for a while. There are some performance concerns around implementing this functionality as default as performing a `distinct` operation on types can be an expensive operation from a type system standpoint. However de-duplication of variadic types is being considered for an upcoming feature that will aim to support TS type evaluation on TB types (which would also include union and intersect normalization). This functionality is still a fair way off (and may require significant changes to TB's type infrastructure to achieve)

With this said, you can perform this operation externally using a custom type. Below is a draft static and runtime implementation of this functionality where the Distinct function will de-duplicate types. The only caveat is you will need to do this "outside" of TypeBox. 

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUGUDGAFhiAIY5qYCiAHjBgHYAmAzhehrfcywEoYsArgBt4AXzgAzKBBBwA5AAEWwBvmGlgUAPQwOAIwg15AKBPbtcALQ3bd+w8dPnL1+csARYCxir8MAC44XBhSX3x3a1domNi4kwwaSFg4PUw4Lx8-GABJNWFBJgEAHmQ4RO5WPCISUgBtAF0cAGFyukYq5AJiMgA+OABeOBM4FDbKljg61UkMKDgAGXGOya6ashwAOm2ZubheZZ5qnvqGhpHRuAB+OFaKlcXhy8ubmChBDCfnuCDM3zVcvlCiVeC1+hdRkFJKRhCwMGZEsl4GlPn9sqVDp1urVGjgAIL4fCY1bYsiNQZTBr9IYXMr3I7TBizeZLelY9bkODbTa7eYHNkkjmNBpfUY3NEAvLqYEsYoE-A4Bb9AVSGFw0UvDLef7+Yqgqbc+WKqkQy6-bXo-V1Q2Ek3PILyyJxZ0u12RCX+IK8QQMXwgeEWKKu4MhxwJJLQeCSH3+YAQBharKSoFFFgAChYHJYQTWJ1xcHwpGYwCYYQwOdJpAAlIgLlAMDBBFAE5mTixNpJVEwMxzBv1KJx2jxNlwVmnC8XS-QcK3ajWBguUBxRzx+EJRJtkO8MDWAISLn1FTsMDBMExicNIqQx3zxxM6mAYlW5nFUnttoLW7bIBpV81J3VkH6BA6wbJsWyzTZ6yYQR8AwNM01IQkcAnJgSzLedgNNetG2bOBdw9QFpVTRDkILIs0KnHdTTFA1tiQhVyMnMtzm+H46M2BjWLgMQcHJUhBTzX84AE+90SA88zEDUMZNkyIAFUWFIABzANLFkjTgzMfB4x8MYhgHTZ5IYOMGDTQi0zqOBA0ICAADc9jKWkOE2AA5QQQH0OY0yrLBnMwNyPK8qAfL80ZDPczzvN8-yME2EIoFUZTQti+K3iSlLwpchKMpirKAoAIQgCBhAwItMqXQritK8q8squKipKsqzKrExf1akwdIYFgms2YQIGS5AqyAA)

```typescript
import { Type, TSchema, TypeExtends, TypeExtendsResult } from '@sinclair/typebox'

// ------------------------------------------------------------------
// Distinct: Static
// ------------------------------------------------------------------
export type DistinctIncludes<T extends TSchema[], C extends TSchema> = 
  T extends [infer L extends TSchema, ...infer R extends TSchema[]]
    ? C extends L 
      ? true 
      : DistinctIncludes<R, C> 
    : false

export type Distinct<T extends TSchema[], Acc extends TSchema[] = []> = 
  T extends [infer L extends TSchema, ...infer R extends TSchema[]] 
    ? DistinctIncludes<Acc, L> extends false 
      ? Distinct<R, [...Acc, L]>
      : Distinct<R, [...Acc]>
    : Acc
// ------------------------------------------------------------------
// Distinct: Runtime
// ------------------------------------------------------------------
export function DistinctIncludes(schemas: TSchema[], candidate: TSchema) {
  return schemas.find(schema => TypeExtends.Extends(candidate, schema) === TypeExtendsResult.True) !== undefined
}
export function Distinct<T extends TSchema[]>(schemas: [...T]): Distinct<T> {
  return schemas.reduce((acc, candidate) => {
    return !DistinctIncludes(acc, candidate)
      ? [...acc, candidate]
      : [...acc]
  }, [] as TSchema[]) as Distinct<T>
}

// ------------------------------------------------------------------
// Usage
// ------------------------------------------------------------------

const T = Type.Union(Distinct([ // hover T 
  Type.Number(),
  Type.Number(),
  Type.Number(),
  Type.String(),
  Type.String(),
  Type.String(),
  Type.Boolean(),
  Type.Boolean(),
  Type.Boolean()
]))

console.log(T)
``` 
For now, the default behavior is to just to allow duplicated schematics until some of the other infrastructure is able to support optimal de-duplication + type evaluation. 

Hope this helps
S

**Comment by sinclairzx81** [comment]
Will close off this issue for now, but will mark as `future` and pick up this again at some point down the road.

Cheers
S
