### ISSUE TITLE
Get method requesting 'body' 

### ISSUE THREAD

**Issue by MutedOne** [sinclairzx81/typebox#678]
![image-2.png](https://github.com/sinclairzx81/typebox/assets/47779436/fbd0e0f1-bc52-4889-843f-36bb46f8cbe6)

In elysiajs requesting 'body' even get method

**Comment by sinclairzx81** [comment]
@MutedOne Hi,

This is probably more a question for the Elysia repository. TypeBox has no notions of `body` parameters (or GET http verbs). Those things would reside with Elysia's routing setup.

Was there a specific question you had about TypeBox?

**Comment by MutedOne** [comment]
Okay. Thanks
