### ISSUE TITLE
I can't find a way to translate json-schema to typebox format

### ISSUE THREAD

**Issue by RumyantsevOleg** [sinclairzx81/typebox#682]
I use TypeBox in my project and I like everything. But I also have many places where the validation scheme is autogenerated. And quite often I want to use JSON schema format together with typeBox. For example to use Type.Partial or other Typebox features. But I can't do that because it won't work for the schema described not through the builder. Can you tell me if there is an option to convert JSON-schema to typebox format?

**Comment by sinclairzx81** [comment]
@RumyantsevOleg Hi,

You can try https://github.com/xddq/schema2typebox which generates TypeBox types from Json Schema via a command line interface. This is the current best option for refined schema translation that matches the TypeBox subset.

Does this help?

**Comment by RumyantsevOleg** [comment]
@sinclairzx81 Yes, that helped, thank you. Just wanted to know how reliable it is to use this library in production? Because as far as I can see it is not very popular. Thanks

**Comment by RumyantsevOleg** [comment]
Plus my JSON schemas are generated in memory, they don't represent any files

**Comment by sinclairzx81** [comment]
@RumyantsevOleg Hiya,

There are ways to map Json Schema to TypeBox types, but you will need to write this mapping logic yourself. The following is a starter script on how you might begin to approach this.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZRgQxsAxnAvnAMyghDgHIABAZ2ADssAbNYKAehgE8wBTAIwgAeZAFDCsEWlXgAVOAF44AMWIgAFAmFw4nHgC5yEXgCtuWGGQA0muGGI9YwblX0atWgS+1du+srQCuILzcUGR4Vm5wHJ46PuRSUHQA5mG4EW4AXjHevvwQDNxotKnpWgDu2XrkAQwMqda4wrgAlKKxcLIKqBjYADyxEAQdAHyirKxwALTTM7Nz8wuLS8vLwuNwAFJUEihYABbcIGhwwx3eAEKCaxMrt3f3D6KgkLCIHQDyxqYwFh2oibQkr9pAA5QLBKDAy75Qq0YFg2rAgCCtA4vwAogA3NAMfwYbh4QgqcjUOiMZhsWL8IRjCZYfxSEhwJLcWghbBeHjCAAmpiYUAJBH89EwO2UJF64kkMjg3AEMFZ3Kom2Q+0OaGGqioaqO+mkzX04pAvWko2Ecpe8DoCqgBDQWAJG1VByOiCa5oElrg1pCdodm0+JjMsvliuVTp1x1cnLiZEMQfM1lsEHsmCc+gASqZoNzegAFOwhTgAaW4aJVkdGjQt0CttBtfsd-2SIYVtCVFZdUessV8CWSImrntr3vrvvtjrBQRCrbDnfVbq0veq4JCg49Xp9tonm2hBSKs-b4edC+jy7IeX3xXdNdeW8bmwRDEPHYjXcXMd8NTq7vaRoLKZFo4VAmi+ypZuIUC5gBqYcKW5ZvuqwynAoWI4niCq9NGADaxajnAADWZaDB0AC6hoqCauGkVWox-pRshym2r4nkcKHWIxoZHgGXzBgA-B8vEwL0-6Fg4ThUWQyapsBZA0acugcWBKowACSRwAJ0jNoCcCKVonHMeGe6whpHTGQeekdMpGxThCpmgquUC6UpTFzjZ-i1PZT7OfpKIcMIQA)

```typescript
import { Static } from '@sinclair/typebox'

const T = From({
  type: 'object',
  properties: {
    x: { type: 'number' },
    y: { type: 'string' },
    z: { type: 'boolean' },
    w: { type: 'null' }
  }
})

type T = Static<typeof T>

// -----------------------------------------------------------------
// Json Schema > TypeBox
// -----------------------------------------------------------------

import { TObject, TString, TNumber, TBoolean, TNull, TAny, Evaluate } from '@sinclair/typebox'

// custom generic type
declare function From<const T extends JSchema>(schema: T): From<T>

export interface JSchema {
}
export interface JObject extends JSchema {
  type: 'object'
  properties: Record<PropertyKey, JSchema>
}
export interface JString extends JSchema {
  type: 'string'
}
export interface JNumber extends JSchema {
  type: 'number'
}
export interface JBoolean extends JSchema {
  type: 'boolean'
}
export interface JNull extends JSchema {
  type: 'null'
}
type FromProperties<T extends Record<PropertyKey, JSchema>> = Evaluate<{
  [K in keyof T]: From<T[K]>
}>
type From<T extends JSchema> =
  T extends JObject ? TObject<FromProperties<T['properties']>> :
  T extends JString ? TString :
  T extends JBoolean ? TBoolean :
  T extends JNumber ? TNumber :
  T extends JNull ? TNull :
  TAny
```
Providing such a mapping is currently outside the scope of TypeBox, but may be explored in later revisions, possible when TypeBox drops support for TS 4.0.

Will close off this issue for now
All the best
S
