### ISSUE TITLE
Property 'Mapped' does not exist on type 'JavaScriptTypeBuilder'

### ISSUE THREAD

**Issue by theurgi** [sinclairzx81/typebox#687]
When using TypeBox-Workbench to convert TS types to TypeBox schemas, a `Type.Mapped` declaration is emitted. When trying to use the generated code in a project with `typebox 0.31.28`, I get: 

> Property 'Mapped' does not exist on type 'JavaScriptTypeBuilder'.

Upon further investigation, TypeBox-Workbench appears to be using `typebox 0.32.0-dev-16`, so I installed that. I still don't seem to have access to the `Mapped` method on the `Type` class (`JavaScriptTypeBuilder`), but can access it directly via `import { Mapped } from '@sinclair/typebox'`.

Given that `Mapped` doesn't appear to be documented, I assume I've stumbled upon an in-development feature?

Perhaps you're aware of this, but if not, just a heads-up.

Thanks for all your hard work. 🙏

**Comment by sinclairzx81** [comment]
@theurgi Hi,

Ah, good spotting :) the Mapped type is a new feature being developed for Revision 0.32.0. I usually integrate new features on the Workbench early to communicate and test functionality (specifically TypeScript alignment). If you're interested you can view the provisional changelog for 0.32.0 below.

https://github.com/sinclairzx81/typebox/blob/index/changelog/0.32.0.md

I've been publishing `dev` revisions out for integrators, you can install the latest using the following.

```bash
$ npm install @sinclair/typebox@0.32.0-dev-17 # or later

# or just

$ npm install @sinclair/typebox@dev
```
And track the latest published dev revisions on NPM [here](https://www.npmjs.com/package/@sinclair/typebox?activeTab=versions)

---

### Timeframe for Release

I'm trying to get this revision out before the end of the year (within the next few weeks), If you have a read over the changelog, there's some VERY big updates in this revision. I'm currently in the process of finalizing and testing the updates against various toolchains, which has been somewhat time consuming.

I have been meaning to reach out to the community to help test this revision, so if you did want to install and test it, and provide feedback, that would be very helpful.

Hope this brings some insights
Cheers
S

**Comment by theurgi** [comment]
Awesome, exciting update! Great work! I will certainly work with `0.32` and report any issues I may encounter.
