### ISSUE TITLE
Should default values be applied when using Decode() or Check()?

### ISSUE THREAD

**Issue by kaisellgren** [sinclairzx81/typebox#691]
I noticed that defining default values:

```typescript
const A = Type.Object({
  count: Type.Integer({ default: 0 }),
  offset: Type.Integer({ default: 0 }),
  totalCount: Type.Optional(Type.Integer()),
})
```

will not work with either Decode() or Check():

```typescript
Value.Check(A, {}) // false ?
Value.Decode(A, {}) // throws 'Unable to decode due to invalid value'?
```

The only way I can think to make this to work is by first running the data through `Value.Cast()` then passing that down to those functions, but that has its own problems. For example, `Cast()` will turn otherwise invalid input into valid:

```typescript
Value.Cast(Type.Object({ x: Type.String() }), { heh: 5 }) // { x: '' }
```

Is this behavior intended or am I misunderstanding the library? In Zod, for example, using `parse()` will apply the default values for anything that's missing.

Great job on the library by the way.

**Comment by kaisellgren** [comment]
So it looks like this is intended behavior as per JSON Schema spec. 

Can you recommend a library (beyond Zod, which suffers from horrible performance) that is able to parse with default values? We simply have too much reliance on default values to be able to anything otherwise.

**Comment by sinclairzx81** [comment]
@kaisellgren Hi,

TypeBox actually has some new functionality arriving in the next revision (0.32.0) which will support generating values from `default` annotated types. To use, you will need to install the `dev` version (which is scheduled to release in about a weeks time)

```bash
npm install @sinclair/typebox@0.32.0-dev-28 # latest dev revision
```
The following is possible on 0.32.0
```typescript
import { Type, TSchema, StaticDecode } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// Custom Decode Pipeline
function Decode<T extends TSchema, R = StaticDecode<T>>(schema: T, value: unknown): R {
  const defaulted = Value.Default(schema, value)      // generate values for 'default' annotated types
  const converted = Value.Convert(schema, defaulted)  // coerce values if reasonable conversions are possible
  const cleaned = Value.Clean(schema, converted)      // similar to .strict(), will discard unknown properties
  return Value.Decode(schema, cleaned)                // run transform decoders (if available)
}

const A = Type.Object({
  count: Type.Integer({ default: 0 }),
  offset: Type.Integer({ default: 0 }),
  totalCount: Type.Optional(Type.Integer()),
})

Decode(A, {}) // { count: 0, offset: 0 }
```
> Can you recommend a library (beyond Zod, which suffers from horrible performance) that is able to parse with default values? We simply have too much reliance on default values to be able to anything otherwise.

You can also use Ajv here which supports default value generation, value coercion and clean (referred to as `removeAdditional` in configurations). Ajv is widely used and is equally recommended to TypeBox's own value checking infrastructure. It's also a lot faster than Zod. Some relevant links below to get Ajv setup.

https://moltar.github.io/typescript-runtime-type-benchmarks/ - Performance

https://github.com/sinclairzx81/typebox?tab=readme-ov-file#typecheck-ajv - Ajv Setup
https://ajv.js.org/options.html#usedefaults - same a Value.Default
https://ajv.js.org/options.html#coercetypes - same as Value.Convert
https://ajv.js.org/options.html#removeadditional - same as Value.Clean

Hope this helps
S

**Comment by kaisellgren** [comment]
This sounds promising.

I will try the next version once it's out and report back!

Thanks.

**Comment by sinclairzx81** [comment]
@kaisellgren Hi,

Revision 0.32.0 has just been published so this new functionality is now considered "stable". Will close off this issue for now but feel free to reply on this thread if you have any questions about the new functionality provided on this revision.

All the best!
S
