### ISSUE TITLE
Wrong return type from Composite (trying to do partial by key function)

### ISSUE THREAD

**Issue by tzelon-cypator** [sinclairzx81/typebox#692]
Hey,
First I want to thank you on a great library. 

I'm trying to create an helper function for PartialByKey, given an object and keys return the object with the keys as optional. 

This is my function, the return type is all keys are optionals. 
```js
function Optional<T extends TObject>(schema: T, keys: (keyof Static<T, []>)[]) {
  return Type.Composite([Type.Partial(Type.Pick(schema, keys)), Type.Omit(schema, keys)]);
}
```
![image](https://github.com/sinclairzx81/typebox/assets/101450733/7a2952e9-8cb3-467f-a67f-ba34c6e37cf2)

but when I try the same composite on an hard coded object, something like this, I get what I want. 
```js
const CreateAssetSchema = Type.Composite([
  Type.Partial(Type.Pick(AssetSchema, ["description", "is_active"])),
  Type.Omit(AssetSchema, ["description", "is_active"]),
]);
```
![image](https://github.com/sinclairzx81/typebox/assets/101450733/ccf56087-57b5-4189-b3ef-965d622f38a0)

the object 
```js
const AssetSchema = Type.Object({
  id: Type.Number(),
  name: Type.String(),
  internal_name: Type.String(),
  is_active: Type.Boolean(),
  version: Type.Number(),
  description: Type.Optional(Type.String()),
});

```

**Comment by sinclairzx81** [comment]
@tzelon-cypator Hi,

You can try the following which should work ok on version 0.31.0. This approach involves replicating the return logic by building out the TComposite return type (as you would for your runtime logic). I've named this mapping `PartialKeys` in the example below.

### TypeBox 0.31.0

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUHkBGAVhgMYw7IDCE4EAzsDNigArAkDWFuIjFLAQ1jABAGxwBBOnQyw4AXzgAzKDTgByAAIMAdiVEDgUAPQx0GfBAAe6gFC2zmVkJgjRAaQyo6AHmRwMKyYdABM6PCJScjh3AKCMUPCOLwglFABtdTBVTGEMOnUAXQA+OABeFGpaBiYfdNs4RrxeGD9JaVlW9xxk1FSMrJzO4Hyi4uKsBqbkQWExPzZONrgpGVgfbrhe-uRM7Ihc11GS8dsS2yUAVz1XCB04WdcxT28-OOCwiOIyHFjAj-CAAptmldoMDsNjgBKdIlQF0EgACwwIAEAC4UD0vHQMekAHQE9yFKEYmYuNwvXzIX7pHSXED4WQlRBTOBQDAwS5Qe5oTB4qqQGoYQH1JqNXkYPE8RjwpEogRY7xwAThHQYABusihkzFKHMeMebkBEoN7A4suRqMV4RVcDVmqgUKhrOJytVGtktnk9mMxjgAFErAJwKIMPYSHc6PB-BUTQRvjBAQgplZSfqAHL0xlQQHaqaoNN8zMM2S5nVwABehclxezua9ztsEZ0UbglHKD3Jz2xxpwmRsOHUqCKjebdAgobxoggAHNAZQoUA)

```typescript
import { Type, TObject, TComposite, TPick, TOmit, TPartial, Assert } from '@sinclair/typebox'

type TPartialKeys<T extends TObject, K extends keyof T['properties']> = TComposite<[
  TOmit<T, Assert<K, keyof T['properties']>>,
  TPartial<TPick<T, Assert<K, keyof T['properties']>>>
]>
function PartialKeys<T extends TObject, K extends (keyof T['properties'])[]>(schema: T, keys: [...K]): TPartialKeys<T, K[number]> {
  return Type.Composite([
    Type.Omit(schema, keys as never),
    Type.Partial(Type.Pick(schema, keys as never))
  ]) as never
}

// Example

const T = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
})

const C = PartialKeys(T, ['x', 'y'])

console.log(C)
```

### TypeBox 0.32.0

There's actually been some work done recently to improve inference for cases like this. The example below will work on the next revision (scheduled to be release in the next week or so), which should help simplify cases like this. You can install it with

```typescript
npm install @sinclair/typebox@dev
```

```typescript
import { Type, TObject } from '@sinclair/typebox'

function PartialKeys<T extends TObject, K extends PropertyKey[]>(schema: T, keys: [...K]) {
  return Type.Composite([
    Type.Omit(schema, keys),
    Type.Partial(Type.Pick(schema, keys))
  ]) // inferred directly from return type.
}

const T = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
})

const C = PartialKeys(T, ['x', 'y'])

console.log(C)
```
Just to note the 0.32.0 implementation of this for future reference (as the 0.31.0 implementation may not work on 0.32.0)

### Workbench

Just as an aside, if you're doing a bit of work with custom generic TB types, you may find the TB workbench helpful as it can help generate types based on how you would write them in TypeScript. There's been some work done recently here to align TB to TS, allowing TypeBox to be an code target for TypeScript types.

[Workbench Link Here](https://sinclairzx81.github.io/typebox-workbench/?share=DQp0eXBlIFBhcnRpYWxLZXlzPFQsIEsgZXh0ZW5kcyBrZXlvZiBUPiA9IA0KICBPbWl0PFQsIEs%2BICYNCiAgUGFydGlhbDxQaWNrPFQsIEs%2BPg0KDQp0eXBlIFQgPSB7DQogIHg6IG51bWJlciwNCiAgeTogbnVtYmVyLA0KICB6OiBudW1iZXINCn0NCg0KdHlwZSBDID0gUGFydGlhbEtleXM8VCwgJ3gnIHwgJ3knPg%3D%3D)

Hope this helps
S

**Comment by sinclairzx81** [comment]
@tzelon-cypator All good :)

> A question, would you consider adding PartialKeys to library? I find myself use it a lot.

Unfortunately no. PartialKeys would be considered a "higher order type" in the regard it can be constructed by combining one or more primitive types (Pick, Omit, Partial, etc). The preference in TypeBox is to make it easier to compose higher order types, but not to introduce higher order types into the type system. As such, TypeBox limits itself to TS structural, readonly and utility types only, with convenience types only provided if they are equally represented in the TS type system.

There are however a two new core types landing in the next version:

https://github.com/sinclairzx81/typebox/blob/index/changelog/0.32.0.md#Types-Mapped-Type
https://github.com/sinclairzx81/typebox/blob/index/changelog/0.32.0.md#Types-Const-Type

I'm hoping these provide a bit more flexibility for users to create higher order constructs in the library.

Hope this brings some insight
All the best
S
