### ISSUE TITLE
Static type of object without additionalProperties: false

### ISSUE THREAD

**Issue by lewis-wow** [sinclairzx81/typebox#695]
should not type `Static` of this schema

```ts
Type.Object({
  a: Type.Number()
})
```
be 
```ts
{
  a:number; 
  [k: string]: unknown;
}
``` 
than 
```ts
{
  a:number; 
}
```

**Comment by sinclairzx81** [comment]
@lewis-wow Hi!

Yes maybe. TypeBox does try to follow TypeScript's structural notions of a type for indirect non-explicit assignment, but there is room for interpretation here. The following is what TypeBox is trying to match behavior wise.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGoQWA9lATMgbwChlkAPALmRAFcBbAI2hOQE8rbHmBfI0SWIhTpMOAMyEWlavSZQW7GV3mkAXh1k8iRMKwAOKACrIAvGgzYoEiGUggAJgGdzovMgD8yMFBooq8ABtHFGQAelCXSwlHbxpMGig4AIDWZBs7J0icXBZSPPyCwqLikrzw3NLKqurwrwALaAgYHAgAOnaK6q7ustCiBCwQGOQAQSoRKNNCcioARgAaNipcRfVkCW5S2pHkYGc4LKt+weGAIXGLbKmdnqra0939x0dgAHMQOAYAlAB3YDA6qNkH8Acg4PZ7P9gIMkgAFKBYAxQXTIADkqlRnVu2JK5Rx+K2ERsSD0YF2IGQ7Q6BJphXKAyGZIAwhdXPgzAQZsgFktkCtkGsNoTkEzkABaNJkPQBYAIf5g55vEB0CDgZBYGBgiFQmEBZB6BFIsDACDOSGOJIBLA-CD2bTaUhEIA)

```typescript
interface Vector2 {
  x: number
  y: number
}
interface Vector3 {
  x: number
  y: number
  z: number
}

type T = Vector3 extends Vector2 ? true : false  // Vector3 structurally extends Vector2
                                                 //
                                                 // therefore...
                                                 //
const A: Vector3 = { x: 1, y: 2, z: 3 }          // A is Vector3
const B: Vector2 = A                             // B is assignable to A with additionalProperty 'z'
                                                 //
                                                 // except ....
                                                 //
const C: Vector2 = { x: 1, y: 2, z: 3 }          // C - explicit assignment of additional properties disallowed
```
> Where above, values of Vector3 are assignable to Vector2 as Vector3 also structurally represents a Vector2. The only time where this isn't true is with explicit assignment of object literal values.

Note that TypeScript is permissive of structural assignment of A to B even though such an assignment would result in B having additional properties. On the inverse, there isn't a way to prevent TypeScript from forbidding indirect assignments of A to B (as there is no additionalProperties false constraint in TypeScript). For such assignments to be forbidden, I'd imagine TypeScript would need to adopt a nominal type system (not a structural one)

TypeBox's view of the above is that it should simply infer without the `[k: string]: unknown` as indirect assignment is generally permissive by the TypeScript type system anyway, and that validation constraints (such as additionalProperties) are only applicable to validation, not the type system....except....

---

### AdditionalProperties of Type

TypeBox does have a way to express additional properties of a given type.

```typescript
const T = Type.Object({
  x: Type.Number(),
  y: Type.Number()
}, {
  additionalProperties: Type.Boolean()
})
// which would naturally infer as
type T = {
  x: number,
  y: number,
  [k: string]: boolean
}
```
The above works today from a validation standpoint, however the type `T` still infers as `{ x: number, y: number }` as additionalProperties is kept unknown to the type system for the assignability reasons above (for now). This may change in future revisions once other parts of the codebase have stabilized, but for now, I'm keeping on with the current inference.

---

Will close off this issue for now, but would be happy to continue things over [here](https://github.com/sinclairzx81/typebox/discussions) as I do think it's worth discussing and do partially agree the expected inferred type should factor additionalProperties in some capacity. There is quite a bit to factor (including composition of schematics where applied constraints can lead to illogical types), so a more formal discussion on this would be the best way to proceed for any changes to how TypeBox infers types.

Hope this brings some insight
Cheers
S
