### ISSUE TITLE
Composite & Omit: infinite and Never

### ISSUE THREAD

**Issue by simon-tannai** [sinclairzx81/typebox#698]
Hello 👋

I'm currently refactoring all the typing of my project with a combination of `Type.Composite()` and `Type.Omit()` methods.
But I'm facing to two issues:

1. `Type instantiation is excessively deep and possibly infinite`
2. `Property 'nameOfProperty' does not exist on type  never`

# Examples
## Type instantiation is excessively deep and possibly infinite
First, I'm defining a default schema and some "shortcuts", representing the common MySQL tables fields
```typescript
export const timestampSchema = Type.Date({
  maximumTimestamp: 100000,
  minimumTimestamp: 999999,
});

export const OptionalNullableDate = Type.Optional({ ...timestampSchema, nullable: true, default: undefined });

export const OptionalNullableNumber: TOptional<TNumber> = Type.Optional(Type.Number({ nullable: true, default: undefined }));

export const OptionalNullableBoolean: TOptional<TBoolean> = Type.Optional(Type.Boolean({ nullable: true, default: undefined }));

export const IDSchema = Type.Number({ minimum: 1 });

export const defaultDatabaseSchema = Type.Object({
  id: IDSchema,
  createdAt: timestampSchema,
  updatedAt: timestampSchema,
});
export type DefaultDatabaseType = Static<typeof defaultDatabaseSchema>;
```

Then, I'm defining the `orderTableSchema`:
```typescript
export const orderTableDbSchema = Type.Composite([
  defaultDatabaseSchema,
  Type.Object({
    firstName: Type.String(),
    lastName: Type.String(),
    deliveryDate: OptionalNullableDate,
    [...]
    deliveryTo: Type.Number(),
  }),
]);
```

After that, I'm creating the `orderSchema`:
```typescript
export const orderSchema = Type.Composite([
  Type.Omit(orderTableDbSchema, [
    'createdAt',
    'updatedAt',
  ]),
  Type.Object({
    ordersProducts: Type.Array(orderProductSchema), // Typebox Composite
    shops: Type.Array(shopSchema), // Typebox Composite
    users: Type.Optional(Type.Array(userSchema, { nullable: true, default: undefined })),  // Typebox Composite
  }),
]);
```
At this moment, I'm getting the error `Type instantiation is excessively deep and possibly infinite.` on the `Type.Omit(orderTableDbSchema, [`.

Finaly, I'm creating the `orderRestSchema`:
```typescript
export const orderRestSchema = Type.Composite([
  Type.Omit(orderTableDbSchema, [
    'createdAt',
    [...]
    'deliveryDate',
  ]),
  Type.Object({
    deliveryDate: Type.String(),
    createdAt: Type.String(),
    updatedAt: Type.String(),
    products: Type.Array(orderProductRestSchema), // Typebox Composite
    deliveryInformation: addressSchema, // Typebox object
    quantity: Type.Number(),
    waitingForPayment: Type.Boolean(),
    shop: shopRestSchema, // Typebox Composite
    numberPackages: Type.Number(),
    paidAt: OptionalNullableString(),
    canceledAt: OptionalNullableString(),
    retrievedAt: OptionalNullableString(),
    paymentFailedAt: OptionalNullableString(),
    confirmedByShopAt: OptionalNullableString(),
    pickedUpAt: OptionalNullableString(),
  })]);
```
On the `Type.Composite()`, I get the error `Type instantiation is excessively deep and possibly infinite`

Is there an issue with the deep `Composite` usage ? 

## Property `nameOfProperty` does not exist on type `never`
Into my code, I'm using the `OrderType` type, which is a type generated with the Typebox's `Static`:
```typescript
export type OrderType = Static<typeof orderSchema>;
```

```typescript
  return orders.map((order: OrderType) => ({
    ...order,
    deliveryDate: order.deliveryDate?.toISODate() || null,
    [...]
```
I'm getting this error: `Property  toISODate  does not exist on type  never `.
This field is defined into the `orderTableSchema`. It's looks like with the different `Omit()` and `Composite()`, the typing is "loose".

I suppose it's related the the previous error ?

**Comment by sinclairzx81** [comment]
@simon-tannai Hi,

It's difficult to provide a concise answer without the full schematics, however one thing that stands out is the definition of.

```typescript
export const OptionalNullableDate = Type.Optional({ ...timestampSchema, nullable: true, default: undefined });
```
The application of additional properties in this way may cause TypeScript to loose track of the underlying TSchema type (which is particularly true for modifiers which TypeBox augments internally). I've updated this to the following (where I noted TS was producing errors for the composition of OptionalNullableDate using spread). You can review the full code at the link below.

[TypeScript Link Here](https://www.typescriptlang.org/play?ssl=14&ssc=21&pln=14&pc=22#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsriQBYYgHkByAriAEYZTkBCEEANhgIA7cgHkwxCEIJ84AXzgAzKBBBwA5AAEAzsCEk+BYFAD0MdBlYQAHuoBQdjNciw4JKdvjEQGTwXCUNHRwALwoFgB0ACJEGAAUCHZwcHTWoCzIoL6E4ABccACMAAwlJVhJKXrpIJk+fnlwAJzNLeVyAJQA3A4mJnBM2hhwMFTA2sMQcARMAOY+QvDa1LREpOME48DwUBiEeuMjQxTLweaYEY7O0PDuQp5wAIKz8-BhADzIcE4wGEIAJuNjkECAA+OJLYH5ZA4Ah-P5bYBSGT5ABKGHcUD+bwACipMLBUABpDCoHBMIQAayEEAA7kIQe0oaEQXAEnAIhzYfDJNI+DgOREISt5O0en0mGA-rE-hN+oMps9fjBLi4bh54OIeTJmHxDKwBDEfqFwudNYjeXEnnMlXFvNl-GBAiscEghExdQR9Rh8jAoExsHA-hhFNM+DB8uSg4o9BgZR1RXZev19KoXkpoF8oCooNpE30nKq3Oq4GakXwdXqDbFjWhTRJzTI2QK7fVHSd6HA3R6vT6-QGo6Hw8mozG410HAXrkW7hr62WK56BMw2BwoaXeR9l+woCywrWMBF1439xEtxw2V3K97hn2cAP3UPI8HRyLxyqp7d7kfy+6rzx+IIQhrnOG7IP+AjCLuJoHt+cQnuBgEXr+i7Xr6-p3sGg4Rv8z5CLGr7dO+rifvAACSUROsEe6RGeUBsiAVQgCw+QFCKhGTsRxb3mGhqehsGCUQQNaRKIrAAFbojACQVMAfz5ORgnlMkJA7NKDxDi2ORtsCSn9JKakaVkraKXYHTdBxXgWHAUSYQ+vGsPx+7GvgqwkG8ZwYBAiiBrZPFEHxgyCSChFEWqM5wNAQZQMgKFRKwgnCecADCqiQLoPxxAA2hU3EwPZ-EmckJ6iRJJBSYkyTJNGOYwAw-jXie+BQHoMxxO0unJIYnh1T4UKRE1LVtR1Pl8MAABuHCoIa17fguXrTcNQajRNUCoMgEB9ectFDRUHTlAAum+FnTvckUcAl1HJalEDpfE2VFSJDFSWd0WxfF7Y4PdlXqCpgg-H86nqMN6gSlK-2A7ph26cV4mSdJlVwEmEAUgA-Lt7V2Id3RAA)

```typescript
// use this to augment schematics and to retain the TSchema type.
export const Augment = <T extends TSchema>(schema: T, additional: Record<PropertyKey, unknown>): T => ({ ...additional, ...schema })

// updated to use augment
export const OptionalNullableDate = Type.Optional(Augment(timestampSchema, { nullable: true, default: undefined }))
```

Let me know if this helps. If there are still issues, it would be helpful to see a full reproduction of the schematics + errors present on the TSP link.

Cheers
S

**Comment by simon-tannai** [comment]
@sinclairzx81 Thanks for your answer 🙏

Unfortunatly, it's not fixing the issue.
[I created a TSP](https://www.typescriptlang.org/play?ts=5.0.4#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsriQBYYgHkByAriAEYZTkBCEEANhgIA7cgHkwxCEIJ84AXzgAzKBBBwA5AAEAzsCEk+BYFAD0MdBlYQAHuoBQdjNciw4JKdvjEQGTwXCUNHRwALwoFgB0ACJEGAAUCHZwcHTWoCzIoL6E4ABccACMAAwlJVhJKXrpIJk+fnlwAJzNLeVyAJQA3A4mJnBM2hhwMFTA2sMQcARMAOY+QvDa1LREpOME48DwUBiEeuMjQxTLweaYEY7O0PDuQp5wAIKz8-BhADzIcE4wGEIAJuNjkECAA+OJLYH5ZA4Ah-P5bYBSGT5ABKGHcUD+bwACipMLBUABpDCoHBMIQAayEEAA7kIQe0oaEQXAEnAIhzYfDJNI+DgOREISt5O0en0mGA-rE-hN+oMps9fjBLi4bh54OIeTJmHxDKwBDEfqFwudNYjeXEnnMlXFvNl-GBAiscEghExdQR9Rh8jAoExsHA-hhFNM+DB8uSg4o9BgZR1RXZev19KoXkpoF8oCooNpE30nKq3Oq4GakXwdXqDbFjWhTRJzTI2QK7fVHSd6HA3R6vT6-QGo6Hw8mozG410HAXrkW7hr62WK56BMw2BwoaXeR9l+woCywrWMBF1439xEtxw2V3K97hn2cAP3UPI8HRyLxyqp7d7kfy+6rzx+IIQhrnOG7IP+AjCLuJoHt+cQnuBgEXr+i7Xr6-p3sGg4Rv8z5CLGr7dO+rifrOWo-t2Aj4FAegzMacQgHo+RuiuUDGkUOCpExLDbsaABMACs-HtMy0GHiBx6RFRNEJBUl4ob26EVPeYbYSOeF-OUyQMUIAAyvwzCM+TaZpKQENYelCAZVBGWZbTtG+k7EcWC5elJll0dpXEsWxHFmV5PFhAJQkiSeACqQjmnEADaFQnm5MxstpFlWUZei+eZ+mGaZ1giiZJ4VnE7TlAAug5VxOTOcAuQICHCDWkThZFUXwbwEFCIV5CRAV7SlYRRFqpVACSUROsEe5ddx55INp1T5AUIqEY5A33MpMCGp6GwYKNBD1aarAAFbojAMnJMAfz5MN20mSQOzSg8Q4tjkbbAiZEpSj8fz3T6WStlddgdN0S3DBYcBRJhD7rawm37sa+CrCQbxnBgECKIG4NhpDm3bSCfX9dO9zQEGUDIChUSsNtu0HgAwqokC6D80VKeja1EBtgx-ckJ6iAdR0nckSjGJ4DD+NecW+tJRUVMkhhCyLUKSeLlkdVLcBgFQUgYGeUDy+c8XK-zXx0MAfA6weeuSwbXI7No2imxE5smckJBbKgdsOyrABewBgDTQb5N+1VbYrCUW-z7jkr6ruie7Bv7GhJA8rbJbieRV4x-zQZ8MAABuHCoPubvB-r-PaOrYDCz4hfUUrofJKXEBgA8cLW0nYvVyHjuq0wUDUJtKKxHbWvF8kYDd73gwAGI7AAjv6+hR23Eud34MADFXS8q541GYNiBCoC8g3ndHRe16rRifUOJ6GvEp8kMIJAYAIF-+yngfX53OzixgufP8nZFv7ETumcc552vi-f+yEvTvxVsA3OUB85ZFwHwCAl8Fbt2HmffeSoJ5GCfl9P+DZU6k0ASrGAKCZC4ggH8JgCdtCDX0HwAAakQQek0oAYLIYQPglDqG0IAKLWAMMw1B5wh6n04RQlQvCYDaGEQ8EAEAI6sJYhg2BecJ4YF8PQoRLDRJiKAY-EB8CNG+AETokRB59EwMMXA1AJjZFEHkYohYyjtwYMGFAbOpAMD2O0Uw3R+U2HuI4F4h+9izH+IsaeIJp8PGhJ8ZohxMAnFKL0TEzuEi+B+OEa4884jyF8AiTktJKj8lcLkQo1JgTSmd1Hj3Kgm1RCYg4BPY214A6QMoifTutxoxQB8H8LgqBcBl3wR0iiGBoEGzAKQCksZQqNyHOMq8Uz+beybn8Fu4DCGB3TnXcWmA0SKEjIfbZ85OlB3QafQwUS9lwD4JZdeNdO5CFYLvEgFICAzF8Gc3kgctYGKzrYqeqhcnsNPmo+ByAIBguLh0Eq44gZIxLM04mpNWAwzCHDYgCMkYozgITDgJMoHk3bDjCc5VlrwEJVAHhNCYAU3GntQ6Cc+ZnV+dqC5AKKhgGog-bJujlkoW5SPPlGAimCtflythJlCDWH7j8DlRCvQirgNnRxlSXEEPORM1Vs9hDEHMHbehPxvngpMnU8eGAFXtKlbqmVPKx4NMnjPOeJAo5Ctct0ioOwjYRUsvgCAHylX-IdQDPGyKmlEzpQnTFeBCA4sRhYfFNKY0MrJYtSl+NqWorTWiTwjLRLcxZcdRIp0j6eqXA60V3iBVLLtVeVVvLvESvrRA+1LFZVmRtSG6VnaKjquSZqttOy+3bhMvqhYLtjULAwGa4ulrnXWoHtqv5Y6OAWqdZtKeGBZ6-Hdb2iZ6dfVGH9TMQNwbV2co7eO-6ZVCwkSmM3Xw2hC1cx5qystnY5ZFpTnEXZJ9Q5IztrBADVzQ5WxfU8hK009DJSykUXKFRnZGuPug2DulMrWTgIh+FyHnGR2g4lODWH8i4dDl7H2VDRaRFAxc82oc6ZcN9jRusZF-30cAyZG5RGMPwew+R7jjy0PST46RnDSGR7qzwvQoM1gQN-rAxLRj0nNZsIU+xpTNdQ7qwGDRAuv7NOcfAyZOOfoE7mlbrRxTxnpLsTgAAFlKM5+yOAkzIMsj8awypkjOpNRwdwIANOEI4xM2qQhQ56B+D3VQFdWMwRs0erjFRnVRGADMUg1HgtllC3+VqgFQ59M8GljL7g-aGZC1pkOodBi3D+CVzL5WuaJbTsl3zGw+ECEHdAbLFpA7hdDo-b+RBoANbK-FsSRmksmYqEqDgzbBhxd642KrhVCvIJ6xVnLq3XNKV4NrLbfXbPaZMgQMABBYAvC1stvguWUIMZMurH45Yf3Nam61mbvmUGPxRLwEA13DsreO9VkyVgiBLcB7dnbjHgAcAB29yrwO1t2UBlm5FGyW5xuxaQJNmB8WQZttjTND7iw0vzem4ElMIg03ABAem8QYqc1owxY6NLiUGlJS9OAjP+bqBuoID6911Cd3UG9O6MBhcq3UOds6QuRd330ENi+kuDbqE-tRb+sY5dS-O1ghYOC2nK-l1IPpAyhkjIbtr1XMyPnzMWSr3nkLUDXwd6VPKtGP2lusUC0BK7F7PJVvz8XRHT5i8F7c710ypH0qs+cB4WY95xFTdHhO5PtoQpsXnehihoB0B5PkAnr72yd0nYaheE0akqxpEYYglkJ7QF3nrqJ4WMHMW3O8z53zY+WPSSrGXv9K2XI3gbBXD88Ejp1R94f-N1ew5-mMht93I-811y8A34-D1T4DyPk3xgzfDNGRPtd03p8j1mXbhf7at8dwqB0XqEaQZRo4OTrHCacd4tRmT7IRO7BAA) to reproduce the `Type instantiation is excessively deep and possibly infinite ` error.

**Comment by sinclairzx81** [comment]
@simon-tannai Thanks for the repro.

Yes, this does look like it's pushing out the extents of the type system. Unfortunately, there isn't going to be any new patches to 0.31.x to resolve this issue, but the good news is that TypeBox is scheduled to release 0.32.0 within the next few days, and this version has a lot of optimizations to push out inference further.

You can install the current development revision with the following (which is the version set to be released shortly)

```
npm install @sinclair/typebox@0.32.0-dev-28
```
Have tested your repro against the 0.32.0 build, and things should work ok. It should be fine to take on this development version in the interim (so you can continue on with refactoring), just be mindful to update to the published revision once released.

Let me know if this helps.

**Comment by simon-tannai** [comment]
Thanks @sinclairzx81, this version fix a part of the error but not everything. 
I'll continue to try to investigate / optimize to understand 🙏
