### ISSUE TITLE
Supplying default values

### ISSUE THREAD

**Issue by robcresswell** [sinclairzx81/typebox#7]
Hello! First off, great project, looks like a really interesting idea! I stumbled across it completely by accident while browsing the typescript subreddit, and its exactly the kind of thing I've been looking for to plug into Fastify (currently I'm manually syncing TS definitions and Schemas)

I couldn't see any way of defining default values. Is this something that I missed, or that you're planning on supporting? For example, how would the follow translate into a Typebox definition?

```
timeout: {
  type: 'number',
  minimum: 1000,
  maximum: 15000,
  default: 5000,
}
```

It seems like `Type.Range(1000, 15000)` mostly covers it, but not the default handler

**Comment by sinclairzx81** [comment]
Hi, thanks for pointing this out. The `Type.Range(...)` function is actually being phased out in favor of passing options directly on `Type.Number({...})` I have just pushed an update that does this as well as adds TS types for all the constraints listed for [number](https://json-schema.org/understanding-json-schema/reference/numeric.html). The version to grab is `0.9.3`. Example below.

```typescript
// npm install @sinclair/typebox@latest --save

const Timeout = Type.Number({   
  minimum: 1000,
  maximum: 15000,
  default: 5000
})
```
I couldn't find information relating `default` constraint. However if you just pass it as an option, it will appear in the resulting schema if your validator or other processes require it.

Hope that helps!

**Comment by robcresswell** [comment]
Yeah thats perfect. I pulled the `default` thing directly form `ajv`: https://ajv.js.org/#assigning-defaults

**Comment by robcresswell** [comment]
Closing, as it seems this is solved. Thanks for your help!
