### ISSUE TITLE
Override TS types?

### ISSUE THREAD

**Issue by pluma** [sinclairzx81/typebox#70]
Is there a way to override what TS type is generated for a given type?

I'm using type-fest's `Opaque` type to distinguish between different "kinds" of primitives (e.g. strings that represent URLs). There doesn't currently seem to be a way to represent these in a typebox schema.

A possible API could look like this:

```ts
// from type-fest
type UrlString = Opaque<string, "url">;

// schema
const File = Type.Object({
  url: Type.Opaque<UrlString>(Type.String()),
  title: Type.String()
});
type File = Static<typeof File>; // { url: Opaque<string, "url">, title: string }
```

This wouldn't have to be tied to type-fest specifically. `Type.Opaque` could serve as a general escape-hatch to override the "natural" type. Maybe it could be renamed to avoid confusion.

**Comment by sinclairzx81** [comment]
@pluma Hi, thanks for the suggestion! :)

Currently there are no immediate plans to implement `Type.Opaque(...)` in TypeBox, though this situation could change if the TypeScript team reach consensus and decide to introduce it as a future utility type or some private / hidden / opaque property mechanism of the language. As it stands the [following](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUHkBGAVhgMYw7IAKUEmswGAzjgMowCGMwJcAvnADMaIOAHIAAo2AA7EgBt2wKAHoY6DPggAPUQCg4u5crgBaM+YuWr1m7euHjaTCYBiTGA9N3vP35d26GFqQsHBqmHC4YOwAjgCuGAA8TtgoEADWGNJwALxwcdLp0hAA7tIAfLko6nAAZIhwUBjsACYQ0nKocAD63bSxCb0AXGmZ2bwA3AHhGHAAglVRA0lI7COMMFAyAOZ8OKLsopVGcAAWEABuGFABJ373D-YnKQBC2p6Pn48BJO0bkdF4rM8sk4EEYFkWow8ERSDBktRaNcuExyhQMlkwVoIdIoXANltpNtygAKGAjZA4GAY6QUmkASlylQQ+jgbKaMDiUGyKQAdABJaQQqCMOEkgDa5GqmF5BGIZBJSF6-SBw2lGF5ACVmm0OqgSXyADLAYXsORkhmM3j0gC69N0vB+f3gL0WgISBvUsthCtWFK9bEJ2xJVvp+0O9t0MzZrrybE43ESMwgAjgL2OxnOVxuAQCQA) would be possible in TypeBox today.

```typescript
import { Type, TObject, TProperties, Static } from '@sinclair/typebox'
 
// ----------------------------------------------------
// Type-Fest
// ----------------------------------------------------

export type Opaque<Type, Token = unknown> = Type & { readonly __opaque__: Token };

type A = Opaque<{ a: string }, 'a'> // hover

// ----------------------------------------------------
// TypeBox
// ----------------------------------------------------

const Opaque = <T extends TObject<TProperties>, Token extends string>(t: T, token: Token) => {
    return Type.Intersect([t, Type.Object({ __opaque__: Type.Readonly(Type.Literal(token)) })])
}

const B = Opaque(Type.Object({ a: Type.String() }), 'a')

type  B = Static<typeof B> // hover
```
However, as the resulting schema would include the `__opaque__` property, this clearly wouldn't be the intent. So for something like this to work in TypeBox (as I'd imagine it anyway), TypeScript would ideally need some mechanism to say a property should be treated as private (opaque) or inaccessible.  In this scenario, TypeBox would omit properties of this form, potentially as a type of `modifier`, so maybe something like.
```typescript
const Opaque = <T extends TObject<TProperties>, Token extends string>(t: T, token: Token) => {
    return Type.Intersect([t, Type.Object({ __opaque__: Type.Opaque(Type.Literal(token)) })])
}
// analogous to
export type Opaque<Type, Token = unknown> = Type & { opaque __opaque__: Token };
```
Have been keeping an eye out for this feature of this sort to emerge primarily as it would also allow TypeBox to discard the `kind` and `modifier` Symbols currently applied to all schemas as well as a few other things related to type inference. 

Hope this provides a bit of insight in the current state of things. 
Cheers
S

**Comment by pluma** [comment]
Yeah, I figured as much. That's why I'd instead prefer a mechanism for typebox to allow users to mask/shadow the "implementation" type and let `Static` see something else instead.

e.g.
```ts
const A = Type.Object({
  str: Type.String(),
  url: Type.Override<UrlString>(Type.String())
});

type A = Static<typeof A>; // { str: string, url: UrlString }
```

The `Opaque` type is just a reason I ran into this.

**Comment by pluma** [comment]
I was able to implement this like so:

```ts
type TOpaque<U, T extends TSchema> = {
  [key in keyof T]: T[key]
} & {
  readonly __opaque__: U;
};

const Opaque = <U, T extends TSchema>(item: T) => {
  return item as TOpaque<U, T>
}

type StaticX<T> = T extends TOpaque<infer U, any> ? U : Static<T>;
```

Note that this still results in the fake `__opaque__` property appearing on both the value (as expected) as well as the schema (as maybe not expected) so this is probably not something users will want unless they're already using type-fest's `Opaque` type.

**Comment by pluma** [comment]
After further experiments this approach turned out to cause weird bugs like breaking `StaticObject`, so I'm not going to pursue it further. I'll close this issue as I don't think there's anything you should do unless `opaque` lands in TS proper.

**Comment by sinclairzx81** [comment]
@pluma Hi, thanks for the follow up. Yeah, had a look at this last night and you were on the right track. Outside of the `opaque` stuff, it was interesting to think about providing some escape hatch for `Static<T>` (without the need for `StaticX<T>` as you implemented), But not sure how that should work. Indirectly all roads gravitate towards `opaque` type support in TypeScript to allow composition of the resulting types.

On `StaticObject<T>`, I'm actually quite bothered by this type. I do wonder if there is a better way to resolve the `readonly`, `optional` property modifiers from the `Object` without those horrible intersections (which do break easy as it has a tendency to push TS recursion limits). I'm always up for suggestions to improve this if you have any thoughts. 

Thanks Again
S

**Comment by pluma** [comment]
No worries. Typebox is great even without the ability to override `Static` easily. I'll probably just stop using `Opaque` for now.

**Comment by SebastienGllmt** [comment]
Sorry for commenting on a closed issue, but I found this issue through Google and just wanted to mention that you can now override `Static` easily using `Type.Unsafe` so you can implement opaque types using `Type.Unsafe<UrlString>(Type.String())`
