### ISSUE TITLE
schema definition

### ISSUE THREAD

**Issue by lifeiscontent** [sinclairzx81/typebox#707]
I'm building a library on top of typebox,

I was wondering if you had some suggestions on how to create some kind of schema definition from a typebox type.

here's the test I'm trying to get passing.

```ts
test.describe('conform-typebox', () => {
	const schema = Type.Object({
		text: Type.Optional(
			Type.String({
				minLength: 1,
				maxLength: 100,
				pattern: '^[A-Z]{1-100}$',
			}),
		),
		tag: Type.String({ pattern: 'x|y|z' }),
		number: Type.Number({ minimum: 1, maximum: 10 }),
		timestamp: Type.Optional(
			Type.Date({
				minimumTimestamp: new Date(1).getTime(),
				maximumTimestamp: new Date().getTime(),
				default: new Date().getTime(),
			}),
		),
		options: Type.Array(Type.String({ pattern: 'a|b|c' }), {
			minItems: 3,
		}),
		nested: Type.Optional(
			Type.Object({
				key: Type.String(),
			}),
		),
		list: Type.Optional(
			Type.Array(
				Type.Object({
					key: Type.String(),
				}),
				{ maxItems: 0 },
			),
		),
	});

	const payload = {
		text: '',
		tag: '',
		number: '99',
		timestamp: new Date(0).toISOString(),
		options: ['a', 'd'],
		nested: { key: '' },
		list: [{ key: '' }],
	};
	const error = {
		text: ['min', 'regex'],
		tag: ['required', 'invalid'],
		number: ['max'],
		timestamp: ['min'],
		'options[1]': ['invalid'],
		options: ['min'],
		'nested.key': ['required'],
		nested: ['error'],
		'list[0].key': ['required'],
		'list[0]': ['error'],
		list: ['max'],
		'': ['error'],
	};

	test('getFieldsetConstraint', () => {
		expect(getFieldsetConstraint(schema)).toEqual({
			text: {
				minLength: 1,
				maxLength: 100,
				pattern: '^[A-Z]{1-100}$',
			},
			tag: {
				required: true,
				pattern: 'x|y|z',
			},
			number: {
				required: true,
				min: 1,
				max: 10,
			},
			timestamp: {},
			options: {},
			nested: {},
			list: {},
		});
	});

	test('parse', () => {
		const formData = createFormData([
			['text', payload.text],
			['tag', payload.tag],
			['number', payload.number],
			['timestamp', payload.timestamp],
			['options[0]', payload.options[0]],
			['options[1]', payload.options[1]],
			['nested.key', payload.nested.key],
			['list[0].key', payload.list[0].key],
		]);

		expect(parse(formData, { schema })).toEqual({
			intent: 'submit',
			payload,
			error,
		});
	});
});
```

**Comment by sinclairzx81** [comment]
@lifeiscontent Hi,

> I was wondering if you had some suggestions on how to create some kind of schema definition from a typebox type.

TypeBox types are themselves schema definitions, and it is possible to extract and select sub schematics from them (see Index). However, if you just need to assert a TypeBox type matches an expected schema definition, usually the easiest way to do this is to just create the TypeBox type you expect. TypeBox tests some types this way internally, particularly when asserting the structure for computed or mapped types.

The following is a basic setup that tests the return type for Vector is expected.

```typescript
import { Type, TSchema } from '@sinclair/typebox'

// ----------------------------------------------------------------
// test infrastructure
// ----------------------------------------------------------------
declare function assertDeepEqual(left: unknown, right: unknown): void

// ----------------------------------------------------------------
// example
// ----------------------------------------------------------------
const Vector = <T extends TSchema>(T: T) => Type.Object({ x: T, y: T, z: T })

const T = Vector(Type.Number()) 

// this should pass
assertDeepEqual(T, Type.Object({
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number(),
}))

// this should fail
assertDeepEqual(T, Type.Object({
    x: Type.String(),
    y: Type.String(),
    z: Type.String(),
}))
```
The above approach is generally easier than explicitly testing each Json Schema property, and lets you reason about types without factoring the schematics that constituents them.

Does this help?

**Comment by lifeiscontent** [comment]
Hi @sinclairzx81 thanks for the quick response, this was helpful but not quite what I was looking for, I probably didn't give a great explanation of what I'm looking for.

For context, I'm trying to build an adapter like the following:

https://github.com/edmundhung/conform/tree/main/packages/conform-zod
https://github.com/edmundhung/conform/tree/main/packages/conform-yup

there are two main concerns for this adapter, first, it takes a schema, and transforms it into its own schema representing something of what an HTML5 ValidityState would look like.

it uses the schemas internals to represent how a form should be validated (using HTML5 input attributes)

the next concern is when a schema throws an error, the transformation then needs to understand which of the HTML5 input attributes are invalid. the list looks like the following:

```js
const attrs = [
		'required',
		'minLength',
		'maxLength',
		'min',
		'max',
		'step',
		'multiple',
		'pattern',
	];
```

if you have some words of wisdom of how to approach this problem differently, I'm all ears for some thoughts, but initially, what I was invisioning is being able to share the schemas from a Node.js API service with a client-side validation library using the `Value.Decode` from typebox and the `Value.Errors` to handle the scenarios I've outlined above.

Thanks again for your thoughtful response

- Aaron

**Comment by sinclairzx81** [comment]
@lifeiscontent Heya,

Might close off this issue for now as this topic is probably best discussed via GH discussion thread (as it's generally more integration related than issue related). Feel free to start a thread if you have any other questions on TB reflection, integration or  validation.

All the best!
S

**Comment by lifeiscontent** [comment]
@sinclairzx81 yep, sounds good, thank you so much again for the well thought out explanation and illustration, you definitely didn't need to go into that kind of detail, but very much appreciate that you did, so thank you! and happy holidays :)
