### ISSUE TITLE
How to do Async Check?

### ISSUE THREAD

**Issue by lifeiscontent** [sinclairzx81/typebox#710]
If I have a `Type.Promise(Type.String())` how can I use `Value.Decode` or `Value.Check` or some other method to do async validation?

**Comment by sinclairzx81** [comment]
@lifeiscontent Heya

TypeBox doesn't actually validate Promise, Function, Constructor, Iterator and AsyncIterator types. Rather these types are included as a semi formal (albeit non-standard) interface description format used mostly in RPC work (although there's likely other uses for them). You can think of them as an analog to something like GRPC [IDL](https://en.wikipedia.org/wiki/Interface_description_language), or SOAP's [WSDL](https://en.wikipedia.org/wiki/Web_Services_Description_Language), in that they describe callable network functions and return types.

From the readme.

> TypeBox provides an extended type set that can be used to create schematics for common JavaScript constructs. These types can not be used with any standard Json Schema validator; but can be used to frame schematics for interfaces that may receive Json validated data. JavaScript types are prefixed with the [JavaScript] jsdoc comment for convenience. The following table lists the supported types.

For the most part, these types can be largely be ignored (you wouldn't use them to validate data directly), rather they are generally orientated towards integrating into larger systems (such as [this](https://github.com/sinclairzx81/sidewinder) one), where being able to describe various JavaScript constructs (such as Functions and Promises) can assist with generating runtime interface logic derived from interface metadata (i.e. reflection)

If you're wondering how they're used (or at least how I use them), see link below.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AAmGA7sAHa1QD0AxhIzFAIbswSAKFCRYiOAHUMAIwDKGKADdg7LLgJFSlGvSYtWFRUsXDR0eEmkyAwgBtgGbjnyFi5KrQbNFHB08EhIVZWOABaCMio6JjYuPiExPjg0JsuHn4YFPCk3Lz8gqigzkYKeDTuPgE4AF4UdAwAOgqMgQAKBCE4brgjZUUALkQuntGSXmpqEiG0TEaAMQBXRgFgLjaAbVmmgDlFkBlFNoBKABp6ub2Do+OAXXPtxqvDqBPjke7sIWx37ML-gGAsLZBTKVQYP5AqHQuLFLhlXrGcG1OCMehSWSglRqNotKowX59bFNEAYGAACwg1Da40mJHObXY-m4AElqOdeOcZMdagA+YajEKjUYAH2F4rFwpFHzgQvFcEl8u6ip6AGpInAwLw+CAKHA2rwhox9i8uUaTYp3oLQvKVbaZXKJUq1RrlsAAI6LLBMxzOXTcYB4RxQB02iWhpXqiJwUkUqmo3ikuBMPCKKAYaiuLQlVpZa2hiOjKNhODpmCLKCMZOMVNQdOZ3h6gAGxuuUCbhZ60tGZYrVd4cFVcBkcG+vyFMMnU+y9l9WQnU8XQLhpXgPoCKLRdAxtmZMFx6Xx5xI5JgMDAAxCjWvjRIvxKCPTFEWdngdV4dF4wDXe8a7F4dh2DSExTOcACM4HvI6CrOrBTpKtK0F2nBzrIS60bagA5vsAR6o2+qxpS1BDGUUBMJhHLmm2ZqohaUBQWGMEoShYrZF2zEocWMZkkRCZJimaYZlmxA5vibHKuJg4ak+L7wMAzati8TZAA)



Hope this helps
S

**Comment by lifeiscontent** [comment]
@sinclairzx81 thanks again, I had no idea sidewinder existed, this seems really cool; you are building so many interesting projects! Thanks for the context and sharing this project. I'll go ahead and close the issue.
