### ISSUE TITLE
Support JavaScript Map<K,V> and Set<T>

### ISSUE THREAD

**Issue by hansSchall** [sinclairzx81/typebox#713]
Maps and Sets seem to be the only thing that is missing to cover all commonly used builtins

```typescript
Type.Map<K extends TSchema, V extends TSchema>(key: K, value: V): TMap<K,V>;
Type.Set<T extends TSchema>(schema: T): TSet<T>;
```

Could be extended to WeakMap and WeakSet...

Workaround until this is impemented:
```typescript
export type TMapWorkaround<K extends TSchema, V extends TSchema> = TArray<TTuple<[K,V]>>;

export function MapWorkaround<K extends TSchema, V extends TSchema>(key: K, value: V): TMapWorkaround<K,V> {
    return Type.Array(Type.Tuple([key,value]));
}


const mapType = MapWorkaround(Type.String(), Type.Number());

const a: Static<typeof mapType> = [["foo", 5]]; // [string, number][]

const b = new Map(a); // Map<string, number>

const c = [...b.entries()]; // Static<typeof mapType> = [string, number][]
```

By the way: When writing the workaround i experienced this behavior:
```typescript
type Foo<K extends TSchema, V extends TSchema> = Static<TArray<TTuple<[K, V]>>>;
// maps to
type Foo<K extends TSchema, V extends TSchema> = [Static<AssertType<K, TSchema>, unknown[] & []>, ...TTupleInfer<AssertRest<[V], TSchema[]>, unknown[] & []>][]
// instead of
type Foo<K extends TSchema, V extends TSchema> = [Static<K>, Static<V>][]
// this might be a bug, because the first two types are not assignable to the last one
```

**Comment by sinclairzx81** [comment]
@hansSchall Hi

It is very unlikely TypeBox will get built in support Map and Set as these are container types in JavaScript which are not immediately serializable / transmissible data structures. However as per your example, you can represent their constructor arguments as JsonSchema (which is suitable for TypeBox)

Based on this, both Map and Set can be expressed as user defined types which describe the constructor arguments, and optionally wrapped with a Transform type to handle automatic decode / encode of these data structures. 

See example below.

```typescript
import { Type, TSchema } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// ------------------------------------------------------------------
// Types: Set & Map
// ------------------------------------------------------------------
const SetType = <T extends TSchema>(T: T) => {
  const schema = Type.Array(T, { uniqueItems: true })
  return Type.Transform(schema)
    .Decode(value => new Set(value))
    .Encode(value => [...value])
}

const MapType = <K extends TSchema, T extends TSchema>(K: K, T: T) => {
  const schema = Type.Array(Type.Tuple([K, T]))
  return Type.Transform(schema)
    .Decode(value => new Map(value))
    .Encode(value => [...value.entries()])
}
// ------------------------------------------------------------------
// Usage
// ------------------------------------------------------------------
{
  const T = SetType(Type.String())
  const D = Value.Decode(T, ['A', 'B', 'C'])
  const E = Value.Encode(T, D)

  console.log('Set-Decoded', D)
  console.log('Set-Encoded', E)
}
{
  const T = MapType(Type.String(), Type.Number())
  const D = Value.Decode(T, [['A', 1], ['B', 2]])
  const E = Value.Encode(T, D)

  console.log('Map-Decoded', D)
  console.log('Map-Encoded', E)
}
```
This isn't really a workaround. User defined types is general functionality provided by TypeBox. Also note, the above Transform implementation would equally apply to other JavaScript constructs (WeakMap, TypedArrays, Blob, URL, URLSearchParams, FormData, Date, etc) without TypeBox having to implement new them all as built in Types. Currently, TypeBox does have built in types for Date and Uint8Array, however these may possibly be deprecated in future in favor of Transform codecs.

Hope this helps
S

**Comment by sinclairzx81** [comment]
@hansSchall Heya,

Will close off this issue as Map and Set are generally considered to be out of scope.

All the best
S
