### ISSUE TITLE
Having trouble narrowing type with Array.filter

### ISSUE THREAD

**Issue by eloyrobillard** [sinclairzx81/typebox#719]
Hello,

When trying to narrow an array type by using `.filter` with `Type.Check`, I ran into a couple issues.

Stackblitz: https://stackblitz.com/edit/typescript-sxx5rp?file=index.ts

### First Bug

In the first case, the type does not get inferred and remains `any[]` even after filtering:

``` ts
const foos: any[] = [0, 1, 2];

const Foo = TypeCompiler.Compile(Type.Number());

const nums = foos.filter(foo => Foo.Check(foo)); // any[]
```

This could just be an issue with TypeScript.

### Second Bug

On the other hand, the type of `result` is correctly inferred as `number[]` if I change the last line to the following:

```
const nums2 = foos.filter(Foo.Check); // number[]
```

But I get the following error:

```
TypeError: Cannot read properties of undefined (reading 'checkFunc')
    at Check (webpack-internal:///(rsc)/./node_modules/@sinclair/typebox/build/import/compiler/compiler.mjs:59:21)
    at Array.filter (<anonymous>)
    ...
```

The problem could be that filter also passes index and array to `Check`, not just the element `foo`.

### Expected behavior

- `.filter(foo => Foo.Check(foo))` should correctly infer the type
- `.filter(Foo.Check)` should not produce an error

**Comment by sinclairzx81** [comment]
@eloyrobillard Hi,

### First Bug

I think this is normal TypeScript behavior. Consider the following (without TypeBox) where there is an explicit guard for number types only, however the return value is inferred as `any[]`.

```typescript
const foos: any[] = [0, 1, 2];

const bars = foos.filter(foo => typeof foo === 'number') // any[]
```
However when passing a function, I believe TypeScript is able to correctly derive the return guard via [Instantiation Expression](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#instantiation-expressions). However it might be good to ping this question on the TypeScript repository (as this behavior is specific to TypeScript)

```typescript
const foos: any[] = [0, 1, 2];

const check = (value: number): value is number => typeof value === 'number'

const nums = foos.filter(check) // number[]
```

### Second Bug

The compiled `TypeCheck<T>` is a an object type with internal fields that are accessed via `this`. As such, you won't be able to pass the `Foo.Check` function directly as the `this` context would be lost (which causes the error). However it is possible to `.bind` to ensure the context is retained. The following should work.

```typescript
const foos: any[] = [0, 1, 2];

const Foo = TypeCompiler.Compile(Type.Number());

const nums = foos.filter(Foo.Check.bind(Foo)); // number[]
```
The above is a little awkward, but is standard JavaScript. 

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@eloyrobillard Hiya,

Going to close off this issue as this all appears to be standard (albeit interesting) Ts/Js behaviors.

Feel free to reply on this thread if you have any follow up questions though. 
Cheers!
S

**Comment by eloyrobillard** [comment]
Thank you for the detailed reply.
