### ISSUE TITLE
Upgrade typebox deps - TypeClone method name changed

### ISSUE THREAD

**Issue by wenerme** [sinclairzx81/typebox#721]
- Old TypeClone.{Type,Clone}
- New TypeClone.{CloneType,CloneRest} ?

**Comment by sinclairzx81** [comment]
@wenerme Hiya

This was updated on 0.32.0. The TypeClone namespace has been retired, and the new imports are

```typescript
import { CloneType, CloneRest } from '@sinclair/typebox'
```
Note, the TypeBox clone functions are somewhat private (in that they were not specifically documented (and still don't have proper documentation for them)), but if you were using the `TypeClone` previously, you can update to use `CloneType` and `CloneRest` respectively on TypeBox 0.32.x.

Hope this helps!
S
