### ISSUE TITLE
JsonTypeBuilder#Record not passing on options

### ISSUE THREAD

**Issue by gregerolsson** [sinclairzx81/typebox#739]
Options object passed to JsonTypeBuilder#Record [is not passed on to free Record function](https://github.com/sinclairzx81/typebox/blob/master/src/type/type/json.ts#L276)

This prevents `[Kind]: "Record"` types from having `$id`, `title`, and so on.

I can make a PR if you prefer, but since its just a 1-liner fix perhaps it can be sorted while you're doing other changes.

Oh, and thanks for a fantastic library ❤️

**Comment by sinclairzx81** [comment]
@gregerolsson Hi,

Thanks for reporting! Have published a fix on 0.32.12 and written option assignment tests to try and catch missed option passing in future (during refactors, forgetting to pass in the options when refactoring has been a common oversight, they're easy to forget!)

All the best!
S
