### ISSUE TITLE
A `TObject` With No/Optional-only Properties Has Invalid Static Type

### ISSUE THREAD

**Issue by SirDavidLudwig** [sinclairzx81/typebox#74]
I've come across an issue which I believe to be a bug in TypeBox (version `0.16.5`) where a variable declared as a `TObject`, containing either all optional properties or no properties at all, becomes a top type that is assignable to anything except for `undefined|null`. I've provided a simple example below to demonstrate the issue. Is this type of behavior intended?

```ts
import { Static, Type } from "@sinclair/typebox";

let Test = Type.Object({
    key: Type.Optional(Type.Number()) // 
});

type TestType = Static<typeof Test>;

// Passes, but I don't believe it should...
let test: TestType = "this works";
```

**Comment by sinclairzx81** [comment]
@SirDavidLudwig Hi. Good spotting. This looks like a quirk of TS type inference. If you expand `TestType` it produces the following intersection type.

```typescript
type TestType = {} & {} & { key?: number | undefined; } & {}
```
> This intersection maps to `readonly optional`, `readonly`, `optional` and `required` properties respectively specified on `Type.Object({...})`.

So, If you define this type explicitly then it will assert as you expect. Oddly TS may just be naively reducing the above to just `{}` in inference cases for optimization reasons (I'm guessing here) and the Language Service isn't. But if this was the case, it would give the behavior of the [following](https://www.typescriptlang.org/play?strict=true&ts=4.3.0-beta#code/C4TwDgpgBAGlC8UDeBfAsAKEwYwPYDsBnYKADwC5YEoBGKAenqmAAsBLQqDqXAa0wFYMQA) (which works even in strict)

```typescript
type X = {}

const x: X = 1 // this is ok
```
I have published a possible fix on `0.16.6` that explicitly reduces the modifier intersections down (at the cost of introducing an extra level of depth resolving object types). This fix is based on the above reasoning above that TS has some sort of optimization going on.

If all is working your side, can close this one off.
Cheers!

**Comment by SirDavidLudwig** [comment]
Yeah, seems to work great on my end now. I appreciate the quick fix!

**Comment by sinclairzx81** [comment]
Thanks for letting me know. Will close this one off.

Cheers!
S
