### ISSUE TITLE
[Feature Request?] allow more flexible input for string pattern

### ISSUE THREAD

**Issue by sabercoy** [sinclairzx81/typebox#746]
I would like to define a pattern that is a regex that ignores case
```typescript
const test = Type.Object({
  email: Type.String({
    pattern: /^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i
  })
})
```
but pattern expects a string, and there is no way to express this regex as a string (that I know of) that can specify to ignore case.
The implementation seems to be to take the pattern and wrap it in new RegExp, but what this does is wrap the string with slashes, so there is no way to get the "i" at the end.

So could pattern allow a type that would make this possible?

**Comment by sinclairzx81** [comment]
@sabercoy Hi, Try the RegExp type.

```typescript
const test = Type.Object({
  email: Type.RegExp(/^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i)
})
```
Just note that the string `pattern` is limited to the ECMA 262 subset supported by Json Schema while the RegExp type offers full UTF-16 + flags support (but comes at a cost of not being compliant with Json Schema)

Hope this helps
S

**Comment by sabercoy** [comment]
> Hi, Try the RegExp type.

Wow I didn't even think to use Type.RegExp in there. It looks like this works.
I see, the pattern should be compliant with that standard, that's understandable.

THANKS SO MUCH! I love the project.

**Comment by sinclairzx81** [comment]
@sabercoy All good :)

Will close off this issue for now
All the best!
S
