### ISSUE TITLE
TUnion of literals from const array

### ISSUE THREAD

**Issue by ehaynes99** [sinclairzx81/typebox#751]
I've been trying -- unsuccessfully -- to come up with a function to create a `TUnion` using a const array (or a TS 5.x "const parameter" like  `<const T extends ReadonlyArray<string | number | boolean>>`). E.g.

```typescript
const values = ['first', 'second', 'third'] as const

// equivalent to:
// const AsTUnion: TUnion<[TLiteral<"first">, TLiteral<"second">, TLiteral<"third">]>
const AsTUnion = Type.Union([Type.Literal('first'), Type.Literal('second'), Type.Literal('third')])
```

I thought it would be straightforward:
```typescript
export type UnionValues<T extends ReadonlyArray<string | number | boolean>> = {
  [K in keyof T]: TLiteral<T[K]>
}

// inferred as:
// type Tmp = readonly [TLiteral<"first">, TLiteral<"second">, TLiteral<"third">]
type Tmp = UnionValues<typeof values>
```
However, this doesn't satisfy the generics for `TUnion`
```typescript
const LiteralUnion = <const T extends ReadonlyArray<string | number | boolean>>(
  values: T,
// typescript: Type 'UnionValues<T>' does not satisfy the constraint 'TSchema[]'. [2344]
): TUnion<UnionValues<T>> => // ...
```

I tried approaching from the other direction:
```typescript
// inferred as:
// type Tmp2 = TLiteral<"first" | "second" | "third">
type Tmp2 = TLiteral<(typeof values)[number]>
```
But would have to use an unsafe type to actually create it, e.g.:
```typescript
const LiteralUnion = <const T extends ReadonlyArray<string | number | boolean>>(values: T): TLiteral<T[number]> => {
  return Type.Unsafe<T[number]>(Type.Union(values.map((str) => Type.Literal(str)))) as any
}

// const Example: TLiteral<"first" | "second" | "third">
const Example = LiteralUnion(values)
// type Example = "first" | "second" | "third"
type Example = Static<typeof Example>
```

This works, but feels rather ugly, as TypeBox doesn't really have a native equivalent. Any ideas?

**Comment by sinclairzx81** [comment]
@ehaynes99 Hi, try the following

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUFUB2wE+OyAMsDBlAIYA2cAvnAGZQQhwDkAAgM7B8AYzo1gUAPQx0GAEYQAHlwBQyjAsiw40zCgpVadAkXwAeZHHVV8AEz5w+MKIIDmAbQC6OAIJChlhWs7PUpqek84AF44TwA+KLhlOBQAoPs3QRZqODJUjFt7R2d8FxwAOgrM7IAlPIKHJ1dPDyTkuAB+EIN6Y2JTapw3CrLfIVJ9MLpTMliPWNbkgC48Qj7R+eUWAFdhGBMc0MNeswsrfOCiprmACgA3ei2MPmWoDBobYjpUGOHkDwBKZbkQ49VYneIIVqvGBbKD4FAyMrHO4PJ5lEA0MAouiPKLxNCYMoTQzYx7-clwGj2fAYW7UZSMVQSCRwYaqITERxwABqCTcXBY4kcXBwXD4GA5thF3BgAAtxDYuB5KfZJY52Zz4BZosTQSZrtz-qogA)

```typescript
import { Type, TUnion, TLiteral } from '@sinclair/typebox'

export type TLiteralUnion<T extends string[], Acc extends TLiteral[] = []> = 
  T extends [infer L extends string, ...infer R extends string[]]
    ? TLiteralUnion<R, [...Acc, TLiteral<L>]>
    : TUnion<Acc>

function LiteralUnion<T extends string[]>(values: readonly [...T]): TLiteralUnion<T> {
  return Type.Union(values.map(value => Type.Literal(value))) as never
}

// ...

const V = ['first', 'second', 'third'] as const

const T = LiteralUnion(V)
```
Hope this helps
S
