### ISSUE TITLE
Tuple with rest items (or Array with prefixedItems)

### ISSUE THREAD

**Issue by alexey13** [sinclairzx81/typebox#756]
Good day @sinclairzx81!

Question about tuple with rest items.

```ts
type T = ['me', 'you', ...string[]];
```

Made some research, its possible in json-schema with help of prefixItems and items [https://json-schema.org/understanding-json-schema/reference/array#id7](https://json-schema.org/understanding-json-schema/reference/array#id7) but not possible currently in typebox, right?

Thanks a lot!

**Comment by sinclairzx81** [comment]
@alexey13 Hi!

Unfortunately, TypeBox doesn't support this type currently as it's tied to the Draft-7 specification for Tuple representation (which is the default for Ajv). However, you can still implement this type manually....

There's a couple of ways you can approach this. Either using Type.Unsafe (using Ajv as your validator), or registering a new type with the TypeRegistry.

---

### Ajv + Unsafe Type

The following implements this type using Unsafe. To use this type, you will need to configure Ajv for draft 2020-12. This is generally the quickest way to get the type working.

Documentation on configuring Ajv for Draft 2012-12 can be found [here](https://ajv.js.org/json-schema.html#draft-2020-12)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsriQBYYgFwC+cAZlBCHAOQACAzsADsSAGwLAoAehjoMAIwgAPTgChlGBZFhxpmFAFcwwjACUMvGPiKkAPMjjqYGAQBNeKSjToBtALo5T5vYKji5uFNS0BDgAgiQkQSGucHoCANYCEADuAr5wALxwvgB8+XDKcBUoCU5JXoLMGFBwADLVoe4RdDgAdL31jXDGbUnhngS+PuWVFQD8+oYmZhaExCTWxv5LOF693bFkeCs2zUU+RVPTAFyFu-s9vZar60tFE6rqmvAkEAKByAZGALwAq2YZhDyRXybQIOGrgzoEIoACmAjhAvGuO16yD8cCgS2uQIAlPkSlM0JhugBVX4EBq2AGLcyPGzIaEwIrIhAXbQya6cAhQKAEVCcLA8sD45jABQASTRGLgqNovHF0xSGAAbgRhHoiBhnPKVdd8eYpgwiaplN9fvA7AV-gsgUivBSMN18FBBABzJFE8gyboAOT0IFkjT9uLd3QAQhAIEYCAI-ZblDoMFUCiy1umIMwUCUJBJCuYvQJvTgBKHw1B7t15AmMEm3kA)

```typescript
import { Type, Static, TSchema } from '@sinclair/typebox'

export type TupleRestStatic<T extends TSchema[], Rest extends TSchema, Acc extends unknown[] = []> = 
    T extends [infer L extends TSchema, ...infer R extends TSchema[]]
      ? TupleRestStatic<R, Rest, [...Acc, Static<L>]>
      : [...Acc, ...Static<Rest>[]]

export const TupleRest = <T extends TSchema[], Rest extends TSchema>(items: [...T], rest: Rest) => 
  Type.Unsafe<TupleRestStatic<T, Rest>>({
    type: 'array',
    prefixItems: items,
    unevaluatedItems: rest
  })


const T = TupleRest([Type.String(), Type.Number()], Type.Boolean())

type T = Static<typeof T> // [string, number, ...boolean[]]
```
---

### TypeRegistry

The following implements the same type using the TypeBox TypeRegistry. This approach will require you to manually implement the check logic for the type.

```typescript
import { Type, Static, TSchema, TypeRegistry, Kind } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// --------------------------------------------------------------------
// TupleRest
// --------------------------------------------------------------------
TypeRegistry.Set<TTupleRest>('TupleRest', (schema, value) => {
  return (
    Array.isArray(value) && value.length >= schema.prefixItems.length &&
    schema.prefixItems.every((schema, index) => Value.Check(schema, value[index])) &&
    value.every((value, index) => index < schema.prefixItems.length || Value.Check(schema.unevaluatedItems, value))
  )
})
export type TupleRestStatic<T extends TSchema[], Rest extends TSchema, Acc extends unknown[] = []> = 
    T extends [infer L extends TSchema, ...infer R extends TSchema[]]
      ? TupleRestStatic<R, Rest, [...Acc, Static<L>]>
      : [...Acc, ...Static<Rest>[]]

export interface TTupleRest<T extends TSchema[] = [], Rest extends TSchema = TSchema> extends TSchema {
  [Kind]: 'TupleRest'
  static: TupleRestStatic<T, Rest>
  type: 'array'
  prefixItems: T
  unevaluatedItems: Rest
}
export function TupleRest<T extends TSchema[], Rest extends TSchema>(prefixItems: [...T], unevaluatedItems: Rest): TTupleRest<T, Rest> {
  return { [Kind]: 'TupleRest', type: 'array', prefixItems, unevaluatedItems } as never
}

// ... 

const T = TupleRest([Type.String(), Type.Number()], Type.Boolean())

type T = Static<typeof T> // [string, number, ...boolean[]]

const R = Value.Check(T, ['', 1, true, true, true]) // true
```
---
I'll make a note to implement an overload for the Rest parameter on `Type.Tuple` once TypeBox transitions over to Draft 2020-12. But for now, the above approach is the current best option for representing this type.

Let me know if this helps
Cheers
S

**Comment by alexey13** [comment]
Thank you very much! 
Will use TypeRegistry example, its awesome!
