### ISSUE TITLE
Support for self-referencing fields of recursive type

### ISSUE THREAD

**Issue by lithdew** [sinclairzx81/typebox#761]
I have this schema:

```ts
const Program = T.Recursive(
  (This) =>
    T.Object({
      accounts: T.Record(
        T.String(),
        T.Union([T.String(), T.Object({ ref: T.KeyOf(T.Index(This, ["accounts"])) })])
      ),
    }),
  { $id: "Program" }
);

type TProgram = Static<typeof Program>;
```

`TProgram` resolves to:

```ts
type TProgram = {
    accounts: {
        [x: string]: string | {
            ref: never;
        };
}
```

Is there any way to make this schema such that the following instance of this schema is valid?

```ts
const TEST = {
  accounts: {
    programId: "5XDdQrpNCD89LtrXDBk5qy4v1BW1zRCPyizTahpxDTcZ",
    testId: { ref: "programId" },
  },
} satisfies TProgram;
```

**Comment by sinclairzx81** [comment]
@lithdew Hi,

Self referential recursive + indexed types are currently not supported by TypeBox.....however you can try implement this type other ways. For example, the following extracts the `accounts` property out into it's own type, this avoids the need to self reference via Type.Index.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwIYGcUA0cAyjNjMAMZwC+cAZlBCHAOQACuwAdpQDbZgUAPQx0GAEYQAHqwBQcsZhQBBSpQgBXbjHwBeEmQqUAPEowR6cNRu26AfHI3dc8G1p36UAOgBKGSk0oLgA3DAAKZAALYH17H38NKAATcLk4DJ9SKB4Ac3CASiJ0zORvAFVuYAhucIBtMuy8wqIygHkJACsAmHCEEsy4KAx6AC4UGNwB2gKSgF0CosQ4ABJgZPHWdztcVhmFcxQABSZcqGwWA1JyKjNxSzgTiDOLx2dXR9Pzy58O7spev1Bth1B5dONtp45DRZgp6NoAdVuHAYBhXOEQtg+JoMONkE8XiACohpu94CDbDoAIxwAyY7EYbwUsG4OqsZl2KmsObTYD0cLmB4c6m0vQGViuHLcXKsYnDGBBZHCYRwYC5bjQDDTUk1D7CmAAJlpOFBnO8w3obP1Bu5vP5gqs1tF4sleVlQwwCqgSpVao1wwUg2VcG8oZw3GScFwEDgNWhCiAA)

```typescript
import { Type as T, Static } from '@sinclair/typebox'

type TAccounts = Static<typeof Accounts>
const Accounts = T.Recursive(This => T.Record(
    T.String(), 
    T.Union([T.String(), T.Object({
      ref: This
    })
  ])), { $id: 'Accounts' })

type TProgram = Static<typeof Program>
const Program = T.Object({
    accounts: Accounts
})


function test(value: TProgram) {
    const account1 = value.accounts['account1']
    if(typeof account1 === 'string') return // ignore
    
    const account2 = account1.ref['account2']
    if(typeof account2 === 'string') return // ignore

    // ... and so on
}
```
Hope this helps
S

**Comment by sinclairzx81** [comment]
@lithdew Hey, might close of this issue as self referential recursive indexing is generally supported (and it may not be supported in future given the way recursive types are constructed). However, you should be able to use the workaround above to represent this type.

Hope this helps.
Cheers!
S
