### ISSUE TITLE
TTuple is not exported

### ISSUE THREAD

**Issue by peternedap** [sinclairzx81/typebox#8]
I've run into [this](https://github.com/microsoft/TypeScript/issues/5711) problem when using `Type.Tuple()` with this minimal example:

```typescript
import { Type } from '@sinclair/typebox';

export const schema = Type.Tuple({});
```

The normal solution is providing a type definition to `schema`, but the main reason I'm using typebox is because types can be inferred. 

Another solution would be exporting `TTuple1` ... `TTuple8` in `typebox.d.ts`.

**Comment by sinclairzx81** [comment]
Hi, Have pushed a update to npm `@sinclair/typebox@0.9.6` which exports all the generic variants see [diff](https://github.com/sinclairzx81/typebox/commit/ff8a1cc77a205565087f37813b990e1b67962d68)

If you're having problems with the inference tho, just double check you're using an up to date version of the TypeScript compiler (TypeBox was built against TS `3.8.3`) and older versions of the compiler are not supported. Also double check your `Tuple.Type()` type.

```typescript
import { Type, Static } from '@sinclair/typebox';

// const schema = Type.Tuple({}); // Type.Tuple doesn't take {}

const schema = Type.Tuple(Type.String(), Type.Number())

type T = Static<typeof schema> // T = [string, number]
```
Let me know how you go.

**Comment by sinclairzx81** [comment]
Just on the `Type.Tuple(...)` signature above. It has been changed in `0.9.7`. See [here](https://github.com/sinclairzx81/typebox/issues/9#issuecomment-596054508) for more information.

**Comment by sinclairzx81** [comment]
Will close of this Issue as all TypeBox's internal type representations are now exported. Many Thanks.
