### ISSUE TITLE
Type.Schema

### ISSUE THREAD

**Issue by pterrien** [sinclairzx81/typebox#802]
Hello,

I'm trying to validate data that must contain a TypeBox schema property: in my case, these are plugin definitions, that must provide a schema to validate their config file against. Something we could translate to TS like this:
```typescript
interface IPlugin {
	config: TSchema
}
```

I couldn't find anything like a `Type.Schema`, could you kindly guide me on the best way to implement it?
Additionally, would it be possible to restrict the type of schema? In my case the corresponding TS type would be `TObject` obviously.

At this time, my best bet is to implement a schema that would cope with the `TSchema` (or `TObject`) definition defined in your code:
```typescript
export interface TSchema extends TKind, SchemaOptions {
  [ReadonlyKind]?: string
  [OptionalKind]?: string
  [Hint]?: string
  params: unknown[]
  static: unknown
}
```

Thanks in  advance for your help.

**Comment by sinclairzx81** [comment]
@pterrien Hi,

There's a few of ways to approach this, most of which comes down to how you want your plugin API to look, and how types contribute to inference elsewhere. Perhaps the following helps?

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsriQBYYgHkDyARgFYYnwC+cAZlBCDgByAAIBnYADsSAGwLAoAehjoMTCAA8hAKG2LFcYDzioIAVzgB3ApPgE4YzCWAEZwAF4YAJnAit28CqY2hgakLCGthhQPAQkGCgACjJmAOZSADwAwhCSPMCpcKEwGJJeYiiUNHQAfEUaJWUVyMxsHBlIJLn5qQBccDl5BXCcdUicuvpwMFTAFXNw9rEc0Ki8ZtLEubzQ0zTTqovqAG4YIWHQ8DwbHMDbyWmZgz31jeWV1LQENQAUXUN9AbdAoASn6yAe6Uk2WBqTG2jgcCgGBgZigkhQqgAdK0Aj9OrCRiDtBM9AYAIKLMpwABCi2RB0wFQgxghKSh2n+YnglIAvHBIVIfmhMDj-Bx8XANODsQA5MwgJjRH4gnCoGWi+WK5UgonEzm5bm0uD8wWSYXY3ESpAEDUYLH4KBSVIqnBMO0OmBOyQu3WcEH6oIJPl4QjEEgZIMsuDkmq6IPG-n4IikSOqaM0uNAA)

```typescript
import { Type, Static, TSchema, TObject } from '@sinclair/typebox'

// if you want a specialized object type
export interface TPlugin<Config extends TSchema> extends TObject<{ config: Config }> { }

// this is a factory function for the type above
export function Plugin<Config extends TSchema>(config: Config): TPlugin<Config> {
  return Type.Object({ config })
}

// A and B are types of TPlugin
const A = Plugin(Type.Object({ x: Type.Number(), y: Type.Number() }))

const B = Plugin(Type.Object({ a: Type.String(), b: Type.String() }))

type A = Static<typeof A>

type B = Static<typeof B>

```
> Additionally, would it be possible to restrict the type of schema? In my case the corresponding TS type would be TObject obviously.

You can constrain the generic `Config` parameter to be of `TObject` only in the following way.

[TypeScript Link Here](https://www.typescriptlang.org/play?ssl=9&ssc=132&pln=1&pc=1#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUHkBGAVhgMbwC+cAZlBCHAOQACAzsAHYkA2AhsFAHoY6DPggAPBgCgpGcZFhwOMDFCo8SGFAAUuAVwDmHADwBhCOyrADcOSvYATFniKkYAPlvj7Tl8TLGSCQWVgYAXHDmltZw5J5I5DJyCvBUepwwwBZwuoYmUaFePs7IBP4eABTB0eGRIdYAlBHIuUbsZvUG8VJwcFAYMHpQ7CgiAHRlbhVBnbENUolS1SzwABpwALw5+m0VaJhjAMowUBwGFQ0NcAICtlC0UBEAglAGeiAY7PAQVHDCmIxkMdTuwDAwlM52BB4DwWGwDOwePguFoYBA4GAeFAeB8VFA4D8-iJAZMAi1aJhYMAMCx3AwxjIgA)

```typescript
import { Type, TObject } from '@sinclair/typebox'

export interface TPlugin<Config extends TObject> extends TObject<{ config: Config }> { }

export function Plugin<Config extends TObject>(config: Config): TPlugin<Config> {
  return Type.Object({ config })
}

const X = Plugin(Type.String()) // error: Argument of type 'TString' is not assignable to parameter of type 'TObject<TProperties>'.
```
Hope this helps!
S

**Comment by pterrien** [comment]
Once again, thank you for your super quick answer, the level of support on this repo is truly amazing. :)
That's a very straightforward and elegant solution indeed.

Many thanks, that really helps!
