### ISSUE TITLE
null passes validation

### ISSUE THREAD

**Issue by asansyzb** [sinclairzx81/typebox#81]
Hi! Passing null to fields Type.String(), Type.Integer() or Type.Number() passes ajv validation on fastify.

Not sure how to fix it.

```
export const TBody = Type.Object({
    phoneNumber: Type.String(),
    timestampt: Type.Integer()
});
```

`body: TBody
`
and POST request with
```
{
    phoneNumber: null,
    timestamp: null
}
```

**Comment by sinclairzx81** [comment]
@asansyzb Hi. The JSON schema for `TBody` is the following (which you can inspect by calling `console.log(TBody)`. Your schema disallows passing `null` for `phoneNumber` and `timestamp`.

```typescript
const TBody = {
  type: 'object',
  properties: { 
    phoneNumber: { type: 'string' }, 
    timestamp: { type: 'integer' } 
  },
  required: [ 'phoneNumber', 'timestamp' ]
}
```
I've quickly tested locally and passing `null` for either `phoneNumber` or `timestamp` will have AJV report `data/phoneNumber must be string` and `data/timestamp must be string` errors on validation. So this is likely something going on with Fastify.

Would you be able to submit this issue to the Fastify repository? Feel free to link back to this issue if its helpful.

Cheers
S

**Comment by sinclairzx81** [comment]
@asansyzb Will close off this issue as TypeBox should be working as expected. 

Cheers!
S
