### ISSUE TITLE
Type.Object should turn additionalProperties to off by default

### ISSUE THREAD

**Issue by adrian-kriegel** [sinclairzx81/typebox#82]
I think in most cases you would NOT want `additionalProperties` to be `true` (or omitted).  I don't believe that there are many use cases that require `additionalProperties` to be true. In case you need it, you could still pass `{ additionalProperties: false }` in the options. Since the conversion from Types to JSONSchema is not well-defined it may make sense to allow the user to configure these kinds of details themselves using a global config object.

**Comment by sinclairzx81** [comment]
@adrian-kriegel  Hi! Thanks for bringing this up, I've been hoping someone would raise this.

I do actually agree with you here. TypeBox `0.16.x` actually set `additionalProperties: false` by default (as I also believe this to be expected from the end user), unfortunately, this had led to quite a few unforeseen JSON schema related composition issues downstream (particularly around type intersection), and I've unfortunately had to revert this back on `0.17.x`.

The main issue with having TypeBox set constraints like `additionalProperties` is that it goes against the design principles of JSON schema. That is to say "Schemas constraints are only additive, never subtractive". In the `Type.Intersect(...)` case, in order for TypeBox to compose two intersected schemas, it would first need to clone the original schemas, remove their `additionalProperties: false` constraints and use these new permissive schemas for the composition. The end result of that is you wind up with two schemas, (the original with `additionalProperties: false` and the other with `additionalProperties: true`). It also adds some ambiguity with respect to how TypeBox should reconcile varying `additionalProperties` as well as introducing an extraordinary amount complexity to make this all work. It was really this that prompted the revert back.

I should note however, the current `Type.Intersect(...)` method is just mashing two schemas together manually and is limited to intersecting on `Type.Object()` types only. (an unfortunate consequence of the `0.16.x` change), however in future revisions of TypeBox, `Type.Intersect(...)` may be expressed with `allOf` and constrained with `unevaluatedProperties`. This is inline with JSON schema draft `2019-9` [link](https://github.com/json-schema-org/json-schema-spec/issues/556). But to allow for this, TypeBox must mandate that users be explicit about constraints, and be mindful that applying constraints do have a implication on schema composition.

I actually had a lengthy discussion around this topic a few months back with one of the json schema spec engineers that you can read about [here](https://github.com/json-schema-org/json-schema-spec/issues/1087). It goes into some depth but should provide additional rationales for the `0.17.x` revert.

I hope this sheds a little bit of light on things, happy to discuss more, so will leave this issue open for a few days.

Cheers
S

**Comment by sinclairzx81** [comment]
Will close off this issue as applying default constraints to TypeBox types (as convenient as that is) will break planned schema composition in later releases.

Many Thanks
S

**Comment by adrian-kriegel** [comment]
@sinclairzx81 I was just wondering about the Intersect issue. What's the problem with using something like

```typescript
// allow additional properties if all items allow it
const additionalProperties = items.reduce<boolean>(
    (acc, { additionalProperties }) => (acc = acc && (additionalProperties !== false)),
     true,
);
```
in the current implementation? Wouldn't that behave like an intersect type in TS?

**Comment by sinclairzx81** [comment]
@adrian-kriegel Hey. Yeah, had considered that. The decision to omit `additionalProperties` in `0.17.x` really had more to do with keeping TypeBox in tune with JSON schema design principles (where applying constraints like `additionalProperties` effectively locks a schema and forbids intersection). So applying `additionalProperties: false` by default might be considered surprising behavior if you're looking at TypeBox from the JSONschema perspective.

In saying this tho, `additionalProperties: false` is actually closer to TypeScript than you might think. Consider the following. Playground link [here](https://www.typescriptlang.org/play?ssl=5&ssc=1&pln=4&pc=2#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyycAXMiAK4C2ARtADQFE1mW3QEC+BBMFICMMHQhkkAM5gAFDExkM6AJQ4e+bvgIB6TcgC0+g4aPGTpg1p0QAHnCoAHADYQy6ANYW9Zr99OqEIyWQAEzgwOGQAXhxSZABGAAZ6ZBZkACZE5AQyBPjkTmRtTORgcWIgoOAhETgHVQlpELDFVUKfNvaPa1tHZ2SKMGLwaAhJUABzBwBPD3bZrzqR6WwYhKSU9KSsuNzOZUKwAAsS5HhgB3EgA)

```typescript
interface Foo {
  a: number,
  b: number
}

function test(foo: Foo) {

}

// ---------------------------------------
// example: ok
// ---------------------------------------

const data = {a: 10, b: 20, c: 100 } // c is additional

test(data)

// ---------------------------------------
// example: fail
// ---------------------------------------

test({a: 10, b: 20, c: 10 }) // this fails
```
This is actually consistent with construction being strict and assignment being polymorphic (which is permissive) rule. And also happens to align with `additionalProperties: false`, so there is actually parity between JSON schema and TypeScript in this regard (it's just a little hard to spot given the different contexts).

Also, I need to keep `additionalProperties: false` if I want to take advantage of `unevaluatedProperties` in future. So for example, the following is how intersections will work with `unevaluatedProperties`.

```typescript
const A = Type.Object({ a: Type.String() })

const B = Type.Object({ b: Type.String() })

const C = Type.Intersect([ A, B ], { unevaluatedProperties: false })

// which translates into

const A = { type: 'object', properties: { a: { type: 'string' } } }  // permissive

const B = { type: 'object', properties: { b: { type: 'string' } } } // permissive

const C = {
    unevaluatedProperties: false,
    allOf: [A, B]
}
```
Note that the `unevaluatedProperties` implementation is pending until I've had a chance to review validators outside of AJV and JSON.NET Schema. I note that in the AJV case, you need to opt into using `unevaluatedProperties` by pulling in the `2019-9` spec. And that will break implementations currently using `Type.Intersect(...)`. I've actually been waiting to see if this remains the case in future. TypeBox advertises itself as being JSON Schema 6 compatible, so I've been between a rock and a hard place making the decision when to start leveraging `unevaluatedProperties`. But it will happen eventually :D

Hope that brings a little more insight!
Thanks again mate
