### ISSUE TITLE
Should coerce type to array

### ISSUE THREAD

**Issue by woody146** [sinclairzx81/typebox#823]
Current
```ts
Value.Convert(Type.Object({
    a: Type.Array(Type.String()),
  }), {a: 'string'} )
=> {a: 'string'}
```

Should be (like [ajv](https://github.com/fastify/ajv-compiler?tab=readme-ov-file#ajv-configuration) with `coerceTypes: 'array'`)
```ts
Value.Convert(Type.Object({
    a: Type.Array(Type.String()),
  }), {a: string'} )
=> {a: ['string']}
```

In api with get method, client sends field `a` with array type but only one element such as `/api/?a=string`
After converting, server receives `{a: 'string'}`, but it should be `{a: ['string']}`

**Comment by sinclairzx81** [comment]
@woody146 Hi, thanks for the suggestion.

Let me have a think about this. The current convert logic was based on the idea that primitive types (string, number and boolean) should be coerce-able in some form or another, but structural types (array and object) should not as invariance between structural types and primitives types may be lost (although this is more of a guiding principal hoping to simplify the rules of conversion)...the `coerceTypes: 'array'` was considered however.

I think in the case of `/api/?a=string`, one would naturally express this as `{ a: string }` (and where expressing it as `{ a: string[] }` would only obfuscate the receiving type / value (this is largely framework dependent concerns outside of TypeBox). But can you think of any other cases were you would want `coerceTypes: 'array'` ?

I'll leave this issue open for further discussion
Cheers!
S
