### ISSUE TITLE
[question] Creating schemas from interfaces

### ISSUE THREAD

**Issue by simoneromano96** [sinclairzx81/typebox#83]
Hello, I currently have a codebase that exposes a number of big typescript interfaces from a library (so I cannot edit them) and would like to convert them to schemas without duplicating the already existing code with the risk of having a disarray with the library.

Is there any way to do it? Would it even be possible?

Example interface: 
```ts
import { Type } from "@sinclair/typebox"

interface IUser {
    member_id: number;
    member_group_id: number;
    name: string;
}

// What I would like to do
const User2 = Type.Object<IUser>()
```

**Comment by sinclairzx81** [comment]
@simoneromano96 Hi, Unfortunately not possible. TypeScript type information vanishes at compile time, so there is no information available for TypeBox to construct the JSON schema at runtime.

The best you could do is the following, but would require porting all your existing types to TypeBox (which doesn't sound feasible in your case)

```typescript
import { Type, Static } from "@sinclair/typebox"

type IUser = Static<typeof IUser>
const IUser = Type.Object({ 
    member_id:       Type.Number(),
    member_group_id: Type.Number(),
    name:            Type.String()
})

console.log(IUser) // prints the schema for IUser

function test(user: IUser) { // treats IUser as a type
   // test user properties here
}
```
There are tools available however, maybe try https://github.com/YousefED/typescript-json-schema which should generate JSON schema from existing TypeScript types. I believe it uses the compiler API to to read out `interface` and `type` information and outputs JSON schema as a separate file.

Hope this helps!
S

**Comment by sinclairzx81** [comment]
Will close off this issue

Good Luck mate! Hope you find a good solution :)
S

**Comment by markusjohnsson** [comment]
Yes, the types vanishes at compile time, but with a tool that takes the TypeScript sources it would be possible. 

Aside: A while ago I was playing around with the idea of running TypeScript (that is, the compiler) on JSON objects for validation, at runtime, in my application. Then I had runtime type checking on data posted from to my service, based on my original (plain TypeScript) types. It worked, but performance was quite lousy. Perhaps it could be sped up somehow by utilising incremental compilation and such.
