### ISSUE TITLE
Utility type inference appears missing or broken

### ISSUE THREAD

**Issue by Xhale1** [sinclairzx81/typebox#834]
Hello hello! Fantastic library, I've been following this project for a while!

Not entirely sure if this is a bug or intended behavior. Using the `Pick` example from the docs:
```ts
const T = Type.Pick(
  Type.Object({
    x: Type.Number(),
    y: Type.Number(),
  }),
  ['x'],
);
```
I would expect `['x']` to by typed in such a way that the keys of the object are inferred as accepting `'x' | 'y'`, allowing type hints on what keys can be picked. Instead, this array accepts any string value. The type appears to be `TMappedKey`.

I'm using TypeBox `0.32.20` and TypeScript `5.4.5`.

**Comment by sinclairzx81** [comment]
@Xhale1 Hiya,

Might close off this issue as things are working as per design here. 

I may revisit auto inference of pick-able properties again in later revisions if I can get the inference fast enough and avoid some of the generics / compositional issues when using Pick/Omit in mapping functions. I do appreciate it can provide a nicer DX, but I think for now, I'm opting to avoid any additional performance overhead and go with the current design until some of the other internal aspects on 0.32.x have stabilized. 

Again, hope this brings some insight.
All the best!
S
