### ISSUE TITLE
Add custom validation messages example to docs

### ISSUE THREAD

**Issue by johtso** [sinclairzx81/typebox#85]
Would it possibly be worth adding custom error messages to the validation example section of the documentation?

Something like this:
https://codesandbox.io/s/typebox-validation-with-error-messages-0ekq5?file=/src/index.ts
```ts
import { Type } from "@sinclair/typebox";
import addFormats from "ajv-formats";
import addErrors from "ajv-errors";
import Ajv from "ajv";

// Setup
const ajv = new Ajv({ allErrors: true });
addFormats(ajv, ["email", "time", "uri"])
  .addKeyword("kind")
  .addKeyword("modifier");
addErrors(ajv);

// TypeBox
const User = Type.Object(
  {
    name: Type.String(),
    email: Type.String({
      format: "email",
      errorMessage: { format: "${0#} must be a valid email address" }
    })
  },
  { errorMessage: { _: "default error" } }
);

const validate = ajv.compile(User);
// Validate
const isValid = validate({
  name: 1,
  email: "dave@@domain.com1"
});

console.log(isValid);
console.log(validate.errors);

```

**Comment by sinclairzx81** [comment]
@johtso Hi. Thanks for the suggestion. Um, maybe. I'm just a bit weary of adding AJV specific documentation to the TypeBox project (AJV has it's own documentation). The current example that's there now is mostly for convenience and just includes a minimum recommended setup that takes into account the `kind` and `modifier` keywords and the `string` formats that TypeBox keeps type information for. The setup of the `addFormats()` and `addKeyword()` was mostly in response to AJV 7 defaulting to `strict` mode (so the setup may have been non-obvious to new users not immediately familiar with JSON schema).

But with that said, im not adverse to documentation! :D The Validate section of the readme could use a bit of a clean up. I may add some note in there linking off to the AJV documentation (which might be better option than showing an implementation of one of its add-ons). Let me have a think about :)

Many Thanks!
S

**Comment by johtso** [comment]
Oh yeah, it was more just out of my experience as a new user trying to figure out _if_ typebox was something I could to define my form validation (as someone a bit unfamiliar with JSON Schema and AJV).

Now that I've gotten my head around it I understand that typebox just gives you a schema, and then you can do whatever you want with it (including giving it to other libraries that implement validation).. and then if you look at AJV you can see that with a little more tweaking you can get custom validation message. After figuring this out you then just need to realize that typebox lets you pass whatever options you want to your types and they end up in your schema.

So it's less about documenting how to use external libraries.. and about just having a working example showing how you could use typebox to define validation for a form.. and also get type definitions for free.

**Comment by sinclairzx81** [comment]
@johtso Hi, I have updated the AJV validation example to include a bit more information (and added an example to get started with type referencing). I've also included a link off to their website for more information. 

I think this information is fairly adequate (it should cover the everything required to start using TypeBox with AJV). For functionality specific to AJV (such as error formatting), that is probably best linked over to their documentation website.

Will close off this issue
Many Thanks!
S

**Comment by johtso** [comment]
Good stuff, thanks for all the work you're doing!

**Comment by Wilson13** [comment]
I agree with @johtso on the need for more information regarding AJV validation, especially on custom error messages.

Of course this library isn't just for used with AJV, but if there's considerably enough users that are using it with AJV, I think it'd be real nice to have either a specific section on the documentation, or just have a folder of example source code regarding this.

Thanks for this awesome work @sinclairzx81
