### ISSUE TITLE
Typescript doesn't suggests the props using Pick or Omit

### ISSUE THREAD

**Issue by yanmifeakeju** [sinclairzx81/typebox#874]
I've noticed that when using TypeScript in our project, the IDE doesn't suggest props when utilizing the Pick or Omit methods. I have a feeling that this functionality used to be available before. 

Any insights on why this feature is no longer working or if I may be mistaken about its previous availability

**Comment by sinclairzx81** [comment]
@yanmifeakeju Hi, sorry for the delay in reply.

TypeBox previously inferred Pick/Omit and Index property keys, however it was removed on 0.32.x as the inference required to obtain the keys was proving very expensive (as TB needed to either Static or derive keys during composition (which was a problem for very deeply nested / computed types)), also the exact property key values resulted in a few issues when using Pick/Omit/Index in generic functions (where keys are passed as generic arguments)

As of 0.32.0, TypeBox allows passing any keys, however you should check the return value of Omit/Pick and Index.

```typescript
import { Type } from '@sinclair/typebox'

const T = Type.Object({
  x: Type.Number(),
  y: Type.Number()
})

// As of 0.32.x...

const A = Type.Pick(T, ['z'])  // TObject<{}>

const B = Type.Omit(T, ['z'])  // TObject<{ a: TNumber, b: TNumber }>

const C = Type.Index(T, ['z']) // TNever
```

Hope this provides some insight into the change. Will close off this issue for now, but if you have any additional questions on the above, feel free to ping on this thread.

All the best
S

**Comment by artsiommiksiuk** [comment]
@sinclairzx81,
Can we have two versions of those methods? One with enabled inference and another one without? I have a use case, where the whole purpose of using TS + TypeBox to ensure that types are picked (in this case) correctly automatically.

it can be two versions for export by TypeBox: full vs optimized.

**Comment by dwickern** [comment]
I'm +1 for solving this in some way. It's much more verbose to write `Type.Omit(T, ['z'] satisfies ReadonlyArray<keyof T>)`, especially considering it worked in a previous release

**Comment by sinclairzx81** [comment]
@dwickern Hi,

> I'm +1 for solving this in some way. It's much more verbose to write Type.Omit(T, ['z'] satisfies ReadonlyArray<keyof T>), especially considering it worked in a previous release

It is technically possible to bring back, but I think it's correct for it not to infer the keys (or at least not to infer in a way that would prohibit non-applicable keys). Also note that TypeScript doesn't prohibit non-applicable keys from being used with Omit (or Pick)

```typescript
type T = { x: number, y: number, z: number }

type O = Omit<T, 'a' | 'b' | 'c'> // this is fine
```
I tend to lean towards the view that inference of possible keys may have been a mistake, as it implies that only those keys are possible parameters for Omit, but where the operation is actually "Omit LHS properties from those in the set of RHS", which places no constraints on the possible keys that can be used. 

---

I may return to this in future. Omit, Pick and Index are due for an overhaul to simplify their implementations, and where TypeBox will focus more on implementing schema level Pick/Omit parameters (treating the string[] signature as a DX overload)

```typescript
const T = Type.Object({ x: Type.Number(), y: Type.Number() })

// This will be the defacto way to Omit properties
const O = Type.Omit(T, Type.Union([
  Type.Literal('x'),
  Type.Literal('y'),
]))

// This will be the DX friendly way to Omit - where inference 
// of 'x' and 'y' may be brought back for this signature only.
const O = Type.Omit(T, ['x', 'y'])
```

Hope this brings some insight
Cheers
S
