### ISSUE TITLE
How to check if a schema conforms?

### ISSUE THREAD

**Issue by Qrokqt** [sinclairzx81/typebox#877]
I'm looking for a way to pass a schema to a function and have typescript throw an error if the schema doesnt conform to a type, is this possible?

```
// not sure how to represent this in TypeBox
interface ValidSchema {
  [key: string]: string;
}

function doSomething<T extends ValidSchema>(arg1: T) {
}

//good
doSomething(Type.Object());
doSomething(Type.Object({
  foo: Type.String(),
  bar: Type.String(),
}));

//bad
doSomething(Type.Number());
doSomething(Type.Object({
  foo: Type.Number(),
});
doSomething(Type.Object({
  foo: Type.Object({
    bar: Type.String(),
  }),
}));
```

**Comment by sinclairzx81** [comment]
@Qrokqt Hi, try the following...

[TypeScript Link Here](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUHkBGAVhgMYw7IDKMUwAdgOZwC+cAZlBCHAOQACAZ3okANgENgUAPQx0GfBAAePAFArZmOAEERIiAHcMAEzgBePEVIwAPEgDaAawyoAXHAE16DALpuqnxhYAPjU2AFc6MmAIOjgjCEouDBgACy9rZDgMRRgMOiMBbV0DYyCACgESFIwQMT8ASkQ4KQAqOAA6TrgWqRY1KSkGCAgjFXjEkGS0xjK0THaCYjIyhGZ6+oBuMYSk1K9ZuQXLZYQVOHZhv0PqWhn6rDO4fDEoK-mb-fuVNc3+qWfRuNdtMGAd5gA5MIgfAYKBldZbIGTPYzOYYI5LGArR5sS4oQ6Q6Gw+EPNaInbIkFg9GLKzY864iBvGnHLGnc7nZ6vfHvAKgr7nNakhFAA)

```typescript
import { Type, TObject, TString } from '@sinclair/typebox'

type Allowed = TObject<{ [key: string]: TString }>

function doSomething<T extends Allowed>(schema: T) { /* ... */ }

//good
doSomething(Type.Object({}));
doSomething(Type.Object({
  foo: Type.String(),
  bar: Type.String(),
}));

//bad
doSomething(Type.Number());
doSomething(Type.Object({
  foo: Type.Number(),
});
doSomething(Type.Object({
  foo: Type.Object({
    bar: Type.String(),
  }),
}));
```
Hope this helps
S

**Comment by Qrokqt** [comment]
Perfect, thanks!

**Comment by photz** [comment]
Unfortunately this is not a general solution. I'm trying to define a `SchemaFor<T>` but even the simplest attempt runs into a "type instantiation is excessively deep and possibly infinite" error.

This is what I tried:
```typescript
type SchemaFor<T> = T extends string ? ReturnType<typeof Type.String>
  : T extends number ? ReturnType<typeof Type.Number>
  : T extends boolean ? ReturnType<typeof Type.Boolean>
  : T extends object ? TObject<{ [P in keyof T]: SchemaFor<T[P]> }>
  : TSchema;
```
