### ISSUE TITLE
Composite Union type does not work

### ISSUE THREAD

**Issue by pkuczynski** [sinclairzx81/typebox#894]
I am defining my type as:

```ts
const pagination =  Type.Object({
  page: Type.Optional(Type.Number({  minimum: 1,  default: 1 })),
  size: Type.Optional(Type.Number({  minimum: 1,  default: 10 })),
})

const query = Type.Composite([
  pagination,
  Type.Union([
    Type.Object({
      categoryId: Type.Number()
    }),
    Type.Object({
      name: Type.String()
    })
])
```

and in the result I am getting:

```
 TObject<{
    page: TOptional<TNumber>
    size: TOptional<TNumber>
}>
```

like if it would be ignoring the `Union` part. What I was expecting to get as a JSON schema is (as in this [example](https://ajv.js.org/json-schema.html#unevaluatedproperties)):

```json5
{
  type: "object",
  properties: { page: { type: "number" }, size: { type: "number" }},
  anyOf: [
    {
      required: ["categoryId"],
      properties: { categoryId: { type: "number" }}
    }
    {
      required: ["name"],
      properties: { name: { type: "string" }}
    }
  ]
}
```

This is important as otherwise the defaults in `pagination` would throw at ajv when `strict: true` is used (my initial attemp was to use `Type.Union` of `Type.Composite` from `pagination` and variant of other query params ).

I am using `"@sinclair/typebox": "^0.32.31"`.

**Comment by sinclairzx81** [comment]
@pkuczynski Hi,

This is a known limitation that should be resolved in future revisions. You can work around this limitation by authoring the types slightly differently. As follows.

[TypeScript Link Here](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUFJIR2LeAAUCAcw5Fg8uAF4UwgHQB5EQCsMJGAAoEUuHDBqMALn2ZjYYvIJcradwByAK4gIhhQNvYgHKAhrgCMOHAAJhhUBEFcMAkUAJS5WHZwbABeLm4YHl7sPn6GwaHhkXDR7LEgCUmp6ZnZcPEADHkFUuS5svKKcCrqNdUA6sAwABYBBCAYuhUGAMJ0kGwwGFYA2jMa1Tj+lSbmljZFNRuu1wb4UByqVuNjALrjcgUyjUFy07EWKx2RAwqmgqAAksktq89uAIIdjmcQXMwVdDLcLNZbPYSNDYVAEckXvUQmEIj9cv8ZEJMHAAIpBcKoLb4TQkAA8LIwECo7M5FIAfHB+Pw4MsIAA3cITIFirnIwwAVTa8lORXOOPkENW62w+uxmiNS2WUKO5MpUn+QA)

```typescript
import { Type, Static } from '@sinclair/typebox'

const Pagination = Type.Object({
  page: Type.Optional(Type.Number({  minimum: 1,  default: 1 })),
  size: Type.Optional(Type.Number({  minimum: 1,  default: 10 })),
})
const PaginationWithName = Type.Composite([Pagination, Type.Object({
  name: Type.String()
})])
const PaginationWithCategoryId = Type.Composite([Pagination, Type.Object({
  categoryId: Type.Number()
})])

type Query = Static<typeof Query>
const Query = Type.Union([
  PaginationWithName,
  PaginationWithCategoryId
])
```
> What I was expecting to get as a JSON schema is (as in this [example](https://ajv.js.org/json-schema.html#unevaluatedproperties)):

Unfortunately, the combination of `object` and `anyOf` (mixed as a singular schema as per your code snippet) falls outside the documented schematics generated by TypeBox. The preferred solution would be to have TypeBox automatically transform the schematics into the `Query` structure shown above. This would be analogous to the following TypeScript example.

[TypeScript Link Here](https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgApwOajmYB7EZAbwChlzkAHTCAfgC5kQBXAWwCNoyKBnYALzqMWHLgF8SAeknIwAC2A9ki2XJQ85cSigCeeZgHIoKODwDWoDLLzIExnBBJgd25AEVm0HcgC8aTNi4BMgAZMgAFBTI3ORETHCsEIw8YFCWyGLIAD5RuTHEtg4YeFA6AJIAJsJsnFAZJACUJFIy8ioq8uqars7a7HgAHsgQAG5wADbMDkoA7sDytnislHh8kE4uKAByBAAiiqnA7MyQFR5evgUA2gDSyoRmEHow7p6lALqM56W37xnI0mQcjwIy4LVU7VmmjAsk2-SGIAgEAqSjANgqeA2rgAomNJg4ADwAFQAfJc4rd7shHs9kETPnTfv8wkQJFiUPsUmljqdvt4-LiJlNIAS+WTAcDQVAgA)

```typescript
interface Pagination {
    page?: number
    size?: number
}
// this is the shape you're asking to create
type Query = Pagination & (    
    { name: string } |         
    { categoryId: number }
)

// this is the shape typebox evaluates with Composite
type NonDistributedQuery = { [K in keyof Query]: Query[K] } // hover

// this is what typebox needs to do
type Evaluate<T> = { [K in keyof T]: T[K] } & {}

type DistributedQuery = Evaluate<Query> // hover
```
Above, the `Evaluate<T>` type will be added to TypeBox specifically for this case. The Evaluate function will take care of transforming the Intersect/Union into the flattened type `DistributedUnion` above. Unfortunately, this type isn't ready yet, so you will need to refactor the types shown in the previous example in the meantime.

Hope this helps
S

**Comment by sinclairzx81** [comment]
@pkuczynski Hi,

Might close up this issue for now as this issue is non-actionable on the current revision. In the interim, would recommend refactoring the types as follows.

```typescript
import { Type, Static } from '@sinclair/typebox'

const Pagination = Type.Object({
  page: Type.Optional(Type.Number({  minimum: 1,  default: 1 })),
  size: Type.Optional(Type.Number({  minimum: 1,  default: 10 })),
})
const PaginationWithName = Type.Composite([Pagination, Type.Object({
  name: Type.String()
})])
const PaginationWithCategoryId = Type.Composite([Pagination, Type.Object({
  categoryId: Type.Number()
})])

type Query = Static<typeof Query>
const Query = Type.Union([
  PaginationWithName,
  PaginationWithCategoryId
])
```
If you have any follow up questions on the above, feel free to reply on this thread.

All the best!
S
