### ISSUE TITLE
Field descriptions

### ISSUE THREAD

**Issue by riquenunes** [sinclairzx81/typebox#9]
Is it possible to use typebox to generate JSON schemas with field descriptions?

For example:
```json
"properties": {
    "productId": {
      "description": "The unique identifier for a product",
      "type": "integer"
    }
  }
```

**Comment by sinclairzx81** [comment]
Hi. I have just pushed an update to allow for this (typebox npm version `0.9.7`). I have added documentation for this use case in the readme. See [User Defined Schema Properties](https://github.com/sinclairzx81/typebox#user-defined-schema-properties).

Note: To allow for custom properties across all types. The signatures of `Type.Union(...)`, `Type.Intersect(...)` and `Type.Tuple(...)`, have changed. 

```typescript
// before
const T = Type.Tuple(Type.String(), Type.Number()) // [string, number]

// now
const T = Type.Tuple([Type.String(), Type.Number()])

// allowing for
const T = Type.Tuple([Type.String(), Type.Number()], { desc: 'a tuple' })

```

Hope that helps !

**Comment by riquenunes** [comment]
thanks! that's exactly what I needed!

**Comment by rattrayalex** [comment]
The linked section no longer appears in the readme, and I don't find any mention of `title`, `description`, or [other annotations allowed in the json-schema spec](https://json-schema.org/understanding-json-schema/reference/generic.html#id2). 

Was this feature removed?

**Comment by sinclairzx81** [comment]
@rattrayalex You can pass additional options (including `title` and `description`) on the last argument for any given type. For example.

```typescript
const T = Type.String({ title: 'String', description: 'A basic string type' })

const T = Type.Object({
   email: Type.String({ format: 'email' }),
   address: Type.String({ description: 'US street address' })
}, {title: 'Customer', description: 'A customer record' })
```

TypeBox still provides definitions for all the known JSON schema options (so you should see these using intellisense), but you can specify your own custom properties if you wish. All properties will be applied to the underlying schema, except for properties required by the underlying type (which will be ignored, or more specifically overwritten when constructing the schema).

Hope that helps.
S

**Comment by rattrayalex** [comment]
Got it! Very helpful. Can you add custom properties this way as well, like `'x-mycompany-myannotation': "foo"`?

Would a PR adding this to the README be welcome?
