### ISSUE TITLE
Default values in nested objects are not generated

### ISSUE THREAD

**Issue by landrygeiger** [sinclairzx81/typebox#926]
Hello, when I try to use `Value.Default` to generate the default values for a schema, properties on nested objects within the schema do not have their default values generated.

```typescript
const TestSchema = Type.Object({
  a: Type.Object({
    b: Type.String({ default: null }),
  }),
  c: Type.String({ default: null }),
});

const T = Value.Default(TestSchema, { a: {} }); // { a: {}, c: null }
```

As you can see, the root level properties are generated, but not the nested ones.

Thanks!

**Comment by kade-robertson** [comment]
You can solve this by specifying an empty object as the default for the `Type.Object` components:

```ts
const TestSchema = Type.Object({
  a: Type.Object({
    b: Type.String({ default: null }),
  }, { default: {} }),
  c: Type.String({ default: null }),
}, { default: {} });
```

**Comment by sinclairzx81** [comment]
@landrygeiger Hi, 

As per @kade-robertson comment, TypeBox uses a top down order of initialization when using default values. You will need to specify defaults at a higher level such that the lower level properties can be initialized.

Will close this one off as working as expected.
Cheers
S
