### ISSUE TITLE
Is there a way to 'spread' referenced type?

### ISSUE THREAD

**Issue by anri-asaturov** [sinclairzx81/typebox#93]
HI, would appreciate help finding a way to spread/flatten referenced object into another type.

To better explain what I'm trying to achieve, say, I have this definition:
```
type EmailAndPass = {
  email: Type.String(),
  pass: Type.String()
}
```
and I'd like to reuse it in several other types, but instead of referencing it as a property with 'email' and 'pass' nested in it, I want to flatten it, so the resulting type is an equivalent of:
```
type SignupRequest = {
  name: Type.String(),
  email: Type.String(),
  pass: Type.String()
}

type SomeOtherRequest = {
  someProp: Type.String(),
  email: Type.String(),
  pass: Type.String()
}
```

I know I can just reference `email` and `pass` properties one by one, but I'd like to avoid that.
So hypothetical code could look something like
```
type SomeOtherRequest = {
  someProp: Type.String(),
  ...Type.Ref(EmailAndPass) // this is obviously an error currently
}
```

**Comment by sinclairzx81** [comment]
@anri-asaturov Hi. Yes, you can use an `Type.Intersect(...)`. It mirrors TypeScript's `A & B` intersection types. Example below and [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZQzHACiIXlwCC7ACYAFAixZwAvHkLESAHgUYIVZauAbtegwD5ZJCOxbwVazbr6hiZomAB0APIiAFYYJDAAFAiycHAYDlwAXCjCYfhQHADmCQCUWClwYEHZoRh5MAXsxSWy5C1yMtZ4dBgRMAAWGFAAShgAjgCuGD7GpkSkVsK23SC9A0Ojk9Mw7jKe3vC4PX2DI+NTMyG5AJLsMEMscYkA2n6OAS4sOLWRMU9JFRYPR0tDANVy+SKpXKMjaAF12rJZFQJpxiF44PcfABGBIANwIXCm2TeTkCBhKiAqcH4-Ex2zgBKJGEqoMMpww1NpjMJUzCrWRqPiwAxWJgACZ8byMNkjqsThtzttKckZKkaXSxTzmayIGB2UNOWrUtymXzWkA)

```typescript
import { Type, Static } from '@sinclair/typebox'

type EmailAndPass = Static<typeof EmailAndPass>
const EmailAndPass = Type.Object({
  email: Type.String(),
  pass: Type.String()
})

type SomeOtherRequest = Static<typeof SomeOtherRequest>
const SomeOtherRequest = Type.Intersect([EmailAndPass, Type.Object({
  someProp: Type.String(),
})])


function test1(value: EmailAndPass) {
   // test value props here
   // value.
}
function test2(value: SomeOtherRequest) {
   // test value props here
   // value.
}
```

Hope that helps
Cheers
S

**Comment by anri-asaturov** [comment]
Thank you so much
