### ISSUE TITLE
How to do a cross field validation?

### ISSUE THREAD

**Issue by askareija** [sinclairzx81/typebox#934]
Hi!, i have a question. I'm using elysia and i know that elysia using typebox for validation. I have validation code like this:

```typescript
export const authRequestVerificationCodeValidation = {
  body: t.Object({
    contact: t.Union([
      t.String({ format: "email" }),
      t.String({ minLength: 8 }),
    ]),
    sendMethod: t.Union([t.Literal("email"), t.Literal("whatsapp")]),
  }),
};
```

Is there a way i can validate if the `sendMethod` field is email, then contact field validation must be `t.String` with email format, else if whatsapp then the validation is `t.String` with minLength of 8?

Thanks

**Comment by sinclairzx81** [comment]
@askareija Hi,

TypeBox doesn't have cross field validation as it's not well represented in the Json Schema specification. However you can reimplement this type in the following way to make use of TypeScript [discriminated unions](https://basarat.gitbook.io/typescript/type-system/discriminated-unions) (which is supported in TypeBox)

[TypeScript Link Here](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwIYGc4wA0cAyjNjMAMZwC+cAZlBCHAOQACuwAdlQDbZgUAPQx0GAEYQAHmwBQ8jDMiwCEuAEEArjAAWAJQwBHbRlwwAahijAG1CsAg80mOAF5S5SlQA84zAgGLV1DEzMLa1t7KkdnVwwAPiUVaHgqZwsQ-SNTcysbOwdKeI1PGAA6AFUeJx4ACgBteTgCCoB5SQArDCoYeqQW1rhcDB4AEwBZDH0IcYAuNoAZYBgbbH56tgwQIX42AEpiYZEROHHgXCpbEF4KaDgh1oyecj7FyrJbHgBzAcZoLsYIttrtgPs6AchrQjkNKp0en1-k8RmMpjM9HMPhUVmsoBstgB3PQUXDYMBgQ7EU7nS7XUB3GDQFEvN7AtpfXh-JC3HhLMY-fSLAAckOhsIAugcgA)

```typescript
import { Type as t, Static } from '@sinclair/typebox'

export type AuthRequestVerificationType = Static<typeof AuthRequestVerificationType>
export const AuthRequestVerificationType = t.Union([
  t.Object({ 
    sendMethod: t.Literal('email'),    // discriminator
    contact: t.String({ format: 'email' })
  }),
  t.Object({ 
    sendMethod: t.Literal('whatsapp'), // discriminator
    contact: t.String({ minLength: 8 })
  }),
])
```
Hope this helps
S

**Comment by sinclairzx81** [comment]
Just as follow on addendum, for your particular case, the specification does support conditional schematics.

```typescript
import { Type, Static } from '@sinclair/typebox'

export const T = Type.Object({
    x: Type.Union([
        Type.Literal(1),
        Type.Literal(2),
    ]),
}, {
    if: Type.Object({ x: Type.Literal(1) }),
    then: Type.Object({ y: Type.Literal(3) })
})

// if x === 1 expect { x: 1, y: '...' }
// if x === 2 expect { x: 2 }
```
However the TypeBox compiler infrastructure doesn't currently support these kind of schematics as there are difficulties reconciling the appropriate static type (although the above schematic is supported in Ajv and other standard validators). As Elysia is backed by the TypeBox TypeCompiler, the recommendation is to use the Discriminated Union type above.

Cheers
S

**Comment by askareija** [comment]
Ah i see, thanks! i'll try this
