### ISSUE TITLE
empty tuple cause error

### ISSUE THREAD

**Issue by renzholy** [sinclairzx81/typebox#94]
I'm using 0.20.1

Error occurs when I use `Type.Tuple([])` to validate `[]`

```
schema is invalid: data/items must be object,boolean, data/items must NOT have fewer than 1 items, data/items must match a schema in anyOf
```

**Comment by sinclairzx81** [comment]
@renzholy Hi. That's an interesting bug. TypeBox generates the following for an empty tuple.

```typescript
{
  "type": "array",
  "items": [],
  "additionalItems": false,
  "minItems": 0,
  "maxItems": 0
}
```
This should be valid JSON Schema. You can actually test it by copy and pasting the above into https://www.jsonschemavalidator.net/. 

I've pushed a patch for this on `@sinclair/typebox@0.20.3` that generates the following when creating an empty tuple. I think there may have been changes recently to AJV with respect to how it handles `items` on the draft `2020` implementation. The following should make AJV happy.

```typescript
{
  "type": "array",
  "minItems": 0,
  "maxItems": 0
}
```
Let me know if that solves things your side. Thanks for letting me know.
Cheers
S

**Comment by renzholy** [comment]
Thanks! I noticed that you always reply in time for all the issues and PRs. That's why I choose typebox instead of io-ts 😄

**Comment by sinclairzx81** [comment]
@renzholy Hey, all good :) Will close of this issue. Thanks for reporting !
