### ISSUE TITLE
Advice to compose types

### ISSUE THREAD

**Issue by saxomoose** [sinclairzx81/typebox#951]
Thanks a lot for this library.

I prefer the `Type.Composite()` api over `Type.Intersect()` to compose schemas together. However, the function can only compose types of `TObject` as explained in #939. In order to circumvent this problem, is it sustainable to work as follows:

```typescript
const HasEmail = Type.Object({ email: Type.String({ format: "email" }) })
const HasPhone = Type.Object({ phone: Type.String() })
const Contactable = Type.Object(Type.Composite([HasEmail, HasPhone]).properties, { $id: "Contactable" })
const NaturalPerson = Type.Composite([
    Type.Object({
        givenName: Type.Array(Type.String()),
        familyName: Type.Array(Type.String()),
        gender: StringEnum(["Male", "Female", "Unknown"]),
    }),
    Contactable
], { $id: "NaturalPerson" })
```

There is perhaps a more straightforward approach.

**Comment by sinclairzx81** [comment]
@saxomoose Hi,

Composite types will always return TObject types, So you don't need to wrap Contactable in an Object (as it already is one). Consider the following.

```typescript
const HasEmail = Type.Object({ email: Type.String({ format: "email" }) })
const HasPhone = Type.Object({ phone: Type.String() })
const Contactable = Type.Composite([HasEmail, HasPhone], { $id: "Contactable" })

// ^ hover this variable
//
// const Contactable: TObject<{
//    email: TString;
//    phone: TString;
// }>

const NaturalPerson = Type.Composite([
  Contactable,
  Type.Object({
    givenName: Type.Array(Type.String()),
    familyName: Type.Array(Type.String()),
    gender: StringEnum(["Male", "Female", "Unknown"]),
  }),
], { $id: "NaturalPerson" })
```
As above, it can be helpful to hover over the return variable for computed types (the Contactable variable in this case) and see what the type is. TypeBox computes both schematics and types representing those schematics when you compose, so you can use this type information to get an idea what the schematics are (and how they can compose elsewhere)

Hope this helps :)
S

**Comment by sinclairzx81** [comment]
@saxomoose Heya,

Will close off this issue for now. But if you have any other questions, feel free to ping on this thread.

Cheers!
S

**Comment by saxomoose** [comment]
Thank you for the prompt reply.
