### ISSUE TITLE
Unknown format 'email' after update

### ISSUE THREAD

**Issue by nickfla1-mxm** [sinclairzx81/typebox#967]
## Description

We have recently updated form `0.29.2` to `0.32.0` and the formatting of strings has broken.

I have looked around the changelogs but I couldn't find anything regarding this change. I could replicate it on an empty project as well.

## Example

```ts
import { Type } from '@sinclair/typebox'
import { TypeCompiler } from '@sinclair/typebox/compiler'

const A = Type.Object({a: Type.String({format: 'email'})})

const tc = TypeCompiler.Compile(A)

for (const err of tc.Errors({a: 'email@gmail.com'})) {
  console.log(err)
}
```
#### Output
```
{
  type: 49,
  schema: { format: 'email', type: 'string', [Symbol(TypeBox.Kind)]: 'String' },
  path: '/a',
  value: 'email@gmail.com',
  message: "Unknown format 'email'"
}
```
#### Expected result
No logs, since the string is a valid email.

**Comment by sinclairzx81** [comment]
@nickfla1-mxm Hi,

TypeBox requires all formats be registered before use. This functionality hasn't changed between 0.29.x and 0.33.x, (although I would have expected previous versions to alert with "unknown format")

To use a format (i.e. email), you will need to register it first (you can find examples of common formats [here](https://github.com/sinclairzx81/typebox/tree/master/example/formats)), the following is a ajv compatible email checker.

```typescript
import { Type, FormatRegistry } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// -------------------------------------------------

const EmailExpression = /^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i

FormatRegistry.Set('email', (value) => EmailExpression.test(value)) // required

// -------------------------------------------------

const Email = Type.String({ format: 'email' })

const A = Value.Check(Email, 'user@domain.com')

const B = Value.Check(Email, 'not an email')

console.log(A, B) // true false
```

TypeBox may introduce a set of built in formats in later revisions (that would need to conform to a variety of RFC specifications). But for now, you need to specify them explicitly. It's a similar story with `ajv` + `ajv-formats`. 

Hope this helps
S

**Comment by nickfla1-mxm** [comment]
It indeed helped! Thanks!

Maybe it's a little confusing that the `format` property in `String` is typed in such way that it suggests any value at all since those formats are not registered by default.

**Comment by sinclairzx81** [comment]
@nickfla1-mxm All good :)

> Maybe it's a little confusing that the format property in String is typed in such way that it suggests any value at all since those formats are not registered by default.

Ah, Typebox did actually change the TS specific type for String where it removed the generic argument for Format. For some history, there was some considerations around using the format as a way to `__brand` a string on inference, or potentially repurposing the generic argument to store template literal patterns for later inference. Both of these were implemented via other means, which lead to the generic Format on String being dropped (simplifying String and moving complexity elsewhere)

The following are relevant to 0.33.0.

### Branded Types

```typescript
// Branded / Nominal types can be constructed by wrapping a type in Unsafe. The reasoning here
// is that the `__brand` property is a phantom property only used in inference and do not
// represent the schematics.

const T = Type.Unsafe<string & { __brand: 'email' }>(Type.String({ format: 'email' }))

type T = Static<typeof T>  // type S = string & { __brand: "email"; }
```

### Template Literal Types

```typescript
// Template Literal types were given their own type separate from String. 

const T = Type.TemplateLiteral('prop${A|B|C}')

type T = Static<typeof T> // type T = "propA" | "propB" | "propC"
```
So these constitute the inference changes to String and related types between 0.29.0 and 0.33.0. The runtime FormatRegistry (or TypeSystem.Format) format registration requirement remains largely unchanged however.

---

Will close of this issue for now, but if you have any other other questions, feel free to ping on this thread.
All the best
S
