### ISSUE TITLE
Type.Omit() on Type.Ref() fails

### ISSUE THREAD

**Issue by velsa** [sinclairzx81/typebox#97]
I need to use part of one schema in another schema and I'm using the `Type.Ref()` for that:

```js
import { Type } from '@sinclair/typebox'

const fullObj = Type.Object({
    prop1: Type.String(),
    prop2: Type.String(),
}, {$id: "fullObj"})

const partObj = Type.Omit(Type.Ref(fullObj), ["prop2"])
```

On the last line typebox is throwing an error: `Cannot convert undefined or null to object`

I found a workaround by using another `Type.Object()`:

```js
const partObj = Type.Omit(Type.Object(Type.Ref(fullObj)), ["prop2"])
```

Is this the expected behavior or a bug?

**Comment by sinclairzx81** [comment]
@velsa Hi. Currently the TypeBox Utility Types `Type.Pick(...)`, `Type.Omit(...)`, `Type.Required(...)` and `Type.Partial(...)` are not supported with `Type.Ref(...)`. The `Type.Ref(...)` function is currently flagged as experimental, so have been waiting on community feedback before implementing more around this feature. 

To support referenced utility types, the TypeBox type builder will need to keep a `Map<ID, TSchema>` for each schema that contains an `$id`. When referencing, the utility type functions would need to inspect the map and pull the referenced schema from the map. Some of the schema resolution logic gets quite a bit more complicated in these cases, particularly for varying types, so have been deferring this work till I have a chance to sit down with it. I'm also a bit mindful of `JSON Pointer` references, and wondering if these should also be supported.

Will mark this as an `enhancement` but may not get a chance to look into this for some time.

Hope that helps
S

**Comment by sinclairzx81** [comment]
@velsa Hi, just to let you know, I have finally added support for this on `0.23.0`. The implementation follows essentially description above. Have updated the change log with information up this update that you can read about at the link below.

https://github.com/sinclairzx81/typebox/blob/master/changelog.md#0230

Will close off this issue but let me know if you run into any problems with the new functionality.
Cheers
S
