### ISSUE TITLE
Value.Convert does not seem to convert sometimes

### ISSUE THREAD

**Issue by firatoezcan** [sinclairzx81/typebox#990]
I've found a bit of inconsistency with Value.Convert when I attempted using it for my environment variables. The code that I ended up with for reproduction looks like this:

```js
const useVariable = true;
const value = useVariable ? { PROJECTS_DB_PORT: "5432" } : process.env;

console.log("Raw: ", Value.Convert(schema, value));
console.log("Destructure: ", Value.Convert(schema, { ...value }));
```

When I use a locally declared variable it converts it correctly with the output being:

```
Raw:  { PROJECTS_DB_PORT: 5432 }
Destructure:  { PROJECTS_DB_PORT: 5432 }
```

however when I want to use `process.env` it does not work and instead I get:

```
Raw:  { PROJECTS_DB_PORT: '5432' }
Destructure:  { PROJECTS_DB_PORT: 5432 }
```

This is fine-ish since I am not using Value.Convert heavily and can just destructure it first before moving on, but I thought that this could be something that is either a bug or works as intended but maybe necessites a few words in the documentation

**Comment by sinclairzx81** [comment]
@firatoezcan Heya,

Will close off this issue as there isn't anything to action here. Would recommend checking out the new Parse function though as it internally implements the Clone, Convert, Clean, Default pipeline. It should simplify reading out envs as well as help to reduce boilerplate. 

https://github.com/sinclairzx81/typebox#parse

Cheers!
S

**Comment by firatoezcan** [comment]
Ahhh this makes a lot of sense, I figured Convert didn't mutate the original object but maybe my testing was thrown off by the quirk with process.env.

Thanks for the help, Parse is way better than what I have right now 🙏

**Comment by jp319** [comment]
Following up on this, just wanted to share an update after digging into how `process.env` behaves here.

It looks like `Value.Parse` doesn't fully resolve the issue on its own, especially if you chain a `Value.Decode` right after it (like when using `Type.Codec` or `Type.Transform` fields):

```ts
const StringToNumber = Type.Codec(Type.String())
    .Decode((value) => Number.parseInt(value))
    .Encode((value) => String(value))

const CommaSeparatedArray = Type.Codec(Type.String())
    .Decode((value) => value.split(",").map((s) => s.trim()))
    .Encode((value) => value.join(","));

const EnvSchema = Type.Object({
        NODE_ENV: Type.Union([Type.Literal("development"), Type.Literal("production")]),
        PORT: StringToNumber,
        CLIENT_URLS: CommaSeparatedArray,
});

const parsed = Value.Parse(EnvSchema, process.env);  // Clone -> Convert -> Clean -> Default
const decoded = Value.Decode(EnvSchema, parsed);     // still silently passes values through

console.log(decoded.PORT, typeof decoded.PORT); // "3000" "string" - expected number
console.log(decoded.CLIENT_URLS, Array.isArray(decoded.CLIENT_URLS)) // "http://localhost:4321,http://localhost:5173" false - expected true
```

Spreading the object (`{ ...process.env }`) before either call still fixes it, just like the original workaround in #626. I also noticed this seems to conflict a bit with the answer in #1067, where `Value.Convert(Environment, process.env)` is shown working directly on raw `process.env`.

Might be worth adding a quick note in the `Value.Parse` docs to flag that `process.env` still needs a spread first.

Thanks for maintaining such a great library either way!

Edit:

typebox version: 1.3.9
