### ISSUE TITLE
Is there a way to coerce when creating a schema?

### ISSUE THREAD

**Issue by fdaciuk** [sinclairzx81/typebox#997]
Hi! What I'm trying to do is create a rule in schema to parse a value that is a boolean optional and turn it to a boolean at the end.

I know I can use `Value.Cast`, but I'm trying to do it inside of an object.

Example:

```ts
const User = Type.Object({
  // other properties ...
  emailVerified: Type.Optional(Type.Boolean()),
})
```

To make sure `emailVerified` is always a boolean, I use this:

```ts
const User = Type.Object({
  // other properties ...
  emailVerified: Type.Transform(Type.Optional(Type.Boolean()))
    .Decode(Boolean)
    .Encode(v => v),
})
```

Is there a way to do something like:

```ts
const User = Type.Object({
  // other properties ...
  emailVerified: Type.Transform(Type.Optional(Type.Boolean()))
    .Cast(Type.Boolean()),
})
```

or something like this, without using `Decode` and `Encode` all the time?

**Comment by sinclairzx81** [comment]
@fdaciuk Hi,

Rather than using Transform, you can try use defaults + Parse. Consider the following.

```typescript
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'

// -----------------------------------------------------------
// The Type
// -----------------------------------------------------------

const T = Type.Object({
  emailVerified: Type.Optional(Type.Boolean({ default: true }))
})

// -----------------------------------------------------------
// Standard Parsing
// -----------------------------------------------------------

const R1 = Value.Parse(T, {})                       // { emailVerified: true }
const R2 = Value.Parse(T, { emailVerified: false }) // { emailVerified: false }
const R3 = Value.Parse(T, { emailVerified: true })  // { emailVerified: true }

console.log(R1)
console.log(R2)
console.log(R3)

// -----------------------------------------------------------
// Coercion Also Supported
// -----------------------------------------------------------

const R4 = Value.Parse(T, { emailVerified: 'TRUE' })  // { emailVerified: true }
const R5 = Value.Parse(T, { emailVerified: 'false' }) // { emailVerified: false }
const R6 = Value.Parse(T, { emailVerified: 1 })       // { emailVerified: true }
const R7 = Value.Parse(T, { emailVerified: 0 })       // { emailVerified: false }

console.log(R4)
console.log(R5)
console.log(R6)
console.log(R7)
```
> Note that if you are using defaults, the wrapping the property in Type.Optional isn't necessarily required as Parse will always generate the value if the property is omitted. 

The Parse function internally calls to the Convert, Clean, Default, Transform functions on Value.*, if you are only interested in generating defaults, you can just call Default only.

```typescript
const R = Value.Default(T, {}) // { emailVerified: true }
```
Additionally, If you are constructing a custom validation pipeline, take a look at the internal TypeBox Parse implementation

https://github.com/sinclairzx81/typebox/blob/master/src/value/parse/parse.ts#L41-L68

You can replicate this code in your codebase to create application specific pipelines depending on your requirements (which may involve the use of Cast or other function)

Hope this helps
S

**Comment by fdaciuk** [comment]
Wow, I hadn't noticed the use of "default". This helps a lot, thank you @sinclairzx81 ❤️

**Comment by AshotN** [comment]
> // -----------------------------------------------------------
> // The Type
> // -----------------------------------------------------------
> 
> const T = Type.Object({
>   emailVerified: Type.Optional(Type.Boolean({ default: true }))
> })
> 
> // -----------------------------------------------------------
> // Standard Parsing
> // -----------------------------------------------------------
> 
> const R1 = Value.Parse(T, {})                       // { emailVerified: true }


@sinclairzx81 your example is not working for me. 

This is the type I get for R1
```ts
const R1: {
    emailVerified?: boolean | undefined
}
```

Version
`"typebox": "1.0.78",`
